### ISSUE TITLE
[Suggestion] Change hostname to cat /etc/hostname

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#100]
Referencing this line in distrobox-create: [`--hostname ${container_name}.$(hostname)`](https://github.com/89luca89/distrobox/blob/5f04416d4c3d2fbe7049814f49530e709bed7bd0/distrobox-create#L245).
Some systems may not have a hostname command in their path. That's why my suggestion is to change `$(hostname)` to `$(cat /etc/hostname)` or to make a check if the first one exists and use it accordingly.

**Comment by 89luca89** [comment]
Yep agree, will change it in next commit :+1:

**Comment by 89luca89** [comment]
Done as per commit https://github.com/89luca89/distrobox/commit/49a767e64cf467a16ed4268cd7368fa2befbeea3
