### ISSUE TITLE
[Suggestion] Document assemble configuration fields

### ISSUE THREAD

**Issue by maxgio92** [89luca89/distrobox#1006]
**Is your feature request related to a problem? Please describe.**

This is just a proposal to improve the documentation.

As an end-user, I would like to know in detail the goal of all the fields that can be specified in the configuration for the `assemble` command.

**Describe the solution you'd like**

Considering that they match the `create` command's flags, they could be linked to the [`create` synopsis](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md#synopsis).

**Describe alternatives you've considered**
To replicate `create` flags description in the `assemble` [Available options](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-assemble.md) section.

**Additional context**

NA.

**Comment by 89luca89** [comment]
Thanks @maxgio92 for the suggestion, this is implemented now :+1:
