### ISSUE TITLE
[Error] Distrobox does not work on latest SteamOS with podman-launcher: crun: [conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

### ISSUE THREAD

**Issue by JD-The-65th** [89luca89/distrobox#1007]
**Describe the bug**
On the latest SteamOS Preview, Distrobox (latest "next" version as of this issue) distrobox containers specifically will not launch.

**To Reproduce**
1. Use SteamOS Preview
2. Remove preinstalled Distrobox and Podman
3. Install distrobox and podman-launcher
4. Make a distrobox container and run it

**Expected behavior**
I expected the distrobox container to load

**Logs**
[log.log](https://github.com/89luca89/distrobox/files/12836858/log.log)

**Desktop (please complete the following information):**
 - Podman
 - Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.18.10
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64

 - distrobox: 1.5.0.2
 - SteamOS (preview)
 - curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --next --prefix /run/media/deck/25eaaa63-450f-4400-bf57-a1dee344c0f1/distrobox

**Additional context**
As observed by the logs, only distrobox is affected by this issue.

**Comment by JD-The-65th** [comment]
Okay, well, this is my screw up. I was using podman-launcher incorrectly, using a symbolic link to my SDCard thinking that would work. My bad.

**Comment by JuanJ67m** [comment]
I can not run SteamOS in Fedora 42 Silverblue with Distrobox.

I used:

```
wicho@fedora-jtm:~$   distrobox create \
  --image ghcr.io/linuxserver/steamos:latest \
  --name SteamOS \
  --unshare-all \
  --home ~/SteamOS \
  --pre-init-hooks "sudo pacman -R --noconfirm opencl-mesa clang-libs lib32-opencl-mesa ; true"
 
Creating 'SteamOS' using image ghcr.io/linuxserver/steamos:latest	 [ OK ]
Distrobox 'SteamOS' successfully created.
To enter, run:

distrobox enter SteamOS


wicho@fedora-jtm:~$ distrobox enter SteamOS
Starting container...                   	
**Container Setup Failure!**
```
