### ISSUE TITLE
[Error] ERROR: Invalid flag '--unshare-all'

### ISSUE THREAD

**Issue by raldone01** [89luca89/distrobox#1008]
**Describe the bug**
`distrobox/docs/useful_tips.md` mentions the `--unshare-all` flag.
It seems to no longer exist.

**To Reproduce**
Run the command mentioned in the documentation:
```
distrobox create --root \
  --image registry.opensuse.org/opensuse/distrobox:latest \
  --additional-packages "systemd docker" \
  --init \
  --unshare-all
```

**Expected behavior**
The sample command from the documentation should work.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? `podman`
 - Which version or podman, docker or lilipod? `podman version 4.7.1`
 - Which version of distrobox? `distrobox version: 1.5.0.2`
 - Which host distribution? `arch`
 - How did you install distrobox? `yay -Sy distrobox`

**Comment by misobarisic** [comment]
[#985](https://github.com/89luca89/distrobox/issues/985)
