### ISSUE TITLE
[Suggestion] Removing the need for --name

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#101]
**Describe the solution you'd like**
Since `distrobox-enter`, `distrobox-create` and `distrobox-rm` require `--name/-n` to be specified, wouldn't it be a quality of life improvement to make `distrobox-create -n <name> -i <image>` the same as `distrobox-create <name> -i <image>`, therefore technically making the _flag-less_ input text the container name.

**Comment by 89luca89** [comment]
like `distrobox enter NAME` for example and so on right?

I'm not against it at all I like it, I just want to implement in a way that it's not positional (so no $2, $3 etc etc) and that works well for all the flags

:+1:  from me

**Comment by misobarisic** [comment]
Yeah, of course. It should not depend on its position. Hard coding $2, $3... would not be acceptable.

**Comment by 89luca89** [comment]
Started a PR for this, seems working as intended but let's have more eyes on it :smile:

**Comment by alcir** [comment]
It works so far.

**Comment by 89luca89** [comment]
much better now it is quite more natural to use it this way :+1:
