### ISSUE TITLE
Cannot enter a distrobox without root

### ISSUE THREAD

**Issue by ThoriumTextile** [89luca89/distrobox#1012]
Please, before opening a bug:

- [x] make sure you've read the documentation.
- [x] Ensure there isn't already an open issue about this.
- [x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I can create instances just fine, but I cannot enter into them unless I specify the `--root` flag

**To Reproduce**
1. Create any distrobox (i.e. `distrobox create -i ubuntu -n ubuntu`
2. Attempt to enter it as a regular user
3. `Error: unable to start container "a7a543824eba5e4ec9c2749d7fcb94a4980a3e42b644e9f0fb607155d82d902f": crun: make /home/[...]/.local/share/containers/storage/overlay/56c744aa701c173387f662d8f6272a55afe81fea63bcbffab2aa73374ba73793/merged private: Permission denied: OCI permission denied`

**Expected behavior**
Being able to enter the created container without root.

**Logs**
N/A, podman logs -f <container> returns no output

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? `podman`
 - Which version or podman, docker or lilipod? `4.7.1`
 - Which version of distrobox? `1.5.0.2`
 - Which host distribution? `Arch Linux`
 - How did you install distrobox? `sudo pacman -S distrobox`

**Comment by ThoriumTextile** [comment]
> I had this issue, then I read this. [Run Docker without root](https://docs.docker.com/engine/install/linux-postinstall/)

This works but i'd really rather stick with podman. Should I open an issue there?

**Comment by rainwashed** [comment]
I wouldn't be too sure about podman as I've never used it before, but possibly the same theory run without needing root privileges.

**Comment by profetik-777** [comment]
> > I had this issue, then I read this. [Run Docker without root](https://docs.docker.com/engine/install/linux-postinstall/)
> 
> This works but i'd really rather stick with podman. Should I open an issue there?

Maybe not so much "open an issue" but learn more about the nuances of Podman.

They have a great discord group you can check out. 

P.s. Should you consider this a bug? I am able to enter a distrobox fine with Aeon OS. Maybe this is thing w/ arch based systems only. 

I recommend creating a VM and testing on another distro that is not arch to confirm for yourself.

**Comment by 89luca89** [comment]
This is not a distrobox bug
