### ISSUE TITLE
[Error] distrobox-assemble --name adds too many additional_packages.

### ISSUE THREAD

**Issue by hirnidrin** [89luca89/distrobox#1013]
Please, before opening a bug:

- [x] - make sure you've read the documentation.
- [x] - Ensure there isn't already an open issue about this.
- [x] - Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
`distrobox assemble --name box-x` does not work correctly with multiple `[box-n]` sections in distrobox.ini: `additional_packages` belonging to individual sections are added up -> later boxes add all packages mentioned in earlier boxes.

**To Reproduce**

Define 2 boxes with different additional_packages
```
cd /tmp
cat distrobox.ini
[box1]
image=ghcr.io/ublue-os/ubuntu-toolbox:latest
replace=true
additional_packages="gh"

[box2]
image=ghcr.io/ublue-os/ubuntu-toolbox:latest
replace=true
additional_packages="nodejs npm"
```

Check dry run for full file -> ok, each box gets its correct additional packages.
```
distrobox assemble create --replace --file ./distrobox.ini --dry-run
 - Deleting box1... 
 - Creating box1... 
/home/arbeiter/.local/bin/distrobox-create --yes --name box1 --image ghcr.io/ublue-os/ubuntu-toolbox:latest --additional-packages " gh"
 - Deleting box2... 
 - Creating box2... 
/home/arbeiter/.local/bin/distrobox-create --yes --name box2 --image ghcr.io/ublue-os/ubuntu-toolbox:latest --additional-packages " nodejs npm"
```

Check dry run scoped for box2 -> wrong, box2 gets additional packages of both box1 and box2, see last line.
```
distrobox assemble create --replace --file ./distrobox.ini --dry-run --name box2
 - Deleting box2... 
 - Creating box2... 
/home/arbeiter/.local/bin/distrobox-create --yes --name box2 --image ghcr.io/ublue-os/ubuntu-toolbox:latest --additional-packages "  gh nodejs npm"
```

**Expected behavior**
The `--name` scoped box gets the additional packages of its definition, nothing else.

**Additional context**
I have located the error in the distrobox-assemble script, will submit a PR.

**Comment by 89luca89** [comment]
This is fixed now
