### ISSUE TITLE
[Suggestion]Possibility to mount a volume from inside the container after been created.

### ISSUE THREAD

**Issue by marcello-pietrobon** [89luca89/distrobox#1020]
Hello,

from the documentation

> [Mount additional volumes in a distrobox](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#mount-additional-volumes-in-a-distrobox)
> distrobox create supports the use of the --volume flag, as specified in the usage [HERE](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md)
> Simply use:
> distrobox create --name test --image your-chosen-image:tag --volume /your/custom/volume/path

I see that I can mount a volume only at the time of the creation of the container.

Is it possible to mount a volume after the container has been created?
I couldn't find an answer to this question.
If the answer is not, it would be great to have this possibility.
If the answer is yes, could this be explained in the [useful_tips](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md) page?

Thank you.

**Comment by marcello-pietrobon** [comment]
I have maybe to specify that I'm using an image for which something strange happens:
```
[me@Resolve_Centos_7_root ~]$ sudo mount | grep sda
/dev/sda1 on /run/host/mnt/dskw type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
```
but:
```
[mar@Resolve_Centos_7_root ~]$ ls -l /mnt/dskw/
total 0
```
while with all the others containers I have they see files and dirs inside such volume,
and when I do 

> $ sudo mount | grep sda

 in them, I get exactly the same result, that is the volume is successfully mounted and in the same way.

<br>
The feature request is still valid though, if volumes cannot be mounted after the container's creation.

**Comment by marcello-pietrobon** [comment]
Actually I realize now that even with the command

`distrobox create --root --name Resolve_Centos_7_root --image quay.io/centos/centos:7 --volume /mnt/dskw/
`
the problem persists.

Maybe a should do a separate question for this. S.v.p. let me know.

**Comment by 89luca89** [comment]
The mounts are available on host's `/run/host/mnt/`
