### ISSUE TITLE
[Suggestion] Create a "distrobox container"

### ISSUE THREAD

**Issue by osalbahr** [89luca89/distrobox#1021]
**Is your feature request related to a problem? Please describe.**

Can't use Distrobox on macOS.

- https://github.com/89luca89/distrobox/issues/36

**Describe the solution you'd like**

As a middle-ground, thoughts on using Distrobox in a container?

**Describe alternatives you've considered**

`podman exec -it fedora-rawhide /bin/bash` etc.

**Additional context**

This idea stems from the ability for [using Podman/Docker inside a Distrobox](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-podman-inside-a-distrobox). Does this mean it is possible to use "Distrobox inside a Distrobox" (only one level deep)? Idk, just a thought. Here is what I envision:

```console
[user:host] % podman run -it docker.io/distrobox/distrobox
[distrobox:distrobox] $ distrobox create -i fedora:rawhide
[distrobox:distrobox] $ [now i am using Fedora Rawhide]
```

I often want to quickly try to test something on multiple distros, and Distrobox is great for that. I am fine with just switching to my Fedora partition and use Distrobox as normal. I'm just curious of the possibility above. Doesn't have to be fully-featured.

**Comment by juhp** [comment]
+1

(FWIW seems one can use toolbox inside toolbox)

**Comment by 89luca89** [comment]
Granted, we now have a Containerfile for a distrobox image :+1: 

`podman run -ti --userns keep-id localhost/distrobox:latest`

**Comment by osalbahr** [comment]
> Granted, we now have a Containerfile for a distrobox image 👍
> 
> `podman run -ti --userns keep-id localhost/distrobox:latest`

I must be missing something:

```console
$ podman run -ti --userns keep-id localhost/distrobox:latest
Trying to pull localhost/distrobox:latest...
WARN[0000] Failed, retrying in 1s ... (1/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
WARN[0001] Failed, retrying in 1s ... (2/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
WARN[0002] Failed, retrying in 1s ... (3/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
```

**Comment by 89luca89** [comment]
> > Granted, we now have a Containerfile for a distrobox image 👍
> > `podman run -ti --userns keep-id localhost/distrobox:latest`
> 
> I must be missing something:
> 
> ```
> $ podman run -ti --userns keep-id localhost/distrobox:latest
> Trying to pull localhost/distrobox:latest...
> WARN[0000] Failed, retrying in 1s ... (1/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
> WARN[0001] Failed, retrying in 1s ... (2/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
> WARN[0002] Failed, retrying in 1s ... (3/3). Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused 
> Error: initializing source docker://localhost/distrobox:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
> ```

you need to build the image

inside the distrobox source folder do `podman build . -t distrobox`

then you'll have the image

I still haven't bothered to build and push it
