### ISSUE TITLE
[Error] Cannot mount ntfs volume on centos-7 container

### ISSUE THREAD

**Issue by marcello-pietrobon** [89luca89/distrobox#1023]
Using image quay.io/centos/centos:7

I don't see a mounted volume, which is an ntfs volume mounted with --make-shared

`/dev/sda1 on /mnt/dskw type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096)`

```
[me@Resolve_Centos_7_root ~]$ ll /mnt/dskw/
total 0
``` 

The command to create the volume was:
$ distrobox create --root --name Resolve_Centos_7_root --image quay.io/centos/centos:7 --volume "/mnt/dskw"

With other distros, Fedora, Roky Linux, etc. I don't have this issue in any way and I can easily see that volume.

As I really need a CentOS-7 distro I would like to understand and solve this.

Thank you

**Comment by stafpapa** [comment]
Same issue with manjaro Linux, after I did an update last week. It does not mount ntfs volumes automatically like it used to do.

**Comment by marcello-pietrobon** [comment]
I do too use archlinux distro.

**Comment by 89luca89** [comment]
Hi @marcello-pietrobon 
this works in other distros (guest) but specifically not on centos-7?

If that's the case it is probable that maybe come dependencies are missing?
