### ISSUE TITLE
Can't install any image besides default Fedora image

### ISSUE THREAD

**Issue by robertzo** [89luca89/distrobox#1024]
When I run: `distrobox create -n name -i image:archlinux-toolbox:latest` I keep on getting this error:

`Error: short-name "archlinux-toolbox:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"`

I tried this with ubuntu and arch with toolbox and without toolbox and get this exact same error.

I am running the latest version of distrobox installed via curl.

OS: Pop!_OS 22.04 (based of Ubuntu 22.04)

Container Manager: podman

The only time it works is if I leave out the image flag and do a default Fedora install: `distrobox create -n name`

**Comment by Martan404** [comment]
The command is wrong. **-i** should not include _image:_
Some containers can be searched and you only need to type the command like this `distrobox create -i archlinux -n name` but when I try with archlinux-toolbox is doesn't work. So use the full container path instead.

`distrobox create -n name -i quay.io/toolbx-images/archlinux-toolbox`

More containers and their names can be found here https://distrobox.it/compatibility/#containers-distros

Make sure you copy the correct path, like `quay.io/toolbx-images/archlinux-toolbox`

**Comment by robertzo** [comment]
Thank you so much. I have been searching and couldn't find any answer. All the articles tells me to use -i image:latest (example: -i archlinux:latest)
