### ISSUE TITLE
wget install on Mageia - can't enter container - container not running?!?

### ISSUE THREAD

**Issue by emsofo** [89luca89/distrobox#1025]
Is your feature request related to a problem? Please describe.
Installed Distrobox using instructions with wget script on Mageia Cauldron (development version) and also installed docker
When I create a container with systemd and libpam-systemd installed - and try distrobox enter - it tries to start but at the end I get:
Container Setup Complete:
Error response from daemon: Container "xxxxxxxxx" is not running

it shows up on the list when I do a "distrobox list" command

Use is in the docker group 

Only error I have seen in the log is:
+ find /usr/share/libalpm/scripts/*distrobox*.sh -delete
find: '/usr/share/libalpm/scripts/*distrobox*.sh': No such file or directory

Describe the solution you'd like
Trying to understand why the newly created container fails to start 

Describe alternatives you've considered
Unfortunately, Mageia is not one of the supported distros (I have made a formal request for them to package distrobox)

Additional context

**Comment by rrahl0** [comment]
please provide better (full) logs. use a pasteservice or formatting on github

**Comment by emsofo** [comment]
Here's the output 
[test.txt](https://github.com/89luca89/distrobox/files/13228226/test.txt)
[output.txt](https://github.com/89luca89/distrobox/files/13228228/output.txt)

**Comment by rrahl0** [comment]
which version of distrobox are you running? I am using 1.5.0.2 here and it works fine. (tbf I am on podman)

**Comment by emsofo** [comment]
Running also 1.5.0.2 - What distro are you using?  Maybe I should try Podman instead ?!?  Although Docker should work . . .

**Comment by rrahl0** [comment]
yes it should, sitting right now on Fedora 39.

**Comment by emsofo** [comment]
Fedora is officially supported - Mageia unfortunately not - so that may be the issue.  I asked the Mageia developers if they could package it - but they are tight on resources and it's not a priority.  Thought someone here could help troubleshoot using standard wget install . . .

**Comment by rrahl0** [comment]
well there is only so much I myself can help, but you could also look how much is "missing" to get mageia working and trying to get it supported.

**Comment by emsofo** [comment]
I looks like it installed fine from the wget script - but for some strange reason, after trying to create a new container - when I try to run it - it simply starts then stops again.  Can't find out why ?!?

**Comment by dnkmmr69420** [comment]
kt may be something with podman but idk for sure

**Comment by profetik-777** [comment]
> I looks like it installed fine from the wget script - but for some strange reason, after trying to create a new container - when I try to run it - it simply starts then stops again. Can't find out why ?!?

It is not officially supported, and given this is a volunteer based project - it is hard to expect the lead dev to help troubleshoot this for you. 

You will have to advocate and find someone to take this on for you if you yourself can't fill in the technical gaps required to chart a path forward to getting it working, or getting Mageia to supported. 

@89luca89  - think we should close this one.

**Comment by ozky84** [comment]
I use Mageia 9 and problem is Mageia docker images are out of date, only working right now is Mageia 8 image...
see this:
https://github.com/juanluisbaptiste/docker-brew-mageia/issues/32

**Comment by 89luca89** [comment]
Mageia is not a supported host distribution
Guest is working as expected on supported distributions

I'm closing this, if anyone is interested in officially supporting Mageia as an host, we'll discuss in another issue
