### ISSUE TITLE
Applications do not respect cursor theme on host OS [Error]

### ISSUE THREAD

**Issue by rainwashed** [89luca89/distrobox#1026]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Any visual application installed in a container does not respect the cursor theme of the host OS.

**To Reproduce**
1. Create a distro container

**Expected behavior**
The visual application have the same cursor theme as the host OS

**Logs**

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - Docker
 - Which version or podman, docker or lilipod?
 - Docker version 24.0.6, build ed223bc820
 - Which version of distrobox?
 - distrobox: 1.5.0.2distrobox: 1.5.0.2
 - Which host distribution?
 - EndeavourOS Linux
 - How did you install distrobox?
 - AUR

**Additional context**

Related to https://github.com/89luca89/distrobox/issues/745

**Comment by profetik-777** [comment]
This sounds like a wayland based thing, not a distrobox "bug". 

https://bbs.archlinux.org/viewtopic.php?id=285670 

Please verify this and report back when you get a chance.

**Comment by firefoxlover** [comment]
I am using a Podman Fedora39 Distrobox and installed Firefox there. My host is Fedora Kinoite KDE without Firefox installed, using the Breeze cursor theme.

I could need some help to 
- get the cursor to use the breeze theme (`breeze-cursor-theme` is installed but the default GNOME cursor is still used)
- get KDE Decorations in Firefox

**Comment by shenmo7192** [comment]
> I am using a Podman Fedora39 Distrobox and installed Firefox there. My host is Fedora Kinoite KDE without Firefox installed, using the Breeze cursor theme.
> 
> I could need some help to
> 
>     * get the cursor to use the breeze theme (`breeze-cursor-theme` is installed but the default GNOME cursor is still used)
> 
>     * get KDE Decorations in Firefox
> 
> 
> I already did that:
> 
> ```
> sudo dnf install -y breeze-cursor-theme
> 
> gsettings set org.gnome.desktop.interface cursor-theme 'breeze-cursor'
> ```
> 
> No change in Firefox

install the same cursor theme in the container can fix it
