### ISSUE TITLE
[Suggestion] Prevent duplicate desktop entries for local desktop files that have been exported

### ISSUE THREAD

**Issue by FSMaxB** [89luca89/distrobox#1028]
**Is your feature request related to a problem? Please describe.**
I'm using Jetbrains IDEs using the Jetbrains Toolbox utility. This utility creates it's own `.desktop` files in `$HOME/.local/share/applications`, which then show up in my list of applications, but if I start one of them, although it does run, it runs outside of the distrobox container, which means the entire development environment is missing (language runtimes, compilers etc.).

In order for it to run properly, I am using `distrobox-export --app`, but with that I end up with two desktop entries. One being the correct one (the exported one, running in the container), the other one being the one that runs directly on the host and it's extremely easy to accidentally start the wrong one.

My current workaround for this issue is to add `NoDisplay=true` to the original `.desktop` files so only the exported files show up. After every IDE update however, I need to run `distrobox-export` again and it will copy the `NoDisplay=true` into the exported desktop file, where I have to remove it again.

**Describe the solution you'd like**
Not sure what a proper solution would look like. One idea is to always remove `NoDisplay=true` in the desktop file that `distrobox-export` creates, maybe even automatically add `NoDisplay=true` to local `.desktop` files automatically.

Mostly I want to document the issue with my workaround and start a discussion on possible solutions.

**Describe alternatives you've considered**
Maybe it's an option to not map `.local/share/applications` from the host into the container at all so every distrobox has it's own. This way local `.desktop` files from inside the container won't show up on the host in the first place and could be exported like any other `.desktop` file.

**Comment by 89luca89** [comment]
This is simply because the home is the same between host and container

Just create the box with a custom home and this problem will not present anymore

**Comment by FSMaxB** [comment]
> Just create the box with a custom home and this problem will not present anymore

Yeah, but having it use my home is a feature that I really on here :sweat_smile:.

**Comment by 89luca89** [comment]
Using a custom home won't prevent you to access the host's home
It just sets $HOME to a different path, so that intellij will install/unpack there

Exported apps/bins will still be put in the host's home, and this will prevent duplicate entries
