### ISSUE TITLE
[Suggestion] Enable github discussions

### ISSUE THREAD

**Issue by Darin755** [89luca89/distrobox#1032]
Would it be possible to enable Github discussions for this repo? Having a place to ask questions and show our accomplishments would be nice.

### Describe the solution you'd like
I should be fairly easy to change this repos settings to enable discussions. This would allow for a place to post things that aren't formally structured or unrelated.

### Describe alternatives you've considered
I see that [issue #452](https://github.com/89luca89/distrobox/issues/452) is related but it seems that no answer was reached.

### Additional context
I would like a place to informally discuss distrobox. Github discussions seems like the place to do this.

**Comment by Aman9das** [comment]
@89luca89 Please consider, this will really help troubleshoot problems.

**Comment by 89luca89** [comment]
They are enabled already
