### ISSUE TITLE
[Discussion] /etc/hosts not overwriteable 

### ISSUE THREAD

**Issue by ptulpen** [89luca89/distrobox#1033]
Hello, 

I want to use distrobox-assemble to test ansible roles which modify /etc/hosts
Via default this is not possible, since it is write protected, but also **additional_flags="--no-hosts"** or **additional_flags="--no-hosts=true"** does not help (which does in pure podman)
I would like to have either a copy of /etc/hosts or a complete independend one 
Any ideas how to achieve this?

distrobox version is 1.5.0.2

**Comment by profetik-777** [comment]
Is there a reason why you wouldn't use recommendations/documentation related to testing anisble role testing? Just curious. 

https://ansible-development.readthedocs.io/en/master/test_ansible_roles/

Also see: https://ansible.jeffgeerling.com/

**Comment by 89luca89** [comment]
Hi @ptulpen 

You'll need to use `--unshare-netns` and `umount /etc/hosts` then you can do this

But I'd follow @profetik-777 recommendation and test with the proper tools
