### ISSUE TITLE
Kali Linux container fails to initialize, gives an error at installing basic packages[Error]

### ISSUE THREAD

**Issue by sid3425** [89luca89/distrobox#1034]
**Describe the bug**
When I try creating a Kali Linux container, it is able to pull the image and apply it normally, however it gives an error during the "Installing basic packages" step, and just exits the process.

**To Reproduce**
Enter into the created Kali Linux container

**Expected behavior**
The container should install the basic packages normally and the user should be inside the Kali Linux CLI.

**Logs**
```
podman logs -f kali
distrobox: Installing basic packages...
+ [ -n  ]
+ printf distrobox: Installing basic packages...\n
+ basename /bin/bash
+ shell_pkg=bash
+ [ bash = ash ]
+ [ 0 -ne 0 ]
+ command -v find
/usr/bin/find
+ command -v mount
+ command -v passwd
/usr/bin/mount
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ [ 0 -ne 0 ]
+ rm -f /etc/dpkg/dpkg.cfg.d/excludes
+ export DEBIAN_FRONTEND=noninteractive
+ apt-get update
Get:1 http://kali.download/kali kali-rolling InRelease
Err:1 http://kali.download/kali kali-rolling InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists...
E: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
Error: An error occurred
+ [ 100 -ne 0 ]
+ printf Error: An error occurred\n
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 Podman
 - Which version or podman, docker or lilipod?
 4.3.1
 - Which version of distrobox?
 1.5.0.2
 - Which host distribution?
 Ubuntu 23.10
 - How did you install distrobox?
 Pacstall(the apt package gives the same issue as well)

**Additional context**
This problem does not occur when using other container distros, it only occurs when trying to use Kali Linux.

**Comment by 89luca89** [comment]
This has been solved now
