### ISSUE TITLE
[Error] Podman graph driver error message when entering image

### ISSUE THREAD

**Issue by dprimon** [89luca89/distrobox#1039]
After upgrading the host distro Debian bullseye to bookworm I get this error when entering a distrobox container:
`ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve.  May prevent use of images created by other tools`
After a quick search on the internet I decided trying deleting the mentioned file. 

Is there a way to get rid of the message? 

As advertised, deleting local files renders the images unusable.

```
$podman --version
podman version 4.3.1
```

**Comment by 89luca89** [comment]
Not distrobox relevant, this is a podman issue
