### ISSUE TITLE
[Suggestion] Detect Host System Default Browser to Open Links

### ISSUE THREAD

**Issue by robert2343** [89luca89/distrobox#1048]
Not sure if this is the right place for this. If not, please let me know.

I would like to have a GUI app running in a distrobox container detect what the default browser of the host system is, so that when I click on a link from within the GUI app in distrobox, it opens the link in my default browser, which is installed on my host system.

If this is already possible, would someone be able to explain it or point me to the place in the docs where it describes how to do this?

Thanks!

**Comment by hustler-not-chatty** [comment]
You will need flatpak installed, and its service running on your host.

**Comment by robert2343** [comment]
Why would I need flatpak for this if the browser is not installed through flatpak?

**Comment by hustler-not-chatty** [comment]
In your container, xdg-open, the program responsible for firing up your default browser, depends on flatpak to function properly (At least in my experience it really does).

You can try it for yourself, and easily revert changes with your favorite package manager anyway.

**Comment by 89luca89** [comment]
Now `xdg-open` is linked to the host one by default, so this won't be  a problem anymore
