### ISSUE TITLE
[Suggestion]  Add a confirmation dialogue when removing distrobox

### ISSUE THREAD

**Issue by profetik-777** [89luca89/distrobox#1050]
When using 

distrobox rm [distrobox name] command, add a dialogue box to confirm w/ user that is what they want to do, 

eg.

Are you sure you want to remove { distrobox name}? This is permanent and cannot be undone. Y / N?

**Comment by 89luca89** [comment]
There is now :) 

![image](https://github.com/89luca89/distrobox/assets/598882/ba6a1e31-cced-402c-b5dd-d889d63d94c3)
