### ISSUE TITLE
[Error] initialising Ubuntu 23.10 container fails due to libgl1-mesa-glx no longer being available

### ISSUE THREAD

**Issue by flexiondotorg** [89luca89/distrobox#1053]
**Describe the bug**

When an Ubuntu container is initialised by entering it for the first time, distrobox attempts to install [libgl1-mesa-glx](https://github.com/89luca89/distrobox/blob/bf65e627b7b5c9b505932a671618c378aa84c48f/distrobox-init#L574). `libgl1-mesa-glx` has been a transitional package for a while and is now obsolete from Ubuntu 23.10 and onwards. As a result, initialising Ubuntu 23.10 containers fails.

**To Reproduce**

Create an Ubuntu 23.10 container and try to enter it.
```
distrobox create --image ubuntu:23.10 --name dev-mantic --pull
distrobox enter dev-mantic -- true
```

The following is output:

```
Starting container...                  	 [ OK ]
Installing basic packages...           	 Error: An error occurred
```

**Expected behavior**

Running the following should create a functioning Ubuntu 23.10 container.

```
distrobox create --image ubuntu:23.10 --name dev-mantic --pull
distrobox enter dev-mantic -- true
```

**Logs**

Run `podman logs -f dev-mantic`, and you'll see:

```
Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgl1-mesa-glx' has no installation candidate
```

**Desktop:**
 - Using `podman`
 - podman version 4.7.2
 - distrobox: 1.5.0.2
 - NixOS 23.05 (Stoat)
 - Via nixpkgs.

**Additional context**

Installing `libgl1` and `libglx-mesa0` instead of `libgl1-mesa-glx` will result in equivalent behaviour and should work on Ubuntu 18.04 and newer.

**Comment by flexiondotorg** [comment]
See https://github.com/89luca89/distrobox/pull/1005

**Comment by 89luca89** [comment]
Fixed

**Comment by Sagor0078** [comment]
is this fixed?
