### ISSUE TITLE
[Error] cannot install `nvidia-cuda-dev` package on Ubuntu LTS in distrobox: "Invalid cross-device link"

### ISSUE THREAD

**Issue by guss77** [89luca89/distrobox#1054]
**Describe the bug**

When creating a new Ubuntu LTS image and trying to install the package `nvidia-cuda-dev`, we get a dpkg error:

```
Unpacking nvidia-cuda-dev:amd64 (11.5.1-1ubuntu1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-1yJRmk/66-nvidia-cuda-dev_11.5.1-1ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/lib/x86_64-linux-gnu/stubs/libcuda.so' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/apt-dpkg-install-1yJRmk/44-libnvidia-ml-dev_11.5.50~11.5.1-1ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-1yJRmk/66-nvidia-cuda-dev_11.5.1-1ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**To Reproduce**

I use the following script to reproduce the issue:

```
distrobox create --image ubuntu:latest --nvidia --name test && \
  distrobox enter test -- sudo -E apt install -q -y nvidia-cuda-dev
distrobox rm -f test # optional, just to cleanup
```

**Expected behavior**

The installation should complete successfully:

**Logs**

Please see attached logs:

- "enter" logs from podman:  [distrobox-test-enter.log](https://github.com/89luca89/distrobox/files/13377795/distrobox-test-enter.log)
- full output from the above script: [distrobox-test-setup.log](https://github.com/89luca89/distrobox/files/13377809/distrobox-test-setup.log)

**Desktop:**

Ubuntu 23.04 (with some extra repositories)
Podman 4.5.0 - installed from Kubic repository
Distrobox 1.5.0.2 - installed from Neon jammy repositories

**Comment by guss77** [comment]
If I enter the distrobox after the installation fails (instead of deleting it), and try to delete the files that failed to be installed, I get a "Device or resource busy error:

```
$ sudo rm -f /usr/lib/x86_64-linux-gnu/stubs/libcuda.so 
rm: cannot remove '/usr/lib/x86_64-linux-gnu/stubs/libcuda.so': Device or resource busy
```

**Comment by 89luca89** [comment]
If you created the container with `--nvidia` then it will mount host's nvidia libraries into the container
Then you cannot just `rm` them

If you need a different version of cuda between host/guest, then to NOT use the nvidia flag, and do a separate installation/instance of the drivers in the container

**Comment by guss77** [comment]
Got it - it means that we cannot use a different CUDA library version then what is installed in the host - if we use the `--nvidia` flag than the installation will fail, and if we don't use the flag - the resulting installation will have a version mismatch with the host driver and will not run.
Oh well :shrug:
