### ISSUE TITLE
[Feature] Support for home on NFS

### ISSUE THREAD

**Issue by SylvanBrocard** [89luca89/distrobox#1055]
I am working in a system where the users home directories are mounted on a NFS share. I'm using root docker as the backend.
`distrobox create` fails because docker can not mount directories that are inside a NFS but not the root of the NFS mount.

In other words, passing `--mount /home/me:/home/me:rslave` to docker will fail because the root of the NFS mount is `/home`.
However, passing `--mount /home:/home:rslave` is supported.

I request a feature where we could specify a custom mount point for the user home, separate from the user home variable.

I successfully tested the following modification:
```diff
---
 distrobox-create | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/distrobox-create b/distrobox-create
index e09961f..0e27686 100755
--- a/distrobox-create
+++ b/distrobox-create
@@ -63,6 +63,7 @@ container_pre_init_hook=""
 container_user_custom_home=""
 container_user_gid="$(id -rg)"
 container_user_home="${HOME:-"/"}"
+container_user_home_mount_point=${container_user_home}
 container_user_name="${USER}"
 container_user_uid="$(id -ru)"
 dryrun=0
@@ -595,7 +596,7 @@ generate_command() {
 		--volume \"${distrobox_entrypoint_path}\":/usr/bin/entrypoint:ro
 		--volume \"${distrobox_export_path}\":/usr/bin/distrobox-export:ro
 		--volume \"${distrobox_hostexec_path}\":/usr/bin/distrobox-host-exec:ro
-		--volume \"${container_user_home}\":\"${container_user_home}\":rslave"
+		--volume \"${container_user_home_mount_point}\":\"${container_user_home_mount_point}\":rslave"
 
 	if [ "${unshare_devsys}" -eq 0 ]; then
 		result_command="${result_command}
```

This, together with a `distrobox.conf` that contains
```text
container_user_home_mount_point="/home"
```
lets me create distroboxes with a regular `distrobox create -n test` command. And I can access my home directory inside the container just fine.

**Comment by SylvanBrocard** [comment]
As an addendum: this modification only works when Distrobox is installed as root (otherwise it will also unsuccessfully try to mount other folders located in `$HOME/.local`). But I'm not sure that's an issue, because in a context where you don't have root privileges, you can't mount a NFS share into docker anyway, if I'm not mistaken.

**Comment by SylvanBrocard** [comment]
I was wrong in my initial post. The problem isn't that docker can't mount subfolders in a NFS, it's that it doesn't have the rights to access user home folders. So it cant mount `/home`, but not `/home/user`.

**Comment by 89luca89** [comment]
This should already work, the problem is in podman/docker not being able to read /home, but that's not on distrobox

**Comment by DLLDev** [comment]
> I was wrong in my initial post. The problem isn't that docker can't mount subfolders in a NFS, it's that it doesn't have the rights to access user home folders. So it cant mount `/home`, but not `/home/user`.

Just use the --root parameter with distrobox command.
