### ISSUE TITLE
[Suggestion] Possibility to use unshare flags after a container has been created

### ISSUE THREAD

**Issue by eylenburg** [89luca89/distrobox#1056]
**Is your feature request related to a problem? Please describe.**
I have a Distrobox container that runs MS Office 2016 (unsupported, no more updates, but latest version working in Wine) via PlayOnLinux 4 (abandoned by the developers) running in an old Ubuntu 18.04 container (unsupported, no more security updates, but the last version supporting 32-bit). To set it up, I needed Internet to download and install the required packages and Wine components. But now that it's working, I'd like to cut off the Internet access because both Ubuntu 18.04 and MS Office 2016 are not getting any more updates and are a potential security risk. 

**Describe the solution you'd like**
You can already use unshare flags (e.g. ```--unshare-netns```) to sandbox the container, but this seems to be only possible when creating the distrobox.

**Describe alternatives you've considered**
It would be great if you could add these unshare flags (or other modifications) to an existing distrobox container.

**Comment by 89luca89** [comment]
This is not possible, as the userspaces are defined at creation time

Please refer to podman and docker docs about this.

As a workaround you can use `--clone` flag to clone existing containers into new ones, with new flags
