### ISSUE TITLE
[Error] New SteamOS 3.5.5 broke podman path

### ISSUE THREAD

**Issue by dtantono** [89luca89/distrobox#1057]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Flatpak requires https://github.com/flatpak/flatpak/issues/5104 and /usr/local/bin should not be used for podman and the last resort is I need to delete the podman on /home/deck/.local/ directory However, when I determine the installation to different folder it refused and it still insist on connecting to  /home/deck/.local/ So, to sum up Flatpak and distrobox does not get along each other

**To Reproduce**
1. I want to update my flatpak app
2. I got error Error: unable to start container "3efd40b79094e89ba65457e158618157a16bd143e4051cf41166c5363b47240f": cannot chown run directory:
3. I checked it and then I need to delete the podman folder (https://www.reddit.com/r/SteamDeck/comments/16mwirf/flatpak_update_issue_in_35_preview_related_to/?sort=new)
4. I installed to different directory like home/deck/bin
5. it refuse and insist to connect to /.local which is not allowed

**Expected behavior**
it should go to specific directory

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 
 - Which version of distrobox? 1.4.2.1
 - Which host distribution? SteamOS
 - How did you install distrobox? install it with podman

**Additional context**
![image](https://github.com/89luca89/distrobox/assets/29157187/3434fa70-c247-470a-bda9-6e3bfd7a37a5)

![Screenshot_20231118_074645](https://github.com/89luca89/distrobox/assets/29157187/c9ae6f13-029f-49a5-9c6a-9916b61ff3f8)
![Screenshot_20231118_074632](https://github.com/89luca89/distrobox/assets/29157187/d442dd03-24a0-4408-9ac6-c24577abdc2b)

**Comment by 89luca89** [comment]
Version 1.4.2.1 is very old and unsupported
Try with newer versions, if the problem persist, reopen the issue :+1:
