### ISSUE TITLE
[Suggestion] Ability to keep track of distrobox exports

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#1058]
It would be useful if distrobox keeps track of exports. The exports could be listed on a yml file organized by container source, and export type. There could be a `distrobox-list-exports` command that lists exports organized by container and export type. There should be a way to list exports from a specific container like `distrobox-list-exports --container my-container` to list exports from a specific container. There could also be a `distrobox-list-exports --raw` option that lists the exports with no organization (useful for programs like hyfetch or neofetch to show the number of exports in the packages area.) --raw and --container should be able to be used combined to list exports not labeled but only from a specific container. --type flag could be used to list exports of only one export type (has bin and app options)

examples

```
$ distrobox list-exports

container-name:
	app:
		gimp
		firefox
	bin:
		vim
		micro
		htop
my-container:
	app:
		kitty
	bin:
		btop
		mc
```

```
$ distrobox list-exports --raw

gimp
firefox
vim
micro
htop
kitty
btop
mc
```

```
$ distrobox list-exports --raw --type bin

vim
micro
htop
btop
mc
```

```
$ distrobox list-exports --type bin

container-name:
	bin:
		vim
		micro
		htop
my-container:
	bin:
		btop
		mc
```

**Comment by 89luca89** [comment]
This has been implemented as of commit 6e26cb2a304e38b0eb0f3f7d0e8d2476ae511e84
