### ISSUE TITLE
[Error] Ros2 running inside Distrobox can't discover topics/nodes running on other computer in the same network

### ISSUE THREAD

**Issue by NoeelMoeskops** [89luca89/distrobox#106]
**Describe the bug**
When running Ubuntu 20.04 with a fresh install of Ros2 Foxy the "container" is unable to find any topics running on another computer (same lan). `ros2 topic list` results only in the local topics. The remote topics are not shown.

(The distrobox container is able to discover the other computer fine with `arp -a` and can `ssh` into it.)

**To Reproduce**
1. Install Ros 2 Foxy (Galactic also does not work) using Ubuntu 20.04 Distrobox.
2. Have a ros2 topic on another computer in the same network.
3. Run `ros2 topic list` on the local distrobox and see that the remote topics are not shown

**Expected behavior**
Being able to communicate from within the container to the outside ros network

**Logs**
there are non.

**Desktop (please complete the following information):**
 - OS: Fedora (remote ros computer is running Ubuntu as well)
 - Version 35

**additional info**
Ros2 uses multicast to discover nodes. Default ports are: 7400 UDP and 7401 UDP. See https://docs.ros.org/en/foxy/Concepts/About-Domain-ID.html?highlight=multicast

**Comment by 89luca89** [comment]
Hi @NoeelMoeskops 

I'm not familiar with Ros2 sadly, so I don't really know much but are there some logs of the application error? 
Technically speaking the container is using the host's network and as you said ARP and ssh manages to connect no problem
Does for example using netcat on ros2 ports work?

**Comment by NoeelMoeskops** [comment]
I tried it with a different network configuration, and it worked. So it properly has nothing to do with Distrobox.
:+1:

**Comment by xiyuoh** [comment]
Hello @NoeelMoeskops! I'm facing the same issue where my ROS 2 nodes/topics cannot be discovered outside of distrobox. Could you shed some light on the network configuration you tried? Thanks!
