### ISSUE TITLE
[Error] Firefox segfaults when using systemd/init

### ISSUE THREAD

**Issue by pavinjosdev** [89luca89/distrobox#1060]
**Describe the bug**
Firefox and Firefox based browsers like Mullvad Browser segfaults when creating container with systemd/init flag using Debian 12 toolbox container image (on LMDE 6/Debian 12 host). Issue persists even when using `--unshare-all` flag. No issues when creating distrobox without systemd/init.

**To Reproduce**
```
# Create distrobox with init
distrobox create --image quay.io/toolbx-images/debian-toolbox:12 --init --additional-packages 'systemd libpam-systemd firefox-esr' --name debs

# Enter distrobox
distrobox enter debs

# Open firefox in normal mode
firefox

# Or safe mode
firefox --safe-mode

# Visit youtube and play a video in a new tab
# If no issue, stop distrobox and enter it again.
# Then open youtube with multiple tabs.
# If still no issue, restart host and open youtube in distrobox
```

**Expected behavior**
Firefox works without segfaults and other errors.

**Distrobox Logs including firefox issue at the end**
[distrobox_debug.txt](https://github.com/89luca89/distrobox/files/13404838/distrobox_debug.txt)

**Podman Logs**
[podman_debug.txt](https://github.com/89luca89/distrobox/files/13404839/podman_debug.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 4.3.1
 - Which version of distrobox? distrobox: 1.6.0 stable
 - Which host distribution? LMDE 6 (Debian 12.1)
 - How did you install distrobox? from github curl/bash script using latest stable version

**Additional context**
I have been having this issue for a few weeks but not been able to figure out the cause. Issue reproduced when using Fedora 38/39 Silverblue host & container, Debian trixie/sid host & Debian 12 container using distrobox v1.5.0.2 dev and stable as well.

Issue happens when visiting complex websites like YouTube, other large/complicated programs such as Mullvad VPN GUI are also affected. Issue persists when running Firefox in both normal mode and safe mode (addons/extensions disabled)

Opening this issue here as I was not able to reproduce the issue on a basic podman container running on the same host with systemd init, X11, and Pulse audio passthrough.

Thanks for any help in troubleshooting this.

Updates:
Issue reproduced on distrobox stable v1.6.0 and with/without deleting firefox profile (/home/pavin/.mozilla)

**Comment by 89luca89** [comment]
Hi @pavinjosdev 

I've just tried and I couldn't reproduce with 1.6.0 and podman 4.7.2 on Aeon

![image](https://github.com/89luca89/distrobox/assets/598882/2ad28295-05fb-4cee-86e8-d93e2ee3685d)

**Comment by pavinjosdev** [comment]
@89luca89 I did some more testing on physical machines (fully updated and rebooted fresh) this time using distrobox v1.6.0 (installed from github) and the same create command in my initial post. These are my findings:

1. LMDE 5 (Debian 11) laptop: Firefox worked without segfaults, but there was no audio. Installed pipewire and there was audio. Stopped distrobox using `distrobox stop debs` and entered it again to confirm everything was working still. The dreaded segfaults returned and won't go away even after removing and creating distrobox again.
2. Fedora 39 KDE laptop: Firefox segfaulted on first open itself. Stopping and entering container again did not solve issue.

Could you try to stop the distrobox from your test on Aeon and enter it again to verify? Perhaps restart the Aeon host and try again to see if it happens?
I will ask around in the matrix chat, if anyone else is able to reproduce the issue.

Thanks for your help! :slightly_smiling_face:

**Comment by pavinjosdev** [comment]
Feel free to close this once PR #1069 is merged.
