### ISSUE TITLE
[Error] Installing a Container on linux-hardened not allowed

### ISSUE THREAD

**Issue by firefoxlover** [89luca89/distrobox#1061]
I try to test Arch with linux-hardened Kernel.

Flatpak and Podman (Distrobox?) both create custom namespaces, which is not allowed in the hardened kernel.

Flatpak can be circumvented by installing `bubblewrap-suid` and it immediately works.

Is there such a thing for Podman, or for Distrobox? Would podman and docker implement this, or Arch, or every distro, or Distrobox?

Thanks!

**Comment by 89luca89** [comment]
Hi, no if podman and docker don't work it's not possible to use distrobox.

And this is not a distrobox bug.
