### ISSUE TITLE
[Error] 'distrobox-export --app' didn't work in version 1.6.0 [arch linux testing] 

### ISSUE THREAD

**Issue by henriqueffc** [89luca89/distrobox#1066]
It is not possible to export the .desktop file using the `distrobox-export --app` command in version 1.6.0 present in the Extra-Testing repository on Arch Linux. In version 1.5.0.2-2, operation is normal.

The following message is displayed:

```
distrobox-export --app gedit
Error: cannot find any desktop files.
Error: trying to export a non-installed application.
```
`org.gnome.gedit.desktop` is in the `/usr/share/applications` of the container.

The `distrobox-export --bin` command is working properly.

```
distrobox-export --bin /usr/bin/gedit --export-path ~/bin
/usr/bin/gedit from ubuntu exported successfully in /home/user/bin.
OK!
```
Logs:
[distrobox.log](https://github.com/89luca89/distrobox/files/13418404/distrobox.log)
[podman.log](https://github.com/89luca89/distrobox/files/13418689/podman.log)

I use Arch Linux, podman in version 4.7.2, distrobox 1.6.0, and installed it using the distro's official repository.

**Comment by 89luca89** [comment]
Thanks for reporting! Fixed

**Comment by ItsRogueRen** [comment]
This issue is still present in 1.6.0.1 on both Nobara (tested myself) and Arch (tested by a a member of my discord server). 

The error is the same the original issue described from what I can tell.
