### ISSUE TITLE
[Error] Cannot start orginal container after update

### ISSUE THREAD

**Issue by xensurve** [89luca89/distrobox#1068]
OS : ARCH PLASMA
DISTROBOX VERSION : 1.6.0.1
PODMAN : podman version 4.7.2

Container was working fine until updated to latest version

I can create a new container and it works but cant get into my orginal one, this container was working fine until the update, I tried to use the older 1.5 version but still cant get the container to run

ERROR : {"msg":"exec container process (missing dynamic library?) `/usr/bin/entrypoint`: No such file or directory","level":"error","time":"2023-11-21T17:26:45.197731Z"}

How can I fix this, I have some important things stored in it

UPDATE : if I edit /usr/lib/systemd/system/user@.service and comment the line below I get "starting container " but doesnt go any further

#OOMScoreAdjust=100

**Comment by pavinjosdev** [comment]
`/usr/bin/entrypoint` in container (read-only) is mapped to `/usr/local/bin/distrobox-init` in the host.
After the upgrade, do you still have that file on the host?
What's the output of: `ls -lh /usr/local/bin/ | grep distrobox`

**Comment by pavinjosdev** [comment]
@lgdsgd2000 The `/usr/bin/..` path is used when installing from the official repos. Otherwise when running the install script from Github the path would be `usr/local/bin/..` Please post the output of:

```
whereis distrobox
distrobox enter <your-distrobox-name> --dry-run
```

**Comment by pavinjosdev** [comment]
@quazar-omega Try removing it directly using podman:

```
podma start <name-of-your-container>
podman exec <name-of-your-container> rm /var/lib/pacman/db.lck
# or to get a shell
podman exec -it <name-of-your-container> bash
```

**Comment by quazar-omega** [comment]
@pavinjosdev I thought of doing that, the issue is that I can't even start the container, or rather `start` doesn't display any errors, but the container goes down soon after starting it with these logs:
<details>
<summary>startup error logs</summary>

```
+ for dep in ${dependencies}
+ command -v bc
+ for dep in ${dependencies}
+ command -v bzip2
+ for dep in ${dependencies}
+ command -v chpasswd
+ for dep in ${dependencies}
+ command -v curl
+ for dep in ${dependencies}
+ command -v diff
+ for dep in ${dependencies}
+ command -v find
+ for dep in ${dependencies}
+ command -v findmnt
+ for dep in ${dependencies}
+ command -v gpg
+ for dep in ${dependencies}
+ command -v hostname
+ missing_packages=1
+ break
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ command -v apk
+ command -v apt-get
+ command -v dnf
+ command -v emerge
+ command -v microdnf
+ command -v pacman
/usr/sbin/pacman
+ pacman -S -y -y
:: Synchronizing package databases...
error: failed to synchronize all databases (unable to lock database)
Error: An error occurred
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

</details>

Then when I try to run a command within it, it follows that I get this:
```
$ podman exec new-box-arch rm /var/lib/pacman/db.lck
Error: can only create exec sessions on running containers: container state improper
```

**Comment by pavinjosdev** [comment]
@quazar-omega Ah, I should've seen this coming as distrobox uses a custom entrypoint.

Try this:

```
podman unshare
podman mount <name-of-your-container>
# cd into the mounted filesystem and make changes
podman unmount <name-of-your-container>
exit
```

**Comment by quazar-omega** [comment]
Oh my goodness, didn't know that was possible, thank you, it works!

..However, the underlying issue remains and I still haven't identified it, i.e. after logging back into the container I tried to upgrade it, but something weird happens where after a short while I'm kicked out of the shell and the container stops on its own, circling back to this issue where the `db.lck` has to be deleted to be able to start the container again. Know how I can troubleshoot this further?

**Comment by quazar-omega** [comment]
Got them here:

1.
	```
	distrobox enter --verbose new-box-arch &> "$(xdg-user-dir DOCUMENTS)/distrobox-enter-arch_failure.txt"
	```
	Output: [distrobox-enter-arch_failure.txt](https://github.com/89luca89/distrobox/files/13622091/distrobox-enter-arch_failure.txt)
2.
	```
	podman logs -f new-box-arch &> "$(xdg-user-dir DOCUMENTS)/podman-logs-arch_failure.txt"
	```
	Output: [podman-logs-arch_failure.txt](https://github.com/89luca89/distrobox/files/13622156/podman-logs-arch_failure.txt)
3.
	```
	podman cp new-box-arch:/var/log/pacman.log - &> "$(xdg-user-dir DOCUMENTS)/podman-cp-arch_failure.log"
	```
	Output: [podman-cp-arch_failure.log](https://github.com/89luca89/distrobox/files/13622170/podman-cp-arch_failure.log)

There's a lot of data, I'm not exactly sure what I should be looking for

**Comment by pavinjosdev** [comment]
@quazar-omega It would've been better to have the logs after deleting the `db.lck` file manually and trying to enter distrobox.

Have a look at `distrobox-init` which is the default entrypoint for the container, if any command fails it would exit and the container would stop.

From the podman logs, it seems the issue is connected to pacman failing to acquire lock or update packages. Here it couldn't update the packages:

```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 glibc-2.38-7-x86_64 downloading...
checking keyring...
checking package integrity...
error: glibc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/glibc-2.38-7-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
warning: lock file missing /var/lib/pacman/db.lck
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```

You could try backing up `distrobox-init` and commenting out the pacman update line to see if you can enter the container and fix it.

**Comment by 89luca89** [comment]
like #1088 this is a pacman issue, not a distrobox one
