### ISSUE TITLE
[Error] If the system default terminal set is a Flatpak distributed one, the Distrobox shell fails to launch from the desktop entry in the terminal emulator.

### ISSUE THREAD

**Issue by IPlayZed** [89luca89/distrobox#1071]
Please, before opening a bug:

**Describe the bug**
If the system default terminal set is a Flatpak distributed one, the Distrobox shell fails to launch from the desktop entry in the terminal emulator.

**To Reproduce**
1. Set a terminal (like Black Box or Konsole) distributed as a Flatpak as system default.
2. Create a Distrobox container or create a desktop entry to launch the shell for it.
3. After some loading animation for opening the shell in the terminal emulator, it closes without further information.

**Expected behavior**
Terminal emulator is opened with distrobox container shell.

**Logs**
No relevant Docker logs.
Relevant journal logs:
```
Nov 23 00:35:41 minefpc systemd[531053]: Started My-distrobox - Terminal entering My-distrobox.
Nov 23 00:35:41 minefpc systemd[531053]: Started app-flatpak-com.raggesilver.BlackBox-1374187.scope.
```

**Desktop (please complete the following information):**
 - Docker
 - Docker version 24.0.7, build afdd53b4e3
 - Which version of distrobox?
 - Arch 6.6.1-zen1-1-zen
 - Pacman

**Additional context**
This happens regardless of the backend used. Only tested for KDE. Only tested for terminal emulators Black Box and Konsole.
Black Box [supports specifying](https://gitlab.gnome.org/raggesilver/blackbox/-/issues/233) the command to be launched. This works when issuing it directly in the terminal: `flatpak run com.raggesilver.BlackBox --command "/usr/bin/distrobox enter  my-distrobox"`, but putting this in the desktop entry's `Exec=` line produces the bug still.

**Comment by pavinjosdev** [comment]
Try adding `Terminal=true` to the desktop file after the Exec line. Maybe the default terminal opens with some useful output.
Could be useful if you could share the Exec line here as well.

**Comment by IPlayZed** [comment]
> Could be useful if you could share the Exec line here as well.
The default generated is:
`Exec=/usr/bin/distrobox enter  my-distrobox`
The one I tried (and fails as well) is:
`Exec=flatpak run com.raggesilver.BlackBox --command "/usr/bin/distrobox enter  my-distrobox"`

**Comment by IPlayZed** [comment]
For clarity this is the _.desktop_ file:
```ini
[Desktop Entry]
Name=My-distrobox
GenericName=Terminal entering My-distrobox
Comment=Terminal entering My-distrobox
Categories=Distrobox;System;Utility
Exec=flatpak run com.raggesilver.BlackBox --command "/usr/bin/distrobox enter  my-distrobox"
Icon=/home/admin/.local/share/icons/distrobox/fedora.png
Keywords=distrobox;
NoDisplay=false
Terminal=true
TryExec=/usr/bin/distrobox
Type=Application
```

The only thing I changed is the Exec line as explained above.

**Comment by IPlayZed** [comment]
I think the baseline problem is that Flatpak based terminals might have a different correct syntax for opening terminal programs from desktop shortcuts (as you call to flatpak, not the binary) and Distrobox is not prepared for this. But I might be wrong here, but this happened to me multiple times, for instance Vim had similar issues.

**Comment by pavinjosdev** [comment]
I wasn't able to reproduce the issue on LMDE 6 host and debian 12 container.
![black_box_distrobox](https://github.com/89luca89/distrobox/assets/11430516/d85fb925-0a59-408f-9630-cb93742db335)

What happens when you run `/usr/bin/distrobox enter  my-distrobox` and `flatpak run com.raggesilver.BlackBox --command "/usr/bin/distrobox enter  my-distrobox"` from your main terminal? Perhaps the path to distrobox is incorrect.

FYI I'm running distrobox v1.6.0.1 with PR #1069 applied.

**Comment by IPlayZed** [comment]
As I have mentioned:

> Black Box [supports specifying](https://gitlab.gnome.org/raggesilver/blackbox/-/issues/233) the command to be launched. This works when issuing it directly in the terminal: flatpak run com.raggesilver.BlackBox --command "/usr/bin/distrobox enter  my-distrobox"
that works fine, a new terminal window is opened up with the corresponding container opened.

Issuing `/usr/bin/distrobox enter  my-distrobox` enters the container.

I am running distrobox 1.5.0.2 from the Arch repos. Should the PR #1069 affect this behavior?

**Comment by pavinjosdev** [comment]
There have been changes to `distrobox-export` since 1.5.0.2. Perhaps try updating to 1.6.0.1 from Github, re-export the app and see if that fixes the issue.
PR #1069 changes the way you enter the distrobox as well as the corresponding exports.

Before doing any of those, could you try creating a simple desktop file that opens htop or something (i.e., something with a continuous output and not something that does something and exits immediately) using BlackBox terminal? Maybe this is not related to distrobox at all.

**Comment by IPlayZed** [comment]
I tried installing BlackBox as a native package, the results were the same, but now there was additional journal output:
```
Nov 28 18:24:25 minefpc plasmashell[83896]: Unknown option -e
Nov 28 18:24:25 minefpc plasmashell[83896]: Run /usr/bin/blackbox --help to get help
Nov 28 18:24:25 minefpc systemd[4054]: app-distrobox-5fd9f9acc4c64306926c579cb07dd31a.scope: Couldn't move process 83896 to requested cgroup '/user.slice/user-1001.slice/user@1001.service/app.slice/app-distrobox-5fd9f9acc4c64306926c579cb07dd31a.scope': No such process
Nov 28 18:24:25 minefpc systemd[4054]: app-distrobox-5fd9f9acc4c64306926c579cb07dd31a.scope: Failed to add PIDs to scope's control group: No such process
Nov 28 18:24:25 minefpc systemd[4054]: app-distrobox-5fd9f9acc4c64306926c579cb07dd31a.scope: Failed with result 'resources'.
Nov 28 18:24:25 minefpc systemd[4054]: Failed to start Distrobox - Terminal entering Distrobox.
```

This happened as well with other terminal based desktop entries, like Htop.

**Comment by IPlayZed** [comment]
@pavinjosdev Do you have some idea about where should I open an issue? My first guess is BlackBox or KDE.

**Comment by pavinjosdev** [comment]
@IPlayZed I suggest KDE forums as Blackbox/htop/distrobox desktop entries were working fine on Cinnamon DE.
