### ISSUE TITLE
[Error] Installing network-manager-openvpn in a rootful systemd container results in kde plasma session losing access to video and audio cards.

### ISSUE THREAD

**Issue by kisame217** [89luca89/distrobox#1077]
**Describe the bug**
In rootful systemd container with unshare-all, installing network-manager-openvpn, stopping and restarting container leads to kde plasma not being able to access graphics card.  

**To Reproduce**
Create container
```
distrobox create -v --image ubuntu:22.04 --init  --additional-packages "systemd" --unshare-all --root --name ubuntu-tb
```

Enter distrobox and install network-manager-openvpn
```
distrobox enter -v -r ubuntu-tb
sudo apt install network-manager-openvpn
```

Exit, stop the container  and then try to enter again.

**Expected behavior**
This should not affect host system.

**Logs**
[create_and_firstenter.txt](https://github.com/89luca89/distrobox/files/13466409/create_and_firstenter.txt)
[podmanlogs.txt](https://github.com/89luca89/distrobox/files/13466410/podmanlogs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - Podman
 - Which version or podman, docker or lilipod?
 - podman version 4.7.2
 - Which version of distrobox?
 - distrobox: 1.6.0.1
 - Which host distribution?
 - Fedora Kinoite 39
 - How did you install distrobox?
 - wget

**Additional context**
Attaching journalctl logs because it clearly shows kde losing access to gpu.
[journalctl.txt](https://github.com/89luca89/distrobox/files/13466416/journalctl.txt)

**Comment by neurodiverseEsoteric** [comment]
Same issue for archlinux image (which presumably has openvpn/networkmanager-openvpn already installed)...

**Comment by 89luca89** [comment]
Hi @kisame217 can you try with latest git version?

I just tried your commands, and this did not affect the host system for me:

![image](https://github.com/89luca89/distrobox/assets/598882/9c0db955-df4f-4308-918c-0dc58fab2f79)

**Comment by kisame217** [comment]
@89luca89 I just tested with both 1.7.0 and the latest commit and the problem still persists.
Are you sure you are installing network-manager-openvpn  in the container?

**Comment by RegisHubelia** [comment]
Got similar issue with libvirtd...  when services are started in the container, all input (keyboard, mouse) and gpu is unresponsive.  Seems like the system is frozen, but it's not as if I press the power button, it shuts down gracefully as usual.  Using the official documentation for libvirtd on microos.

**Comment by 89luca89** [comment]
@RegisHubelia @kisame217 I've just pushed a fix that likely would resolve the issue

Can you try with version from GIT?

**Comment by RegisHubelia** [comment]
Will do and revert.  Thank you very much!

**Comment by kisame217** [comment]
@89luca89 Can confirm issue no longer persists. Thank you very much. I'll be closing this issue.
