### ISSUE TITLE
[Error]sudo: PAM account management error: Authentication service cannot retrieve authentication info

### ISSUE THREAD

**Issue by lgdsgd2000** [89luca89/distrobox#1078]
**Describe the bug**
host: archlinux
container: archlinux
distrobox: 1.6.0.1 form archlinux repository
podman:4.7.2
I only created one container. Initially, I noticed that the container would not start after the distrobox update, and after checking the podman logs to resolve the issue([what I do](https://github.com/89luca89/distrobox/issues/1068#issuecomment-1826864245)), I had the problem shown in the title. This container is rootless, but now executing anything that requires sudo will get the error

**To Reproduce**
I created a new archlinux container but can't reproduce the error.

**Logs**
[distrobox-enter subarch --verbose.txt](https://github.com/89luca89/distrobox/files/13470300/distroboxlog.txt)

**Additional context**

**Comment by ZariTen** [comment]
Getting the same issue here. Host is Fedora Kinoite, Container Arch Linux. After creating the container, everything is normal. But if i stop it and start again, i bump into this issue and can't use sudo anymore. 
This doesn't seem to affect containers created with --root

**Comment by SimplyTadpole** [comment]
I have the same problem on Fedora Kinoite.

**Comment by haryp2309** [comment]
I have the same issue. The `su `-command still works, so I'm able to update the container and edit root files and such. But the `sudo`-command doesn't work anymore:

```sh
$ sudo echo "Hello World!"
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
```

Host: Fedora Silverblue 39
Container: Fedora Workstation 38 with separate home directory.

**Comment by Autumnlight02** [comment]
fedora kionite, happens on arch as well!

**Comment by samkcdev** [comment]
Currently I am on the latest 1.7.1 
Host OS:Fedora 39
Both my existing arch and Debian containers shows the same sudo errors which I mentioned above. Does this work only in new containers or do I have to make any changes?

**Comment by pavinjosdev** [comment]
@samkcdev Could you try if the problem exists in a new debian container using toolbox image?

```
distrobox create --image quay.io/toolbx-images/debian-toolbox:12 \
--init --additional-packages "systemd libpam-systemd" \
--name deb-test
```

If not, you can [clone](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#duplicate-an-existing-distrobox) the current ones into new distrobox containers.

**Comment by samkcdev** [comment]
@pavinjosdev

I cloned the existing debian and arch containers they cloned successfully and I was able to enter the containers but when I try to use sudo in both the containers it throws me a new error:

```
sudo: /etc/sudo.conf is owned by uid 1000, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```
I have created a new debian test container the way you have shown so far its working fine with regards to sudo. Will test it for few days for any issues.

For now I am planning to create new arch containers to replace the existing ones
