### ISSUE TITLE
[Suggestion] Templates

### ISSUE THREAD

**Issue by ccarney16** [89luca89/distrobox#108]
Hello! Thank you for providing such a neat set of scripts to make working with other distributions easier (along with running apps in legacy environments). As the title suggests, rather than nailing down every distro to support, allow users to create templates to support a wider variety of images.

One of the issues I have come across is that legacy distribution versions do not really work out so well, largely due to the repos being down or packages being renamed. This also occurs with unsupported distros. My proposal is to remove any package management out of init and perform them before creating the main container. This will also allow the ability to provide a repeatable and reliable environment for any modifications.

In terms of structure, the template could be separated into 2 parts, the information file and build script. the information file could provide information such as base image and tags that can be used, for example:

```
AUTHOR="templateauthor@example.com"
DESCRIPTION="Template for Ubuntu"
IMAGE="docker.io/library/ubuntu"
TAGS="20.04,18.04"
FALLBACK_SHELL="/bin/bash"
```

`distrobox-create` could pull the image and run a build script to install any needed dependencies. The container can then be committed to image once the build script was successful. I have provided a sample for podman:

```
distrobox-create --name ubuntu_environment --template ubuntu --tag 20.04 # Example of the command being executed

# What distrobox-create could do with the template
podman run --name distrobox-build-s87ag -v /usr/share/distrobox/templates/ubuntu/build.sh:/build.sh ubuntu:20.04 /build.sh
podman commit distrobox-build-s87ag distrobox_ubuntu:20.04
podman rm distrobox-build-s87ag
```

Alternatives I have thought about were to use Dockerfiles instead of scripts, as both options would achieve the same solution.

**Comment by 89luca89** [comment]
Hi @ccarney16 

Can you bring some examples on what type of environment didn't work? I've used some old images (Debian 8, Centos 7) and they did work indeed. Are you talking even legacy-er?

I don't really want to create a situation where we need custom built images **as a requirement** 
But on the other hand nothing stops you from using a dedicated image, the `init` will try to install things only if they're not present in the container, so for example, a `fedora-toolbox` image will just skip the install part.

So maybe we could add a section where we explain how to create a dedicated image so that it doesn't need to be `init`ialized?

**Comment by ccarney16** [comment]
Yeah, that sounds good instead. I need to run some older images such as ubuntu 12.04 or debian 7 due to some older network equipment needing specific versions of java.

**Comment by 89luca89** [comment]
For distributions old enough that mirrors are down, you could this way just create the dedicated image using local mirrors or manually adding the programs but having a template system wouldn't fix this issue anyway as we're just moving the installation commands from one script (the init) to another (the template)

**Comment by ccarney16** [comment]
I was thinking of a reproducible environment specific to an application need, but I do get your point of view, as using something like flatpak or just using podman directly would be a better option for a highly specialized need.

**Comment by 89luca89** [comment]
Yes probably, but anyway I'll add a page to the docs to create a distrobox tailored image if needed :+1:

**Comment by ccarney16** [comment]
That sounds good! I saw the commands required for init, so I'll see about doing that and make a custom image. Thanks again!
