### ISSUE TITLE
[Error] podman does not run

### ISSUE THREAD

**Issue by dtantono** [89luca89/distrobox#1085]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
podman does not run

**To Reproduce**
1. type distrobox-upgrade --all
2. I got error ERRO[0000] invalid internal status, try resetting the pause process with "/home/deck/.local/share/podman-static/bin/podman system migrate": could not find any running process: no such process 

**Expected behavior**
it should works 

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.6.1
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? SteamOS 3.5.7
 - How did you install distrobox?curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local

**Additional context**
![image](https://github.com/89luca89/distrobox/assets/29157187/73814e35-2738-4077-ad65-a5f7b95acf91)
![image](https://github.com/89luca89/distrobox/assets/29157187/fa046bc1-9840-4a25-aaf1-0de7c11a4b3e)

**Comment by Bai-Chiang** [comment]
I find that SteamOS 3.5 come with distrobox preinstalled.[1,2]

[1] https://github.com/ValveSoftware/SteamOS/issues/754#issuecomment-1711435612
[2] https://github.com/89luca89/distrobox/issues/1108

**Comment by dtantono** [comment]
oh, I just found out that I got same error message on Kubuntu 22.04 as well

**Comment by Bai-Chiang** [comment]
I don't have Ubuntu based system. But I tried following command on my steam deck with preinstalled distrobox, it works. SteamOS version: 3.5.7
```
distrobox create --image registry.fedoraproject.org/fedora-toolbox:39 --name fedora-39
distrobox upgrade --all
```

**Comment by dtantono** [comment]
Nope, I got same errors
![image](https://github.com/89luca89/distrobox/assets/29157187/08a7d3d8-baed-496e-b285-96f25ba8e257)

**Comment by Bai-Chiang** [comment]
It seems you are using podman installed in `/home/user/.local/share/podman-static`. If you run `which podman` it should say `/usr/bin/podman`. Similarly, `which distrobox` should give `/usr/bin/distrobox`.

**Comment by dtantono** [comment]
the picture I show you is on Ubuntu system and it display same error message with SteamOS

**Comment by Bai-Chiang** [comment]
May I ask how you installed distrobox on your Ubuntu system?

**Comment by dtantono** [comment]
https://github.com/89luca89/distrobox/blob/main/docs/posts/steamdeck_guide.md and also I use this (curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local) for sudoless installation

**Comment by Bai-Chiang** [comment]
For your steam deck, I think after removing `/home/user/.local/share/podman-static` directory, it should use `/usr/bin/podman` instead. Also removing `~/.local/bin/distrobox*` so it uses `/usr/bin/distrobox`.

**Comment by dtantono** [comment]
and I got new error message on my sream deck
![image](https://github.com/89luca89/distrobox/assets/29157187/94bfd559-eb88-417b-8ad3-462fe8cbb034)

**Comment by Bai-Chiang** [comment]
Then remove `~/.local/podman` directory.

**Comment by dtantono** [comment]
![image](https://github.com/89luca89/distrobox/assets/29157187/4f07440a-d9c7-4e26-a9c5-5ff0300170a1)
there is no such thing as podman in that directory

**Comment by Bai-Chiang** [comment]
Could you show me your `~/.config`? There may be some old podman configs.

Also could you run this command `podman run docker.io/hello-world`?

**Comment by dtantono** [comment]
I cannot run that docker 
![image](https://github.com/89luca89/distrobox/assets/29157187/35ca471b-7d4f-4738-9a2e-8de6eea83ff2) and for that config I wrote nothing
![image](https://github.com/89luca89/distrobox/assets/29157187/b4467c88-b1cf-4e59-9c1b-0b3433205f4b)

**Comment by Bai-Chiang** [comment]
Do you have `~/.config/containers` directory? Remove it if it's there. If it still doesn't work, you may paste `/etc/containers/containers.conf` here.

**Comment by dtantono** [comment]
yeah it works. But, how about the Ubuntu one? because SteamOS is immutable distro and Ubuntu is not. Is same solution applies?

**Comment by Bai-Chiang** [comment]
What I did was removing podman and distrobox installed in `~/.local` and your old configuration `~/.config/containers`, so that you will use system installed podman and distrobox located in `/usr/bin/` and default configuration. Basically undo your old installation.

If you are using Ubuntu 23.04 or 23.10, distrobox already included in the repository. So you can install it with `apt install distrobox`. Then using similar steps remove your old installation.

If you are using Ubuntu 22.04, I'm not sure how to get your installation work. You may consider upgrade to newer version or wait until 24.04 release, so you can install distrobox directly from repository.

SteamOS is immutable so you can't install packages from repository with `pacman -S package-name`, that why there is [this](https://github.com/89luca89/distrobox/blob/main/docs/posts/steamdeck_guide.md) dedicated installation guide to work around it. Now distrobox is preinstalled, we don't need these work around anymore. It's always better to install packages from distribution repository, since it's well tested.

**Comment by dtantono** [comment]
the method I use to install distrobox on Ubuntu is sudoless instalation like this https://github.com/89luca89/distrobox/blob/main/docs/posts/steamdeck_guide.md

**Comment by Bai-Chiang** [comment]
I'd suggest you install through `apt`. Check out the Ubuntu section. [1] This is recommended method.

[1] https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#host-distros

**Comment by dtantono** [comment]
thanks, I remove the sudoless distrobox and get the PPA running properly. You mentioned the next LTS  release 24.04 which will be happened on April 2024 should support distrobox natively. When I upgrade my Ubuntu to next LTS release. Should I remove the PPA?

**Comment by Bai-Chiang** [comment]
I think the best practice is removing all packages installed from PPA and removing all PPA before upgrading the system. After upgrade you can install distrobox directly.

**Comment by dtantono** [comment]
Thank you

**Comment by CouscousPie** [comment]
If somebody ends here from simply duckducking the error `ERRO[0000] invalid internal status, try resetting the pause process with "podman system migrate": could not find any running process: no such process`...
... did you already try literally executing "podman system migrate"?
This was what fixed it for me.
