### ISSUE TITLE
[Error] Error while entering arch container

### ISSUE THREAD

**Issue by mosK1T0** [89luca89/distrobox#1088]
**Describe the bug**

**To Reproduce**
When I try to enter a container running arch I get the following error:
`Installing basic packages...            	 Error: An error occurred`
I dose not matter if this is a new container or one I have used for a long time

**Logs**
Run the commands with `--verbose` and post the log here as a file upload (distrobox enter --verbose [container_name]:
[verbose.txt](https://github.com/89luca89/distrobox/files/13540003/verbose.txt)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag (here are the podman logs but im not sure if the container uses podman):
[podman.txt](https://github.com/89luca89/distrobox/files/13540005/podman.txt)

**Desktop (please complete the following information):**
 - I think podman?
 - podman version 4.8.0
 - distrobox: 1.6.0.1
 - Fedora 39
 - coper repos

**Comment by 1player** [comment]
@thunderburger what do you mean that you are having the same issue with 1.5.0.2?

I rebased my Silverblue workstation to 39.20231120.0, which is on 1.5.0.2, and the problem disappears. I'll wait until this is fixed before upgrading again.

**Comment by thunderburger** [comment]
> @thunderburger what do you mean that you are having the same issue with 1.5.0.2?

That the `Installing basic packages...            	 Error: An error occurred` error described in OP, is still present when trying with a previous version of distrobox (1.5.0.2).

**Comment by BennyAJ** [comment]
I'm also having this issue

**Comment by SelfRef** [comment]
I had the same issue. I removed `archlinux` image from local, then let Distrobox to pull it again, and it now works.

**Comment by twklessor** [comment]
@SelfRef That's good to know although it doesn't really apply to an existing container. It's quite unfortunate that a new version can break a container without any test cases indicating a problem. I'm not well versed in the ecosystem for distrobox so maybe I'm mistaken.

**Comment by 1player** [comment]
@89luca89 Any update? I am still on the distrobox 1.5 until this gets resolved. I really do not want to rebuild my archlinux container I've used for 2 years. 

I am still not sure where the problem is actually, whether its a backwards incompatible change, or a bug in 1.6

**Comment by mosK1T0** [comment]
@1player I'm on version 1.6.0.1 and the issue still persists.

**Comment by 89luca89** [comment]
@mosK1T0 @1player the problem presents itself if you try to enter an archlinux container created with 1.5.x from a 1.6.x installation?

Because creating/running it works correctly from 1.6.x

As a migration you might want to check if creating a new container with `--clone` works?

**Comment by spkane** [comment]
In my case the `pigz` package was the actual problem.

I needed to run:

```sh
pacman-key --refresh-keys
pacman -S  --noconfirm pigz
```

**NOTE**: Be patient. The pacman-keys command can take a long time to complete.

Something like this should also work:

```sh
distrobox-create --image archlinux:base-20230723.0.166908 --name arch --pre-init-hooks "pacman-key --refresh-keys"
distrobox enter arch
```

**Comment by spkane** [comment]
In my case, some of the packages have an odd key validity issue. Some of the package keys have likely expired on the packages for this 7-month-old Arch Linux release, and a few others have been renewed in that time frame.

I needed to install a few packages and then refresh the keys to get everything to install cleanly.

This worked for me:

```sh
distrobox-create --image archlinux:base-20230723.0.166908 --name arch --pre-init-hooks "pacman -S -y -y; pacman -S --noconfirm libx11 vulkan-icd-loader; pacman-key --refresh-keys"
distrobox enter arch
```

**NOTE**: You need to be really patient. The `pacman-keys` command can take a very long time to complete.

**Comment by 89luca89** [comment]
This isn't properly a distrobox issue, from what I see it is a pacman/keys issue

**Comment by sultancoding** [comment]
This worked for me, Install package `dbus` first:

`distrobox create --pull -i docker.io/library/archlinux:latest --name Distrobox-Archlinux --home ~/Distrobox/Archlinux --additional-packages "systemd" --init --pre-init-hooks "pacman -S -y -y; pacman -S --noconfirm dbus; pacman-key --refresh-keys"`
