### ISSUE TITLE
[Error] parsing commandline arguments is broken now

### ISSUE THREAD

**Issue by uncomfyhalomacro** [89luca89/distrobox#1089]
**Describe the bug**
I cannot run command line arguments outside the container from exported binaries anymore.

**To Reproduce**
1. Export some binary.
3. Use the exported binary from host.
4. Run some commandline args.

A good example would be `julia`:

Before distrobox version 1.6.0.1, you can just run `julia -e 'print("Hello world")'`.

On that version, I get:

```bash
julia -e 'print("Hello world")'
ERROR: syntax: incomplete: invalid string syntax
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Expected behavior**
It should be the same as before the version and parses the arguments correctly.

**Comment by pavinjosdev** [comment]
Fixed in PR #1069

**Comment by pavinjosdev** [comment]
There were changes to distrobox-export from `1.5.0.2` to `1.6.0.1`.
Could you try deleting and re-exporting the binary to see if it fixes issue.
BTW, this issue does not happen with PR #1069 applied as it changes the way exports are handled.

**Comment by uncomfyhalomacro** [comment]
i still got the same issue after removing and then reexporting the binary

**Comment by uncomfyhalomacro** [comment]
It seems recreating a new container fixes this? odd. i guess i should recreate containers every major update
