### ISSUE TITLE
[Suggestion] de in container on silverblue

### ISSUE THREAD

**Issue by gmankab** [89luca89/distrobox#1090]
hello

there is a guide for running de in distrobox on centos - https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md

is it possible to do something similar on fedora silverblue?

i tried to follow this guide, but gnome not starts

output of `journalctl -b -p3 > log.txt 2>&1`: [log.txt](https://github.com/89luca89/distrobox/files/13555378/log.txt)

**Comment by 89luca89** [comment]
The guide is now a bit updated, and yes it is possible on silverblue

**Comment by gmankab** [comment]
i'll try thank you
