### ISSUE TITLE
[Discussion] Is that possible to remove pre-init-hooks ?

### ISSUE THREAD

**Issue by CicadaSeventeen** [89luca89/distrobox#1091]
I used to need proxy for a debian container so that I went though the guild here to use `pre-init-hooks`. 
https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md

However, for some reason I do not need to use proxy anymore. While I can delete proxy setting of `apt` in the container, the proxy settings recover here once I launch distrobox another time.

Is there any way to remove the hooks rather than I have to build a new container?

Thanks.

**Comment by pavinjosdev** [comment]
@CicadaSeventeen Perhaps try cloning the distrobox without `pre-init-hooks`: https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#duplicate-an-existing-distrobox

**Comment by 89luca89** [comment]
> @CicadaSeventeen Perhaps try cloning the distrobox without `pre-init-hooks`: https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#duplicate-an-existing-distrobox

This is the correct answer :+1:
