### ISSUE TITLE
[Error] Multiline exported_app and distrobox-assemble

### ISSUE THREAD

**Issue by k1mbl3** [89luca89/distrobox#1096]
It looks like there's a little bug when using the multiline 'exported_app' on version 1.6.0.1. The following 'distrobox.ini' goes well until it starts exporting the apps, then it gets stuck during the first one.
```ini
[test]
image=alpine
replace=true
pull=true
start_now=true
additional_packages="xterm htop"
exported_apps="xterm"
exported_apps="htop"
```

When it's a single line like this, it fails to parse and returns the errors 'cannot find any desktop files.' and 'trying to export a non-installed application'
```ini
[test]
image=alpine
replace=true
pull=true
start_now=true
additional_packages="xterm htop"
exported_apps="xterm htop"
```

**Comment by Eoin-ONeill-Yokai** [comment]
I'm having a similar issue with single line `exported_bins` where it isn't properly parsing single line bins. Example:

```
[devbox]
additional_packages="build-essential scons clang-format black pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev git git-lfs vim git-filter-repo ripgrep bat"
image=toolbx-images/debian-toolbox:unstable 
home=/home/eoin/.container_home/devbox
pull=true
replace=true
start_now=true
exported_bins="/usr/bin/git /usr/bin/scons /usr/bin/vim /bin/rg /bin/batcat"
exported_bins_path="/home/eoin/.local/bin"
```

This reports the following error:

```shell
Error: cannot find /usr/bin/git/usr/bin/scons/usr/bin/vim/bin/rg/bin/batcat.
```

Looks to me like space splitting has a regression for some reason.

**Comment by Idesmi** [comment]
Can reproduce

**Comment by ebits21** [comment]
Same as #1083

Noticed it right on release because I was excited to try out the full assemble command lol

**Comment by john-ghatas** [comment]
Encountered this issue as well

**Comment by gunzy83** [comment]
> Noticed it right on release because I was excited to try out the full assemble command lol

Just upgraded, was excited to try it too. Can confirm the fix works.
