### ISSUE TITLE
[Discussion] Set persistent MAC address in unshared-netns distrobox?

### ISSUE THREAD

**Issue by tjbbjt** [89luca89/distrobox#1101]
Is there a way to configure a persistent MAC address with a distrobox created with --unshare-netns?

Everytime I stop and start a unshared-netns distrobox a random MAC address is applied to the Tap interface

In a Rocky Linux distrobox I tried to make a cfg file for tap in /etc/sysconfig/network-scripts/ifcfg-tap0 as

DEVICE=tap0
ONBOOT=yes
BOOTPROTO=none
TYPE=Tap
HWADDR=ma:ca:dd:re:ss:##

Doesn't work though. What am I missing??

**Comment by rrahl0** [comment]
yes, just add to the additional-flags --mac-address (as this is a podman feature)

**Comment by tjbbjt** [comment]
> yes, just add to the additional-flags --mac-address (as this is a podman feature)

Thanks for helping, I added --additional-flags:

distrobox-create DistroboxName --unshare-netns --image rockylinux:9 "--network=bridge --mac-address=ma:ca:dd:re:ss:##" 

It seemed to work fine but when I enter the distrobox I get an error:

> ERRO[0000] Unable to clean up network for container Container: "failed to mount tmpfs on \"/run/user/1000/libpod/tmp/rootless-netns/run/systemd/resolve\" for rootless netns: no such file or directory" 
Error: unable to start container "Container": failed to mount tmpfs on "/run/user/1000/libpod/tmp/rootless-netns/run/systemd/resolve" for rootless netns: no such file or directory

Podman is a bit over my head, am I missing additional-flags?

**Comment by 89luca89** [comment]
The right answer is to use `--unshare-netns --additional-flags "--mac-address 02:42:ac:11:00:11 --network=bridge"`
If that doesn't work, there is something wrong with your podman setup, which is out of scope with distrobox
