### ISSUE TITLE
[Error] Distrobox export does not pass command-line arguments correctly, breaking freerdp (and possibly other programs)

### ISSUE THREAD

**Issue by d3-X-t3r** [89luca89/distrobox#1104]
**Describe the bug**
Quotes, which are part of a command-line argument passed to a distrobox exported binary, are removed by distrobox - which breaks the syntax for the receiving binary. One such program affected by this is `xfreerdp` - which requires quotes when launching a Remote App, using the syntax `xfreerdp /v:server /app:program:"C:\Path\to the\binary.exe"`. This same syntax works fine when executed inside of the container (ie after `distrobox enter <name>`), so there's no issue with the parameter syntax itself.

It appears that the arguments are passed (somewhat correctly) after escaping the quotes,backslashes and spaces, ie `xfreerdp /v:server /app:program:\"C:\\Path\\to\ the\\binary.exe\"`, but xfreerdp still says the syntax is invalid. Unfortunately it doesn't print out the arguments that it received, so I'm not sure what exactly is going wrong. It would be great if the shim script that's created passes the full arguments as-is: quotes and all.

**To Reproduce**
1. Install freerdp inside a container
2. Export xfreerdp: `distrobox-export --bin /usr/sbin/xfreerdp`
3. Launch the exported binary: `xfreerdp /v:server /app:program:"C:\Path\to the\binary.exe"`
4. Try again with escapes:  `xfreerdp /v:server /app:program:\"C:\\Path\\to the\\binary.exe"`

Error message:
```
[11:24:11:123] [50847:0000c69f] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: Unsupported command line syntax!
[11:24:11:123] [50847:0000c69f] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: FreeRDP 1.0 style syntax was dropped with version 3!
```

**Expected behavior**
- Exported binary should be able to accept all passed-on parameters without requiring any special modifications by the end-user
- Exported binary should pass on all the input parameters intact to the binary inside the container.

**Logs**
[No relevant logs printed by podman / or the `--verbose` flag in this instance]

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 4.8.1
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Bazzite (Based on Fedora 39 Kinoite)
 - How did you install distrobox? Part of the distro

**Additional context**

**Comment by 89luca89** [comment]
Hi @d3-X-t3r this is already solved in latest git version, as you can see:

![image](https://github.com/89luca89/distrobox/assets/598882/b7e8c075-bfa5-41c5-ab74-1a5203bcaadf)
