### ISSUE TITLE
[Error] Unable to login with fedora rawhide on wayland 

### ISSUE THREAD

**Issue by githubuser6000** [89luca89/distrobox#1117]
**Describe the bug**
Hello, I followed the guide [here](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md), but am unable to login. I try to login and am shown the lock screen again. 

**To Reproduce**
* Install fedora 39 KDE
* Update system 
* Install distrobox
* Follow guide above
* Try to login with the new entry at lock screen after logout
* Notice that you are back at the lockscreen 

**Expected behavior**
Expect to be logged into KDE rawhide version :D 

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - Which version or podman, docker or lilipod?
 - Which version of distrobox?
 - Which host distribution?
 - How did you install distrobox?
 - Podman: `4.8.1`
 - Distrobox: `1.6.0.1`
 - Host: Fedora 39 KDE spin `6.6.8-200.fc39.x86_64`

**Additional context**
I understand this isn't a supported usecase, and that there are warnings, but I'd really appreciate it if I could get this to work ❤️

**Comment by 0x006E** [comment]
Have you checked if your distrobox-enter binary is at /usr/local/bin. Also for kde, there is a small mistake in the doc as the container name is not mentioned in the session file.

**Comment by githubuser6000** [comment]
I managed to fix the path and got it working, but apparently the new trackpad gestures that were added to KDE don't work but I guess that's off-topic or out of scope. I'd appreciate any insight you might have though : )

Thank you!
