### ISSUE TITLE
[Error] ping command does not work.

### ISSUE THREAD

**Issue by s-kesh** [89luca89/distrobox#1118]
**Describe the bug**
ping to a address does not work.
I have a fedora distrobox on debian 12 host. When I try to ping to a address, it shows following error

```
$ ping -v 8.8.8.8
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: => missing cap_net_raw+p capability or setuid?
```

ping works on the host.

**To Reproduce**
Use ping on the container.

**Expected behavior**
ping should work.

**Logs**
[ping.log](https://github.com/89luca89/distrobox/files/13768983/ping.log)
[podmanerr.log](https://github.com/89luca89/distrobox/files/13768995/podmanerr.log)
[podman.log](https://github.com/89luca89/distrobox/files/13768997/podman.log)

**Desktop (please complete the following information):**
 - podman
 - 4.3.1
 - 1.6.0.1
 - debian 12.4 (kernel: 6.1.0-16-amd64)
 - Mannualy installed distrobox using curl.

**Additional context**
None

**Comment by pavinjosdev** [comment]
Could you try in a distrobox created using `--unshare-netns` flag?

**Comment by 89luca89** [comment]
Hi @s-kesh can you provide more info on how the container was created? I'm not able to reproduce this issue

**Comment by s-kesh** [comment]
Sorry for such a late reply. I was busy with some work.
I created the the distrobox with

`distrobox create --image registry.fedoraproject.org/fedora-toolbox:39 --name fedbox`

Let me know if you need some other information. If you can not reproduce it, maybe it is a problem with debian.

**Comment by nafiz1001** [comment]
I'm on Debian 12 (Bookworm), and I also had a similar issue.
I created distrobox with `distrobox-create -i debian:bookworm --unshare-netns`

The `--unshare-netns` did kinda help, but then I was getting another issue.

```
nafiz@debian-bookworm:~$ ping google.com
PING google.com (x.x.x.x) 56(84) bytes of data.
```

It would just hang on the first `PING` line.

**Comment by nafiz1001** [comment]
@s-kesh Can you reopen the issue? 😅

**Comment by pavinjosdev** [comment]
@nafiz1001 Are you using the latest distrobox version 1.7.0 and the debian [toolbox](https://quay.io/organization/toolbx-images) image?

Because I'm not able to reproduce the issue with those.

**Comment by nafiz1001** [comment]
> @nafiz1001 Are you using the latest distrobox version 1.7.0 and the debian [toolbox](https://quay.io/organization/toolbx-images) image?
> 
> Because I'm not able to reproduce the issue with those.

Yep.

```
nafiz@thinkbook:~$ distrobox-create -i quay.io/toolbx-images/debian-toolbox:12 --unshare-netns
Creating 'debian-toolbox-12' using image quay.io/toolbx-images/debian-toolbox:12	 [ OK ]
Distrobox 'debian-toolbox-12' successfully created.
To enter, run:

distrobox enter debian-toolbox-12

nafiz@thinkbook:~$ distrobox enter debian-toolbox-12
Starting container...                   	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 [ OK ]
Setting up read-only mounts...          	 [ OK ]
Setting up read-write mounts...         	 [ OK ]
Setting up host's sockets integration...	 [ OK ]
Integrating host's themes, icons, fonts...	 [ OK ]
Setting up package manager exceptions...	 [ OK ]
Setting up package manager hooks...     	 [ OK ]
Setting up dpkg exceptions...           	 [ OK ]
Setting up apt hooks...                 	 [ OK ]
Setting up distrobox profile...         	 [ OK ]
Setting up sudo...                      	 [ OK ]
Setting up user groups...               	 [ OK ]
Setting up kerberos integration...      	 [ OK ]
Setting up user's group list...         	 [ OK ]
Setting up existing user...             	 [ OK ]
Setting up user home...                 	 [ OK ]
Ensuring user's access...               	 [ OK ]

Container Setup Complete!
bash: go: command not found
nafiz@debian-toolbox-12:~$ ping google.com
PING google.com (172.217.13.174) 56(84) bytes of data.
^C
--- google.com ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10219ms

nafiz@debian-toolbox-12:~$ exit
logout
nafiz@thinkbook:~$ distrobox-list 
ID           | NAME                 | STATUS             | IMAGE                         
e49bb5d6b107 | debian-toolbox-12    | Up 55 seconds ago  | quay.io/toolbx-images/debian-toolbox:12
nafiz@thinkbook:~$ distrobox --version
distrobox: 1.7.0
```

**Comment by 89luca89** [comment]
Still, I'm unable to reproduce

![image](https://github.com/89luca89/distrobox/assets/598882/dfde54e3-9671-49bd-a61a-52ba644be1a4)

**Comment by naclander** [comment]
@89luca89 this is still occurring on several container images I attempted. 

podman version 5.0.3
Ubuntu 24.10 -  6.11.0-13-generic

**Comment by mfilipe** [comment]
Same problem here! 

Podman 4.9.3
Distrobox 1.8.1.2
Ubuntu Server 24.04.2 LTS
RaspberryPi 5 16Gb
Kernel 6.8.0-1031-raspi

**Comment by mfilipe** [comment]
The root cause for this issue are `net.ipv4.ping_group_range` and `CAP_NET_RAW`.

Check how your host is configured:

```
$ sysctl net.ipv4.ping_group_range
net.ipv4.ping_group_range = 1   0
```

`1   0` means [the host won't allow rootless containers to use `ping`](https://github.com/systemd/systemd/pull/13141/files). Ubuntu, for example, has `1   0`, Fedora has `0   2147483647`. 

To enable, you have to change the `net.ipv4.ping_group_range` value:

```
$ sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
net.ipv4.ping_group_range = 0 2147483647
```

Now create a distrobox with `--cap-add=NET_RAW`:

```
distrobox create ... --additional-flags "--cap-add=NET_RAW"
```
