### ISSUE TITLE
[Error] "Distrobox create" uses Fedora38 when on Rawhide

### ISSUE THREAD

**Issue by trytomakeyouprivate** [89luca89/distrobox#1119]
I am not sure if this is because of rawhide, or because the automatically chosen version is outdated.

```
distrobox create
Image registry.fedoraproject.org/fedora-toolbox:38 not found.
Do you want to pull the image now? [Y/n]: 
```

```
Operating System: Fedora Linux 40 (Kinoite-beta)
KDE Plasma Version: 5.90.0
KDE Frameworks Version: 5.246.0
Qt Version: 6.6.1
Kernel Version: 6.7.0-0.rc6.20231222git24e0d2e527a3.52.fc40.x86_64 (64-bit)
```

**Comment by osalbahr** [comment]
FYI, this is because the default image is [hardcoded](https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-create#L56C10-L56C10) as 38.

**Comment by trytomakeyouprivate** [comment]
oh lol okay. I would like to discuss using the hosts Distro version is nothing is added?

https://github.com/89luca89/distrobox/pull/1156

That fixes the version for Fedora for now
