### ISSUE TITLE
[Error] Error in link at steamdeck installation page

### ISSUE THREAD

**Issue by BorMi** [89luca89/distrobox#1120]
**Describe the bug**
The link in  (https://distrobox.it/posts/steamdeck_guide/):
Install Podman

To install podman, [refer to the install guide](**https://distrobox.it/posts/steamdeck_guide/install_podman_static.md#**):

must point to https://distrobox.it/posts/install_podman_static.md

**Comment by 89luca89** [comment]
No that's correct like it is now, that are two separate guides

Thanks for reporting!
