### ISSUE TITLE
[Error] Cannot create voidlinux containers. fails to install basic packages

### ISSUE THREAD

**Issue by 0x006E** [89luca89/distrobox#1124]
**Describe the bug**
Distrobox fails on installing basic package section due to the install failing on the void linux container.

**To Reproduce**
1. Create a distrobox with image ghcr.io/void-linux/void-glibc-full:latest
2. Enter the distrobox

**Expected behavior**
A shell in the container

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[distrobox_enter_verbose.txt](https://github.com/89luca89/distrobox/files/13794478/distrobox_enter_verbose.txt)
[podman_logs.txt](https://github.com/89luca89/distrobox/files/13794479/podman_logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 4.8.2
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Gentoo
 - How did you install distrobox? emerge

**Additional context**
There seems to problem in the pam package in the container

**Comment by 89luca89** [comment]
Seems like the issue solved itself, CI is passing for that image
