### ISSUE TITLE
[Discussion] Installation instructions for Fedora Silverblue?

### ISSUE THREAD

**Issue by zine999** [89luca89/distrobox#1125]
Hi, sorry, I did my best to search the existing issues and documentation but couldn't figure out how to install this on Fedora Silverblue.

Are you supposed to use `rpm-ostree` or `flatpak` or...?

**Comment by alcir** [comment]
You can layer the package from the Fedora repository
`rpm-ostree install distrobox`
or install distrobox in your home with `curl` [^1]
`curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local`

Personally, on Silverblue, i prefer to avoid layering packages as much as possible.

[^1]: https://github.com/89luca89/distrobox#alternative-methods

**Comment by zine999** [comment]
Thanks @alcir! I guess this answers my questions so I'll close this issue. Would be nice to have official instructions somewhere in the docs or README, but at least now someone can search the issues and will hopefully find them.
