### ISSUE TITLE
[Error] error with distrobox-enter when --eval "XXX" in cmd contain backslashes

### ISSUE THREAD

**Issue by EndlessPeak** [89luca89/distrobox#1126]
**Describe the bug**
I encountered an issue where the `distrobox-enter` fails to execute correctly when there are backslashes `\` present in the environment variables within the cmd.
For example,when cmd contain a string `--env "FZF_COMPLETION_TRIGGER=\"` , it will say ./distrobox-enter: eval: line 541: syntax error near unexpected token `getent` ,where line 541 is `eval ${cmd}`, and cmd is generated by `generate_cmd` function.

**To Reproduce**
1. Define an environment variable within the cmd that includes backslashes.
2. Execute `distrobox-enter` 

**Expected behavior**
It should enter the docker or podman container directly.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
   I have tried both podman and docker.
 - Which version or podman, docker or lilipod?
   Podman 4.7.2 ; docker 24.0.5
 - Which version of distrobox?
   I have tried both 1.6.0.1 and 1.5.0.2.
 - Which host distribution?
  NixOS 23.11
 - How did you install distrobox?
  By Nix from Nixpkgs-unstable or write a single nix file to fetch it manually.

**Additional context**
Now my solution is use a simple replacement as follows:
```bash
modified_cmd="${cmd//\\/\\\\}"
eval ${modified_cmd}
```

But when the cmd contains two backslashes `\\`,this replacement will fail. Maybe it can be fixed more effectively.

**Comment by 89luca89** [comment]
This has been fixed in latest git version
