### ISSUE TITLE
[Error] kali-rolling:latest          Installing basic packages...           	 Error: An error occurred

### ISSUE THREAD

**Issue by firashacker** [89luca89/distrobox#1132]
i used kali in distrobox alot its always fine but recently it failed to initiate because of a missing package , this issue may not be related to distrobox i think its the docker image, but in case you can fix it by referencing other image ,version or so

apt sucks 

+ [ -n  ]
+ printf distrobox: Installing basic packages...\n
distrobox: Installing basic packages...
+ basename /bin/zsh
+ shell_pkg=zsh
+ [ zsh = ash ]
+ [ 0 -ne 0 ]
+ command -v find
/usr/bin/find
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ [ 0 -ne 0 ]
+ rm -f /etc/dpkg/dpkg.cfg.d/excludes
+ export DEBIAN_FRONTEND=noninteractive
+ apt-get update
Get:1 http://kali.download/kali kali-rolling InRelease [41.2 kB]
Get:2 http://kali.download/kali kali-rolling/contrib amd64 Packages [123 kB]
Get:3 http://kali.download/kali kali-rolling/main amd64 Packages [19.4 MB]
Get:4 http://kali.download/kali kali-rolling/non-free amd64 Packages [227 kB]
Fetched 19.8 MB in 3s (6837 kB/s)
Reading package lists...
+ apt-get install -y zsh
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libgdbm6 libgpm2 libncursesw6 zsh-common
Suggested packages:
  gdbm-l10n gpm zsh-doc
The following NEW packages will be installed:
  libgdbm6 libgpm2 libncursesw6 zsh zsh-common
0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 5278 kB of archives.
After this operation, 19.9 MB of additional disk space will be used.
Get:1 http://kali.download/kali kali-rolling/main amd64 libgdbm6 amd64 1.23-5 [72.5 kB]
Get:2 http://http.kali.org/kali kali-rolling/main amd64 libgpm2 amd64 1.20.7-10+b1 [14.2 kB]
Get:3 http://http.kali.org/kali kali-rolling/main amd64 libncursesw6 amd64 6.4+20231209-1 [135 kB]
Get:4 http://kali.download/kali kali-rolling/main amd64 zsh-common all 5.9-5 [4147 kB]
Get:5 http://http.kali.org/kali kali-rolling/main amd64 zsh amd64 5.9-5+b1 [909 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 5278 kB in 1s (4081 kB/s)
Selecting previously unselected package libgdbm6:amd64.
(Reading database ... 5332 files and directories currently installed.)
Preparing to unpack .../libgdbm6_1.23-5_amd64.deb ...
Unpacking libgdbm6:amd64 (1.23-5) ...
Selecting previously unselected package libgpm2:amd64.
Preparing to unpack .../libgpm2_1.20.7-10+b1_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.7-10+b1) ...
Selecting previously unselected package libncursesw6:amd64.
Preparing to unpack .../libncursesw6_6.4+20231209-1_amd64.deb ...
Unpacking libncursesw6:amd64 (6.4+20231209-1) ...
Selecting previously unselected package zsh-common.
Preparing to unpack .../zsh-common_5.9-5_all.deb ...
Unpacking zsh-common (5.9-5) ...
Selecting previously unselected package zsh.
Preparing to unpack .../zsh_5.9-5+b1_amd64.deb ...
Unpacking zsh (5.9-5+b1) ...
Setting up libgpm2:amd64 (1.20.7-10+b1) ...
Setting up zsh-common (5.9-5) ...
Setting up libncursesw6:amd64 (6.4+20231209-1) ...
Setting up zsh (5.9-5+b1) ...
Setting up libgdbm6:amd64 (1.23-5) ...
Processing triggers for debianutils (5.14) ...
Processing triggers for libc-bin (2.37-12) ...
+ deps=
			zsh
			apt-utils
			bc
			curl
			dialog
			diffutils
			findutils
			gnupg2
			less
			libnss-myhostname
			libvte-2.9*-common
			libvte-common
			lsof
			ncurses-base
			passwd
			pinentry-curses
			procps
			sudo
			time
			util-linux
			wget
			libegl1-mesa
			libgl1-mesa-glx
			libvulkan1
			mesa-vulkan-drivers
		
+ install_pkg=
+ apt-cache show zsh
+ install_pkg= zsh
+ apt-cache show apt-utils
+ install_pkg= zsh apt-utils
+ apt-cache show bc
+ install_pkg= zsh apt-utils bc
+ apt-cache show curl
+ install_pkg= zsh apt-utils bc curl
+ apt-cache show dialog
+ install_pkg= zsh apt-utils bc curl dialog
+ apt-cache show diffutils
+ install_pkg= zsh apt-utils bc curl dialog diffutils
+ apt-cache show findutils
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils
+ apt-cache show gnupg2
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2
+ apt-cache show less
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less
+ apt-cache show libnss-myhostname
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname
+ apt-cache show libvte-2.9*-common
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common
+ apt-cache show libvte-common
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common
+ apt-cache show lsof
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof
+ apt-cache show ncurses-base
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base
+ apt-cache show passwd
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd
+ apt-cache show pinentry-curses
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses
+ apt-cache show procps
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps
+ apt-cache show sudo
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo
+ apt-cache show time
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time
+ apt-cache show util-linux
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux
+ apt-cache show wget
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget
+ apt-cache show libegl1-mesa
E: No packages found
+ apt-cache show libgl1-mesa-glx
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx
+ apt-cache show libvulkan1
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1
+ apt-cache show mesa-vulkan-drivers
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1 mesa-vulkan-drivers
+ apt-get install -y zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1 mesa-vulkan-drivers
Reading package lists...
Building dependency tree...
Reading state information...
Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgl1-mesa-glx' has no installation candidate
+ [ 100 -ne 0 ]
Error: An error occurred
+ printf Error: An error occurred\n
+ [ -n  ]
+ printf distrobox: Installing basic packages...\n
distrobox: Installing basic packages...
+ basename /bin/zsh
+ shell_pkg=zsh
+ [ zsh = ash ]
+ [ 0 -ne 0 ]
+ command -v find
/usr/bin/find
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ [ 0 -ne 0 ]
+ rm -f /etc/dpkg/dpkg.cfg.d/excludes
+ export DEBIAN_FRONTEND=noninteractive
+ apt-get update
Hit:1 http://kali.download/kali kali-rolling InRelease
Reading package lists...
+ apt-get install -y zsh
Reading package lists...
Building dependency tree...
Reading state information...
zsh is already the newest version (5.9-5+b1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
+ deps=
			zsh
			apt-utils
			bc
			curl
			dialog
			diffutils
			findutils
			gnupg2
			less
			libnss-myhostname
			libvte-2.9*-common
			libvte-common
			lsof
			ncurses-base
			passwd
			pinentry-curses
			procps
			sudo
			time
			util-linux
			wget
			libegl1-mesa
			libgl1-mesa-glx
			libvulkan1
			mesa-vulkan-drivers
		
+ install_pkg=
+ apt-cache show zsh
+ install_pkg= zsh
+ apt-cache show apt-utils
+ install_pkg= zsh apt-utils
+ apt-cache show bc
+ install_pkg= zsh apt-utils bc
+ apt-cache show curl
+ install_pkg= zsh apt-utils bc curl
+ apt-cache show dialog
+ install_pkg= zsh apt-utils bc curl dialog
+ apt-cache show diffutils
+ install_pkg= zsh apt-utils bc curl dialog diffutils
+ apt-cache show findutils
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils
+ apt-cache show gnupg2
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2
+ apt-cache show less
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less
+ apt-cache show libnss-myhostname
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname
+ apt-cache show libvte-2.9*-common
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common
+ apt-cache show libvte-common
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common
+ apt-cache show lsof
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof
+ apt-cache show ncurses-base
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base
+ apt-cache show passwd
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd
+ apt-cache show pinentry-curses
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses
+ apt-cache show procps
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps
+ apt-cache show sudo
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo
+ apt-cache show time
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time
+ apt-cache show util-linux
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux
+ apt-cache show wget
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget
+ apt-cache show libegl1-mesa
E: No packages found
+ apt-cache show libgl1-mesa-glx
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx
+ apt-cache show libvulkan1
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1
+ apt-cache show mesa-vulkan-drivers
+ install_pkg= zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1 mesa-vulkan-drivers
+ apt-get install -y zsh apt-utils bc curl dialog diffutils findutils gnupg2 less libnss-myhostname libvte-2.9*-common libvte-common lsof ncurses-base passwd pinentry-curses procps sudo time util-linux wget libgl1-mesa-glx libvulkan1 mesa-vulkan-drivers
Reading package lists...
Building dependency tree...
Reading state information...
Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgl1-mesa-glx' has no installation candidate
+ [ 100 -ne 0 ]
+ printf Error: An error occurred\n
Error: An error occurred

**Comment by 89luca89** [comment]
Fixed in 11c327d6d56a972184189b04fa96944c13a4cd13
