### ISSUE TITLE
Problem launch app GUI from container rootfull

### ISSUE THREAD

**Issue by vincenzogianfelice** [89luca89/distrobox#1136]
My sytem OS: **Fedora 39** **(silverblue)** 
OS container: **Fedora39** (classic)
**Latest version of distrobox**

As the title, when tried launch an app from an rootfull container (but the user is not root in the container) nothing is launched as the root password is required to launch the container instance. I read the guide, I also used **zenity**, as per the guide.  But the same isn't the case.  How can I launch apps from a root container?

**Comment by 89luca89** [comment]
Hi @vincenzogianfelice 

to reproduce

1- install rootful container
2- install graphical app
3- export it (right?)
4- launch it

Am I understanding correctly?
