### ISSUE TITLE
[Suggestion] Add an `export --list` command

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [89luca89/distrobox#1137]
**Is your feature request related to a problem? Please describe.**

No easy way to know what bins/apps have been exported from a box.

**Describe the solution you'd like**

Add flag `--list` as option to `distrobox-export`, optionally with `-b` or `-a`. Output a list of `--app`s or `--bin`s that have previously been exported.

**Describe alternatives you've considered**

- Keeping a hand-maintained record of what is exported from each container.
- Personal memory; this is just a big fail, especially if handling distroboxen on multiple machines.

**Comment by 89luca89** [comment]
Thanks for the idea @ParaplegicRacehorse !
