### ISSUE TITLE
[Error] Can't login to Slack in fedora container

### ISSUE THREAD

**Issue by cmalvi** [89luca89/distrobox#1138]
**Describe the bug**
Slack installed in a fedora container, it open the browser to try to login but when xdg-open call slack after login on browser it stays on the login screen, seems like xdg-open call slack without passing it the url

**To Reproduce**
 - install slack on fedora container (rpm)
 - launch slack and click on login button
 - login using the browser
 - see slack regain focus without do anything

**Expected behavior**
slack login correctly

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - podman
 - Which host distribution? bazzite

**Comment by juhp** [comment]
The browser is running in the host?

**Comment by cmalvi** [comment]
Tried with browser from host and inside the same container, same result

**Comment by 89luca89** [comment]
Hi @cmalvi 

I think you also need to `distrobox-export` slack from inside the container
In order for `xdg-open` from the host, to re-open the slack inside the container

**Comment by cmalvi** [comment]
Already did it with same result.

I give it a new try creating a new container, now it works only using browser outside the container

**Comment by 89luca89** [comment]
@cmalvi it works then by exporting slack and using the browser from the host

I'm closing as solved then
