### ISSUE TITLE
[Error] init_hook with quotes doesn't work

### ISSUE THREAD

**Issue by flexagoon** [89luca89/distrobox#1141]
**Describe the bug**
I put the following init_hooks in distrobox.ini:

```ini
init_hooks=sdkmanager "tools" "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest" "platform-tools";
```

However, distrobox removes quotes from the command, causing it to fail.

**To Reproduce**
Add any command with quotes to init_hooks

**Expected behavior**
Quotes are preserved

**Logs**

The important part is

```console
DEBU[0000] Called create.PersistentPostRunE(podman [...] ; sdkmanager tools platforms;android-34 build-tools;34.0.0 cmdline-tools;latest platform-tools;)
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.8.1
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? uBlue (Fedora Silverblue)
 - How did you install distrobox? Comes bundled with uBlue

**Comment by flexagoon** [comment]
The only workaround I managed to find is using this:

```ini
init_hooks=printf $(echo 'sdkmanager \\\\x22tools\\\\x22 \\\\x22platforms\\;android-34\\\\x22') | sh;
```

Which is... Well, I don't think I have to say anything here.

**Comment by Vitmark97** [comment]
I struggled with this as well. I wrote a proper .sh script, encoded it with base64 and decoded it in the pre_init_hooks. If your script is large, you can add compression into the mix so that the base64 is shorter.

## Example
preinithooks.sh
```sh
#!/bin/sh
echo "Hello"
```

```sh
base64 -w0 preinithooks.sh
```
```ini
pre_init_hooks="echo IyEvYmluL3NoCmVjaG8gIkhlbGxvIgo= | base64 -d | sh;"
```

### With compression
```sh
zstd -c preinithooks.sh | base64 -w0
```
```ini
pre_init_hooks="echo KLUv/SQXuQAAIyEvYmluL3NoCmVjaG8gIkhlbGxvIgqH3ixW | base64 -d | zstd -d | sh;"
```

**Comment by flexagoon** [comment]
@Vitmark97 that is certainly simpler than my workaround, at the expense of not being able to see what the command does directly from the config file... This kind of workarounds shouldn't be needed though.

I ended up just making a [custom container image](https://github.com/flexagoon/flutterbox/blob/main/Containerfile) that does all of the required stuff at build time. I think that's the best option for now, and in many cases it's probably even better than using init hooks.

If you want to do this check out the [boxkit](https://github.com/ublue-os/boxkit) project which I used to make my image, it provides a GitHub Action that automatically builds, signs and publishes your image every week

**Comment by 89luca89** [comment]
Hi @flexagoon 

Have you tried escaping them and using quotes for the whole string?

Like:

`init_hooks="sdkmanager \"tools\" \"platforms;android-34\" \"build-tools;34.0.0\" \"cmdline-tools;latest\" \"platform-tools\"";`

let me know if this works, if it does we can document this behaviour
