### ISSUE TITLE
export syncthing service doesn't work

### ISSUE THREAD

**Issue by alcir** [89luca89/distrobox#115]
Looking at the examples, the command 
`distrobox-export -v --service syncthing --extra-flags "--allow-newer-config"`
currently exports the `/usr/lib/systemd/system/syncthing@.service` systemd file.
But it doesn't work.
I'm not a systemd expert.
But I think that `syncthing@.service` is supposed to work as a system service, but under a specific user, despite if he is logged in or not.
If we want to use user systemd unit inside the user home directory, we should export `/usr/lib/systemd/user/syncthing.service`

**Comment by 89luca89** [comment]
Thanks @alcir 

If we specify 

` distrobox-export -v --service syncthing.service --extra-flags "--allow-newer-config"`

it works as expected, will update the docs :+1: thanks!
