### ISSUE TITLE
[Suggestion]: Use host clipboard?

### ISSUE THREAD

**Issue by briandipalma** [89luca89/distrobox#1152]
**Is your feature request related to a problem? Please describe.**

I can't yank text from neovim into the host.

**Describe the solution you'd like**

The container clipboard to be replaced with the host one.

**Describe alternatives you've considered**

No idea how to get around this TBH.

**Comment by briandipalma** [comment]
OK so it looks like you just need to install xsel on X.org hosts is that correct?

**Comment by 89luca89** [comment]
xorg/wayland integration is already there, for neovim either use xsel or use the right registry

**Comment by briandipalma** [comment]
Cool, I raised a useful tips PR https://github.com/89luca89/distrobox/pull/1225 for this. It wasn't totally obvious to me so it might help others.
