### ISSUE TITLE
[Error] Distrobox assemble documentation is inconsistent with functionality

### ISSUE THREAD

**Issue by uncomfyhalomacro** [89luca89/distrobox#1154]
# System Information

**OS**: openSUSE Tumbleweed
**Distrobox version**: 1.16.0.1

# Scenario

`distrobox assemble` is a new way to create and configure distrobox instances through a config file in `ini` format. By default, it looks for `distrobox.ini` from where the command was invoked unless `--file` flag is used.

# Bug

A config file like this will error with a message that they cannot find `/usr/bin/typst/usr/bin/julia`. 

```ini
[tumbleweed]
home=/home/uncomfy/development/projects
replace=true
additional_packages="juliaup nodejs-common rustup go hare terminfo foot-extra-terminfo typst"
exported_bins="/usr/bin/typst /usr/bin/julia"
```

It seems the `exported_bins` section was not tested or overlooked yet the documentation
mentions that if there are multiple entries, you should quote it while separated by a space.

## The fix

The following config file works as long as each exported bins have only one entry only.
```ini
[tumbleweed]
home=/home/uncomfy/development/projects
replace=true
additional_packages="juliaup nodejs-common rustup go hare terminfo foot-extra-terminfo typst"
exported_bins="/usr/bin/typst"
exported_bins="/usr/bin/julia"
exported_bins_path="/home/uncomfy/.local/bin"
```

# Other discovered bugs not mentioned

`exported_bins_path` does not expand `~` so `~/.local/bin` will error. So the temporary workaround is a full absolute path.

**Comment by ebits21** [comment]
Same as #1083 with a possible fix with #1084
