### ISSUE TITLE
[Discussion] Fedora images require cracklib-dicts to setup passwords

### ISSUE THREAD

**Issue by kerneis-anssi** [89luca89/distrobox#1158]
When creating a rootful container from a fedora image (eg. `fedora:latest` or `fedora-toolbox:39`), setting up a password on first boot fails with the following error message:

```
⚠️  First time user password setup ⚠️ 
Changing password for user kerneis.
New password: 
Retype new password: 
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Password quality check failed: The password fails the dictionary check - error loading dictionary
```

It is a bad situation because you end up logging inside the container without having set the password (and are asked again on every connection attempt).

The issue would occur for rootless containers as well I guess, except you never really need to setup the password there.

This can be worked around by adding `cracklib-dicts` to the list of additional packages in `distrobox create`. Maybe this should be documented somewhere, or even taken care of automatically by distrobox? At least this issue can help future frustrated users, it took me a while to figure out.

Background:
- https://github.com/cockpit-project/cockpit/issues/5684
- https://bugzilla.redhat.com/show_bug.cgi?id=1410450
- https://fedoraproject.org/wiki/Features/PasswordQualityChecking

**Comment by ahnaf-tahmid-chowdhury** [comment]
Yes. I have faced the same issue while using docker. But, there is no issue while using podman.

**Comment by kerneis-anssi** [comment]
I don’t think it’s related to Docker vs. podman. I’m using a Fedora Silverblue 39 as a host OS with `distrobox` as the sole layered package, and I don’t have docker installed. It is probably related to the image used, but if such is the case, I think distrobox should either install the required packages on first `enter` or at least document what needs to be done for images to work as rootful containers (like it does for `--init`).
