### ISSUE TITLE
[Suggestion] distrobox assemble rm should remove exported binaries ALWAYS

### ISSUE THREAD

**Issue by jansenm** [89luca89/distrobox#1160]
**Is your feature request related to a problem? Please describe.**

distrobox assemble allows me to specify `exported_bins_path`as the directory for exported binaries. distrobox assemble create honors that directory. distrobox assemble rm doesn't.

**Describe the solution you'd like**

distrobox assemble rm should forward the configured path to distrobox rm so that command can use it instead of the default path to look for binaries to delete (lines 310+)

**Describe alternatives you've considered**

I have to delete them after distrobox assemble rm manually

**Additional context**

**Comment by 89luca89** [comment]
Hi @jansenm 

this is the behaviour of `distrobox rm`, I cannot know what are all the custom `export-path` used, so `rm` will un-export automatically only on the default paths
