### ISSUE TITLE
gnome-session --builtin is no longer available with GNOME 46

### ISSUE THREAD

**Issue by jbicha** [89luca89/distrobox#1161]
https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md

recommends using `gnome-session --builtin` but gnome-session 46 Alpha no longer includes [that option](https://gitlab.gnome.org/GNOME/gnome-session/-/commit/76534bcc5)

**Comment by 89luca89** [comment]
Hi @jbicha what is the possible solution for this?

**Comment by jbicha** [comment]
I don't know. I've never used distrobox and only posted this issue while searching Debian for anything that used gnome-session --builtin . I don't use gnome-session --builtin either.

I know that the Budgie developers have recently created budgie-session, a soft fork of gnome-session to keep that option.
