### ISSUE TITLE
Notice: We're going to move Ubuntu and Arch Linux toolbx-images to the new upstream location

### ISSUE THREAD

**Issue by travier** [89luca89/distrobox#1167]
See pull requests:
- https://github.com/toolbx-images/images/pull/82
- https://github.com/toolbx-images/images/pull/84

We're going to stop updating and will later delete the Arch Linux & Ubuntu images from the toolbx-images repository in favor of the upstream images.

**Comment by travier** [comment]
I had initially reported that https://github.com/Dvlv/BoxBuddyRS/issues/29. Not sure where / if the images are hardcoded anywhere here.

**Comment by 89luca89** [comment]
Thanks @travier for the update!

Here all tests and the completion is generated from the `compatibility.md` file table :+1:

**Comment by travier** [comment]
Great! Thanks
