### ISSUE TITLE
Lilypod

### ISSUE THREAD

**Issue by ozky84** [89luca89/distrobox#1175]
Documention is bit weird as Lilipod is supported in Distrobox but in real is not?
Why is this says suportted even is not?
https://github.com/89luca89/lilipod/issues/8

**Comment by ozky84** [comment]
@89luca89
???

**Comment by ozky84** [comment]
Would be good and nice to answer these bug reports...
Take a look this closed bug Lilipod
https://github.com/89luca89/lilipod/issues/8

**Comment by 89luca89** [comment]
Hi @ozky84 

Bug reports are answered when I have time, and will
No need to bump or tagging

Lilipod is supported by version 1.6+ and that post is from BEFORE release
