### ISSUE TITLE
[Error] Cannot enter images created with `--nvidia`

### ISSUE THREAD

**Issue by 00sapo** [89luca89/distrobox#1177]
**Describe the bug**
After having created an instance with `--nvidia`, entering it fails

**To Reproduce**
```
federico@cucchia ~ [1]> distrobox create -n archlinux -i docker.io/library/archlinux:latest --nvidia
Creating 'archlinux' using image docker.io/library/archlinux:latest	[ OK ]
Distrobox 'archlinux' successfully created.
To enter, run:

distrobox enter archlinux

federico@cucchia ~> distrobox enter archlinux
Starting container...                   	[ OK ]
Installing basic packages...            	[ OK ]
Setting up devpts mounts...             	[ OK ]
Setting up read-only mounts...          	[ OK ]
Setting up read-write mounts...         	[ OK ]
Setting up host's sockets integration...	[ OK ]
Setting up host's nvidia integration... 	
 Warning: cannot create mount target file: /usr/lib64/nvidia/current/libnvidia-ptxjitcompiler.so.525.147.05 Error: An error occurred
federico@cucchia ~ [1]> file /usr/lib64/nvidia/current/libnvidia-ptxjitcompiler.so.525.147.05
/usr/lib64/nvidia/current/libnvidia-ptxjitcompiler.so.525.147.05: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6df05862ec63b25b1ef12bd8c8f1c38bf6cbb1ff, stripped
federico@cucchia ~> ls -l /usr/lib64
total 8
lrwxrwxrwx 1 root root 42 Sep 30 10:31 ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2*
lrwxrwxrwx 1 root root 33 Jan 27 12:09 nvidia -> /usr/lib/x86_64-linux-gnu/nvidia//
federico@cucchia ~> distrobox --version
distrobox: 1.6.0.1
federico@cucchia ~> podman --version
podman version 4.3.1
```

Logs are attached.ls

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.3.1
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Debian 12
 - How did you install distrobox? `curl` main branch of the repo
[podman.log](https://github.com/89luca89/distrobox/files/14072124/podman.log)
[distrobox.log](https://github.com/89luca89/distrobox/files/14072125/distrobox.log)

**Comment by 89luca89** [comment]
@00sapo hi, can you try with latest git version? it has various fixes for nvidia stuff

**Comment by 89luca89** [comment]
@00sapo did it work with git version?

**Comment by 00sapo** [comment]
Hi, I tried right now with the latest commit but I still get the same error
