### ISSUE TITLE
[Discussion] Can't figure out how to log in to sites that VSCode redirects to.

### ISSUE THREAD

**Issue by ukizet** [89luca89/distrobox#1180]
Sorry for the bad title, I don't know how to describe it better.

So I have this problem. When I click the login button (for example in Figma plugin) in VSCode (in distrobox), I am redirected to the site in my default browser. Then when the browser wants to open VSCode to continue logging in, either nothing happens (unless I use distrobox-export --app code) or a new VSCode window opens and nothing happens there either. How to solve this?

"Describe the solution you'd like": I would like the login to work normally, i.e. the same as in the flatpak version, or the same as if VSCode was installed on my host system.

For me, the alternative is to use VSCode flatpak, but it is very slow to connect to containers.

**Comment by 89luca89** [comment]
You need to export the VSCode from the container (export --app) or the browser won't know how to call back it
