### ISSUE TITLE
Apps working when launched from container, but not host.

### ISSUE THREAD

**Issue by pseudofakee** [89luca89/distrobox#12]
Hi there,

Great tool!

I am using Fedora Silverblue and have set up an arch container for software access.

I'm seemingly unable to launch applications once I have exported them with 

```distrobox-export --app```

The .dekstop files go across fine, and they come up in the launcher ...yet they never actually _launch_. They run fine when launched from the container terminal.

Examples I have tested are Atom and GNOME Podcasts.

I may be missing something fundamental, as I am relatively new to container workflows.

Cheers.

**Comment by 89luca89** [comment]
Hey @pseudofakee thanks forma the big reporter, can you post the desktop file generated?  to check if there are some errors in the file generation

Thanks!

**Comment by pseudofakee** [comment]
Yup

file:///var/home/joseph/.local/share/applications/atom.desktop
file:///var/home/joseph/.local/share/applications/org.gnome.Podcasts.desktop

**Comment by pseudofakee** [comment]
```
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century
GenericName=Text Editor
Exec=/usr/local/bin/distrobox-enter --name Arch -e  env ATOM_DISABLE_SHELLING_O>
Icon=atom
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
StartupWMClass=atom

```

**Comment by 89luca89** [comment]
> 

Thanks

Executing directly from your host's terminal:

`/usr/local/bin/distrobox-enter -v --name Arch -e  env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom`

Does it work? If not can you try pasting the output? Thanks!

**Comment by pseudofakee** [comment]
[atom_error.txt](https://github.com/89luca89/distrobox/files/7655943/atom_error.txt)

**Comment by 89luca89** [comment]
Mmmh can you try executing without the

 `env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false ` 

Could be because it's not handling well multiple commands passed to the container

**Comment by pseudofakee** [comment]
```
/usr/local/bin/distrobox-enter -v --name Arch -e /usr/bin/atom
```

Returns
[atom_error_2.txt](https://github.com/89luca89/distrobox/files/7655993/atom_error_2.txt)

dropping the -e gets me into the container (without the ability to find /usr/bin/atom so it fails there )

**Comment by 89luca89** [comment]
> ```
> /usr/local/bin/distrobox-enter -v --name Arch -e /usr/bin/atom
> ```
> 
> Returns [atom_error_2.txt](https://github.com/89luca89/distrobox/files/7655993/atom_error_2.txt)
> 
> dropping the -e gets me into the container (without the ability to find /usr/bin/atom so it fails there )

And doesn't work still right? any other error? I mean after the `+ '[' 0 -ne 0 ']'` on the terminal?

**Comment by pseudofakee** [comment]
[atom_error_3.txt](https://github.com/89luca89/distrobox/files/7656021/atom_error_3.txt)

**Comment by 89luca89** [comment]
@pseudofakee  Had to install `atom` to dig into this :smiley: 

Not really sure how `distrobox` should handle this, but the problem here is that `atom` is not really... well `atom` 

`/usr/bin/atom` is a script that launcher electron9 to then launch node and so on, so it launches, forks and exits
this works if you're **inside** the container and launch atom because your environment is still up and running (you're inside it)

That is why I didn't see any error from distrobox, podman nor atom itsef :smile: 

if you launch directly with `distrobox-enter --name Arch -e /usr/bin/atom` the main PID (the script) exits before electron can do his thing, so the container exits

the solution here is to launch `/usr/bin/atom -f` so in **foreground** then it works both using the desktop file and directly launching the command with `distrobox-enter`

**Comment by pseudofakee** [comment]
Awesome, you got it ;)

It makes sense, I was also having that issue when trying to call the synth 'Aeronaut' which is also electron based.

Thanks for the work !

**Comment by 89luca89** [comment]
I'll close this issue then @pseudofakee if you have any idea on how to improve distrobox to handle these cases don't hesitate to open an issue for a feature request 😄

**Comment by 89luca89** [comment]
Created a feature request to add extra flags to exported apps and services to fix situation like this one
Thanks @pseudofakee for bringing up this type of problem :smile:
