### ISSUE TITLE
[Suggestion] Officially support the `linuxserver/steamos` container

### ISSUE THREAD

**Issue by spkane** [89luca89/distrobox#1202]
**Is your feature request related to a problem? Please describe.**

I am using `distrobox` on the Steam Deck and in some instances, I would like to use an actual SteamOS (modified Arch Linux) container with it instead of a generic Arch Linux container, primarily so that I can install libraries that some application might need, even though the real SteamDeck root filesystem is read-only.

**Describe the solution you'd like**

In general, using the `linuxserver/steamos` container, an Arch Linux derivative, works, but I had to tweak a few things. There is a conflict with the pre-installed `clang-libs`, so I needed to uninstall those and the two packages that were dependent on them to get the `enter` command to work.

There is also a warning about user creation since there is already a UID 1000 inside the container.

**Describe alternatives you've considered**

I can get this generally working by running:

```sh
distrobox-create --image ghcr.io/linuxserver/steamos:latest --name steamos --pre-init-hooks "sudo pacman -R --noconfirm opencl-mesa clang-libs lib32-opencl-mesa ; true”
distrobox-enter steamos
```

**UPDATE 2024-02-11**:
This was originally tested with the version of `distrobox` that is currently shipped on the Steam Deck. `distrobox: 1.4.2.1`. I have since tested it on the Steam Deck with `distrobox: 1.6.0.1` and there are no errors during the setup, but I have not done further testing beyond that yet.

**Comment by 89luca89** [comment]
Thanks @spkane this is great!

And inspired me to do some experiments to run the whole session in nested gamescope, it mostly works with GPU accelleration and all, that's sweet!

Thanks!

**Comment by spkane** [comment]
Glad that it worked out well.

I only wish there was a container that could be easily mapped to the specific SteamOS versions (e.g. 3.5.7) that run on the SteamDeck. Something like that along with distrobox would make for a very simple and convenient way to build apps for the SteamDeck without needing to mess with a read-write root filesystem and installing additional libraries and such.

**Comment by JuanJ67m** [comment]
can not run SteamOS in Fedora 42 Silverblue with Distrobox.

I used:

```
wicho@fedora-jtm:~$   distrobox create \
  --image ghcr.io/linuxserver/steamos:latest \
  --name SteamOS \
  --unshare-all \
  --home ~/SteamOS \
  --pre-init-hooks "sudo pacman -R --noconfirm opencl-mesa clang-libs lib32-opencl-mesa ; true"
 
Creating 'SteamOS' using image ghcr.io/linuxserver/steamos:latest	 [ OK ]
Distrobox 'SteamOS' successfully created.
To enter, run:

distrobox enter SteamOS


wicho@fedora-jtm:~$ distrobox enter SteamOS
Starting container...                   	
Container Setup Failure!
```

... the the container do not run
