### ISSUE TITLE
[Discussion] Distrobox is acting differently, and kind of broken, depending on how I launch it

### ISSUE THREAD

**Issue by josephtole** [89luca89/distrobox#1206]
I am building a custom container to fit my needs. The code is available [here](https://github.com/jetole/my-workspace) and the container images are available [here](https://quay.io/repository/josephtole/my-workspace).

When I launch the container via distrobox from my host shell, everything works as expected. When I launch the container via distrobox as the custom command in my gnome terminal, a few weird things happen that I have not been able to find the root cause for. There are probably more issues but these ones are the only ones I have noticed so far is:

-  Nerd font glyphs are not appearing in the prompt or my custom tmux theme
    - I have configured gnome terminal to use the same font in that profile as all of my other profiles that work  when I manually launch the container via distrobox
    -  `~/.local/share/fonts` from the host is availabe to the container but I don't think this would make a difference
- `apt` and `nvim` seem to be missing

I would appreciate any help and thanks in advance.

P.S. I am running distrobox 1.5.0.2, installed into `/opt/distrobox` on Fedora SilverBlue 39.
P.P.S. The blueish green terminal screenshot is me launching distrobox from the host terminal and the blackish terminal screenshot is me launching distrobox as the command from the gnome terminal profile.

![Screenshot from 2024-02-13 21-40-46](https://github.com/89luca89/distrobox/assets/63594401/0a883266-bbad-4947-b9f3-cc64eb1e8dbb)
![Screenshot from 2024-02-13 21-41-22](https://github.com/89luca89/distrobox/assets/63594401/4d9719c5-64c7-4b19-b9c6-8c46095fc371)

**Comment by jetole** [comment]
If I run this command in a terminal or change it to the command my gnome terminal profile runs, it seems like glyphs appear and apt and nvim work: `podman run -it --rm local/my-workspace`.

**Comment by jetole** [comment]
> Have you tried using a different container image to determine if the cause is the custom image or the terminal?
> 
> > apt and nvim seem to be missing
> 
> This is probably a PATH issue, check the path variable (i like to use `echo "$PATH" | tr ':' '\n'`)

Thank you but these aren't the causes.

**Comment by josephtole** [comment]
@89luca89 Would you have any insight on what may be the root cause of the problem?
