### ISSUE TITLE
[Error] Nvidia integration is not working

### ISSUE THREAD

**Issue by Boria138** [89luca89/distrobox#1217]
**Describe the bug**
When creating a container with the --nvidia option distrobox run crashes with an error when starting integration 

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Everything should work without error 

**Logs**
+ dest_file=/usr/lib/x86_64-linux-gnu/nvidia_535.154.05/libnvidia-vulkan-producer.so
+ [ -e /usr/lib/x86_64-linux-gnu/nvidia_535.154.05/libnvidia-vulkan-producer.so ]
+ type=file
+ [ -L /run/host/usr/lib64/nvidia_535.154.05/libnvidia-vulkan-producer.so ]
+ type=link
+ [ link = link ]
+ dirname /usr/lib/x86_64-linux-gnu/nvidia_535.154.05/libnvidia-vulkan-producer.so
+ mkdir -p /usr/lib/x86_64-linux-gnu/nvidia_535.154.05
+ cp -d /run/host/usr/lib64/nvidia_535.154.05/libnvidia-vulkan-producer.so /usr/lib/x86_64-linux-gnu/nvidia_535.154.05/libnvidia-vulkan-producer.so
cp: '/run/host/usr/lib64/nvidia_535.154.05/libnvidia-vulkan-producer.so' and '/usr/lib/x86_64-linux-gnu/nvidia_535.154.05/libnvidia-vulkan-producer.so' are the same file

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? - podman
 - Which version or podman, docker or lilipod? - 4.8.3
 - Which version of distrobox? - 1.6.0.1
 - Which host distribution? - ALT Linux
 - How did you install distrobox? - self build

**Comment by 89luca89** [comment]
Hi @Boria138 this is already fixed in latest git version, please use that and try again, thanks

**Comment by Boria138** [comment]
> Hi @Boria138 this is already fixed in latest git version, please use that and try again, thanks

Ah, can I please know in which committee this was fixed so I can port it with a patch, I plan to build distrobox in alt linux so it would be more convenient for me to backport the fix than to use the git version.

**Comment by Boria138** [comment]
Oh, I found it, then I guess we can close the bug.

**Comment by 89luca89** [comment]
Cool glad it is fixed then :+1:
