### ISSUE TITLE
[Error] Garuda Linux /sys is mounted but not shared

### ISSUE THREAD

**Issue by djkato** [89luca89/distrobox#1220]
Trying to run a distro, I get `Error response from daemon: path /sys is mounted on /sys but it is not a shared or slave mount`

# To Reproduce
- use Garuda dragonised
- `sudo pacman -S distrobox`
- (Maybe have docker and docker desktop installed)
- `distrobox create -i ubuntu:23.04 --name ubuntu`. 
- `distrobox enter ubuntu`- This returned error
`Error response from daemon: Mounts denied:
The path /tmp is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.
Error: failed to start containers: ubuntu`
- Add `/tmp` to file sharing resources via docker desktop
- running it again, error:`Error response from daemon: path /sys is mounted on /sys but it is not a shared or slave mount
Error: failed to start containers: ubuntu`

after that I tried adding /sys via docker desktop and doing `sudo mount --make-shared /sys` (based on #192 ) but neither helped

**Expected behavior**
it enters

## Logs
```
+ '[' -z ubuntu ']'
+ '[' '!' -t 0 ']'
+ '[' '!' -t 1 ']'
+ case "${container_manager}" in
+ command -v podman
+ command -v podman-launcher
+ command -v docker
+ container_manager=docker
+ command -v docker
+ '[' 1 -ne 0 ']'
+ container_manager='docker --log-level debug'
+ '[' 0 -ne 0 ']'
+ container_home=/home/djkato
+ container_path=/home/djkato/.local/bin:/home/djkato/.bun/bin:/home/djkato/.local/share/bob/nvim-bin:/home/djkato/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin
+ '[' 0 -ne 0 ']'
+ container_status=unknown
++ docker --log-level debug inspect --type container --format 'container_status={{.State.Status}};
{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}' ubuntu
+ eval 'container_status=created;
container_home="/home/djkato";
container_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
++ container_status=created
++ container_home=/home/djkato
++ container_path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ '[' created = unknown ']'
+ '[' created '!=' running ']'
+ docker --log-level debug start ubuntu
Error response from daemon: path /sys is mounted on /sys but it is not a shared or slave mount
Error: failed to start containers: ubuntu
+ cleanup
+ rm -f /home/djkato/.cache/.ubuntu.fifo
+ '[' -n '' ']'
+ '[' 1 -eq 1 ']'
+ docker --log-level debug logs ubuntu
```

No docker logs present, docker only throws `(HTTP code 500) server error - Cannot restart container 1ba1c8eee52abb92f1ecd25690e6517ecf6ccf4f394cd7c7d53bee78e398be52: path /sys is mounted on /sys but it is not a shared or slave mount`

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Yes
 - Which version or podman, docker or lilipod? docker desktop: 4.26.1, engine: 24.0.7
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Garuda Linux
 - How did you install distrobox? `sudo pacman -S distrobox`

**Comment by 89luca89** [comment]
Hi @djkato 

Garuda is not one of the officially supported distros, nor tested upon

Also in the docs there is clearly the solution at the very same error message that you posted:

https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes
