### ISSUE TITLE
[Error] Error starting container ubuntu on Ubuntu 22.04 with WSL 2

### ISSUE THREAD

**Issue by alexandreqo** [89luca89/distrobox#1222]
**Describe the bug**
When trying to enter the container named "ubuntu-teste" using distrobox-enter on Ubuntu 22.04 WSL. The specific error message reads:
Error response from daemon: path /tmp is mounted on / but it is not a shared or slave mount
Error: failed to start containers: ubuntu-teste

**To Reproduce**
Steps to reproduce the behavior
1. Open a terminal on Ubuntu 22.04 WSL.
2. Run the commands:
3. ```
distrobox create --image ubuntu:22.04 --name ubuntu-teste
  distrobox-enter --name ubuntu-teste.

```
**Expected behavior**
The distrobox-enter command should successfully launch the container named "ubuntu-teste".

**Logs**
[logerr.txt](https://github.com/89luca89/distrobox/files/14350562/logerr.txt)


**Desktop (please complete the following information):**
Operating System: Ubuntu 22.04 WSL 2
distrobox version : 1.6.0.1

**Additional context**
Add any other context about the problem here.

**Comment by 89luca89** [comment]
Please read the documentation. there is specifically the workaround for this bug in the compatibility section.
