### ISSUE TITLE
[Error] Problem with extended grep regexps in distrobox-assemble

### ISSUE THREAD

**Issue by pavelxdd** [89luca89/distrobox#1227]
Commit https://github.com/89luca89/distrobox/commit/cca85a25db935ad93dd2794287c42448d82757e0
changed the `grep -q` to `grep -E` for `init_hooks` parsing (but not for `pre_init_hooks` ...), which broke the expressions matching.

In extended mode you don't need to escape the `\{0,1\}` - it should be `{0,1}`.

Compare:

````bash
> echo "1 2 3;" | grep -E ';[[:space:]]\{0,1\}$' && echo 1 || echo 0
0
````

````bash
> echo "1 2 3;" | grep -E ';[[:space:]]{0,1}$' && echo 1 || echo 0
1 2 3;
1
````

````bash
> echo "1 2 3;" | grep -q ';[[:space:]]\{0,1\}$' && echo 1 || echo 0
1
````

I think these lines should be changed back to `grep -q`. At least the code block should be the same as `pre_init_hooks` parsing.

**Comment by 89luca89** [comment]
Thanks a lot @pavelxdd for the report :smile:
