### ISSUE TITLE
[Error] False positive grep match in distrobox-assemble

### ISSUE THREAD

**Issue by pavelxdd** [89luca89/distrobox#1228]
If `distrobox.ini` contains `init_hooks` after the `pre_init_hooks` lines, then this line
https://github.com/89luca89/distrobox/blob/e9f9eff487464b62bb48f9d05054aaa3e8e7dbed/distrobox-assemble#L469
returns false positive, which prepends the `init_hooks` list with IFS symbol. Which laters results in init_hooks arguments prepended with `&&` in the beggining so there's an error that `&&` is unexpected in line `: ; && cmd ...`

I think this grep should be `"^${key}=" "${tmpfile}"` (note the line beginning `^` expression) which also fixes the issue described above. If hooks commands contain string which match the `distrobox.ini` keys, there will be no false positives.

**Comment by 89luca89** [comment]
Thanks a lot @pavelxdd for the report :smile:
