### ISSUE TITLE
Create an option to enter custom home dir by default

### ISSUE THREAD

**Issue by RealVishy** [89luca89/distrobox#1229]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i enter my distrobox using the Ptyxis terminal and it enters my user's home dir instead of the custom home dir i've specified in my distrobox assemble.

**Describe the solution you'd like**
Add an bool option in distrobox assemble to specify if the distrobox opens in your home dir or the custom home dir by default.
Ideally it would be enabled by default if you specify a custom home dir.

**Describe alternatives you've considered**
I tried using an init hook to cd into the custom dir of my distrobox but it didn't appear to work. I'm not sure of any alternatives other than setting a custom default location in my terminal?
**Additional context**

**Comment by paidhi** [comment]
I set `skip_workdir=1` in `${HOME}/.config/distrobox/distrobox.conf` to achieve this.

**Comment by 89luca89** [comment]
Correct answer
