### ISSUE TITLE
[Discussion] Unable to open /dev/kfd read-write: Permission denied when installing ROCm in distrobox

### ISSUE THREAD

**Issue by wayneyaoo** [89luca89/distrobox#1230]
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
GPU: AMD ATI Radeon RX 6600/6600 XT/6600M
Distrobox version: 1.6.0.1
Podman version: 4.9.3

I'm trying to install ollama on a distrobox running local LLM with my AMD GPU. As a pre-requisite, I need to install `rocm` to compile `ollama` specifically for AMD GPU. So `rocm` needs to be on the distrobox too. But when I ran `rocminfo`, it errors the following:

```
ROCk module is loaded
Unable to open /dev/kfd read-write: Permission denied
<myusername> is not member of "nogroup" group, the default DRM access group. Users must be a member of the "nogroup" group or another DRM access group in order for ROCm applications to run successfully.
``` 

I manage to get rid of the second error by adding myself to the `nogroup` group but the second line first error `Unable to open /dev/kfd read-write: Permission denied` is always there. I assume this blocks the `ollama` compilation.

`sudo rocminfo` doesn't help either. I suspect it's the device permission that didn't get passed in but did quite some search but no luck. What should I do next? Thanks very much for any help!

Here's how I create the box:

ollama.ini
```ini
[ollama-box]
image=ubuntu:22.04
init=false
additional_packages="build-essential libtcmalloc-minimal4 wget git python3 python3-venv libgl1 libglib2.0-0"
init_hooks="groupadd render;"
init_hooks="groupadd video;"
init_hooks="usermod -aG render,video $LOGNAME;"
init_hooks="apt update -y;"
init_hooks="apt upgrade -y;"
init_hooks="cd /tmp && wget https://repo.radeon.com/amdgpu-install/5.6.1/ubuntu/jammy/amdgpu-install_5.6.50601-1_all.deb && apt install -y ./amdgpu-install_5.6.50601-1_all.deb && rm amdgpu-install_5.6.50601-1_all.deb;"
init_hooks="amdgpu-install --usecase=rocm --no-dkms -y;"
nvidia=false
pull=false
root=false
replace=false
start_now=true
```

**Comment by 89luca89** [comment]
Hi @wayneyaoo 

Ensure you have `crun` installed and `podman info` shows that you're using crun as `ociRuntime`
This allows to share group access between host and guest

Then ensure you, on the host, are in the right groups, and you'll have the proper access to the device

Else, just use a rootful container

This will solve your problems

**Comment by wayneyaoo** [comment]
Hey @89luca89 I really appreciate it! My host user missing access to the device is the key... Not sure why I was not in `render`. After adding myself to the group it works. `crun` was already installed and picked up by `podman`.

For others that might hit this issue with AMD GPU, the above template file works fine (but it doesn't install `clblast`). Just make sure your host user has rw access to the `/dev/kfd`. [Also after ollama 0.1.21, AMD GPU will be recognized automatically](https://github.com/ollama/ollama/pull/814#issuecomment-1901554508) even if the installation script didn't say so (it'll mention "NVIDIA GPU is not found, ollama will work in CPU mode" but when it serves, it'll figure out the AMD GPU, given `rocm` and `clblast` are installed).

**Comment by thednp** [comment]
@wayneyaoo can you please advise on how you got over this:

> make sure your host user has rw access to the `/dev/kfd`

Thank you so much.

**Comment by wayneyaoo** [comment]
> [@wayneyaoo](https://github.com/wayneyaoo) can you please advise on how you got over this:
> 
> > make sure your host user has rw access to the `/dev/kfd`
> 
> Thank you so much.

Hey not sure if you resolved this but to  achieve that, on your host machine, add yourself to the group owning the device file via e.g., `usermod -a -G <group> <username>`.
