### ISSUE TITLE
[Error] distrobox-export not working for symlink desktop files

### ISSUE THREAD

**Issue by FlorianLudwig** [89luca89/distrobox#124]
**To Reproduce**
1. have a symlink inside `/usr/share/applications/`
2. try to install the application with the symlinked desktop file

**Expected behavior**

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

```
/usr/bin/distrobox-export: 375: cannot create /run/host//home/f.ludwig/.local/share/applications/receiver.desktop: Directory nonexistent
```

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - distrobox: 1.2.11

**Comment by 89luca89** [comment]
Hi @FlorianLudwig 

can you attach the output of `distrobox-export` runned with `--verbose`?

**Comment by 89luca89** [comment]
Also the command you used to create the distrobox would be useful to try and reproduce the issue :+1:

**Comment by FlorianLudwig** [comment]
You can reproducable the issue with any distrobox image.

Here an example:

```
# echo "Name=Test" > /root/test.desktop
# ln -s /root/test.desktop /usr/share/applications/test.desktop
# distrobox-export --app test
mkdir: cannot create directory ‘/run/host//root’: Permission denied

An error occurred
```

The error message is different as i put the `.desktop` file inside `/root` but the root cause is the same: The symlink is copied and interpreted as `/root` inside the host system ( `/run/host//root` instead of `/root`)

The solution would be to follow the symlink and not replicated it.

**Comment by 89luca89** [comment]
Ok thanks I can reproduce this

So there are 2 issues here:

- distrobox-export is not meant to be used as `root`
- if not used as root, it will fail as it cannot resolve the symlink, as this is in /root and it's 0700

I'll add a check to prevent `distrobox-enter` to run as root.
