### ISSUE TITLE
Unable to connect to distrobox from VS Code Flatpak on Silverblue - Port Forwarding Errors

### ISSUE THREAD

**Issue by davepwsmith** [89luca89/distrobox#1247]
**Describe the bug**
I am trying to follow the instructions [here](https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md#from-flatpak) to connect to a distrobox from my flatpak vscode. I am running into an error when I try to connect using the script installed. I can connect to the container directly if I set the docker command to 'podman-remote' in vscode, but I am not sure what I am going to miss/screw up if I do that? 

**To Reproduce**
1. Create a distrobox using the jupyter/datascience-notebook container
2. Follow the Flatpak integration instructions above
3. Attempt to attach to the running container

**Expected behavior**
To be able to connect to the running container

**Logs**
[vscode-devcontainer-logs.txt](https://github.com/89luca89/distrobox/files/14467468/vscode-devcontainer-logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 4.9.3
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Fedora Silverblue ([Universal Blue](https://github.com/ublue-os/framework/pkgs/container/silverblue-framework))
 - How did you install distrobox? Was installed with the image

**Additional context**

**Comment by 89luca89** [comment]
Just pushed a fix for how input command are handled
Also the guide is for Distrobox 1.7+

Can you upgrade and try again?
