### ISSUE TITLE
[Suggestion] Add support for User Linux Mode 

### ISSUE THREAD

**Issue by lars18th** [89luca89/distrobox#126]
**Is your feature request related to a problem? Please describe.**
Every distrobox uses the same kernel of the _host_ Linux. Then we don't have the option of using _kernel_ tools of the _guest_ distro. This have sense when you want to use compile tools for the specific distro that require kernel headers.

**Describe the solution you'd like**
The solution that I suggest is to provide support for running Distrobox with UML (User Mode Linux). This could be a crazy idea, but more or less it's simple: compile a custom kernel that mimics the distro to use and run the distro over-the-top of this kernel. This kernel will be running in userland, so you can generate whatever you want. See more at https://www.kernel.org/doc/html/latest/virt/uml/user_mode_linux_howto_v2.html#introduction .

**Describe alternatives you've considered**
We don't have any alternative except a virtual machine for a full running of the distro. However, when creating a UML kernel and run the distrobox on top of it, we can reproduce the distro at 100% if the UML kernel has the same options enabled as the target distro. For sure the performance could have some impact, but the recent UML support has improved a lot in the Linux kernel.

**Additional context**
The idea is to generate the UML kernel automatically from Distrobox. So then the user only needs to request if he wants to use the host kernel or a new guest kernel.

I hope you don't think that this it's only a crazy idea.
Regards.

**Comment by 89luca89** [comment]
Hi @lars18th 

thanks for taking time to expose your idea

Strictly speaking this is not something Distrobox can cover, if something you should convince Podman or Docker to implement something like this and expose it, as Distrobox wants to remain a simple wrapper around container managers, not replacing them.

So I'm sorry but I can't take this suggestion.

For your use case, you can install kernel, headers and tools just fine inside the container, for example on debian:

`apt-get install linux-{image,headers,tools}-5.10.0-9-amd64 linux-tools-5.10`

works as intended, and you have headers and tools at disposal.

**Comment by lars18th** [comment]
Hi @89luca89 ,

Thank you for your response. After reading your post, I agree that the work requires to be done by Podman or Docker developers. And I feel some of them want to support containers in the userland. So perhaps they need to introduce the UML support. Only if this will be introduced in the future, then will have sense to speak about some support in Distrobox. Then, we can close this issue now.

Regards.
