### ISSUE TITLE
[Error] Distrobox creation still fails on fish in 1.7.0

### ISSUE THREAD

**Issue by ruffson** [89luca89/distrobox#1260]
**Describe the bug**
Related to https://github.com/89luca89/distrobox/issues/1210.
When trying to create and enter a distrobox, it will throw an error if the container was **created** with fish. (Even if trying to _enter_ with bash, it will fail).

**To Reproduce**
In `fish` try to create a container:
```
distrobox create --name sage --init --image sagemath/sagemath:latest --additional-packages "systemd libpam-systemd"
```
and enter it which will throw the error:
```
distrobox enter sage
```

**Expected behavior**
Don't fail when using fish to create and enter a container.

**Logs**

```
...
Firing up init system...                         [ OK ]

Container Setup Complete!
⚠️   First time user password setup ⚠️
New password:
Retype new password:
passwd: password updated successfully
fish: Command substitutions not allowed
$(getent passwd raph | cut -f 7 -d :) -l
 ^
```
I don't know how necessary the verbose log is but lemme know if you need me to get that.

**Desktop (please complete the following information):**
 - Using docker: `25.0.3` on Fedora 39
 - Distrobox version `1.7.0`
- Installed distrobox via the installer from the website.

**Additional context**
Tried other docker images and had the same issue.

**Comment by m2Giles** [comment]
Try prepending the create command and enter command with `env SHELL=/bin/bash`

This should force the creation of the distrobox with bash as the user inside the containers shell instead of fish. On newer Distros with a more modern version of fish, this error does not occur.

**Comment by ruffson** [comment]
> Try prepending the create command and enter command with `env SHELL=/bin/bash`
> 
> This should force the creation of the distrobox with bash as the user inside the containers shell instead of fish. On newer Distros with a more modern version of fish, this error does not occur.

Okay thanks I will try that!

**Comment by 89luca89** [comment]
This worked well for me

![image](https://github.com/89luca89/distrobox/assets/598882/3fb4183d-6f2b-4513-972c-b17062c8a37d)

This could be a specific image problem not a distrobox problem
You can use that env trick to avoid distrobox installing the shell for you

**Comment by vigress8** [comment]
Experiencing the same issue with this recommended image: https://quay.io/toolbx-images/debian-toolbox:testing
The following patch seems to fix it
```patch
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -332,7 +332,7 @@
 		if [ "${headless}" -eq 0 ]; then
 			container_command_login="${container_command_login} --pty"
 		fi
-		container_command_login="${container_command_login} -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -l\""
+		container_command_login="${container_command_login} -c \"\\\$SHELL -l\""
 		if [ -n "${container_command}" ]; then
 			container_command="$(echo "${container_command}" | sed 's/\$/\\\$/g')"
 			container_command="${container_command_login} -c \"${container_command}\""
```
This is on an Arch Linux host with Fish 3.7.0

**Comment by acuteaura** [comment]
this crashes with `distrobox create --name archlinux --init --image archlinux:latest` on distrobox 1.7.1.0

**Comment by C-Loftus** [comment]
Find this doesn't work for me, even if I am not inside fish, so long as fish is my default shell. Not entirely clear why

```
host@computer ~> bash
host@computer:~$ distrobox create --name test --init --image debian:latest --additional-packages "systemd libpam-systemd pipewire-audio-client-libraries"
Creating 'test' using image debian:latest	[ OK ]
Distrobox 'test' successfully created.
To enter, run:

distrobox enter test

host@computer:~$ distrobox enter test
Starting container...                   	[ OK ]
Installing basic packages...            	[ OK ]
Setting up devpts mounts...             	[ OK ]
Setting up read-only mounts...          	[ OK ]
Setting up read-write mounts...         	[ OK ]
Setting up host's sockets integration...	[ OK ]
Integrating host's themes, icons, fonts...	[ OK ]
Setting up distrobox profile...         	[ OK ]
Setting up sudo...                      	[ OK ]
Setting up user groups...               	[ OK ]
Setting up kerberos integration...      	[ OK ]
Setting up user's group list...         	[ OK ]
Setting up existing user...             	[ OK ]
Setting up user home...                 	[ OK ]
Ensuring user's access...               	[ OK ]
Setting up init system...               	[ OK ]
Firing up init system...                	[ OK ]

Container Setup Complete!
fish: command substitutions not allowed here
$(getent passwd host | cut -f 7 -d :) -l
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
