### ISSUE TITLE
[Error] Can't remove a distrobox

### ISSUE THREAD

**Issue by eylenburg** [89luca89/distrobox#1262]
**Describe the bug**
I'm trying to remove a container, but it still appears in the list and doesn't seem to be deleted at all.

**To Reproduce**
Run `distrobox-rm`

**Expected behavior**
The container is deleted

**Logs**
```
user@localhost:~> distrobox list
ID           | NAME                 | STATUS             | IMAGE                         
c262738d96aa | debian               | Up 50 seconds      | docker.io/library/debian:testing
7f4912f78577 | tumbleweed           | Up About an hour   | registry.opensuse.org/opensuse/distrobox:latest
user@localhost:~> distrobox stop debian
debian

user@localhost:~> distrobox-rm debian
Removing exported binaries...
Error: cannot find any desktop files.
Error: trying to export a non-installed application.

user@localhost:~> distrobox list
ID           | NAME                 | STATUS             | IMAGE                         
c262738d96aa | debian               | Up 42 seconds      | docker.io/library/debian:testing
7f4912f78577 | tumbleweed           | Up About an hour   | registry.opensuse.org/opensuse/distrobox:latest
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.9.3
 - Which version of distrobox? 1.7.0
 - Which host distribution? openSUSE Tumbleweed
 - How did you install distrobox? from repo

**Additional context**
It works when running `podman stop debian && podman rm debian`

**Comment by mabequinho** [comment]
Got the same issue yesterday running Suse's Aeon.
