### ISSUE TITLE
Cant start distrobox

### ISSUE THREAD

**Issue by kangarooo** [89luca89/distrobox#1265]
distrobox create --name tmuxtest --init --image ubuntu:22.04
distrobox enter tmuxtest 
Starting container...                            [ OK ]
Installing basic packages...                     [ OK ]
Setting up devpts mounts...                      [ OK ]
Setting up read-only mounts...                   [ OK ]
Setting up read-write mounts...                  [ OK ]
Setting up host's sockets integration...         [ OK ]
Integrating host's themes, icons, fonts...       [ OK ]
Setting up distrobox profile...                  [ OK ]
Setting up sudo...                               [ OK ]
Setting up user groups...                        [ OK ]
Setting up kerberos integration...               [ OK ]
Setting up user's group list...                  [ OK ]
Setting up user home...                          [ OK ]
Ensuring user's access...                        [ OK ]
Setting up init system...                        [ OK ]
Firing up init system...                         Error: could not set up init system, no init found! Consider using an image that ships with an init system, or add it with "--additional-packages" during creation.!

**Comment by m2Giles** [comment]
--init flag is for starting an init such as systemd or openrc inside the distrobox. It fails if you do not have any appropriate init system installed which is the default for most OCI containers.

**Comment by 89luca89** [comment]
Read the docs, `--init` either needs a dedicated init image, or needs to install additional packages for them to work

There are pratical examples in the help and even in the man pages
