### ISSUE TITLE
[Error] RPM packaging breaks compatibility with guests without `/usr/bin/sh`

### ISSUE THREAD

**Issue by michel-slm** [89luca89/distrobox#127]
**Describe the bug**
After creating a Debian testing container, using the image URLs listed in https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#containers-distros, I can't start the container.

**To Reproduce**
```
distrobox create --image docker.io/library/debian:testing --name debian-packaging
distrobox enter debian-packaging --verbose
```
I also tried `docker.io/library/debian:testing-backports`, the error is similar. Likewise with Debian stable and unstable.

**Expected behavior**
It should start

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[distrobox-enter.txt](https://github.com/89luca89/distrobox/files/7892753/distrobox-enter.txt)

```
$ podman logs --latest
{"msg":"exec container process (missing dynamic library?) `/usr/bin/entrypoint`: No such file or directory","level":"error","time":"2022-01-18T22:19:48.000323778Z"}
exec container process (missing dynamic library?) `/usr/bin/entrypoint`: No such file or directory
```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 35
 - Distrobox version: distrobox-1.2.11-1.fc35.x86_64 from COPR

**Additional context**
It works fine for CentOS Stream 8 and Stream 9. To double check that it's not affecting Apt-based distros in general, I created an Ubuntu 22.04 container and that starts just fine.

**Comment by 89luca89** [comment]
Hi @michel-slm  thanks for the report

I cannot reproduce this, both on Fedora 35 host and on Ubuntu 20 host, using Debian stable, testing, testing-backports and unstable containers

But using the `copr` version seems to be the key, I can indeed reproduce the issue

I'll investigate the problem with @alcir 

In the meantime, you can install it using the `curl` method and it should work

**Comment by 89luca89** [comment]
@alcir

I suspect the problem is in the use of `/usr/bin/sh` for the shebang
If possible it should remain `/bin/sh` as it's the POSIX compliant path for the shell

**Comment by 89luca89** [comment]
I can confirm the problem is that shebang modified, @michel-slm if you use the `curl` install method it will work
Will wait for a fix by @alcir  :+1:

**Comment by michel-slm** [comment]
Thanks @89luca89 ! In Fedora, /bin is just a symlink to /usr/bin anyway so it should not matter. I suspect the problem is some of the mangling is to scripts that are meant to run on the Debian side, though, and Debian hasn't made this /usr transition?

AFK now but I'm assuming it's the bin/sh in distrobox-enter that's problematic

**Comment by michel-slm** [comment]
PS @alcir I'm more than happy to help get this into Fedora properly, let me know if you want to submit it and I'll review.

I have some workflows that are much simplified by this amazing tool

**Comment by alcir** [comment]
> PS @alcir I'm more than happy to help get this into Fedora properly, let me know if you want to submit it and I'll review.

@michel-slm thank you very much.
It is currently under review since some time. But the reviewer is facing a bug with `fedora-review` and the review process is blocked. 
[Review Request: distrobox](https://bugzilla.redhat.com/show_bug.cgi?id=2034246)
[_Blocker bug_ about `fedora-review`](https://bugzilla.redhat.com/show_bug.cgi?id=2038828)

**Comment by 89luca89** [comment]
> Thanks @89luca89 ! In Fedora, /bin is just a symlink to /usr/bin anyway so it should not matter. I suspect the problem is some of the mangling is to scripts that are meant to run on the Debian side, though, and Debian hasn't made this /usr transition?
> 
> AFK now but I'm assuming it's the bin/sh in distrobox-enter that's problematic

Yes exactly, it's enter and export that are problematic
on Debian and other minimal distirbutions /usr/bin/sh is not present and not a given thing
That's why Centos and Ubuntu works but Debian not :smile: 

@alcir let me know if I can help in any way with the RPM fix :+1:

**Comment by alcir** [comment]
Package in COPR updated

I used
`%global __brp_mangle_shebangs_exclude_from %{_bindir}/distrobox*`

**Comment by 89luca89** [comment]
@alcir 
That was fast! :smile: cool I've tested it and works as expected
Waiting @michel-slm feedback to close this

Thanks a lot @alcir !

**Comment by michel-slm** [comment]
> the review process is blocked

since it's been a while, I've taken over the review. I'll get to it the first time in the morning, meanwhile, let me try the fix

**Comment by michel-slm** [comment]
I can confirm it's fixed, thanks both for the quick troubleshooting and update! Let's follow up on the review tomorrow - @alcir , I think per @89luca89 we should only brp_exclude distrobox-enter and distrobox-export, and fix the rest, but either way, I'll close this now. Thanks!
