### ISSUE TITLE
(GNOME) Windows from containers don't get matched to the exported desktop file

### ISSUE THREAD

**Issue by fkrull** [89luca89/distrobox#128]
**Is your feature request related to a problem? Please describe.**
When exporting .desktop files from a container, gnome-shell (might apply to other desktops) doesn't match open windows to the desktop entry. Specifically:

* the windows have a generic name and icon on the dock, rather than name and icon from the desktop file
* if the application is pinned to the dock, the windows are on their own, not grouped with the pinned icon

Any applications from the container have the WM_CLIENT_MACHINE property (can be checked with xprops) set to the hostname of the container. When this property doesn't match the system's hostname, gnome-shell doesn't group the windows with the desktop file. It also appends " (on \<container hostname\>)" to the window titlebar. (IIRC all I've tried where X11 windows. I would guess similar rules apply for Wayland windows, but I haven't checked.)

This can be worked around by setting the container hostname to match the host's hostname. Then gnome-shell groups windows as I want it to.

**Describe the solution you'd like**
I'm... not sure. Just a `--hostname` flag for distrobox-create? A `--no-custom-hostname` toggle? In general this seems related to the gradient from more to less host integration, but I don't know how to communicate the path from the problem ("my windows don't group with the desktop entry") to the solution ("I have to set the container's hostname to match the host's hostname").

**Comment by 89luca89** [comment]
Hi @fkrull 

Very interesting, I was testing the same, another way is to launc (from the inside of container)

`sudo unshare -u -- sh -c "hostname $(cat /etc/hostname | cut -d'.' -f2-) && sudo -u your-user-name your-app"`

This will effectively change the hostname just for that app launch

But for me it still does not behave like expected in gnome even if I set the container to the same hostname, namely windows don't group with the desktop entry

**Comment by fkrull** [comment]
You're right, my initial analysis was too simplistic.

* The container hostname matters, but only for X windows (i.e. all windows on X11 and Xwayland windows on Wayland)
* If the desktop file has a "StartupWMClass=" field, that field is matched to the WM_CLASS (X11) or "app id" (Wayland?) of the window
* If the desktop file doesn't have a "StartupWMClass=" field, the file name of the desktop file is matched to the WM_CLASS/app id

I've tested this with Rhythmbox (Wayland) and Chromium (X11) from an Alpine 3.15 container. Their desktop files don't have StartupWMClass so they're not matched after exporting them with distrobox-export. Renaming the desktop file or adding StartupWMClass gets it to match.

**Comment by 89luca89** [comment]
> You're right, my initial analysis was too simplistic.
> 
> * The container hostname matters, but only for X windows (i.e. all windows on X11 and Xwayland windows on Wayland)
> * If the desktop file has a "StartupWMClass=" field, that field is matched to the WM_CLASS (X11) or "app id" (Wayland?) of the window
> * If the desktop file doesn't have a "StartupWMClass=" field, the file name of the desktop file is matched to the WM_CLASS/app id
> 
> I've tested this with Rhythmbox (Wayland) and Chromium (X11) from an Alpine 3.15 container. Their desktop files don't have StartupWMClass so they're not matched after exporting them with distrobox-export. Renaming the desktop file or adding StartupWMClass gets it to match.

Cool I'll test again
Could be useful then in the export to add a StartupWMClass if not already present 

I'll report here the tests, and see if the unshare trick can be integrated with the export

**Comment by 89luca89** [comment]
Tested and we need both

- StartupWMClass
- same hostname as the host

So adding that to the

`sudo unshare -u -- sh -c "hostname $(cat /etc/hostname | cut -d'.' -f2-) && sudo -u your-user-name your-app"`

Need to work more on the export to enable this but we're on the right path to solve :+1:

**Comment by 89luca89** [comment]
As with issue #172 this could be solved with an init-hook 
closing this if there are more question feel free to reopen or open a new one

**Comment by 1player** [comment]
This is still a problem. I understand that this "could" be solved with a init hook, but how is it solved, in practice?

Do I need to recreate my toolbox, forcing the hostname as described in #172 ? Why can't this be done by default, is there a reason why distrobox injects a different hostname than the host machine?

Given that exporting apps is a core functionality, IMHO this issue needs to be ironed out and/or documented.

**Comment by 89luca89** [comment]
> Why can't this be done by default, is there a reason why distrobox injects a different hostname than the host machine?

Because we need a way to distinguish the host from the guest in the terminal, something that pops up and is supported by all default prompts, hence the hostname

But if we find out a better way I'm all for it :+1:

> This is still a problem, should be reopened. I understand that it "could" be solved with a init hook, but how, in practice?
> Given that exporting apps is a core functionality, IMHO this issue needs to be ironed out and/or documented.

As documented [HERE](https://distrobox.privatedns.org/useful_tips.html#enable-ssh-x-forwarding-when-ssh-ing-in-a-distrobox)

> Do I need to recreate my toolbox, forcing the hostname as described in https://github.com/89luca89/distrobox/issues/172 ?

Yes

---

Anyway if you want we can open a new discussion to find a different way to distinguish (without addons for shells and such) host and guest you're welcome :+1:

**Comment by 1player** [comment]
> As documented [HERE](https://distrobox.privatedns.org/useful_tips.html#enable-ssh-x-forwarding-when-ssh-ing-in-a-distrobox)

Well, that talks about SSH forwarding, not windows not being matched to the appropriate .desktop file. I understand that the solution is similar, but the documentation could use some clarification in my opinion.

Another thing that is not immediately clear, so it might help anyone reading this issue, is that this issue affects X11 applications only. If your application is Wayland native, this is not a problem. I have encountered this running Emacs in a distrobox, my workaround was to compile the git version of Emacs which uses Wayland, so I didn't have to do the hostname hack.

**Comment by 89luca89** [comment]
> Another thing that is not immediately clear, so it might help anyone reading this issue, is that this issue affects X11 applications only. If your application is Wayland native, this is not a problem. I have encountered this running Emacs in a distrobox, my workaround was to compile the git version of Emacs which uses Wayland, so I didn't have to do the hostname hack.

Very interesting, that could explain why I did not have many of those problems

Anyway feel free to open a new discussion for the previous hostname discussion (and alternative ways to show difference between host and guest) and to improve documentation
thanks

**Comment by Cm4nXD** [comment]
I was unable to get the --init-hooks on any distrobox container. Can someone explain what I'm doing wrong here?

```
distrobox-create --image quay.io/toolbx-images/archlinux-toolbox --name arch --init-hooks '"$(uname -n)" > /etc/hostname'
```

**Comment by Cm4nXD** [comment]
https://gist.github.com/rbreaves/293d72e162e9d5e8c5e40d5263dc6d28
> Ok I figured it out, my issue is that the latest version of arch doesn't ship with inetutils, which prevents the solution proposed by distrobox dev from working. I'm not sure if this is the best way to do it, but using this as the command to create the container fixed my issues.
> 
> `distrobox-create --name arch --image docker.io/library/archlinux:latest --init-hooks 'sudo pacman -S inetutils --noconfirm && hostname ryzen-tower'`
> 
> of course replace `ryzen-tower` with whatever your computer's hostname is ( the output of `uname -n` from host system)
> 
> I tried replaceing hostname with a variable but distrobox just spat errors at me. (somthing like this:)
> 
> `distrobox-create --name arch --image docker.io/library/archlinux:latest --init-hooks 'sudo pacman -S inetutils --noconfirm && hostname $(uname -n)'`

**Comment by iihmsunn** [comment]
@Cm4nXD variable worked when i moved it outside of the hook. 

```
inithook="sudo dnf install hostname -y && hostname $(uname -n)"
distrobox-create --name toolbox --image fedora:38 --init-hooks "${inithook}"

```
but now that i think of the actual issue is probably that variables are only resolved in double quotes and you have single quotes
