### ISSUE TITLE
[Error] /usr/bin/distrobox-enter: line 614: venv/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by xensurve** [89luca89/distrobox#1281]
Everything was fine until the latest update 

I can exectute the file if inside the distrobox but from outside it cant see the PATH, so if I do

` 
cd ~/foo/bar && source venv/bin/activate && python hello.py'  `  inside the container it works

But if I do

`
distrobox-enter -T -n xensurve -- 'cd ~/foo/bar && source venv/bin/activate && python hello.py'
`

It fails to see the path

I tried double quotes and removing the quotes , I tried different ways to escape the the quotes , but it still cant see the path 

Ive been using the below to open terminal and run the command up until now and it was working fine

`
konsole -e bash -c "(distrobox-enter -T -n xensurve -- 'cd ~/foo/bar && source venv/bin/activate && python hello.py') ; bash "
`

**Comment by 89luca89** [comment]
try doing `distrobox enter foo -- sh -c "cd ~/foo && source stuff && command"` this should work
