### ISSUE TITLE
[Suggestion] Allow running distrobox from a git checkout

### ISSUE THREAD

**Issue by nathanchance** [89luca89/distrobox#129]
Thanks a lot for this project, it is nice to have an "easy to use anywhere" alternative to `toolbox` :)

It would be nice if `distrobox` could be run directly from the git repository (as it makes updating and `PATH` management simpler) but that is not possible because `distrobox-create` assumes that `distrobox-init` and `distrobox-export` are in `PATH`.

```
$ git clone https://github.com/89luca89/distrobox
...

$ distrobox/distrobox create
realpath: '': No such file or directory
realpath: '': No such file or directory
Error: no distrobox-init found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

An error occurred
```

I can work around this by adding `PATH=$PWD/distrobox:PATH distrobox/distrobox ...` but a more user friendly approach might be something like:

```diff
diff --git a/distrobox-create b/distrobox-create
index dd331fd..4d9f137 100755
--- a/distrobox-create
+++ b/distrobox-create
@@ -38,8 +38,8 @@ container_user_gid="$(id -rg)"
 container_user_home="${HOME:-"/"}"
 container_user_name="${USER}"
 container_user_uid="$(id -ru)"
-distrobox_entrypoint_path="$(realpath "$(command -v distrobox-init)")"
-distrobox_export_path="$(realpath "$(command -v distrobox-export)")"
+distrobox_entrypoint_path="$(realpath "$(dirname "${0}")"/distrobox-init)"
+distrobox_export_path="$(realpath "$(dirname "${0}")"/distrobox-export)"
 non_interactive="${DBX_NON_INTERACTIVE:-0}"
 verbose=0
 version="1.2.12"
```

It seems unlikely to me that `distrobox-init` and `distrobox-export` would not be in the same folder as `distrobox-create` but maybe you are aware of something that I am not, hence the suggestion rather than a pull request.

**Comment by 89luca89** [comment]
Hi @nathanchance 
Yep I agree it would be easier to not require the PATH 

I was thinking we could do something like

```shell
distrobox_entrypoint_path="$(realpath "$(dirname "${0}")"/distrobox-init)"
distrobox_export_path="$(realpath "$(dirname "${0}")"/distrobox-export)"
[ ! -e "${distrobox_entrypoint_path}" ] && distrobox_entrypoint_path="$(realpath "$(command -v distrobox-init)")"
[ ! -e "${distrobox_export_path}" ] && distrobox_export_path="$(realpath "$(command -v distrobox-export)")"
```

This way we cover the situation where distrobox-init or export are not in the same directory of create, but are in PATH

If you want to open a PR, it's welcomed :smile:

**Comment by nathanchance** [comment]
Sure thing, thanks for the suggestion! I will open a PR shortly.
