### ISSUE TITLE
[Error] fish history cannot be saved with custom home

### ISSUE THREAD

**Issue by nathanchance** [89luca89/distrobox#130]
**Describe the bug**

When using `--home` with a completely fresh folder, I see an permission denied error for `.local/share/fish`, which causes the history not to be saved.

**To Reproduce**

```
# Make sure distrobox-home does not exist already
$ mkdir -p distrobox-home

$ distrobox create --home $PWD/distrobox-home

$ distrobox enter -- fish -l
error: Your history will not be saved.
warning-path: Unable to locate data directory derived from $HOME: '/home/nathan/tmp/distrobox-home/.local/share/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
nathan@fedora-toolbox-35 /h/n/tmp>
```

**Expected behavior**

I should not see the error or any of the warnings.

**Desktop:**

 - OS: Ubuntu 
 - Version: 20.04

**Additional context**

This comes from `distrobox-init`:

```sh
# bind mount distrobox directory for themes and icons
mkdir -p "${container_user_home}/.local/share/themes"
mkdir -p "${container_user_home}/.local/share/icons"
mkdir -p "${container_user_home}/.local/share/fonts"
# Fix permissions for home directories
chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/.local/share/themes"
chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/.local/share/icons"
chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/.local/share/fonts"
```

In my case, `${container_user_home}/.local/share` did not exist, so it was created with the container's `root` user, but only the `themes`, `icons`, and `fonts` permissions are fixed. Perhaps the entire `.local` folder should have the permissions fixed? Not sure what the implications of that change are thus just the bug report rather than a pull request.

For now, I can work around this by creating `.local/share` before creating the container.

**Comment by 89luca89** [comment]
Hey @nathanchance nice catch! Thanks!

Indeed we need to add a

`chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/.local/`
`chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/.local/share`

before that, I'll craft a fix when back home, or if you have time to open a PR it's more than welcomed :smile:

**Comment by nathanchance** [comment]
> EDIT: note that I'm not using `-R` because it might interfere with other things (for example if not using a custom home, it will mess up podman's containers permissions)

Ha, answered my question before I could even ask it :)

I can submit a PR for this, once I verify that the issue is actually resolved with the suggestion!
