### ISSUE TITLE
[Error] private: Permission denied: OCI permission denied

### ISSUE THREAD

**Issue by InvisibleRasta** [89luca89/distrobox#1300]
On a freshly installed ArchLinux system I installed podman and distrobox. When running` distrobox create --image ubuntu:22.04` everything goes well but as soon as i type `distrobox enter ubuntu-22-04`  as suggested by the distrobox plugin I get the following error:
`Error: unable to start container "935ae52246d0472d541b3e4d03304d82fac8c42ff109d6666f5746fc171ca06d": crun: make `/home/user/.local/share/containers/storage/overlay/abe71661b72757d207e2a1c6b40737133011daadb00319ee94e79c1036cb25b9/merged` private: Permission denied: OCI permission denied`

**Comment by 89luca89** [comment]
This is a podman problem not a distrobox problem
