### ISSUE TITLE
Unable to add user to group that only exists in the container.

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#1302]
Reopening #997 because for some reason the maintainer decided it cannot be reopened and needs a duplicate issue. So here it is.

## Steps to reproduce
* Create an alpine container
* `gpasswd -a user somegroup`
* Exit, restart the container
* Expect to see user in the group.

## Actual behaviour

User is not added to the group even after restarting the container.

The suggested workaround in #997 of relogging in the user does not seem to work either because sudoers does not allow it.

```
alpine:~ % cat /etc/group | grep sph
wheel:x:10:root,sph
abuild:x:300:sph
sph:x:1000:
alpine:~ % id
uid=1000(sph) gid=1000(sph) groups=1000(sph),65534(nobody)
alpine:~ % sudo -u sph -i
Sorry, user sph is not allowed to execute '/bin/zsh' as sph on alpine.tranquility.
```

It seems the issue here is that the sudoers file created by distrobox-init only allows sudo-ing to root:

```
alpine:~# cat /etc/sudoers.d/sudoers 
Defaults !fqdn
%wheel ALL=(ALL:ALL) ALL
%sudo ALL=(ALL:ALL) ALL
%root ALL=(ALL:ALL) ALL
"sph" ALL = (root) NOPASSWD:ALL
```

In any case, https://github.com/89luca89/distrobox/issues/590 suggests this should be possible out of the box without needing to sudo, but it does not seem to be the case.

Pinging @HugLifeTiZ because they have the exact same issue, as reported in a comment on #997.

**Comment by HugLifeTiZ** [comment]
It wasn't the maintainer who said the bug couldn't be re-opened, it was the original submitter of the issue. I don't think this hurts anything; but it's Luca's call on whether we proceed here or go back to the other one.

**Comment by 89luca89** [comment]
Hi @1player right now with 1.7+ there is the `--unshare-groups` flag that will disjoin the groups of the user (inside) from outside

So you can indeed add your user to a group that is only in the container this way
NB: unshare-groups is default when selecting `--init`

Let me know if this addresses your issue :+1:

**Comment by 1player** [comment]
Thank you Luca, using the `--unshare-groups` flag fixes it. Closing.

**Comment by 89luca89** [comment]
> Thank you Luca, using the `--unshare-groups` flag fixes it. Closing.

Great!
