### ISSUE TITLE
[Error] using apt install, distrobox crash

### ISSUE THREAD

**Issue by Xdavius** [89luca89/distrobox#1312]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
distrobox-create -i debian -n debian 
distrobox-enter debian
sudo apt install *something*

contener stop and return to my shell

```
Dépaquetage de libitm1:amd64 (12.2.0-14) ...
Sélection du paquet libatomic1:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../28-libatomic1_12.2.0-14_amd64.deb ...
Dépaquetage de libatomic1:amd64 (12.2.0-14) ...
Sélection du paquet libasan8:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../29-libasan8_12.2.0-14_amd64.deb ...
Dépaquetage de libasan8:amd64 (12.2.0-14) ...
[davius@davius-gladius ~]$

davius@deb:/home/davius$ sudo apt upgrade
E: dpkg a été interrompu. Il est nécessaire d'utiliser « sudo dpkg --configure -a » pour corriger le problème.
davius@deb:/home/davius$ sudo dpkg --configure -a
Paramétrage de binutils-common:amd64 (2.40-2) ...
Paramétrage de linux-libc-dev:amd64 (6.1.76-1) ...
Paramétrage de libctf-nobfd0:amd64 (2.40-2) ...
Paramétrage de libgomp1:amd64 (12.2.0-14) ...
Paramétrage de perl-modules-5.36 (5.36.0-7+deb12u1) ...
Paramétrage de libtirpc-dev:amd64 (1.3.3+ds-1) ...
Paramétrage de rpcsvc-proto (1.4.3-1) ...
Paramétrage de libmpfr6:amd64 (4.2.0-1) ...
Paramétrage de libmpc3:amd64 (1.3.1-1) ...
Paramétrage de libatomic1:amd64 (12.2.0-14) ...
Paramétrage de libgdbm-compat4:amd64 (1.23-3) ...
Paramétrage de libnsl-dev:amd64 (1.3.0-2) ...
Paramétrage de libcrypt-dev:amd64 (1:4.4.33-2) ...
Paramétrage de netbase (6.4) ...
Paramétrage de libbinutils:amd64 (2.40-2) ...
Paramétrage de libisl23:amd64 (0.25-1.1) ...
Paramétrage de libc-dev-bin (2.36-9+deb12u4) ...
Paramétrage de libcc1-0:amd64 (12.2.0-14) ...
Paramétrage de libperl5.36:amd64 (5.36.0-7+deb12u1) ...
Paramétrage de liblocale-gettext-perl (1.07-5) ...
Paramétrage de libitm1:amd64 (12.2.0-14) ...
Paramétrage de libctf0:amd64 (2.40-2) ...
Paramétrage de cpp-12 (12.2.0-14) ...
Paramétrage de perl (5.36.0-7+deb12u1) ...
Paramétrage de libgprofng0:amd64 (2.40-2) ...
Paramétrage de cpp (4:12.2.0-3) ...
Paramétrage de libc6-dev:amd64 (2.36-9+deb12u4) ...
Paramétrage de binutils-x86-64-linux-gnu (2.40-2) ...
Paramétrage de binutils (2.40-2) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.36-9+deb12u4) ...
Traitement des actions différées (« triggers ») pour man-db (2.11.2-2) ...
davius@deb:/home/davius$ 
```

**Expected behavior**
Musn't crash

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 5.0.0
 - Which version of distrobox? -git
 - Which host distribution? Arch
 - How did you install distrobox? yay

**Additional context**
See a bug patched two weeks ago, but here, no more changes

**Comment by Xdavius** [comment]
Some news : seems to be a podman 5.0 bug. Still testing the -git version

**Comment by 89luca89** [comment]
Hi @Xdavius I can't reproduce this issue, I just created a debian container and installed something big (`libgtk3*` just to pull lots of things) and it worked no problem

Be sure you're using v1.7.1+ as that includes the fix

**Comment by 89luca89** [comment]
> Some news : seems to be a podman 5.0 bug. Still testing the -git version

I'm still on 4.9.3 will try to reproduce on 5.0 when it comes around

**Comment by 89luca89** [comment]
@Xdavius just tried with 5.0.0 (Fedora-rawhide) and still cannot reproduce

![image](https://github.com/89luca89/distrobox/assets/598882/2f861e85-9185-45dd-ae9b-8a9ab2b35e55)

**Comment by Xdavius** [comment]
Hi @89luca89 

[davius@davius-gladius ~]$ distrobox --version
distrobox: 1.7.1.0
[davius@davius-gladius ~]$ podman version
Client:       Podman Engine
Version:      5.1.0-dev
API Version:  5.1.0-dev
Go Version:   go1.22.1
Git Commit:   8ec821452581120b73625daff68b5eb4829f44f6-dirty
Built:        Thu Mar 28 15:21:38 2024
OS/Arch:      linux/amd64

Same here.

You are on fedora, I'm on arch. Maybe the podman's archlinux package has a problem. It's quite a long time I had the bug.
5.1-dev seems to not be affected in my tests for now.

I think we can close here. 

Thank you for replying.

**Comment by 89luca89** [comment]
Thanks for reporting back! :+1:
