### ISSUE TITLE
Distrobox crashing on updating containers sporadically[Error]

### ISSUE THREAD

**Issue by brandflake11** [89luca89/distrobox#1314]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Sometimes when updating or install a package in my arch container (I'm using [this](https://github.com/brandflake11/arch-audio-container) as my container) in distrobox, distrobox seems to close abruptly during the update, not completing the installation in the container. This happens even with a clean arch container as well. Sometimes it crashes the container and sometimes it doesn't.

**To Reproduce**
Start an arch container and install a package or update the container.

**Expected behavior**
The container should not sporadically crash.

**Logs**

[podmanlogs.log](https://github.com/89luca89/distrobox/files/14797290/podmanlogs.log)
[distroboxcrash.log](https://github.com/89luca89/distrobox/files/14797291/distroboxcrash.log)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - Podman
 - Which version or podman, docker or lilipod?
 - podman-4.9.3-1.fc39.x86_64
 - Which version of distrobox?
 - distrobox-1.7.0.1-1.fc39.noarch
 - Which host distribution?
 - Universalblue Sericea
 - How did you install distrobox?
 - Distrobox is part of the Universalblue Sericea image

**Additional context**
This has happened in another container as well, but is less common for some reason.

**Comment by 89luca89** [comment]
This is a problem fixed on 1.7.1

**Comment by brandflake11** [comment]
Awesome, thanks so much!
