### ISSUE TITLE
Security issues, multiple users without a password inside the container and old kernel

### ISSUE THREAD

**Issue by NotMainstream** [89luca89/distrobox#1315]
Hello, I`m using distrobox with podman and BoxBoddy as a UI. I have a few security concerns, namely the containers have multiple users without a password and the kernel is old.  My host operating system has just the users created by me but the distrobox container has root; bin; daemon; adm; lp; sync; shutdown; halt; mail; operator; ftp; nobody; tss; dbus; avahi; tcpdump; systemd-network; systemd-oom; systemd-resolve; polkitd; rtkit; pipewire;  geoclue; systemd-coredump; systemd-timesync ALL WITHOUT PASSWORDS. I see this as a huge security issue, but I`m no expert so maybe someone can let me know if this is considered safe or if you plan on doing something to fix this issue or maybe it`s already fixable and you can let us know what can it be done. I intended to use the container for a web browser but it doesn`t look safe at all to do that. Thanks a lot.

**Comment by 89luca89** [comment]
Hi @NotMainstream 

Using rootless podman means that users inside the container have AT MOST the same privilege as your user

Also those users are set by distros not by distrobox, and are service user, not real users with shell access
You have the same ones on you host distro. That's just how Unix style service works.

Also a kernel inside the container doesn't make sense, a container always uses Host's kernel 
Containers are not virtual machines
