### ISSUE TITLE
[Error] Performance regression when entering big custom homes

### ISSUE THREAD

**Issue by stendler** [89luca89/distrobox#1317]
**Describe the bug**
Since `1.7.0`  (f7e8532b178055257dbbab23f440d27064a14a98) the startup time of my distroboxes (or first enter after stop) with custom homes has increased dramatically.

**To Reproduce**
Enter a distrobox with a custom home folder with about 3 million files worth of around 700GB.

**Expected behavior**
- fast startup
- no ownership changes to any existing nested file or folder

**Logs**
It stays in `Setting up skel...` for a long time in `chown -R 1000:1000 <custom-home>`

<details><summary>container log excerpt (click to expand)</summary>

```
+ printf 'distrobox: Setting up user home...\n'  
distrobox: Setting up user home...  
++ getent passwd username  
++ cut -d: -f6  
+ '[' <custom-home> '!=' <custom-home> ']'  
+ printf 'distrobox: Ensuring user'\''s access...\n'  
distrobox: Ensuring user's access...  
+ '[' '!' -e /etc/passwd.done ']'  
+ '[' 0 -eq 1 ']'  
+ touch /etc/passwd.done  
+ '[' -n /home/username ']'  
+ '[' -d /etc/skel ']'  
+ printf 'distrobox: Setting up skel...\n'  
distrobox: Setting up skel...  
++ find /etc/skel/ -type f  
+ skel_files='/etc/skel/.bash_logout  
/etc/skel/.bash_profile  
/etc/skel/.bashrc'  
+ for skel_file in ${skel_files}  
++ basename /etc/skel/.bash_logout  
+ base_file_name=.bash_logout  
++ dirname /etc/skel/.bash_logout  
+ skel_file_path=/etc/skel  
+ file_path_for_home=  
+ '[' -n '' ']'  
+ '[' '!' -f <custom-home>/.bash_logout ']'  
+ for skel_file in ${skel_files}  
++ basename /etc/skel/.bash_profile  
+ base_file_name=.bash_profile  
++ dirname /etc/skel/.bash_profile  
+ skel_file_path=/etc/skel  
+ file_path_for_home=  
+ '[' -n '' ']'  
+ '[' '!' -f <custom-home>/.bash_profile ']'  
+ for skel_file in ${skel_files}  
++ basename /etc/skel/.bashrc  
+ base_file_name=.bashrc  
++ dirname /etc/skel/.bashrc  
+ skel_file_path=/etc/skel  
+ file_path_for_home=  
+ '[' -n '' ']'  
+ '[' '!' -f <custom-home>/.bashrc ']'  
+ chown -R 1000:1000 <custom-home>
``` 

</details>

**Desktop:**
 - podman 4.9.3
 - distrobox 1.7.0.1
 - Host: opensuse microos
 - Installed via zypper / transactional-update / was bundled

**Additional context**
- This only happens on container startup. So when entering in one window, entering again or opening an application while the container is running will be faster, even if the first enter is still stuck at that step.
- The custom home folder may contain other container volume mounts, which break if their ownership changes.
- I'm not sure why skel files are copied in the first place, if the custom home directory is not empty. Could this be skipped or made optional?

**Comment by Wiedzmin89** [comment]
I have same issue with NFS home folder
