### ISSUE TITLE
tzdata failing to install on mint (version 2.1 from the docs)

### ISSUE THREAD

**Issue by Gildedter** [89luca89/distrobox#1325]
mint distro created using the following command: `SHELL=/bin/zsh distrobox create --name mint --image docker.io/linuxmintd/mint21.1-amd64 --home ~/.containers-home/mint/`

I have distrobox installed on the steam deck running Steam OS 3.5 (the one that comes pre-installed). I'm using a custom home directory because my zsh config (and other configs too) kept polluting the default `/home/deck/` directory, so having several containers installed ends up reading the same config files.

my terminal:
![image](https://github.com/89luca89/distrobox/assets/93777256/d371db9b-024c-40c3-bfcb-ea0c0b3d0d5b)

Edit: I have already tried [this](https://serverfault.com/a/1016972) but nothing happened.

_Originally posted by @Gildedter in https://github.com/89luca89/distrobox/issues/820#issuecomment-2009463893_

**Comment by 89luca89** [comment]
This issue is fixed in newest version of distrobox, the one shipped with SteamOS is quite old, please use a newer version

**Comment by Gildedter** [comment]
> This issue is fixed in newest version of distrobox, the one shipped with SteamOS is quite old, please use a newer version

is there an update guide where I can move my existing image over? or do I have to setup everything from scratch?
