### ISSUE TITLE
[Error] `distrobox enter` fails to enter after creating container Error: parsing

### ISSUE THREAD

**Issue by NateWright** [89luca89/distrobox#1336]
**Describe the bug**
Using `distrobox enter` after creating a container with `distrobox create` or `distrobox assemble create`, I receive the following error:
```bash
Starting container...                   	 Error: parsing --since "2024-04-10T09:26:40.%N%:z": unable to interpret time value
```

**To Reproduce**
```bash
distrobox create --name u22 --home /home/nwright/distrobox/home/u22 --image ubuntu:22.04
distrobox enter u22
```

**Expected behavior**
Expected behavior is to enter the distrobox normally.
**Logs**
[verbose](https://github.com/89luca89/distrobox/files/14932967/typescript.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 4.9.3
 - Which version of distrobox? distrobox version: 1.7.1.0
 - Which host distribution? NixOS Unstable
 - How did you install distrobox? Through nixpkgs

**Additional context**

**Comment by JamiKettunen** [comment]
So `date +%FT%T.%N%:z` outputs `2024-04-10T09:47:51.%N%:z` for you, have you messed with the core system utilities (shouldn't they always be GNU coreutils on NixOS?)

[I have a patch](https://github.com/JamiKettunen/cports/blob/distrobox/contrib/distrobox/patches/bsddate.patch) to make it (hopefully) universally compatible including with [FreeBSD date(1)](https://man.freebsd.org/cgi/man.cgi?date(1)) used on [Chimera Linux](https://chimera-linux.org) at the cost of losing nanosecond accuracy which I perhaps should submit, no idea if that is desirable but I can't really think of a case where the sub-second accuracy is important personally.

**Comment by NateWright** [comment]
> So `date +%FT%T.%N%:z` outputs something like `2024-04-10T09:47:51.%N%:z` for you, have you messed with the core system utilities (shouldn't they always be GNU coreutils on NixOS?)
> 
> [I have a patch](https://github.com/JamiKettunen/cports/blob/distrobox/contrib/distrobox/patches/bsddate.patch) to make it (hopefully) universally compatible including with [FreeBSD date(1)](https://man.freebsd.org/cgi/man.cgi?date(1)) used on [Chimera Linux](https://chimera-linux.org) at the cost of losing nanosecond accuracy which I perhaps should submit, no idea if that is desirable but I can't really think of a case where the sub-second accuracy is important personally.

I don't believe I have messed with core system utilities. I can try out the patch though.

**Comment by JamiKettunen** [comment]
What is your `date --version`? I couldn't reproduce your `date` output issue on Void Linux (GNU coreutils 9.4) which NixOS unstable should match according to https://search.nixos.org nor Arch Linux (GNU coreutils 9.5)

**Comment by NateWright** [comment]
> What is your `date --version`? I couldn't reproduce your `date` output issue on Void Linux (GNU coreutils 9.4) which NixOS unstable should match according to https://search.nixos.org nor Arch Linux (GNU coreutils 9.5)

Okay, I did that and it looks like it was using the busybox one. I uninstalled busybox and it works now.

**Comment by NateWright** [comment]
I guess I don't understand how that all works. Is there a way to prevent this if you have BusyBox installed?

**Comment by JamiKettunen** [comment]
I've submitted the previously mentioned patch as https://github.com/89luca89/distrobox/pull/1343
