### ISSUE TITLE
[Suggestion] `distrobox system-upgrade`

### ISSUE THREAD

**Issue by boredsquirrel** [89luca89/distrobox#1338]
Distrobox is using OCI containers very differently than they are meant to. Normally you would just use podman etc. commands to update a container, and also for rebasing to the next release.

This does not work with this model, as the base image is minimal and mostly used for doing manual overwrites to it. Everything included is also likely included in something like Fedora atomic desktops.

As context I would also like to separate the home directories by default, so I will integrate this requirement in the idea.

`distrobox system-upgrade NAME` should work like this:
1. Enter the box.
2. `cd ~`
3. `if $PWD == "/home/$USER" or "/var/home/$USER"
4. Create a backup dir `mkdir ~/DISTROBOX-$NAME-BACKUP`
5. Copy only .config and whatnot into that dir
6. `else` (user is using a different home)
7. copy the entire home to that backup dir, `break`
8. Now determine the OS, related to the #744 
9. Use one of a set of different commands to somehow get all the manually installed apps (there has to be a way right? Something else than `history | grep dnf install`
10. Save those apps to a variable
11. Use podman pull or whatever used container tool, get the version and name of the used OCI image
12. Fetch all images, somehow separate the numbers and calculate to only show higher values than the current release version
13. Display a dialog 

```
Upgrading $NAME, choose a version:

1
2
3
```
14. Use a read prompt (or something more elegant, like Ratatui) to let the user choose an option
15. Remove or directly upgrade the used OCI container, discarding all local differences (if needed by removal and reinstallation) (keep the name)
16. Enter it
17. Reinstall the packages using the package manager defined above
18. Copy or move the backup .config or entire home to this boxes home, also using a variable from above maybe
19. Display a nice finished notification!

What do you think? This is pretty complex, btw using [topgrade](https://github.com/r-darwish/topgrade) from within the box should require no dependencies and make things a loot easier. (Ublue uses that in their updater so support is pretty much guaranteed).

Cheers!

**Comment by 89luca89** [comment]
Hi @boredsquirrel 

yea that indeed is a use-case to cover, but I'm still not convinced by either me accumulating commands, nor using external dependencies :sweat_smile: 

Ideally an user would use `distrobox-assemble` and have manifests, that would just require to re-create the container to pull the `:latest` image and be done with it

**Comment by 89luca89** [comment]
I've decided that this is out of scope of the project
Use :latest, or use assemble to have reproducible containers, and replace them when needed
