### ISSUE TITLE
[Suggestion] Allow passing along flags to podman or docker

### ISSUE THREAD

**Issue by nathanchance** [89luca89/distrobox#135]
**Is your feature request related to a problem? Please describe.**

When building LLVM and running the test suite for `ld.lld` on a 64-thread machine, I run out of PIDs, which causes a bunch of weird errors. I have worked around this in the past with the `--pids-limit` flag to `podman`, setting it to `-1` to give an unlimited number of PIDs, rather than [the default of 2048](https://github.com/containers/common/blob/fd83ffc54954d6f09880303dbe78c6d7cb78d030/pkg/config/default.go#L108). I doubt that is a good default for most users, who probably won't be working with a large amount of parallelism, so it would make sense to allow me to pass custom `podman` flags to `distrobox-create`, which would forward them along to `podman`.

Other flags I would use this for are `--env` and `--volume` during `distrobox-enter` to customize the container's environment without having to mess around with dotfiles.

**Describe the solution you'd like**

I envision something like `--additional-args` or whatever is an appropriate flag name that I can use like:

```
$ distrobox-create --additional-flags "--pids-limit -1" --image ... --name ...

$ distrobox-enter --additional-flags "--env ... --volume ..." --name ... 
```

**Describe alternatives you've considered**

I am open to other suggestions to solving this problem :)

**Additional context**

I don't mind working up a PR for this, as long as I have some guidance on how you would prefer it to be implemented.

**Comment by 89luca89** [comment]
Yea I was thinking of something like this for some time :smile: 

Mainly the `env` part is already working like a normal command

`MY_CUSTOM_VAR=value distrobox enter . . .`

About additional volumes, also I was thinking of a separate flag, like

`distrobox create --volume a:b:ro --volume c:d:rw . . .`

That would just pass trough the flag to podman/docker

And then add (like you suggested) `--additional-flags` for everything else, just so that it's a bit easier for users to use vars and volumes and leave to more advanced use the `--additional-flags`

Anyway yes, I like the idea I'll work on this when I have some more time :+1:

**Comment by 89luca89** [comment]
@nathanchance I've opened a pull request with an initial work on this, It's working for me but better have other pair of eyes on this :smile:

**Comment by nathanchance** [comment]
#136 appears to work well for me!

It might be nice to have a shorthand flag (`-a`?) but other than that, I think that checks off all of the boxs for me :) thank you for the quick turn around!

```
$ distrobox create -i ghcr.io/nathanchance/dev/arch -n dev-arch

$ podman container inspect dev-arch | jq '.[0].HostConfig.PidsLimit'
2048

$ distrobox rm -f dev-arch
...

$ distrobox create -i ghcr.io/nathanchance/dev/arch -n dev-arch --volume $CBL_TC:/tc --additional-flags "--pids-limit -1"

$ podman container inspect dev-arch | jq '.[0].HostConfig,.PidsLimit'
0

$ distrobox enter -n dev-arch -- ls /tc/bin/clang
/tc/bin/clang

$ distrobox enter -n dev-arch --additional-flags "--env my_var=test" -- printenv &| grep my_var
my_var=test
```

**Comment by 89luca89** [comment]
Cool, yes I'd like to have the short flags too
will add them just have to find something that fits well :smile:
Sadly for volumes we cannot use -v not -V as they're already taken

**Comment by 89luca89** [comment]
I've added the short `-a` flag for the `--additional-flags`, for volume I'm just leaving it long for now,
this is now merged :smile: 

Thanks for the idea :+1:
