### ISSUE TITLE
/home/USER/.local/bin/distrobox-create: 1: eval: tmpdir: parameter not set

### ISSUE THREAD

**Issue by redbeardymcgee** [89luca89/distrobox#1370]
**Describe the bug**
Uhm...

**To Reproduce**
`test.ini`

```ini
[test]
init_hooks='sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"'
```

`distrobox assemble create --replace --file ./test.ini`

**Expected behavior**
Build the container, with `chezmoi` bootstrapped into `$HOME/.local/bin`

**Host system**
podman 3.4.4
distrobox 1.7.2
Pop!OS 22.04

`curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --next --prefix ~/.local`

**Additional context**
[test.log](https://github.com/89luca89/distrobox/files/15206539/test.log)

**Comment by redbeardymcgee** [comment]
` 128   │ + eval /home/josh/.local/bin/distrobox-create --yes -v --name test --init-hooks ":
       │ ;  sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin""`

If I'm reading this line correctly from the log, it looks like you dropped the surrounding single quotes `'` somewhere while trying to sanitize the input.

**Comment by 89luca89** [comment]
You need to also escape the dollarsign, as it will be evaluated by your current shell, not inside the container

so:

`init_hooks='sh -c \"\$(curl -fsLS get.chezmoi.io)\"'`

If you don't escape the `$(` this will be evaluated by your current shell BEFORE going to distrobox
this is valid for every script and shell command, not a distrobox exclusive

This works indeed

![image](https://github.com/89luca89/distrobox/assets/598882/e0fe8d7d-ccee-4925-9dc3-8aedcbefc347)
