### ISSUE TITLE
[Error] Can't install things in Ubuntu 22 container because directories are owned by nobody:nogroup

### ISSUE THREAD

**Issue by miranda** [89luca89/distrobox#1385]
After creating a Ubuntu 22 container with distrobox and podman, I built Audacity in it.  When I sudo make install, it fails because a lot of directories are strangely owned by nobody:nogroup.  I cannot chown them either.

```
distrobox create ubuntutest --image ubuntu:22.04
distrobox enter ubuntutest
ls -l /usr/local/share/

drwxr-xr-x 1 root   root      0 May  9 12:58 ca-certificates
drwxr-xr-x 1 nobody nogroup 328 Apr 26 22:59 fonts
drwxr-xr-x 1 nobody nogroup 540 Mar 29 11:29 icons
drwxr-xr-x 1 root   root      0 Apr 26 21:02 man
drwxr-xr-x 1 nobody nogroup  70 Nov  1  2023 themes
```
[distrobox_verbose.txt](https://github.com/89luca89/distrobox/files/15266060/distrobox_verbose.txt)

Host: Arch Linux, 6.8.9-zen1-2-zen, X11, KDE 6

Pacman packages used on host:
```
distrobox 1.7.2.1-1
podman 5.0.2-1
```

**Comment by 89luca89** [comment]
Hi @miranda 
those are there for host's icon/fonts/theme integration

you can disable this temporarly by running manually `sudo umount /usr/local/share/{fonts,icons,themes}` or permanently by adding that command to `init-hooks` during creation
