### ISSUE TITLE
[Error :: installing systemd (255.6-1) breaks dependency 'systemd=255.5' required by systemd-sysvcompat

### ISSUE THREAD

**Issue by xensurve** [89luca89/distrobox#1388]
SYSTEM : Arch
DE: Plasma
Distrobox : 1.7.2-1

After downloading image and doing distrobox enter xxx 

It fails and podman error message is

<pre><code>
podman logs -f xxxx
</pre></code>

installing systemd (255.6-1) breaks dependency 'systemd=255.5' required by systemd-sysvcompat

<pre><code>
# version of systemd on client machine
pacman -Ss systemd | grep installed

core/systemd 255.6-1 [installed]
core/systemd-libs 255.6-1 [installed]
core/systemd-sysvcompat 255.6-1 [installed]
</pre></code>

**Comment by xensurve** [comment]
To fix this error  add the refresh pacman switch

<pre><code>

		# If we need to upgrade, do it and exit, no further action required.
		if [ "${upgrade}" -ne 0 ]; then
			pacman -S -y -u --noconfirm
			exit
		fi
</pre></code>

**Comment by 89luca89** [comment]
Fixed in commit cd4f580aa687955e591cc76df96f58390a8c8be9
