### ISSUE TITLE
[Error]  dbus-broker-units: /usr/lib/systemd/system/dbus.service exists in filesystem (owned by dbus)

### ISSUE THREAD

**Issue by xensurve** [89luca89/distrobox#1389]
SYSTEM : Arch
DE : Plasma
DISTROBOX : 1.7.2-1
IMAGE : archlinux:latest

when you use the below , error occurs when you do distrobox enter test, becuase its missing the --overwrite flag with pacman

<pre><code>
distrobox create -i archlinux:latest --init --additional-packages "systemd" -n test
</pre></code>

<pre><code>
there is nothing to do
+ '[' '!' -e /usr/share/zoneinfo/UTC ']'
+ '[' -n ' systemd' ']'
+ pacman -S --needed --noconfirm systemd
resolving dependencies...
:: There are 2 providers available for dbus-units:
:: Repository core
1) dbus-broker-units  2) dbus-daemon-units

Enter a number (default=1):
looking for conflicting packages...

Package (4)             Old Version  New Version  Net Change

core/dbus-broker                     36-2           0.35 MiB
core/dbus-broker-units               36-2           0.00 MiB
core/systemd-libs       255.2-1      255.6-1       -0.06 MiB
core/systemd            255.2-1      255.6-1       -0.31 MiB

Total Installed Size:  34.01 MiB
Net Upgrade Size:      -0.02 MiB

:: Proceed with installation? [Y/n]
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
error: failed to commit transaction (conflicting files)
dbus-broker-units: /usr/lib/systemd/system/dbus.service exists in filesystem (owned by dbus)
dbus-broker-units: /usr/lib/systemd/user/dbus.service exists in filesystem (owned by dbus)
</pre></code>

**Comment by xensurve** [comment]
to fix this the overwrite switch needs to be added

<pre><code>
pacman -Syu --noconfirm --overwrite="*" 
</pre></code>

**Comment by 89luca89** [comment]
Fixed in commit cd4f580aa687955e591cc76df96f58390a8c8be9
