### ISSUE TITLE
[Error] Ephemeral Distrobox (v1.7.2.1) not running on Ubuntu 23.10/Docker 26.1.1

### ISSUE THREAD

**Issue by k1mbl3** [89luca89/distrobox#1392]
It seems that distrobox-ephemeral has stopped working (on Distrobox 1.7.2.1) with Docker 26.1.1, while it works fine with Podman 4.3.1 on Ubuntu 23.10, as it was functioning properly before the update (sorry, i don't remember the exact version i was using).

EDIT: Just tested in a VM with Ubuntu 24.04, and the issue persists.
EDIT2: I think I was using version 1.6.0.1 before the update, as i tested all releases backwards and it was the first one where distrobox-ephemeral came back to life.

When attempting to start an ephemeral Distrobox using Docker, it gets stuck at the 'Starting container...' line until I press Ctrl+C:

(alpine-test is an Alpine image pre-installed with the Distrobox dependencies for faster startups, the issue also happens with vanilla alpine, debian and ubuntu images).

```console
k1mbl3@laptop:/tmp/test-dbx$ DBX_CONTAINER_MANAGER=docker distrobox ephemeral --image alpine-test
Creating 'distrobox-WBcdiiOsLz' using image alpine-test	 [ OK ]
Distrobox 'distrobox-WBcdiiOsLz' successfully created.
To enter, run:

distrobox enter distrobox-WBcdiiOsLz

Successfully copied 2.05kB to /tmp/distrobox-WBcdiiOsLz.os-release
Starting container...                   	^C/usr/local/bin/distrobox-enter: 656: cannot open /home/k1mbl3/.cache/distrobox/.distrobox-WBcdiiOsLz.fifo: No such file
Removing exported binaries...
Removing container...
distrobox-WBcdiiOsLz
Error response from daemon: No such container: distrobox-WBcdiiOsLz
Cannot find container distrobox-WBcdiiOsLz.
```

While running with Podman, it runs normally:
```console
k1mbl3@laptop:/tmp/test-dbx$ DBX_CONTAINER_MANAGER=podman distrobox ephemeral --image alpine-test
Creating 'distrobox-aytkbhUppq' using image alpine-test	 [ OK ]
Distrobox 'distrobox-aytkbhUppq' successfully created.
To enter, run:

distrobox enter distrobox-aytkbhUppq

Starting container...                   	 [ OK ]
Executing pre-init hooks...             	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 [ OK ]
Setting up read-only mounts...          	 [ OK ]
Setting up read-write mounts...         	 [ OK ]
Setting up host's sockets integration...	 [ OK ]
Integrating host's themes, icons, fonts...	 [ OK ]
Setting up package manager exceptions...	 [ OK ]
Setting up distrobox profile...         	 [ OK ]
Setting up sudo...                      	 [ OK ]
Setting up user groups...               	 [ OK ]
Setting up kerberos integration...      	 [ OK ]
Setting up user's group list...         	 [ OK ]
Setting up existing user...             	 [ OK ]
Setting up user home...                 	 [ OK ]
Ensuring user's access...               	 [ OK ]
Executing init hooks...                 	 [ OK ]

Container Setup Complete!
k1mbl3@laptop:/tmp/test-dbx$ 
```

I also have the --verbose log, but I won't be able to post it on the GitHub issue since it exceeds the 65536 characters limit. Additionally, I'm unsure if it's allowed to share a Pastebin URL.

**Comment by traverseda** [comment]
This one bug seems like it's big enough for a release. I'm trying to release some SDK components using distrobox and have run into significant issues because of this.
