### ISSUE TITLE
[Discussion] use latest fedora by default instead of 39

### ISSUE THREAD

**Issue by gmankab** [89luca89/distrobox#1402]
```shell
distrobox enter fedora
Error: no such container fedora
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]:
```

it suggests me to create container with fedora 39, while my host os is fedora 40 atomic

can you please make it to suggest latest version, or version matching with host system

**Comment by slimhk45** [comment]
I look for the same thing, I search a way to create a Fedora container that I can upgrade to the next release if it is available.

**Comment by konstantinblaesi** [comment]
Workaround until a fix is released
`sudo sed -Ei 's/(fedora-toolbox[-:])39/\140/g' /usr/bin/distrobox-{create,enter}`

Changes from #1390 (not sure what happened to that PR)

**Comment by dashingdon** [comment]
these instructions work: https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/
