### ISSUE TITLE
[Error] Wrong hostname for Debian on Fedora host

### ISSUE THREAD

**Issue by slimhk45** [89luca89/distrobox#1406]
My host is Bluefin (a battery-included Fedora Silverblue distribution) and I use Distrobox 1.7.2.1.

I tried to create a Debian distrobox on my Bluefin host using this command:

```
distrobox create --image quay.io/toolbx-images/debian-toolbox:latest --name debian --home /var/home/user/Debian/ --nvidia

distrobox enter debian
```

and it returned the wrong hostname `user@fedora` instead of `user@debian`.

To solve this problem I need to enforce the hostname I want:

```
distrobox create --image quay.io/toolbx-images/debian-toolbox:latest --name debian --hostname debian --home /var/home/user/Debian/ --nvidia
```

Is it possible to enforce the hostname automatically for Debian distrobox on Fedora host? My problem is that I use BoxBuddy for managing my distroboxes and BoxBuddy is using the first command that doesn't enforce the hostname. Hence it is not possible to use BoxBuddy to create proper Debian distroboxes on Fedora host.

The BoxBuddy maintainer redirect me to you to do upstream change.

See here  https://github.com/Dvlv/BoxBuddyRS/issues/94

**Comment by 89luca89** [comment]
This is the new behaviour of distrobox as of version 1.7.2+

This is automatic as changing hostname will break startupwmclass on gnome/kde for exported apps
