### ISSUE TITLE
[Error] Ubuntu 24.04 image tries to install libgl1-mesa / libgl1-mesa-glx

### ISSUE THREAD

**Issue by nikspyratos** [89luca89/distrobox#1410]
First time using Distrobox, very useful so far!

- Podman v4.5.1
- Host: SteamOS latest
- Distrobox: 1.7.2.1
- Installed via site instructions for SteamOS

When trying to spin up with Ubuntu 24, the setup tries to install the mentioned packages, but they don't seem to be in the repos for the latest Ubuntu anymore.

I see there was #788 made to fix #763 in a similar vein, but it seems that's not quite enough in this case.

**Comment by xu-shawn** [comment]
Can confirm this issue

**Comment by 89luca89** [comment]
This has been fixed in PR 618bf902de5ea18c75c05ca0ac5dbb49579655fe
