### ISSUE TITLE
[Suggestion] Command to run a program in a container

### ISSUE THREAD

**Issue by Xanderplayz16** [89luca89/distrobox#1414]
**Is your feature request related to a problem? Please describe.**
I am creating a script that uses Distrobox, and I can't find a good way to do this.

**Describe the solution you'd like**
I would like something like a command that runs an program inside a container, like:
`distrobox-exec mycontainer "/bin/bash -c 'dosomething | somethingelse && morecompute >/dev/null'"`

**Comment by fbartels** [comment]
When using [distrobox export](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-export.md) it creates a wrapper script with the following command to directly executy a command in a distrobox:

```
$HOME/.local/bin/distrobox-enter  -n name-of-distrobox  --  '/usr/bin/code'  "$@"
```

**Comment by 89luca89** [comment]
Just read the `distrobox-enter` docs/man page/help and you'll see there is a flag for that
