### ISSUE TITLE
[Error] Virt-Manager in rootfull+init dbox "crashes" sound for other apps

### ISSUE THREAD

**Issue by nunix** [89luca89/distrobox#1417]
**Describe the bug**
When starting virt-manager from a rootfull+init dbox, the USB audio devices are no more accessible from other apps, such as Chrome or Brave browsers (installed as flatpak).

**To Reproduce**
- Create a new rootfull+init dbox: 
```shell
distrobox create --name virt --root --init
```
- Install virt-manager and dependencies:
```shell
sudo zypper in +pattern:kvm_server +pattern:kvm_tools qemu-spice virtiofsd qemu-hw-display-virtio-gpu
sudo usermod -aG kvm,libvirt $USER
# [Optional] export the desktop app
distrobox-export --app virt-manager
```
- Create a test VM with all the defaults (it doesn´t need to be started aftwerards)
- Exit dbox and stop it:
```shell
exit
distrobox stop --root virt
```
- Start a web app that requires sound (i.e. meet.google.com)
- Open virt-manager (from the desktop icon if exported, or from the CLI inside the dbox)

RESULTS: the running app (i.e. meet.google.com) has no more access to sound devices.

**Expected behavior**
The sound devices should remain available to the running apps.

**Logs**
N/A and specific logs can be provided on-demand.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 5.0.3
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? Aeon
 - How did you install distrobox? installed by default

**Additional context**
I have a workaround: my audio devices are all USB, and if I remove the USB redirection from the VMs configuration, I don't have this issue.

**Comment by 89luca89** [comment]
Fixed by commit a537dfffa6589640e586a1395eec498ed792ccd9
