### ISSUE TITLE
[Suggestion] Change the pull link in distrobox-create -С for Crystal Linux

### ISSUE THREAD

**Issue by nisel11** [89luca89/distrobox#1418]
**Is your feature request related to a problem? Please describe.**

About a month ago Crystal Linux changed the pull link to registry.gitlab.com/crystal-linux/misc/docker:latest , but in distrobox-create -C the wrong link is currently specified.

**Describe the solution you'd like**

I don't know how distrobox-create -C works.

**Describe alternatives you've considered**

Just don't fix it

**Additional context**

![Знімок екрана з 2024-05-27 22-44-02](https://github.com/89luca89/distrobox/assets/96194200/aa070fe3-d3a3-4c30-8efb-5434a22c2a26)

**Comment by 89luca89** [comment]
Thanks, fixed the link :+1:
