### ISSUE TITLE
[Error] vscode podman-host script leads to "Remote Extension host terminated unexpectedly 3 times within the last 5 minutes"

### ISSUE THREAD

**Issue by retif** [89luca89/distrobox#1421]
After following the guide
https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md
downloaded and added podman-host to vscode configuration i get an error

**Remote Extension host terminated unexpectedly 3 times within the last 5 minutes**

at dev containers terminal i can see a lot messages like 
`[164357 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[164697 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[164836 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[165159 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[165320 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[165689 ms] Start: Run in container: /bin/sh -c # Watch machine settings`

the issue is revealed only with ~/.local/bin/podman-host
if i connect with just "podman" it works, but under the root

here is additional logs:
journalctl https://gist.github.com/retif/87fdeb9b4402d0e8a25c25e8ca6670e5
podman log https://gist.github.com/retif/65c01ebf4a8b7a7b187672e816ec66c4
podman inspect https://gist.github.com/retif/8d24848025f2076d35cd18e03c21c6a8
dev containers terminal output https://gist.github.com/retif/acd9496e363a8da8fff69cb7ec2d754a

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 4.9.3
 - Which version of distrobox? distrobox: 1.7.0
 - Which host distribution? ubuntu 24.04
 - How did you install distrobox? apt install

**Comment by retif** [comment]
What I noticed is if after such erroneous connection i change  Remote>Containers>Docker Path from
/home/<your-user>/.local/bin/podman-host
back to
podman

it connects successfully with my users name, without errors, as was expected from podman-host. 
Then i can connect and disconnect multiple times. But if I restart container something is triggered and new connection from vscode connected as root again, and i need to repeat this double change of Docker Path again to fix it

**Comment by 89luca89** [comment]
@retif thanks for reporting
I've refactored the wrapper to now use only podman/docker directly, skipping the injection of distrobox commands

This improved the situation and I no longer see the unexpected terminations
