### ISSUE TITLE
[Error] Unable to create rootfull container when user is handled by systemd-homed

### ISSUE THREAD

**Issue by fcrozat** [89luca89/distrobox#1423]
**Describe the bug**
When user is handled by systemd-homed, rootfull container can't be created.

**To Reproduce**
on MicroOS Desktop/Aeon, with podman:

```
distrobox create --pull --root --init --unshare-all --image registry.opensuse.org/opensuse/distrobox:latest --name foobar
distrobox-enter --root foobar
```

**Logs**
[foobar.log](https://github.com/89luca89/distrobox/files/15484556/foobar.log)

**Comment by 89luca89** [comment]
Hi @fcrozat!

does this happen with rootless too?

Also can you share the content of `/etc/nsswitch.conf` of the host and the container?
it should have references to `systemd` 

Also it would be useful to have the content of /etc/passwd of the container 

Thanks!

**Comment by 89luca89** [comment]
In the meantime I've added a fallback that manipulates `/etc/shadow` directly to initialize the user in the container, this should now work

Let me know if there are still issues :+1:
