### ISSUE TITLE
[Error] initful ubuntu container doesn't source files in /etc/profile.d

### ISSUE THREAD

**Issue by acrispino** [89luca89/distrobox#1428]
I am using an initful Ubuntu-22.04 container on Fedora 40 Silverblue with podman 5.0.3. After upgrading from 1.7.1.0 to 1.7.2.1, scripts under /etc/profile.d/ are no longer being  sourced upon distrobox enter.

```shell
# Works in both 1.7.2.1 and 1.7.1.0
$ distrobox create -i quay.io/toolbx/ubuntu-toolbox:22.04 --additional-packages gawk
$ distrobox enter ubuntu-toolbox-22-04
# ...
$ gawkpath_default # from /etc/profile.d/gawk.sh
$ env | grep AWK
AWKPATH=.:/usr/share/awk
```

```shell
# Works in 1.7.1.0, not in 1.7.2.0 or 1.7.2.1
$ distrobox create -i quay.io/toolbx/ubuntu-toolbox:22.04 --additional-packages gawk --init
$ distrobox enter ubuntu-toolbox-22-04
# ...
$ gawkpath_default
gawkpath_default: command not found
```

The relevant commit seems to be  5ea3d17

**Comment by 89luca89** [comment]
Thanks @acrispino for reporting
this indeed was a regression and prompted me to find a nice solution for non-posix shells :)

thanks!
