### ISSUE TITLE
[Bug] XDG_ env variables still not being set when created with --home

### ISSUE THREAD

**Issue by Bvngee** [89luca89/distrobox#1429]
The problem I'm having is the exact same as in #420: With a `--home` set during distrobox-create, XDG_CONFIG_HOME and related env variables are still relative to the host's home dir. I see a fix was implemented [here](https://github.com/89luca89/distrobox/blob/main/distrobox-enter#L513-L517) in [this commit](https://github.com/89luca89/distrobox/commit/fc55cb8eed88ceacd26468eb3ab56e4356f6ac58), and I've manually double checked that that code snippet is present in my version of distrobox, but for whatever reason the issue persists. I have no idea why.

1. first I ran `distrobox create -i docker.io/library/debian:stable-backports -n Debian --hostname debian --home ~/distrobox/debian-home --nvidia`
2. `distrobox enter Debian`
3.
```
debian% echo $HOME
/home/<user>/distrobox/debian-home
debian% echo $XDG_CONFIG_HOME
/home/<user>/.config
```

**Expected behavior**
```
debian% echo $HOME
/home/<user>/distrobox/debian-home
debian% echo $XDG_CONFIG_HOME
/home/<user>/distrobox/debian-home/.config
```

**Logs**
`podman logs --latest`: [podman_latest.txt](https://github.com/user-attachments/files/15529206/podman_latest.txt)

**Desktop:**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 5.0.3
 - Which version of distrobox? distrobox: 1.7.2.1
 - Which host distribution? NixOS
 - How did you install distrobox? via the nixpkgs package

**Comment by 89luca89** [comment]
This works for me:

![image](https://github.com/89luca89/distrobox/assets/598882/2f7cb65f-4264-4a96-a56b-17ad13a4e679)

Can you try with latest git version?

**Comment by BvngeeCord** [comment]
> This works for me:
> ...
> Can you try with latest git version?

Yup, I just cloned the distrobox repo from git and ran the exact same command that you did:

![image](https://github.com/89luca89/distrobox/assets/69218859/1f7d4325-73f8-46ae-93eb-2a447eb7d9fd)

**Comment by 89luca89** [comment]
@BvngeeCord thanks for trying!

Strange, it seems probably there is something in either your profile or dotfiles setting them?

Can you try with `distrobox enter --dry-run` and see if the `env` is set correctly?

![image](https://github.com/89luca89/distrobox/assets/598882/ff819d7a-f62f-4f51-b31b-d00ffc2775a0)

**Comment by BvngeeCord** [comment]
> @BvngeeCord thanks for trying!
> 
> Strange, it seems probably there is something in either your profile or dotfiles setting them?
> 
> Can you try with `distrobox enter --dry-run` and see if the `env` is set correctly?

Yup! This is interesting..
![image](https://github.com/89luca89/distrobox/assets/69218859/a44a121c-05b0-429b-a253-b765a74f8f61)

**Comment by 89luca89** [comment]
@Bvngee I think if that's the case then it's not a distrobox problem, but you have something (like dotfiles or configs) setting those variables for you AFTER the login
