### ISSUE TITLE
[Error] shift count out of range, OCI permission denied

### ISSUE THREAD

**Issue by pavelxdd** [89luca89/distrobox#1430]
I don't know if it's intended or not, but here's what happens if double dash is the last argument in the enter command:
```
$ distrobox enter debian --                                                   
/usr/bin/distrobox-enter: line 256: shift: shift count out of range
Error: crun: open executable: Operation not permitted: OCI permission denied
```

**Comment by ProneelPal** [comment]
```
distrobox enter debian -- <binary to execute>
```
The `--` is used to run binaries inside distrobox containers. This is used while exporting app icons or binaries to host. The error is shown because it expects a binary next to it.

**Comment by 89luca89** [comment]
Right answer, not a bug
