### ISSUE TITLE
[Error] failed to bind mount to `/etc/localtime` Error: An error occurred - distrobox init

### ISSUE THREAD

**Issue by morrolinux** [89luca89/distrobox#1435]
**Describe the bug**

Arch linux host with ZFS root filesystem.
Creating any debian-based container fails with the error:
` Warning: failed to bind mount /run/host/usr/share/zoneinfo/Europe/Rome to /etc/localtime Error: An error occurred`: 
```
+ mount --rbind -o ro /run/host/usr/share/zoneinfo/Europe/Rome /etc/localtime
mount: /etc/localtime: filesystem was mounted, but any subsequent operation failed: Unknown error 5005.
+ printf Warning: failed to bind mount %s to %s\n /run/host/usr/share/zoneinfo/Europe/Rome /etc/localtime
Warning: failed to bind mount /run/host/usr/share/zoneinfo/Europe/Rome to /etc/localtime
+ return 1
+ [ 1 -ne 0 ]
+ printf Error: An error occurred\n
Error: An error occurred
DEBU[0000] Called logs.PersistentPostRunE(podman --log-level debug logs debian-bullseye) 
DEBU[0000] Shutting down engines                        
```

RHEL-based images like fedora work just fine.

**To Reproduce**
- Create a debian-based or ubuntu-based container on Archlinux with ZFS (not sure if ZFS is relevant here)
- Run `distrobox enter ...` for the first time.

**Expected behavior**
To initialize the container without errors.

**Logs**
[distrobox.log](https://github.com/user-attachments/files/15783808/distrobox.log)
[podman.log](https://github.com/user-attachments/files/15783831/podman.log)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
   - podman
 - Which version or podman, docker or lilipod?
   - 5.0.3
 - Which version of distrobox?
   - 1.7.2.1
 - Which host distribution?
   - Arch linux
 - How did you install distrobox?
   - extra/distrobox (arch repo)

**Additional context**

**Comment by 89luca89** [comment]
This has probably something to do with ZFS setup, anyway I've added a fallback+warning in these cases, where we go back to simply copying the file instead
