### ISSUE TITLE
Zed editor .desktop StartupWMClass needs manual intervention

### ISSUE THREAD

**Issue by mabequinho** [89luca89/distrobox#1438]
**Describe the bug**
Zed exported app icon isn't displayed correctly as in https://github.com/89luca89/distrobox/issues/1306 , while other programs like gvim and alacritty are correctly displayed.

exported `StartupWMClass` defaults to `Zed` instead of `dev.zed.Zed`

**To Reproduce**
* Gnome 46
* Install Zed on Arch Distrobox
* Export App

**Expected behavior**
Exported icon to be show correctly on Gnome Dash.
 
**Desktop (please complete the following information):**
 * podman version 5.0.3
 * distrobox version: 1.7.2.1
 * Silverbue 40

**Comment by 89luca89** [comment]
This seems to be a problem of zed
I don't mess around with the startupwmclass :man_shrugging:
