### ISSUE TITLE
[Error] `distrobox-enter` does not work when `/dev/shm` points to `/run/shm`

### ISSUE THREAD

**Issue by nathanchance** [89luca89/distrobox#144]
**Describe the bug**

On WSL2, `/dev/shm` is a symlink to `/run/shm` (for whatever reason, seems like Ubuntu used to do that too?). When `/dev` gets bind mounted into the container without `/run/shm`, the symlink is broken and the container runtime rightly complains:

```
$ realpath /dev/shm
/run/shm

$ distrobox enter dev-arch
Error: unable to start container "cbf9efdae48aae4730f9810e73e5322e686bcee1596091c27a257d7a1d9d8b0d": openat2 `dev/shm`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

**To Reproduce**

In WSL2 or another OS that has this same symlink behavior, a simple `distrobox-create` + `distrobox-enter` should reproduce it.

**Expected behavior**

There should be no error :)

**Additional context**

The issue is fixed if I add `--volume /run/shm:/run/shm` to my `distrobox-create` command but it seems like this is something that should be handled within `distrobox-create`, perhaps with something like:

```diff
diff --git a/distrobox-create b/distrobox-create
index 336fd72..ae355f6 100755
--- a/distrobox-create
+++ b/distrobox-create
@@ -292,6 +292,12 @@ generate_command() {
                --volume /sys:/sys:rslave
                --volume /tmp:/tmp:rslave"

+       dev_shm_path="$(realpath /dev/shm)"
+       if [ "${dev_shm_path}" != "/dev/shm" ]; then
+               result_command="${result_command}
+                       --volume ${dev_shm_path}:${dev_shm_path}:rslave"
+       fi
+
        # If we have a custom home to use,
        #       1- override the HOME env variable
        #       2- expor the DISTROBOX_HOST_HOME env variable pointing to original HOME
```

**Comment by 89luca89** [comment]
Hi @nathanchance 

seems to be related to `sysvinit` reading here: 
 
 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851427
 - https://github.com/flatpak/flatpak/issues/2136
 
 I'll craft a workaround for this based on your snippet when I'm back (if you want to PR I'm more than happy :smile: )
 
 Probably I'd just use `if [ -L "/dev/shm" ]` to check if it's a symlink or not
 I'll just add a comment before the check just to contextualize it so we'll remember in future why we're doing something like this :+1: 
 
 Thanks for the report :+1:
