### ISSUE TITLE
[Suggestion] Improve distrobox.ini schema documentation

### ISSUE THREAD

**Issue by Venefilyn** [89luca89/distrobox#1444]
**Is your feature request related to a problem? Please describe.**
Currently, looking through the distrobox.ini template and assemble command I'm struck with a sense of when does this execute, what does this mean, how can I do this thing that I want

For example, I want to create a distrobox.ini for a project I'm just starting out in that uses toolbx/distrobox and they have multiple scripts to install things. But `pre_init` and `pre_init_hooks` are confusing as to when they execute, what its purpose is etc. And this applies to pretty much every field in the distrobox.ini

**Describe the solution you'd like**
Distrobox.ini schema is further elaborated on with a clear markdown of what is required, what is optional, and what the different fields do

I should not have to go through source code to figure this out, if anything this should be part of the website and CLI manpage for distrobox-assembly

**Describe alternatives you've considered**
Maybe we figure out a more standardized approach that could also work for other tools in the future, such as if toolbx decides that a config per-repo would be a good idea we should not use the name distrobox.ini but something like containerbox.ini (this is out of scope for this issue but just wanted to throw it out there)

**Comment by 89luca89** [comment]
Thanks @Venefilyn this was indeed in my todo list

I've explained each option with types and what each one does
let me know if further improvement is needed :+1:
