### ISSUE TITLE
[Suggestion] Add Bluefin-cli to the list of compatible images

### ISSUE THREAD

**Issue by slimhk45** [89luca89/distrobox#1453]
Add the Bluefin-Cli image `ghcr.io/ublue-os/bluefin-cli` to the list of compatible images `distrobox create -C`.

PS: I have been redirected upstream here after this there
https://github.com/Dvlv/BoxBuddyRS/issues/93

**Comment by 89luca89** [comment]
Thanks @slimhk45 added!
