### ISSUE TITLE
[Error] Void Linux container gives error when installing packages after distrobox enter

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#1457]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
![image](https://github.com/89luca89/distrobox/assets/104856296/1e8b796e-4954-4d39-b87c-237265eeccd8)
I can't use void linuxcontainers because of this

**To Reproduce**
distrobox create -i ghcr.io/void-linux/void-glibc-full:latest -n void
distrobox enter void

**Expected behavior**
 Installs void linux just fine

**Logs**
[log.txt](https://github.com/user-attachments/files/15996303/log.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podmam
 - Which version or podman, docker or lilipod? 5.1.1
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? Bazzite deck edition
 - How did you install distrobox? It is part of the base image

**Additional context**

**Comment by classabbyamp** [comment]
> ERROR: runit-void-20231124_5: [unpack] failed to unpack files from archive: Unknown error -1

https://github.com/89luca89/distrobox/blob/63496a817f65829a5cd457a8ef5d8859d4b9ba9d/distrobox-init#L1138-L1140

it would make more sense to use an [xbps config noextract pattern](https://man.voidlinux.org/xbps.d#noextract=pattern) for the files that mess up the update

run `xbps-install -Sud runit-void` to figure out what file(s) it is and add `/etc/xbps.d/distrobox-ignore.conf` with `noextract=SomePathOrPattern` inside

**Comment by 89luca89** [comment]
@classabbyamp thanks for the pointer to noextract!

That's exactly what I need :) thanks! will craft a fix soon

**Comment by 89luca89** [comment]
Thanks @classabbyamp, I've implemented the proper fix :+1:

**Comment by dnkmmr69420** [comment]
I loved the quick response. thank you
