### ISSUE TITLE
[Error] Cannot assemble distrobox with name rawhide

### ISSUE THREAD

**Issue by p-fruck** [89luca89/distrobox#1464]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Cannot assemble distrobox with name `rawhide`

**To Reproduce**
- Create `distrobox.ini`:
  ```
  [rawhide]
  image=fedora:rawhide
  pull=true
  replace=true
  ```
- Run distrobox assemble create -n rawhide
  - Empty CLI output, no distrobox is built

**Expected behavior**
Distrobox should be assembled

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

[logs.txt](https://github.com/user-attachments/files/16082530/logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 5.0.3
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? Fedora Silverblue
 - How did you install distrobox? rpm-ostree

**Additional context**

I once fixed the issue by https://github.com/89luca89/distrobox/pull/1147, if I remember correctly this was something about the `[raw` sequence not being escaped correctly. However the changes where reverted due to some regression that is not mentioned any further in https://github.com/89luca89/distrobox/commit/1bb261a08a26231e50a4abd729e258a05c0403eb

**Comment by 89luca89** [comment]
Hi @p-fruck can you try with GIT version?

It seems to work for me:
![image](https://github.com/89luca89/distrobox/assets/598882/c9551aed-148b-40cf-b460-647c9d175cdd)

**Comment by p-fruck** [comment]
I investigated the problem and the issue does not exist in a subfolder. I had a little helper script named `d` in the same directory. If I lead the script, assembling works fine. It seems like `distrobox-assemble create` stops working after `touch d`

**Comment by 89luca89** [comment]
@p-fruck still I can't reproduce this to be honest

**Comment by p-fruck** [comment]
@89luca89 I think this was a misconfiguration in my setup. I will reach out if the issue shows up again and is actually reproducible
