### ISSUE TITLE
[Error] Distrobox hangs indefinitely when entering root container with system init

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [89luca89/distrobox#1470]
**Describe the bug**
I was following [this guide](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_libvirt_in_distrobox.md) for getting libvirt running on my system and ran into an issue where the system would lock up when entering the distrobox and become completely unresponsive. This is on a system running Sway and xfce-polkit, and I'm experiencing this issue on other tiled window managers as well. Lastly, my terminal of choice is Kitty which seems to work perfectly with regular distrobox containers. Unfortunately, I can't get the logs as the process halts during execution, so I've included my podman logs which looks like it succeeds creating the container but there are some notable errors that I'll share below:

```
3399   │ [FAILED] Failed to set up automount Arbitrary Executable File Formats File System Automount Point.
3400   │ See 'systemctl status proc-sys-fs-binfmt_misc.automount' for details.
3401   │ [  OK  ] Reached target Local Encrypted Volumes.
3402   │ [  OK  ] Reached target Login Prompts.
3403   │ [  OK  ] Reached target Local Integrity Protected Volumes.
3404   │ [  OK  ] Reached target Network is Online.
3405   │ [  OK  ] Reached target Path Units.
3406   │ [  OK  ] Reached target Slice Units.
3407   │ [  OK  ] Reached target Swaps.
3408   │ [  OK  ] Reached target Local Verity Protected Volumes.
3409   │ [  OK  ] Listening on Device-mapper event daemon FIFOs.
3410   │ [  OK  ] Listening on LVM2 poll daemon socket.
3411   │ [  OK  ] Listening on Process Core Dump Socket.
3412   │ [  OK  ] Listening on Journal Socket (/dev/log).
3413   │ [  OK  ] Listening on Journal Socket.
3414   │ systemd-udevd-control.socket: Socket service systemd-udevd.service not loaded, refusing.
3415   │ [FAILED] Failed to listen on udev Control Socket.
3416   │ See 'systemctl status systemd-udevd-control.socket' for details.
3417   │ systemd-udevd-kernel.socket: Socket service systemd-udevd.service not loaded, refusing.
3418   │ [FAILED] Failed to listen on udev Kernel Socket.
3419   │ See 'systemctl status systemd-udevd-kernel.socket' for details.
3420   │          Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
3421   │          Starting Load Kernel Module dm_mod...
3422   │          Starting Load Kernel Module drm...
3423   │          Starting Load Kernel Module efi_pstore...
3424   │          Starting Load Kernel Module loop...
3425   │          Starting Journal Service...
3426   │          Starting Remount Root and Kernel File Systems...
3427   │          Starting Apply Kernel Variables...
3428   │          Starting Coldplug All udev Devices...
```

I haven't cross-checked with a normal distrobox log whether or not these errors are expected though. 

**To Reproduce**
With a minimal system (fedora core + xfce-polkit + sway + kitty terminal), attempt to run the above-mentioned virtman tutorial after verifying that distrobox works as expected otherwise. 

**Expected behavior**
No hanging at bare minimum, would prefer a fail condition over the system crashing entirely. 

**Logs**
[podman-log.txt](https://github.com/user-attachments/files/16120813/podman-log.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Which version or podman, docker or lilipod?

`podman 5.1.1`

 - Which version of distrobox?

`distrobox 1.7.2.1`

 - Which host distribution?

Wayblue or UCore Atomic OS.

 - How did you install distrobox?

`rpm-ostree install distrobox` or equivalent layering

**Additional context**
This issue could more likely be a system configuration issue than an actual distrobox bug. My original guess was that polkit wasn't initialized properly on my system and was hanging on asking for user authentication but I've since verified that's not the problem. I'm a bit at a loss for what possible dependency I'm missing so I'm hoping that someone could help me debug this.

**Comment by 89luca89** [comment]
This has been fixed in a537dfffa6589640e586a1395eec498ed792ccd9
