### ISSUE TITLE
[Discussion] Problem with moving containers between computers

### ISSUE THREAD

**Issue by daniij** [89luca89/distrobox#1472]
I created a fedora 39 container on one pc and saved its image using podman.Transferred it to another pc and booted it using podman. (As instructed). When logging into the container created from this image, on the other PC an error occurs: unable to find user xx: no matching entries in passwd file. Probably this error occurs because the two computers have different usernames. Maybe I did something wrong? 

How can I solve this problem and use this container on the other PC without creating a new user with the same name as on the first PC?

If this question should be in the Error thread, then please forgive me.

**Comment by 89luca89** [comment]
This seems more related to podman than distrobox
