### ISSUE TITLE
[Error] Unable to enter container from a NixOS host ("Empty hostname")

### ISSUE THREAD

**Issue by jeaye** [89luca89/distrobox#1482]
**Describe the bug**
I'm unable to enter new containers, due to an error with the container hostname.

```bash
diff: /run/host/etc/static/hostname: No such file or directory
hostname: Empty hostname
Error: An error occurred
```

This error happens on multiple distros. I tested `archlinux:latest` and `ubuntu:latest` and they both have the same error.

**To Reproduce**
On NixOS 24.05, run the following:

```bash
distrobox create arch --image archlinux:latest
distrobox enter arch
```

**Expected behavior**
I expect to be able to enter the containers without error.

**Logs**
* distrobox logs (Arch): [distrobox-arch-enter.txt](https://github.com/user-attachments/files/16276505/distrobox-arch-enter.txt)
* docker logs (Arch): [docker-arch.txt](https://github.com/user-attachments/files/16276508/docker-arch.txt)
* distrobox logs (Ubuntu): [distrobox-ubuntu-enter.txt](https://github.com/user-attachments/files/16276509/distrobox-ubuntu-enter.txt)
* docker logs (Ubuntu): [docker-logs-ubuntu.txt](https://github.com/user-attachments/files/16276510/docker-logs-ubuntu.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? `docker`
 - Which version or podman, docker or lilipod? `Docker version 24.0.9, build v24.0.`
 - Which version of distrobox? `distrobox: 1.7.2.1`
 - Which host distribution? `NixOS 24.05`
 - How did you install distrobox? `Nix`

**Additional context**
I do very much suspect that this is related to NixOS just doing things different, BUT this used to work. I have old containers that I was previously using (before a NixOS upgrade -- which also included a distrobox upgrade). I can still enter those old containers.

For the record, my hostname file:

```bash
[nix-shell:~]$ ls -lh /etc/hostname
lrwxrwxrwx 1 root root 20 Jul 17 17:59 /etc/hostname -> /etc/static/hostname

[nix-shell:~]$ cat /etc/hostname
thelio
```

**Comment by lesserfish** [comment]
Hello!

This is indeed a bug caused by NixOS's weird file hierarchy. I've submitted a pull request with a bug fix (#1506).

In case you are in a hurry and want to get this working right away, replace line 2409 of the file `distrobox-init` from 

    file_watch_src="/run/host${file_watch}"

to

    file_watch_src="readlink -f /run/host${file_watch}"


All the best!

**Comment by jeaye** [comment]
Thank you, thank you, thank you! I'm sure everyone on NixOS will be pleased to see this fixed. For me, it's been a blocker for multiple projects.

**Comment by 89luca89** [comment]
What version are you using? 
The repo version has the configuration fix for distrobox to work

https://github.com/NixOS/nixpkgs/blob/d51c28603def282a24fa034bcb007e2bcb5b5dd0/pkgs/applications/virtualization/distrobox/default.nix#L30

This is not a distrobox bug, use the additional volume
