### ISSUE TITLE
[Suggestion] ephemeral should default to a temparary home

### ISSUE THREAD

**Issue by ZefQ** [89luca89/distrobox#1484]
**Is your feature request related to a problem? Please describe.**
When i create a ephemeral distrobox i expect everything I do in that environment to disappear once i exit the environment. As it is now things lingerer in the hosts home directory if anything i did in that environment wrote content to anything under $HOME 

**Describe the solution you'd like**
That a temporary home directory is created and used as default. mktemp is alrady used with dry-run to generate a random name, why not let it create a temp folder instead that gets thrown away on exit.

**Comment by Zeglius** [comment]
Rather than a default, a flag for it would be better to avoid breaking issues with any user made script

**Comment by 89luca89** [comment]
I don't think this would be a sane default
You can simply pass any `create` flag to ephemeral to set it to a custom home (or use `DBX_CONTAINER_HOME_PREFIX` to make it one automatically for you)
