### ISSUE TITLE
[Suggestion] Option to specify network flag when creating a distrobox

### ISSUE THREAD

**Issue by janlothar** [89luca89/distrobox#1485]
**Is your feature request related to a problem? Please describe.**
I’m always frustrated when I create new containers and have to manually configure the network for each one. I use a container that configures VPN for me, and when I create new containers, I use the flag --network container:vpn-container so that these new containers are routed through this VPN without having to configure the network for each one. Since distrobox creates podman containers with 'host' I can't even use `podman network disconnect` and then `podman network connect`.

**Describe the solution you'd like**
I would like to create Distrobox containers with a flag that allows me to specify a network, similar to the --network container:vpn-container flag. This would streamline the process and ensure all new containers are automatically routed through the specified VPN container.

**Describe alternatives you've considered**
Currently I create distro containers manually through podman for instances where I really need that network configuration.

**Additional context**
I use this [container that configures VPN](https://github.com/qdm12/gluetun).

**Comment by 89luca89** [comment]
You can use`--unshare-netns` combined with `--additional-flags "--network foo"`, it's much clearer and easier using `distrobox assemble` to make them declarative

I'm not going to add more flags to the CLI
