### ISSUE TITLE
[Error] Startup notification works weird on Plasma

### ISSUE THREAD

**Issue by Shatur** [89luca89/distrobox#1486]
**Describe the bug**
When I start Firefox from the .desktop file created by Distrobox, it looks on the taskbar like this:
![image](https://github.com/user-attachments/assets/29d0762b-7baa-455d-993c-fa4a4904c7a1)
Then second instance appears:
![image](https://github.com/user-attachments/assets/4c8a2675-ec80-49c4-886b-a4ed23060481)
And in the end the second instance becomes the main one:
![image](https://github.com/user-attachments/assets/a9352523-af33-4fac-b150-a3198511a51e)

**To Reproduce**
1. Install firefox inside a container
2. Launch it.
3. Pin to taskbar.
4. Close and run again.

**Expected behavior**
I would expect to see a single instance.
As a workaround I can set `StartupNotify=false` to `false`.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.5.1
 - Which version of distrobox? 1.4.2.1
 - Which host distribution? SteamOS
 - How did you install distrobox? preinstalled

**Comment by 89luca89** [comment]
This looks like a *very* old instance of distrobox

Please retry with a newer one, and if the problem persist, reopen the issue, thanks
