### ISSUE TITLE
[Suggestion] Support for Linux (Linux distros based Directly on the Kernel)

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [89luca89/distrobox#1492]
**Is your feature request related to a problem? Please describe.**
I want to use distrobox on any OS based on the Linux Kernel
**Describe the solution you'd like**
Support for the system

**Describe alternatives you've considered**
Support for Distrobox without any package manager
**Additional context**

**Comment by Xanderplayz16** [comment]
This already exists.....
