### ISSUE TITLE
[Error] OBS in Ubuntu distrobox cannot use the obs-vkcapture plugin (isolation issue?)

### ISSUE THREAD

**Issue by ItsRogueRen** [89luca89/distrobox#1499]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
When using OBS from a Distrobox container (i.e. Ubuntu so that you have the API log in for Twitch/YouTube/etc) the obs-vkcapture plugin is unable to capture flatpaks running outside of the distrobox. Currently trying to figure out of this is an issue with the plugin or distrobox

**To Reproduce**
Install an Ubuntu distrobox
Install OBS Studio
Compile the obs-vkcapture plugin from source (no binary is provided)
Run a flatpak application with OBS Game Capture enabled (i.e. something in Bottles)
Make a Game Capture in OBS

**Expected behavior**
Game Capture sees the running flatpak program and captures it

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 5.1.1
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? Nobara 40
 - How did you install distrobox? dnf

**Additional context**
Everything is done with GUIs so I'm not sure how to get the logs needed

**Comment by ItsRogueRen** [comment]
obs-vkcapture dev has responded and it does seem to be a distrobox related issue. 

https://github.com/nowrep/obs-vkcapture/issues/224#issuecomment-2267643579

Would there be a way to allow this to work within a distrobox with a flatpak running outside of distrobox?

**Comment by 89luca89** [comment]
Hi @ItsRogueRen do you still have this problem?
Can you ensure obs in dbox is running on wayland with portals and not with xway?

I'll need help here to debug this

**Comment by ItsRogueRen** [comment]
> Hi @ItsRogueRen do you still have this problem?
> Can you ensure obs in dbox is running on wayland with portals and not with xway?
> 
> I'll need help here to debug this

I can set it back up and test tonight

**Comment by ItsRogueRen** [comment]
I quickly set this up on my laptop (same distro, same desktop, same install method, but Intel iGPU instead of a dedicated AMD GPU). Distrobox is the same version but podman has since updated to 5.2.3

The setup seems to be working on my laptop. I'm using the obs-vkcapture on the program VSeeFace which is running in wine via bottles (flatpak). OBS is running in an Ubuntu 22-04 distrobox which I have not changd any default settings in. The version should be on wayland by default. the Game Capture does appear to work with transparency enabled when previously it did not see the window to capture at all. I'll be setting this back up on my production desktop later tonight to see if the same results happen. 

![image](https://github.com/user-attachments/assets/9e5e9dee-06ab-4031-a4ac-30865b4d68d8)

**Comment by ItsRogueRen** [comment]
> I quickly set this up on my laptop (same distro, same desktop, same install method, but Intel iGPU instead of a dedicated AMD GPU). Distrobox is the same version but podman has since updated to 5.2.3
> 
> The setup seems to be working on my laptop. I'm using the obs-vkcapture on the program VSeeFace which is running in wine via bottles (flatpak). OBS is running in an Ubuntu 22-04 distrobox which I have not changed any default settings in. The version should be on wayland by default. the Game Capture does appear to work with transparency enabled when previously it did not see the window to capture at all. I'll be setting this back up on my production desktop later tonight to see if the same results happen. 
> 
> Image below of the capture working correctly:
> 
> ![image](https://github.com/user-attachments/assets/9e5e9dee-06ab-4031-a4ac-30865b4d68d8)
> 

Just tested it on my main desktop as well, and it is also working there. I'm honestly confused as to why it's now working when it failed no matter what I did before...

**Comment by 89luca89** [comment]
Ok marking as solved then, if you get to reproduce feel free to reopen
