### ISSUE TITLE
[Suggestion] Add ublue toolbox to list of compatible image

### ISSUE THREAD

**Issue by asen23** [89luca89/distrobox#1501]
**Is your feature request related to a problem? Please describe.**
Boxbuddy is using list of compatible image for their dropdown selection and i like to see ublue image there.

**Describe the solution you'd like**
Add image from https://github.com/ublue-os/toolboxes.
```
ghcr.io/ublue-os/bluefin-cli
ghcr.io/ublue-os/ubuntu-toolbox
ghcr.io/ublue-os/fedora-toolbox
ghcr.io/ublue-os/wolfi-toolbox
ghcr.io/ublue-os/powershell-toolbox
ghcr.io/ublue-os/docker-distrobox -> need init and root
ghcr.io/ublue-os/docker-distrobox -> need init and root
```

**Describe alternatives you've considered**
Manually typing the image url.

**Additional context**
Ublue toolbox launch instantly and in general are nicer to use.

**Comment by kth8** [comment]
Universal Blue also maintain an Arch Linux image under another repo https://github.com/ublue-os/arch-distrobox
