### ISSUE TITLE
[Error] Distrobox patially breaks GitLens when running VsCodium from inside a distrobox

### ISSUE THREAD

**Issue by MateusRodCosta** [89luca89/distrobox#1502]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Apparently GitLens works by manually running certain git commands in a special shell, however distrobox makes the shell appear a little later than GitLens expects, breaking the command.
Once the shell becomes functional you can copy and paste the GitLens command and it will run fine.

**To Reproduce**
Create a distrobox, install VSCodium inside it and the GitLens extension. Try to use GitLens normally.

**Expected behavior**
Expected GitLens to work normally the same way as on flatpak or installed on host.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

IMHO, N/A.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman-5.1.2-1.fc40.x86_64
 - Which version of distrobox? distrobox-1.7.2.1-1.fc40.noarch
 - Which host distribution? Fedora Silverblue 40
 - How did you install distrobox? rpm-ostree override where I replaced toolbox with distrobox

**Additional context**

This issue seems to be more closely related to GitLens not waiting for the distrobox shell to become available, so this could likely be solved by making GitLens wait or if the distrobox shell loaded faster.

**Comment by 89luca89** [comment]
Yes I'd say it's more related to the plugin not waiting for the execution to finish

distrobox shell execution could be faster, but this is out of scope of my priorities for now, I'd be better to reopen another issue as a feature/suggestion (improve enter performance?) and let it stay there to be scheduled for the future
