### ISSUE TITLE
[Error] pacman: error while loading shared libraries: libassuan.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WMan22** [89luca89/distrobox#1515]
**Describe the bug**
Unable to use pacman or distrobox upgrade for anything due to a missing library.

**To Reproduce**
```
[wman@nobara-3060 ~] sudo dnf install podman-docker
[wman@nobara-3060 ~] sudo dnf install distrobox
[wman@nobara-3060 ~]$ distrobox-create --nvidia --name arch --image archlinux
[wman@nobara-3060 ~]$ distrobox enter arch
[wman@arch ~]$ sudo pacman -Syu
```

**Expected behavior**
I expected the package manager in the arch linux container I created to function.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
[distrobox-createverbose.txt](https://github.com/user-attachments/files/16568741/distrobox-createverbose.txt)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
```
[wman@nobara-3060 ~]$ podman logs --latest
[wman@nobara-3060 ~]$ docker logs --latest
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 podman-docker
 - Which version or podman, docker or lilipod?
 podman-docker-5:5.1.2-1.fc40.noarch
 - Which version of distrobox?
 distrobox-1.7.2.1-1.fc40.noarch
 - Which host distribution?
 Nobara Project 40 Official
 - How did you install distrobox?
 Through sudo dnf install distrobox.

**Additional context**
N/A

**Comment by Strikeless** [comment]
Also occurs for me on NixOS (unstable nixpkgs) and Docker with image [docker.io/library/archlinux:latest](docker.io/library/archlinux:latest). Worked fine about a year ago with mostly the same setup.

**Comment by WMan22** [comment]
> Also occurs for me on NixOS (unstable nixpkgs) and Docker with image [docker.io/library/archlinux:latest](docker.io/library/archlinux:latest). Worked fine about a year ago with mostly the same setup.

Yeah it happened when I used that exact link instead of "archlinux" too.

**Comment by WMan22** [comment]
> Also occurs for me on NixOS (unstable nixpkgs) and Docker with image [docker.io/library/archlinux:latest](docker.io/library/archlinux:latest). Worked fine about a year ago with mostly the same setup.

Turns out, the problem seems to be using docker.io/library/archlinux:latest as in the image itself is bugged and does not include an essential library. I checked into https://gitlab.archlinux.org/archlinux/archlinux-docker and using quay.io/archlinux/archlinux:latest instead of docker.io fixes the problem. Closing issue.
