### ISSUE TITLE
[question]  Is it expected for containers to inherit environment variables from the host? 

### ISSUE THREAD

**Issue by SadSock** [89luca89/distrobox#1516]
I'm using distrobox on nixos, with Arch Linux inside the container. I found that the container inherited environment variables from the host. Is this expected behavior? Why is it designed this way? 

Because nixos is not FHS-compliant, this causes a lot of trouble.

**Comment by 89luca89** [comment]
Yes it is
that's one of the main point of distrobox :)

I've used it successfully on my (admittedly few) test on Nixos
Any other problem like this should first be opened to the packager for Nixos, and see if it can be solved as a config
