### ISSUE TITLE
[Error] [ChromeOS] test container attempts to index an out of range /dev/pts file and dies

### ISSUE THREAD

**Issue by Beethoven-n** [89luca89/distrobox#1517]
Please, before opening a bug:

- [x] Make sure you've read the documentation.
- [x] Ensure there isn't already an open issue about this.
- [x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
When I create and run the official test container from a fresh Penguin environment, I get this output:
`Error: crun: open /dev/pts/5: No such file or directory: OCI runtime attempted to invoke a command that was not found`

**To Reproduce**
- Set up a fresh Linux environment on a Chromebook.
- Inside this environment, set up Podman for rootless mode
- do:
```sh
distrobox create -n test
distrobox enter test
```
- appreciate the error. it always talks about a /dev/pts file that does not exist, no matter how many tabs you have open

**Expected behavior**
The test container runs.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[distrobox.log](https://github.com/user-attachments/files/16591128/distrobox.log)
[podman.log](https://github.com/user-attachments/files/16591129/podman.log)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
Podman
 - Which version or podman, docker or lilipod?
4.3.1
 - Which version of distrobox?
1.4.2.1
 - Which host distribution?
Debian 12 (Bullseye)
 - How did you install distrobox?
apt

**Additional context**

i beg you please allow shell redirection so i can just `distrobox enter test > error.log`  that would have made reporting this so much easier

**Comment by 89luca89** [comment]
This version of distrobox is ancient (and likely before the support for chromeos) try with the git version, if the problem persist, reopen the issue, thanks!
