### ISSUE TITLE
[Error] Cannot open X windows via ssh with custom home directory

### ISSUE THREAD

**Issue by phoppermann** [89luca89/distrobox#1518]
**Describe the bug**
When creating a distrobox with a custom home directory, X windows do not open anymore when ssh-ing to the distrobox host.

**To Reproduce**
- create distrobox with `--home`
- ssh from remote to the distrobox host
- open an X windows in distrobox

**Expected behavior**
The X window opens as without `--home`.

**Desktop:**
 - docker 20.10.9
 - distrobox 1.7.2.1 via RPM
 - openSuse Leap

**Additional context**
Copying `.Xauthority` from the host solves the problem. Can/should this happen automatically?

**Comment by 89luca89** [comment]
No it shouldn't this is because having different Xauthority relies on having different homes
