### ISSUE TITLE
[Discussion] init initended when enter after stop?

### ISSUE THREAD

**Issue by phoppermann** [89luca89/distrobox#1519]
I did `distrobox stop` and then `distrobox enter`. This triggered `distrobox-init` (incl. password setup). Is this the intended behavior? My expectation was that init happens only once after create.

I'm using docker with 1.7.2.1 + https://github.com/89luca89/distrobox/commit/43eb2238e602a0bf1ba4ddb1e3ff3e38ef38d815 and my PRs which have been merged to main.

**Comment by 89luca89** [comment]
init is launched every time the container is stopped
if the password is not set correctly it will be asked again until success
