### ISSUE TITLE
[Suggestion] FreeBSD as a guest OS in a distrobox container?

### ISSUE THREAD

**Issue by Emily511511** [89luca89/distrobox#1522]
Very simple title. Are there any plans to add FreeBSD as an additional supported choice as a guest OS?

**Comment by kth8** [comment]
I know you can run Linux jails under FreeBSD using their binary compatibility layer but never heard of running FreeBSD containers under Linux before.

**Comment by Emily511511** [comment]
> I know you can run Linux jails under FreeBSD using their binary compatibility layer but never heard of running FreeBSD containers under Linux before.

Bruteforcing by putting FreeBSD in a virtual machine and adding integration should be doable.

I don't know if it is possible to put FreeBSD in a "clean container", so-to speak, because FreeBSD and Linux don't use the same kernel (same reason why we can't have a Windows or MacOS distrobox image without virtual machines).

**Comment by kth8** [comment]
Distrobox is a container manger instead of a virtual machine manager so I'm not sure how you see it adding VM support and guest integration. Maybe [Vagrant](https://www.vagrantup.com/) is more what you're looking for?

**Comment by 89luca89** [comment]
This is not doable for the same reason as Windows or Macos guest are not

they won't run on a linux kernel
