### ISSUE TITLE
[Error] setting extended attributes ...  operation not supported

### ISSUE THREAD

**Issue by Ferenc-** [89luca89/distrobox#1529]
Please, before opening a bug:

[x] make sure you've read the documentation.
[x] Ensure there isn't already an open issue about this.
[x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Createing a distrobox out of `freedesktopsdk/toolbox` images fails with `error setting extended attributes ... operation not supported`. 

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Logs**
[fu-logs.txt](https://github.com/user-attachments/files/16726075/fu-logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
`podman`
 - Which version or podman, docker or lilipod?
````
podman --version
podman version 4.9.4-rhel
````
 - Which version of distrobox?
````
distrobox --version
distrobox: 1.7.1.0
````
 - Which host distribution?
````
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
````

 - How did you install distrobox?
`RPM`

**Additional context**
Other images work fine.

**Comment by 89luca89** [comment]
This is not a supported distribution image, please refer to the compatibility list in the docs for a comprehensive list of distros
