### ISSUE TITLE
[Enhancement] Including distrobox in Debian repository

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#153]
Installing distrobox is pretty simple, but it would be nice to install it from a distribution's repository.

I have no experience as a maintainer or packager, so if anyone wants to give a shot at this, it's welcome :smile:

**Comment by michel-slm** [comment]
I'm trying to get started on becoming a Debian maintainer, so ... sure, let me file an ITP (intent to package) on this. This is probably easier than grokking Debian's Python packaging anyway

**Comment by 89luca89** [comment]
Sure! Give it a shot :smile: thanks!

**Comment by 89luca89** [comment]
Heads up, next version will include #190 
This will DEPRECATE the use of `--path/-p` in favor of `--prefix/-P` to behave similar to makefiles.
This way you specify only the base path where `bin` and `man` will be installed, for example

`./install --prefix /usr/local`

**Comment by 89luca89** [comment]
update: 

as of version `1.2.14` it is possible to specify defaults in a configuration file in the following system locations:

- /usr/share/distrobox/distrobox.conf
- /etc/distrobox/distrobox.conf

This will allow a bit of personalization during packaging, for example it would be possible for debian to specify:

```sh
container_image="docker.io/library/debian:stable-backports"
container_manager="autodetect"
container_name="debian-distrobox"
```

**Comment by cat-master21** [comment]
Currently there is a ongoing PR in [Pacstall](pacstall.dev) to include distrobox. Pacstall is used with Debian & Ubuntu. You can maintain it if you like. Sadly you cannot package Distrobox as a deb but it is a issue at: https://github.com/pacstall/pacstall/issues/467.

**Comment by 89luca89** [comment]
> Currently there is a ongoing PR in [Pacstall](pacstall.dev) to include distrobox. Pacstall is used with Debian & Ubuntu. You can maintain it if you like. Sadly you cannot package Distrobox as a deb but it is a issue at: [pacstall/pacstall#467](https://github.com/pacstall/pacstall/issues/467).

Probably I'm not the most indicated person to maintain this as I'm not a Debian nor Ubuntu user :sweat_smile:

**Comment by michel-slm** [comment]
Sorry for the delay - $dayjob has been hectic, and I've been slowly setting up my Debian packaging environment. Just filed the ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008291 - and I should have time to get an initial package up for review next week.

**Comment by michel-slm** [comment]
This is now uploaded to Debian Mentors: https://mentors.debian.net/package/distrobox/

I'll work on finding someone to review and then sponsor an upload next

**Comment by 89luca89** [comment]
Great news thanks! :heart:

**Comment by michel-slm** [comment]
This can be closed now:

https://packages.debian.org/sid/distrobox

**Comment by michel-slm** [comment]
(or actually we can wait a few days until it hits testing too then I will do a PR updating the host distro doc)

**Comment by 89luca89** [comment]
> https://packages.debian.org/sid/distrobox

Great news :tada: 

> (or actually we can wait a few days until it hits testing too then I will do a PR updating the host distro doc)

Yea let's wait at least it reaches testing, then we'll update the docs and close this :+1:

**Comment by dawidd6** [comment]
It reached testing FYI.

**Comment by 89luca89** [comment]
Yay! Will release new version soon hopefully it will take less time now :sweat_smile:
