### ISSUE TITLE
[Error] distrobox container loose name resolution each time I switch to a different WLAN

### ISSUE THREAD

**Issue by hunger** [89luca89/distrobox#1532]
**Describe the bug**

Whenever my laptop switches to a different WLAN, name resolution inside all open distrobox containers fails and stays broken till I restart distrobox.

**To Reproduce**

1. `distrobox enter`
2. `wget google.com` works inside the new distrobox container
3. Switch do a different network using network manager
4. `wget google.com` inside the distrobox container opened in 1. fails to resolve google.com

**Expected behavior**

I can switch networks on the host and the distrobox containers stay functional.

**Logs**

Not sure which ones would be helpful here...

**Desktop (please complete the following information):**

I am in Aeon Linux with no changes whatsoever...

I am using podman 5.2.2, distrobox 1.7.2.1. Both come pre-installed by aeon.

**Additional context**

This used to work just fine earlier... but I can't say for sure when this broke :-/

**Comment by 89luca89** [comment]
Can you help me debug this?

I'll need you to check how `/etc/resolv.conf` changes during this, is it a symlink? What does `podman logs -f <name of container>` show during the VPN change?

**Comment by hunger** [comment]
Sorry, that is no longer possible: After two weeks of not making any progress with this issue, I installed Fedora Silverblue (with toolbox) instead. It was super annoying :-)

I was on a 100% standard Aeon installation released on Aug. 24th. That is a fully immutable distribution, so it might be possible to reproduce the setup.

I guess I can close this now... sorry, I forgot about having filed the ticket, otherwise I would have closed it after reinstalling things.
