### ISSUE TITLE
[Error] commit/c05b6a43769bfa56d572a457f1420e0e2589fe3b : distrobox enter fail

### ISSUE THREAD

**Issue by Xdavius** [89luca89/distrobox#1539]
**Describe the bug**
distrobox enter archlinux after distrobox create archlinux:latest fail, on podman and docker

**To Reproduce**
```
distrobox-create --image docker.io/archlinux/archlinux:latest --name archlinux
davius@debian:~$ distrobox enter archlinux
Starting container...                            [ OK ]
Installing basic packages...                     Error: An error occurred
```

**Expected behavior**

**Logs**
```
+ locale-gen -a
Generating locales...
  en_US.UTF-8... done
  fr_FR.UTF-8...[error] cannot open locale definition file `fr_FR': No such file or directory
+ '[' 4 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? tested on podman/docker
 - Which version or podman, docker or lilipod? Debian Stable version : 
 
   podman/stable 4.3.1+ds1-8+deb12u1 amd64
   docker.io/stable,now 20.10.24+dfsg1-1+b3 amd64

 - Which version of distrobox? -git latest commit
 - Which host distribution? Debian 12
 - How did you install distrobox? Pacstall (I am the maintainer for distrobox pacscript)

**Additional context**
No problem with the latest stable release. Was working before nicely with previous commit.
The latest commit has a breaking bug

Also with archlinux, locale-gen doesn't work : need to reinstall glibc first to deploy languages packages from the archlinux OCI
Was discussed with Antiz, from Archlinux Core team. This is related on how the archlinux image is created.

locale-gen for french method for archlinux OCI : 
- Uncomment fr_FR.UTF8 in /etc/locale.gen
- Pacman -Sy glibc #Will create the language archive and run locale-gen as postinstall script.

Because it's a minimal image, glibc is only partialy deployed, and only en_US is available.

replacing `locale-gen -a` by `pacman -S glibc --no-confirm` should solve the issue, with locale OK.

**Comment by 89luca89** [comment]
Fixed in 54aad24f97b7321fd6e52ea1310e8894a324c638
