### ISSUE TITLE
[Enhancement] Including distrobox in Ubuntu repository

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#154]
Installing distrobox is pretty simple, but it would be nice to install it from a distribution's repository.

I have no experience as a maintainer or packager, so if anyone wants to give a shot at this, it's welcome :smile:

**Comment by 89luca89** [comment]
update: 

as of version `1.2.14` it is possible to specify defaults in a configuration file in the following system locations:

- /usr/share/distrobox/distrobox.conf
- /etc/distrobox/distrobox.conf

This will allow a bit of personalization during packaging, for example it would be possible for ubuntu to specify:

```sh
container_image="docker.io/library/ubuntu:22.04"
container_manager="autodetect"
container_name="ubuntu-distrobox"
```

**Comment by michel-slm** [comment]
I have a dedicated Ubuntu machine now (that I'll be using for Debian packaging) - so it should be straightforward to provide an Ubuntu PPA as well based on the same build scripts.

**Comment by 89luca89** [comment]
That's great news thanks!

**Comment by michel-slm** [comment]
PPA is now available! `sudo add-apt-repository ppa:michel-slm/distrobox`

Eventually this will make it to Debian, and from then on it will be available in the main Ubuntu repos, but I'll keep the latest versions in my PPA anyway.

Blog post: https://michel-slm.name/posts/2022-05-04-distrobox-for-debian-ubuntu/

**Comment by 89luca89** [comment]
Great news thanks! :heart:

**Comment by LyzardKing** [comment]
@michel-slm 
The upstream version of docker should be set as an alternative dependency as well in the debian control file.
the package is named `docker-ce`

**Comment by 89luca89** [comment]
> @michel-slm The upstream version of docker should be set as an alternative dependency as well in the debian control file. the package is named `docker-ce`

Is it possible to have an "podman or docker" dependency?
So that if either of them is already installed, that's fine
if none is installed, prefer podman

**Comment by LyzardKing** [comment]
I'm pretty sure that we can't use wildcards in the dependency list.
But what I'm proposing is simply another alternative:
try (in this order):
podman, docker-ce, docker.io

Podman would be preferred, then docker-ce (only available if the PPA is added, ignored otherwise), finally try the docker.io package in the repos

**Comment by 89luca89** [comment]
This is done
