### ISSUE TITLE
[Suggestion] It would be great if distrobox cli have a command to list available container distros.

### ISSUE THREAD

**Issue by tirtharajsinha** [89luca89/distrobox#1540]
**Is your feature request related to a problem? Please describe.**
When I try new a distro, and have to look into markdown file on github for it for the actual name.

**Describe the solution you'd like**
Introduce a commande like ```distrobox-list-available``` to show all the available container distros listed on https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#containers-distros

**Describe alternatives you've considered**
tried to webscrap the table using python and make cli tool but that's was not very promising.

**Comment by tirtharajsinha** [comment]
Please let me know If any command like that already exists I don't know of.

**Comment by 89luca89** [comment]
`distrobox create --compatibility`

See help and man pages
