### ISSUE TITLE
[Error] Distrobox rm / Distrobox enter returns error when container has short environment variables

### ISSUE THREAD

**Issue by senioroman4uk** [89luca89/distrobox#1546]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Distrobox does not handle containers that have short environment variables

**To Reproduce**
1. create a box with rocm/pytorch
```distrobox create --name rocm --image rocm/pytorch:latest --home ~/Boxes/rocm-pytorch```
2. try to enter this box or remove it
```
distrobox enter rocm
```

```
distrobox rm rocm
```

Observe the error
Error: template: inspect:1:37: executing "inspect" at <slice . 0 5>: error calling slice: index out of range: 5

**Expected behavior**
Distrobox is entered / removed without any errors

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

[logs.txt](https://github.com/user-attachments/files/16861523/logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 5.2.2
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? bluefin-dx:latest 
 - How did you install distrobox? Came pre-installed with the distro

**Additional context**
n/a

**Comment by 89luca89** [comment]
Solved by #1545
