### ISSUE TITLE
[Error] zfs root file system overlayfs error

### ISSUE THREAD

**Issue by osevan** [89luca89/distrobox#1550]
~ 1m 6s
  ❯ distrobox create -n deb
  Image registry.fedoraproject.org/fedora-toolbox:39 not found.
  Do you want to pull the image now? [Y/n]: n
  next time, run this command first:
  podman pull registry.fedoraproject.org/fedora-toolbox:39

  ~ 11s
  ❯ distrobox-list
  Error: configure storage: kernel does not support overlay fs: 'overlay' is not supported over zfs at "/home/ra/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver^C
~

**Comment by 89luca89** [comment]
This is a podman configuration problem, nothing to do with distrobox
