### ISSUE TITLE
[Suggestion] Distrobox to do less things automatically

### ISSUE THREAD

**Issue by findurance** [89luca89/distrobox#1570]
**Is your feature request related to a problem? Please describe.**
`distrobox enter my-container`

There are several problems, that Distrobox assumes a specifc workflow, meaning: it wants to create a container, no matter what

1. If distrobox.conf exists, `distrobox enter ...` will forcibly create a new container
2. If distrobox.conf does *not* exist, `distrobox enter ...` will prompt user to create a new container, since 'Y' is the default reply. There is **no way** to make 'N' the default!  ----> Y is the default reply and there only is a `-y` flag for `distobox create`, too. So `distrobox enter` can only assume "yes", or "YES", which already does not make sense.
 
**Describe the solution you'd like**
Do not enforce a container creation in every workflow. Instead, this should be optional, say `-c` flag: "Create a new container, if none exists".

For how Distrobox currently handles things, it makes it quite impossible to have an error-proof automation of things, as there is no fine-grained phases in the operations. So, in case a container does not exist before hand, user would just want to exit, and create a container manually.

Now due to creation is enforced, it is very easy to create default containers by accident. And this makes automating workflows very difficult too.

**Describe alternatives you've considered**
1. Tried to search for a container name using both commands: `podman` and `distrobox`. They give out a listing of containers, which I need to parse, cut and text format to find out if a container exists.
-> if `distrobox enter ..` would just tell "container did not exist" and returned an error code, things would work as a normal programmer might think: fail early.

**Additional context**
Here is an example from openSUSE Tumbleweed, after disabling `/usr/etc/distrobox/distrobox.conf`

$ distrobox enter tw-test 
Error: no such container tw-test
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]: n
Ok. For creating it, run this command:
        distrobox create <name-of-container> --image <remote>/<docker>:<tag>

So, it is pretty clear that an operation where I simply want to enter a non-existing container, Distrobox tries to shove me another container, and there is **no way** of telling it not do that!

**Comment by 89luca89** [comment]
This is a problem with your distro's configuration not with distrobox
As you already see it does not forcibly do anything if the config to `assume_yes` is not set

Defaults to Y/n it's because I like it as is, so I'll keep it like so :shrug:

**Comment by findurance** [comment]
Where are the available configuration keys defined?

When navigating to https://github.com/89luca89/distrobox/blob/main/docs/README.md#configure-distrobox it only shows a very limited config example, and does not list `assume_yes`, for example.

**Comment by findurance** [comment]
Where do I find the configuration keys that are usable?
