### ISSUE TITLE
Incorrect Timestamps in distrobox-list After Forced Reboot

### ISSUE THREAD

**Issue by freddygaffey** [89luca89/distrobox#1573]
**Describe the bug**
when I ran ``distrobox-list`` after force reboot it outputted 

(base) [fred@fred-arch-i3 cozy]$ distrobox-list
ID           | NAME                 | STATUS             | IMAGE
4941abaa58d5 | distrobox-audible    | Exited (0) 46 hours ago | docker.io/library/debian:latest
c922fd57e94f | cozy-distroBox       | Exited (143) 4 hours ago | docker.io/library/debian:latest
85701d6fb512 | cozy-ubuntu          | Exited (0) 292 years ago | docker.io/library/ubuntu:latest
efb63182f382 | cozy-ubuntu-2        | Exited (0) 292 years ago | docker.io/library/ubuntu:20.04
f601928ff338 | cozy-deb             | Exited (0) 292 years ago | registry.fedoraproject.org/fedora-toolbox:39
429f861e7346 | cozy-ubuntu-4        | Exited (0) 292 years ago | docker.io/library/ubuntu:latest
d63f829b6ea6 | Libation-dowload-books | Exited (0) 292 years ago | docker.io/library/debian:latest

**Steps how to reproduce the behaviour**

I do not know how to reprouguse 

1. I enterd in to  cozy-ubuntu-4 
2. I was running/ran  
      meson setup --prefix=$(pwd)/app ./build 
      ninja -C build install
     and some pyton stuff 
3. I ran steam-runtime in that the game liftoff crashed so I held down the power botten and rebooted 
4. I went back to what i was doing ran distrobox-list to coppy name to run distrobox-enter cozy-ubuntu-4 and notised the time errors

**Expected behaviour**
Describe the bug: After performing a forced reboot of my system, I ran the distrobox-list command and noticed that several containers are showing incorrect timestamps. Specifically, multiple containers show "Exited (0) 292 years ago," which is clearly not accurate.

**Example output:**

bash

(base) [fred@fred-arch-i3 cozy]$ distrobox-list
ID           | NAME                  | STATUS                  | IMAGE
4941abaa58d5 | distrobox-audible      | Exited (0) 46 hours ago | docker.io/library/debian:latest
c922fd57e94f | cozy-distroBox         | Exited (143) 4 hours ago | docker.io/library/debian:latest
85701d6fb512 | cozy-ubuntu            | Exited (0) 292 years ago | docker.io/library/ubuntu:latest
efb63182f382 | cozy-ubuntu-2          | Exited (0) 292 years ago | docker.io/library/ubuntu:20.04
f601928ff338 | cozy-deb               | Exited (0) 292 years ago | registry.fedoraproject.org/fedora-toolbox:39
429f861e7346 | cozy-ubuntu-4          | Exited (0) 292 years ago | docker.io/library/ubuntu:latest
d63f829b6ea6 | Libation-dowload-books | Exited (0) 292 years ago | docker.io/library/debian:latest

**Steps to Reproduce:** I am not sure how to reproduce this consistently, but here are the steps leading up to the issue:

1. Entered cozy-ubuntu-4 container.
2. Ran the following commands inside the container:
3. meson setup --prefix=$(pwd)/app ./build
4. ninja -C build install
5. Some Python do not rember commands.
6. Opened the Steam runtime to play a game (Liftoff), which crashed.
7. Performed a force reboot by holding down the power button.
8. Upon restarting, I ran distrobox-list and observed the incorrect timestamps.

**Expected Behavior:** Timestamps for the containers should reflect accurate times, such as when they exited, instead of showing "292 years ago."

**Actual Behavior:** Multiple containers show "Exited (0) 292 years ago," which is clearly incorrect.

I do not know defaluls from arch aur it says no installed

Client Details:
    API Version: 5.2.3
    Go Version: go1.23.1
    OS/Arch: linux/amd64

Client:       Podman Engine
Version:      5.2.3
API Version:  5.2.3
Go Version:   go1.23.1
Git Commit:   c5366a308e89edd9636b66faf79bd5cb18ed0905
Built:        Sun Sep 29 02:25:47 2024
OS/Arch:      linux/amd64
desktop environment: i3 
distrobox version: 1.7.2.1

Additional Context:

    No changes to system defaults from Arch AUR.
    Podman and Distrobox installed through Arch repositories.
    Force reboot might have caused the issue.

**Comment by 89luca89** [comment]
This is not distrobox, but podman issue
