### ISSUE TITLE
[Error] zsh completion scripts are installed to the wrong folder on Ubuntu

### ISSUE THREAD

**Issue by davidshen84** [89luca89/distrobox#1580]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**

The zsh completion scripts are installed into the `/usr/share/zsh/site-functions` folder on Ubuntu.
```
> dpkg-query -L distrobox | grep zsh
/usr/share/zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/_distrobox
/usr/share/zsh/site-functions/_distrobox-assemble
/usr/share/zsh/site-functions/_distrobox-create
/usr/share/zsh/site-functions/_distrobox-enter
/usr/share/zsh/site-functions/_distrobox-ephemeral
/usr/share/zsh/site-functions/_distrobox-export
/usr/share/zsh/site-functions/_distrobox-generate-entry
/usr/share/zsh/site-functions/_distrobox-host-exec
/usr/share/zsh/site-functions/_distrobox-init
/usr/share/zsh/site-functions/_distrobox-list
/usr/share/zsh/site-functions/_distrobox-rm
/usr/share/zsh/site-functions/_distrobox-stop
/usr/share/zsh/site-functions/_distrobox-upgrade
```

However, `/usr/share/zsh/site-functions` is **not** the in the default `fpath` list on Ubuntu. You can use `zsh -fc 'print -rl $fpath'` to verify it on Ubuntu and compare it with other distros.

**To Reproduce**
- Insta `distrobox/noble,now 1.7.0-1` on Ubuntu
- Open a new terminal and type `distrobox <tab>`

**Expected behavior**
Completion prompts popup with other distrobox sub-commands.

**Additional context**
On Ubuntu vendor scripts are supposed to be installed into these folders:

```
/usr/share/zsh/vendor-functions
/usr/share/zsh/vendor-completions
```

**Comment by 89luca89** [comment]
This is a debian package issue, which is not officially done by me, please open the bug to them

**Comment by davidshen84** [comment]
It looks like there's no Debian package for the distrobox. I only found an Ubuntu one and filed a bug.

https://bugs.launchpad.net/ubuntu/+source/distrobox/+bug/2084366
