### ISSUE TITLE
[Error] DPkg::Pre-Invoke 'umount /var/log/journal' error on Ubuntu & Debian images

### ISSUE THREAD

**Issue by edserhub** [89luca89/distrobox#159]
**Describe the bug**
A previous fix https://github.com/89luca89/distrobox/issues/123 seems to have introduced a problem with other DEB based distributions. Installing packages or applying updates fails with an error:

```
umount: /var/log/journal: no mount point specified.
E: Problem executing scripts DPkg::Pre-Invoke 'umount /var/log/journal'
E: Sub-process returned an error code
```

Removing `/etc/apt/apt.conf.d/00_distrobox` stops the error from occurring.

**To Reproduce**

- Create and enter an Ubuntu 20.04 distrobox
- Perform a `sudo apt update; sudo apt install -y sshpass`

**Expected behavior**
The package installation proceeds without error.

**Logs**
[apt.log](https://github.com/89luca89/distrobox/files/8002045/apt.log)
[distrobox-enter.log](https://github.com/89luca89/distrobox/files/8002061/distrobox-enter.log)
[docker.log](https://github.com/89luca89/distrobox/files/8002021/docker.log)

**Desktop (please complete the following information):**
 - OS: CentOS
 - Version 7

**Additional context**
Using the latest version: `distrobox: 1.2.12`

**Comment by 89luca89** [comment]
Hi @edserhub 
seems like it is because `/var/log/journal` was not mounted during the container setup
can you post a log of

`docker logs ubuntu`

To check why it was not mounted? 

(or simply check on your host if `/var/log/journal` exists in the first place :smile: )

A fix is incoming for it :+1:

**Comment by edserhub** [comment]
Hi @89luca89 

Thanks for the response!

Ahh `/var/log/journal` does _not_ exist on the host. It's a fairly standard CentOS 7 installation. At least, there's nothing that's been customised around systemd / journald.

[ubuntu-docker.log](https://github.com/89luca89/distrobox/files/8002510/ubuntu-docker.log)

**Comment by 89luca89** [comment]
Perfect that's what I was expecting :smile: 

Pushed right now a fix in: https://github.com/89luca89/distrobox/commit/77d6a6520d89c4bd8f9751a708955f38339a53d7

Should work now, you can expect the fix to be part of the next release :+1:

**Comment by edserhub** [comment]
Amazing! 🙌🏻 I can confirm that https://github.com/89luca89/distrobox/commit/77d6a6520d89c4bd8f9751a708955f38339a53d7 solves the issue for me. Thank you! 😊

**Comment by 89luca89** [comment]
Glad it's fixed, thanks for the report!
