### ISSUE TITLE
[Discussion] Bump default container image to Fedora 40?

### ISSUE THREAD

**Issue by osalbahr** [89luca89/distrobox#1593]
Is your feature request related to a problem? Please describe.

`distrobox enter` defaults to 39 (n-1) release of Fedora. This is fine until Fedora 41 drops. I would like to discuss when bumping happens. I am on `OS: Fedora Linux Asahi Remix 40 (Workstation Edition) aarch64`.

Describe the solution you'd like

Bump the default image to latest Fedora.

Describe alternatives you've considered

Manually use latest fedora-toolbox image.

Additional context

```console
$ distrobox ls
ID           | NAME                 | STATUS             | IMAGE                         
404e49c72620 | my-distrobox         | Up 3 minutes       | registry.fedoraproject.org/fedora-toolbox:39
```

- https://github.com/89luca89/distrobox/pull/1134

**Comment by alcir** [comment]
Which version of distrobox are you using?

**Comment by osalbahr** [comment]
> Which version of distrobox are you using?

It appears that the issue is already resolved. Thx for the sanity check.

```console
$ ~/Development/homebrew/bin/distrobox enter
Error: no such container my-distrobox
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:latest? [Y/n]: n
Ok. For creating it, run this command:
	distrobox create <name-of-container> --image <remote>/<docker>:<tag>
$ /usr/bin/distrobox enter
Error: no such container my-distrobox
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]: n
Ok. For creating it, run this command:
	distrobox create <name-of-container> --image <remote>/<docker>:<tag>
$ ~/Development/homebrew/bin/distrobox --version
distrobox: 1.8.0
$ /usr/bin/distrobox --version
distrobox: 1.7.2.1
```
