### ISSUE TITLE
[Error] setup_pkg_manager_hooks() does not create /etc/distrobox-post-hook.sh

### ISSUE THREAD

**Issue by Labaman** [89luca89/distrobox#1595]
**Describe the bug**
 distrobox-init does not create /etc/distrobox-post-hook.sh in arch-based  containers (maybe not only in arch-based containers).

**To Reproduce**
1. Create any distrobox container based on arch image
2. Enter the created container
3. Install any package (e.g. mc)
![distrobox_hook_bug](https://github.com/user-attachments/assets/e15e4623-eb02-4e95-b4a0-0c66bfd0b621)

**Expected behavior**
Correct execution of all hooks
All executable files exist

**Logs**
[arch_podman_logs.txt](https://github.com/user-attachments/files/17542214/arch_podman_logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 podman

 - Which version or podman, docker or lilipod?
Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.22.0
Git Commit:   8d2b55ddde1bc81f43d018dfc1ac027c06b26a7f-dirty
Built:        Tue Mar 26 01:02:37 2024
OS/Arch:      linux/amd64

 - Which version of distrobox?
 1.8.0

 - Which host distribution?
 SteamOS 3.6.2

 - How did you install distrobox?
sudo steamos-readonly disable
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh -s -- --prefix /usr
sudo steamos-readonly enable

**Comment by MakaiHanta** [comment]
Why did you close the ticket if the problem is not solved?
