### ISSUE TITLE
Can't enter containers after rebooting the host

### ISSUE THREAD

**Issue by alxlg** [89luca89/distrobox#16]
Hi, I can create new containers and enter them just one time.

When I try to enter a container for a second time with

```bash
distrobox-enter --name fedora-35 -- bash -l  

Error: unable to start container "fedora-35": container create failed (no logs from conmon): EOF

Cannot start container, does it exist?
Try running first:

    distrobox-create --name <name-of-container> --image <remote>/<docker>:<tag>
An error occurred
```

despite I have a container with that name:

```bash
podman ps -a
CONTAINER ID  IMAGE                                 COMMAND               CREATED       STATUS                   PORTS  NAMES
92bef478ff04  registry.fedoraproject.org/fedora:35  /usr/bin/entrypoi...  15 hours ago  Created                         fedora-35-2
e276c55031e7  registry.fedoraproject.org/fedora:35  /usr/bin/entrypoi...  19 hours ago  Exited (6) 19 hours ago         fedora-35
```

EDIT: what's trigger this is the reboot of the host, I can create new containers and enter them as far as I don't reboot the host. After the reboot all the previous containers can't be entered despite they are listed by podman ps.

**Comment by 89luca89** [comment]
Hey @alxlg can you post a log with `--verbose`? thanks!

**Comment by 89luca89** [comment]
Also @alxlg can you check your `podman` version?

I saw that there is a bug on `podman` for version prior to 1.6.4 here: https://github.com/containers/podman/issues/4522

**Comment by 89luca89** [comment]
Yea I'm on 20.04 too and was wondering if it was an ancient podman version :smile: 

Ok will add a link to the podman installation site in the requirements
Will mark the issue as resolved
Thanks for the report!

**Comment by 89luca89** [comment]
Added in commit: [dcc5cbe5e796139783de79784c210c8e34c40396](https://github.com/89luca89/distrobox/commit/dcc5cbe5e796139783de79784c210c8e34c40396)
