### ISSUE TITLE
[Error] Pacman "call to execv failed" on a fresh Arch container

### ISSUE THREAD

**Issue by nfp0** [89luca89/distrobox#1602]
**Describe the bug**
On a fresh Arch container (on an Arch host), running something like `sudo pacman -S nano` to install nano outputs the following error:

```
:: Running pre-transaction hooks...
(1/1) Distrobox hook /etc/distrobox-pre-hook.sh...
call to execv failed (No such file or directory)
error: command failed to execute correctly
```

The application installs correctly, but I wonder what that error is.

**To Reproduce**
1) Create an Arch box with something like `distrobox create -n Arch -i archlinux`
2) Run `sudo pacman -S nano` after entering the container
3) Observe the error.

**Desktop**
- I am using Podman version 5.2.5 on Arch Linux.
- Distrobox version 1.8.0 installed through the Arch repos.

**Comment by hexisXz** [comment]
I have this same issue...

**Comment by kv7-coder** [comment]
I have this same issue...

I installed Arch in the following way:

``distrobox create -i archlinux --name arch --hostname archlinux --home /home/$(whoami)/arch --root``

![2024-12-27_21-29](https://github.com/user-attachments/assets/d66870a8-3678-4031-9b45-41b5ddad9a85)

**Comment by JakoDel** [comment]
> I have this same issue...
> 
> I installed Arch in the following way:
> 
> `distrobox create -i archlinux --name arch --hostname archlinux --home /home/$(whoami)/arch --root`
> 
> ![2024-12-27_21-29](https://private-user-images.githubusercontent.com/83992579/399029507-d66870a8-3678-4031-9b45-41b5ddad9a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNzU3NDcsIm5iZiI6MTczNjA3NTQ0NywicGF0aCI6Ii84Mzk5MjU3OS8zOTkwMjk1MDctZDY2ODcwYTgtMzY3OC00MDMxLTliNDUtNDFiNWRkYWQ5YTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDExMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMmRlN2Y4NjEyMjgyZjBlOTVlMWVkNzI2NDJhZTI2MWYyN2I2MGQ0NzMxNzY0NTkzZTYzYjJkYmM5YmQ0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.frHjHKM7felRhDwWEmfXAT3siRN0pc9PXofMNX5ihHk)

Me too but it's normal since the script installs only v1.8.0 from October. I guess I should've used the script that installed from the master branch
