### ISSUE TITLE
Apt Issues 

### ISSUE THREAD

**Issue by FedX-sudo** [89luca89/distrobox#161]
I have noticed a couple bugs with Apt inside a distrobox. First, by default there is no `_apt` user by default which breaks apt, but this can be fixed by running `sudo useradd -r -M --system _apt` inside the container. The second is far more difficult to fix, if it can be fixed at all. Apt/DPKG expects to own DBus, but inside a distrobox, it does not, so whenever I try to install anything that requires a graphics stack, the install just breaks. I don't see how that could be fixed without moving dbus inside the container, in which case (if I understand the stack correctly) it would allow for graphical apps to be installed, but would not be able to open a window because DBus is  sandboxed away from the container. Any thoughts?

**Comment by 89luca89** [comment]
Hey @FedX-sudo 
I'm trying right now on an ubuntu image and the `_apt` user is present by default, and installing a graphical application (`gnumeric` to test something small and quick) worked as expected

![image](https://user-images.githubusercontent.com/598882/152658465-223bf880-f533-4516-bc54-b5169b24bdc9.png)


Can you give some more information on how is your setup so I can try to reproduce?

**Comment by FedX-sudo** [comment]
Well this is interesting... It appears to be an incompatibility with Sway... I am not sure about other Wayland compositors, but apparently the way Sway sandboxes graphical applications bricks apt inside distrobox.

**Comment by 89luca89** [comment]
> Well this is interesting... It appears to be an incompatibility with Sway... I am not sure about other Wayland compositors, but apparently the way Sway sandboxes graphical applications bricks apt inside distrobox.

Interesting
Can you give some Info on the setup? I'll try to reproduce it

**Comment by FedX-sudo** [comment]
Specifically I was seeing the issue on NixOS 22.05 running Sway 1.6 with Zen Kernel 5.15 (yeah I need to update) I hopped over to Plasma 5.23 X11 on the same system after reboot and now Gnumeric is installing just fine inside a Ubuntu 22.04 container. I can't open a gnumeric window, but I assume that's more X11 than anything.

**Comment by FedX-sudo** [comment]
Wait, it seems to be working now. Maybe an update off the master branch and a reboot was all it needed? I will add more to this thread if anything else arises, but I think it's good?

**Comment by 89luca89** [comment]
> Specifically I was seeing the issue on NixOS 22.05 running Sway 1.6 with Zen Kernel 5.15 (yeah I need to update) I hopped over to Plasma 5.23 X11 on the same system after reboot and now Gnumeric is installing just fine inside a Ubuntu 22.04 container. I can't open a gnumeric window, but that is a different issue, as the same thing is happening in Arch.

The second issue has probably something to do with xhost permission could it be?
`xhost +si:localuser:$USER`

About the sway problem, I'll try something with sway tomorrow, I know for sure it works on gnome Wayland as it's what I use daily

**Comment by 89luca89** [comment]
> Wait, it seems to be working now. Maybe an update off the main branch and a reboot was all it needed? I will add more to this thread if anything else arises, but I think it's good?

Cool, worth doing a test tomorrow anyway, but if it works that's good :smile:

**Comment by FedX-sudo** [comment]
Yeah, the second issue was solved by hopping back onto Wayland, so I *think* everything is good now... Thank you for the help, and it's interesting to think the Wayland compositor could effect the container distros.

**Comment by 89luca89** [comment]
Yes seems strange, especially the missing _apt user, I'm not sure the compositor was at fault here
