### ISSUE TITLE
Distrobox failed  to install basic packages after making an archlinux container

### ISSUE THREAD

**Issue by vaynefox** [89luca89/distrobox#1610]
**Describe the bug**
After creating a new archlinux container and entering the container, it just fails to install basic packages

**To Reproduce**
1. Run `distrobox create --name Music1 --image archlinux --home ChimeraX`
2. After container has been created I run `distrobox enter Music1`
3. installing packages borked out

**Expected behavior**
I expected it to install all packages and finally start messing around some arch packages

**Logs**

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 words-2.1-8-any downloading...
 time-1.9-5-x86_64 downloading...
checking keyring...
checking package integrity...
error: time: signature from "Caleb Maclennan <alerque@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/time-1.9-5-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: words: signature from "Caleb Maclennan <alerque@archlinux.org>" is unknown trust

:: File /var/cache/pacman/pkg/words-2.1-8-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)

Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
 [37mDEBU[0m[0000] Called logs.PersistentPostRunE(podman --log-level debug logs Music1) 
 [37mDEBU [0m[0000] Shutting down engines                        
 [36mINFO [0m[0000] Received shutdown.Stop(), terminating!        [36mPID [0m=26697

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 5.2.5
 - Which version of distrobox? distrobox: 1.7.1.0
 - Which host distribution? Fedora 41
 - How did you install distrobox? Native via DNF

**Additional context**
Seems to be a problem with PGP keys.

**Comment by Pyro57000** [comment]
Pull a new arch image in your creat command with the -p flag
`distrobox create --name Music1 --image archlinux --home ChimeraX -p`
