### ISSUE TITLE
[Error] "./distrobox-export" includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by richard-hajek** [89luca89/distrobox#163]
**Describe the bug**
distrobox fails to create default container on Arch Linux

**To Reproduce**
1. Have Arch Linux
2. run ./distrobox-create

**Expected behavior**
Creation of container

**Logs**
[--verbose](https://github.com/89luca89/distrobox/files/8011613/log.txt)
[docker_version.txt](https://github.com/89luca89/distrobox/files/8011620/docker_version.txt)

**Desktop (please complete the following information):**
 - OS: Arch Linux: current newest
 - Version: current newest

**Comment by deinferno** [comment]
Try running this https://github.com/89luca89/distrobox/pull/160 pull request or use release version of Distrobox

**Comment by richard-hajek** [comment]
Using a release version works!

**Comment by 89luca89** [comment]
Hi @richard-hajek 
Yea this seems related to PR #160 and will be fixed with that :+1:
