### ISSUE TITLE
[Suggestion] Move/add version flag or argument at the top level

### ISSUE THREAD

**Issue by lentzi90** [89luca89/distrobox#164]
**Is your feature request related to a problem? Please describe.**
I expected to be able to get the version with `distrobox version` or `distrobox --version` but this does not work.
Instead I have to do `distrobox create --version`.

**Describe the solution you'd like**
I want the `--version` flag to work at the top level without any extra command like `create`.

**Comment by 89luca89** [comment]
Yep completely agree on this one :+1: 
Will work on this soon or if anyone wants to PR it is welcomed 😄

**Comment by 89luca89** [comment]
Thanks to @misobarisic for implementing this :+1:
