### ISSUE TITLE
[Suggestion] Change install/uninstall script based on whether running with sudo privileges or not

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#166]
The install script defaults to `/usr/local/bin`. What if it defaulted to `~/.local/bin` if ran with `./install` and `/usr/local/bin` with `sudo ./install`. 

The install script should also give some output when successfully installed instead of the current nothing.

**Comment by 89luca89** [comment]
Agree with this, having the default based on being root or not is useful :+1:
