### ISSUE TITLE
[Error] Problem using distrobox outside of install directory

### ISSUE THREAD

**Issue by s2live** [89luca89/distrobox#169]
**Description of the bug**
After creating a container I run

sudo distrobox-enter fedora-toolbox-35

I'm met with this error message
Error: chdir `/home/user`: No such file or directory: OCI runtime attempted to invoke a command that was not found

/home/user is the working directory the terminal is in, the same happens from any directory besides  the install directory /usr/local/bin 

Also unless I invoke sudo, whatever directory I am in none of the distrobox commands work for me as the files aren't even found not sure if I should have raised a separate issue for that.

Example of what happens when I don't prefix with sudo
Error: error inspecting object: no such container  <container-name>

I tried again with ubuntu this time feedback that the container was running was posted then the error occurred.

Starting container ubuntu
run this command to follow along:
	podman logs -f ubuntu
.
done!
Error: chdir `/home/user`: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred

**To Reproduce**
For me: trying to enter a container (and likely other commands I haven't tried yet) outside of my install directory  /usr/local/bin/

**Expected behavior**
I expected to be able to use distrobox regardless of the current working directory

**Desktop (please complete the following information):**
 - OS:  Manjaro in kvm/qemu
 - OS Version: Latest
 
**Additional context**
Distrobox Version 1.2.14

**Logs**
sudo distrobox enter --verbose  ubuntu
+ container_manager=podman
+ command -v podman
+ '[' -z '' ']'
++ id -ru
+ '[' -S /run/user/0/podman/podman.sock ']'
+ '[' 1 -ne 0 ']'
+ container_manager='podman --log-level debug'
+ '[' -z ubuntu ']'
+ '[' 0 -ne 0 ']'
++ podman --log-level debug inspect --type container ubuntu --format '{{.State.Status}}'
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called inspect.PersistentPreRunE(podman --log-level debug inspect --type container ubuntu --format {{.State.Status}}) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /run/containers/storage       
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is being used 
DEBU[0000] Cached value indicated that native-diff is not being used 
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 7              
DEBU[0000] Error parsing cgroup: expected 3 fields but got 1: /proc/6899/cgroup 
DEBU[0000] Called inspect.PersistentPostRunE(podman --log-level debug inspect --type container ubuntu --format {{.State.Status}}) 
+ container_status=running
+ container_exists=0
+ '[' 0 -gt 0 ']'
+ '[' running '!=' running ']'
++ generate_command
++ result_command='podman --log-level debug exec'
++ result_command='podman --log-level debug exec
		--user=root'
++ '[' 0 -eq 0 ']'
++ result_command='podman --log-level debug exec
		--user=root
		--interactive
		--tty'
++ result_command='podman --log-level debug exec
		--user=root
		--interactive
		--tty
		--workdir=/home/user
		--env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter'
++ set +o xtrace
++ result_command='podman --log-level debug exec
		--user=root
		--interactive
		--tty
		--workdir=/home/user
		--env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env="COLORTERM=truecolor" --env="SUDO_GID=1000" --env="LC_ADDRESS=en_GB.UTF-8" --env="LC_NAME=en_GB.UTF-8" --env="LC_MONETARY=en_GB.UTF-8" --env="SUDO_USER=user" --env="PWD=/home/user" --env="LOGNAME=root" --env="XAUTHORITY=/home/user/.Xauthority" --env="LC_PAPER=en_GB.UTF-8" --env="LANG=en_GB.utf8" --env="LS_COLORS=[...]:" --env="LC_IDENTIFICATION=en_GB.UTF-8" --env="TERM=xterm-256color" --env="DISPLAY=:0.0" --env="SHLVL=1" --env="LC_TELEPHONE=en_GB.UTF-8" --env="LC_MEASUREMENT=en_GB.UTF-8" --env="LC_TIME=en_GB.UTF-8" --env="SUDO_UID=1000" --env="MAIL=/var/mail/root" --env="LC_NUMERIC=en_GB.UTF-8" --env="PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin" --env="XDG_DATA_DIRS=" --env="XDG_CONFIG_DIRS=" '
++ result_command='podman --log-level debug exec
		--user=root
		--interactive
		--tty
		--workdir=/home/user
		--env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env="COLORTERM=truecolor" --env="SUDO_GID=1000" --env="LC_ADDRESS=en_GB.UTF-8" --env="LC_NAME=en_GB.UTF-8" --env="LC_MONETARY=en_GB.UTF-8" --env="SUDO_USER=user" --env="PWD=/home/user" --env="LOGNAME=root" --env="XAUTHORITY=/home/user/.Xauthority" --env="LC_PAPER=en_GB.UTF-8" --env="LANG=en_GB.utf8" --env="LS_COLORS=[...]" --env="LC_IDENTIFICATION=en_GB.UTF-8" --env="TERM=xterm-256color" --env="DISPLAY=:0.0" --env="SHLVL=1" --env="LC_TELEPHONE=en_GB.UTF-8" --env="LC_MEASUREMENT=en_GB.UTF-8" --env="LC_TIME=en_GB.UTF-8" --env="SUDO_UID=1000" --env="MAIL=/var/mail/root" --env="LC_NUMERIC=en_GB.UTF-8" --env="PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin" --env="XDG_DATA_DIRS=" --env="XDG_CONFIG_DIRS="  ubuntu bash -l'
++ printf %s 'podman --log-level debug exec
		--user=root
		--interactive
		--tty
		--workdir=/home/user
		--env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env="COLORTERM=truecolor" --env="SUDO_GID=1000" --env="LC_ADDRESS=en_GB.UTF-8" --env="LC_NAME=en_GB.UTF-8" --env="LC_MONETARY=en_GB.UTF-8" --env="SUDO_USER=user" --env="PWD=/home/user" --env="LOGNAME=root" --env="XAUTHORITY=/home/user/.Xauthority" --env="LC_PAPER=en_GB.UTF-8" --env="LANG=en_GB.utf8" --env="LS_COLORS=[...]:" --env="LC_IDENTIFICATION=en_GB.UTF-8" --env="TERM=xterm-256color" --env="DISPLAY=:0.0" --env="SHLVL=1" --env="LC_TELEPHONE=en_GB.UTF-8" --env="LC_MEASUREMENT=en_GB.UTF-8" --env="LC_TIME=en_GB.UTF-8" --env="SUDO_UID=1000" --env="MAIL=/var/mail/root" --env="LC_NUMERIC=en_GB.UTF-8" --env="PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin" --env="XDG_DATA_DIRS=" --env="XDG_CONFIG_DIRS="  ubuntu bash -l'
+ cmd='podman --log-level debug exec
		--user=root
		--interactive
		--tty
		--workdir=/home/user
		--env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env="COLORTERM=truecolor" --env="SUDO_GID=1000" --env="LC_ADDRESS=en_GB.UTF-8" --env="LC_NAME=en_GB.UTF-8" --env="LC_MONETARY=en_GB.UTF-8" --env="SUDO_USER=user" --env="PWD=/home/user" --env="LOGNAME=root" --env="XAUTHORITY=/home/user/.Xauthority" --env="LC_PAPER=en_GB.UTF-8" --env="LANG=en_GB.utf8" --env="LS_COLORS=[...]" --env="LC_IDENTIFICATION=en_GB.UTF-8" --env="TERM=xterm-256color" --env="DISPLAY=:0.0" --env="SHLVL=1" --env="LC_TELEPHONE=en_GB.UTF-8" --env="LC_MEASUREMENT=en_GB.UTF-8" --env="LC_TIME=en_GB.UTF-8" --env="SUDO_UID=1000" --env="MAIL=/var/mail/root" --env="LC_NUMERIC=en_GB.UTF-8" --env="PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin" --env="XDG_DATA_DIRS=" --env="XDG_CONFIG_DIRS="  ubuntu bash -l'
+ eval podman --log-level debug exec --user=root --interactive --tty --workdir=/home/user --env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter '--env="COLORTERM=truecolor"' '--env="SUDO_GID=1000"' '--env="LC_ADDRESS=en_GB.UTF-8"' '--env="LC_NAME=en_GB.UTF-8"' '--env="LC_MONETARY=en_GB.UTF-8"' '--env="SUDO_USER=user"' '--env="PWD=/home/user"' '--env="LOGNAME=root"' '--env="XAUTHORITY=/home/user/.Xauthority"' '--env="LC_PAPER=en_GB.UTF-8"' '--env="LANG=en_GB.utf8"' '--env="LS_COLORS=[...]"' '--env="LC_IDENTIFICATION=en_GB.UTF-8"' '--env="TERM=xterm-256color"' '--env="DISPLAY=:0.0"' '--env="SHLVL=1"' '--env="LC_TELEPHONE=en_GB.UTF-8"' '--env="LC_MEASUREMENT=en_GB.UTF-8"' '--env="LC_TIME=en_GB.UTF-8"' '--env="SUDO_UID=1000"' '--env="MAIL=/var/mail/root"' '--env="LC_NUMERIC=en_GB.UTF-8"' '--env="PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin"' '--env="XDG_DATA_DIRS="' '--env="XDG_CONFIG_DIRS="' ubuntu bash -l
++ podman --log-level debug exec --user=root --interactive --tty --workdir=/home/user --env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env=COLORTERM=truecolor --env=SUDO_GID=1000 --env=LC_ADDRESS=en_GB.UTF-8 --env=LC_NAME=en_GB.UTF-8 --env=LC_MONETARY=en_GB.UTF-8 --env=SUDO_USER=user --env=PWD=/home/user --env=LOGNAME=root --env=XAUTHORITY=/home/user/.Xauthority --env=LC_PAPER=en_GB.UTF-8 --env=LANG=en_GB.utf8 '--env=LS_COLORS=[...]:' --env=LC_IDENTIFICATION=en_GB.UTF-8 --env=TERM=xterm-256color --env=DISPLAY=:0.0 --env=SHLVL=1 --env=LC_TELEPHONE=en_GB.UTF-8 --env=LC_MEASUREMENT=en_GB.UTF-8 --env=LC_TIME=en_GB.UTF-8 --env=SUDO_UID=1000 --env=MAIL=/var/mail/root --env=LC_NUMERIC=en_GB.UTF-8 --env=PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin --env=XDG_DATA_DIRS= --env=XDG_CONFIG_DIRS= ubuntu bash -l
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called exec.PersistentPreRunE(podman --log-level debug exec --user=root --interactive --tty --workdir=/home/user --env=DISTROBOX_ENTER_PATH=/usr/local/bin/distrobox-enter --env=COLORTERM=truecolor --env=SUDO_GID=1000 --env=LC_ADDRESS=en_GB.UTF-8 --env=LC_NAME=en_GB.UTF-8 --env=LC_MONETARY=en_GB.UTF-8 --env=SUDO_USER=user --env=PWD=/home/user --env=LOGNAME=root --env=XAUTHORITY=/home/user/.Xauthority --env=LC_PAPER=en_GB.UTF-8 --env=LANG=en_GB.utf8 --env=LS_COLOR##[...]
env=SUDO_UID=1000 --env=MAIL=/var/mail/root --env=LC_NUMERIC=en_GB.UTF-8 --env=PATH=/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin --env=XDG_DATA_DIRS= --env=XDG_CONFIG_DIRS= ubuntu bash -l) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /run/containers/storage       
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is being used 
DEBU[0000] Cached value indicated that native-diff is not being used 
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 7              
DEBU[0000] Handling terminal attach                     
INFO[0000] Created exec session f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 in container f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82 
DEBU[0000] Sending resize events to exec session f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 
INFO[0000] Going to start container f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82 exec session f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 and attach to it 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82 -u f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 -r /usr/bin/crun -b /var/lib/containers/storage/overlay-containers/f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82/userdata/f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 -p /var/lib/containers/storage/overlay-containers/f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82/userdata/f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01/exec_pid -n ubuntu --exit-dir /var/lib/containers/storage/overlay-containers/f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82/userdata/f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01/exit --full-attach -s -l none --log-level debug --syslog -t -i -e --exec-attach --exec-process-spec /var/lib/containers/storage/overlay-containers/f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82/userdata/f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01/exec-process-4146343521 --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /run/containers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --exec --exit-command-arg f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 --exit-command-arg f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82]"
INFO[0000] Running conmon under slice machine.slice and unitName libpod-conmon-f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82.scope 
DEBU[0000] Attaching to container f1a6e41fe06e59248610343700ca9b1f9d991c28ec9ceafcce937b4ca78c0c82 exec session f59180556c6452dfba7dcca778d12acea015b4ffa44273f53eac81c4147d1e01 
DEBU[0000] Received: 0                                  
DEBU[0000] Received: -1                                 
Error: OCI runtime error: [conmon:d]: exec with attach is waiting for start message from parent
[conmon:d]: exec with attach got start message from parent
+ '[' 255 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred

Maybe a bit too verbose but better than too little!

**Comment by 89luca89** [comment]
Hi @s2live you're not supposed to use `sudo distrobox`
As stated in the readme, it either works with rootless podman or with sudoless docker (adding yourself to docker group)

If you run with `sudo` it will integrate the $HOME of the root, instead of your user, so it won't find `/home/user` 

Try running without sudo and let me know if you still have problems :+1:

**Comment by s2live** [comment]
Thank you so much Luca! I set podman up to run rootless and it works great, running GUI apps with toolbox nicely. Awesome, this is a really great project. I read the readme more carefully while researching but skipped straight to installation today. Oops.

BTW the reason I am running distrobox is as I'm prototyping a FOSS GUI application that will allow users to install and run non-native Linux applications. It will manage containers via the OCI, the scope is limited to the essential commands and settings the target audience Linux-casuals not power-users.  I believe the best way to meet those goals is to rely greatly on distrobox as a dependency.

**Comment by 89luca89** [comment]
> BTW the reason I am running distrobox is as I'm prototyping a FOSS GUI application that's purpose is allowing users to install and run non-native Linux applications. It will manage containers via the OCI, the scope is limited to the essential commands and settings the target audience Linux-casuals not power-users. I believe the best way to meet those goals is to rely greatly on distrobox as a dependency, so thanks again for making this.

That is super col 😄 looking forward to know more about this!

**Comment by s2live** [comment]
Hmm well it's in the early stages so far, but I think I _may_ have struck upon means to achieve what I desire. What complicates it is that ideally users would be able to use GUI software centres. The best way to go about this seems to be to use packagekit as it's cross platform, and has good support for RPM and dpkg packages as well arch compatible manjaro pamac packages, so it covers all bases.

gnome-software uses packagekit and runs on all the distros I've tried it on, though I have had some issues, 1) Nothing but installed packages show up as the app fails to connect to any repository. 2) When gnome-software is install on both the host and the guest image there are no issues connecting but the installation being integrated with the host causes confusion and a repository targeting the host distro is used. I suspect it's mostly related to appstream if not libpackagekit. I'm not sure if the best way to go about this is to alter the environment, fork gnome-software and make some changes. Or build a bespoke gui based on packagekit.
