### ISSUE TITLE
[Error] Error parsing env vars picks invalid entries

### ISSUE THREAD

**Issue by ryleu** [89luca89/distrobox#17]
Here's what happened:

![image](https://user-images.githubusercontent.com/69326171/144907264-6b960880-cc05-45d1-ae26-3cfe27e69625.png)

Text for copy / pasting purposes:
```
ryleu@riley-fedora ~ [1]> podman pull docker.io/library/ubuntu:20.04
Trying to pull docker.io/library/ubuntu:20.04...
Getting image source signatures
Copying blob 7b1a6ab2e44d done  
Copying config ba6acccedd done  
Writing manifest to image destination
Storing signatures
ba6acccedd2923aee4c2acc6a23780b14ed4b8a5fa4e14e252a23b846df9b6c1
ryleu@riley-fedora ~> distrobox-create --image docker.io/library/ubuntu:20.04 --name ubuntu-20-04
4ca39d806adbdb662c895e26d5bf05ea19d64510eba997e067b4a44247eef936
ryleu@riley-fedora ~> distrobox-enter --name ubuntu-20-04 -- bash -l
Starting container
run this command to follow along:
	podman logs -f ubuntu-20-04
.....done!
Error: error parsing environment variables: name "declare -f" has white spaces, poorly formatted name
An error occurred
ryleu@riley-fedora ~ [125]>
```

I'm not sure why this happened. It *could* be because of SSH, but that seems unlikely. I'll test it without SSH once I get the chance.

System info:

 - OS: Fedora 35
 - Shell: Fish (over SSH)
 - DistroBox version: latest (installed this morning from git)

**Comment by ryleu** [comment]
It could be that Fedora has some weird env vars that Ubuntu doesn't support?

**Comment by ryleu** [comment]
[dbresult.txt](https://github.com/89luca89/distrobox/files/7663029/dbresult.txt)

Okay, here's the verbose output. The formatting is a bit weird, but it has all of the info. One issue I can see right off the bat is that it's also moving env vars like these:

```
++ echo '--env="SSH_CONNECTION=10.25.25.52"'
++ echo '--env="SSH_CLIENT=10.25.25.52"'
++ echo '--env="SSH_TTY=/dev/pts/0"'
```

Maybe some sort of env var whitelist would make sense? This could be an unrelated issue though.

**Comment by ryleu** [comment]
It seems like it's detecting an env var named `declare -f`. I ran `echo $declare\ -f` and got nothing. I would recommend running `cat dbresult.txt | grep 'declare -f` to highlight where it shows up.

**Comment by 89luca89** [comment]
Mhh i see in the logs it picked up these envs

```
++ for i in $(printenv)
++ echo '--env="SSH_CONNECTION=10.25.25.52"'
++ for i in $(printenv)
++ echo '--env="56492"'
++ for i in $(printenv)
++ echo '--env="10.25.25.76"'
++ for i in $(printenv)
++ echo '--env="22"'
++ for i in $(printenv)
```

Which are invallid (not in NAME=VALUE format)

I'll check a better solution to pass the entire env to the container

**Comment by 89luca89** [comment]
@ryleu  I've worked a version that does not try to parse the env but just uses a temp file and the `--env-file` flag instead of multiple single `--env` flags

it is in the `fix_env_passing` branch and it's this file:

https://raw.githubusercontent.com/89luca89/distrobox/fix_env_passing/distrobox-enter

Can you try with this file? If it does work I'll open a new PR to address this issue

**Comment by 89luca89** [comment]
@ryleu seems to be a regression I've introduced in commit: [enter: simplify env passing](https://github.com/89luca89/distrobox/commit/7b2585d39018a01295c60d74350b37479f864273)

I've reverted the commit and added an additional filter to remove lines containing spaces (which are the problem for env)

I've tested again on fedora 35 and it was giving me the same error, with this version is working as intended.
Culprit was this env variable which is oddly formatted:

```
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}
```

**Comment by ryleu** [comment]
I'll give it a try once I get home.

**Comment by ryleu** [comment]
Now it seems to be unable to connect to networking. Everything is working perfectly on the host system...

```
/usr/bin/mount
/usr/bin/passwd
/usr/bin/apt-get
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

An error occurred
```

**Comment by ryleu** [comment]
Oh yeah, it also uses apt-utils instead of apt for whatever reason.

Unrelated: do you have a Discord or something to make communication faster?

**Comment by ryleu** [comment]
![image](https://user-images.githubusercontent.com/69326171/144977950-10ecef26-0245-499f-887b-a5d78ee0b5ac.png)
:thinking:

**Comment by 89luca89** [comment]
> ![image](https://user-images.githubusercontent.com/69326171/144977950-10ecef26-0245-499f-887b-a5d78ee0b5ac.png) thinking

Yea probably I need a better "loading" screen :smile: 



> Oh yeah, it also uses apt-utils instead of apt for whatever reason.
> 
> Unrelated: do you have a Discord or something to make communication faster?

No I don't have one yet
`apt-utils` is being installed, not used

> Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
>   Temporary failure resolving 'security.ubuntu.com'
> Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Reading package lists...
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'

This seems a dns resolution failure, I've just tested on Fedora 35 host and ubuntu 20.04 container and it works
Probably you need to recreate the container (`podman rm -f ubuntu-20-04`) or simply stop it and restart it (`podman kill -s 9 ubuntu-20-04` and then redo `distrobox-enter`)

**Comment by ryleu** [comment]
Okay, I'll see if I set up SSH on my phone properly and give it a shot.

**Comment by ryleu** [comment]
Same issue... I'm going to try 21.10.

**Comment by 89luca89** [comment]
If it's still the DNS problem let's open a separate issue for it so it's more clear it's another problem ok?

**Comment by ryleu** [comment]
That's a good idea, give me a sec.

**Comment by 89luca89** [comment]
Marking the env one as solved

**Comment by ryleu** [comment]
Sounds good, I'll let you know if the issue comes back once we get the DNS thing sorted.

**Comment by 89luca89** [comment]
This one should be ok, if the podman command launches at all it means the env issue is resolved :smile:
