### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by meisme-dev** [89luca89/distrobox#170]
**Describe the bug**
When trying to run distrobox-enter, I get an error:
``` 
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: operation not permitted: unknown
```

**To Reproduce**
Create a distrobox and try to enter it on Arch Linux.

**Expected behavior**
The command succeeds.

**Logs**
<details>

```
+ container_manager=podman
+ command -v podman
+ container_manager=docker
+ command -v docker
+ '[' -z docker ']'
+ '[' 1 -ne 0 ']'
+ container_manager='docker --log-level debug'
+ '[' -z ubuntu ']'
+ '[' 0 -ne 0 ']'
++ docker --log-level debug inspect --type container ubuntu --format '{{.State.Status}}'
+ container_status=created
+ container_exists=0
+ '[' 0 -gt 0 ']'
+ '[' created '!=' running ']'
++ date +%FT%T.%N%:z
+ log_timestamp=2022-02-18T19:58:48.753685927-05:00
+ docker --log-level debug start ubuntu
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: operation not permitted: unknown
Error: failed to start containers: ubuntu
+ '[' 1 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
```

</details>

`docker logs ubuntu` returns nothing
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version Kernel 5.16-zen

**Comment by 89luca89** [comment]
Hi @meisme-dev 
how did you set up docker?
From what I see this is `rootless docker` problem like you can see here: https://github.com/opencontainers/runc/issues/1658

To use with docker It is supposed to use the normal docker sock just adding yourself to the docker group
For rootless use better go the podman route

Let me know if this is the case :+1:

**Comment by meisme-dev** [comment]
Thanks! I tried adding myself to the Docker group, and I still get the same error.

**Comment by 89luca89** [comment]
You then need to use the docker daemon socket so 

- follow this guide https://docs.docker.com/engine/security/rootless/ to revert the changes of rootless docker
- follow this guide to set it up correctly for distrobox https://docs.docker.com/engine/install/linux-postinstall/
- be sure you do not have DOCKER_HOST set to /run/user/1000/docker.sock

Or try with podman following the instruction in the compatibility table here: https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#supported-container-managers :+1:

**Comment by 89luca89** [comment]
@meisme-dev any news on this?

**Comment by meisme-dev** [comment]
I was able to get it working with podman, however for some reason GUI apps don't launch.
