### ISSUE TITLE
[Suggestion] Support ssh -X forwarding

### ISSUE THREAD

**Issue by tliron** [89luca89/distrobox#172]
**Describe the solution you'd like**
I'd like to able to `ssh -X` into a machine, run `distrobox-enter`, and be able to run a X11 app.

Currently by default this will not work with distrobox because it changes the hostname (for some good reasons) and this leads to an authentication error due to how `~/.Xauthority` is constructed (I think). The workaround I found is to change the hostname back to the original inside the container, e.g.:
```
sudo hostname mymachine
```
Running X11 apps will then work with forwarding.

I was thinking of mentioning this as a pull request to in [useful tips](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md), but before doing so I want to make sure that 1) there wouldn't be negative side effects to changing the hostname, and 2) well, maybe there's a better way to enable X11 forwarding from distrobox? Maybe it could be made to "just work" out of the box?

**Comment by 89luca89** [comment]
Hi @tliron 

as discussed on #62 the use of hostnames is just a way to make it clear to the user that he is in a container and not on the host.
Setting a custom PS1 (like toolbx and cnest do) is possible, but then if would not be clear for custom prompts for example.

One way around this is to disable the feature itself by creating the distrobox with a custom init-hook

`distrobox create --image image:tag --name you-name --init-hooks "hostname $(uname -n)"`

this way the created distrobox will always share the same, let me know if this fixes it for you! :+1:

**Comment by tliron** [comment]
Understood. In that case you welcome a PR to the "useful tips" page to explain how to enable X11 forwarding with this trick?

**Comment by 89luca89** [comment]
Sure thing :simile:

**Comment by tliron** [comment]
Hm, indirect issue -- the `--init-hooks` does not some to work for me. Here's my command:
```
distrobox-create --name test --image debian:10 --volume /Depot:/Depot:rw --init-hooks "hostname $(uname -n)"
```

**Comment by 89luca89** [comment]
Mmmh i tried right now and it seems to work
The prompt does not thange but
`hostname` returns my host's hostname correctly

**Comment by tliron** [comment]
Hm, to be honest this is not a permanent hostname change. And how you change permanently differs on different Linux (systemd or not). I think I would recommend people running `sudo hostname $(uname -n)` before trying X forwarding. Or give a few options for people to try.

**Comment by 89luca89** [comment]
Also one should try

`distrobox-create --name test --image debian:10 --volume /Depot:/Depot:rw --init-hooks "$(uname -n)" > /etc/hostname`

This should be universal enough

**Comment by tliron** [comment]
1) Wouldn't that change the host's `/etc/hostname` file?
2) Unfortunately, no. In systemd the `/etc/hostname` file is owned by systemd and can be rewritten if you edit it. You're supposed to use `hostnamectl`.

Anyway, I think it should be OK as a tip for people to just use a temporary change for when they want to run it. In may case, I am doing something like this on the remote system:
```
ssh -X myhost distrobox-enter test -- ./xclock.sh
```
And then `xclock.sh` on the host is:
```
#!/bin/sh
sudo hostname myhost
xclock
```

**Comment by 89luca89** [comment]
> Hm, to be honest this is not a permanent hostname change. And how you change permanently differs on different Linux (systemd or not). I think I would recommend people running `sudo hostname $(uname -n)` before trying X forwarding. Or give a few options for people to try.

It's not a permanent change, but it's enforced in the `init` so the container will always report the host's hostname with the command `hostname` regardless of what the prompt will display

If that does still not work, then we can document this using the script like you explain in the last comment :+1:

**Comment by tliron** [comment]
Oh, so init-hooks work whenever I run `distrobox-enter`?

That's confusing to me, because the examples for it show it being used for installing packages, something that I expect would happen when the container _image_ is created.

**Comment by 89luca89** [comment]
no it works whenever you "start" the container, namely the first `distrobox-enter` you launch, if the container is not running, it will be started, and thus the init script (which is the entrypoin) will run

After that the container will remain running, and the `hostname` is set for all the other `distrobox enter` you do afterwards
