### ISSUE TITLE
[Error] Quotes are not preserved in `distrobox-enter`

### ISSUE THREAD

**Issue by pbertera** [89luca89/distrobox#173]
**Describe the bug**
If you need to run a command with full shell env (Eg. referencing the `$HOME` var in a distrobox created with custom home folder)
You must run the command with `distrobox-enter --name sandbox -- bash -l -c "command arg1 arg2"`.

The issue here is that quotes are not preserved and the the command executed is `podman exec [...] sandbox bash -l -c command arg1 arg2`. For that reason `command` never receives the arguments `arg1 arg2`.

**To Reproduce**

1) create a box with custom home:
```
$ mkdir /tmp/home && distrobox-create -i registry.fedoraproject.org/fedora-toolbox:35 --name tmp --home /tmp/home
```
2) echo the `$HOME` variable from the box
```
$ distrobox-enter tmp -- echo '$HOME'
/var/home/pietro
``` 
This is expected because the box environment is not loaded, nor the default entrypoint script is executed

3) echo the `$HOME` variable from the box after loading the environment
```
$ distrobox-enter tmp -- bash -l -c 'echo $HOME'
   <-- an empty line here
```

**Expected behavior**

At point 3) should print `/tmp/home`

**Additional context**
The issue is created by the following assignment in `distrobox-enter` (`$*` do not preserve quotes):
```
        -e | --exec | --)
                shift
                container_command=$*
                break
```

**Possible solutions**
1) use `container_command=${*@Q}` instead of `container_command=$*`, this preserves the quotes but requires Bash 4 or later
2) do some magics parsing the arguments and escaping the quotes

**Comment by 89luca89** [comment]
Hi @pbertera 

thanks for the finding, yes completely agree to find a way to fix the issue
but I'd like to maintain it POSIX compliant so let's find a way around it, will research something :+1:

**Comment by 89luca89** [comment]
Hi @pbertera 
I was playing with this use case, the solution is to simply escape the quotes

`distrobox enter test -- bash -l -c \"echo \\\$HOME\"`

works as expected :+1:

**Comment by pbertera** [comment]
Indeed, but this is not what an user expect I think.
I mean from an UX perspective would be nice to have the same behavior of `podman exec -- command`.

**Comment by 89luca89** [comment]
yea I agree on this, trying to find a way around
sadly it seems the quotes do not hit the argument parsing in the first place

**Comment by 89luca89** [comment]
Actually we just need to add a set of single quotes for it to work:

`distrobox ente test -- bash -l -c ' "echo \$HOME" ' `

The `\$HOME` escape is needed otherwise the command line would evaluate it **before** launching the command and it will result in the host's variable (this is the same if we do a direct podman command)

**Comment by pbertera** [comment]
Hi @89luca89,
indeed the workaround works.
Yep, I think we should document the use-case.

Thanks a lot

**Comment by 89luca89** [comment]
Added example to the docs, thanks!
