### ISSUE TITLE
[Error] wrong home path ends up in /etc/passwd when requesting custom --home during create

### ISSUE THREAD

**Issue by ennec-e** [89luca89/distrobox#175]
**Describe the bug**  
Incorrect user home path ends up in guest's /etc/passwd when using --home option during distrobox-create  
Somehow user entry in /etc/passwd inside guest is using values mentioned in host's /etc/passwd user entry

**To Reproduce**  
```
    distrobox-create --home /tmp/pathq/ --image ubuntu:latest ubuntu-studio.android.q
    distrobox-enter ubuntu-studio.android.q
```
```
    echo ${HOME}
    # this returns correct home (the one assigned with --home)

    cat /etc/passwd | grep $(whoami)
    # this shows something not right (shows host's user home path)
```

**Expected behavior**  
The path passed using --home should be used to populate (and maintain) user's entry in /etc/passwd

**Desktop**  
Host OS: Fedora 34 (x86_64)
Guest OS: Ubuntu 20.04 (docker ubuntu:latest)

**Additional context**  
The discrepancy causes visible issues. 
For example Android Studio uses user home path set in /etc/passwd to create many directories 
(.gradle, .android etc). This ends up polluting the Host's home because of the bug mentioned above.
It is expected that inside the container the home directory provided in create command will be used.

**Comment by 89luca89** [comment]
Thanks @ennec-e for the report
I can confirm this applies when podman/docker already creates the user for us (so it is already present and the check skipped)
