### ISSUE TITLE
[Error] Cannot enter directory having special characters.

### ISSUE THREAD

**Issue by nm004** [89luca89/distrobox#181]
**Describe the bug**
`distrobox-enter --name sandbox` issues an error when inside directory that has special characters, like white space, parentheses, quotes, etc.

**To Reproduce**

White space:
```
mkdir 'white space'
cd 'white space'
distrobox-enter --name sandbox
```

and you get,
```
Error: no container with name or ID "space" found: no such container

An error occurred
```

Parentheses:
```
mkdir '(parentheses)'
cd '(parentheses)'
distrobox-enter --name sandbox
```
and you get,

```
/var/home/n/.local/bin/distrobox-enter: eval: line 351: syntax error near unexpected token `('

An error occurred
```

**Expected behavior**
Entering container with no errors, like `toolbox enter` does.

**Additional context**
This bug caused by the last `eval ${cmd}` line. Escaping `--workdir` argument may solve this issue.

**Comment by 89luca89** [comment]
Fixed by #182
