### ISSUE TITLE
[Error] distrobox-enter fails if the user's shell is not available out-of-the-box in the guest

### ISSUE THREAD

**Issue by michel-slm** [89luca89/distrobox#185]
**Describe the bug**
If the guest container (e.g. CentOS, where many packages are part of EPEL and not the base distro) is entered from a host where the user's shell is set to a package that's not in the default set of repos, the bring-up fails.

This happens even if I intentionally switch to a different shell (e.g. starting bash, then doing `distrobox enter` from bash).

We should consider:
- if `$SHELL` and the shell set in /etc/passwd differs, prefer installing `$SHELL`
- do shell installation in a separate package installation transaction and don't make it block
- consider allowing the user to supply additional commands to be run as part of the bringup /before/ packages are installed (e.g. for centos stream 8, doing a 'dnf install epel-release' would fix this)
 
**To Reproduce**
- create a CentOS container: `distrobox create --image quay.io/centos/centos:stream8 --name c8s`
- install fish on host OS, then `chsh -s /usr/bin/fish`
- make sure you're *not* on Fish (use bash or zsh)
- `distrobox enter c8s`
- 
**Expected behavior**
Bringing up the guest OS should work

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

(note: not doing full logs as this already shows the issue)
```
$ distrobox enter c8s
Starting container c8s
run this command to follow along:
        podman logs -f c8s
......................2022-02-22T09:31:19.091614000-08:00 /usr/bin/find
2022-02-22T09:31:19.091694000-08:00 /usr/bin/mount
2022-02-22T09:31:19.091763000-08:00 /usr/bin/passwd
2022-02-22T09:31:19.092073000-08:00 /usr/bin/dnf
2022-02-22T09:31:32.263787000-08:00 CentOS Stream 8 - AppStream                     1.6 MB/s |  20 MB     00:11
2022-02-22T09:31:37.894413000-08:00 CentOS Stream 8 - BaseOS                        7.5 MB/s |  19 MB     00:02
2022-02-22T09:31:42.579019000-08:00 CentOS Stream 8 - Extras                        9.4 kB/s |  18 kB     00:01
2022-02-22T09:31:44.186852000-08:00 No match for argument: fish
2022-02-22T09:31:44.189684000-08:00 Package findutils-1:4.6.0-20.el8.x86_64 is already installed.
2022-02-22T09:31:44.190396000-08:00 Package ncurses-base-6.1-9.20180224.el8.noarch is already installed.
2022-02-22T09:31:44.190988000-08:00 Package passwd-0.80-3.el8.x86_64 is already installed.
2022-02-22T09:31:44.192017000-08:00 Package shadow-utils-2:4.6-14.el8.x86_64 is already installed.
2022-02-22T09:31:44.192994000-08:00 Package util-linux-2.32.1-28.el8.x86_64 is already installed.
2022-02-22T09:31:44.230861000-08:00 Error: An error occurred

An error occurred
```

```
$ podman logs c8s
+ '[' '!' -f /run/.containerenv ']'
+ '[' -z 1001 ']'
+ '[' -z /home/michel ']'
+ '[' -z michel ']'
+ '[' -z 1001 ']'
++ basename /usr/bin/fish
+ shell_pkg=fish
+ command -v find
/usr/bin/find
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
+ command -v dnf
/usr/bin/dnf
+ dnf install -y fish findutils ncurses-base passwd procps-ng shadow-utils sudo util-linux vte-profile
CentOS Stream 8 - AppStream                     1.6 MB/s |  20 MB     00:11
CentOS Stream 8 - BaseOS                        7.5 MB/s |  19 MB     00:02
CentOS Stream 8 - Extras                        9.4 kB/s |  18 kB     00:01
No match for argument: fish
Package findutils-1:4.6.0-20.el8.x86_64 is already installed.
Package ncurses-base-6.1-9.20180224.el8.noarch is already installed.
Package passwd-0.80-3.el8.x86_64 is already installed.
Package shadow-utils-2:4.6-14.el8.x86_64 is already installed.
Package util-linux-2.32.1-28.el8.x86_64 is already installed.
Error: Unable to find a match: fish
Error: An error occurred
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 35

**Additional context**
I can file a PR with proposed fix #1

**Comment by michel-slm** [comment]
and.. that issue goes away once I have fish installed in the container and re-enter with it. So it seems to happen if the container shell is not what is in the host /etc/passwd - weird.

**Comment by ennec-e** [comment]
@michel-slm  This _seems_ similar to what I was experiencing in #175. In my case it was some weirdness with homedir. The locus of both issues seems to be unexpected values in /etc/passwd.

Can you try applying this PR [#176] and see if you still can't enter. 
[#176 ]: https://github.com/89luca89/distrobox/pull/176

**Comment by ennec-e** [comment]
@89luca89 Yes absolutely. What I was thinking was this part

> This happens even if I intentionally switch to a different shell (e.g. starting bash, then doing `distrobox enter` from bash).

Might be because the container's user shell wasn't being updated on each init before. It get's fixed on first useradd.
The PR would *probably* help partially resolve this as the usermod step would update container shell  to their current host shell (bash) at every init

**Comment by 89luca89** [comment]
@michel-slm hi, I've pushed a new patch in a PR here: https://github.com/89luca89/distrobox/pull/189
I've tested your use case and seems to fix it, can you also confirm?

Thanks!

**Comment by 89luca89** [comment]
@michel-slm I've tested this with various setups and with SHELL set to various values (even non-existing shells) and seems like it fixes the problem, I'm resolving this, if you'll encounter problems with the fix do not hesitate to reopen this issue or open a new one! :+1:
