### ISSUE TITLE
[Error] permission denied: OCI permission denied

### ISSUE THREAD

**Issue by InvisibleRasta** [89luca89/distrobox#187]
**Describe the bug**
Cant enter  containers

**To Reproduce**
**distrobox-create --name arch-distrobox --image docker.io/archlinux:latest**
```
d03e19bcfad2991a9bd4fd5069d8c2148e964f547a1f6c87e01f1c29832448f3
Distrobox 'arch-distrobox' successfully created.
To enter, run: distrobox-enter arch-distrobox

```

**distrobox-enter arch-distrobox**
`Error: unable to start container "d03e19bcfad2991a9bd4fd5069d8c2148e964f547a1f6c87e01f1c29832448f3": runc: runc create failed: unable to start container process: error during container init: error preparing rootfs: mount /home/user/.local/share/containers/storage/overlay/f28d4e438e68177945fc2750a8ec7dfb2527ee7b68d9aed866ac476b7df5b5f1/merged:/home/user/.local/share/containers/storage/overlay/f28d4e438e68177945fc2750a8ec7dfb2527ee7b68d9aed866ac476b7df5b5f1/merged, flags: 0x5000: permission denied: OCI permission denied`

**Logs**
no output when running podman logs arch-distrobox

**Desktop (please complete the following information):**
 - Fedora 35
 - podman 4.0.0-10.fc35.x86_64

**Comment by 89luca89** [comment]
Hi @InvisibleRasta 
can you please test the following command to ensure that rootless podman works in your setup?

Please run **without sudo**:

`podman run --rm -ti --ipc host  --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash`

If this command does not work there is a problem with the setup of podman, 
let me know! :+1:

**Comment by InvisibleRasta** [comment]
Unfortunately it did not work for me. I am allways getting this OCI permission denied error
~  podman run --rm -ti --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob 9ae2c166397c done
Copying blob baca2b2a1f03 done
Copying config 80d141e567 done
Writing manifest to image destination
Storing signatures
Error: runc: runc create failed: unable to start container process: error during container init: error preparing rootfs: mount /home/user/.local/share/containers/storage/overlay/f4aaf8174628f76592d7574d496594a9406b86dd7f98e6f5ee1aec5252442d12/merged:/home/user/.local/share/containers/storage/overlay/f4aaf8174628f76592d7574d496594a9406b86dd7f98e6f5ee1aec5252442d12/merged, flags: 0x5000: permission denied: OCI permission denied

**Comment by InvisibleRasta** [comment]
i have tried that alredy but the guys in the IRC channel #podman told me to upgrade it

**Comment by 89luca89** [comment]
Mh OK seems then it is something else, probably worth opening an issue on podman at this point

**Comment by InvisibleRasta** [comment]
I did open an issue there. It seems it is now happening only with distrobox
https://github.com/containers/podman/issues/13328

**Comment by 89luca89** [comment]
That command is a pure podman command, so if that doesn't work it means that `rootless` podman is not working as expected, it's not really related to distrobox in this case

**Comment by 89luca89** [comment]
Hi @InvisibleRasta do you have any update on this issue?

**Comment by InvisibleRasta** [comment]
I am still on this error. Anyone has been able to figure it out?

**Comment by aral** [comment]
Can confirm is still an issue on latest Fedora Silverblue to Arch image.

**Comment by aishwaryaredd** [comment]
Hello All,
I am facing same issue as mentioned. Is this issue fixed? If yes, Please share the fix.
It would be really helpfull.

**Comment by a3f** [comment]
My home directory is on btrfs mounted from a dm-crypt volume. I also kept getting this error, even for @89luca89's arch image above.

I worked around it by creating a new ext4 partition and configured podman to use it with the overlay driver:
```
# ~/.config/containers/storage.conf
[storage]
  driver = "overlay"
  runroot = "/run/user/$your_user_id/containers"
  graphroot = "/scratch/$your_user_name/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```
```
# /etc/systemd/system/scratch.mount
[Unit]
Description=Scratch mount

[Mount]
What=/dev/disk/by-uuid/<your_fs_uuid>
Where=/scratch
Type=ext4

[Install]
WantedBy=multi-user.target
```

I also installed:

```
sudo apt install containers-storage fuse-overlayfs
```

It's possible some of these things aren't necessary, but I am content and don't want to sink anymore time into this now that it's working.

**Comment by poltpolt** [comment]
in my case I had the same on todays fresh ubuntu 24.04 machine

I deployed distrobos for  ubuntu2004 with 
distrobox-create --name ubuntu2004 --image ubuntu:20.04

and I got
distrobox enter ubuntu2004
Error: unable to start container "a6332c27f0b4e9151b3b17949e7e3548e29a2dd6d90c557e8ecb1f0f0133e9a8": crun: make `/home/polrus/.local/share/containers/storage/overlay/6288af1284999d256ef24178205483882ac2993df463249956f1395e6f64e172/merged` private: Permission denied: OCI permission denied

i solved it with:
```
sudo chown -R $USER:$USER /home/$USER/.local
sudo chmod -R 700 /home/$USER/.local
sudo chmod -R 755 /home/$USER/.local/share
sudo chmod -R 755 /home/$USER/.local/share/containers
sudo chmod -R 755 /home/$USER/.local/share/containers/storage
 
```

**Comment by kovmir** [comment]
> i solved it with:
> 
> ```
> sudo chown -R $USER:$USER /home/$USER/.local
> sudo chmod -R 700 /home/$USER/.local
> sudo chmod -R 755 /home/$USER/.local/share
> sudo chmod -R 755 /home/$USER/.local/share/containers
> sudo chmod -R 755 /home/$USER/.local/share/containers/storage
>  
> ```

Thanks! I migrated from one Linux distribution to another saving my `/home` partition, this solved the problem.
