### ISSUE TITLE
[Error] Failed to resolve names for Ubuntu archives

### ISSUE THREAD

**Issue by ryleu** [89luca89/distrobox#19]
When I try to set up an Ubuntu distrobox, it loads forever. When I get the logs from pod man it says it failed to resolve names for `archive.ubuntu.com` and `security.ubuntu.com`. I can access both sites from the host system.

Host system: Fedora 35

DistroBox version: 6db2fc4

Guest system: both Ubuntu 20.04 and 21.10

Error & logs:

```

ryleu@riley-fedora ~> distrobox-create --image docker.io/library/ubuntu:20.04 --name ubuntu-20-04
f818363c6ce37a68923068ed989e20eba86466466854b01124b4d6ea275e359f
e/
ryleu@riley-fedora ~> distrobox-enter --name ubuntu-20-04 -- bash -li
Starting container
run this command to follow along:
        podman logs -f ubuntu-20-04
....................................................................................................^C⏎
ryleu@riley-fedora ~ [SIGINT]> podman logs -f ubuntu-20-04
+ HOST_LINKS=/etc/host.conf /etc/hosts /etc/resolv.conf /etc/localtime /etc/timezone
+ rm -f /etc/host.conf
+ ln -s /run/host/etc/host.conf /etc/host.conf
+ rm -f /etc/hosts
+ ln -s /run/host/etc/hosts /etc/hosts
+ rm -f /etc/resolv.conf
+ ln -s /run/host/etc/resolv.conf /etc/resolv.conf
+ rm -f /etc/localtime
+ ln -s /run/host/etc/localtime /etc/localtime
+ rm -f /etc/timezone
+ ln -s /run/host/etc/timezone /etc/timezone
+ basename /bin/bash
+ shell_pkg=bash
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ apt-get update
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ apt-get install -y --no-install-recommends sudo apt-utils passwd procps util-linux bash
Reading package lists...
Building dependency tree...
Reading state information...
Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

E: Unable to locate package sudo
E: Package 'apt-utils' has no installation candidate
+ [ 100 -ne 0 ]
An error occurred
+ echo An error occurred
```

**Comment by ryleu** [comment]
Will running the installer again from the git repo update it again if I `git fetch && git pull` from master?

**Comment by 89luca89** [comment]
Yes works the same just `git checkout main; git fetch; git pull; ./install`

**Comment by 89luca89** [comment]
Also if you can include the contend of `/etc/resolv.conf` of the host (if you can)

**Comment by ryleu** [comment]
[cat_etc_resolv.conf_output.txt](https://github.com/89luca89/distrobox/files/7669290/cat_etc_resolv.conf_output.txt)
[printenv_output.txt](https://github.com/89luca89/distrobox/files/7669291/printenv_output.txt)

Here are those files. The issue persists on the latest commit.

**Comment by 89luca89** [comment]
> Edit: I normally use micro as my editor... No idea why I haven't set that env var. My OS is outing me as a normie disappointed

I'm not judging here ahahaha

Anyway I see you have fedora set up with `systemd-resolved` **but** the nameserver is modified manually to `192.168.1.1` instead of the default 

```
nameserver 127.0.0.53
options edns0 trust-ad
search lan
```

Can you try restoring it to default and use `NetworkManager` to set the DNSs on the host instead?

That's the only thing I see different from my setup right now

Can you try this way?

**Comment by ryleu** [comment]
Okay, I have changed `/etc/resolv.conf`. Is there a way to refresh everything? I'm not sure if the changes have actually been re-read and applied properly.

**Comment by 89luca89** [comment]
Inside the container it's just a symlink to the host file so the change is applied, for your main host I **think** it should be ok, but in doubt if you can reboot it's better :sweat_smile:

**Comment by ryleu** [comment]
After the reboot, `/etc/resolv.conf` was reset :thinking:

**Comment by 89luca89** [comment]
So it's back to your original setup with the hardcoded IP? Does the container still not work?

**Comment by ryleu** [comment]
A second `podman pull` did not help. Could my podman config be messed up maybe? It was installed on my system by default, so I assumed it was set up correctly.

**Comment by ryleu** [comment]
Reinstalling didn't help. I also tried `resolvectl revert enp9s0`, followed by a reboot, but that did not help either.

**Comment by 89luca89** [comment]
Can you try adding 

`nameserver 1.1.1.1` on top of the `192.168.1.1` in you resolv.conf and then create a **new** distrobox?

**Comment by ryleu** [comment]
Alright, I added it, `podman rm`'ed the old box, created a new one, entered it and got... the same damn error.

**Comment by 89luca89** [comment]
Let's see, running this:

```
podman create --dns none --env="XDG_RUNTIME_DIR=/run/user/1000" --hostname ubuntu-20 --ipc host --name ubuntu-20 --env="SHELL=/bin/bash" --network host --no-hosts --pid host --privileged --security-opt label=disable --ulimit host --user root:root --userns keep-id --volume /dev:/dev:rslave --volume /:/run/host/:rslave --volume /etc:/run/host/etc:rslave --volume /media:/run/host/media:rslave --volume /mnt:/run/host/mnt:rslave --volume /run:/run/host/run:rslave --volume /tmp:/run/host/tmp:rslave --volume /usr:/run/host/usr:rslave --volume /var:/run/host/var:rslave --volume /run/media:/run/media:rslave ubuntu:20.04 bash
```

This should create a podman and enter it
This podman uses the host's network and has no dns set up, nor it has /etc/hosts set up

Now I'd like to see the content of `/etc/resolv.conf` and `/run/host/etc/resolv.conf`, then try to ping google or something to check if DNS is working, then try `cp /run/host/etc/resolv.conf .etc/resolv.conf` and check again if DNS are working

I'm trying to debug through you because I cannot reproduce the issue on here... 

Also are you using F35 workstation, silverblue or server?

**Comment by 89luca89** [comment]
Oh ok sorry wrong command, let's do:

```sh
podman create --dns none --env="XDG_RUNTIME_DIR=/run/user/1000" --hostname ubuntu-20 --ipc host --name ubuntu-20 --env="SHELL=/bin/bash" --network host --no-hosts --pid host --privileged --security-opt label=disable --ulimit host --user root:root --userns keep-id --volume /dev:/dev:rslave --volume /:/run/host/:rslave --volume /etc:/run/host/etc:rslave --volume /media:/run/host/media:rslave --volume /mnt:/run/host/mnt:rslave --volume /run:/run/host/run:rslave --volume /tmp:/run/host/tmp:rslave --volume /usr:/run/host/usr:rslave --volume /var:/run/host/var:rslave --volume /run/media:/run/media:rslave ubuntu:20.04 sleep infinity

podman start ubuntu-20

podman exec -ti ubuntu-20 bash

```

Now you should enter the container correctly

**Comment by ryleu** [comment]
Okay, I'm logged in as root in the container!

**Comment by 89luca89** [comment]
Also because I just manually set my `/etc/resolv.conf` to be yours (I also am in a 192.168.1.1 subnet) and it works, I'm confused now :sweat:

**Comment by ryleu** [comment]
`cat /run/host/etc/resolv.conf` from the pod returns no such file, even though I can access it from the host. Could that be the issue?

**Comment by 89luca89** [comment]
Yep definitely the issue
What is the permission on `/etc/resolv.conf` in the host?

Can you read it without root?

**Comment by ryleu** [comment]
I can read it without root. I'm going to try to `ls -Alf` it.

**Comment by ryleu** [comment]
```
lrwxrwxrwx. 1 root root        32 Dec  6 18:13 resolv.conf -> /run/systemd/resolve/resolv.conf
```
I could try to `cat` the target.

**Comment by 89luca89** [comment]
What does

`ls -ladZ /etc/resolv.conf` 

return? This is mine in F35

`lrwxrwxrwx. 1 root root unconfined_u:object_r:net_conf_t:s0 39 Nov 15 10:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`

It's a symlink to `/run/systemd/resolve/stub-resolv.conf`

And

`ls -ladZ /run/systemd/resolve/stub-resolv.conf`

returns

`-rw-r--r--. 1 systemd-resolve systemd-resolve system_u:object_r:net_conf_t:s0 949 Dec  7 16:10 /run/systemd/resolve/stub-resolv.conf`

**Comment by ryleu** [comment]
`ls -ladZ /etc/resolv.conf`:
```
lrwxrwxrwx. 1 root root system_u:object_r:net_conf_t:s0 32 Dec  6 18:13 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
```

`ls -ladZ /run/systemd/resolve/stub-resolv.conf`:
```
-rw-r--r--. 1 systemd-resolve systemd-resolve system_u:object_r:net_conf_t:s0 949 Dec 7 16:10 /run/systemd/resolve/stub-resolv.conf
```

**Comment by 89luca89** [comment]
Ok seems like your has the `system_u` attribute while mine has `unconfined_u` attribute
Probably that's that

I see if you go for the source it works, so probably I'll just add a symlink detection and go for the source in the `init`

**Comment by ryleu** [comment]
That seems like a good plan of action. I'm pretty sure `resolv.conf` is freshly generated on each reboot before the rest of the system boots, so it's probably perfectly safe to symlink directly to the original in `/run`.

**Comment by 89luca89** [comment]
I've created a new branch `fix_init_symlink`

Can you try that and let me know if it fixes the issue? 

If you're using `git` you can simply switch branch and run again the `install`

Thanks!

**Comment by ryleu** [comment]
Sorry this took so long, the git command was being weird so I gave up for a bit. I reinstalled it, removed the old pod, and made a box, but it did not fix the issue.

**Comment by 89luca89** [comment]
OK but just reinstalling  doesn't work as is 
You can replace the `distrobox-init` in your installation path with this one and recreate the container 

https://raw.githubusercontent.com/89luca89/distrobox/b5761890d53d14eb80f792b9005c08015fa939e2/distrobox-init


This way you don't have to fiddle with git 😄

**Comment by 89luca89** [comment]
Scratch that, I've released version 1.0.5 with the included fix, you can test it reinstalling using the curl command or cloning again the repository and run `install`

`curl https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh`

or

`git clone https://github.com/89luca89/distrobox; cd distrobox; sudo ./install`

**Comment by ryleu** [comment]
Git was apparently working properly. This hasn't fixed the issue.

**Comment by 89luca89** [comment]
> Git was apparently working properly. This hasn't fixed the issue.

Can i have again the logs from the failing container please?

**Comment by ryleu** [comment]
Sure!

```

ryleu@riley-fedora ~> podman logs -f ubuntu-21-10
+ HOST_LINKS=/etc/host.conf /etc/hosts /etc/resolv.conf /etc/localtime /etc/timezone
+ [ -f /run/host/etc/host.conf ]
+ rm -f /etc/host.conf
+ realpath /run/host/etc/host.conf
+ ln -s /run/host/etc/host.conf /etc/host.conf
+ [ -f /run/host/etc/hosts ]
+ rm -f /etc/hosts
+ realpath /run/host/etc/hosts
+ ln -s /run/host/etc/hosts /etc/hosts
+ [ -f /run/host/etc/resolv.conf ]
+ [ -f /run/host/etc/localtime ]
+ rm -f /etc/localtime
+ realpath /run/host/etc/localtime
+ ln -s /run/host/usr/share/zoneinfo/America/New_York /etc/localtime+ [ -f /run/host/etc/timezone ]
+ basename /bin/bash
+ shell_pkg=bash
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ apt-get update
Ign:1 http://archive.ubuntu.com/ubuntu impish InRelease
Ign:2 http://security.ubuntu.com/ubuntu impish-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Ign:1 http://archive.ubuntu.com/ubuntu impish InRelease
Ign:2 http://security.ubuntu.com/ubuntu impish-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Ign:1 http://archive.ubuntu.com/ubuntu impish InRelease
Ign:2 http://security.ubuntu.com/ubuntu impish-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Err:1 http://archive.ubuntu.com/ubuntu impish InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu impish-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/impish/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/impish-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/impish-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/impish-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ apt-get install -y --no-install-recommends sudo apt-utils passwd procps util-linux bash
Reading package lists...
Building dependency tree...
Reading state information...
Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

E: Unable to locate package sudo
E: Package 'apt-utils' has no installation candidate
An error occurred
+ [ 100 -ne 0 ]
+ echo An error occurred
ryleu@riley-fedora ~>
```
Sorry for the weird formatting, Terminus does some strange stuff with the output so it looks good on mobile. It doesn't carry over to GitHub very well.

**Comment by 89luca89** [comment]
Aha! Found it!

That's strange but in our 2 installations of Fedora we have 2 different implementations on how `systemd-resolved` implements the symlink

in mine:

`lrwxrwxrwx. 1 root root unconfined_u:object_r:net_conf_t:s0 39 Nov 15 10:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`

in yours:

`lrwxrwxrwx. 1 root root system_u:object_r:net_conf_t:s0 32 Dec  6 18:13 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf`

this means, in mine, the symlink resolves correctly when we mount `/run/host/` as it is using a relative path `../run/blabla`, yours will not resolve as it's using a full path `/run/blabla` which is a broken link inside the container

SOLUTION:

We move this solution **outside** the container, we will mount those files in the `create` phase using realpath and readonly mounts

Will create a PR so you can check if this time this works :smile:

**Comment by ryleu** [comment]
That would certainly explain the weirdness. I wonder why there's a difference between the installs?

I'll test it out in a bit after you post it, but it might take a second because I have school to do.

**Comment by 89luca89** [comment]
No worries and rush, school is more important :smiley: 

Anyway now that I know what was wrong, I reproduced successfully your issue (I've forced my symlink to be fullpath) and now I've tested a fix that worked with this setup.

It is in the `fix_init_symlinks_2` branch
or you can update just the `create` and `init` file from here:

https://raw.githubusercontent.com/89luca89/distrobox/fix_init_symlinks_2/distrobox-create
https://raw.githubusercontent.com/89luca89/distrobox/fix_init_symlinks_2/distrobox-init

Remember that now both of them have to be updated as mounting as read-only that files in create will make the old init error as it's trying to overwrite read-only files

**Comment by ryleu** [comment]
It works!

**Comment by ryleu** [comment]
![image](https://user-images.githubusercontent.com/69326171/145238616-8ad1a710-97a6-4e42-a826-051569269394.png)

**Comment by 89luca89** [comment]
Cool will merge and close this issue

thanks for the collaboration and debugging!

**Comment by misterbreen** [comment]
Hi. Ive just installed Fedora 35 today and trying to create a deb11 DistroBox, I get the same original error. Well, e.g. 

2022-03-27T22:56:24.650267000+01:00 Err:1 http://deb.debian.org/debian bullseye InRelease
2022-03-27T22:56:24.650510000+01:00   Temporary failure resolving 'deb.debian.org'
2022-03-27T22:56:24.650783000+01:00 Err:2 http://security.debian.org/debian-security bullseye-security InRelease
2022-03-27T22:56:24.650878000+01:00   Temporary failure resolving 'security.debian.org'
2022-03-27T22:56:24.650963000+01:00 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
2022-03-27T22:56:24.651053000+01:00   Temporary failure resolving 'deb.debian.org'

should your fix have made it into latest releases?

Thanks
