### ISSUE TITLE
Launching host apps (flatpak) from container?

### ISSUE THREAD

**Issue by 0ranki** [89luca89/distrobox#194]
Is your feature request related to a problem? Please describe.

This is not really a bug or feature request, most closely a support request.

- I wanted to turn VS Code settings sync on inside the distrobox container. Exporting the app from the container works well, I'm still amazed how easy this is. But since I didn't have a browser installed inside the container, signing in to GitHub won't work, since VS Code (and a lot of other apps,too for similar purposes) tries to open a browser.

Describe the solution you'd like
- I'm not sure if there is a reasonable solution for this, since we are talking about containers. I tried to search the issues from Toolbox as well, but didn't find any.

Describe alternatives you've considered
- I managed to find 2 workarounds for now (these are for a F35 toolbox image):
  1. Install firefox and xdg-utils inside the container
    - Strange enough, this seems to open the sign-in tab on the host browser
  2. Manual method (works at least with GitHub signin):
    - Launch code from the container with `code --verbose`
    - Try to sign in and follow the logs outputted to the terminal
    - The authorization URI will be there, open that manually in the browser
    - Authorize, and GH will give you a link to use in case redirecting back to the application won't work. It won't, since VS Code is running in the container
    - Click the "Signing in to GitHub" in the bottom bar, a dialog box will open asking for the URI
    - Paste the URI from GitHub there

Additional context
- Since after installing Firefox inside the container, the tab opened in the host (flatpak) browser, I think there might be a way to circumvent installing a browser in the container. It's not that big a deal, but would save space. Unfortunately I am not savvy enough with containers to figure this out.
- I understand that this might be out of scope or just plain impossible, please close if you think so.

**Comment by misobarisic** [comment]
There already exists a way to run commands on the host described [here](https://github.com/89luca89/distrobox/blob/main/docs/posts/execute_commands_on_host.md). 

My only idea would be to make a custom script for opening web urls (`xdg-open`) and set it as the default. This would handle opening urls both inside the container and on the host. If a url were to be opened on the host, it would feel as normal (you'd only need to define the browser name inside the script). But if you were to open a url inside the container, the aforementioned script would `chroot` back to the host and run the opening script there. I am unsure how we would be able to achieve this since `chroot` requires elevated privileges.

**Comment by 89luca89** [comment]
Hi @0ranki 
as @misobarisic explained you can see [here](https://distrobox.privatedns.org/posts/execute_commands_on_host) how to execute commands on the host, probably just integrating `xdg-open` will be more than enough for what you're doing

I'm at this point I'm contemplating about integrating some `host-exec` by default :thinking:

**Comment by 0ranki** [comment]
I thought I'd post an update regarding `xdg-open` in case it's useful for someone, even though the issue is closed.

When installing the VS Code RPM, it pulls in `xdg-utils` as a dependency. This is actually causes problems inside a distrobox. I got URL url opening working by overriding the real `xdg-open` executable with one that calls `flatpak spawn --host /usr/bin/xdg-open "$@"`.

Now this doesn't help the VS Code login issue, as they've renewed the Github login procedure and there would need to be a way to add the distrobox-exported VS code as an URL handler for vscode:// links, which opens up after the Github OAUTH login. I haven't figured that part out yet, but launching the host browser by clicking a link works with the above method. It also works for other file types.

**Comment by 89luca89** [comment]
> a way to add the distrobox-exported VS code as an URL handler for vscode:// links, which opens up after the Github OAUTH login.

That should be taken care of when you export the .desktop file technically?
Or maybe there is something else?

**Comment by 0ranki** [comment]
Yes, the code URL handler is exported as well, and I think that is what should handle the link.

There might be something wrong with the actual VS Code/Github login flow though (for Linux), as the redirect back to the app after entering Github credentials in the browser doesn't seem to be working, even by pasting the link manually. Using flatpak browsers may be the issue, they don't do well with urls containing `:`. Tried to use the ostree firefox with Silverblue too, but GNOME did not know what to do with the return link. Not to mention the obvious user error possibility here.

**Comment by 0ranki** [comment]
Again writing more info, in case this could be useful to someone else.

I was able to make it work, the biggest issue was that flatpak browsers can't see the hosts MIME types, so flatpak Firefox doesn't know how to handle the vscode:// link no matter what. That's a known issue with flatpak, interesting to see if they can solve it sometimes.

Second one is that despite the files being generated on the host correctly during `distrobox-export`, the MIME type isn't registered into xdg-settings. This is a bug in VS Code, and is apparently already fixed in the insiders edition.

Link to the issue comment containing the solution:
[https://github.com/microsoft/vscode/issues/146408#issuecomment-1095273737](https://github.com/microsoft/vscode/issues/146408#issuecomment-1095273737)

So the workflow for making the Github login work:
(I'm on Fedora Silverblue 35, using a F35 distrobox container called fedora-toolbox-35)
- use a non-flatpak default browser
- create `~/.local/bin/xdg-open` and make executable:
```bash
    #!/bin/bash

    if [[ -f "/run/.containerenv" ]]; then
	flatpak-spawn --host /usr/bin/xdg-open "$@"
    else
	/usr/bin/xdg-open "$@"
    fi
```
- create distrobox
- update and install the MS VS Code RPM in the container
- `distrobox-export --app code`
- On the host:
  - `xdg-settings set default-url-scheme-handler vscode fedora-toolbox-35-code-url-handler.desktop`
  - `xdg-mime default fedora-toolbox-35-code-url-handler.desktop x-scheme-handler/vscode`
  - I rebooted just in case
- Github SSO login works.

I wasn't able to test and verify this again, as the Github SSO seems to be very tenacious and despite deleting everything I could find related to VS Code, including the distrobox container, VS Code remembered my Github account when turning the sync on again.

At least that `xdg-open` wrapper is a good thing, mostly when something is started with it I´d expect the app to be used to be the one installed on the host. In my case using VS Code on Silverblue this way is a far better method than playing with the Flatpak version and Remote: Containers extension for just about everything.

**Comment by 89luca89** [comment]
> Again writing more info, in case this could be useful to someone else.
> 
> I was able to make it work, the biggest issue was that flatpak browsers can't see the hosts MIME types, so flatpak Firefox doesn't know how to handle the vscode:// link no matter what. That's a known issue with flatpak, interesting to see if they can solve it sometimes.
> 
> Second one is that despite the files being generated on the host correctly during `distrobox-export`, the MIME type isn't registered into xdg-settings. This is a bug in VS Code, and is apparently already fixed in the insiders edition.
> 
> Link to the issue comment containing the solution: [microsoft/vscode#146408 (comment)](https://github.com/microsoft/vscode/issues/146408#issuecomment-1095273737)
> 
> So the workflow for making the Github login work: (I'm on Fedora Silverblue 35, using a F35 distrobox container called fedora-toolbox-35)
> 
>     * use a non-flatpak default browser
> 
>     * create `~/.local/bin/xdg-open` and make executable:
> 
> 
> ```shell
>     #!/bin/bash
> 
>     if [[ -f "/run/.containerenv" ]]; then
> 	flatpak-spawn --host /usr/bin/xdg-open "$@"
>     else
> 	/usr/bin/xdg-open "$@"
>     fi
> ```
> 
>     * create distrobox
> 
>     * update and install the MS VS Code RPM in the container
> 
>     * `distrobox-export --app code`
> 
>     * On the host:
>       
>       * `xdg-settings set default-url-scheme-handler vscode fedora-toolbox-35-code-url-handler.desktop`
>       * `xdg-mime default fedora-toolbox-35-code-url-handler.desktop x-scheme-handler/vscode`
>       * I rebooted just in case
> 
>     * Github SSO login works.
> 
> 
> I wasn't able to test and verify this again, as the Github SSO seems to be very tenacious and despite deleting everything I could find related to VS Code, including the distrobox container, VS Code remembered my Github account when turning the sync on again.
> 
> At least that `xdg-open` wrapper is a good thing, mostly when something is started with it I´d expect the app to be used to be the one installed on the host. In my case using VS Code on Silverblue this way is a far better method than playing with the Flatpak version and Remote: Containers extension for just about everything.

Hey @0ranki that is a really nice search and writeup
Would you like to open a PR to add this on the vscode-distrobox integration page? :smile:

**Comment by 0ranki** [comment]
@89luca89 sure, I'll need to verify on a clean install/profile that the steps actually work. Probably a good idea to test on some non-ostree distro as well.

**Comment by ian-h-chamberlain** [comment]
Sorry to bump an old post, but I was having some issues with this mechanism on SteamOS until I realized there is actually a utility to do this for you automatically with some distros. Any time I tried to use the `~/.local/bin` script, vscode would default to `/usr/bin/xdg-open` instead.

Also worth noting for google's sake: in my case there was a weird bug where doing this seemed to corrupt my icon cache, requiring me to run `kbuildsycoca5` on the host to fix it after each time I clicked a link :sob: 

In my case this is what I had to do (resolving both of the above issues):

```console
$ # probably also available with dnf, apt, etc but maybe named `flatpak-xdg-open`
$ yay flatpak-xdg-utils
$ # could also be somewhere else in $PATH that will take precedence over builtin `xdg-open`
$ sudo ln -s /usr/lib/flatpak-xdg-utils/xdg-open /usr/local/bin/
```

I can open a PR to update / add this info to the vscode page if it seems useful? Maybe I'll also try spinning up a fresh container to make sure it works there the same way.

**Comment by 89luca89** [comment]
> Sorry to bump an old post, but I was having some issues with this mechanism on SteamOS until I realized there is actually a utility to do this for you automatically with some distros. Any time I tried to use the `~/.local/bin` script, vscode would default to `/usr/bin/xdg-open` instead.
> 
> Also worth noting for google's sake: in my case there was a weird bug where doing this seemed to corrupt my icon cache, requiring me to run `kbuildsycoca5` on the host to fix it after each time I clicked a link sob
> 
> I found [containers/toolbox#291 (comment)](https://github.com/containers/toolbox/issues/291#issuecomment-948975647) which seems closely related and led me to a solution. In my case this is what I had to do (resolving both of the above issues):
> 
> ```
> $ # probably also available with dnf, apt, etc but maybe named `flatpak-xdg-open`
> $ yay flatpak-xdg-utils
> $ # could also be somewhere else in $PATH that will take precedence over builtin `xdg-open`
> $ sudo ln -s /usr/lib/flatpak-xdg-utils/xdg-open /usr/local/bin/
> ```
> 
> I can open a PR to update / add this info to the vscode page if it seems useful? Maybe I'll also try spinning up a fresh container to make sure it works there the same way.

You should be able to just use `distrobox-host-exec` to have a working xdg-open:

`sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open`

can you confirm this works? (works for me, but better have more feedbacks)

**Comment by ian-h-chamberlain** [comment]
> You should be able to just use `distrobox-host-exec` to have a working xdg-open:
> 
> `sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open`
> 
> can you confirm this works? (works for me, but better have more feedbacks)

Huh, this does seem to do the trick as well! I guess the main issue I had before was only trying to use `~/.local/bin` (instead of `/usr/local/bin`), but VSCode seems to ignore that path and falls back to `/usr/bin/xdg-open`, which doesn't work correctly.

Thanks for this suggestion, it seems to function the same but requires one less step (no extra packages needed)!
