### ISSUE TITLE
[Suggestion]  distrobox-halt or -stop

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [89luca89/distrobox#195]
**Is your feature request related to a problem? Please describe.**
Just a means to easily free the resources consumed by the container when finished with it.

**Describe the solution you'd like**
A halt or stop command for container would be great.

**Describe alternatives you've considered**
The `podman` and `docker` halt commands are not so easy for me to remember -- or find -- when I'm otherwise mostly interacting with them via `distrobox`.  So far, the simplest and easiest method of halting a container has been to `distrobox-enter -i [image] systemctl shutdown`.

**Comment by misobarisic** [comment]
> The `podman` and `docker` halt commands are not so easy for me to remember -- or find.

`podman stop [container]`?

**Comment by misobarisic** [comment]
But I agree. It would be quality of life improvement for most users to have `distrobox-stop` available

**Comment by 89luca89** [comment]
Nothing against this i guess, we can do a small wrapper for it, contributions are welcome :smile: 
I'll do it in some free time if no one wants to do this :+1:
