### ISSUE TITLE
Best way to do something after distrobox-init?

### ISSUE THREAD

**Issue by tunix** [89luca89/distrobox#200]
Hi,

I want to install & configure lunarvim right after distrobox-init is executed. Is there a proper way of doing this? What does distrobox-init do if I provide an ENTRYPOINT inside the Containerfile?

**Comment by 89luca89** [comment]
Hi @tunix 
it is possible to use init-hooks during the creation phase as explained here:

https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md

Entrypoint in the container is overwritten to be `distrobox-init` so the intended way to do custom stuff on initialization is to use the hooks

**Comment by tunix** [comment]
Hi @89luca89 ,

I just realized that while I read the source code but there are some problems with it. I tried the hook for installing lunarvim during the `distrobox-init` process but the permissions are wrong. My uid and gid is 1000 but the files this process created are owned by 10000.

**Comment by 89luca89** [comment]
@tunix this is because the init is performed as root inside the container (which is mapped to an high UID) 
If you need to do it as your user either add a `sudo -u your-user` before the command, or run it as part of the exec 

```
distrobox create [...]
distrobox enter -- command-to -setup-lunarvim
distrobox enter 
```
