### ISSUE TITLE
[Suggestion] private network

### ISSUE THREAD

**Issue by BlauerHunger** [89luca89/distrobox#213]
**Is your feature request related to a problem? Please describe.**
I recently came across a situation where it would have been nice to run sandboxed applications seamlessly on my host where it is ensured that every connection the application makes goes through tor. 

**Describe the solution you'd like**
I'd like to see the ability to either directly connect a distrobox container to a certain network bridge (rootful) OR to intercept everything in slirp4netns (or whatever networking plugin is used) so that everything is routed through a given gateway, e.g. tor. 

**Describe alternatives you've considered**
Current alternatives are the use of Whonix or QubesOS. 

**Additional context**
I see Distrobox as a promising middle ground between full-blown Qubes OS and a classic system where everything is installed as usual for cases where flatpak just isn't enough (e.g. multiple installations of one program, software not available as flatpak)

**Comment by 89luca89** [comment]
Probably we can integrate something with #28 we first need to have a sandboxed mode :smile: 

I'll set this to blocked as it depends first on that issue to be solved first

**Comment by 89luca89** [comment]
This has been implemented already
