### ISSUE TITLE
[Discussion] Cant enter rockylinux:8 container

### ISSUE THREAD

**Issue by biji** [89luca89/distrobox#214]
Is your feature request related to a problem? Please describe.

I can't enter to rocky linux 8, created with:

```
distrobox-create --image rockylinux:8 --name rocky8
```

Error message:
```
distrobox-enter rocky8
Starting container rocky8
run this command to follow along:
        podman --remote logs -f rocky8
./usr/bin/dnf
Rocky Linux 8 - AppStream                       0.0  B/s |   0  B     00:00    
Error: An error occurred

An error occurred
```

It seem error with `resolv.conf` , please help how to fix

Host /etc/resolv.conf:
```
nameserver 127.0.0.53
options edns0 trust-ad
search .
```

Thanks

**Comment by 89luca89** [comment]
Hi @biji can you provide more information on your setup?

1 - are you using podman or docker
2 - which distrobox version
3 - which podman or docker version 
4 - which distribution you're on

Thanks

**Comment by biji** [comment]
Hi
1. I'm using podman
2. distrobox version: 1.2.13
3. podman version 3.4.4
4. fedora 35

**Comment by 89luca89** [comment]
@biji any news on this?

**Comment by biji** [comment]
Thank you very much. It is now working using distrobox 1.2.14

```
$ distrobox-create --image rockylinux:8 --name rocky8
b0267d8181b34a26e98e1adae6c80b50564e890b4047c4263d67d7e12da80d67
Distrobox 'rocky8' successfully created.
To enter, run:
	distrobox-enter rocky8

$ distrobox-enter rocky8
Starting container rocky8
run this command to follow along:
	podman --remote logs -f rocky8
..............................
done!
$
```
