### ISSUE TITLE
[Suggestion] Kde Neon support

### ISSUE THREAD

**Issue by sbancuz** [89luca89/distrobox#219]
Hi, i wanted to start developing some stuff on kde, so i tried making a container even though is not supported, i succeeded by pulling the image from [the neon docker page](https://community.kde.org/Neon/Docker) (eg. kdeneon/plasma:developer is the one i tested) on the kde website and selecting the docker.io/library/... option then prompted by distrobox-create.

There is just one little problem with these images, they already have a default user "neon" that causes distrobox-init to fail to create the user because it tries to use the same UID twice, to "fix" this issue i tried to add  `userdel -f neon` before the user creation process and it worked.

Obviously this is just something temporary, but to add support for this and some other weird distro that comes already with a user it should be just as simple as deleting all the users already present in the image

**Comment by 89luca89** [comment]
Hi @sbancuz I'm not sure those images are intended to be used as simple distroboxes, but anyway I'm thinking it would be useful to have some `pre-init-hooks` so that one could issue commands **before** the init start, effectively resolving this issue.

I've opened #220 to solve this

**Comment by bam80** [comment]
Just intended to open an issue about the support.

@sbancuz I'm curious if instructions here will let you run full Neon session with Distrobox? :)
https://distrobox.privatedns.org/posts/run_latest_gnome_kde_on_distrobox.html#running-latest-plasma

**Comment by bam80** [comment]
(For the reference - there is also https://github.com/Wenzel/docker-kdesrc-build which doesn't developed any more)

**Comment by 89luca89** [comment]
This should now be doable using `preinit-hooks` to run the `userdel -f neon`
