### ISSUE TITLE
[Feature] Pre-initialization Hooks

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#220]
In #118 it was implemented an initialization hook to issue commands after the init and before the main loop starts

It would be useful to have also pre-init-hooks, to issue BEFORE the init starts:

```
distrobox create --image kdeneon/all:user --name test-neon \
             --pre-init-hooks "userdel -f neon"
```

**Comment by sbancuz** [comment]
Wouldn't it be better to have maybe a directory called `pre-init-hooks` with hooks, named for example "kdeneon", and check if the image name contains the name of the hook and if it does, just eval the hook file before the init process, i feel like hardcoding the fix into the create command it's not something you should do. I could try to implement this myself you want but i never did anything with bash.

**Comment by 89luca89** [comment]
mmh not a big fan of this, it implies that you cannot have 2 different hooks for 2 containers using the same image for example or subsets of the name

this instead is much similar to the already present `init-hook` flag, which has to be ran just on the first start of the container (not in each `enter`)

It's not an hardcode here, you're free to pass whatever argument to `--pre-init-hooks` for any image, including simply the `sh /path/to/your/script` if you wish :smile:
