### ISSUE TITLE
Can't access my generated Archlinux distrobox

### ISSUE THREAD

**Issue by greedy-it** [89luca89/distrobox#221]
Hello,

I have a problem and that is when I create a distrobox with Archlinux, then I can not enter it.

**This is creating:**

`distrobox-create -i archlinux -n dev-arch`
125b8f2eeb2901348569b049f170a679262afa0b14368e8a238a8ba346af25c5
Distrobox 'dev-arch' successfully created.
To enter, run:
	`distrobox-enter dev-arch`

**This is enter the distrobox:**

`distrobox-enter -n dev-arch`
Starting container dev-arch
run this command to follow along:
	podman --remote logs -f dev-arch
........../usr/sbin/find
/usr/sbin/mount
/usr/sbin/passwd
/usr/sbin/pacman
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change  Download Size

core/bash    5.1.016-1    5.1.016-1      0.00 MiB       1.63 MiB

Total Download Size:   1.63 MiB
Total Installed Size:  8.19 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 bash-5.1.016-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
reinstalling bash...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
resolving dependencies...
looking for conflicting packages...

Package (8)       Old Version  New Version  Net Change  Download Size

core/bash         5.1.016-1    5.1.016-1      0.00 MiB               
core/findutils    4.9.0-1      4.9.0-1        0.00 MiB       0.44 MiB
core/ncurses      6.3-2        6.3-2          0.00 MiB       1.14 MiB
core/procps-ng    3.3.17-1     3.3.17-1       0.00 MiB       0.50 MiB
core/shadow       4.11.1-1     4.11.1-1       0.00 MiB       1.16 MiB
core/sudo                      1.9.10-1       6.85 MiB       1.65 MiB
core/util-linux   2.37.4-1     2.38-1         0.26 MiB       2.42 MiB
extra/vte-common               0.68.0-1       0.02 MiB       0.01 MiB

Total Download Size:    7.33 MiB
Total Installed Size:  37.47 MiB
Net Upgrade Size:       7.12 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 util-linux-2.38-1-x86_64 downloading...
 sudo-1.9.10-1-x86_64 downloading...
 shadow-4.11.1-1-x86_64 downloading...
 ncurses-6.3-2-x86_64 downloading...
 procps-ng-3.3.17-1-x86_64 downloading...
 findutils-4.9.0-1-x86_64 downloading...
 vte-common-0.68.0-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
reinstalling ncurses...
reinstalling bash...
reinstalling findutils...
reinstalling procps-ng...
reinstalling shadow...
installing sudo...
upgrading util-linux...
installing vte-common...
:: Running post-transaction hooks...
(1/5) Creating system user accounts...
(2/5) Reloading system manager configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
(3/5) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
fchownat() of /tmp failed: Operation not permitted
fchownat() of /dev/snd/seq failed: Operation not permitted
fchownat() of /dev/snd/timer failed: Operation not permitted
fchownat() of /dev/loop-control failed: Operation not permitted
fchownat() of /dev/kvm failed: Operation not permitted
fchownat() of /dev/vhost-net failed: Operation not permitted
fchownat() of /dev/vhost-vsock failed: Operation not permitted
(4/5) Reloading device manager configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Device manager is not running.
(5/5) Arming ConditionNeedsUpdate...
Warning: failed to bind mount /run/host/etc/machine-id to /etc/machine-id
Error: An error occurred

An error occurred

**My system:**

Fedora Silverblue 35
podman version 3.4.4
distrobox version: 1.2.14
archlinux:latest version

Thanks for your help.

**Comment by 89luca89** [comment]
Hi @greedy-it this issue is fixed in the `main` branch version, it needs a `pacman -Syyu` before installing the needed dependency, and it has been added

Please try using the latest version from git main branch and let me know

**Comment by greedy-it** [comment]
Perfect! Solved! Thanks for fast support.
