### ISSUE TITLE
[Error] Issues installing metasploit-framework and other dependencies on kali-rolling guest

### ISSUE THREAD

**Issue by lucapxl** [89luca89/distrobox#226]
**Describe the bug**
when trying to install `kali-linux-headless` or just `metasploit-framework` on a kali-rolling guest, the installation fails.
On the same host, if I run the podman directly with `podman run -it kali-rolling` I am able to install successfully the same packages that fail in the distrobox

**To Reproduce**
create the distrobox and enter it:
`distrobox-create --image kali-rolling --name kali`
`distrobox-enter kali`

Install metasploit-framework
`sudo apt update && sudo apt -y install metasploit-framework`

**Expected behavior**
the packages should install without error like when running the container via podman directly.

**Logs**
Installer log:
> ...
> fixing permissions on existing directory /var/lib/postgresql/14/main ... ok
> creating subdirectories ... ok
> selecting dynamic shared memory implementation ... posix
> selecting default max_connections ... 100
> selecting default shared_buffers ... 128MB
> selecting default time zone ... Etc/UTC
> creating configuration files ... ok
> running bootstrap script ... ok
> performing post-bootstrap initialization ... ok
> syncing data to disk ... ok
> Can't exec "systemctl": No such file or directory at /usr/bin/pg_createcluster line 593.
> update-alternatives: using /usr/share/postgresql/14/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
> /var/lib/dpkg/info/postgresql-14.postinst: 111: systemctl: not found
> dpkg: error processing package postgresql-14 (--configure):
>  installed postgresql-14 package post-installation script subprocess returned error exit status 127
> Setting up libjson-xs-perl (4.030-1+b2) ...
> Setting up john (1.9.0-Jumbo-1+git20211102-0kali2) ...
> dpkg: dependency problems prevent configuration of postgresql:
>  postgresql depends on postgresql-14; however:
>   Package postgresql-14 is not configured yet.
> 
> dpkg: error processing package postgresql (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of metasploit-framework:
>  metasploit-framework depends on postgresql; however:
>   Package postgresql is not configured yet.
> 
> dpkg: error processing package metasploit-framework (--configure):
>  dependency problems - leaving unconfigured
> Setting up ruby3.0 (3.0.3-1) ...
> Setting up ruby-rubygems (3.3.5-2) ...
> Setting up ruby (1:3.0+1kali1) ...
> Setting up rake (13.0.6-3) ...
> Setting up libruby3.0:amd64 (3.0.3-1) ...
> Setting up ruby-bundler (2.3.5-2) ...
> Setting up ruby3.0-dev:amd64 (3.0.3-1) ...
> Setting up bundler (2.3.5-2) ...
> Setting up ruby-dev:amd64 (1:3.0+1kali1) ...
> Processing triggers for libc-bin (2.33-6) ...
> Processing triggers for ca-certificates (20211016) ...
> Updating certificates in /etc/ssl/certs...
> 0 added, 0 removed; done.
> Running hooks in /etc/ca-certificates/update.d...
> done.
> Errors were encountered while processing:
>  postgresql-14
>  postgresql
>  metasploit-framework
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 36
 - Version: distrobox: 1.2.14
 - Guest: docker.io/kalilinux/kali-rolling:latest

**Additional context**
I tested both the latest github version of distrobox as well as the packaged version in Fedora 36.

**Comment by 89luca89** [comment]
This seems a missing dependency which is `systemctl`, which is not pulled from apt automatically
Can you try installing it manually before 

sudo apt update && sudo apt -y install systemd && sudo apt -y install metasploit-framework

**Comment by 89luca89** [comment]
Hey @lucapxl 
I was able to install the framework using latest version from `main` branch (so more updated than 1.2.14)
This was probably because of a fix implemented for another issue regarding systemd services.

Can you try using the latest version from git and try again? You will have to recreate the container

**Comment by lucapxl** [comment]
@89luca89 I can confirm that all works on version 1.2.15. Great job!

**Comment by 89luca89** [comment]
Glad it works now, closing then
