### ISSUE TITLE
[Feature] Allow flag to not use workdir on distrobox-enter

### ISSUE THREAD

**Issue by X9VoiD** [89luca89/distrobox#231]
**Describe the bug**
Distrobox shell does not start on specified home directory.

**To Reproduce**
```
distrobox create -n arch -i archlinux -H ~/pods/arch
distrobox enter arch
```
The shell will start in host's `~` directory.

**Expected behavior**
The shell should start in host's `~/pods/arch` directory.

**Logs**
[distrobox_log.txt](https://github.com/89luca89/distrobox/files/8458068/distrobox_log.txt)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Version: 22.05

**Additional context**
Can be workaround by doing `cd ~` upon login.

**Comment by 89luca89** [comment]
This is wanted, it's not a bug, for a seamless integration you exepct to enter the container in the same workdir you're launching it,
a way to do this would be a `--no-workdir` flag to skip that and simply enter the $HOME set (either custom or not)

This has to be implemented anyway in the future (till sandboxing and the new #230 is done) 

If the flag sounds good for your issue, I'll modify it to be a feature request

**Comment by X9VoiD** [comment]
I see, `--no-workdir` would indeed be a good flag for this.

**Comment by nathanchance** [comment]
I started to take a look at this but it is not entirely clear to me how to get the user's custom home value in `distrobox-enter`, as that is only available in the container after creation. I see there is an `inspect` call after the command has been generated, would it be possible to add an `inspect` call in `generate_cmd` or is that too early?

**Comment by 89luca89** [comment]
> I started to take a look at this but it is not entirely clear to me how to get the user's custom home value in `distrobox-enter`, as that is only available in the container after creation. I see there is an `inspect` call after the command has been generated, would it be possible to add an `inspect` call in `generate_cmd` or is that too early?

Yes we can extrapolate it from that inspect phase, as that is done way before calling `generate_cmd`
We can add this:

```shell
eval "$(${container_manager} inspect --type container "${container_name}" --format \
	'container_status={{.State.Status}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}}{{end}}{{end}};
	{{range .Config.Env}}{{if slice . 0 6 | eq "SHELL="}}container_shell={{slice . 6 | printf "%q"}}{{end}}{{end}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}')"

```

and it will save the HOME variable of the container in `$container_home`, and we can use it
