### ISSUE TITLE
[Suggestion] add a way to update all boxes at once

### ISSUE THREAD

**Issue by castrojo** [89luca89/distrobox#240]
**Is your feature request related to a problem? Please describe.**

Sometimes I forget to update my containers.

**Describe the solution you'd like**

podman itself comes with this: https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html which lets me run `podman auto-update` and then containers tagged with `io.containers.autoupdate` get updated. It also comes with a handy timer and systemd service unit to do it all in the background for me. 

Perhaps `autoupdate=true` or something in the distrobox configuration file, or perhaps if there's a need for tagging support in general so that I could pass along the tag myself that would work too.  We'd need to tell people to enable the timer as well since I'm not sure if it's on by default on every distro? 

**Describe alternatives you've considered**

I was just going to make my own service units but since podman already supports this out of the box then I didn't have to do that, whew!

**Comment by 89luca89** [comment]
Hi @castrojo !

While I agree that we need something to keep the various toolboxes updated, `podman-update` doesn't seem to fit well with the concept of "pet-container"
In the moment it downloads a new image (for example latest version of `fedora:rawhide`), it would overwrite the container, so that every customization that you've done (packages) would be lost and you'll find yourself with a vanilla container without notice

**Comment by 89luca89** [comment]
Probably a better approach would be just using `topgrade` https://github.com/r-darwish/topgrade

Seems like you can just do something like:

`distrobox list | tail -n+2 | awk '{print $4}' | xargs -I{} distrobox enter {} -- topgrade`

To update all.

Another approach would be implementing distrobox support in it, seems like they already opened an issue for this: https://github.com/r-darwish/topgrade/issues/881 and it already supports toolbx

**Comment by amazingidiot** [comment]
I just had a similar idea and after a short discussion on matrix here are my thoughts:

distrobox-create gets a new flag like "--autoupdate". It adds a new step to the distrobox-enter scripts, which would run the distributions package manager (or topgrade, haven't tried this tool yet). Pretty much all commonly used package managers have a flag to skip any prompts (I think @89luca89  already is aware of this in the initial installation of additional packages during the packages creation).

distrobox-enter gets a new flag like "--no-autoupdate" or "--skip-update" to skip the updates in case there's no internet connection or the user doesn't want the container to update. Maybe the internet connectivity could be read from the network manager? When the flag is not present, then updates are installed before the user enters the distrobox. Maybe a restart of the container afterwards is a good idea? Sure, it slows the start of the distroboxes, but one can always disable autoupdating and use distroboxes the usual way.

what might also be possible is a "distrobox-update" which starts the all distroboxes, runs the distributions package manager, and stops the containers again?

**Comment by 89luca89** [comment]
I like the idea of updating all the boxes at once :smile: 

Probably I'll see if I can find some time to add the support to topgrade itself, as a dedicated tool it surely will do better than me looping trough the boxes and trying all package managers
