### ISSUE TITLE
[Error] distrobox-enter hang when starting containers without an entry point

### ISSUE THREAD

**Issue by vyskocilm** [89luca89/distrobox#242]
**Describe the bug**

```
distrobox-enter distroless-static-debian11
Starting container distroless-static-debian11
run this command to follow along:
        podman logs -f distroless-static-debian11
................................................................. indefinitelly ..............................
```

**To Reproduce**
```
distrobox-create --image gcr.io/distroless/static-debian11 --name distroless-static-debian11
```

**Expected behavior**

I know this was a PEBKAC. I'd say that distrobox shall warn or error when attempting to use an image without an entrypoint

**Logs**

```
podman logs -f distroless-static-debian11
{"msg":"exec container process (missing dynamic library?) `/usr/bin/entrypoint`: No such file or directory","level":"error","time":"2022-04-25T09:17:49.000226354Z"}
```

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version: VERSION_ID="20220406"

**Additional context**

```
$ rpm -q distrobox podman conmon crun
distrobox-1.2.14-1.1.noarch
podman-4.0.3-1.1.x86_64
conmon-2.0.30-1.3.x86_64
crun-1.4.4-1.1.x86_64
```

**Comment by 89luca89** [comment]
Hi @vyskocilm 

If you try to run the image normally you'll see that it's missing `/bin/sh` which is necessary to execute the entrypoint:

```sh
$ podman run --rm -ti gcr.io/distroless/static-debian11 /bin/sh
Trying to pull gcr.io/distroless/static-debian11:latest...
Getting image source signatures
Copying blob 36698cfa5275 done  
Copying config a6ca08aa98 done  
Writing manifest to image destination
Storing signatures
Error: executable file `/bin/sh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

So this image cannot be compatible with distrobox (and it is not in fact listed in the compatibility list)

**Comment by vyskocilm** [comment]
Hi @89luca89, thanks for a fast answer. I do know and admitted this was my mistake. I just used your distrobox for the first time and immediately love it :+1: Such a wonderful tool :muscle:. Not surprising I wanted to use it immediately in all other scenarios even if I should not :innocent:

I'd say that some kind of a warning or an error may be enough. Not sure how much work this would be.

**Comment by 89luca89** [comment]
That was a good idea :smile: pushed a commit to implement this check, thanks!
