### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by SingleSlice** [89luca89/distrobox#243]
Permission issue when trying to install xinit inside a container.
![image](https://user-images.githubusercontent.com/32547537/165155853-b0af2a24-9369-4823-905f-3988e3e3a897.png)

-OS : arch linux
using podman, debian image
tried using both the git version, and the normal one.

installing xinit does work on my laptop

**Comment by 89luca89** [comment]
Hi @SingleSlice which version of distrobox are you running?
Podman or docker?

Can you try latest version from `main` branch from git and see if it resolves the problem?

**Comment by 89luca89** [comment]
Sorry just saw that yo wrote it under the screenshot, I'll try and see if I can reproduce :+1:

**Comment by 89luca89** [comment]
@SingleSlice nice find :smile: this seems to be an incompatibility of installing in general systemd on a fuse.overlayfs file system:

`podman run --rm -ti debian:latest bash` 

and running `apt install systemd` will yield the same result.

I've found a workaround for this, and pushed it to `main`, I've tested installing systemd and xinit and now it works as intended

**Comment by SingleSlice** [comment]
> @SingleSlice nice find smile this seems to be an incompatibility of installing in general systemd on a fuse.overlayfs file system:
> 
> `podman run --rm -ti debian:latest bash`
> 
> and running `apt install systemd` will yield the same result.
> 
> I've found a workaround for this, and pushed it to `main`, I've tested installing systemd and xinit and now it works as intended

now, `podman run --rm -ti debian:latest bash` does work without errors, but systemd throws the same error.

i tried searching a little on the internet, and thought my kernel was the problem, so i changed from linux-zen to linux-linux, still wont work.

**Comment by 89luca89** [comment]
You should try the latest `main` branch and create the container again and it will work :+1:

The normal podman command won't work, this is an incompatibility between systemd trying to set ACLs and overlayfs, so the only way to resolve this is to mount an ext4 or xfs filesystem in some specific paths.
Latest commit resolves this

**Comment by SingleSlice** [comment]
Oh! I did try to use the latest branch, with the git clone and ./install, though it still won't work, maybe I'm doing something wrong.

Just to be sure, would having a separate home partition cause problems with distrobox?

**Comment by 89luca89** [comment]
Nope should work without problems, I'm using a separate partition myself without problems
You'll need to recreate the container so 

`distrobox rm your-container`

and then create it again

**Comment by SingleSlice** [comment]
then i guess its a problem with my arch setup, as it wont work anyways even with removing the container, thanks for being so available to fixing issues :D
