### ISSUE TITLE
[Suggestion] Pop!_OS container support

### ISSUE THREAD

**Issue by TheParadoxBox** [89luca89/distrobox#250]
**Is your feature request related to a problem? Please describe.**
I've been looking to use Distrobox under Fedora Silverblue, but I would like to be able to use a Pop!_OS container for gaming. Unfortunately, Pop!_OS isn't supported yet and I can't figure out how to add it myself.

**Describe the solution you'd like**
Ideally, it should be added to the compatibility list.

**Describe alternatives you've considered**
I've considered using Ubuntu instead, but Snaps really bug me.

**Additional context**
I did find a Pop!_OS container on Docker Hub if that helps: https://hub.docker.com/r/hugojosefson/popos It doesn't seem to be updated to 22.04 yet, though.

**Comment by 89luca89** [comment]
Hey @TheParadoxBox 

So, I'd say you can go with Ubuntu, docker images do not use snaps :+1: 

But anyway I see no reason why it shouldn't work, you can try it yourself

`distrobox create -i hugojosefson/popos:latest -n popos`
`distrobox enter popos`

**Comment by TheParadoxBox** [comment]
Thanks for the help! The command you replied with works great with Docker as the backend; after some Googling, I found that all you need to change to get it to work with Podman is to just change `hugojosefson/popos:latest` to `docker.io/hugojosefson/popos:latest`.

I suppose official support for Pop!_OS in Distrobox won't come until there's an official Docker Pop!_OS package, which is likely to never happen, seeing as Docker is geared toward servers. Thanks for the help, though!

**Comment by misobarisic** [comment]
> Thanks for the help! The command you replied with works great with Docker as the backend; after some Googling, I found that all you need to change to get it to work with Podman is to just change `hugojosefson/popos:latest` to `docker.io/hugojosefson/popos:latest`.

You had to do that since `docker.io` is not in your registries file (aka it is not a "prefix"). You need to add it manually. The conf file should be located in `/etc/containers/...` if I'm not mistaken.
