### ISSUE TITLE
[Error] Enter tries to execute shell based on HOST's PATH instead of the container's one

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#251]
If you create a container like:

`SHELL=/usr/bin/zsh distrobox create -i alpine:latest -n test`

and do a

`distrobox enter test`

You'll get an:

`Error: executable file `/usr/bin/zsh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found`

That is because alpine puts it in `/bin/zsh`, so let's find a way to make it work

**Comment by serebit** [comment]
Something similar to this is happening for me on distrobox v1.4.0:
```
distrobox create --root --image alpine:edge
```
Then entering with:
```
distrobox enter --root alpine-edge
```
produces the following error message:
```
sh: /usr/bin/zsh: not found

An error occurred

An error occurred
```
