### ISSUE TITLE
[Suggestion] Passing unsupported CLI flag should generate error

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#252]
## Use case

Passing an unsupported flag currently fails silently.

This can complicate troubleshooting problems. (e.g., when two different versions of Distrobox are at play or if a flag is misspelled). For example, see https://github.com/89luca89/distrobox/issues/249#issuecomment-1116016993

## Proposed solution

Implement an error message, e.g., 

```
Error: Unknown flag --root 
```

**Comment by 89luca89** [comment]
Fixed by #255
