### ISSUE TITLE
[Suggestion] Add support for microdnf in the distrobox-enter script for RHEL UBI Minimal support

### ISSUE THREAD

**Issue by MikuOcta** [89luca89/distrobox#254]
The RHEL UBI-minimal platform uses as a package manager microdnf rather than YUM or DNF. It would be nice for when the "distrobox-enter" command is used, to first install dnf or yum on the image, then install the other requiered packages for the missing dependencies.

![Screenshot from 2022-05-03 21-03-06](https://user-images.githubusercontent.com/81514969/166514734-c26aee62-af52-4fb3-8b5c-1ea841785e3c.png)
_distrobox-enter's errors with the RHEL UBI-minimal image_

**Comment by 89luca89** [comment]
Hi @MikuOcta 
Do you know of, or point to, a list of those minimal containers using microdnf? So I can test multiple environments

Thanks!

**Comment by MikuOcta** [comment]
@89luca89 As I am aware, only minimal RHEL UBI Images use microdnf. Let me point you to the information from the RedHat website

https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

![Screenshot_20220503-215051_Samsung Internet.png](https://user-images.githubusercontent.com/81514969/166522481-a2832cc6-67da-4971-abbd-0963f6f2d23a.png)

**Comment by MikuOcta** [comment]
@89luca89 As I am aware, only minimal RHEL UBI Images use microdnf. Let me point you to the information from the RedHat website

https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

![Screenshot_20220503-215051_Samsung Internet.png](https://user-images.githubusercontent.com/81514969/166522481-a2832cc6-67da-4971-abbd-0963f6f2d23a.png)

Also, microdnf (even if not installed by default) can be used on other RedHat-like platforms as well, such as Fedora or CentOS Stream

**Comment by 89luca89** [comment]
OK perfect!
Not a problem adding the pkg manager detection, just to check which package names I need
Hopefully it uses the same repos as normal yum/dnf

**Comment by MikuOcta** [comment]
> OK perfect! Not a problem adding the pkg manager detection, just to check which package names I need Hopefully it uses the same repos as normal yum/dnf

Yes it does. microdnf is just a simpler implementation of DNF for containers. Everything should work like DNF in terms of packages.

**Comment by 89luca89** [comment]
Done! :+1:
