### ISSUE TITLE
[Error] Distrobox create --root with Rocky Linux fails with keep-id error

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#267]
## To Reproduce

```shell
distrobox create --root --image docker.io/rockylinux/rockylinux:8 --name rocky
```

## What should happen

It should work.

## What actually happens

Error:

```
Error: keep-id is only supported in rootless mode
```

## Desktop (please complete the following information):
 - OS: Fedora Silverblue
 - Version 36

**Comment by 89luca89** [comment]
Hi @aral thanks for the report!

What `podman` version are you on?

**Comment by 89luca89** [comment]
Oh ok is a new check introduced on April 21: https://github.com/containers/podman/commit/80c0fceb24b70a85f3f2ca8be29f4a131c0881d4 

:smile: 

Adding a check on `create` to work around this

**Comment by 89luca89** [comment]
Fixed in latest commit :+1:

**Comment by aral** [comment]
@89luca89 Thank you :)
