### ISSUE TITLE
[Error]distrobox refused to enter with some apt images

### ISSUE THREAD

**Issue by djypku** [89luca89/distrobox#278]
**Describe the bug**
In some conditions, `distrobox` refused to enter even if all required packages are installed. That is because `distrobox` wants 
```
 ls /etc/profile.d/*vte* |
```
But in some distros or images installing all packages required does not add such file.

**To Reproduce**
Somehow get a image with such problem.(I can give you an example by push to dockerhub if you want.)
Then
```
distrobox create -i xxx -n yyy
distrobox enter yyy
```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 1.2.14

**Else**
1. Logs are lost. I may add them here later.
2. I do not know if 1.2.15 has solve this problem

**Comment by 89luca89** [comment]
Hi @djypku version 1.2.16 solves the problem
Still unreleased you can simply clone from got and use the install script

**Comment by djypku** [comment]
> Hi @djypku version 1.2.16 solves the problem Still unreleased you can simply clone from got and use the install script

Thanks.
