### ISSUE TITLE
[Error]: Themes in $HOME not work

### ISSUE THREAD

**Issue by Dansito** [89luca89/distrobox#279]
**Describe the bug**
Themes installed in $HOME do not work in applications installed in containers

**To Reproduce**
Install fedora silverblue or any distro and then install themes in $HOME and verify that themes in $HOME don't work automatically

**Expected behavior**
It did not work as expected or some detail is missing to make it work

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
![image](https://user-images.githubusercontent.com/84112405/168881180-42199745-d736-426a-b6b5-60e0362945e9.png)

![image](https://user-images.githubusercontent.com/84112405/168881218-42281c71-cf4d-4226-b858-d28e99a865e8.png)

![image](https://user-images.githubusercontent.com/84112405/168881259-4bd5e8ad-c765-45e4-abc7-69bbc80508d2.png)

[podman-logs.txt](https://github.com/89luca89/distrobox/files/8710617/podman-logs.txt)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version: 36

**Additional context**
The talk in the matrix

**Comment by nathanchance** [comment]
Isn't this #253, which is fixed in main with https://github.com/89luca89/distrobox/commit/55bcc2c81200dffe041fe6eb81e21de8a58f3e9e?

**Comment by Dansito** [comment]
Well, it's not "fixed" at least for the moment

**Comment by 89luca89** [comment]
@Dansito did you try with 1.2.16 from `git`?

**Comment by 89luca89** [comment]
@Dansito tried with latest `main` using your same theme and it works both using ~/.themes and ~/.local/share/themes, I'm closing this as it's fixed upstream

**Comment by ludg1e** [comment]
Hello, by some reason on distrobox 1.4.1 this isn't working
