### ISSUE TITLE
[Error] ~/.local/share/fonts owned by "nobody" and not writable. (Doom Emacs can't install icon fonts)

### ISSUE THREAD

**Issue by Aex12** [89luca89/distrobox#294]
**Describe the bug**
I'm trying to use Doom Emacs on Distrobox. I'm using an Archlinux image for the container. The program works flawless, however, the installer is unable to install the custom icon fonts, so icons are missing. Apparently, the installer tries to write font files to the ~/.local/share/fonts folder, but the permission is denied because that folder is owned by "nobody" and doesn't have go+w permissions. 

On the host, the folder ~/.local/share/fonts is owned by me and have a completely different set of files, so I guess this folder is mounted by the image at some point.

**To Reproduce**
Create an Archlinux distrobox, install emacs, then install Doom Emacs.

**Expected behavior**
The folder should be writable by distrobox, so programs can install their own fonts.

**Logs**
This error is thrown by Doom Emacs installer itself:
`Error: (file-error "Opening output file" "Permission denied" "/home/aex12/.local/share/fonts/material-design-icons.ttf")`
using --verbose doesn't produce any further errors on the podman side.

**Desktop (please complete the following information):**
 - OS: Fedora 35 Workstation (Latest updates applied)
 - Version: Linux 5.17.9-200.fc35.x86_64

**Additional information**
After digging a bit more, I've found that /usr/share/fonts is mounted to ~/.local/share/fonts (I guess this is done to archieve font sharing accross distrobox)

**Possible fixes**
Maybe it would be better to mount /usr/share/fonts on ~/.local/share/fonts/system so user fonts are still shared with distroboxes and not just system fonts, and so other programs can install their own user fonts.

**Comment by 89luca89** [comment]
Hi @Aex12 
Version 1.3.0 fixes this, this is the same as #253
