### ISSUE TITLE
[Error] Unable to install GUI apps in Ubuntu containers

### ISSUE THREAD

**Issue by MainKt** [89luca89/distrobox#296]
**Describe the bug**
I'm not able to install GUI apps in Ubuntu containers. I get some systemd errors.

**To Reproduce**
distrobox create -i ubuntu:latest ubuntu
distrobox enter ubuntu
sudo apt install gedit

**Expected behavior**
Successfully install gedit

**Logs**
The error occurs at this point during installation 
```/var/log/journal is a mountpoint
debconf: delaying package configuration, since apt-utils is not installed
Setting up systemd (249.11-0ubuntu3.1) ...
cp: '/etc/resolv.conf' and '/run/systemd/resolve/stub-resolv.conf' are t
he same file
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned 
error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
[PodmanLogs.txt](https://github.com/89luca89/distrobox/files/8824954/PodmanLogs.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.1.0
 - Which version of distrobox? 1.3.0

**Additional context**
It happens only in Ubuntu containers as far as I have seen

**Comment by 89luca89** [comment]
Thanks for the report guys! I can reproduce and I'll craft a fix soon :+1:

**Comment by 89luca89** [comment]
@MainKt @michallepicki can you test the PR i've created? seems to work for me

**Comment by MainKt** [comment]
> 

I'm getting the same error

**Comment by MainKt** [comment]
Yes

**Comment by 89luca89** [comment]
OK can you list here which GUI application you're trying to install? Thanks

**Comment by michallepicki** [comment]
From the issue description:
> sudo apt install gedit

but I'm hitting this when installing other apps as well.

I confirmed an older version of distrobox still works (there are some errors about read-only filesystem but installation succeeds), I'm trying to bisect to find the commit that introduced this issue.

**Comment by 89luca89** [comment]
> I'm trying to bisect to find the commit that introduced this issue.

Thanks a lot!

> there are some errors about read-only filesystem but installation succeeds

Yea they are not fatal
The fix in the PR is working for me, showing some read-only errors (which are fine)

To test the installation `distrobox-init` must be in the same path as where the previous one was 
Because the container "mounts" the init inside so placing it somewhere else won't work

**Comment by michallepicki** [comment]
On https://github.com/89luca89/distrobox/commit/24cdb6ca0e4ec9afc6e132727a79a3bb2a02ca2d `sudo apt install gedit` is succeeding, during installation I'm seeing this:

<pre>Setting up systemd (249.11-0ubuntu3.1) ...
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib
/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /
lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib
/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.ser
vice → /lib/systemd/system/systemd-resolved.service.
ln: failed to create symbolic link &apos;/etc/resolv.conf&apos;: Device or resource busy
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-pstore.service 
→ /lib/systemd/system/systemd-pstore.service.
<font color="#DC322F"><b>fchownat() of /run/systemd/seats failed: Operation not permitted</b></font>
<font color="#DC322F"><b>fchownat() of /run/systemd/sessions failed: Operation not permitted</b></font>
<font color="#DC322F"><b>fchownat() of /run/systemd/users failed: Operation not permitted</b></font>
<font color="#DC322F"><b>fchownat() of /var/lib/systemd/coredump failed: Read-only file system</b></font>
<font color="#DC322F"><b>fchownat() of /tmp failed: Operation not permitted</b></font>
Selecting previously unselected package systemd-sysv.
</pre>

On https://github.com/89luca89/distrobox/commit/87f4a74f4cfb96043dde4459fb498880f53a80f6 `sudo apt install gedit` fails with one of the two above errors (either `cp: '/etc/resolv.conf' and '/run/systemd/resolve/stub-resolv.conf' are the same file` or `cp: cannot create regular file '/run/systemd/resolve/stub-resolv.conf': Permission denied` but as I said I have an unusual setup using nextdns, so it probably depends on whether I have `systemd-resolved.service` enabled and running or not)

The linked PR doesn't change the behavior, it fails the same way for me.

**Comment by 89luca89** [comment]
> The linked PR doesn't change the behavior, it fails the same way for me.

Can you get me the output of:

`cat /etc/apt/apt.conf.d/00_distrobox`

from inside the container?

**Comment by michallepicki** [comment]
> Can you get me the output of:
> `cat /etc/apt/apt.conf.d/00_distrobox`
> from inside the container?

On branch `fix/296`, before installing anything:
<pre>DPkg::Pre-Invoke {&quot;if mountpoint /run/systemd/journal; then umount /run/systemd/journal; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//run/systemd/journal ]; then mount --rbind /run/host//run/systemd/journal /run/systemd/journal; fi&quot;;};
DPkg::Pre-Invoke {&quot;if mountpoint /run/systemd/seats; then umount /run/systemd/seats; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//run/systemd/seats ]; then mount --rbind /run/host//run/systemd/seats /run/systemd/seats; fi&quot;;};
DPkg::Pre-Invoke {&quot;if mountpoint /run/systemd/sessions; then umount /run/systemd/sessions; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//run/systemd/sessions ]; then mount --rbind /run/host//run/systemd/sessions /run/systemd/sessions; fi&quot;;};
DPkg::Pre-Invoke {&quot;if mountpoint /run/systemd/users; then umount /run/systemd/users; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//run/systemd/users ]; then mount --rbind /run/host//run/systemd/users /run/systemd/users; fi&quot;;};
DPkg::Pre-Invoke {&quot;if mountpoint /var/lib/systemd/coredump; then umount /var/lib/systemd/coredump; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//var/lib/systemd/coredump ]; then mount --rbind /run/host//var/lib/systemd/coredump /var/lib/systemd/coredump; fi&quot;;};
DPkg::Pre-Invoke {&quot;if mountpoint /var/log/journal; then umount /var/log/journal; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host//var/log/journal ]; then mount --rbind /run/host//var/log/journal /var/log/journal; fi&quot;;};
</pre>

On main branch ( https://github.com/89luca89/distrobox/commit/c0c0c39c8ad2e7bdb8f3953f9f108f9b106eada9 ):

<pre>DPkg::Pre-Invoke {&quot;if mountpoint /var/log/journal; then umount /var/log/journal; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host/var/log/journal ]; then mount --rbind -o ro /run/host/var/log/journal /var/log/journal; fi&quot;;};</pre>

On a working commit ( https://github.com/89luca89/distrobox/commit/24cdb6ca0e4ec9afc6e132727a79a3bb2a02ca2d ) it's the same as on main:

<pre>DPkg::Pre-Invoke {&quot;if mountpoint /var/log/journal; then umount /var/log/journal; fi&quot;;};
DPkg::Post-Invoke {&quot;if [ -e /run/host/var/log/journal ]; then mount --rbind -o ro /run/host/var/log/journal /var/log/journal; fi&quot;;};</pre>

**Comment by michallepicki** [comment]
I'd like to point out that on a commit that works for me, `/etc/resolv.conf` also fails to mount but it doesn't cause the apt installation to fail:
```
ln: failed to create symbolic link '/etc/resolv.conf': Device or resource busy
```

Somehow https://github.com/89luca89/distrobox/commit/87f4a74f4cfb96043dde4459fb498880f53a80f6 made this issue an installation-failing error.

**Comment by 89luca89** [comment]
@michallepicki @MainKt 
I forgot a path in the fix/296, can you try again with the new commit I've pushed?

**Comment by michallepicki** [comment]
@89luca89 Looking good! Installation succeeded. Here is systemd setup part of `apt install gedit` log, "device or resource busy" is back and doesn't affect the result, and there's only one red error line now about `/tmp` which also doesn't affect the result:

<pre>Setting up systemd (249.11-0ubuntu3.1) ...
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib
/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /
lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib
/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.ser
vice → /lib/systemd/system/systemd-resolved.service.
ln: failed to create symbolic link &apos;/etc/resolv.conf&apos;: Device or resource busy
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-pstore.service 
→ /lib/systemd/system/systemd-pstore.service.
<font color="#DC322F"><b>fchownat() of /tmp failed: Operation not permitted</b></font>
</pre>

**Comment by 89luca89** [comment]
Very good, seems like the fix works

Yea there will be some permission denied stuff, on rootless containers
But should not prevent apt from working

**Comment by MainKt** [comment]
Thank you very much :)

**Comment by 89luca89** [comment]
Thanks to both of you for reporting and helping debug!
