### ISSUE TITLE
[Error] MODULE_VERSION: parameter not set

### ISSUE THREAD

**Issue by loftyhauser** [89luca89/distrobox#298]
I'm trying to use distrobox on a Linux Mint 20.2 machine (based on Ubuntu 20.04).  I've used distrobox from git (latest) and tag 1.30, as well as the version from the Ubuntu PPA.  I've tried installing containers for Fedora 36, CentOS 7 and Ubuntu 20.04, and keep getting the same error.  After installing the container, and running 'distrobox-enter', the container appears to update correctly, but then:

done!
/usr/bin/distrobox-enter: 1: eval: MODULE_VERSION: parameter not set

An error occurred

Given that I get the same error regardless of the distrobox version and container OS, it appears to be a problem with my host OS.  I have no idea what MODULE_VERSION is, or how to troubleshoot -- any ideas? (I have dkms installed on the machine for VirtualBox kernel modules; this is the only thing that I can think of...)

Thanks!

**Comment by 89luca89** [comment]
Hi, can you do a `echo $MODULE_VERSION` on the host?

**Comment by 89luca89** [comment]
Also generally if you can the output of `env` on the host

**Comment by loftyhauser** [comment]
echo $MODULE_VERSION is empty (not set).  The whole environment is:

SHELL=/bin/bash
SESSION_MANAGER=local/moroni:@/tmp/.ICE-unix/1572,unix/moroni:/tmp/.ICE-unix/1572
WINDOWID=96468995
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-xfce:/etc/xdg:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_MENU_PREFIX=xfce-
CLUTTER_BACKEND=x11
LANGUAGE=en_US
SSH_AUTH_SOCK=/tmp/ssh-8d0gvMVP9eY2/agent.1572
GIT_PS1_SHOWDIRTYSTATE=true
DESKTOP_SESSION=xfce
SSH_AGENT_PID=1662
GTK_MODULES=gail:atk-bridge
KRB5_CONFIG=/usr/local/krb5/etc/krb5.conf
XDG_SEAT=seat0
ENV=/usr/share/modules/init/profile.sh
PWD=/home/alofthou
GSETTINGS_SCHEMA_DIR=/home/alofthou/data
LOGNAME=alofthou
XDG_SESSION_DESKTOP=xfce
QT_QPA_PLATFORMTHEME=qt5ct
XDG_SESSION_TYPE=x11
MODULESHOME=/usr/share/modules
MANPATH=:
XAUTHORITY=/home/alofthou/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/alofthou
GDM_LANG=en_US
HOME=/home/alofthou
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=XFCE
VTE_VERSION=6003
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
LESSCLOSE=/usr/bin/lesspipe %s %s
MODULEPATH_modshare=/etc/environment-modules/modules:1:/usr/share/modules/$MODULE_VERSION/modulefiles:1:/usr/share/modules/modulefiles:1:/usr/share/modules/versions:1
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=alofthou
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
LOADEDMODULES=
DISPLAY=:0.0
SHLVL=1
BASH_ENV=/usr/share/modules/init/bash
XDG_VTNR=7
XDG_SESSION_ID=c2
XDG_RUNTIME_DIR=/run/user/1000
COMPIZ_CONFIG_PROFILE=mint
GTK3_MODULES=xapp-gtk3-module
XDG_DATA_DIRS=/usr/share/xfce4:/home/alofthou/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/usr/share
PATH=/home/alofthou/local/distrobox/bin:/home/alofthou/local/cmake/3.23/bin:/home/alofthou/local/vim/8.2.4643/bin:/usr/local/ossh/bin:/usr/local/krb5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/share/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
GDMSESSION=xfce
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GIT_PS1_SHOWUNTRACKEDFILES=true
GIO_LAUNCHED_DESKTOP_FILE_PID=2867
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/xfce4-terminal.desktop
OLDPWD=/home/alofthou
MODULES_CMD=/usr/lib/x86_64-linux-gnu/modulecmd.tcl
_=/usr/bin/env

**Comment by 89luca89** [comment]
This is a problem with Linux Mint:

In your env you have 

`MODULEPATH_modshare=/etc/environment-modules/modules:1:/usr/share/modules/$MODULE_VERSION/modulefiles:1:/usr/share/modules/modulefiles:1:/usr/share/modules/versions:1`

This refers to `$MODULE_VERSION` which is not declared

Either you have to declare MODULE_VERSION in your ~/.bashrc or your ~/.profile or in /etc/profile
Or you raise this to Mint developers to have this sorted out
Even leaving it empty, just declaring it:

`export MODULE_VERSION=""`

**Comment by loftyhauser** [comment]
Ah, got it.  That's an easy fix.  Leaving it empty (export MODULE_VERSION="") seems to work.  Thanks!

**Comment by 89luca89** [comment]
Cool!
