### ISSUE TITLE
[Suggestion] Clean up exported apps when removing container

### ISSUE THREAD

**Issue by michallepicki** [89luca89/distrobox#301]
Currently when `distrobox-export` was used from inside a container, and this container is being removed with `distrobox rm` on the host without running `distrobox-export -d` first, there are leftover files on the host system.

**Describe the solution you'd like**
Before removing the container, there could be additional logic to check if there were any apps exported from it, and clean them up from the host system.

**Comment by 89luca89** [comment]
That's a really good idea :+1:

**Comment by PgBiel** [comment]
Just my two cents here, but perhaps a storage file of sorts could be kept by distrobox in some system folder such that it always knows which apps it has exported and which files it created for each one?

That would certainly simplify the logic necessary to implement auto-cleaning exports on distrobox removal, and even allow for removing exports after the container was deleted and/or without having to enter the container, I believe

**Comment by 89luca89** [comment]
This has already been implemented
