### ISSUE TITLE
[Error] flatpak install fails from within rootful container on Fedora Silverblue

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#303]
**Describe the bug**

Trying to run `flatpak install` from within a rootful container (tried with Ubuntu and Arch) fails with read-only file system error:

```
❯ sudo flatpak install flathub org.winehq.Wine/x86_64/stable-21.08 org.freedesktop.Sdk/x86_64/21.08

Looking for matches?
error: Unable to load summary from remote flathub: Error opening file ?/var/lib/flatpak/repo/tmp/cache/summaries/flathub.idx?: Read-only file system
```

**To Reproduce**

I was following the instructions at https://github.com/gjpin/itch-flatpak

**Expected behavior**

flatpak should work from within containers.

**Logs**

n/a

**Desktop (please complete the following information):**

 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.10
 - Which version of distrobox? 1.2.16

**Comment by 89luca89** [comment]
Hi @aral

if you see here, I've set some instructions on how to fulfill your use case:

https://distrobox.privatedns.org/useful_tips.html#use-distrobox-to-install-different-flatpaks-from-the-host

**Comment by 89luca89** [comment]
Also just an heads up, version 1.2.16 suggests me that you have an installation from `git` itself, probably better upgrade it now, we're at 1.3.x now :smile:

**Comment by 89luca89** [comment]
Hi @aral did you have time to check if the suggested doc worked?

**Comment by aral** [comment]
@89luca89 Sorry, Luca, I haven’t had the chance but I don’t see why it wouldn’t work. Please feel free to close this and I can reopen it later in case it doesn’t :)

**Comment by 89luca89** [comment]
I've tested this for you to ensure it was still working and it works 😄 if you encounter problems with the docs above, we can reopen the issue, no problems!
