### ISSUE TITLE
[Error] Unable to login to containerized KDE plasma through GDM on host Fedora Silverblue

### ISSUE THREAD

**Issue by MainKt** [89luca89/distrobox#309]
**Describe the bug**
The distrobox plasma's login option in GDM doesn't work

**To Reproduce**
https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md#running-latest-plasma on host Fedora Silverblue

**Expected behavior**
Login to Plasma

**Logs**
when I tried `startplasma-wayland` in tty, inside the container, I got `kwin_xwl: /tmp/.X11-unix is not owned by root or us`

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.1.0
 - Which version of distrobox? 1.3.0

**Additional context**
I think it's due to the ownership of `/tmp/.X11-unix` in Fedora Silverblue

**Comment by 89luca89** [comment]
Yes as stated in the article itself:

```
First in the host we need a reliable way to fix the permissions problem of the /tmp/.X11-unix directory. This directory should either belong to root or $USER. But in a rootless container, host's root is not mapped inside the container so we need to change the ownership from root to $USER each time.
```

Probably the profile is not working, maybe wrapping the `startplasma-wayland` in a script that first sets up the permissions?

**Comment by MainKt** [comment]
I was a bit confused. Thank you for the clarification

**Comment by pulkitkrishna00** [comment]
@MainKt I am facing the same problem. How did you solved it?
