### ISSUE TITLE
[Error] distrobox-export doesn't pass --root on rootful containers

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#313]
**Describe the bug**

Exporting an application with `distrobox-export` on a rootful container doesn't pass `--root` to the generated desktop file.

**To Reproduce**

1. `distrobox create --root test`
2. `distrobox enter --root test`
3. `distrobox-export --app example`
4. On the host: `grep Exec ~/.local/share/applications/test-example.desktop`

**Expected behavior**

The `.desktop` to be generated with `Exec=/usr/bin/distrobox-enter --root -n test -- 'example'`

**Actual behavior**

The `.desktop` is generated with the following line: `Exec=/usr/bin/distrobox-enter -n test -- 'example'`

**Additional context**

Either `distrobox-export` should able to tell when a container is rootful and append `--root` to the .application file by itself, or please add a `--root` option to `distrobox-export`.

**Comment by 89luca89** [comment]
You're right! Fixed!
