### ISSUE TITLE
[Error] Authorization required, but no authorization protocol specified

### ISSUE THREAD

**Issue by LarsHaalck** [89luca89/distrobox#316]
**Describe the bug**
Starting a GUI Application inside rootless podman (but I guess other setups are also affected), the following error arises:
```
Authorization required, but no authorization protocol specified
Error: Can't open display: :0
```
which can also happen with Toolbox as stated in the [Arch Wiki](https://wiki.archlinux.org/title/Toolbox#X11_Apps_Not_Working)

**To Reproduce**
Given a simple `xauth` setup with only one entry like
```
<MY_HOSTNAME>/unix:0  MIT-MAGIC-COOKIE-1 <SOMETHING>
```
Running a GUI application:
```
distrobox create --image ubuntu:22.04 --name u22
distrobox enter --name u22
sudo apt install x11-apps
xclock
```
results in the error above.

**Fix**
Run 
```
xauth add "$(boxname).$(hostname)/unix$DISPLAY" . "$(xauth list | grep "^$(hostname)/unix$DISPLAY\s*MIT-MAGIC-COOKIE-1\s*" | awk '{print $3}')"
```
where `boxname=u22` in the case above.

**Expected behavior**
Run the GUI application

**Desktop (please complete the following information):**
 - podman 4.1.0
 - distrobox [d8bfce15a8975aa1c28c3615db6bb478677a2c18]

**Additional context**
Arch Linux with i3 and lightdm

I don't know if this is a bug per se, but I think it would help new users to state the "fix" to this problem somewhere, but maybe I was just blind.

**Comment by 89luca89** [comment]
Could it be related to this?

https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes

**Comment by LarsHaalck** [comment]
Okay so just blind. Thanks.

`xhost +si:localuser:$USER` also works for me, and I don't know enough about X access control to understand the difference. 

Maybe this note could be added someplace else, because I think it is quite difficult to find.

**Comment by 89luca89** [comment]
Sure, if you find a way to expose better the docs feel free to open an issue or a Pull Request :smile:

**Comment by RashiqAzhan** [comment]
Hi @89luca89. Sorry for bumping this. I'm running into the same issue.

Running the command results in `access control disabled, clients can connect from any host` for me. Adding `sudo` doesn't change the output.

Anyone got any ideas?

**Comment by juan11iguel** [comment]
> Okay so just blind. Thanks.
> 
> `xhost +si:localuser:$USER` also works for me, and I don't know enough about X access control to understand the difference.
> 
> Maybe this note could be added someplace else, because I think it is quite difficult to find.

I also faced this issue and only found this command that worked in this closed issue after a lot of digging. Maybe this should be added back to the docs?

**Comment by cyberalt1** [comment]
Tried all that and it did not work, please reopen this issue because it's breaking all usage of distrobox
