### ISSUE TITLE
[Error] Ubuntu Image VSCode Install results in resolv.conf problem

### ISSUE THREAD

**Issue by maxfridbe** [89luca89/distrobox#319]
**Describe the bug**
I'm not sure this belongs here, but vscode team seems to think distrobox caused this.

When making a ubuntu latest box and installing vscode the apt manager goes weird with resolv.conf issues and is no longer usable, not even sure how to fix it.  cannot install even one package after this occurs.

Anything you can do to shed light on this would be appreciated.

**To Reproduce**
Make an ubuntu:latest and follow ubuntu instructions here: https://code.visualstudio.com/docs/setup/linux

**Expected behavior**
Should work, not sure if its a distrobox alias thing or what.

**Logs**

>     debconf: delaying package configuration, since apt-utils is not installed Setting up systemd (249.11-0ubuntu3.1) ... cp: '/etc/resolv.conf' and '/run/systemd/resolve/stub-resolv.conf' are the same file dpkg: error processing package systemd (--configure): installed systemd package post-installation script subprocess returned error exit status 1 Errors were encountered while processing: systemd E: Sub-process /usr/bin/dpkg returned an error code (1)

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - podman
 - Which version of distrobox?
 - just installed latest

**Additional context**
I  am running Fedora SilverBlue 36

**Comment by maxfridbe** [comment]
@89luca89 Sure, im sorry im like 40% on what to do to install 1.3.1, I installed distrobox via

> curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

is there a similar command i could use to load 1.3.1

**Comment by misobarisic** [comment]
>  curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
> 
Yup, that's the correct way to install the latest commit version

**Comment by 89luca89** [comment]
> > curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
> 
> Yup, that's the correct way to install the latest commit version

Nope that will install the latest **release**

Thinking of which, it will be handy to add a "--next" flag that installs latest commit 🤔 



> @89luca89 Sure, im sorry im like 40% on what to do to install 1.3.1, I installed distrobox via
> 
> > curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
> 
> is there a similar command i could use to load 1.3.1

You will need to either use git or download the last sources from the green "code" button, unzip it, and from inside the directory launch `./install` or `sudo ./install`

**Comment by maxfridbe** [comment]
Yup that worked! thanks, sorry didn't realize that distrobox is a collection of scripts. and I can just clone the latest!  Thank you so much for even bothering to respond.

**Comment by misobarisic** [comment]
> Thinking of which, it will be handy to add a "--next" > flag that installs latest commit 🤔 

Indeed. Would bea QoL improvement
