### ISSUE TITLE
[Error] Cloning does not work if default image is specified in configs

### ISSUE THREAD

**Issue by PgBiel** [89luca89/distrobox#320]
**Describe the bug**
Using `distrobox` 1.3.0 installed from the OpenSUSE Tumbleweed (snapshot 20220609-0) repo, I cannot clone distrobox containers.
When I run (for example - `InnerUbuntu` is the name of my Ubuntu 22.04 distrobox container)
```bash
distrobox-create --name UbClone --clone InnerUbuntu
```

The output is
```bash
Error: Invalid arguments, choose only one between clone or image name.

An error occurred
```

Which left me confused, as I am not specifying any image name (I clearly didn't specify the `--image` parameter at all).

Running a normal `distrobox-create` without any parameters proceeded to prompt me to download the image `registry.opensuse.org/opensuse/tumbleweed:latest`, which suggested that the image parameter was defaulting to that.

Analysing the code of the command `distrobox-create`, I was pointed to possible config file locations that could be overriding the image parameter, and I found the file `/etc/distrobox/distrobox.conf` in my system, with the following contents:

```bash
container_image="registry.opensuse.org/opensuse/tumbleweed:latest"
container_name="tumbleweed"
container_manager="autodetect"
```
The `container_image` variable in this conf file seemed to match the variable used to hold the value of the `--image` parameter in the `distrobox-create` script code. And indeed, running the same command with verbose toggled on (running `distrobox-create --name UbClone --clone InnerUbuntu --verbose`), I got

```
+ '[' -n InnerUbuntu ']'
+ '[' -n registry.opensuse.org/opensuse/tumbleweed:latest ']'
+ printf 'Error: Invalid arguments, choose only one between clone or image name.\n'
Error: Invalid arguments, choose only one between clone or image name.
+ exit 2
+ '[' 2 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
```

which indicated that the `if` that checked if both `--clone` and `--image` were simultaneously passed was being triggered with `InnerUbuntu` (the name of the container I wish to clone) and with the image link in the `/etc/distrobox/distrobox.conf` file.

To further confirm this, I ran `sudo mv /etc/distrobox/distrobox.conf /etc/distrobox/distrobox.conf.old`, which **solves this particular issue** (after running this `mv` command to hide the conf file from the script, I can run `distrobox-create --name UbClone --clone InnerUbuntu` and it initiates the cloning process) - but, of course, hiding the conf file has side-effects (the OpenSUSE Tumbleweed default values for parameters are no longer there, and must be specified manually, which could or could not be an issue for certain users).

So, I believe that, to fix this issue, perhaps some check should be put in place to verify the source of the `container_image` and `container_clone` variables in the `distrobox-create` script. Maybe if `--clone` is specified through the CLI, the code should ignore `container_image` specified through config files, and vice-versa (ignore `container_clone` from conf files if `--image` is specified), or something like that (and also maybe have a hierarchy of conf files, such that `container_clone` in a conf file in the home directory would invalidate `container_image` in a conf file in a system directory - just some thoughts). After all, if one of the two variables isn't ignored, the script just breaks. (But there could be possibly other ways to fix this.)

Please do tell me if this bug would be better reported to OpenSUSE maintainers instead (however, I felt that it was appropriate to post this here first).

**EDIT:** I also found that, even if the config file issues are fixed (even with my `mv` fix), it seems that clone doesn't work with container names that have uppercase characters (such as my `InnerUbuntu` - I ran `distrobox-create --name ubclone --clone InnerUbuntu`, which returned the logs below).

```
Duplicating InnerUbuntu...
Error: repository name must be lowercase
Cannot clone container: InnerUbuntu

An error occurred
```

(Logs with `--verbose`: https://paste.opensuse.org/d6d29af7)

However, after the `mv` fix, clone works just fine with container names that are entirely lowercase (it worked with a container named `testbuntu`).
(Should I open another issue for this?)

**To Reproduce**
1. Install `distrobox` on OpenSUSE Tumbleweed from the distro's official OSS repo through `sudo zypper install distrobox` (this should occur with both `podman` and `docker`; in my case, I installed `podman` through `sudo zypper install podman`)
2. Create a container; e.g. through `distrobox-create -n UbuntuContainer -i docker.io/library/ubuntu:22.04`
3. Attempt to clone the container; e.g. through `distrobox-create --name UbuntuContClone --clone UbuntuContainer`
4. It fails with `Error: Invalid arguments, choose only one between clone or image name.`

**Expected behavior**
Normally, distrobox would clone the container without errors.

**Logs**
As specified above, the result of `distrobox-create --name UbClone --clone InnerUbuntu --verbose` is

```
+ '[' -n InnerUbuntu ']'
+ '[' -n registry.opensuse.org/opensuse/tumbleweed:latest ']'
+ printf 'Error: Invalid arguments, choose only one between clone or image name.\n'
Error: Invalid arguments, choose only one between clone or image name.
+ exit 2
+ '[' 2 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
```

Also, when fixing that particular error (by hiding system-wide config that overrides the image name parameter), I get another error regarding the container name having uppercase characters - full logs with `--verbose` (with some `<SNIP>`'d possibly sensitive info) are here: https://paste.opensuse.org/d6d29af7

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.0.3-3.1
 - Which version of distrobox? 1.3.0-1.1

**Comment by 89luca89** [comment]
Hi @PgBiel 
thanks for discovering the bug!

The problem here is not OpenSUSE specific, it's a but in the configuration logic
I'll craft a fix soon :+1:

Changing the title to reflect the general problem

**Comment by 89luca89** [comment]
> So, I believe that, to fix this issue, perhaps some check should be put in place to verify the source of the container_image and container_clone variables in the distrobox-create script. Maybe if --clone is specified through the CLI, the code should ignore container_image specified through config files,

That's exactly what already happens

I'll just remove the check that blocks execution if `--image` and `--clone` are specified, and simply let the script ignore `--image` in case of `--clone`

**Comment by 89luca89** [comment]
@PgBiel the fix has been pushed

**Comment by PgBiel** [comment]
> @PgBiel the fix has been pushed

Thank you very much @89luca89 for the extremely quick fix!!! Now that's a great maintainer!

Do you suggest I open another issue for the lowercase/uppercase naming errors I found as well? (In the "EDIT:" section of the issue)
(Maybe that's intentional behavior, but I just want to make sure :p)

**Comment by 89luca89** [comment]
> > @PgBiel the fix has been pushed
> 
> Thank you very much @89luca89 for the extremely quick fix!!! Now that's a great maintainer!
> 
> Do you suggest I open another issue for the lowercase/uppercase naming errors I found as well? (In the "EDIT:" section of the issue) (Maybe that's intentional behavior, but I just want to make sure :p)

This has sadly to do with podman and how it handles the names
I've pushed another commit that fixes this, I've just did a release so this will be part of 1.3.2 in the future. For now you can install from latest git commit using the option `--next` in the install command

**Comment by PgBiel** [comment]
Ohhh, alright! Thank you very much for the speedy fix once again, and also thank you for the amazing project! :+1:
