### ISSUE TITLE
[Suggestion] Provide a better alternative to flatpak-spawn --host

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#321]
**Is your feature request related to a problem? Please describe.**

`flatpak-spawn --host` is a nice convenience to be able to run programs on the host machine from inside the toolbox. But it has some major shortcoming, such as not correctly passing through the tty devices, so not all programs can be run cleanly using this tool.

An example of these shortcomings is if you try to open a shell on the host, and run sudo.

```
toolbox:~ % flatpak-spawn --host bash
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[sph@host ~]$ sudo -i
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
^Csudo: a password is required
```

**Describe the solution you'd like**

AFAIK it is possible to write an alternative to `flatpak-spawn --host` that directly interacts with Flatpak DBus portal to avoid all this shortcomings. Though this alternative does not exist yet, I would like Distrobox to ship with such an alternative to provide a seamless experience. 

Here's the Tilix terminal emulator spawning a command on the host through DBus: https://github.com/gnunn1/tilix/blob/5008e73a278a97871ca3628ee782fbad445917e7/source/gx/tilix/terminal/terminal.d#L2963

I know this is quite complicated, but I think distrobox would benefit if people can access their host machine without any compromise. 

**Additional context**

A collection of issues about flatpak-spawn --host: 

* https://github.com/flatpak/flatpak-xdg-utils/issues/57
* https://github.com/flatpak/flatpak/issues/3697
* https://github.com/flatpak/flatpak/issues/3285

**Comment by 89luca89** [comment]
Thanks @1player for the suggestion
Indeed both `flatpak-spawn` and `chroot` inside `distrobox-host-exec` have their own limitations
This is also because the point of having a container... well is not exiting a container :joy:  so obviously is not a simple thing

Creating an alternative to flatpak-spawn is not in the scope of the project, but I'll keep this open in case we can come up with other ideas :+1:  or if someone wants to fix stuff upstream in flatpak-spawn :+1:

**Comment by 1player** [comment]
I've been working on a better `flatpak-spawn --host` alternative which fixes the issues mentioned above: https://github.com/1player/host-spawn

Needs a little more work, but already handles creating a pty for the spawned process, which is the reason `flatpak-spawn --host` causes those pty error with some commands, and passes through SIGWINCH signals, so handles terminal size changes.

**Comment by 89luca89** [comment]
> I've been working on a better `flatpak-spawn --host` alternative which fixes the issues mentioned above and a couple more: https://github.com/1player/host-spawn

Very good I'll check it!
If anything it would be nice to either embed something like this in the project or make this upstream

**Comment by 1player** [comment]
> If anything it would be nice to either embed something like this in the project or make this upstream

Feel free to embed it or we can discuss any change you'd need before integrating into distrobox. I'm not opposed to the idea.

**Comment by 89luca89** [comment]
I was thinking, it could live in its own repo, and be curl/wget installed during init
I don't think it would fit in this very repo as it would require compilation, and other stuff to work

Living in another repo (`distrobox-host-exec`? so it replaces the existing utility) and providing builds for the various libc and architectures could work

**Comment by 1player** [comment]
I like those fixes, I'm happy with a PR, giving you commit permissions, or better yet, move it to a `distrobox` Github org. What do you think?

**Comment by 89luca89** [comment]
@1player 

opened a PR to fix this issue, for now I'm using binaries from my fork, if you start a release, and come up with a versioning scheme I'll follow that and switch the download to your repo, let me know :+1:

**Comment by 1player** [comment]
I've tagged 1.0.1 with your changes. I'll use a semver versioning scheme.

**Comment by 89luca89** [comment]
Perfect, I'll fix a version for each distrobox release, and stick with it, see how I've updated the PR :+1: 
This way we can also auto-update host-spawn when a new version is released, granted it will be updated only when distrobox itself is updated (via distrobox-host-exec)

**Comment by 1player** [comment]
Sounds great. 

Honestly the only thing I have planned for host-spawn is the symlinking trick I mentioned in #343 i.e. being able to do `ln -s /usr/local/bin/host-spawn /usr/local/bin/podman`. You might want to integrate the same thing into `distrobox-host-exec`, but I can't give you a date when I'll have it done, so if you want to cut a new release of distrobox, go ahead.
