### ISSUE TITLE
[Error] distrobox-enter does not properly parse arguments with space

### ISSUE THREAD

**Issue by cheese** [89luca89/distrobox#322]
**Describe the bug**
What `distrobox-enter` does:
```
$ distrobox-enter --no-tty --no-workdir mockbuild-container -- ls ' ll dfdf'
ls: cannot access 'll': No such file or directory
ls: cannot access 'dfdf': No such file or directory
```

The expected result as of `docker exec`
```
$ docker exec mockbuild-container ls ' ll dfdf'
ls: cannot access ' ll dfdf': No such file or directory
```

**To Reproduce**
`distrobox-enter --no-tty --no-workdir mockbuild-container -- ls ' ll dfdf'`

**Expected behavior**
The same as `docer exec` 

**Logs**
Easy to reproduce

**Desktop (please complete the following information):**
 - Are you using podman or docker? docker
 - Which version or podman or docker? Docker version 20.10.16, build aa7e414
 - Which version of distrobox? 1.3.1

**Additional context**

**Comment by 89luca89** [comment]
Hi @cheese 
this is covered in the docs here: https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#execute-complex-commands-directly-from-distrobox-enter

this is mainly due to how arguments are passed from a script (distrobox) to the main process (podman/docker)

If you escape the quotes, it will work:

` distrobox-enter --no-tty --no-workdir mockbuild-container -- ls \' ll dfdf\'`

**Comment by 89luca89** [comment]
@cheese any news on this?

**Comment by cheese** [comment]
As a toolbox/docker/podman user, it is inconvenient that arguments need extra escaping.

**Comment by 89luca89** [comment]
Yea I agree, but sadly that's a limitation on using `shell` as an implementation
Quotes (unescaped) are evaluated at runtime and the script (enter, create, all of them) just receive the string already stripped of quotes

In this example:

```sh
#!/bin/sh

printf ' %s' ${@}
```

you can see that running it already removes all of the quotes:

```console
~$ sh /tmp/test "hi how are you\"" a b c
 hi how are you" a b c
 ```
 
 So escaping is needed in this case

**Comment by 89luca89** [comment]
@cheese closing this as this cannot be solved due to `sh` limitations
