### ISSUE TITLE
[Suggestion] support kerberos

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#323]
**Is your feature request related to a problem? Please describe.**
It would be nice to have working host kerberos in distrobox toolboxes, like toolbox provides.

**Describe the solution you'd like**
I guess this requires bind mounting some kerberos files into distrobox containers if they exist.

**Comment by 89luca89** [comment]
Hi @juhp ! Nothing against this, I'm not very familiar with kerberos, is there already a list of files involved in this?

**Comment by 89luca89** [comment]
@juhp 
Cool, added to latest commit, can you test if this works for you?

After upgrading you'll need to `stop` the container, and enter again, so that init will run again and create the file

**Comment by juhp** [comment]
Cool, thanks - yes it works for me!

**Comment by 89luca89** [comment]
Cool! :+1:
