### ISSUE TITLE
[Error] Can not run any graphical application.

### ISSUE THREAD

**Issue by stafpapa** [89luca89/distrobox#329]
**Describe the bug**
Can not run any graphical application.

**To Reproduce**
On Manjaro linux KDE (on virtualbox, and I do not know if this is relevant or not):
distrobox-create --name arch-distrobox --image archlinux:latest --root
distrobox enter --root arch-distrobox
sudo pacman -Sy kate
kate
> Note, I get the same error regardless of using the flag `--root`

**Expected behavior**
Should open the graphical interface

**Logs**
Authorization required, but no authorization protocol specified

qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)

**Desktop (please complete the following information):**
 - Are you using podman or docker? I get the same error with both
 - Which version or podman or docker? Podman 4.1.0
 - Which version of distrobox? 1.3.1

**Comment by misobarisic** [comment]
You need to have `xhost` running on the host. You also need to run `xhost +` to grant yourself appropriate priviledges.

**Comment by stafpapa** [comment]
Thank you. This solved the issue.
