### ISSUE TITLE
[Suggestion or Bug, not sure] distrobox-export --app not working for .desktop files in ~/.local/share/applications

### ISSUE THREAD

**Issue by afland** [89luca89/distrobox#337]
I have a fedora 36 container set up with its own home directory. distrobox-export --app [app] isn't working for .desktop files located in ~/.local/share/applications instead of the typical /usr/local/share. I'm not sure if that's a bug on my end, or if the command simply doesn't search the .local/share/applications directory.

If the latter is true, it would be great if ~/.local/share/applications were added to the paths distrobox-export --app searches for .desktop files in

**Comment by 89luca89** [comment]
Duplicate of #297

**Comment by afland** [comment]
> Duplicate of #297

unless I'm missing something, that doesn't look like a duplicate to me

**Comment by 89luca89** [comment]
Well that one covers this
Now there is support to export apps in that directory
