### ISSUE TITLE
[Error] Container with root + init logs out host user when first running distrobox enter

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#344]
## Summary 

I have an Ubuntu 22.04 container created with `--root` and `--init` options. When I first enter it, it logs out my Fedora host user.

After signing back in, things work as they should.

## To Reproduce

1. Create an Ubuntu 22.04 container, passing `--root --init` as options.

2. Enter the container (e.g., `distrobox-enter --root --name ubuntu-22.04-root-init`). In my setup I pass `distrobox-enter --root --name ubuntu-22.04-root-init -- fish` as I use fish shell.

## What should happen 

The container should start without logging out the host user.

## What actually happens

The host user is logged out.

## Workaround

After logging back in (at which point, you will have lost any state you had in your previous session), you can enter the container.

## Desktop (please complete the following information):**
 - Are you using podman or docker? __Podman__
 - Which version or podman or docker? __4.1.0__
 - Which version of distrobox? __1.3.1__
 - Host OS: Fedora Silverblue 36

**Comment by 89luca89** [comment]
Hi @aral 

this is indeed fixed in 1.3.2, starting from commit https://github.com/89luca89/distrobox/commit/b79564659646368253c6f844641bc41a6718f0ec

So could you try it with latest version from git? I've had this exact same bug and that commit fixed it

**Comment by aral** [comment]
@89luca89 Hey Luca, my bad, sorry. Should’ve pulled and `./install`ed before reporting. As you said, it works perfectly in 1.3.2 (latest from main). Closing.

**Comment by 89luca89** [comment]
Great, glad all is working 😄

**Comment by vitedevs** [comment]
I'm on v. 1.6.0.1 and have the exact same problem.
