### ISSUE TITLE
[Suggestion] distrobox-list should suppress colour when attached to a pipe

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#352]
**Is your feature request related to a problem? Please describe.**
I love the colored output of distrobox-list.
But if I run `distrobox-list | ...` then the colour control codes are still passed out.

**Describe the solution you'd like**
How about suppressing coloured output when stdout of distrobox-list is attached to a pipe?

**Additional context**
It seems this can be detected like this, for example:
```shell
if [ -t 1 ] ; then echo terminal; else echo "not a terminal"; fi
```

**Comment by 89luca89** [comment]
@juhp great idea! Implemented :+1:

**Comment by juhp** [comment]
Wow thank you @89luca89, so fast!
