### ISSUE TITLE
[Discussion] running distrobox inplace

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#354]
I like to run the latest distrobox directly from git.
Also I am lazy so I setup short alias symlinks:

~/bin/db-enter -> ~/src/distrobox/distrobox-enter

etc.

However this hack doesn't work quite 100% (though mostly (~95%) it is fine for me).
Today I noticed that after using db-create, db-enter failed:

`Error: invalid arguments "", "eln-distrobox:/usr/bin/distrobox-host-exec": you must specify paths`

Anyway a quick workaround was just to use `/usr/bin/distrobox-enter` to setup the container,
and then my `db-enter` started working normally.
I guess I am not quite "doing this right" (probably my hack is not the intended way to do this...).

So any suggestions how this could work better (I see the `install` script, so I could just run it I guess, though would prefer not).

This is the little script I use to generate my symlinks:
```bash
#!/bin/sh

BINDIR=$HOME/bin
TOPDIR=$(readlink -e $(dirname $0))

for i in distrobox-*; do
    ln -s $TOPDIR/$i $BINDIR/$(echo $i | sed s/distrobox/db/)
done

ln -s $TOPDIR/distrobox $BINDIR/
```

*Describe the solution you'd like*
It would be nice if symlinked distrobox* worked out of the box,
and eg if fresh distrobox-enter could locate distrobox-host-exec better.
If the only sane answer is to use `./install` that's fine too I guess,
but just wondered if there was some other way approach this?
On the other hand supporting this might be too complicated perhaps.

*Describe alternatives you've considered*
Earlier I had this local hack just for distrobox:

```bash
modified   distrobox
@@ -49,7 +49,7 @@
 
-distrobox_path="$(dirname "${0}")"
+distrobox_path="$(dirname $(readlink ${0}))"
 distrobox_command="${1}"
 shift
```

**Comment by 89luca89** [comment]
I'll need to test this out, i think with the new way of setting up the entry point and other distrobox utilities added in commit https://github.com/89luca89/distrobox/commit/52a34fbd52e1f0f035657b167ebe997d41db0993
We could be able to bring back realpath/readink

**Comment by 89luca89** [comment]
@juhp any news on this? did this work after commit https://github.com/89luca89/distrobox/commit/52a34fbd52e1f0f035657b167ebe997d41db0993 changes?

**Comment by juhp** [comment]
Sorry for the slow reply (I wasn't sure from your comment in July if something more was needed).

So I just tried now:

```shellsession
$ db-create -i fedora:37
:
$ db-enter fedora-37
Container fedora-37 is not running.
Starting container fedora-37
run this command to follow along:

 podman logs -f fedora-37

Error: invalid arguments "", "fedora-37:/usr/bin/distrobox-host-exec": you must specify paths

An error occurred
```

With verbose output, it ended with:
```
:
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 25             
Error: invalid arguments "", "fedora-37:/usr/bin/distrobox-host-exec": you must specify paths
+ '[' 125 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
+ rm -f '/var/home/petersen/.cache/.*.fifo' '/var/home/petersen/.cache/.*.status'
```

Then I ran `distrobox-enter fedora-37` and the `db-enter` symlink starts to work okay.

**Comment by 89luca89** [comment]
Right, tested this and with `realpath` works as intended
This should not pose a problem for NixOS too as now we copy a new version of the file (instead of mounting it) so it should survive path changes

**Comment by juhp** [comment]
I might have run into a small problem with rm now:

```shellsession
$ db-rm fedora-37
Do you really want to delete fedora-37? [Y/n]: 
/var/home/petersen/bin/db-rm: line 247: /var/home/petersen/bin/distrobox-generate-entry: No such file or directory
```

I could probably add a symlink for distrobox-generate-entry to workaround, but maybe something can be tweaked in distrobox-rm to handle this?

**Comment by 89luca89** [comment]
@juhp yea now should work, didn't include the `realpath` for it like for the other tools :+1:
