### ISSUE TITLE
[Suggestion] Add the option to install only scripts or docs

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#357]
The installer currently always installs everything. Would it not be better to have a set of flags such as `--only-docs`, `--only-scripts` or `--no-docs`, `--no-scripts` to make the installation more particular?

**Comment by 89luca89** [comment]
Not sure why one should need this, as docs are (for me) part of the package itself
It would result in potentially rouge installations, like docs and scripts at different versions and so on, which would make support and bug reporting more difficult
