### ISSUE TITLE
[Discussion] Is there a way to change a toolbox shell?

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#359]
I created a toolbox ages ago and it's running on zsh. Distrobox has set the env variable SHELL=/usr/bin/zsh

Now I want to use fish. There doesn't seem to be a way for podman to update variables of an existing containers, so do I have to recreate the toolbox entirely? That would be really annoying.

Is there a reason why $SHELL is passed to the container? Can't we just default to /usr/bin/bash, since many custom shells tend to fail anyway on an empty distrobox, because they're not installed inside the container?

**Comment by aral** [comment]
Would launching the shell via the distrobox-enter command work for you? (That’s how I do it.) e.g.,

```shell
distrobox-enter --name my-container -- fish
```

**Comment by 1player** [comment]
Yes that might work, thanks.

I'm still wondering if there's a need to pass $SHELL on creation though. `distrobox-enter` is already passing through a few environment variables, why not pass $SHELL as well at that stage?

**Comment by 89luca89** [comment]
Hi @1player 

> I'm still wondering if there's a need to pass $SHELL on creation though. distrobox-enter is already passing through a few environment variables, why not pass $SHELL as well at that stage?

To be honest I don't remember why it was done this way, I'm testing porting it to `enter` so that it follows host's SHELL each enter

**Comment by 1player** [comment]
Got it. Feel free to close this if there's nothing we can do to improve.

Honestly, the problem is upstream podman that doesn't let us change environment variables of an existing container. I think what I will try is `podman commit` my distrobox, and from the resulting image recreate the container with a different $SHELL environment variable.

It's easy to "reverse engineer" how my distrobox was created originally with `podman generate systemd --new`, so it's just a matter of changing the `--env SHELL=/usr/bin/zsh` option that's passed to `podman create`.

**Comment by 89luca89** [comment]
@1player 
you can use the `--clone` option in create to duplicate, it will automate all of this for you :+1:

**Comment by 1player** [comment]
But if I clone it'll create a new container with that same shell, right? So I need to use podman because I need a completely new container with different options, but with the same data.

**Comment by 89luca89** [comment]
no it will just use the image and reassign the variables with the new `create` phase :+1:
