### ISSUE TITLE
[Error] Failed to connect to bus when trying to enable systemd user service from within container

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#366]
**Describe the bug**

From within an Ubuntu 22.04 container:

```
sudo systemctl --user enable helix-system-colour-scheme-synchronisation.service

Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using
```

**To Reproduce**

Please see above.

**Expected behavior**

I should be able to create a user service in a container that has `init` and `root`.

**Desktop (please complete the following information):**
  - Fedora Silverblue 36
  - distrobox: 1.3.2

**Comment by aral** [comment]
Workaround: enable the service from host.

**Comment by 89luca89** [comment]
> sudo systemctl --user enable helix-system-colour-scheme-synchronisation.service

You should use --user without sudo, and it will work
if you use sudo, it uses the "root" systemd, which in the container may or may not work
if you use `--user` without sudo, it uses the common session (your user session) and will work

I'll close this for now, if it's not that let me know and I'll reopen!

**Comment by aral** [comment]
@89luca89 Sorry, my bad in the original issue. I can confirm that the problem exists when you don’t use sudo (which I errorneously wrote out of habit while writing the issue).

So the following commands:

```shell
  systemctl --user enable lipstick.service
  systemctl --user start lipstick.service
```

Fail with:

```shell
Failed to connect to bus: No data available
```

When run from a rootful, init containter.

Apologies for the initial confusion.

**Comment by aral** [comment]
Right, error can be more easily checked with:

```
systemctl --user status
```

This results in the same error.

The following workaround works:

```shell
XDG_RUNTIME_DIR=/run/user/ systemctl --user status
```

(Oddly, without specifying the user id. If you specify it – 1000 – it fails.)

**Comment by aral** [comment]
OK, no, there is definitely something outside of the app:

```
(process:8081): dconf-CRITICAL **: 16:32:46.402: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
```

**Comment by aral** [comment]
Interesting, other things have started to fail too. Going to try a reboot.

```
hint: Waiting for your editor to close the file... F: X11 socket /tmp/.X11-unix/X0 does not exist in filesystem.
F: X11 access will require --share=network permission.
F: Can't get document portal mount path

** (process:10936): WARNING **: 16:58:16.716: Failed to connect to bus: Could not connect: No such file or directory

** (process:10936): WARNING **: 16:58:16.752: Failed to connect to bus: Could not connect: No such file or directory

** (process:10936): WARNING **: 16:58:16.756: Failed to connect to bus: Could not connect: No such file or directory

(re.sonny.Commit:2): Gtk-WARNING **: 15:58:16.765: cannot open display: :0
error: There was a problem with the editor 'flatpak run --file-forwarding re.sonny.Commit @@'.
Please supply the message using either -m or -F option.
```
