### ISSUE TITLE
[Enchancement] What about including distrobox in the Fedora repository?

### ISSUE THREAD

**Issue by alcir** [89luca89/distrobox#37]
Installing `distrobox` is pretty simple, but it would be nice to install it from a distribution's repository.
I could try to take care of the Fedora one if you agree.
I don't guarantee that the package will be accepted an so on, but if you agree, I can try.

**Comment by 89luca89** [comment]
Hy @alcir 
Absolutely nothing against this 😄

**Comment by alcir** [comment]
In the spec file we need a Summary and a Description.
What do you think about:

```text
Summary: Another tool for containerized command line environments on Linux
```
(Toolbx summary is `Tool for containerized command line environments on Linux`)


```text
%description
Use any linux distribution inside your terminal. Distrobox uses podman
or docker to create containers using the linux distribution of your
choice. Created container will be tightly integrated with the host,
allowing to share the HOME directory of the user, external storage,
external usb devices and graphical apps (X11/Wayland) and audio.
```

**Comment by 89luca89** [comment]
Yep seems fitting

I've never done packaging for rpms but howo do we express an optional dependency?

What I mean is that distrobox works both with podman and docker
If neither is installed, we should install podman as a dependency 
If podman is installed then we just set up distrobox
But if docker is installed we should ignore the podman dependency and work with docker 

Is this possible with rpms?

**Comment by alcir** [comment]
> But if docker is installed we should ignore the podman dependency and work with docker

This is an interesting question.
I will look if it is possible.

**Comment by 89luca89** [comment]
Thanks a lot!

**Comment by M0Rf30** [comment]
> Yep seems fitting
> 
> I've never done packaging for rpms but how do we express an optional dependency?
> 
> What I mean is that distrobox works both with podman and docker If neither is installed, we should install podman as a dependency If podman is installed then we just set up distrobox But if docker is installed we should ignore the podman dependency and work with docker
> 
> Is this possible with rpms?

It's possible with every package manager. Basically you have to declare runtime dependencies as optional, with no non-optional dependencies. Here [my PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=distrobox).

In this way distrobox will warn you if something is missing.

I've done a previous attempt using as depends=('podman-docker') that, on Arch, provides docker and replace it, operating a full switch, but this behaviour forces the user to go for a drop-in replacement.

So my suggestion is: Keep it simple and rely on distrobox (not package manager) checks

**Comment by M0Rf30** [comment]
Another way could be to use a so-called splitted package: one spec file that generates two packages (distrobox-docker and distrobox-podman with their related runtime dependencies). Related runtime dependencies and their parent can be, at this point, mutually exclusive or whatever

**Comment by 89luca89** [comment]
Great stuff, I like the optional dependency path
The distrobox-podman and distrobox-docker one maybe is a bit cluncky

PS. Grazie a voi ragazzi 😄

**Comment by alcir** [comment]
The point is that docker could not be a dependency, since there is not a docker package in the Fedora repository.
A way to solve this, could be something like 
`Requires: (%{_bindir}/podman or %{_bindir}/docker)`
So. If `/usr/bin/docker` exists in the system, the RPM will not install the package containing `/usr/bin/podman`, otherwise it will install podman.
However I don't know if it is in line with the packaging best practices. If it really works. Will see.

An alternative could be: don't consider any dependency from the RPM point of view. Install distrobox even without podman or docker already installed. Then, when you will run distrobox, you will receive a warning that you should install one of these packages.

**Comment by 89luca89** [comment]
Yes probably the simplest way is to leave distrobox disjointed from the container manager
Also because in the future I would like to add nerdctl support and more, so probably leaving it by itself is the best approach

**Comment by 89luca89** [comment]
@alcir how's the situation with the Copr? I'd like to add the copr link to the README  :smile:

**Comment by alcir** [comment]
I update the COPR as soon as you tag a new release.
BTW the goal is to include distrobox in the main Fedora Linux repository. I'm still waiting for someone to pick up the review process.

https://bugzilla.redhat.com/show_bug.cgi?id=2034246

**Comment by 89luca89** [comment]
> I update the COPR as soon as you tag a new release. BTW the goal is to include distrobox in the main Fedora Linux repository. I'm still waiting for someone to pick up the review process.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2034246

Cool, I'll add the copr link to the docs then :smile: 
Let's hope we get in the main repos 🤞

**Comment by M0Rf30** [comment]
Congratulations! You're quoted by phoronix [here](https://www.phoronix.com/scan.php?page=news_item&px=Distrobox-Clear-Linux)

**Comment by 89luca89** [comment]
> Congratulations! You're quoted by phoronix [here](https://www.phoronix.com/scan.php?page=news_item&px=Distrobox-Clear-Linux)

Great news and well thanks @castrojo for the forum post that generated this :smile:

**Comment by 89luca89** [comment]
@alcir @M0Rf30 as an update, future releases of distrobox will include man files thanks to @misobarisic 
don't know if you'll need to modify anything in your packaging, I wanted to inform you :+1:

**Comment by alcir** [comment]
I see.
The spec file will be modified accordingly.
Thanks.

**Comment by M0Rf30** [comment]
> @alcir @M0Rf30 as an update, future releases of distrobox will include man files thanks to @misobarisic don't know if you'll need to modify anything in your packaging, I wanted to inform you 👍

got it, I'll manage it. IMHO should be managed by install script, but no problem at all

**Comment by 89luca89** [comment]
> > @alcir @M0Rf30 as an update, future releases of distrobox will include man files thanks to @misobarisic don't know if you'll need to modify anything in your packaging, I wanted to inform you 👍
> 
> got it, I'll manage it. IMHO should be managed by install script, but no problem at all

Yep it is managed by it, it was just in case you're not using it and using other commands in the pkgbuild 👍

**Comment by misobarisic** [comment]
> got it, I'll manage it. IMHO should be managed by install script, but no problem at all

The install script automatically installs them in the proper location, provided the man files exist.

**Comment by M0Rf30** [comment]
> > got it, I'll manage it. IMHO should be managed by install script, but no problem at all
> 
> The install script automatically installs them in the proper location, provided the man files exist.

If so, don't have to change nothing. And should be ok in this way. complexity demanded to proper scripts, not to package spec files

**Comment by M0Rf30** [comment]
Should you close this? Out of topic and COPR package already done

**Comment by 89luca89** [comment]
> Should you close this? Out of topic and COPR package already done

I think the issue is more about main repositories, so let's see if @alcir package is accepted :smil
🤞

**Comment by alcir** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-be777c0be0
Also thanks to @michel-slm

**Comment by 89luca89** [comment]
Super :tada: thanks @alcir and @michel-slm

**Comment by michel-slm** [comment]
@alcir, @89luca89 - I've upvoted the packages for Fedora 34 and 35, but for EPEL 8 I hit this issue (which can be work around): https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-92c7c9d199#comment-2358145

copying the message so we can follow along here

I'm hit by this issue when first trying distrobox enter: https://github.com/containers/podman/issues/11255
```
~ 
❯ podman logs -f f35
Error: using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported

~ 
❯ podman logs -f debian-packaging
Error: using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
```

The solution in the podman issue works, creating this file:
```
❯ cat /etc/containers/containers.conf 
# distrobox via podman needs this
# see https://github.com/containers/podman/issues/11255
[engine]
events_logger = "journald"
```
It might be worth filing a bug for both podman in RHEL 8 and in RHEL 9, since per the tracker it's affecting RHEL 9 too - and either ship a README documenting the workaround and possibly get it documented upstream in https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md too

**Comment by 89luca89** [comment]
> @alcir, @89luca89 - I've upvoted the packages for Fedora 34 and 35, but for EPEL 8 I hit this issue (which can be work around): https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-92c7c9d199#comment-2358145
> 
> copying the message so we can follow along here
> 
> I'm hit by this issue when first trying distrobox enter: [containers/podman#11255](https://github.com/containers/podman/issues/11255)
> 
> ```
> ~ 
> ❯ podman logs -f f35
> Error: using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
> 
> ~ 
> ❯ podman logs -f debian-packaging
> Error: using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
> ```
> 
> The solution in the podman issue works, creating this file:
> 
> ```
> ❯ cat /etc/containers/containers.conf 
> # distrobox via podman needs this
> # see https://github.com/containers/podman/issues/11255
> [engine]
> events_logger = "journald"
> ```
> 
> It might be worth filing a bug for both podman in RHEL 8 and in RHEL 9, since per the tracker it's affecting RHEL 9 too - and either ship a README documenting the workaround and possibly get it documented upstream in https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md too

I've just now tried a RHEL8.5 VM with a developer account, netinstall iso with normal "workstation" installation profile and it didn't show that journald error

What type of installation can reproduce this?

**Comment by alcir** [comment]
Now that distrobox (1.2.11) is in the Fedora Linux repository and 1.2.12 is on its way to the testing one, we can close this ticket.
Thanks.

**Comment by 89luca89** [comment]
> Now that distrobox (1.2.11) is in the Fedora Linux repository and 1.2.12 is on its way to the testing one, we can close this ticket. Thanks.

Thanks to you for taking care of this! 🎉 
When at home I'll update thendocs to point to official repos 😄 
Thanks a lot!

**Comment by M0Rf30** [comment]
> @alcir @M0Rf30 Heads up, next version will include #190 This will DEPRECATE the use of `--path/-p` in favor of `--prefix/-P` to behave similar to makefiles. This way you specify only the base path where `bin` and `man` will be installed, for example
> 
> `./install --prefix /usr/local`

done, for git package
