### ISSUE TITLE
[Suggestion] Use podman --remote if running inside of podman

### ISSUE THREAD

**Issue by orowith2os** [89luca89/distrobox#371]
**Is your feature request related to a problem? Please describe.**
You need to specify `podman --remote` to interact with podman inside of Distrobox.

**Describe the solution you'd like**
Distrobox would detect, most likely with an environment variable, that it's running inside of a container. If detected, it will use ``podman --remote`` instead of `podman` for any commands related to podman.

**Describe alternatives you've considered**
Using `podman --remote` individually works, but it's a bit of a pain compared to Distrobox.

**Comment by orowith2os** [comment]
I can look into making a PR that implements this, although don't expect it to be up too quickly lol

**Comment by 89luca89** [comment]
The `--remote` is thought for well remote hosts :smile: 
The right move would be to use `distrobox-host-exec`, `host-spawn` or `flatpak-spawn` to interact with host's podman

**Comment by orowith2os** [comment]
I believe it would be easier to include a check for an appropriate environment variable, and if set, use `--remote` rather than relying on flatpak-spawn or other alternatives. It would probably be possible to wrap the distrobox commands with `distrobox-host-exec`, but if someone has a container-based workflow and they don't want to have to do any workarounds, `--remote`` being included inside of distrobox itself would be the easiest method.

**Comment by 89luca89** [comment]
At one point distrobox **did** include the --remote but was creating problems and I've decided to simplify the situation cutting it
