### ISSUE TITLE
[Error] distrobox-export fails when there is a dot in the container name

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#375]
**Describe the bug**

distrobox-export fails when there is a dot in the container name. It truncates the name at the dot.

**To Reproduce**

In a rootful initted Ubuntu 22.04 container called `ubuntu-22.04-root-init` with batcat installed (`apt install batcat`):

```
distrobox-export --bin /usr/bin/batcat --export-path ~/.local/bin
```

From the host:

```
batcat --version
``` 

**Expected behavior**

You should see the batcat version.

**Actual behavior**

```
Error: inspecting object: no such container ubuntu-22
Cannot find container ubuntu-22
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:36? [Y/n]: ^C
```

**Workaround**

Create a new container, cloning the one you have, removing any dots from the name.

e.g., for the above root/init container (I’m not sure if you have to repeat the `--root` and `--init` flags or if clone handles that for you but I figured it wouldn’t hurt if I did.)

```shell
distrobox create --clone ubuntu-22.04-root-init --name ubuntu-2204-root-init --root --init
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.1.1
 - Which version of distrobox? 1.3.2 (d303247)

**Comment by 89luca89** [comment]
That's a nice catch :smile: 

I've just now pushed a commit that will fix this behaviour.
After upgrading you'll need to stop, and start again the container
