### ISSUE TITLE
[Error] distrobox enter fails when /etc/passwd shell is set to /bin/fish

### ISSUE THREAD

**Issue by Zlopez** [89luca89/distrobox#377]
**Describe the bug**
When creating a new CentOS 9 Stream toolbox and my default shell is set to `/bin/fish` it will fail to start with following:
```
Error: crun: executable file `fish` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

**To Reproduce**
1. Change default shell to `/bin/fish` (https://www.tecmint.com/change-a-users-default-shell-in-linux/)
2. Relog as the user
3. `distrobox-create --name centos9-stream --image centos:stream9`
4. `distrobox enter centos9-stream`

**Expected behavior**
Ended up inside container

**Logs**
[distrobox.log](https://github.com/89luca89/distrobox/files/9337080/distrobox.log)

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.1.1
 - Which version of distrobox? 1.3.1

**Additional context**
This works with Fedora 36, it seems that the issue is only because the CentOS Stream doesn't have fish in default repositories. But it would be nice if the distrobox would ignore the shell set by user to prevent issues like this one.

The workaround for this is to set the shell to `/bin/bash` and just add `/bin/fish` at the end of `~/.bashrc`. This will still fail when loading `.bashrc`, but at least you will end up inside toolbox.

**Comment by Zlopez** [comment]
The workaround I mentioned above doesn't really work :-/

What works is to set the shell explicitly:
```
SHELL=/bin/bash distrobox-create --name centos9-stream --image centos:stream9
SHELL=/bin/bash distrobox enter centos9-stream
```

As you can see the shell needs to be set even for the `distrobox-create` command. Otherwise you will end up in the same situation as above.

**Comment by misobarisic** [comment]
This [post](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#pre-installing-additional-package-repositories) describes how you can enable additional repositories on centos. Which in turn allows fish to be installed in the init phase.

**Comment by Zlopez** [comment]
> This [post](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#pre-installing-additional-package-repositories) describes how you can enable additional repositories on centos. Which in turn allows fish to be installed in the init phase.

Thanks, I didn't noticed this.

**Comment by 89luca89** [comment]
Thanks for the report @Zlopez 

Indeed it is a problem, right now `distrobox-init` correctly falls back to `bash` when it cannot install the $SHELL of the host.
We need a way to tell back `enter` that situation

**Comment by 89luca89** [comment]
@Zlopez 
Pushed a commit that fixes the behavior

Now `enter` will respect the login shell of the container
during init, if it's not possible to install your custom shell (in this case fish) it will fallback to `bash`, and will successfully `enter`

you can then change shells simply using chsh as in a normal system
