### ISSUE TITLE
[Suggestion] Ubuntu image creates a .profile in user's home directory

### ISSUE THREAD

**Issue by homeisfar** [89luca89/distrobox#378]
I understand that Distrobox is meant to be integrated with the host, but I had a very surprising behavior the other night. I use Fedora as my host with fish shell as the default (`chsh -s /usr/bin/fish`). I set up an Ubuntu box like so:

```
distrobox create --image ubuntu:latest --name testbuntu
distrobox enter testbuntu
```

This is all it takes for the Ubuntu container to create a `.profile` in my home directory. This was extremely unexpected and surprising because when I rebooted a couple of days later and launched gnome-terminal, I was greeted with bash instead of my default fish. It took me a while to pinpoint it to the newly created .profile file . I don't know what the solution to this is, but I think this surprise dot file creation in my home dir is inappropriate behavior and it'd be best if it did not happen.

**Comment by 89luca89** [comment]
Sadly this is an unwanted behavior of Ubuntu, more than something to do with distrobox
This would have happened even if you just ran a simple podman/docker sharing the $HOME like

`podman run --rm -ti --volume $HOME:$HOME ubuntu:latest bash -l`

I cannot do much about it, you can use custom homes to prevent this
