### ISSUE TITLE
[Feature] Add NixOS to container distros

### ISSUE THREAD

**Issue by samuelludwig** [89luca89/distrobox#38]
https://nixos.org/

To be honest I can't imagine this is going to be a simple play given NixOS's unique way of managing itself and its filesystem.

**Comment by 89luca89** [comment]
Hi @samuelludwig 
I see there's this available

https://hub.docker.com/r/nixos/nix

What I would like to have is a way to install the needed programs
sudo shadow utils-linux $SHELL (to match the host) 
Directly without going the /etc/configuration.nix route.
And we need to add the nix paths to $PATH or nothing will work 😄 

I might need and Hand in this as I'm not a nix user so I am not really knowledgeable on a lot of things nix related

But I can see it possible 👍

**Comment by 89luca89** [comment]
Fiddled with it a bit today, usind `nix-env` to set up this container: https://hub.docker.com/r/nixos/nix
From what I see it sets up on `/root/.nix-profile/bin` so it is exclusive to the root user, other users cannot use it.

This also seems to not create necessary files for sudoers and passwd

I will need an hand for this, so for now I'll leave as `need-help` tag and unblock it

**Comment by TheEvilSkeleton** [comment]
> Hi @samuelludwig I see there's this available
> 
> https://hub.docker.com/r/nixos/nix
> 
> What I would like to have is a way to install the needed programs sudo shadow utils-linux $SHELL (to match the host) Directly without going the /etc/configuration.nix route. And we need to add the nix paths to $PATH or nothing will work smile
> 
> I might need and Hand in this as I'm not a nix user so I am not really knowledgeable on a lot of things nix related
> 
> But I can see it possible +1

Just to make things clear, the link you posted is the nix **package manager**, and not NixOS. NixOS doesn't provide and Docker builds for NixOS itself so sadly there's not much we can do here.

**Comment by 89luca89** [comment]
Oh OK I thought it was a nixos build really 😅 
Well I'm this case, I'll close this issue and we can open a new one when a container image of nixos will exist or someone males the above image work somehow 👍
