### ISSUE TITLE
[Error] XDG_RUNTIME_DIR setting causes systemd --user commands to fail in Fedora --init container

### ISSUE THREAD

**Issue by aral** [89luca89/distrobox#380]
## Describe the bug

In a Fedora 36 container set up using `distrobox create --init …`, issuing systemd `--user` commands fail with “Failed to connect to bus: No data available”.

## To Reproduce

```shell
distrobox create --init --image quay.io/fedora/fedora:36 --name fedora-distrobox-init-36 --pre-init-hooks "dnf install -y systemd"
distrobox enter fedora-distrobox-init-36
systemctl --user status
```

## Expected behavior

You should see user status output from systemd.

## What actually happens

Error:  “Failed to connect to bus: No data available”

## What actually works

```
XDG_RUNTIME_DIR=/run/user systemctl --user status
```

The value of `$XDG_RUNTIME_DIR` within the container is the same as that for the host:

```shell
printenv XDG_RUNTIME_DIR

/run/user/1000
```

Setting that to `/run/user` instead seems to solve the problem.

I don’t know why but maybe you can shed some light on it, @89luca89 :)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.1.1
 - Which version of distrobox? 1.3.2 (20336f6)

**Comment by 89luca89** [comment]
This is because an initful container can have a separate user systemd session
In order to have a standalone systemd inside the container, some integration is lost, `systemctl --user` is one of that
