### ISSUE TITLE
[Error] Trying new ubuntu chiseled fails

### ISSUE THREAD

**Issue by maxfridbe** [89luca89/distrobox#381]
**Describe the bug**

> Error: unable to start container "372938dbdee48b027d994f15150d0c685fb865ee9f60bf969cd3e642357e7c84": unable to find user root: no matching entries in passwd file

**To Reproduce**
running 

> distrobox create -n chiz-ubuntu -i mcr.microsoft.com/dotnet/nightly/aspnet:6.0-jammy-chiseled

> distrobox-enter chiz-ubuntu

**Expected behavior**

**Logs**
No logs available

**Desktop (please complete the following information):**
 - Which version or podman or docker?
podman version 4.1.1
 - Which version of distrobox?
distrobox: 1.3.1

**Additional context**
Fedora Silverblue

**Comment by 89luca89** [comment]
Hi @maxfridbe 

distroless containers are not supported in distrobox
chisel is a very similar approach, this image even lacks `sh`, `/etc/passwd` and can only execute .NET, so distrobox cannot possibly work on this

You can indeed use non-chisel version of the image:

```sh
    distrobox create -n ubuntu -i mcr.microsoft.com/dotnet/nightly/aspnet:6.0-jammy
    distrobox-enter ubuntu
```
this will work

Closing as this is not a distrobox bug.
