### ISSUE TITLE
[Discussion] how to stop distrobox defaulting to fedora:36

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#384]
### Is your feature request related to a problem? Please describe.

Personally I always want to specify the OS/image when creating a toolbox.
I guess I am more-or-less a "one toolbox per OS" kind of user.

But if I don't specify an image, possibly by forgetting -i etc,
distrobox automatically assumes I want a fedora:36 container,
which I normally don't.

### Describe the solution you'd like

Basically I want a configuration option such that distrobox-create fails immediately if I don't specify the image (OS).
ie I would like to have a way to configure "no default image", if possible.

**Comment by misobarisic** [comment]
For the time being you can set the `DBX_CONTAINER_IMAGE` environment variable to something that doesn't exist and set `DBX_NON_INTERACTIVE` as well to emulate the desired behaviour.

**Comment by 89luca89** [comment]
@juhp 
this is an intended behavior, for ease of use if no image is specified, we use the default one
you can change the default one in your config files following this:

https://github.com/89luca89/distrobox/#configure-distrobox

I'd like to maintain it like this for ease of use

**Comment by juhp** [comment]
Okay, I think I can workaround it by just setting a dummy default image.

**Comment by dmytri** [comment]
> Okay, I think I can workaround it by just setting a dummy default image.
> 
> For more context: I am still mostly using toolbox for Fedora containers: so normally I don't want to use fedora images for distrobox by default - I suspect there are also other users in this situation.

just our of curiosity, what is the advantage of using toolbox for fedora containers? why not use distrobox for all of them?
