### ISSUE TITLE
[Error] Host timezone isn't synced to container

### ISSUE THREAD

**Issue by PureTryOut** [89luca89/distrobox#385]
**Describe the bug**
The timezone in use by the host isn't synced to the container.

**To Reproduce**
Use a timezone other than UTC on the host. Run `date` in both host and container to compare.

**Expected behavior**
The container to use the same timezone as the host.

**Logs**
```
04:36 ~ date
Wed Aug 24 16:36:36 CEST 2022
04:36 ~ distrobox enter archlinux
02:36 ~ date
Wed Aug 24 14:36:42 UTC 2022
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.1.1
 - Which version of distrobox? 1.3.1

**Additional context**
The host is an Alpine Linux system and the container I'm testing it with is Arch Linux.

**Comment by 89luca89** [comment]
Hi @PureTryOut 
Seems like this is a problem on Alpine

The `/etc/localtime` file is a symlink to an absolute path: `/etc/zoneinfo/XXXX` so it will not find it 
Adapted with latest commit the code to watch for the changes and now seems to be ok even on Alpine

Thanks for reporting! :+1:
