### ISSUE TITLE
[Suggestion] add --stop to distrobox-rm

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#391]
**Is your feature request related to a problem? Please describe.**
Of course one can run podman stop manually on a container before `distrobox-rm`,
but I think it would be a nice small feature addition to provide a `--stop` option
to `distrobox-rm` so that it can be all done in one step (or ie by just editing the command):

```shellsession
$ distrobox-rm fedora-37-db
Please stop container fedora-37-db before deletion
Run:
	podman stop fedora-37-db
or use the "--force" flag
```

**Describe the solution you'd like**
```shellsession
$ distrobox-rm fedora-37-db --stop
:
```

**Additional context**
(I know there is --force but I feel using stop is a softer approach.)

**Comment by 89luca89** [comment]
Hi @juhp 

well the `--force` flag just does `stop` before `rm`

**Comment by juhp** [comment]
Ah okay, I should have checked...
Somehow I assumed it was doing `podman rm --force`.
Though in that case I might rename `--force` to `--stop`.
I hope I can remember this. :-)
