### ISSUE TITLE
Malformed variables can stop distrobox from entering a container

### ISSUE THREAD

**Issue by amazingidiot** [89luca89/distrobox#395]
Hi,
as discussed in the distrobox matrix channel, a short summary of an issue I observed.

In my case I am using Kitty as a terminal emulator. Kitty creates an env variable $KITTY_PUBLIC_KEY, that contained a single \` causing the last line of the distrobox-enter script to fail since bash tried to find the corresponding \`.

It is independent from Kitty since any malformed variable containing a backtick can make distrobox fail to enter a container, see the following example:

```
$ MALFORMED='this won`t work'
$ echo $MALFORMED
this won`t work

$ distrobox enter Rust
/usr/bin/distrobox-enter: line 494: qE: unbound variable

An error occurred

An error occurred

```

A possible solution might be to check if an environment variable contains any backtick and then ignore it in the $cmd variable? Maybe notify the user that a variable is malformed and cannot be used in the container? It might be possible to escape the backtick in the $cmd variable and make it available in the container?

Thanks and best regards,
Oliver

**Comment by 89luca89** [comment]
Fixed with latest commit :+1:

**Comment by chzerv** [comment]
It seems like `$` is yet another special character that causes `distrobox-enter` to fail. Funny enough, the variable containing it was also `KITTY_PUBLIC_KEY`, which seems to be randomly generated every time a new kitty instance is launched.

 Ignoring `$`  from the environment resolves the issue and has not caused any other issues.. *yet*!

**Comment by 89luca89** [comment]
Reopening for investigation

**Comment by amazingidiot** [comment]
> Fixed with latest commit 👍

Cool!



> Reopening for investigation

Also cool. If you need something tested, happy to help

**Comment by 89luca89** [comment]
I'll try to find as many invalid chars as possible to exclude them, I think "`" and "$" are the most common but probably also "&" and some others

**Comment by chzerv** [comment]
I just noticed that ignoring "$" causes a "Missing X server or $DISPLAY" error when trying to launch GUI apps.

`$(?!DISPLAY)` seems to solve that, but I'm not sure if it will cause any other errors.

Also happy to help if you need something tested!

**Comment by 89luca89** [comment]
I think it was because just grepping for `$` won't work, we need to escape it `\$` and it will just remove vars containing that char.

I've pushed an update that will remove the following chars:

`grep -Ev ' |"|`|\$'`

This should take care of most of them 
Can anyone give a couple of rounds of tests?

**Comment by amazingidiot** [comment]
I'll see what i can do tomorrow

**Comment by NKS1608** [comment]
The same thing happened to me, the interesting thing is that the first two times I used it there was no error. I use kitty but xterm works normally.


```distrobox enter --root test
/usr/bin/distrobox-enter: line 494: tSa: unbound variable

An error occurred

An error occurred```

**Comment by NKS1608** [comment]
fixed lol ![image](https://user-images.githubusercontent.com/22014605/189559384-e6b95536-620c-4e54-a431-f13fdc295c3c.png)

**Comment by chzerv** [comment]
> I think it was because just grepping for `$` won't work, we need to escape it `\$` and it will just remove vars containing that char.
> 

You are absolutely right, I can't believe I missed that...

> I've pushed an update that will remove the following chars
> 
> `grep -Ev ' |"|`|$'`
> 
> This should take care of most of them Can anyone give a couple of rounds of tests?

Haven't had any errors since e1b1536937350276d38aa533e163eb8446ce87ed was pushed! 

Thank you!

**Comment by 89luca89** [comment]
Cool, I'll mark this as solved again, and if something else pops up, we can reopen :smile:
