### ISSUE TITLE
[Suggestion] Add --root option to distrobox-generate-entry

### ISSUE THREAD

**Issue by Andreiva13** [89luca89/distrobox#397]
**Is your feature request related to a problem? Please describe.**
If the container was generated with `--root` then `distrobox-generate-entry` cannot be used as the container is not found when ran as normal user and running with `sudo` generates the files only for the root user

**Describe the solution you'd like**
Adding a `--root` option that'd work just like it does for the other commands.

**Comment by 89luca89** [comment]
Hi @Andreiva13 

This is a wanted behaviour for now
Right now --root will use sudo, and the password prompt won't work launching from the app drawer

So it's purposefully disabled for now

Not sure how to implement this in a reliable way
So I'm not planning to add it in the near future (help is always welcome 😋 )

Will keep this open for future reference 👍

**Comment by 89luca89** [comment]
Implemented by f9e032d5f8e7359abfe60f7d19d8aa5856348a64
