### ISSUE TITLE
Error when installing with curl https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

### ISSUE THREAD

**Issue by Athanaze** [89luca89/distrobox#4]
Host os : kernel 5.13.19-2-MANJARO 

I executed 
 curl https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

It printed out : 

/usr/bin/curl
/usr/bin/tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    345      0 --:--:-- --:--:-- --:--:--   345
100  139k    0  139k    0     0   117k      0 --:--:--  0:00:01 --:--:--  440k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0    320      0 --:--:-- --:--:-- --:--:--   321
100 21507    0 21507    0     0  25096      0 --:--:-- --:--:-- --:--:--  103k
distrobox-1.0.0/
distrobox-1.0.0/LICENSE
distrobox-1.0.0/README.md
distrobox-1.0.0/distrobox-create
distrobox-1.0.0/distrobox-enter
distrobox-1.0.0/distrobox-export
distrobox-1.0.0/distrobox-init
distrobox-1.0.0/install
**chmod: cannot access '/usr/local/bin/distrobox-1.0.0/distrobox-create': No such file or directory**

`ls` in `usr/local/bin` gives :

`distrobox-create  docker-compose  git-quick-stats`

So it looks like it's a simple folder naming error (distrobox-create instead of distrobox-1.0.0 ?)

Best of luck with your project, it would be very useful to me :)

**Comment by 89luca89** [comment]
Mh probably yes i'll check it today when back at pc,

Can you try for now specifying the folder?

```
curl https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- -p ~/.local/bin
```

This will work without sudo and put it in ~/.local/bin, so you must add it to your $PATH if not already present

**Comment by 89luca89** [comment]
@Athanaze I've pushed a fix for this in another branch

You can test using

```
curl https://raw.githubusercontent.com/89luca89/distrobox/fix_mount_routine/install | sudo sh
```

Or

```
curl https://raw.githubusercontent.com/89luca89/distrobox/fix_mount_routine/install | sh -s -- -p ~/.local/bin
```

**Comment by 89luca89** [comment]
I've tested the change, and it fixes your situation, this bug will be closed with the merge request, thanks a lot for the reporting!
