### ISSUE TITLE
[Error] default OCI runtime "crun" not found: invalid argument (SteamOS - Steam Deck)

### ISSUE THREAD

**Issue by LiamDawe** [89luca89/distrobox#401]
I've read the documentation, and I'm trying to run this on SteamOS (Steam Deck).

Are the documents missing some steps? As running the suggested way to install from [this page](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#install-podman-in-a-static-manner) 

> curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/extras/install-podman | sh -s -- --prefix ~/.local

Results in this error:

> Error: default OCI runtime "crun" not found: invalid argument

**Comment by 89luca89** [comment]
Yep, it was missing a `/bin` in the path for the command

Tested this again and should be working fine (at least in the recovery image it works)

**Comment by LiamDawe** [comment]
Hi, thanks but looks like you need to do the same fix for removing it via this:

> curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/extras/install-podman | sh -s -- --prefix ~/.local --remove

As it results in the same error.
