### ISSUE TITLE
[Suggestion] Either curl or wget should be allowed everywhere

### ISSUE THREAD

**Issue by linsui** [89luca89/distrobox#407]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
In distrobox-generate-entry wget is hardcoded to be used. It should try curl if wget is not available. It already done in the install script and it should be like that everywhere.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - Which version or podman or docker?
 - Which version of distrobox?

**Additional context**

**Comment by 89luca89** [comment]
This is not a bug

Changing to feature suggestion

**Comment by 89luca89** [comment]
Added to latest commit

**Comment by linsui** [comment]
Thanks!
