### ISSUE TITLE
[Suggestion] icon_default should be a related path to prefix

### ISSUE THREAD

**Issue by linsui** [89luca89/distrobox#408]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I can set the prefix when installing be it's not used in distrobox-generate-entry. The icon path is hardcoded instead.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - Which version or podman or docker?
 - Which version of distrobox?

**Additional context**

**Comment by 89luca89** [comment]
This is not a bug

Changing to feature suggestion

**Comment by 89luca89** [comment]
This is not planned, in the future it will become part of #386
