### ISSUE TITLE
Another step needed for Steam Deck

### ISSUE THREAD

**Issue by LiamDawe** [89luca89/distrobox#409]
Hi, thanks for the Steam Deck fixes and docs updates.

Looks like currently it can't run GUI apps though, as this error is encountered:

```
(deck@ubuntu-20-04 ~)$ gedit
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused

(gedit:90857): Gtk-WARNING **: 11:33:16.135: cannot open display: :0
```

Any thoughts on what we need to run to get GUI apps working too?

Terminal apps work though.

**Comment by misobarisic** [comment]
Seems like a duplicate of #329.

**Comment by LiamDawe** [comment]
Huh, you're right

> xhost +si:localuser:$USER

Fixed it.

Be good to have that in the SteamOS section of the docs for sure.

**Comment by 89luca89** [comment]
Added :+1:

**Comment by Jookia** [comment]
I found I needed this on Arch too

**Comment by TheBricktop** [comment]
how did You create ubuntu 20.04 container? Im getting a unsupported image specific error every time im trying to create ubuntu container

**Comment by skribzz** [comment]
> Huh, you're right
> 
> > xhost +si:localuser:$USER
> 
> Fixed it.
> 
> Be good to have that in the SteamOS section of the docs for sure.

When I tried this all I got was “bash: xhost: command not found”

**Comment by mrbaggins** [comment]
Just bought and updated a steam deck. distrobox 1.8. Trying to do the same with the above xhost command and getting the same "command not found" error. Bit stuck.
