### ISSUE TITLE
distrobox-export --app failure due to cp: -r not specified

### ISSUE THREAD

**Issue by pseudofakee** [89luca89/distrobox#41]
Hi again!

I was just trying to export Visual Studio Code today (from the Aur bin package) and came across the following

```

[joseph@Arch ~]$ distrobox-export --app code
cp: -r not specified; omitting directory '/usr/share/icons/hicolor/128x128/stock/code'

```
Nothing is exported to .local/share/applications/

Not sure if I missed a flag somewhere, but I couldn't see any that were relevant ?

**Comment by 89luca89** [comment]
Hi @pseudofakee testing @alegrey91 fix, if all ok will merge and fix the issue :+1:
