### ISSUE TITLE
[Suggestion] PureOS

### ISSUE THREAD

**Issue by bentpurist** [89luca89/distrobox#412]
I would like to run PureOS on my Steam Deck using distrobox. It would be helpful if you could add PureOS to the distros you already support so I could install PureOS easily. I don't have the knowledge necessary to attempt it myself. Thanks for your consideration.

**Comment by misobarisic** [comment]
I have tested it myself and the container starts without an issue.
`distrobox create -i docker.io/pureos/byzantium -n pureos` -> `distrobox enter pureos`

**Comment by bentpurist** [comment]
> I have tested it myself and the container starts without an issue. `distrobox create -i docker.io/pureos/byzantium -n pureos` -> `distrobox enter pureos`

Thank you for replying to my post. I thought I did what I was supposed to do. It seemed to set up the container. When I tried to enter pureos, however, I got this:
localuser:deck being added to access control list
(deck@steamdeck ~)$ distrobox enter pureos
bash: xhost: command not found
Help would be appreciated. Thanks.

**Comment by misobarisic** [comment]
You need to have `xhost` installed on the host and have appropriate permissions to be able to use graphical apps inside a container.

Please refer to #329 and #409

**Comment by bentpurist** [comment]
I looked at #329 and #409 but I could not see what I am supposed to do to correct the problem. Is xhost installed by default on the Steam Deck? If not, how do I install it? By the way, I did add the following three lines at the end of my bashrc file:
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/podman/bin:$PATH
xhost +si:localuser:$USER
I continue to get this:
(127)(deck@steamdeck ~)$ distrobox enter pureos
bash: xhost: command not found
Thanks.

**Comment by bentpurist** [comment]
I solved the problem by running sudo apt install x11-xserver-utils in Konsole. It might be helpful to others if this could be mentioned in the instructions along with a suggestion that the user set up a password on the user's account (for sudo purposes) before performing the Distrobox installation.
