### ISSUE TITLE
[Bug] distrobox-init: filesystems mounted inside /run/bees are searched, delaying container startup

### ISSUE THREAD

**Issue by GermanBread** [89luca89/distrobox#416]
**Describe the bug**
It takes a very long time to start any container.

The startup command `find /run/host/run -name user -prune -o -name nscd -prune -o -name system_bus_socket -prune -o -type s -print` queries all my filesystems that are mounted by beesd. It takes around 20 seconds to query `/nix/store` + all the snapshots of `/home` that exist.
Beesd mounts the filesystem it is working with at `/run/bees/<UUID of fs>` (note: after stopping all beesd instances and mounts the container starts up pretty much instantly)

The problematic line seems to be located here: https://github.com/89luca89/distrobox/blob/main/distrobox-init#L692

**To Reproduce**
Install beesd and tell it to deduplicate \<file system with a lot of files\>, then run `distrobox enter <inactive container>`

**Expected behavior**
The startup script should not query `/run/host/run/bees`

**Logs**
[gamebox.log](https://github.com/89luca89/distrobox/files/9578792/gamebox.log)

**Desktop (please complete the following information):**
 - _OS_ **NixOS 22.11pre408684.9608ace7009 (Raccoon)**
 - _Are you using podman or docker?_ **podman**
 - _Which version or podman or docker?_ **4.2.1**
 - _Which version of distrobox?_ **1.4.0**

**Comment by GermanBread** [comment]
I created a [fork](https://github.com/GermanBread/distrobox) and modified `distrobox-init`, but unfortunately I have no idea how to test my changes (and I even managed to ruin my container setup...)

**Comment by GermanBread** [comment]
Update: I managed to test my changes in a NixOS VM (with beesd)

My changes fix the issue I described.

**Comment by 89luca89** [comment]
Hi @GermanBread 

thanks for the debug and contribution :smile: 

Will check this out :+1:

**Comment by 89luca89** [comment]
Merged, thanks!
