### ISSUE TITLE
[Suggestion] Update XDG_CONFIG_HOME when created with --home

### ISSUE THREAD

**Issue by bsvh** [89luca89/distrobox#420]
**Is your feature request related to a problem? Please describe.**
I created a distrobox with a separate home for working on some software in a clean environment. I noticed that the software was creating config files in my `$XDG_CONFIG_HOME`, which is set to `$HOME/.config`. This was unexpected for me, as setting `--home` was specifically so that user configuration files were not loaded.

**Describe the solution you'd like**
Unset `$XDG_CONFIG_HOME`, `$XDG_CACHE_HOME`, `$XDG_DATA_HOME`, and `$XDG_DATA_DIRS`.

**Describe alternatives you've considered**
You could also set `$XDG_` to the standard locations in the container's home, but I think that is making too many assumptions and could be handled by `--env`. You could also leave it as is and let the user update `--env`, but I think if someone is using `--home` they don't want to keep the `$XDG_` vars set.

**Comment by orowith2os** [comment]
It's probably better to set the XDG base dir variables inside of the custom home, and not unset them; we shouldn't be promoting having the variables unset. The user can override them if desired.

**Comment by luc14n0** [comment]
Ignoring `XDG_*` variables inherited from the user's shell configs when using `--home` sounds better than _unsetting_ them. Of coursing that re-setting them based on the value passed to `--home` is another option too. Then we should ask ourselves which one fits best **Distrobox**'s purposes/philosophy.

**Comment by luc14n0** [comment]
By the way, a quick solution one could use would to go to config file where they are setting the `XDG_CONFIG_HOME` variable and add some logic so to make a given Distrobox container to either use a different value or just not set the variable at all, something like:

1. First the logic in the RC file of your shell:

``` sh
if [ "$DBX_CONTAINER" = "my-container" ]; then
    XDG_CONFIG_HOME=/same/location/used/with/--home
else
    XDG_CONFIG_HOME=/path/to/location/of/choice/on/the/host/system
fi
```

This was the different values strategy.

``` sh
if [ "$DBX_CONTAINER" != "my-container" ]; then
    XDG_CONFIG_HOME=/path/to/location/of/choice/on/the/host/system
fi
```

And this one, selective setting strategy. Only setting `XDG_CONFIG_HOME` on environments that don't have `DBX_CONTAINER=my-container`

3. And now all we need to do is to finally set the variable when launching the **Distrobox** container.

``` sh
$ distrobox enter --additional-flags '--env DBX_CONTAINER=my-container' --name my-container-name
```

The basic idea is to set a specific variable in the container environment that can be checked in the shell config file(s). I personally use this kind of logic to selective choose what the config files do based on where the shell is being opened, whether it's on the host or on a (specific) **Distrobox** container.

**Comment by misobarisic** [comment]
Distrobox already adds `$CONTAINER_ID` env variable. You can use it instead of setting one manually.

**Comment by luc14n0** [comment]
Yes, for this particular case using `CONTAINER_ID` should suffice.

**Comment by krakjn** [comment]
@luc14n0 
Interesting, so the idea is for the user's interactive shell files to pick up on the fact they are in container and thus change $PATH and other environment vars. 

I have been messing around with `--init-hooks` and `--additional-flags` on `distrobox-create` to change shells and set the PATH correctly. The issues are:

1. Reading through [this](https://github.com/89luca89/distrobox/blob/c05b6a43769bfa56d572a457f1420e0e2589fe3b/distrobox-init#L1982) I see the profile is capturing both bash and zsh, but unfortunately I am on fish. 
2. I notice the default shell on alpine linux is `bash` what if I want to stay on `/bin/ash`? 
3. Love the deep binding of host and container, this project is incredible. But is there a way to _isolate shells_? I have separate programs on separate paths and if I change shells it doesn't persist. If I keep shells PATH works but it's polluted with host PATH. 

I am running `alpinelinux` container on a `nixos` host. I would love a `--shell` or `--path` argument to prepend/overwrite/append on these critical env vars. 

I have tried `distrobox assemble create` with a `distrobox.ini` to workaround this but I get one or the other, never both. 

Summary: sanitized PATH and different shell than host would be huge. I am willing to contribute here.
