### ISSUE TITLE
[Docs] Running latest gnome on distrobox doesn't work

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#423]
**Describe the bug**
I tried following the section about [running gnome under distrobox](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md), but after taking all steps it instantly exits not even opening session properly.

**To Reproduce**
1. Go with all the steps required for [running gnome under distrobox](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md)
2. Run it from gdm

**Expected behavior**
Gnome session should run from it and not instantly exit

**Logs**
Podman latest logs (doesn't seem to be all that useful): 
[podman latest log](https://github.com/89luca89/distrobox/files/9594594/podman.latest.log)

**Desktop :**
 - Podman
 - 4.2.0
 - distrobox 1.4.1 (though fetched from master at the moment, `1b79cc8 completion: fix container name suggestion` commit)
 - Fedora Silverblue 36

**Additional context**
The part related to x11 sockets is not super obvious, where i should place that shell file or execute command? does it have to run from user? or from root? from inside container or outside? I tried various ways, but none of them worked to make session run (including chowing folder to user directly)

**Comment by luc14n0** [comment]
> **Additional context** The part related to x11 sockets is not super obvious, where i should place that shell file or execute command? does it have to run from user? or from root? from inside container or outside? I tried various ways, but none of them worked to make session run (including chowing folder to user directly)

Do you mean the [Generate session file - GNOME](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md#generate-session-file---gnome) section?

If so right at the beginning it states "First in the host we need ...". When we say "host" we mean the system where **Distrobox** got installed, in your case **Fedora Silverblue 36**, and where we install "guests", i.e. containers.

And the `/etc/profile.d/fix_tmp.sh` script is not suppose to be run by you as it should get run automatically whenever a login shell is used/spawned in your Fedora system.

**Comment by misobarisic** [comment]
I am also having trouble. I'm using SDDM but I've made its startup script transfer x11 socket ownership to my user (does so successfully). Desktop file is setup correctly. Upon spawning the session I get a sigtrap from inside the container. Happens on both fedora:rawhide and fedora:36.

**Comment by 89luca89** [comment]
I'll come back to this
Probably instructions have been obsoleted by some upgrade in either gdm or sddm, this is not super-high on my list as I have lots of other bugs/issues to fix :sweat: 

So for now I'll have to do other stuff, in the meantime if someone finds a fix, glad to discuss and test it

If not, and I see it's not an easy feat, I'll probably need to pull this out as I cannot maintain/test it continuously 
And it was done as a fun experiment anyway
