### ISSUE TITLE
[Error] Virtualbox makes distrobox not work. [SOLVED]

### ISSUE THREAD

**Issue by pedrohqb** [89luca89/distrobox#425]
After installing virtualbox, I get this error when I try to enter the distro. Removing it makes it work as usual.

Check out the log:

pedro@mope-tumbleweed:~> distrobox-enter ubuntu
Container ubuntu is not running.
Starting container ubuntu
run this command to follow along:

 podman logs -f ubuntu

Error: unable to start container "5f4953461fc5d5162e2fcfda6dcb1e8128f0873461776277666e828fdff32d8b": runc: runc create failed: unable to start container process: error during container init: error mounting "/dev/vboxusb/002/005" to rootfs at "/dev/vboxusb/002/005": lstat /home/pedro/.local/share/containers/storage/btrfs/subvolumes/26733ff42750022c97b113ccf37f1902ef69c08f063888350cc11744e55dbb2f/dev/vboxusb/002: permission denied: OCI permission denied

An error occurred

**Comment by pedrohqb** [comment]
Solved by installing crun and recreating the container. It seems runc is unable to consider that the user belongs to the vboxusers group and thus is unable to read /dev/vboxusb . That works on crun flawlessly.

**Comment by 89luca89** [comment]
Thanks @pedrohqb 

as we discussed in chat, crun works
