### ISSUE TITLE
[Error] FUSE mount created before a distrobox started not visable inside that distrobox

### ISSUE THREAD

**Issue by ghost** [89luca89/distrobox#427]
**Describe the bug**
FUSE mount created before a distrobox started won't work inside `distrobox`, an empty directory is given instead.

**To Reproduce**
1. Make sure distrobox is not running with `distrobox stop`
2. Mount a rclone remote under `~/.mount/`
3. Navigate to `~/.mount/`, make sure it has some files
4. `distrobox enter` and switch to mount point: `cd ~/.mount/`
5. `ls --all -l`

**Expected behavior**
Files and folders should show up.

**Logs**
Not applicable

**Desktop:**
- podman: 4.2.0
- distrobox: 1.3.1, 1.4.0

**Additional context**
`toolbox` works with fuse mount without racing condition issue.

**Comment by thjderjktyrjkt** [comment]
Ok it seems to be fixed after upgrading to 1.4.0.

```bash
> distrobox --version
distrobox: 1.4.0
```

```bash
> podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 22:42:17 2022
OS/Arch:      linux/amd64
```

**Comment by thjderjktyrjkt** [comment]
It seems to be an issue again and I don't know why.
FUSE mount was accessible, until I manually restarted the container with `distrobox stop` and `distrobox enter`, after that FUSE mount is no longer accessible.

**Comment by 89luca89** [comment]
@thjderjktyrjkt ok will check this :+1:

**Comment by thjderjktyrjkt** [comment]
Turns out `allow_other` doesn't matter, `rclone` has to mount after distrobox is started.
So if distrobox is restarted then fuse mount won't be visable in distrobox. Restarting `rclone` makes the mount reappear in distrobox.

**Comment by 89luca89** [comment]
Hey @thjderjktyrjkt can you provide some commands I can use to test this?

**Comment by thjderjktyrjkt** [comment]
Sure:

1. [Host] Install `rclone`

Check if it's installed:

```bash
rclone version
```

2. [Host] Configure the local backend

```bash
rclone config
```

- `n) New remote`
- name: `local`
- Storage> `local`
- Press enter
- Press enter again

3. [Host] Start distrobox

```bash
distrobox-enter
```

4. [Host] Mount your Downloads directory as FUSE with `rclone mount`

On Host, Not In Container:

```bash
mkdir ~/mount
rclone mount local:Downloads ~/mount
```

5. [Container] Check the mount directory in distrobox

In Container, Not On Host:

```bash
ls ~/mount
```

Make sure it has some files, if not then use your file manager to copy some files and do this step again.

6. [Host] Stop distrobox and start again

```bash
distrobox-stop
distrobox-enter
```

7. [Container] Check the mount directory in distrobox again

```bash
ls ~/mount
```

**Comment by thjderjktyrjkt** [comment]
If you unmount rclone and remount it again then it's reappearing in distrobox again.

Unmount:

```bash
fusermount -u ~/mount
```

Remount:

```bash
rclone mount local:Downloads ~/mount
```

**Comment by 89luca89** [comment]
Thanks a lot @thjderjktyrjkt 

will try this out!
