### ISSUE TITLE
Custom curl based installition is failing without error

### ISSUE THREAD

**Issue by michael-nischt** [89luca89/distrobox#429]
`curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local` (as described [here](https://github.com/89luca89/distrobox#curl))

![Screenshot from 2022-09-21 14-05-10](https://user-images.githubusercontent.com/500820/191499696-3521621f-c207-492d-9509-a80657104c8b.png)

No `~/.local/bin/distrobox` or anything else.

Tested on _Ubuntu 20.04.01 LTS_ and _Fedodra 37_.

**Comment by 89luca89** [comment]
Pushed a fix, seems like something is changed on how github offers the release page, and version scraping broke
Now It uses fixed version for latest release and it's working

You can try again in some minutes, time for the web caches to have the new script available

**Comment by michael-nischt** [comment]
Awesome, that was super quick and works fine now. :muscle:
