### ISSUE TITLE
[Error] Terminal emulator seems to be unaware of child process in distrobox

### ISSUE THREAD

**Issue by thjderjktyrjkt** [89luca89/distrobox#432]
**Describe the bug**
When user tries to close a terminal emulator while a process is still running, it prompts user whether to terminate them.

![image](https://user-images.githubusercontent.com/40300931/191938419-18d5f1e0-7daf-4946-beeb-f2aa06cf07c1.png)

This is however, not the case when `distrobox enter` is set as default shell command. In such case, terminal emulator window can be closed while leaving processes running.

**To Reproduce**
1. Open GNOME Terminal
2. Open settings, change profile settings so it runs `/usr/bin/distrobox-enter` on terminal starts
3. Open a new terminal, execute `sleep 30`
4. Before `sleep` runs out of time, try to close the terminal window

**Expected behavior**
The same "There is still a process running in this terminal" warning should show up. Closing the terminal kills all child processes.

**Logs**
Not applicable

**Desktop (please complete the following information):**
- podman 4.2.0
- distrobox 1.4.0

**Comment by 89luca89** [comment]
Interesting find :smile: 

I can reproduce, will investigate :+1:

**Comment by thjderjktyrjkt** [comment]
And this causes a lot of `fish` to keep running in background overtime, given the default terminal shell command is `distrobox-enter -- fish`.

**Comment by 89luca89** [comment]
I'd like to investigate this more @thjderjktyrjkt 

Would be interesting to know what gnome-terminal uses to catch this

**Comment by thjderjktyrjkt** [comment]
The issue appears to be that when `podman exec`, `conmon` is not a direct child-process of `gnome-terminal-server`.

![image](https://user-images.githubusercontent.com/40300931/197001066-10c8206e-b124-42c8-92e9-e1cc96b23277.png)

this is very likely caused by the fact `conmon` starts in a separate systemd scope, as you can observe with `systemd-cgls` command (also search for `vte-spawn` within the graph, each represents a terminal instance).

I guess a starting point would be investigating `--cgroups` parameter in `podman create`, but i would not give my hopes on it.

in the worst possible circumstance one would have to write its own trap program to terminate processes within container on `vte-spawn-.scope` destory.

to be honest this looks more like `podman` issue than `distrobox` issue. something like `--die-with-parent` (as [bwrap](https://github.com/containers/bubblewrap) has) isn't provided by `podman`, and it's reproducible with `toolbox run`.

**Comment by thjderjktyrjkt** [comment]
A clearer indication of the problem:

![image](https://user-images.githubusercontent.com/40300931/197006154-ab5121ea-718c-43aa-b3ad-eba269739f92.png)

(screenshot used `toolbox` but `distrobox` is in a similar situation)

when a `gnome-terminal` instance exits, `gnome-terminal-server` terminates the corresponding `vte-spawn` systemd scope making all its child-processes to terminate. but `conmon` isn't a child-process of `gnome-terminal-server` so it isn't affected. and because `conmon` is used to execute commands in container, they won't be affected either.

**Comment by thjderjktyrjkt** [comment]
potential solutions:
1. make `conmon` or the executed commands a direct child-process of `podman exec` instance
	- try achieving this by tweaking `podman create` parameters
	- probably won't work as expected, as this breaks boundaries made by systemd 
2. create a trap program that calls a session helper which runs the actual command within container, similar to [host-spawn](https://github.com/1player/host-spawn) or `systemd-run` does.
	- session helper needs to be capable of reliably detecting the presence of trap program
	- perhaps `host-spawn` or `systemd-run` could be (re)used?
	- might be over-engineered
3. ask podman devs to add `--die-with-parent` to `podman exec` and be done with it
	-  not sure if they'll listen though
4. investigate into replacing `podman` with `bwrap` and work on security isolation feature
	- benefits https://github.com/89luca89/distrobox/issues/28 and future flatpak integration
	- requires rewriting a large portion of `distrobox` codebase
	- too much for a basic functionality like this

**Comment by 89luca89** [comment]
Thanks for the investigation @thjderjktyrjkt !

As of now it seems indeed that it's not fixable on distrobox's side so I think I'll close this
About the point 4, I've already investigated it and sadly it's not easily doable and bwrap does not have some of the necessities for a seamless integrations (like the keep-id UID mappings)

Thanks again
