### ISSUE TITLE
[Suggestion] run checkbashisms on shell scripts as part of CI

### ISSUE THREAD

**Issue by michel-slm** [89luca89/distrobox#433]
**Is your feature request related to a problem? Please describe.**
The Debian package for distrobox has some lintian informational issues:
https://udd.debian.org/lintian/?email1=&email2=&email3=&packages=distrobox&ignpackages=&format=html&lt_information=on&lintian_tag=#all

These seem to be generated by checkbashisms (the issues match 1:1):

```
checkbashisms ./distrobox-init 2>&1 | grep -A2 possible
possible bashism in ./distrobox-init line 324 (time):
                apt-get install -y \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 374 (time):
                dnf install -y --allowerasing \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 438 (time):
                microdnf install -y \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 485 (time):
                pacman -Sy --noconfirm \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 525 (time):
                yes | slackpkg install -default_answer=yes -batch=yes \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 583 (time):
                xbps-install -Sy \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 624 (time):
                yum install -y \
                        "${shell_pkg}" \
--
possible bashism in ./distrobox-init line 980 ($UID should be "$(id -ru)"):
printf "test -z \"\$UID\"  && readonly  UID=\"\$(id -ur 2> /dev/null)\"\n" >> /etc/profile.d/distrobox_profile.sh
possible bashism in ./distrobox-init line 981 ($EUID should be "$(id -u)"):
printf "test -z \"\$EUID\" && readonly EUID=\"\$(id -u  2> /dev/null)\"\n" >> /etc/profile.d/distrobox_profile.sh
```

**Describe the solution you'd like**
While in this case these are all false positives (`time` here is a package to be installed; UID and EUID are tested first and conditionally defined), it's probably a good idea to run checkbashisms (in `devscripts` or `devscripts-checkbashisms`, https://command-not-found.com/checkbashisms) to flag these (and ignore the false positives). `shellcheck --shell=dash`  returns a clean bill of health, that should probably also be enabled if not already.

**Describe alternatives you've considered**
I'm also going to suppress this in the Debian package

**Additional context**

**Comment by 89luca89** [comment]
Was wondering on this @michel-slm 
Is there a way to "exclude" some errors?

Like with shellcheck we can, but here I'd like to avoid `grep -v` on stuff :joy:

**Comment by 89luca89** [comment]
Closing this, as `checkbashisms` is redundant with all the other linters we're using
