### ISSUE TITLE
[Suggestion] Align CLI semantics + documentation from `rm` and `stop`

### ISSUE THREAD

**Issue by almereyda** [89luca89/distrobox#436]
**Is your feature request related to a problem? Please describe.**

In continuation of #434, and given that the `distrobox` CLI semantics sometimes differs from the commands known from the Podman or Docker CLIs, it appears advisable to at least align the commands which are implemented in a way, that they resemble each other with similar functionalities.

**Describe the solution you'd like**

I would like to see (the documentation) of the `--force` and `-Y` flags of the `rm` and `stop` commands to converge on a single pattern. While it is possible to run `-Y` with `rm`, it is not documented.

```shell
$ distrobox rm -Y arch alpine-3-16
arch
f5028583fc187bf007f42360d32c412c2cca6dd5aab7806f83f73cca850d2e26
alpine-3-16
a2ceec867d8434d5595396e1521f72b13a2ecd0634ebfee155c08731f9bde1df
```

---

    distrobox stop --help | head -n 11

shows us in the dscriptions that a `-Y` flag exists (eventually aliased to `--force`?), but does not exemplify where to put it in the actual command after `docker-stop`.

```
distrobox version: 1.4.0

Usage:

	distrobox-stop --name container-name
	distrobox-stop container-name

Options:

	--name/-n:		name for the distrobox
	--yes/-Y:		non-interactive, stop without asking

```

    distrobox rm --help | head -n 5 | pbcopy

shows us that a `-f`/`--force` flag exists and where to put it (and undocumentedly aliased to `-Y`), but does not explain it within the `Options:` section below.

```
distrobox version: 1.4.0

Usage:

        distrobox-rm [-f/--force] container-name [container-name1 container-name2 ...]
```

**Describe alternatives you've considered**

An alternative can be to use the Podman/Docker CLIs directly.

**Additional context**

`--name/-n` is also inconsistently handled within the two help texts. The one for `stop` shows it in a separate execution line example, while the one for `rm` omits it[s possible location in the command] completely.

Also more generic flags to the `rm` and `stop` subcommands, which are most possibly inherited, like `--help/-h`, `--root/-r`, `--verbose/-v` and `--version/-V`, appear in different order within both `rm --help` and `stop --help` outputs.

**Comment by almereyda** [comment]
The discussion about being able to *stop multiple containers at once* continues here, too, together with the above.

**Comment by 89luca89** [comment]
Yep this issue suggests to make `stop` work like `rm` so this is included :+1:
