### ISSUE TITLE
[Suggestion] A `--clone` container that "tracks" changes to the container it was cloned from

### ISSUE THREAD

**Issue by dz4k** [89luca89/distrobox#443]
**Is your feature request related to a problem? Please describe.**
One disadvantage of containerized development is that you need to set up common dev tools in every container. This leads to using only one container as if it was the host machine, removing a lot of the benefits of containers.

I switched from toolbx to distrobox mainly because of the `--clone` feature. This lets me duplicate my main toolbox and add on a few more packages for projects.

However, if I decide to adopt a new tool for my development (say, test-drive a new editor for a few days) I'm back where I started: I need to install the tool on each container.

**Describe the solution you'd like**
It would be amazing to have a cloned container "track" its parent such that things installed on the parent can be used readily on the clone. Distro upgrades for several containers could be done at once.

Not sure if this is even possible. It seems like doing it at the filesystem level would just break things (e.g. if I run a distro upgrade on a child container, then install a package on the parent, what happens?)

**Describe alternatives you've considered**
Nix and Guix allow a similar workflow by making you write a program that can set up the whole system at any time, and only letting you modify the system by modifying that program. Then, you can write that program to invoke another program that sets up your base tools.

That is, if I understand Nix correctly. I couldn'f fully wrap my head around it.

I much prefer a model where I can install/uninstall packages and mess around with files on the system.

**Comment by 89luca89** [comment]
That would be cool :smile:  but with how `podman` and `docker` work, you cannot really do this as they are image based
You can keep an up-to-date common image you use as base for your containers, but you cannot have it dynamic

**Comment by dz4k** [comment]
Yeah, that's what I suspected... Thanks for your response & maintaining this great project!
