### ISSUE TITLE
[Suggestion] Allow adding a host device to the container

### ISSUE THREAD

**Issue by Minkiu** [89luca89/distrobox#444]
Hey! Thanks for this project!

**Is your feature request related to a problem? Please describe.**
It would be great if we could specify devices to be shared from the host to the container.

**Describe the solution you'd like**
Either on creation or entering, a way to specify `--device /dev/ppp`, for example, so that I can run a VPN within the container.

**Describe alternatives you've considered**
Running the VPN before entering the container, but since I'm in an unmutable OS i'd lose this every time the system upgrades.
Trying `distrobox create -n vpn-box -i ubuntu:20.04 -a "--device /dev/ppp" `  and `distrobox create -n vpn-box -i ubuntu:20.04 -a "--add-group nogroup --device /dev/ppp" ` (the `/dev/ppp` is in that group) do not seem to work, keep getting permission denied on the `/dev/ppp` within the container.

**Additional context**
podman/docker create actually allows this: 
https://docs.podman.io/en/latest/markdown/podman-create.1.html#device-host-device-container-device-permissions
https://docs.docker.com/engine/reference/commandline/create/

Cheers.

**Comment by Minkiu** [comment]
Ignore this, the `-a` flag seems to allow the requested behavior; so I guess I'll have to play with the `--add-group` or `cgroups`.

**Comment by 89luca89** [comment]
@Minkiu 

Technically you shouldn't need this, if running podman with `crun`
as by default all `/dev/` is shared (so all devices) and `--add-group keep-groups` is used

What you need to check is

1 - you're using `crun` as it's the one supporting `keep-groups`
2 - your host user is effectively able to interact with that device without sudo (so you're also in the group)

Alternatively, you can use a rootful container and use `sudo` inside it (**be aware that in rootful containers, root inside the container IS THE SAME as root on the host**)

**Comment by Minkiu** [comment]
Thanks for replying, will try those, for the time being I installed `openfortivpn` via pacman and then set the OS as immutable again after installing it... so far it works and the container is able to resolve urls correctly!
