### ISSUE TITLE
OCI Permission denied (rootless podman)

### ISSUE THREAD

**Issue by brokencode64** [89luca89/distrobox#447]
**Describe the bug**
When creating and trying to enter a distrobox container I get the following error:
```
Error: unable to start container "5b7b813ead8701f69101d858dcd8c36d2344613996c4d1dff348bd89727a30e5": crun: make `/home/username/.local/share/containers/storage/overlay/718fec8b99e5222fbb552febebdb2838c063825e3f9346d84782aa99d6264da4/merged` private: Permission denied: OCI permission denied
```
I can create containers and exec into them using podman without any issues, the issue only occurs when using distrobox. I have tried[ this solution ](https://bbs.archlinux.org/viewtopic.php?id=253966) but it does not work for me.

**Configs**
- _storage..conf_
```
[storage]
driver = "overlay"

runroot = "/run/user/$UID/podman-tmp"
graphroot = "$HOME/.local/share/containers/storage/"
rootless_storage_path = "$HOME/.local/share/containers/storage/"

[storage.options]
additionalimagestores = [
]

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
```

- _containers_.conf_
```
default_capabilities = [
  "CHOWN",
  "DAC_OVERRIDE",
  "FOWNER",
  "FSETID",
  "KILL",
  "NET_BIND_SERVICE",
  "SETFCAP",
  "SETGID",
  "SETPCAP",
  "SETUID",
  "SYS_CHROOT"
]

default_sysctls = [
  "net.ipv4.ping_group_range=0 0",
]

runtime = "crun"
```

- _distrobox_.conf_
```
container_always_pull="0"
container_user_custom_home="$HOME/.local/share/containers"
container_manager="podman"
non_interactive="1"
skip_workdir="0"
```

**To Reproduce**
1. Pull a container image with podman (works fine)
2. Run `distrobox create . . .` (seems to work fine)
3. Run `distrobox enter . . . ` (get the above error)

**Expected behavior**
1. Should be able to pull an image, create a container, and run `distrobox enter` to that container.

**Logs**
n/a

**Desktop (please complete the following information):**
 - Podman 4.2.1
 - Distrobox 1.4.1
 - ArchLinux 5.19.11

**Additional context**

**Comment by brokencode64** [comment]
> Hi @brokencode64
> 
> The problem is this config:
> 
> `container_user_custom_home="$HOME/.local/share/containers"`
> 
> This directory is reserved to podman, and you cannot use it, just use something else

Hi! I've removed this, removed all containers and tried again - I get the same error. Originally I was also running without this line but getting the same error.

**Comment by 89luca89** [comment]
Are you able to run a simple rootless podman?

Like:

```
podman run -it --ipc host --name "test" --network host --privileged --security-opt label=disable --user root:root --pid host --volume /:/run/host:rslave --volume /dev:/dev:rslave --volume /sys:/sys:rslave --volume /tmp:/tmp:rslave --volume /sys/fs/selinux --volume /var/log/journal --volume /run/user/1000:/run/user/1000:rslave --volume /etc/hosts:/etc/hosts:ro --volume /etc/localtime:/etc/localtime:ro --volume /etc/resolv.conf:/etc/resolv.conf:ro --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts --userns keep-id alpine:latest /bin/sh
```

**Comment by brokencode64** [comment]
So I can usually do a regular, rootless podman create and exec, but it seems I run into an issue with `--pid host`. If I remove this I can create and run a container.

**Comment by brokencode64** [comment]
Ok, running with the `--verbose` flag revealed there were permission issues with some dotfiles. I corrected that and it seems to be working now. Sorry for the trouble and thanks!

**Comment by nikp123** [comment]
I have the same issue, but ``--userns host`` failing instead. Though I am on NixOS, so that may be contributing to the issue here.
