### ISSUE TITLE
[Suggestion] Where's the best place to ask questions?

### ISSUE THREAD

**Issue by a9udn9u** [89luca89/distrobox#452]
I can't find any Distrobox questions on SO or SU, no subreddit, no Discord server. Here's probably not a good place to ask questions either. What's the available support channel?

BTW, my question is related to mouse cursor theme. I installed VS Code, it worked, but the cursor theme inside of the vsc window is different than my system theme. I'm on KDE but my GTK mouse cursor theme is the same as KDE.

**Comment by 89luca89** [comment]
Hi @a9udn9u 

there are links to Matrix and Telegram channel in the main page, I don't have (yet) discord nor reddit sorry

---

About the issue:

Are you on wayland? Because for me (on Gnome) QT apps do not pick my cursor theme (native and flatpaks, no difference)
If not, is the cursor theme in a special position? If yes, which one?

**Comment by a9udn9u** [comment]
Thank you for responding!

I'm on X11 (Steam Deck). Both GTK and QT apps pick up the same theme no problem, VSC is an Electron app I'm not sure if that's the reason, I was assuming it honors the GTK setting because in Ubuntu VSC picks up my system cursor theme.

My cursor themes are in standard locations, `/usr/share/icons` and `~/.local/share/icons`.

**Comment by 89luca89** [comment]
@a9udn9u 

Seems strange, I'm on GNOME, and the cursor theme is correctly detected (on wayland)
It does honor GTK theme indeed

Launching it from terminal, does it yield any useful logs?

**Comment by yajo** [comment]
I've had good experience with [github discussions](https://docs.github.com/en/discussions). It's enabled in a few clicks and helps with asynchronous support better than a chat room.

**Comment by poperigby** [comment]
@a9udn9u did you ever fix the cursor issue?
