### ISSUE TITLE
[Discussion] Migrate to a different system for installing packages during setup

### ISSUE THREAD

**Issue by orowith2os** [89luca89/distrobox#453]
Currently, Distrobox installs packages through whatever package manager binaries that it sees. This means that, for example, if there are placeholder binaries (as was the case with Crystal Linux) for other package managers, Distrobox will be confused on what package manager to use.

I suggest parsing the /etc/os-release or the proper containerenv-like file. Judging from the result, it could select the package manager and packages to install for utilities such as Mesa.

I am not suggesting to remove the binary-searching capability, but to prefer a different method of installing needed packages.

*This would be beneficial if, say, it was a Manjaro-like situation where some packages are named differently on the same package manager. For example, Fedora ships Firefox as `firefox`, whereas this may not be the case with an rpm-based distro like OpenSUSE.*

**Comment by 89luca89** [comment]
Yes it is a bit of a weak assumption the use of package managers
For example when someone uses dnf on OpenSUSE

But I also don't really like the idea of specifying one distro (and even versions of it) manually
For example, centos7 vs centos8 when they change from yum to dnf

It becomes really dispersive

But maybe we can find another way?

**Comment by orowith2os** [comment]
I think it might be possible to have a separate file for listing all of the packages and whatnot, aka not have them listed inside of the shell scripts.

Parsing the dockerfile, os-release, or whatever name seems to be the only way to achieve my suggestion, but there may be some other way.

**Comment by 89luca89** [comment]
Closing in favour or #744
