### ISSUE TITLE
[Error] Regression in Kerberos support on Fedora containers running on Ubuntu hosts

### ISSUE THREAD

**Issue by michel-slm** [89luca89/distrobox#454]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Containers created with distrobox after #323 is implemented does this:
```
if [ -d "/etc/krb5.conf.d" ] && [ ! -e "/etc/krb5.conf.d/kcm_default_ccache" ]; then
        cat << EOF > "/etc/krb5.conf.d/kcm_default_ccache"
# # To disable the KCM credential cache, comment out the following lines.
[libdefaults]
    default_ccache_name = KCM:
EOF
fi
```

This (borrowed from toolbox, which is meant to run on Fedora) assumes the host has KCM running. But this is not the case if the host is a stock Ubuntu install.

Having recreated my Fedora container, it now fails when attempting to run `kinit`, `kdestroy` or `klist` with

`klist: No KCM server found while resolving ccache`

**To Reproduce**
- install Ubuntu 22.04
- install Distrobox
- create a Fedora container
- enter the container
- klist

**Expected behavior**
klist should not output the KCM error

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

Irrelevant, nothing unusual there. Kerberos not installed on host.

**Desktop (please complete the following information):**
 - Are you using podman or docker?
   podman
 - Which version or podman or docker?
    3.4.4+ds1-1ubuntu1
 - Which version of distrobox?
   distrobox 1.4.1 on Ubuntu 22.04

**Additional context**

**Comment by 89luca89** [comment]
Looking at it, probably it is enough to check if krb5 is installed on the host
Is there any directory/file we can use as rationale for the test?

**Comment by 89luca89** [comment]
I've added a check for `/var/kerberos/` on the host, in order to trigger the integration only if the host has it installed :+1:
