### ISSUE TITLE
[Error] Exporting binary from within distrobox doesn't function

### ISSUE THREAD

**Issue by BrodieRobertson** [89luca89/distrobox#455]
**Describe the bug**

When attempting to export a binary from a distrobox the resulting file on my host system is unable to open said application and instead tries to use the path to the binary as the name of the distrobox

**To Reproduce**
When inside of the distrobox called videobox2, I want to export the application /usr/bin/kate so I run

`distrobox-export --bin /usr/bin/kate --export-path ~/.local/bin`

The resulting file looks like this, the name of the distrobox is missing
```
#!/bin/sh
# distrobox_binary
# name: 
if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ]; then
    /usr/bin/distrobox-enter  -n  --  /usr/bin/kate  "$@"
else
    /usr/bin/kate "$@"
fi
```

Upon running the export it thinks the name of the distrobox is instead the path to application
```
Error: No such container: /usr/bin/kate
Cannot find container /usr/bin/kate
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:36? [Y/n]:
```

**Expected behavior**
The line containing 
`/usr/bin/distrobox-enter  -n  --  /usr/bin/kate  "$@"`

Should say

`/usr/bin/distrobox-enter  -n videobox2 --  /usr/bin/kate  "$@"`

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
[export-logs.txt](https://github.com/89luca89/distrobox/files/9697044/export-logs.txt)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[docker-logs.txt](https://github.com/89luca89/distrobox/files/9697053/docker-logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? Docker
 - Which version or podman or docker? Docker version 20.10.18, build b40c2f6b5d
 - Which version of distrobox? distrobox version: 1.4.1

**Comment by misobarisic** [comment]
You need to specify a container name after `-n` when using `distrobox enter`.

**Comment by 89luca89** [comment]
Thanks @BrodieRobertson for reporting!

This seems a wrong assumption of mine, seems like not all systems are using cgroups with docker,
spinned up an Arch VM and indeed the output of:

```console
/ # cat /proc/self/cgroup
0::/
```

Does not indeed give back the Id/name of the container
Will need to find a way to do this, as I want to keep using the `/etc/hostname` content as a last resort, being it not reliable for
names with spaces/dots and so on

---

To fix this we need a way to access container's name or id from within the container

**Comment by 89luca89** [comment]
@BrodieRobertson 

pushed a fix for it.
In order to have it working, pull latest `git` version, install it.
You'll need to stop and start again your container to make it effective

**Comment by 89luca89** [comment]
It occurred to me that this fix introduces an unpleasant side effect, where exported apps and services will use the **long** id as suffix, next commit (integrated in #448 ) will fix this, simply using the names
