### ISSUE TITLE
[Error] Error: copying system image from manifest list

### ISSUE THREAD

**Issue by coreybruce** [89luca89/distrobox#457]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I tried to create a distrobox and it wanted to pull the images but ran into a issue

```
distrobox create -n test                                                                                                                                                                        127 ✘ 
Image registry.fedoraproject.org/fedora-toolbox:36 not found.
Do you want to pull the image now? [Y/n]: y
Trying to pull registry.fedoraproject.org/fedora-toolbox:36...
Getting image source signatures
Copying blob 61082f4917d7 done  
Copying blob 50c82c703913 done  
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:50c82c7039130aff7f1d1e304ff9de2ddfb86ec69129ca75ee1ac4f39d91c7a2": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /var/spool/mail: invalid argument): exit status 1

An error occurred

An error occurred
```

**To Reproduce**
 ```distrobox create -n test```

**Expected behavior**
Create a distrobox

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

Log: https://gist.github.com/coreybruce/a3090772c180dde65355c2de06ebbab7

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? Podman 4.2.0-1
 - Which version of distrobox?  1.4.1-1

**Comment by 89luca89** [comment]
Hi @coreybruce 
this is not related to distrobox, but to your rootless podman setup.

Please refer to your distro documentation or support forum to set it up

**Comment by coreybruce** [comment]
> Hi @coreybruce this is not related to distrobox, but to your rootless podman setup.
> 
> Please refer to your distro documentation or support forum to set it up

Oh ok what would be wrong with my podman setup exactly?

**Comment by coreybruce** [comment]
This issue isn't closed nor is it solved

I figured out the issue, would be nice if you actually put the effort into more documentation for Arch based distros no offence..

https://wiki.archlinux.org/title/Podman#Arch_Linux

https://forum.manjaro.org/t/no-etc-subuid-or-etc-subgid-files/119566

**Comment by 89luca89** [comment]
> This issue isn't closed nor is it solved
> 
> Looks like I have to do your job for you since I figured out the issue, would be nice if you actually put the effort into more documentation for Arch based distros no offence..

No of fence taken 😄 
But it's not my job

This is why in the documentation I clearly stated to check the arch wiki to set up rootless podman

It's not on me to document this, its already documented in the wiki and I've correctly linked this in the docs

If the wiki is missing something, they should update it, not me

Anyway thanks for the post

**Comment by coreybruce** [comment]
Would of just been better if you help walk me through podman otherwise I can't use your software and that's just lost users if they can't get support from the developer regardless of the distro they are using. :)

**Comment by coreybruce** [comment]
By the way is the Archlinux container supposed to be missing pacman?
