### ISSUE TITLE
[Error] Emacs always create .emacs on first launch inside container

### ISSUE THREAD

**Issue by gvannoye** [89luca89/distrobox#458]
**Describe the bug**
When launching emacs for the first time inside a fedora:36 container, the `~/.emacs.d` is ignored and `.emacs` is created.

**To Reproduce**
`distrobox create --name test-emacs`
`distrobox enter -n test-emacs`
`sudo dnf install emacs`
`emacs`

**Expected behavior**
Emacs should directly use the config files in `~/.emacs.d`

**Logs**
[https://pastebin.com/K9y1TLKZ](https://pastebin.com/K9y1TLKZ)

**Desktop (please complete the following information):**
 - Are you using podman or docker? I am using podman
 - Which version or podman or docker? version 4.2.1
 - Which version of distrobox? version 1.4.1

**Additional context**
I believe the issue might come from distrobox as toolbox does not seem to have this issue.
I understand this is a very niche issue, and I'm wondering if I should also contact the emacs mailing list for help

**Comment by 89luca89** [comment]
Do we have some sort of logging of emacs startup to see if there are problems reading that directory?

Distrobox (unless you use a custom home with `--home`) just shares the home dir with the container and nothing more, so I don't really know how it can influence what emacs does

**Comment by 89luca89** [comment]
@gvannoye I was thinking

Does installing `emacs` in the container create `/etc/skel/.emacs` by any chance?

Because skel files are used in the `init` to populate the home if not present

**Comment by 89luca89** [comment]
This is now fixed
Skel files are copied only when a custom home is used now :+1:

**Comment by gvannoye** [comment]
Indeed, this seemed to be the cause of the issue! Thanks a lot for your work
