### ISSUE TITLE
Run flatpaks inside distrobox

### ISSUE THREAD

**Issue by CicadaSeventeen** [89luca89/distrobox#462]
**Describe the bug**
Running arch in distrobox with podman, cannot use `flatpak`

**To Reproduce**
1, `distrobox create -i archlinux` and then enter it
2, installing `flatpak` by `pacman`
3, try to install `okular` but fail 

**Expected behavior**
Can install `okular` and run it, since I have managed to run `okular` installed by `pacman`

**Logs**
flatpak error:
```
sudo flatpak install org.kde.okular
Looking for matches?
F: An error was encountered searching remote ?fedora-testing? for ?org.kde.okular?: Unable to load summary from remote fedora-testing: While fetching https://registry.fedoraproject.org/index/static?label%3Aorg.flatpak.ref%3Aexists=1&architecture=amd64&os=linux&tag=testing: [52] Server returned nothing (no headers, no data)
F: An error was encountered searching remote ?flathub? for ?org.kde.okular?: Unable to load summary from remote flathub: Error opening file ?/var/lib/flatpak/repo/tmp/cache/summaries/flathub.idx?: Read-only file system
error: No remote refs found for ?org.kde.okular?
```
It seems that it try to load config from my host OS here, or else there is no reason to see 'fedora-testing'.

distrobox and podman log attached.
[log-distrobox.txt](https://github.com/89luca89/distrobox/files/9731356/log-distrobox.txt)
[log-podman.txt](https://github.com/89luca89/distrobox/files/9731357/log-podman.txt)

**Desktop (please complete the following information):**
Fedora Kinoite 36
podman version 4.1.1
distrobox: 1.2.15

**Additional context**
After several restarting it seems that I can install it. But it is really strange.

**Comment by CicadaSeventeen** [comment]
Update: Still cannot use flatpak. Installation fail because cannot connect to system bus

**Comment by 89luca89** [comment]
Not sure this is going to work smoothly as flatpak is a container technology, and nested containers can be quite the pain

The error you see is because the containerized environment cannot access system bus, you can try using `flatpak --user` to do stuff?

**Comment by CicadaSeventeen** [comment]
> Not sure this is going to work smoothly as flatpak is a container technology, and nested containers can be quite the pain
> 
> The error you see is because the containerized environment cannot access system bus, you can try using `flatpak --user` to do stuff?

If it can, `flatpak --user` will install software into `$HOME` which is outside of container.  Besides I try use `flatpak --user` but fail too.

**Comment by charims** [comment]
I think you need an init system running in order to run flatpak. Perhaps try with `distrobox create -i archlinux --init`

**Comment by juhp** [comment]
I don't think flatpak works even in toolbox?  So ya this is probably a stretch goal.
Is there a use-case (other than my host OS does not directly support flatpak)?

**Comment by 89luca89** [comment]
Running flatpaks (and snaps) **inside** distrobox is not an intended use-case, 
running them will require a separate init as already suggested

I'll leave this open if someone wants to investigate and maybe find a solution, but I'll remove the "bug" as It's not inherently a distrobox nor podman bug

**Comment by mistune** [comment]
I was able to get it to work just by installing flatpak from the repos inside the distrobox container and adding the `--init` flag during `distrobox create`.
