### ISSUE TITLE
Running a command with a non-zero exit code results in "An error occurred"

### ISSUE THREAD

**Issue by 0x0ade** [89luca89/distrobox#467]
**Describe the bug**
When running any command that "fails", `distrobox-enter` prints "An error occurred". When using `distrobox enter` instead of `distrobox-enter`, it does so *twice.*

`trap - EXIT` in `distrobox-enter` before running the user command helps with getting rid of at least one of the two prints. There's still the question of what to do with the trap in `distrobox` itself though, especially given how most (but not all) `distrobox-*` scripts already have their own error handlers. I was thinking of creating a PR which removes the handler in `distrobox` and puts it into the individual scripts if necessary, but don't know where it would be necessary 😅 

**To Reproduce**
```
$ distrobox enter ubuntu -- false; echo $?

An error occurred

An error occurred
1
```

**Expected behavior**
```
$ distrobox enter ubuntu -- false; echo $?
1
```

**Desktop:**
```
$ podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
$ distrobox version
distrobox: 1.4.1
```

**Comment by 89luca89** [comment]
You're right, the TRAP in `distrobox` wrapper is not needed :+1:
