### ISSUE TITLE
[Discussion] Deprecate the main distrobox command

### ISSUE THREAD

**Issue by orowith2os** [89luca89/distrobox#470]
The main `distrobox` command just redirects to the appropriate `distrobox-*` command at the moment.

I believe it would be appropriate to remove this, as it serves little to no purpose and it screws with tab completion in the terminal.

**Comment by 89luca89** [comment]
To be honest @orowith2os 
It is the other way around :joy: 

The `distrobox-foo` command is kept as a backward compatibility and direct-hit for a command, while the `distrobox foo` is more user friendly

Right now completion for me works correctly with latest version, if there are problems with that we need to fix that
