### ISSUE TITLE
Allow user to mount /tmp to a custom location.

### ISSUE THREAD

**Issue by RyanHakurei** [89luca89/distrobox#471]
**Is your feature request related to a problem? Please describe.**
Some software, such as Autodesk Maya, wants to use /tmp during installation, and even creating a root container does not allow the installer to write to temp. Attempting to mount /tmp to an alternate location produces
```
Creating 'Autodesk-Maya' using image quay.io/centos/centos:7	Error: /tmp: duplicate mount destination
```
**Describe the solution you'd like**
Allow the user to mount /tmp elsewhere instead of necessarily binding it to host's /tmp directory.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by 89luca89** [comment]
@RyanHakurei 
Seems strange that you cannot write to /tmp in the first place :thinking: 

Anyway /tmp is needed for some specific integrations
But you can use init-hooks to work around this:

`distrobox create -i quay.io/centos/centos:7 -n Autodesk-Maya --init-hooks "umount /tmp"`

This will unmount the /tmp every time the container starts and you'll have a separate /tmp
Be aware that this removes some integration with the host, notably Xorg integration
