### ISSUE TITLE
[Error] distrobox-enter complaining about paths not being on shared mount

### ISSUE THREAD

**Issue by giomatfois62** [89luca89/distrobox#473]
Hi,
I'm trying to use distrobox on Slackware64-current, using docker as a base.
I am able to create containers but I cannot enter them because of errors like:

`Error response from daemon: path /sys is mounted on /sys but it is not a shared or slave mount`

After reading the compatibility notes I tried making my root filesystem a shared mount using the suggested command 

`mount --make-rshared /`

but distrobox-enter keeps complaining with the same errors.
I tried also putting the comand in my rc.local file to have it run at each machine startup, and I verified that it's indeed making the shared mount using this command:

`findmnt -o TARGET,PROPAGATION /`

which returns:

`TARGET PROPAGATION`
`/      shared`

Now I really don't know what else to try.

My system details are the following:
- Distribution: Slackware64-current
- Kernel Version: 5.19.14
- Docker Version: 20.10.16

**Comment by 89luca89** [comment]
Hi @giomatfois62 

If the `mkshared` fix didn't work I'm not sure if something is wrong with either docker or the distro setup, and I cannot help here

Probably better ask in a Slackware support forum/channel as I cannot help

Sadly Slackware is not a distribution where distrobox is supported and tested
I'm sorry but I'm not able to help here
