### ISSUE TITLE
[Discussion] Any way to pass flags to `podman run` command?

### ISSUE THREAD

**Issue by FSund** [89luca89/distrobox#476]
I'm trying to figure out if it's possible to pass additional flags along to the `podman run` command when starting a distrobox. Specifically I'm looking to use the `--cpuset-cpus` [flag](https://docs.podman.io/en/latest/markdown/podman-run.1.html#cpuset-cpus-number) to limit the number of cpus the container has access to. Is this possible?

My current attempts got this far

```
$ distrobox enter -a "--cpuset-cpus='0-1'" --name testing
Container testing is not running.
Starting container testing
run this command to follow along:

 podman logs -f testing

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up dpkg exceptions...          	 [ OK ]
 Setting up apt hooks...                	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Executing init hooks...                	 [ OK ]

Container Setup Complete!
Error: unknown flag: --cpuset-cpus
See 'podman exec --help'

An error occurred

An error occurred
```

**Comment by thjderjktyrjkt** [comment]
I guess you need to pass that argument when creating distrobox (`distrobox-create -a`), since OCI container doesn't allow changing its environment after being created. Alternatively you may use SystemD resource control to limit the amount of CPUs it can use on the go (check `man systemd.resource-control`), you'll need to use unit override file.

**Comment by FSund** [comment]
> I guess you need to pass that argument when creating distrobox (`distrobox-create -a`), since OCI container doesn't allow changing its environment after being created. 

I was suspecting that I had to do it on creation. That's not compatible with the workflow I'm using, unfortunately.

> Alternatively you may use SystemD resource control to limit the amount of CPUs it can use on the go (check `man systemd.resource-control`), you'll need to use unit override file.

That sounds promising. Thanks!

**Comment by 89luca89** [comment]
@FSund 
As @thjderjktyrjkt suggested, there is a dedicated flag for it, but it needs a container re-creation

Neither podman nor docker support on-the-fly resource assignation/restriction so distrobox cannot provide it sadly
