### ISSUE TITLE
[Error] Cannot create and enter container of Debian Sid

### ISSUE THREAD

**Issue by CicadaSeventeen** [89luca89/distrobox#479]
**Describe the bug**
Cannot create and enter Debian SId container.
Can create Debian Stable container.

**To Reproduce**
```
distrobox create -i debian:sid -n sidtest
distrobox enter sidtest
```

**Expected behavior**
Entering the Sid container.

**Actually behavior**
Report `Segmentation fault (core dumped)`
[podmanlog.txt](https://github.com/89luca89/distrobox/files/9788333/podmanlog.txt)
[verbose.txt](https://github.com/89luca89/distrobox/files/9788335/verbose.txt)

**Desktop (please complete the following information):**
Podman 4.1.1
distrobox 1..4.1
Fedora Kde

**Comment by CicadaSeventeen** [comment]
Even if I provide all the commands `distrobox-init` needs, there will be also "Segmentation fault (core dumped)"

**Comment by juhp** [comment]
`podman run --rm -it debian:sid` works?

**Comment by CicadaSeventeen** [comment]
> `podman run --rm -it debian:sid` works?

Yes. It work as I expect.
I try to make a image with all commands `distrobox` needs, so that `distrobox` will not try to install packages into container. However, it still said "Segmentation fault (core dumped)".
I used to use `distrobox` version 1.2x (cannot remember clearly) so I updated to newest version to try but also failed.
I try both `podman`4.1.1 on Fedora and 3.0.1 on Debian but both failed.
If I update a Debian Stable to Sid, then if I exit if and then `distrbox enter` it, even though actually the container does not stop, I cannot enter it by `distobox` anymore. It just say "Segmentation fault (core dumped)". and exit.

**Comment by 89luca89** [comment]
@CicadaSeventeen 

The `init` command is working correctly, from the logs you provided
Could it be the default command not working?

Can you try

`distrobox enter -e /bin/bash` or `distrobox enter -e /bin/sh` ?
Because from the logs provided seems like nothing is wrong with the initialization of the `sid` container

**Comment by 89luca89** [comment]
@CicadaSeventeen any news on this?
