### ISSUE TITLE
GUI app doesn't launch if host is Arch Linux

### ISSUE THREAD

**Issue by peter15p** [89luca89/distrobox#480]
**Describe the bug**
I'm trying to run a simple GUI app in distrobox. 
If the host is running ubuntu or debian, the app works. 
If the host is running arch, the app does NOT launch.

**To Reproduce**
To simplify things I tested this in a virtualbox vm:

create vm with manjaro-kde-21.3.7-minimal-220816-linux515.iso

sudo pacman -Syu
sudo pacman -S docker   
sudo usermod -aG docker peter
sudo systemctl enable --now docker.service
reboot
docker run hello-world

curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
reboot

download BeyondCompare .rpm file from https://www.scootersoftware.com/download.php

distrobox create -i fedora:36
distrobox enter fedora-36
sudo dnf update
sudo dnf install ~/Downloads/bcompare-4.4.3.26655.x86_64.rpm 
exit

distrobox enter fedora-36 -v -- bcompare 

I see: An error occurred

**Expected behavior**
I should see the BeyondCompare GUI app in the host

**Logs**

**Desktop (please complete the following information):**
 - Are you using podman or docker? DOCKER
 - Which version or podman or docker? 20.10.18
 - Which version of distrobox? 1.4.1

**Additional context**
I retried these steps with a vanilla arch instead of Manjaro and the same thing happened.

**Comment by misobarisic** [comment]
Could you try entering the distrobox's shell and then trying to run the gui app?

The issue could be related to a misconfigured host x11.

Try looking into #329 and #409

**Comment by peter15p** [comment]
Thanks for the quick reply. Sorry I didn't find https://github.com/89luca89/distrobox/issues/329 before I posted my issue. That issue is almost identical to mine.

As shown in https://github.com/89luca89/distrobox/issues/329 running 
```
xhost +
```
fixed the issue.

Suggestion: enhance the host-side of distrobox to detect xhost permissions.

**Comment by brenoluz** [comment]
My host is arch and I was this problem:

Authorization required, but no authorization protocol specified
xterm: Xt error: Can't open display: :0

my $DISPLAY was :0
I changed to unix:0
export DISPLAY=unix:0

It's work now, I don't know if it is the same problem
