### ISSUE TITLE
[Error] Language support broken

### ISSUE THREAD

**Issue by CicadaSeventeen** [89luca89/distrobox#481]
**Describe the bug**
`distrobox` does not support non-English languages anymore. When I have files with name of other languages, strange bugs happen.
If I remember correctly, this bug does not occur in older version of `disrobox`, I will try to confirm it.
 
**To Reproduce**
1. Use newest version of `distrobox` with `podman`, entering whatever cantianer
2. Try inputting other languages into terminal.

**Expected behavior**
Can input like, Greek letters or Chinese characters like in normal terminal.

***actual behavior**
Cannot input Chinese characters.
Can input Greek letters, but when input `enter`, only thing here happens is just like this 
![image](https://user-images.githubusercontent.com/86961676/196044456-94659427-cdb2-4ea1-9b17-eff1be6b7bd2.png)

**Logs**
[podmanlog.txt](https://github.com/89luca89/distrobox/files/9795079/podmanlog.txt)
[verbose.txt](https://github.com/89luca89/distrobox/files/9795080/verbose.txt)

**Desktop**
podman 4.1.1
distrobox 1.4.1

**Comment by juhp** [comment]
Can you provide more details?  (Seems to work okay for me)

You are using distrobox-1.4.1.
What locale do you have?
Did anything else change on your system?  It was working before?

**Comment by CicadaSeventeen** [comment]
> Can you provide more details? (Seems to work okay for me)
> 
> You are using distrobox-1.4.1? What locale(s) do you have? Did anything else change on your system? It was working before?

Oh, I know why. I need to install locales and fonts and then start a new bash. Though programs like `apt` or `mousepad` can display correctly, bash need to be restarted.
