### ISSUE TITLE
[Discussion] can't install containers on distro box

### ISSUE THREAD

**Issue by dandidwi** [89luca89/distrobox#484]
please help, i want to install fedora 36 on distro box. But how come it can't and it says something like the one in the picture, and installing all containers other than fedora 36 is the same....
the distro that I use is Big Linux or a manjaro/Arch derivative distro

![image](https://user-images.githubusercontent.com/32098025/196615960-0aa4a8a0-9f67-4cb5-80c4-e3ba1ed89ee0.png)

**Comment by juhp** [comment]
Rebooting or restarting doesn't help, right?

**Comment by 89luca89** [comment]
@dandidwi 

Being on an arch derivative, you much probably don't have rootless podman correctly set up
As explained in the compatibility documentation [HERE](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md) you need to follow the arch-wiki instructions on how to set it up

**Comment by chinh4thepro** [comment]
First you need to setup your subgid and subuid, after setting it up do podman system migrate then it should work.
