### ISSUE TITLE
epel-release issue with sl7 and centos7

### ISSUE THREAD

**Issue by maroozm** [89luca89/distrobox#488]
I tried using sl7 and centos7 with distrobox. EVerything was fine unti i did
yum install -y epel-release
It cannot find epel-release. Plus if i try to use subscription-manager, it says:
Subscription cannot be used inside a container

This system is not registered with an entitlement server. You can use subscription-manager to register.

**Comment by 89luca89** [comment]
@maroozm hi,

I've tested with SL7 ande Centos:7 and both of them installed `epel-releasr` correctly

**Comment by maroozm** [comment]
I tested this on fedora again and the docker image for sl7 worked. but the above issue was faced on ssolus

**Comment by 89luca89** [comment]
Solus is not one of the Host distro officially supported
It shouldn't make a difference in this case, but I have to clarify it's not a supported platform

**Comment by maroozm** [comment]
but I tried it in pop os 22, with cent os 7. I still cannot install epel-release.

**Comment by alcir** [comment]
> EVerything was fine unti i did

Everything what?
Maybe it is a network issue?

**Comment by maroozm** [comment]
by everything i mean. i can install other packages but nothing in the epel-release. There are a lot of people who face this issue not with the distrobox but generally. eg. [https://access.redhat.com/discussions/5889431](url)

**Comment by maroozm** [comment]
Plus there is no internet issue because when I tried with fedora 36, it worked fine.

**Comment by alcir** [comment]
> There are a lot of people who face this issue not with the distrobox but generally. eg. [https://access.redhat.com/discussions/5889431](url)

But this issue is related to RHEL. Does subscription-manager is supposed to work on CentOS and other RHEL clones?

**Comment by alcir** [comment]
> yum install -y epel-release

What happens issuing this command?

**Comment by maroozm** [comment]
yes. unfortuately, all of the RHEL clones even rocky linux. It says:
unable to find epel-release

> No match for argument: epel-release
Error: Unable to find a match: epel-release

Then I found out you may need to use subscription-manager to first register and then you can get epel-release. but then it says

> subscription-manager is disabled when running inside a container. Please refer to your host system for subscription management.

I even tried tried to download epel-release rpm from [https://dl.fedoraproject.org/pub](url), but that would also not work

**Comment by alcir** [comment]
> Then I found out you may need to use subscription-manager to first register and then you can get epel-release. but then it says

But even if it would work inside a container, I think that subscription-manager is not supposed to work on CentOS and Rocky etc. because... there is nothing to subscribe to.

However, even if this doesn't look like a distrobox issue, could you please paste the exact output of 
`sudo yum install epel-release`

**Comment by maroozm** [comment]
> No match for argument: epel-release
Error: Unable to find a match: epel-release

**Comment by alcir** [comment]
mmm it looks like that this output doesn't mean that "I cannot find epel-release in the repository", but it looks like that _epel-release_ is treated as an an option of the former command.

Because if yum doesn't find a package, the message should be like:
```
[alessio@centos-7 ~]$ sudo yum install nonexistentpackagename
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: pkg.adfinis.com
 * epel: pkg.adfinis.com
 * extras: pkg.adfinis.com
 * updates: pkg.adfinis.com
No package nonexistentpackagename available.
Error: Nothing to do
```

**Comment by alcir** [comment]
And could you post the result of 
`sudo yum repolist`

**Comment by maroozm** [comment]
> Failed to set locale, defaulting to C.UTF-8
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.

This system is not registered with an entitlement server. You can use subscription-manager to register.

repo id                                          repo name
fedora                                           Fedora 36 - x86_64
fedora-cisco-openh264                            Fedora 36 openh264 (From Cisco) - x86_64
fedora-modular                                   Fedora Modular 36 - x86_64
updates                                          Fedora 36 - x86_64 - Updates
updates-modular                                  Fedora Modular 36 - x86_64 - Updates

**Comment by maroozm** [comment]
But there is a difference between my another fedora machine and this pop os one.
fedora uses an image of sl7 from docker.io/library/sl:7
and pop uses all of them (sl7, cent os7/8) from  registry.fedoraproject.org/fedora-toolbox:36

**Comment by maroozm** [comment]
> > Failed to set locale, defaulting to C.UTF-8
> > Updating Subscription Management repositories.
> > Unable to read consumer identity
> > Subscription Manager is operating in container mode.
> 
> This system is not registered with an entitlement server. You can use subscription-manager to register.
> 
> repo id repo name fedora Fedora 36 - x86_64 fedora-cisco-openh264 Fedora 36 openh264 (From Cisco) - x86_64 fedora-modular Fedora Modular 36 - x86_64 updates Fedora 36 - x86_64 - Updates updates-modular Fedora Modular 36 - x86_64 - Updates

Subscription manager errors go away when i sudo yum remove it. But the rest of output is same

**Comment by alcir** [comment]
> > Failed to set locale, defaulting to C.UTF-8
> > Updating Subscription Management repositories.
> > Unable to read consumer identity
> > Subscription Manager is operating in container mode.
> 
> This system is not registered with an entitlement server. You can use subscription-manager to register.
> 
> repo id repo name fedora Fedora 36 - x86_64 fedora-cisco-openh264 Fedora 36 openh264 (From Cisco) - x86_64 fedora-modular Fedora Modular 36 - x86_64 updates Fedora 36 - x86_64 - Updates updates-modular Fedora Modular 36 - x86_64 - Updates

Sorry but I'm in confusion.
These repositories are the ones of the Fedora host and not of a CentOS one.

**Comment by maroozm** [comment]
yes, i am confused too. i am using this command :
``distrobox-create -n sl:7 -n sl7
changing the names to centos, rocky linux etc
i tried this too
``distrobox-create -n docker.io/library/sl:7 -n slinux
but it is till using the image from
[registry.fedoraproject.org/fedora-toolbox:36](url)

**Comment by maroozm** [comment]
> toolbox

yeah sure. I mean I did a sudo yum update after distrobox enter xyz.
I also tried installing other packages. It worked fine for that

**Comment by alcir** [comment]
> distrobox-create -n sl:7 -n sl7

You are using "-n" two times.
The command should be 
`distrobox create -i sl:7 -n sl7`

**Comment by alcir** [comment]
> > toolbox
> 
> yeah sure.

Sorry, I meant distrobox.

**Comment by maroozm** [comment]
Sorry, i wasted a lot of your time. I think the issue was with n flag multiple times usage. By default, it was using fedora, which triggered the issue. I am really sorry.
