### ISSUE TITLE
[Error] When trying to enter a box, it fails with "unable to start container [...] OCI Permission denied"

### ISSUE THREAD

**Issue by plb-42** [89luca89/distrobox#489]
**Describe the bug**
When trying to enter any container (tested with an old arch container, a fresh arch container, and a fresh debian container) it quickly fails producing the following output:

```
Container arch is not running.
Starting container arch
run this command to follow along:

 podman logs -f arch

Error: unable to start container "0a997c563b2c1b153f05dbad670537bf5aac5b7d1b1b79e47fd362d589cc824e": runc: runc create failed: unable to start container process: error during container init: error mounting "/dev/vboxusb/003/002" to rootfs at "/dev/vboxusb/003/002": lstat /home/philipp/.local/share/containers/storage/btrfs/subvolumes/4b2c4598f00cc2892e77e42f293093ea31414e225c9b6064cd997223a3680a5e/dev/vboxusb/003: permission denied: OCI permission denied

An error occurred
```

Before this error started occurring, I started getting the following error in my arch container:

`sudo: /etc/sudo.conf is owned by uid 1000, should be 0 sudo: /usr/sbin/sudo must be owned by uid 0 and have the setuid bit set`

I removed that container and was planning to set up a new one, as this seemed to be the easiest solution. In course of that, the error started occurring.

I've found another user with a simmilar issue who was asked to run

`podman run --rm -ti --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash`

to diagnose wether the issue was with podman. This works without error for me.

**To Reproduce**
1. Create a new container (I've used `archlinux:latest` and `debian:latest`)
2. Try entering that container
Alternatively:
1. Try entering an existing container

**Expected behavior**
The container starts normally.

**Logs**
[podman_logs.txt](https://github.com/89luca89/distrobox/files/9880600/podman_logs.txt)
[distrobox_log.txt](https://github.com/89luca89/distrobox/files/9880605/distrobox_log.txt)

**Desktop (please complete the following information):**
 - openSUSE Tumbleweed x86_64
 - Are you using podman or docker? - Podmam
 - Which version or podman or docker? - 4.2.1
 - Which version of distrobox? - 1.4.1

**Additional context**
Tried rebooting and reinstalling distrobox.

**Comment by juhp** [comment]
I dunno - is it somehow related to using virtualbox??

**Comment by plb-42** [comment]
Now that you mention it, the error did appear after I switched from using the integrated VM in Android Studio to using a Virtualbox based solution on that machine. I'll try removing it and will report back whether that resolved the issue.

**Comment by plb-42** [comment]
I have removed virtualbox and all exiting distrobox containers, and removed and reinstalled both distrobox and podman. 

I have created three fresh containers, one based on debian:latest, one based on archlinux:latest, and one based on tumbleweed:latest. Debian and tumbleweed work fine, but arch fails to intialise with the following logs:

[distrobox_log.txt](https://github.com/89luca89/distrobox/files/9894802/distrobox_log.txt)
[podman_log.txt](https://github.com/89luca89/distrobox/files/9894803/podman_log.txt)

**Comment by 89luca89** [comment]
@Antiz96  the Archlinux one is a separate problem, which has just now been fixed in latest commit

**Comment by Antiz96** [comment]
@89luca89 My bad, I thought it was related... Thanks for the fix :smile:

**Comment by 89luca89** [comment]
Also @plb-42 

the virtualbox problem is an incompatibility of permissions between rootless podman with `runc` and VirtualBox.

You can solve by installing `crun` and recreating your containers (so that they will use `crun` instead of `runc`).
Arch problem that you mentioned has been resolved, and was not related to this issue.

**Comment by plb-42** [comment]
Thank you very much.
