### ISSUE TITLE
[Error] no DISPLAY environment variable specified

### ISSUE THREAD

**Issue by dmytri** [89luca89/distrobox#490]
When using distrobox-host-exec I get "no DISPLAY environment variable specified" though DISPLAY is in env and is correct

```
[dk@sys dk]$ echo $DISPLAY
:20
[dk@sys dk]$ distrobox-host-exec firefox
Error: no DISPLAY environment variable specified
```

it works as expected if I enter bash and then run firefox with DISPLAY set

```
[dk@sys dk]$ distrobox-host-exec bash
[dk@localhost dk]$ DISPLAY=:20 firefox
```

seems like distrobox-host-exec is removing the DISPLAY env

UPDATE:

looks like the issue is with flatpak-spawn

```
flatpak-spawn --host firefox
Error: no DISPLAY environment variable specified
```

But adding the env works

```
flatpak-spawn --host --env=DISPLAY=$DISPLAY firefox
```

Running in an archlinux container

```
pacman -Q flatpak-xdg-utils
flatpak-xdg-utils 1.0.5-1
```

Added an issue to upstream:

https://github.com/flatpak/flatpak-xdg-utils/issues/62#issue-1428265282

**Comment by misobarisic** [comment]
Cannot reproduce. Both `distrobox-host-exec firefox` and `flatpak-spawn --host firefox` work for me.

**Comment by dmytri** [comment]
> Cannot reproduce. Both `distrobox-host-exec firefox` and `flatpak-spawn --host firefox` work for me.

problem was with xinitrc not importing /etc/X11/xinit/xinitrc.d/
