### ISSUE TITLE
[Error] Distrobox refuses to launch RHEL

### ISSUE THREAD

**Issue by Tsu-gu** [89luca89/distrobox#491]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
RHEL9 refuses to launch and says an error.

**To Reproduce**
Install RHEL in distrobox

**Expected behavior**
RHEL should launch

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman or docker?
Podman
 - Which version or podman or docker?
podman version 4.2.1
 - Which version of distrobox?
distrobox version: 1.4.1

**Additional context**  
I'm aware of the message saying `Fatal glibc error: CPU does not support x86-64-v2` but my CPU (Intel(R) Core(TM)2 CPU         T7200  @ 2.00GHz x86_64) has never had problems with any distro, including Fedora I am running now, and it is the testing ground of RHEL.

In case the logs didn't get uploaded, here they are https://pastebin.com/0CDvvrYJ (distrobox) https://pastebin.com/mxvttWDU (podman)

**Comment by 89luca89** [comment]
Hi @Tsu-gu 

are you able to use `podman run --rm -ti registry.access.redhat.com/ubi9/ubi /bin/bash` ?

**Comment by Tsu-gu** [comment]
Hello, I'm afraid I can't
[sussy@lenovo-laptop ~]$ podman run --rm -ti registry.access.redhat.com/ubi9/ubi /bin/bash

Trying to pull registry.access.redhat.com/ubi9/ubi:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 0839fdcf3c33 done  
Copying config deaba7fe0b done  
Writing manifest to image destination
Storing signatures
Fatal glibc error: CPU does not support x86-64-v2

**Comment by Tsu-gu** [comment]
Oh well, that sucks. But luckily I don't need RHEL for anything, and was just curious about how it behaves and such. Thanks for your time anyways!

**Comment by 89luca89** [comment]
No problem :+1:
