### ISSUE TITLE
How to export a binary so that I can pass arguments to it from the host?

### ISSUE THREAD

**Issue by nu111** [89luca89/distrobox#492]
Hi, I am pretty sure that it's just me not understanding how it works...

I am trying Distrobox to have multiple versions of php available in the host. I have installed the flatpak version.

So I created the container
```
distrobox create --image alpine:3.11
```
then I entered the container
```
distrobox enter alpine-3-11
```
then from the container I installed php
``` 
apk add php-cli
```
then I export php as a binary
```
distrobox-export --bin /usr/bin/php7 --extra-flags "--foreground" --export-path $HOME/distrobox-bin
```
This works, from the host I can run the executable in `$HOME/distrobox-bin`, but if I try to pass arguments to it, they are ignored
```
./php7 -v

Error in argument 1, char 1: no argument for option -
Usage: php7 [options] [-f] <file> [--] [args...]
...
```
What I am missing?
Thanks!

**Comment by 89luca89** [comment]
The command you mentioned does not work because `--foreground` do not want other arguments.

I suggest to export it without `extra-flags`, and just call it with `--foreground` when needed.

**Comment by nu111** [comment]
Thanks, it works!
