### ISSUE TITLE
[Suggestion] Better support cases where an HTTPS Proxy is present

### ISSUE THREAD

**Issue by mtalexan** [89luca89/distrobox#493]
**Is your feature request related to a problem? Please describe.**
When entering a newly created distrobox instance, the `distrobox-init` is run to install the minimum necessary packages on top of the standard public distro images.  However many users in corporate environments have to pass thru an HTTPS proxy to reach these servers, and require custom CA certificates to do so.

**Describe the solution you'd like**
Add support for a custom certificates folder to the `distrobox.conf`.  Mount this read-only into all containers, and during `distrobox-init` add the certificates to the trust store/anchors prior to running any package manager commands.

**Describe alternatives you've considered**
The `--pre-init-hook` option could be used to do this with a custom script that uses the `mount_bind` function in `distrobox-init`.  However writing this to cover every supported distro isn't trivial and would do better if it were implemented consistently within distrobox itself given how common a use case this is likely to be.  Additionally it requires the user manually adding the proper `--pre-init-hook` to every `distrobox-create` call.

Creating custom distro container images that include the extra certificates is technically an alternative.  
This runs into the same issue that `distrobox-init` solves however.  Now custom images for every possible distro need to be maintained so the extra proxy CA certificates can be added.  

--- 

EDIT: I discovered the minimally documented `--pre-init-hook` and `--init-hook` options in `distrobox-create` and `distrobox-init`, which are very similar to what I originally described as one of the alternative options to add.

**Comment by mtalexan** [comment]
I just realized from reading the `distrobox-init` code that there's a minimally documented option `--pre-init-hook` that allows you to specify a custom script to run prior to the distrobox-init running.  
However the user workflow is expected to be:
1. `distrobox create`
2. `distrobox enter`
`distrobox-init` is usually called automatically (I can't even find where), and the `--pre-init-hook` option is not available from the `distrobox-enter` that will normally invoke `distrobox-init`.  Also, the `--pre-init-hook` is expected to run on the host system and is responsible for starting the container and executing commands within it if that's part of what's necessary, making it extremely involved for the simple and common case of needing to include extra CAs in the container.

**Comment by mtalexan** [comment]
From playing around with it, it appears at least Debian and Ubuntu images are cloud images that don't have even ca-certificates or basic tools installed in them when downloaded, but also do unauthenticated installation of packages (at least on first run).  For those the pre-init-hook can't do anything to help, but the init-hook could.

Fedora on the other hand fails during initial package installation if the HTTPS proxy's root CA(s) aren't already present in the system trust store before the first `dnf` call.

**Comment by mtalexan** [comment]
> Hey @mtalexan
> 
> From what I read, you can simply deploy per-users scripts and set up `pre-init-hooks` (that run _before_ the package management setup) and `init-hooks` (that run after)

From my deeper digging I found a few notable variations between distro images:  
Some distros deploy "cloud" images that are pre-configured to not use HTTPS for the initial package installs.  Those expect you to manually install the package(s) that add support for using HTTPS, and then subsequent package updates will use HTTPS.  The default Ubuntu image from distrobox is one of these types of images.    The non-"cloud" images (the default Fedora image is one of these) require CAs to be configured before the first attempt to install anything since all updates are always via HTTPS.
The Root CA certificate storage has 2 main types, the older type like what Ubuntu and Debian use, and the newer type like what Arch and Fedora use. In the older type there are a handful of directories that are searched recursively to find the Root CAs to re-compile into the single large file openssl (and friends) use from /etc/ssl/. In the latter type there are different directories with a more granular structure that adds additional support for customization, but also only allows new Root CAs to be added non-recursively to specific folders.  

Because of the differences between the "cloud" and non-"cloud" images, I found I had to write a hook script that would install the Root CAs if the tools/directories were present and skip it if not, and run the hook as both a pre-init and an init hook.  The "cloud" images will only have the destination folders present at init after some basic things have been installed, while the non-cloud images require the CAs to be installed at pre-init since they can't do the initial tool installations without them.  Working from the assumption the Root CAs are all in a flat folder (since some only support that format), there's only 2 directories that need to be looked for to figure out where to copy the Root CA files to.  Then it's just a matter of running whatever the distro-specific tool is for updating the compiled /etc/ssl file from the built-in customization folders.

**Comment by mtalexan** [comment]
Realistically the whole effort is basically just:
1. Look for Debian/Ubuntu destination folder existence
    1. Copy files from host into destination w/o overwrite and only if newer
2. Look for Fedora/Arch destination folder existence
    1. Copy files from host into destination non-recursively w/o overwrite and only if newer
3. If any files were copied, run the distro-specific CA updater tool (e.g. `update-ca-certificates`)
4. Repeat this logic both at pre-init time and at init time.

**Comment by mtalexan** [comment]
The complexity of figuring out how to do this for all the different distros is pretty annoying for someone not working with all the systems reguarly, and it takes some effort to make it efficient, which is the only reason I suggest making this part of the distrobox tool itself.

**Comment by 89luca89** [comment]
> The complexity of figuring out how to do this for all the different distros is pretty annoying for someone not working with all the systems reguarly, and it takes some effort to make it efficient, which is the only reason I suggest making this part of the distrobox tool itself.

At this point isn't easier to just use custom images for it?
One would build a whatever distro image with already pre-baked stuff for your corporate needs, and then distribute those internally

Because this is a level of complexity a bit too high and vague (in the numbers of implementations) to be handled directly bu distrobox
