### ISSUE TITLE
[Error] locale errors can break distrobox containers

### ISSUE THREAD

**Issue by insunaa** [89luca89/distrobox#495]
**Description:**
Depending on host locale containers fail slightly or catastrophically on the first and all subsequent `distrobox enter` commands.

The error message is just a useless/cryptic "An Error occurred."
On some distributions bash/zsh will still start after this error, but on other distributions (for example Arch Linux) no shell opens.

The workaround is to launch the container with `distrobox enter name -- fish` because `fish` doesn't crash when it can't set locales. Other distributions such as Debian require to then do `sudo apt install locales && sudo dpkg-reconfigure locales` to select the appropriate locale (otherwise you'll continue getting this error. For other distros it's different, arch requires `locale.gen` for example, etc. etc.

**To Reproduce**
- Have `en_US.UTF-8` as host locale
- Create any distro with distrobox
- Enter Distrobox
- Receive "An Error occurred"

**Expected behavior**
- Create any distro on distrobox
- Have the initialization script automatically install the locales packages and configure the locales for the respective distros
- Don't receive "An Error occurred"

**Logs**
N/A

**Desktop (please complete the following information):**
 - podman v. 4.3.0
 - distrobox v. 1.4.1
 
Host system: 
- Arch Linux
- Steam OS

**Additional context**
Tested this on my regular desktop and on my steam deck, both of them show this issue. On my desktop I can run the archlinux distrobox image, on my steam deck I cannot

**Comment by 89luca89** [comment]
This issue has been fixes as of commit https://github.com/89luca89/distrobox/commit/60bd7536cbb699ef5f3acc1808bda27024412c4f
