### ISSUE TITLE
Install distrobox 100% rootless a.k.a install podman without root

### ISSUE THREAD

**Issue by elyashivhazan** [89luca89/distrobox#496]
Hi, I wounder if its passable to install podman without root (this means not sudo, doas, etc).

I think Im realy asking "how to setup newuidmap rootless?"

From [extras/install-podman](https://github.com/89luca89/distrobox/blob/main/extras/install-podman)
```shell
echo "Setting up subuid and subgid, needed for rootless podman..."
echo "$(whoami):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid
```

**Comment by elyashivhazan** [comment]
> sudo is needed for literally just those two files since /etc/ is not user writable.
> 
> This seems to be a hard requirement of podman itself https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#etcsubuid-and-etcsubgid-configuration

Hi, thanks for the replay. So how can I achieve the ability to use distrobox in e.g a company laptop (BTW I understand we are talking about podman)?

**Comment by PgBiel** [comment]
Hey @elyashivhazan, can you try these instructions and report back? https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#install-podman-in-a-static-manner

**Comment by 89luca89** [comment]
@elyashivhazan 

Sadly that two files (/etc/subuid, /etc/sugid)  are needed to use rootless podman (and docker) 
There is no work around this

**Comment by elyashivhazan** [comment]
@89luca89 thanks for the answer.

I do not thinks its related but why use podman and not the `chroot` command? I always wandered (I do not know the pros and cons).

**Comment by 89luca89** [comment]
> @89luca89 thanks for the answer.
> 
> I do not thinks its related but why use podman and not the `chroot` command? I always wandered (I do not know the pros and cons).

Ease of use really, I'm also working on another project (https://github.com/89luca89/scatman) which indeed uses chroots, but to do everything as rootless, it will need `/etc/subuid` like podman anyway

**Comment by elyashivhazan** [comment]
@89luca89 good luck with that project and I hope you will added it to distrobox or better more (I think) use [scatman](https://github.com/89luca89/scatman) as distrobox replacement to have one bin.

I will close this issue, I got my answer. Thanks.
