### ISSUE TITLE
[Suggestion] An ability to trick the container that the programs are running on the host

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#498]
Like if you install neofetch and type neofetch in the container, it knows that it is in the container. what if there is a way to trick the container that it is on the real os. so if you type neofetch it displays the info about the host os instaid of the distrobox container.

**Comment by misobarisic** [comment]
You can use use host-exec to run processes on the host.
Running this inside the container `ln -s /usr/bin/distrobox-host-exec ~/.bin/neofetch` would make a symlink to host exec. After which you could just type `neofetch` inside the container shell and you would actually get neofetch from the host.

I don't know why you would want to fake running on the "host os" though.

**Comment by dankmemermusic** [comment]
im gonna try that
