### ISSUE TITLE
[Discussion] why nixos $SHELL must be bash?

### ISSUE THREAD

**Issue by yajo** [89luca89/distrobox#499]
Is your feature request related to a problem? Please describe.
I'm considering switching to NixOS for my main laptop. However, I work in a community of mostly Ubuntu people that maybe will never support nix. I'm convinced I'll hit problems such as https://github.com/pre-commit/pre-commit/pull/1938#issuecomment-997542256. OTOH I'm addicted to [Fish](https://fishshell.com/) and can't imagine my life with Bash again. 

Describe the solution you'd like
Being pragmatic, I'd like to use NixOS on my host, with Fish, and have an Ubuntu distrobox for cases where it's needed. 

Describe alternatives you've considered
Stay in my dear Fedora Silverblue and use nix wherever I can. 

Additional context

According to the docs, it's required to use bash for distrobox: https://github.com/89luca89/distrobox/blob/acb36a427a35f451b42dd5d0f29f1c4e2fe447b9/docs/compatibility.md?plain=1#L61

Why is that? Is there really no other option? 

Thanks!

**Comment by 89luca89** [comment]
Hi @yajo 

I don't use NixOS, that documentation was suggested by a fellow NixOS user :smile: 

You can try and see if it works anyway, I think that with the newer versions (where a lot of shell detection problems are fixed) will work no problem

If you confirm, I can remove that suggestion

**Comment by GermanBread** [comment]
I'm not OP, but I can confirm that distrobox works if `$SHELL` is not bash

**Comment by 89luca89** [comment]
Great, will update the docs accordingly thanks folks! :+1:
