### ISSUE TITLE
[Discussion] Export Steam games?

### ISSUE THREAD

**Issue by izzthedude** [89luca89/distrobox#500]
Is there a way to export games installed with Steam inside a distrobox container? I'm running a Fedora 36 container specifically for gaming purposes with Steam installed in it. I've tried running the following command to export Skyrim:

```
distrobox-export --app steam steam://rungameid/489830
```
This results in the following output:
```
grep: /home/MY_USER/.distrobox/gaming/.local/share/applications/The: No such file or directory
grep: Elder: No such file or directory
grep: Scrolls: No such file or directory
grep: V: No such file or directory
grep: Skyrim: No such file or directory
grep: Special: No such file or directory
grep: Edition.desktop: No such file or directory
^C
```
The reason I'm using `steam steam://rungameid/489830` is because this is what the `.desktop` file generated by Steam uses to launch the game. I'm not sure of any other alternatives to launch Steam games from the CLI. Below is the `.desktop` file for Skyrim:
```
[Desktop Entry]
Name=The Elder Scrolls V: Skyrim Special Edition
Comment=Play this game on Steam
Exec=steam steam://rungameid/489830
Icon=steam_icon_489830
Terminal=false
Type=Application
Categories=Game;
```

I have not tried this with any other games yet.

Here's some context for my setup:
Host OS: `Fedora 36 Workstation`
Using `podman version 4.2.1`
Using `distrobox: 1.4.1`
Container OS: `Fedora 36 Workstation`

Let me know if there's any more information I can provide about my setup. Thanks!

**Comment by 89luca89** [comment]
Not that I think of
To be honest this is outside of distrobox's scope, it is a generic "Userland" tool, adding something specific to Steam is not in my intention

**Comment by GitFo0** [comment]
Hey Buddy, I've found a way to launch steam game shortcuts.

I was curious how the distrobox-export --app command worked when I was able to export steam, so I ran `sudo find / -name "*.desktop" | grep "steam"` and found the `steam.desktop` shortcut. They way distrobox runs commands inside a distrobox after entering is `/usr/bin/distrobox-enter  -n ubuntu-20  --   steam steam://store`.

So you can make some shortcuts yourself, so, for example, to launch FTL (faster than light)

Create a <name>.desktop file, run chmod +x <name>.desktop then paste the below in it:

[Desktop Entry]
Name=FTL
Exec=/usr/bin/distrobox-enter  -n ubuntu-20  --   /usr/bin/steam steam://rungameid/212680
Type=Application
StartupNotify=true
Icon=
