### ISSUE TITLE
How to install a snapp app through distrobox?

### ISSUE THREAD

**Issue by nu111** [89luca89/distrobox#502]
Hi, I installed Fedora Kinoite on a VM and I'm exploring it, I am checking if it's possible to install a snap app to make it accessible to the host. Is there a suggested way to install a Snap app through distrobox?

It's seems not possible to make `snapd` run on a Ubuntu Container image
https://stackoverflow.com/questions/58385340/dockerfile-how-install-snap-snapd-unrecognized-service

I have found this workaround:
https://stackoverflow.com/questions/47859217/how-can-i-install-snapcraft-in-a-docker-image

but it referrers to this Docker image that seems outdated
https://hub.docker.com/r/snapcore/snapcraft

any clue on how to install a snap app with distrobox?

**Comment by thjderjktyrjkt** [comment]
Snap is not supported by Distrobox: https://github.com/89luca89/distrobox/issues/324#issuecomment-1179794085

Besides, Snap runs unconfined outside of Ubuntu: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro

Side question here, what specific apps do you want to use that are only available as snap?

**Comment by nu111** [comment]
Thanks for your reply,

> Side question here, what specific apps do you want to use that are only available as snap?

None in particular, I am just checking what I am losing migrating to Kinoite.
