### ISSUE TITLE
[connect to online docker server ]

### ISSUE THREAD

**Issue by try-ToUnderstand** [89luca89/distrobox#503]
how can I host for example docker in other host and connect to it so I only have the gui and the sound in my local machine and all the processing power and the storage in the other device and can I run distrobox on macos  how to completely isolate the container files  from the host so if I deleted the container all the files will be deleted

**Comment by try-ToUnderstand** [comment]
I know that this will cause problems for the applications that need port forwarding so I just need to use the  host that host docker ip or vpn but this will  be really useful for example if you add support for mac os if you have macbook you don't need to buy higher storage you can run your applications on your desktop and have more apps based on linux

**Comment by 89luca89** [comment]
Hi @try-ToUnderstand 

I suggest for this to use docker directly, as distrobox is thought and developed to run locally and integrate with the host

I'm not planning to support this type of usage as it's  incompatible for the scope of distrobox itself
