### ISSUE TITLE
[Error] Fails at "Setting up users"

### ISSUE THREAD

**Issue by nstgc** [89luca89/distrobox#504]
**Describe the bug**
Entering a box fails at "Setting up users".

**To Reproduce**
- Install podman with the provided rootless script.
- export path.
- Install distrobox.
- export path.
- Create a new box (I tried with `-i archlinux:latest` and `-i ubuntu:22.04`).
- Enter the box.

**Expected behavior**
I'm not entirely sure as I've never used this in a way that resulted in any other behavior, but from what I've read, as well as general expectations of how things work, I would think it would move past that stage to the next. Certainly, it wouldn't give me an error.

**Logs**

Excerpt for `podman logs` which also is the output of `podman enter --verbose`:
```
+ printf 'distrobox: Setting up users...\n'
+ '[' -d /etc/krb5.conf.d ']'
++ printf %s nstgc
++ tr '\\' .
+ grep -q '^nstgc:' /etc/passwd
+ usermod --home /home/db --shell /bin/bash --uid 1000 --gid 1000 nstgc
++ cat /proc/sys/kernel/random/uuid
+ temporary_password=495bb737-2e56-4234-8eef-c413fca71ee0
+ printf '%s\n%s\n' 495bb737-2e56-4234-8eef-c413fca71ee0 495bb737-2e56-4234-8eef-c413fca71ee0
+ passwd root
New password: Retype new password: passwd: password updated successfully
+ printf %s:%s nstgc 495bb737-2e56-4234-8eef-c413fca71ee0
+ chpasswd -e
+ printf %s: root
+ chpasswd -e
+ printf %s: nstgc
+ chpasswd -e
+ mkdir -p /etc/profile.d
+ printf 'test -z "$USER" && USER="$(id -un 2> /dev/null)"\n'
+ printf 'test -z "$UID"  && readonly  UID="$(id -ur 2> /dev/null)"\n'
+ printf 'test -z "$EUID" && readonly EUID="$(id -u  2> /dev/null)"\n'
+ '[' -d /etc/skel ']'
++ find /etc/skel/ -type f
+ skel_files='/etc/skel/.bashrc
/etc/skel/.bash_profile
/etc/skel/.bash_logout'
+ for skel_file in ${skel_files}
++ basename /etc/skel/.bashrc
+ '[' '!' -f /home/db/.bashrc ']'
++ basename /etc/skel/.bashrc
+ '[' '!' -L /home/db/.bashrc ']'
+ cp /etc/skel/.bashrc /home/db
cp: cannot create regular file '/home/db/.bashrc': Permission denied
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

In regards to `cp: cannot create regular file '/home/db/.bashrc': Permission denied`, I *do* have permission, and also this happens even when I use the default home directory. I actually was trying `/home/db` thinking there might be some kind of conflict. In particular `$ touch /home/db/.bashrc` succeeds. `/home/db/.bashrc` is, however, empty, so it did indeed fail to copy.

**Desktop (please complete the following information):**
 - `podman --version # => podman version 4.2.1`
 - `distrobox --version # => distrobox: 1.4.1`

**Additional context**
Running on an Arch Linux host. I have not yet tried installing via a more typical method. I'm trying to help a friend with a Steam Deck who does not have my usual methods at their disposal.

**Comment by 89luca89** [comment]
Hi @nstgc 

This should be fixed as of commit https://github.com/89luca89/distrobox/commit/a3e11a664ed0b2fe5fd0157666a5f38a0cc9c2f6

You can fetch latest `git` version using the curl installer, with the `--next` flag
