### ISSUE TITLE
[Suggestion] Add dconf/gsettings settings integration

### ISSUE THREAD

**Issue by amazingidiot** [89luca89/distrobox#506]
**Describe the bug**
Despite being writable, changes to any gsettings / dconf value are not saved but instead instantly reset. Happens in different distroboxes. In one distrobox for some reason installing gedit and running gsettings with sudo fixed the issue, but that was not reproducible in other distroboxes...

**To Reproduce**
- Create distrobox based on archlinux
- install dconf-editor
- run dconf-editor
- fail to set any settings persistently since they are not applied and reset to their default value instantly

**Expected behavior**
Settings are stored persistently

**Desktop (please complete the following information):**
 - podman version 4.3.0
 - distrobox: 1.4.1

**Comment by 89luca89** [comment]
This is working right now

**Comment by dmytri** [comment]
this doesn't work for me still

```
> distrobox --version
distrobox: 1.5.0.2
```

```
> gsettings set org.gnome.desktop.interface cursor-size 48
> gsettings get org.gnome.desktop.interface cursor-size
24
```

```
> distrobox stop appbox
[...]
> distrobox enter appbox
[...]
> gsettings get org.gnome.desktop.interface cursor-size
24
```
```
