### ISSUE TITLE
Zsh on Arch container leaves behind characters after exiting completion

### ISSUE THREAD

**Issue by sbancuz** [89luca89/distrobox#507]
Hi,
i know this might not be an issue with distrobox itself, but i really don't know where to submit this bug.

I created a new arch container and installed zsh, changed the default shell with `sudo chsh $USER -s /bin/zsh` and everything works fine (it even picks up my host's zsh configs with oh-my-zsh), but when i try to use autocompletion with tab sometimes it leaves some characters behind that are not part of the "command string buffer".

As you can see the part left behind from completion doesn't create any problems but it's just annoying.
As for the motivation why i submit this bug here and not to Konsole (terminal emulator i'm using) or zsh is because when i use zsh in my host system this doesn't happen.
*sample copy pasted from my terminal*
```
➜  ~ LA as ds
Assembler messages:
Error: can't open ds for reading: No such file or directory
➜  ~ is uname            
Linux
➜
```
The LA and is in the beginning of the command are never registered and as you can see the command after runs fine.

I'm on fedora Kinoite 36, kernel 6.0.5 (but i had this bug even before updating the kernel)
distrobox v1.4.1, podman v4.2.1 and the latest arch image

**Comment by sbancuz** [comment]
I'm probably not understanding something, but that command does literally nothing on my machine.
I tried with a new distrobox and the problem still persists, also tried on my laptop.

my .zshrc it's the standard that comes with oh-my-zsh with these plugins if it helps:
plugins=(git
    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)

**Comment by 89luca89** [comment]
Hi @sbancuz 

sorry I've given you the wrong command, try this: `podman run -ti archlinux:latest bash`

Then you install zsh and omzsh inside it with your configs, and try if it does the same problem

**Comment by sbancuz** [comment]
Hi, thanks for the help with podman, never really used it that much.
Installing the configs in the podman container doesn't give any problems, does distrobox enter mess with the shell in any way other than what podman does?

**Comment by juhp** [comment]
I am wondering if this could be related somehow to #398?

**Comment by sbancuz** [comment]
I think it's the same problem but the solution presented in that thread don't work for me.
I've checked $LANG = en_US.UTF-8, $TERM = xterm-256color and made containers.conf file in my .configs.

@89luca89 should i close this issue and move the discussion to #398?

**Comment by 89luca89** [comment]
@sbancuz Not sure if it's the same issue to be honest

So a plain podman container does not present this problem, this indeed is a distrobox issue and I'll need to do an investigation

**Comment by 89luca89** [comment]
> I also managed to connect to my arch container with vs code using the remote containers extension pack, and i don't see the problem. It still uses podman, but it manages to attach to the running container created by distrobox.
> 
> I suspect the bug is in the distrobox-enter script

Thanks, I'll try to reproduce this

Can anyone of you folks provide me a specific setup with zsh/omzsh that can reproduce this? Thanks

**Comment by charraut** [comment]
Hey, 

I have the same problems using distrobox. 
I run Fedora Silverblue as host and Ubuntu as container. Before distrobox I used toolbox for my containers with zsh too and I never encountered this issue. 

This bug appears almost everytime I use Ctrl + R in terminal (to get old commands)
