### ISSUE TITLE
supporting snaps (and by implication systemd) inside of containers

### ISSUE THREAD

**Issue by Danathar** [89luca89/distrobox#510]
I don't like snaps because of the daemon dependency, but unfortunately Canonical has a lot of weight. I went to install authy from twillo in a container (2 factor auth app) and found it was ONLY available as a snap.

This poses a problem. Both distrobox and (and toolbox) don't support running daemons with systemd. Snaps require snapd to be running before you can install a snap.

IS there any clean way of getting an internal systemd running inside a container of distrobox? There doesn't seem to be. This problem isn't going away. We can expect more and more places to support snap. They may or may not include flatpaks or the repositories.

**Comment by pulkitkrishna00** [comment]
You can run containers with systemd. Just add the --init option:
```
distrobox create --init --image ubuntu:22.04
```

But snaps will not work anyway. See #324.

**Comment by Danathar** [comment]
> You can run containers with systemd. Just add the --init option:
> 
> ```
> distrobox create --init --image ubuntu:22.04
> ```
> 
> But snaps will not work anyway. See #324.

Thanks. I followed the bug and read messages. Nasty. I can understand now why it's so difficult.

**Comment by Danathar** [comment]
> You can run containers with systemd. Just add the --init option:
> 
> ```
> distrobox create --init --image ubuntu:22.04
> ```
> 
> But snaps will not work anyway. See #324.

Thanks. I followed the bug and read messages. Nasty. I can understand now why it's so difficult.

**Comment by 89luca89** [comment]
Like already wrote in #462 

Running flatpaks (and snaps) inside distrobox is not an intended use-case,
running them will require a separate init as already suggested

I'll leave this open if someone wants to investigate and maybe find a solution, but don't expect for it to be supported soon

**Comment by 89luca89** [comment]
As of now, snapd inside init+root container works

Still not ideal, not advisable, and I'll not accept bugs for this
![image](https://github.com/89luca89/distrobox/assets/598882/c1e8f022-caf4-4d40-8a2d-0c23d7cbf09b)

**Comment by Danathar** [comment]
> As of now, snapd inside init+root container works
> 
> Still not ideal, not advisable, and I'll not accept bugs for this ![image](https://user-images.githubusercontent.com/598882/258935613-c1e8f022-caf4-4d40-8a2d-0c23d7cbf09b.png)

Thanks for this. I agree with you conceptually, but there are some distros that still use init instread of systemd and thus does help in those situations where only a snap is available
