### ISSUE TITLE
[Discussion] Add Managers: Singularity (and its descendant Apptainer)

### ISSUE THREAD

**Issue by tomeichlersmith** [89luca89/distrobox#511]
## Is your feature request related to a problem? Please describe.
I work as a core developer for the software a part of a physics experiment. As part of this experiment, we have container-ized our software stack in order to make it easier to develop. The computers in use are split between personal laptops (mostly running docker) and university-owned desktops/servers which mostly run [singularity](https://docs.sylabs.io/guides/3.5/user-guide/introduction.html) (now being evolved into [apptainer](https://apptainer.org/)). The solution we currently have is pretty similar to distrobox - we have a [shell script](https://github.com/LDMX-Software/ldmx-sw/blob/trunk/scripts/ldmx-env.sh) which defines shell functions to make it easier to interact with the container. This solution works _fine_ but it has many issues:
- It requires the user to use `bash`
- It opens and closes a container on each command to run inside the container. This is mainly because we _do not_ tightly integrate with the host environment/filesystem as distrobox does.
- It is horrible to maintain, test, and enhance.

### Describe the solution you'd like
I know supporting a new container runner is a big lift; nevertheless, the script listed above already shows a decent comparison on how the `docker` and `singularity` commands operate differently. Perhaps integrating a new runner is easier than I thought?

### Describe alternatives you've considered
My current best solution idea is to attempt to re-write the current bash script in Rust so it is still pretty fast but is easier to maintain, test, and enhance. Another alternative is to ask the folks at VS Code dev containers to support these runners, but that solution is less helpful because a lot of the computers we use do not have a GUI to launch VS Code with.

**Comment by 89luca89** [comment]
Hi @tomeichlersmith 

I'm not against integrating more runtimes (Like also LXC, containerd/nerdctl and so on)

But I want first to be able to make them "pluggable" instead of being monolithic like it's now

**Comment by tomeichlersmith** [comment]
Is #430 what you are talking about in terms of "pluggable"?

I am thinking about working on this and before I start I would just like to base my branch off the right developments.

**Comment by 89luca89** [comment]
Hi @tomeichlersmith 
Yes, that is the idea, but I didn't have much time to work on it, and the fork lagged behind the main implementation, and needs to be redone to reflect all latest changes  sadly

**Comment by tomeichlersmith** [comment]
No problem, I will experiment with reviving/reapplying those changes while working on enabling singularity/apptainer.
