### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by Quezio** [89luca89/distrobox#513]
Hi, where I work we have stationary Linux desktops which we share(so you can't install stuff onto it).
Because of this everybody just takes an external ssd with appimages to work and uses that.
If I could get distrobox working as an Appimage I could take my entire userspace with me. 

Is it possible to get distrobox working as an Appimage? I know that podmann works but also I am pretty new to all of this so sorry if what I'm asking is dump.
And no we can't boot from the personal  external ssd  because of some security reason nobody understands. 
Thanks for your help.

**Comment by elyashivhazan** [comment]
Hi, you dont need an appimage for distrobox just run this command: `curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local`.
This command is from the [docs](https://github.com/89luca89/distrobox#curl). Please note you need to set your PATH var like this: `export PATH="${HOME}/.local/bin:${PATH}"`

BTW you can put your appimages in this dir to just call them like an installed bin.

**Comment by Quezio** [comment]
Hi, jup there's an Appimage for Podman.
Will the command you have showed make distrobox really portable?
From my understanding it just installs it in a different directory without root. 
I sadly don't understand what you mean with the last part of your message.

**Comment by elyashivhazan** [comment]
Yes the command I wrote will just install distrobox in diff dir, but if you want it on your ssd (I assume you do, I just thought you mite just save your home dir on the ssd also) then just download distrobox to it:
```shell
# The ssd path is in /mnt/ssd
SSD_PATH="/mnt/ssd"

# This command will install distrbox at '/mnt/ssd/bin/distrobox*'
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix "${SSD_PATH}"

# Adding the scripts to your path so it can be run anywhere
# Add this command to your
# '~/.basrc' if using bash or to '.zshrc' (I think I dont remember) if using zsh
export PATH="${SSD_PATH}/bin:${PATH}"
```


In my last part I meant how do you setup podman to be used rootless (podman needs th subuid map), dose the admin of the system setting it up or you? Can you please link to the repo for podman's appimage?

**Comment by elyashivhazan** [comment]
I just found the appimage. [This](https://github.com/popsUlfr/podman-appimage) appimage will work only if the appimage is named `podman` or its linked like this `ln -s podman.appimage podman` ([appimage's docs](https://github.com/popsUlfr/podman-appimage#usage)).

**Comment by Quezio** [comment]
Hi, when I add the linie to my bash rc I get the bad substitution error..
The path to my ssd also is /media/mint
/(really long random string).
Could that be a problem?
The distrobox binary installed fine on the ssd. 
Sorry for the late response.

**Comment by elyashivhazan** [comment]
Hi, could you send your `.bashrc`?

**Comment by orowith2os** [comment]
You don't really want to AppImage distrobox, just download the `distrobox-*` scripts and run them like that. Making it an AppImage would be pretty useless, imo.

**Comment by 89luca89** [comment]
Hi @Quezio 

As already explained, there is no need for distrobox to be shipped as an Appimage
And I'm not interested in creating one either

Distrobox is a simple suite of self-contained scripts, you can just ship them in a directory
