### ISSUE TITLE
[Discussion] Integrate vscode

### ISSUE THREAD

**Issue by maroozm** [89luca89/distrobox#514]
How to integrate vscode (from host) to your distrobox? The documentation seems to be about flatpak only.

**Comment by orowith2os** [comment]
It's more or less the same, just don't use flatpak-spawn.

**Comment by maroozm** [comment]
vscode couldn't find my docker installation. So, i didn't tried to find much and instead vscode in my distrobox container. But i wanted to know if there is a way that i can get copilot to work? I installed inside the firefox, but it wouldn't open to authenticate copilot

**Comment by lbssousa** [comment]
Instructions described in https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md for host-side vscode are almost the same as for flatpak one. The only differences are the following:
* configuration file path is `${HOME}/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/your-distrobox-name.json`
* There's no need of any wrapper script for `flatpak-spawn`ing Podman. Just configure your Dev Container extension to use `podman` directly.

Maybe distrobox could provide a helper script to automate appropriate VSCode config creation.

**Comment by 89luca89** [comment]
> Maybe distrobox could provide a helper script to automate appropriate VSCode config creation.

I'm not a VSCode user, but contributions are welcome :smile:

**Comment by lbssousa** [comment]
I may try to contribute in the future. If anyone else wanna try it, these are the recommended steps to automate:

1. Create file `${XDG_CONFIG_HOME}/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/${YOUR_DISTROBOX_CONTAINER_NAME}.json` with the following minimal contents:
```json
{
  "remoteUser": "${localEnv:USER}",
  "settings": {
    "dev.containers.copyGitConfig": false,
    "dev.containers.gitCredentialHelperConfigLocation": "none"
  },

  // Not sure if this terminal setting is really needed
  "terminal.integrated.profiles.linux": {
    "distrobox": {
      "path": "${localEnv:SHELL}",
      "args": [
        "-l"
      ]
    }
  },
  "terminal.integrated.defaultProfile.linux": "distrobox",

  // Not sure if these environment variables are really needed
  "remoteEnv": {
    "COLORTERM": "${localEnv:COLORTERM}",
    "DBUS_SESSION_BUS_ADDRESS": "${localEnv:DBUS_SESSION_BUS_ADDRESS}",
    "DESKTOP_SESSION": "${localEnv:DESKTOP_SESSION}",
    "DISPLAY": "${localEnv:DISPLAY}",
    "LANG": "${localEnv:LANG}",
    "SHELL": "${localEnv:SHELL}",
    "SSH_AUTH_SOCK": "${localEnv:SSH_AUTH_SOCK}",
    "TERM": "${localEnv:TERM}",
    "VTE_VERSION": "${localEnv:VTE_VERSION}",
    "XDG_CURRENT_DESKTOP": "${localEnv:XDG_CURRENT_DESKTOP}",
    "XDG_DATA_DIRS": "${localEnv:XDG_DATA_DIRS}",
    "XDG_MENU_PREFIX": "${localEnv:XDG_MENU_PREFIX}",
    "XDG_RUNTIME_DIR": "${localEnv:XDG_RUNTIME_DIR}",
    "XDG_SESSION_DESKTOP": "${localEnv:XDG_SESSION_DESKTOP}",
    "XDG_SESSION_TYPE": "${localEnv:XDG_SESSION_TYPE}"
  }
}
```
2. **[OPTIONAL]** Create folder `/.vscode-server` within container, writable by normal user, and create a symlink `${HOME}/.vscode-server` pointing to `/.vscode-server`, if it doesn`t exist yet.

Notes:
* In Flatpak context, `XDG_CONFIG_HOME` points to `${HOME}/.var/app/com.visualstudio.code/config`. In host-system context, it normally points to `${HOME}/.config`.
* Additional steps are needed to make VSCode Flatpak interact with host-system Podman binary, which are out of scope of this solution.

**Comment by 89luca89** [comment]
All of this is plenty documented now

**Comment by teohhanhui** [comment]
`podman-host` as recommended in the [docs](https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md) does something weird / unexpected, symlinking `~/.vscode-server` to `/var/tmp/.vscode-server`, which seriously breaks vscode's remote extension host.

**Comment by f0nzie** [comment]
@89luca89, believe or not, the issue with integrating layered or OS installed vscode does not work consistently with distrobox containers. The podman-host script works beautifully with flatpak-vscode, but it doesn’t with with OS-installed vscode. If instead of setting podman-host, we set the podman executable, vscode will login to the container as root, not as the default user. By seeing the enormous amount of queries in the internet on the vscode to distrobox integration you can tell that the use of distrobox is growing but with lot of frustration and pain.

**Comment by teohhanhui** [comment]
@f0nzie
> If instead of setting podman-host, we set the podman executable, vscode will login to the container as root, not as the default user. 

This is an annoying problem, but it can be solved by choosing "edit current container config" from the vscode command palette (Ctrl-Shift-P), and then adding `"remoteUser": "${env:USER}",`

Unfortunately you can't do that before attaching to the container for the first time, unless you choose to create a container config (but that's per project, I think).

https://github.com/microsoft/vscode-remote-release/issues/1996#issuecomment-2112987948

**Comment by lbssousa** [comment]
> @89luca89, believe or not, the issue with integrating layered or OS installed vscode does not work consistently with distrobox containers. The podman-host script works beautifully with flatpak-vscode, but it doesn’t with with OS-installed vscode. If instead of setting podman-host, we set the podman executable, vscode will login to the container as root, not as the default user. By seeing the enormous amount of queries in the internet on the vscode to distrobox integration you can tell that the use of distrobox is growing but with lot of frustration and pain.

If you look for a more consistent way to configure VSCode integration with Distrobox, working for both Flatpak and host-installed versions, you can create a symlink named `$HOME/.var/app/com.visualstudio.code/data/node_modules/bin/podman`, pointing to `/app/bin/host-spawn`(VSCode Flatpak now bundles [host-spawn](https://github.com/1player/host-spawn)).

Then, you can configure Docker path in VSCode Dev Container settings as just `podman`, instead of `/path/to/podman-host`.

**Comment by f0nzie** [comment]
Thanks @teohhanhui .

> This is an annoying problem, but it can be solved by choosing Dev Containers: Open Named Configuration File from the vscode command palette (Ctrl-Shift-P), and then adding "remoteUser": "${env:USER}",

That gave me a hint, combined with one of the old posts from @lbssousa.
The trick is on creating an exclusive *.json* configuration file for each of the distroboxes you plan to enter in for development beforehand.

This vscode configuration file creation will not occur automatically; you will have to create the folder `nameConfigs` under `${HOME}/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/`, and then drop  your  .json configuration files in there.

The user has to create the folder with 
```
 mkdir ${HOME}/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs
```
And then, add the json config file in there. Assuming, as an example, that my distrobox is named `conky-nvidia`:
```
touch  ${HOME}/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/conky-nvidia.json
```

And add these lines:
   ```json
     {
        "remoteUser": "${localEnv:USER}",
        "settings": {
           "dev.containers.copyGitConfig": false,
           "dev.containers.gitCredentialHelperConfigLocation": "none"
         }
      }
   ```

After that, I can access the distrobox from within **host-installed** vscode!

**Comment by lbssousa** [comment]
I summarized all my knowledge about this subject in the following Gist:

https://gist.github.com/lbssousa/bb081e35d483520928033b2797133d5e
