### ISSUE TITLE
[Error] arch-linux missing

### ISSUE THREAD

**Issue by ralyodio** [89luca89/distrobox#518]
can't install arch linux.

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

➜  ~ 
$ distrobox create -i docker.io/library/arch-linux:latest
Image docker.io/library/arch-linux:latest not found.
Do you want to pull the image now? [Y/n]: y
Error response from daemon: pull access denied for arch-linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

An error occurred

An error occurred
➜  ~ 
$ distrobox create -i arch-linux                         
Image arch-linux not found.
Do you want to pull the image now? [Y/n]: 
Using default tag: latest
Error response from daemon: pull access denied for arch-linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

An error occurred

An error occurred

**Comment by ralyodio** [comment]
This works (remove `-`)

`$ distrobox create -i archlinux `

**Comment by 89luca89** [comment]
@ralyodio 

docs do not report arch-linux anywhere, it was already wrote correctly in the docs.
