### ISSUE TITLE
Slow startup using `distrobox-enter`

### ISSUE THREAD

**Issue by ejuarezg** [89luca89/distrobox#519]
Hi,

I recently started using distrobox in Fedora Silverblue and noticed a similar issue I had experienced before in another system. Entering a container takes about a 1-2 minutes. Checking the output of the process shows that it waits on the following lines the majority of the time:

```
distrobox: Setting up host's sockets integration...
++ find /run/host/run -name user -prune -o -name nscd -prune -o -name bees -prune -o -name system_bus_socket -prune -o -type s -print
```

I am running the latest stable version of distrobox on a fresh installation of Fedora Silverblue. The container is question runs Arch Linux.

**Comment by 89luca89** [comment]
Hi @ejuarezg 

Can you send the logs of podman while the container is starting?

Also can you provide the output of that command while ran inside the distrobox? 

Thanks

**Comment by 89luca89** [comment]
mmh seems nothing wrong 
Except for `/run/host/run/media/FlightData`
Is that some mount or network mount? That might explain the sluggishness on wifi

**Comment by ejuarezg** [comment]
Yes, that directory is a network mount. Would you know of a quick way or hack to exclude it from the container startup process?

**Comment by 89luca89** [comment]
Hi @ejuarezg 

I'll do a patch to exclude `/run/host/run/media` from the socket search, as it indeed does not make sense to search there :+1:

**Comment by 89luca89** [comment]
Fixed as of latest commit :+1:

**Comment by ejuarezg** [comment]
Thank you for your help
