### ISSUE TITLE
[Error] distrobox on steam deck error creating "holoiso" box

### ISSUE THREAD

**Issue by DarkenLX** [89luca89/distrobox#521]
terminal output plus commands issued:
 
distrobox-create --image holoiso:latest  --name holo
Image holoiso:latest not found.
Do you want to pull the image now? [Y/n]: y
✔ docker.io/library/holoiso:latest
Trying to pull docker.io/library/holoiso:latest...
Error: initializing source docker://holoiso:latest: reading manifest latest in docker.io/library/holoiso: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

**To Reproduce**
execute distrobox-create --image holoiso:latest  --name holo
fails to pull from any of the three sources presented other two sources just error out saying repo not found
**Expected behavior**
pulls and installs holoiso aka steamos within distrobox for developing purpose.

**Logs**
[log.txt](https://github.com/89luca89/distrobox/files/10053817/log.txt)

**Desktop (please complete the following information):**
using podman
podman version 4.2.1
distrobox version 1.4.1

**Additional context**

**Comment by 89luca89** [comment]
Hi @DarkenLX 

That image does not exist, probably you're searching: `thevakhovske/holoiso:latest`

**Comment by DarkenLX** [comment]
> Hi @DarkenLX
> 
> That image does not exist, probably you're searching: `thevakhovske/holoiso:latest`

That's what im trying to pull so do i type thevakhovske/holoiso:latest in place of holoiso:latest ?

**Comment by 89luca89** [comment]
Yes

**Comment by DarkenLX** [comment]
> Yes

ok that work but upon entering i get this

distrobox enter --name holo
Container holo is not running.
Starting container holo
run this command to follow along:

 podman logs -f holo

 Starting container...                           [ OK ]
 Installing basic packages...                    Error: An error occurred

An error occurred

An error occurred
