### ISSUE TITLE
[Suggestion] Detect host arch during Podman installation

### ISSUE THREAD

**Issue by parkerlreed** [89luca89/distrobox#522]
Podman installation script currently assumes amd64. However, arm64 versions of all the tools are available

Possibly detect the `uname -i` output and set the architecture accordingly into a variable

For Ubuntu that returns `aarch64` on ARM platforms

Was able to use the podman installation script as is after a `sed 's/amd64/arm64/g' -i install-podman`

**Comment by 89luca89** [comment]
Thanks @parkerlreed 

Will investigate this :+1:

**Comment by LukeShortCloud** [comment]
For reference, AMD and Intel report this on Fedora:

```
$ uname -i
x86_64
```

**Comment by 89luca89** [comment]
This is now unsupported
If one needs to install podman they can use the podman-launcher project
