### ISSUE TITLE
[Suggestion] Allow separate `XDG_RUNTIME_DIR`

### ISSUE THREAD

**Issue by ghost** [89luca89/distrobox#523]
**Is your feature request related to a problem? Please describe.**
distrobox's session bus shares with host user's real session bus, as per:

> ```bash
> 	# Mount also the XDG_RUNTIME_DIR to ensure functionality of the apps.
>	if [ -d "/run/user/${container_user_uid}" ]; then
>		result_command="${result_command}
>			--volume /run/user/${container_user_uid}:/run/user/${container_user_uid}:rslave"
>	fi
> ```

https://github.com/89luca89/distrobox/blob/1.4.1/distrobox-create#L518

This is not a problem for most use cases, or rather without it many apps would be outright broken due to the lack of session bus. However, this doesn't work well with dedicated init support.

Once you've set up a distrobox with init system, followed [this guide](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#use-distrobox-to-install-different-flatpaks-from-the-host) and installed some flatpak apps, you'll notice some apps are broken, and only one instance of the same Flatpak app from either host or distrobox can run at the same time. Running the second instance automatically brings up the previous running instance, no matter if it's on host or in distrobox, this generally applies to all applications that make use of dbus activation to handle multiple instances. [VSCodium](https://flathub.org/apps/details/com.vscodium.codium) on the other hand, refuses to start in distrobox all together.

systemd's user session are also broken, as session bus is shared but PID is not, therefore `busctl --user` shows many unknown sockets and `systemctl --user` is completely unusable.

Manually starting and stopping user session bus within container causes more breakages:

```bash
# within distrobox
sudo systemctl start "user@$(id -u).service"
sudo systemctl stop "user@$(id -u).service"
```

And now your host user's session bus is gone (`ls "$XDG_RUNTIME_DIR/bus"`). your host flatpak apps are all broken and you need to terminate your user session on host.

**Describe the solution you'd like**
Always make a separate `XDG_RUNTIME_DIR` when dedicated init system is used within distrobox because dedicated init system won't work well with shared session bus anyway.

**Describe alternatives you've considered**
Add a new custom flag which turns off `XDG_RUNTIME_DIR` sharing.

**Additional context**
The issue can be worked around right away. Append `--dry-run` to `distrobox-create` command:

```bash
distrobox create \
    --image $IMAGE \
    --init \
    --init-hooks "umount /var/lib/flatpak" \
    --name $NAME \
    --dry-run
```

this will get you a messy output. Search for `--volume /run/user/1000:/run/user/1000:rslave` (replace `1000` with your real UID) and replace it with `--tmpfs /run/user`, then proceed executing the command. After that, `distrobox-enter` and execute:

```bash
# within distrobox
sudo systemctl start "user@$(id -u).service"
```

And now you have a separate session bus, inside your distrobox. You can now proceed installing Flatpak apps, or messing around systemd user service.

**Comment by 89luca89** [comment]
This has been implemented, now initful containers will start their own user@.service
