### ISSUE TITLE
-H and --home doesn't work

### ISSUE THREAD

**Issue by dpe0** [89luca89/distrobox#531]
**Describe the bug**
-H and --home doesn't work

**To Reproduce**
```
distrobox create --name test --home /home/username/testfolder
distrobox enter test
ls
```
it still shows my host home folder

**Expected behavior**
it sets the home folder to testfolder

**Logs**
latest version of distrobox with default settings in fedora 37
```
banana@fedora ~]$ distrobox create --name test --home /home/banana/distrobox/test
Creating 'test' using image registry.fedoraproject.org/fedora-toolbox:36	 [ OK ]
Distrobox 'test' successfully created.
To enter, run:

distrobox enter test

test
[banana@fedora ~]$ distrobox enter test
Container test is not running.
Starting container test
run this command to follow along:

 podman logs -f test

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up rpm exceptions...           	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up rpm exceptions...           	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Executing init hooks...                	 [ OK ]

Container Setup Complete!
[banana@test banana]$ ls
 Desktop   distrobox   Documents   Downloads   Music   Pictures   Public   Templates   Videos

```

**Comment by misobarisic** [comment]
You should pass `--no-workdir/-nw` such as `distrobox enter -nw test`

**Comment by dpe0** [comment]
> You should pass `--no-workdir/-nw` such as `distrobox enter -nw test`

thanks. Can I ask, how does it know what my home directory is if I changed it

**Comment by 89luca89** [comment]
Hi @dpe0 

As explained in the docs, `--home/-H` does still mount your main home to ensure the integration
It only sets the $HOME variable to another dir *inside* the container, so that (for example) dotfiles or stuff like that goes to another dir, leaving your host's home clean

You can verify that, entering that container, issuing a `cd` command, will bring you not to the host's home, but to the directory specified in `--home/-H`

**Comment by profetik-777** [comment]
> > You should pass `--no-workdir/-nw` such as `distrobox enter -nw test`
> 
> thanks. Can I ask, how does it know what my home directory is if I changed it

Did this resolve ? If not, follow up otherwise @89luca89 can prob close this.
