### ISSUE TITLE
[Error] Couldn't able to install package in ubuntu container

### ISSUE THREAD

**Issue by sonulohani** [89luca89/distrobox#533]
**Describe the bug**
While installing any package in the ubuntu-22.10 container I get this error
```
/etc/localtime is a mountpoint
umount: /etc/localtime: target is busy.
E: Problem executing scripts DPkg::Pre-Invoke 'if mountpoint /etc/localtime; then umount /etc/localtime; fi'
E: Sub-process returned an error code
```

![image](https://user-images.githubusercontent.com/2958681/204079365-b47c2b99-e5ea-40b0-97ca-7a644ec11085.png)

**To Reproduce**
sudo apt install neofetch

**Expected behavior**
Should be able to install the package successfully

**Desktop (please complete the following information):**
 - Are you using podman or docker?
  Podman
 - Which version or podman or docker?
 podman version 4.2.1
 - Which version of distrobox?
 distrobox version: 1.4.1

**Comment by black-desk** [comment]
seems duplicate with #426
