### ISSUE TITLE
[Suggestion] Custom distrobox-upgrade commands

### ISSUE THREAD

**Issue by myuujiku** [89luca89/distrobox#536]
**Is your feature request related to a problem? Please describe.**
Hi, being able to run distrobox-upgrade --all to update every container without having to enter them is cool. This however doesn't work if you want to use another packaging format in your distrobox (e.g. an AUR helper, flatpaks (in theory, I didn't test that), etc.).

**Describe the solution you'd like**
Being able to set a custom upgrade command for each distrobox.

**Describe alternatives you've considered**
A global "config" or some file that you can edit would be enough.

**Additional context**
I tried editing "/bin/overlay" but I couldn't find a way to make any changes to the file. Is is possible to do that? If so, an easier implementation would be much appreciated, although not strictly necessary. Thanks for your time!

**Comment by 89luca89** [comment]
The idea is to support only the official package managers of the containers, it will become a huge burden to the project to support all hundreds of different and unofficial package managers

What about using (Topgrade)[https://github.com/r-darwish/topgrade] for this case?

**Comment by myu-jiku** [comment]
> The idea is to support only the official package managers of the containers, it will become a huge burden to the project to support all hundreds of different and unofficial package managers

Yes, I get that. My idea was not for distrobox to support these package managers, but to support adding a custom upgrade command. This however could be very difficult to implement in its own right, so I get if that is not an option either.

> What about using [Topgrade](https://github.com/r-darwish/topgrade) for this case?

Generally this seems like it could work. Is support for that already implemented? Though I'd like to point out that the original repository is not maintained anymore. There is a [fork](https://github.com/topgrade-rs/topgrade) however and it seems to be decently maintained, for the time being.

**Comment by 89luca89** [comment]
Closing this as it's not planned
