### ISSUE TITLE
[Error]: Distrobox-enter fails with a mounting error

### ISSUE THREAD

**Issue by LarsHaalck** [89luca89/distrobox#537]
**Describe the bug**
I've had multiple containers that just stopped working when trying to run `distrobox-enter` on them due to errors like `must be superuser to use mount`

**To Reproduce**
I have absolutely no idea. A new container can be entered. I already reinstalled another container last week due to the same problem.

**Expected behavior**
The containers should be started normally.

**Logs**
https://gist.github.com/LarsHaalck/9964e5a59de88d87731d5f7f33d10944

**Desktop (please complete the following information):**
Podman 4.3.1 on Arch Linux with Kernel 6.0.10

**Comment by 89luca89** [comment]
Hi @LarsHaalck 
This seems a problem with Podman more than Distrobox

You can try a `podman system migrate` and see if this solves the problem

**Comment by LarsHaalck** [comment]
I tried `podman system migrate` already but it still doesn't work. Do you have any other ideas or some other logs that might be helpful from my side?

**Comment by LarsHaalck** [comment]
This worked last time for a while but I ended up with the same problem after some days. If I'm the only one at the moment with this problem and since it is quite difficult to reproduce, I guess it makes sense to close this issue for now.

**Comment by 89luca89** [comment]
@LarsHaalck any news on this?

**Comment by LarsHaalck** [comment]
Works without any problems on new containers. I see that it is quite difficult to reproduce and would suggest closing this issue until more people have the same problem.

**Comment by 89luca89** [comment]
Thanks a lot!
