### ISSUE TITLE
[Error] Cannot use telepresence

### ISSUE THREAD

**Issue by andrefmarques** [89luca89/distrobox#538]
**Describe the bug**
Cannot use telepresence

**To Reproduce**
On Fedora Silverblue 37:
- Install distrobox
- distrobox create from ubuntu:22.04
- Install kubernetes, kubens, kubectx and telepresence
- Configure access to cluster
- Run `telepresence connect` 

**Expected behavior**
Telepresence should connect

**Logs**
[log.log](https://github.com/89luca89/distrobox/files/10103291/log.log)

**Desktop (please complete the following information):**
 - Using podman 4.3.1, distrobox 1.4.1

**Additional context**
Found this issue on telepresence:
[https://github.com/telepresenceio/telepresence/issues/2456](url)

And this info on how to run it inside a container, not sure if it applies here:
[https://www.getambassador.io/docs/telepresence/latest/reference/inside-container#running-telepresence-inside-a-container](url)

**Comment by 89luca89** [comment]
Hi @andrefmarques 
You can add `--cap-add=NET_ADMIN` using the `--additional-flags` when creating the distrobox
Or you can use a rootful distrobox with `--root` in order to have privileges

**Comment by andrefmarques** [comment]
Is it possible to add this flag to an existing distrobox or only when creating a new one?

**Comment by 89luca89** [comment]
No, only at creation time as `--cap-add` is done on `podman create` stage

You can specify `--additional-flags` also on `enter`, but this works only on flags of `podman exec`
