### ISSUE TITLE
[Suggestion] Grab host OS's time zone when setting up container by default

### ISSUE THREAD

**Issue by Nitrousoxide** [89luca89/distrobox#539]
**Is your feature request related to a problem? Please describe.**
Right now when a container is setup it seems to default to GMT.  While this doesn't really cause any issues per-say in the operation of apps therin, it does make scheduling tasks more cumbersome than it needs to be since you need to either manually go and correct /etc/localtime or convert your times to GMT

**Describe the solution you'd like**
Grab the host system's time zone and set the container OS's to be the same as default.  I believe that podman supports the --tz flag to set it to any arbitary TZ too.  You can set it at start up with distrobox create (name) -a "--tz local" but I believe this should be the default behavior.

**Describe alternatives you've considered**
If this isn't desired as the default perhaps a note in the distrobox create documentation would be good here at least.

**Additional context**
N/A

**Comment by 89luca89** [comment]
Hi @Nitrousoxide 

this should already be happening, in the `distrobox-init` the timezone (/etc/localtime) is kept in sync with the host:

https://github.com/89luca89/distrobox/blob/main/distrobox-init#L1019
