### ISSUE TITLE
[Error] `distrobox enter` fails with failed bind mount for /var/lib/flatpak

### ISSUE THREAD

**Issue by accelbread** [89luca89/distrobox#545]
**Describe the bug**

When a container is created, and then entered for the first time, it fails and bails out with the following output:
```
Container ubuntu is not running.
Starting container ubuntu
run this command to follow along:

 podman logs -f ubuntu

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	
 Warning: failed to bind mount /run/host/var/lib/flatpak to /var/lib/flatpak Error: An error occurred

An error occurred

An error occurred
```

 Subsequent attempts to enter the container also fail.

I tried both the default fedora image and with ubuntu:22.04 and had the same issue. My host system is NixOS.

**To Reproduce**

1. Run `distrobox create -i ubuntu:22.04 ubuntu
2. Run `distrobox enter ubuntu`

There is then the warning and exit.

**Expected behavior**

I expect to enter the container.

**Logs**

[distrobox create -i ubuntu:22.04 ubuntu --verbose](https://github.com/89luca89/distrobox/files/10145499/log_create.txt)

[distrobox enter ubuntu --verbose](https://github.com/89luca89/distrobox/files/10145500/log_enter.txt)

[podman logs ubuntu](https://github.com/89luca89/distrobox/files/10145504/log_podman.txt)

**Desktop (please complete the following information):**
 - Using podman
 - podman version 4.3.1
 - distrobox version 1.4.1

**Additional context**

**Comment by 89luca89** [comment]
Hi @accelbread 

seems like there is a problem with podman, as `root` inside the container is not uid 0, but uid 1

Can you try to delete your containers and issue a `podman system reset` and try again?

Be aware this will delete ALL your containers

**Comment by accelbread** [comment]
Hi, I ran `podman system reset` and the issue is still the same afterwards

**Comment by accelbread** [comment]
That seems odd, since when I run `podman run ubuntu:22.04 id`, I get:
```
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by 89luca89** [comment]
Let's test this:

```console
podman run -t -i --rm --privileged --userns=keep-id --user 0 fedora:latest bash
```

Then inside the container:

```console
mkdir /tmp/var
mount --rbind /tmp /tmp/var
```

**Comment by accelbread** [comment]
Is there something else I could test or get logs for?

I tried switching from the btrfs storage driver to overlayfs and still have same issue so isn't that either.

**Comment by 89luca89** [comment]
Hi @accelbread 

As you said 

`podman run -t -i --rm --privileged --userns=keep-id --user 0 fedora:latest bash`

works, can we now try:

`podman run -t -i --rm --privileged --userns=keep-id --user 0 --volume /:/run/host fedora:latest bash`

Then inside the shell we try a `mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak`

Thanks!

**Comment by popcorn9499** [comment]
Im not the same person but I seem to be having a similar issue
```
[popcorn9499@popcornDL ~]$ podman run -t -i --rm --privileged --userns=keep-id --user 0 --volume /:/run/host fedora:latest bash
bash-5.2# mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
mount: /var/lib/flatpak: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
bash-5.2# 
```

If I go to create the directory /var/lib/flatpak
Then try to mount again I get
```
bash-5.2# mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
mount: /var/lib/flatpak: filesystem was mounted, but any subsequent operation failed: Unknown error 5005.
bash-5.2# ls /var/lib/flatpak
app  appstream	exports  repo  runtime
```


Doing similar commands seems to work under docker
```
[popcorn9499@popcornDL ~]$ sudo docker run -t -i --rm --privileged --volume /:/run/host fedora:latest bash
Unable to find image 'fedora:latest' locally
latest: Pulling from library/fedora
7778c55b9bda: Pull complete 
Digest: sha256:07a6341eb8b7dcc45fb392fdac0210362a3901ab19846d29e949d70285883216
Status: Downloaded newer image for fedora:latest
[root@c10e3f7827e1 /]# mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
mount: /var/lib/flatpak: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
[root@c10e3f7827e1 /]# mkdir /var/lib/flatpak
[root@c10e3f7827e1 /]# mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
[root@c10e3f7827e1 /]# ls /var/lib/flatpak
app  appstream  exports  repo  runtime
```

distrobox version: 1.4.2.1
podman version 4.4.1
Docker version 23.0.1, build a5ee5b1dfc

Running arch linux as my host distro

**Comment by accelbread** [comment]
I get the same output as @popcorn9499 for the requested command, i.e.
```
[archit@solace:~]$ podman run -t -i --rm --privileged --userns=keep-id --user 0 --volume /:/run/host fedora:latest bash
bash-5.2# mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
mount: /var/lib/flatpak: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
bash-5.2# 
```

As @morganhjk mentioned, I also have both `nodev` and `nosuid` set on `/`.

**Comment by 89luca89** [comment]
Thanks @morganhjk for the debug!

So, if we have `nodev,nosuid,noexec` we should use those same flags during mounts (readonly mounts to be precise) and the problem should resolve

Might need to think this good in order to "catch" those flags correctly during the init

**Comment by morganhjk** [comment]
Since `findmnt` is available during init, something like this could work:

```sh
get_locked_flags() (
  source_dir="$1"

  ! [ -d "${source_dir}" ] && return 0

  flags="$(findmnt --noheadings --output OPTIONS --target "${source_dir}")"
  locked_flags=""

  for flag in nodev noexec nosuid; do
    case ",${flags}," in
      *,${flag},*)
        locked_flags="${locked_flags:+${locked_flags},}${flag}"
        ;;
    esac
  done

  echo "${locked_flags}"
)
```

And then use it like this when mounting directories from the host as read-only:

```sh
for host_mount_ro in ${HOST_MOUNTS_RO}; do
    locked_flags="$(get_locked_flags /run/host"${host_mount_ro}")"
    mount_bind /run/host"${host_mount_ro}" "${host_mount_ro}" ro"${locked_flags:+,${locked_flags}}"
done

**Comment by 89luca89** [comment]
Yea `findmnt` is there by default so we can use it

Cool seems like you already coded a solution :) 
You could open a PR with it so we can start testing stuff

**Comment by accelbread** [comment]
Tested above PR on my machine, and it solves the issue.

**Comment by accelbread** [comment]
Hmm, after further testing the PR, nosuid gets set on the container's root mount as well which prevents sudo from working; since the root isn't pulled from the host, it should not have the options set, right?

**Comment by 89luca89** [comment]
Yes `nosuid` would shut down every suid binary, distrobox cannot do much about this
