### ISSUE TITLE
[Error] libc.so.6: Permission denied

### ISSUE THREAD

**Issue by brainchild0** [89luca89/distrobox#546]
# Description
Entering freshly provisioned container from image `debian/latest` fails with following message:

```
sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```

# Steps to Reproduce

1.  Add  [PPA `murmel0/backports`](https://launchpad.net/~murmel0/+archive/ubuntu/backports).
1.  Install package `distrobox`.
2. As regular user (not root), execute following system command:
    ```
    distrobox create -i debian:latest -n test
    ```
2. Likewise, execute following:
    ```
    distrobox enter test
    ```

# Results

- Console capture  (see below).
- Verbose output for `enter` command with `--verbose` switch (see [gist](https://gist.githubusercontent.com/brainchild0/067808b4d426e1fe9d53604e38b3745b/raw/5807d1a54ff329ac25b4b5cf44ee91e6c9ffd51e/distrobox.log.txt)).

# Environment
- Host running Linux Mint 21.1, based on Ubuntu 22.04 
- Both podman and Docker are installed, and Docker is known to work, but the application is using podman. User is provisioned for access to Docker, by group membership.
- ```
    $ docker --version
    Docker version 20.10.21, build baeda1f
  ```
- ```
  $ podman --version
  podman version 3.4.4
  ```
- ```
  $ distrobox --version
  distrobox: 1.4.1
  ```


---  


```
$ distrobox create -i debian:latest -n test
Creating 'test' using image debian:latest	 [ OK ]
Distrobox 'test' successfully created.
To enter, run:

distrobox enter test

test
```

```
$ distrobox enter test
Container test is not running.
Starting container test
run this command to follow along:

 podman logs -f test

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up dpkg exceptions...          	 [ OK ]
 Setting up apt hooks...                	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Executing init hooks...                	 [ OK ]

Container Setup Complete!
sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied

An error occurred

An error occurred
```

**Comment by 89luca89** [comment]
Hi @brainchild0 

are you able to run a simple podman container with:

`podman run --rm -ti debian:latest /bin/sh`

As of right now, I'm not able to reproduce this problem sadly

**Comment by brainchild0** [comment]
> are you able to run a simple podman container with:
> 
> `podman run --rm -ti debian:latest /bin/sh`

Yes, without error.

---

```
$ podman run --rm -ti debian:latest /bin/sh
# 
```

**Comment by brainchild0** [comment]
Please advise if further tests or reports are needed.

**Comment by brainchild0** [comment]
> I still cannot reproduce the issue
> are you able to enter specifying the command?

 The same problem appears when a command is given as in the example.

Note that I am using Debian Stable, not Sid.

**Comment by brainchild0** [comment]
I tested with Sid, and the results have been the same. 

The problem should reproduce with either.        I have no idea  why it is not reproducing.

**Comment by brainchild0** [comment]
There is an error in the original report. The Mint version is 21.1 not 21.

**Comment by 89luca89** [comment]
Hi @brainchild0 
I've tried in a Mint VM and still cannot reproduce I'm sorry :/

**Comment by brainchild0** [comment]
Would you confirm whether your test environment includes the minor update for Mint version 21.1?

**Comment by 89luca89** [comment]
Yes mint 21.1 fresh install

![image](https://user-images.githubusercontent.com/598882/218163054-66fd3e9a-a285-4a55-9727-43bfc87dedc4.png)

**Comment by PhilippKosarev** [comment]
Happens to me on Fedora 40.
```
$ distrobox create ubuntu --image ubuntu:24.04
Creating 'ubuntu' using image ubuntu:24.04	 [ OK ]
Distrobox 'ubuntu' successfully created.
To enter, run:

distrobox enter ubuntu

$ distrobox enter ubuntu
Starting container...                   	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 [ OK ]
Setting up read-only mounts...          	 [ OK ]
Setting up read-write mounts...         	 [ OK ]
Setting up host's sockets integration...	 [ OK ]
Integrating host's themes, icons, fonts...	 [ OK ]
Setting up distrobox profile...         	 [ OK ]
Setting up sudo...                      	 [ OK ]
Setting up user groups...               	 [ OK ]
Setting up user's group list...         	 [ OK ]
Setting up existing user...             	 [ OK ]
Ensuring user's access...               	 [ OK ]

Container Setup Complete!
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```
For some reason, the issue doesn't come up when creating a container without specifying an image(`distrobox create test`).
A possible cause could be running `chmod 774 ~/* -R` and `chown $USER ~/* -R` since I did that not too long ago.
Also `distrobox list` shows that the container is running, despite me being unable to enter it.
