### ISSUE TITLE
Entering Fedora37 install with --init results in exec error on entry and then dumps you to host shell

### ISSUE THREAD

**Issue by Danathar** [89luca89/distrobox#547]
Creating a plain vanilla Fedora37 session with the following command

`distrobox create -i fedora:37 --name fedora37 --init --home /home/foo/fedora`

Successfully creates the distro, but on entering it the following error occurs and it dumps you back out to the host shell (can't enter the distro).

---
Container fedora37 is not running.
Starting container fedora37
run this command to follow along:

 podman logs -f fedora37

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up rpm exceptions...           	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up rpm exceptions...           	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Executing init hooks...                	 [ OK ]
 Setting up init system...              	 [ OK ]
 Firing up init system...               	 [ OK ]

Container Setup Complete!
Error: can only create exec sessions on running containers: container state improper
---
The Logs from Podman show the following at the end
---
distrobox: Firing up init system...
+ printf 'distrobox: Firing up init system...\n'
+ printf 'container_setup_done\n'
+ exec /sbin/init
container_setup_done
/usr/bin/entrypoint: line 1085: /sbin/init: No such file or directory
---

I did this with distrobox on a plain vanilla Fedora37 host.

**Comment by 89luca89** [comment]
Hi @Danathar 

You need to use a specific type of container for `--init` to work, you can check the compatibility list for a `-init` image
