### ISSUE TITLE
[Error] distrobox-export sometimes doesn't properly close quotes in the Exec line

### ISSUE THREAD

**Issue by alcir** [89luca89/distrobox#55]
For instance with `distrobox-export --app simple-scan`
The applications doesn't appear in the application list because the `Exec` line in the `.desktop` file is wrong.

It is
`Exec=/var/home/myuser/.local/bin/distrobox-enter -H -n fedora-toolbox-35 -- "  simple-scan`
while it should be
`Exec=/var/home/alessio/.local/bin/distrobox-enter -H -n fedora-toolbox-35 -- "  simple-scan  "`

Or
`Exec=/var/home/alessio/.local/bin/distrobox-enter -H -n fedora-toolbox-35 -- "  env QT_QPA_PLATFORM=xcb x2goclient`
should be
`Exec=/var/home/alessio/.local/bin/distrobox-enter -H -n fedora-toolbox-35 -- "  env QT_QPA_PLATFORM=xcb x2goclient "`

While (`distrobox-export --app virt-viewer`)
`Exec=/var/home/alessio/.local/bin/distrobox-enter -H -n fedora-toolbox-35 -- "  remote-viewer  " %u`
is correct.

**Comment by 89luca89** [comment]
Thanks @alcir 
Will look into it asap 😄

**Comment by 89luca89** [comment]
Hey @alcir I've pushed a PR to fix this, I was able to reproduce the issue and should be fixed

I was trying before to support this type of expressions:

`Exec=gnumeric %U`

So I was trying to put the ending quote before  the `%`, but it works anyway if it's included so now I just put the quote at the 
end of the line no matter what :+1:

**Comment by 89luca89** [comment]
@alcir hey did you have a way to test this? Wanted a second opinion on this 😄

**Comment by alcir** [comment]
> @alcir hey did you have a way to test this? Wanted a second opinion on this 😄

Yes, sorry. I will try ASAP

**Comment by alcir** [comment]
Ok. I tested the applications mentioned before, and now it works.
