### ISSUE TITLE
[Suggestion] Implement development container specification

### ISSUE THREAD

**Issue by lentzi90** [89luca89/distrobox#550]
**Is your feature request related to a problem? Please describe.**
Sometimes I use [development containers](https://containers.dev/overview) with VS Code in some projects. In other projects I use distrobox, and this is sometimes more convenient than spinning up VS Code. But I find myself missing the convenience of dev containers when using distrobox. 

What's wrong with a plain Docker/Containerfile? Well they are so static. It is hard to modify and customize them per user.  Plus they lack the [library of features](https://containers.dev/features) that can be easily added to devcontainers, mixed and matched as you like.

**Describe the solution you'd like**
I would love to see distrobox implement the [devcontainer spec](https://containers.dev/implementors/spec/) so that I can automatically create a distrobox container from a `devcontainer.json` file.

**Describe alternatives you've considered**
I have considered using the [devcontainer CLI](https://github.com/devcontainers/cli), but it requires npm and is not nearly as convenient as distrobox.

**Additional context**

**Comment by 89luca89** [comment]
Hi @lentzi90 

For now there is no plan to support devcontainer.json from distrobox

I suggest you to take a look at https://github.com/loft-sh/devpod for a development tool centered on that specification
You'll also find me there :P
