### ISSUE TITLE
Tiny Core Linux

### ISSUE THREAD

**Issue by 12D687** [89luca89/distrobox#552]
I'm wondering how to run Tiny Core Linux in distrobox?

**Comment by luc14n0** [comment]
Since there are no official Tiny Core Linux Docker images available, you have to build your own. Then you load them in **Docker**/**Podman**. From there, you can use the usual **Distrobox** workflow.

You could take [Tatsushid](https://github.com/tatsushid/docker-tinycore)'s work as an inspiration.

**Comment by 89luca89** [comment]
@12D687 
If not official image is available you can try to check in the documentation, the section to create a custom image for distrobox.
But if no official image is available, I cannot support it officially
