### ISSUE TITLE
[Error] Custom shell is lost after stopping container

### ISSUE THREAD

**Issue by fedemp** [89luca89/distrobox#553]
Possible duplicate of https://github.com/89luca89/distrobox/issues/378 cause I noticed that I have a `.profile` file in my home too.

**Describe the bug**
I have a container based on Tumbleweed. Inside it, I have installed `zsh` and used `chsh` to set that as my default shell. If I exit the container and then enter again, `zsh` is chosen. Great.

But if I exit the container, stop it, and then I enter again, the shell is reset to `bash`.

**To Reproduce**
* Important consideration: My host is running `bash`.
* Create a new container. In my case, `distrobox create -i tumbleweed`.
* Install `zsh` and set it as your default shell. `sudo chsh -s /bin/zsh $(whoami)`.
* Exit the container and reenter to confirm `zsh` is now the default shell.
* Exit and stop the container. `podman stop tumbleweed`.
* Enter the container again. You should see the "Starting container" messages. `bash` is again the default shell.

**Expected behavior**
Custom shell is used after "reboots".

**Desktop (please complete the following information):**
 - Are you using podman or docker?
podman.
 - Which version or podman or docker?
4.3.1
 - Which version of distrobox?
Flatpak 1.4.0

**Comment by 89luca89** [comment]
This has been fixed as of commit 441bf929dde6895fd31ab9815465a0e98f7752ac
