### ISSUE TITLE
[Suggestion] install bash-completion in distrobox-init

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#554]
**Is your feature request related to a problem? Please describe.**
`bash-completion` is one of the packages I can't really live without
(it is included in [fedora-toolbox](https://src.fedoraproject.org/container/fedora-toolbox/blob/rawhide/f/extra-packages) by default). Recently I noticed it is not installed into distrobox.

**Describe the solution you'd like**
At least for distros which default to bash, their package manager can install bash-completion by default IMO (eg for dnf and yum at least (maybe microdnf too) and probably more).

**Additional context**
I can open a PR though I am sure which other distros could be covered by this: though we could just start with the above perhaps.

**Comment by juhp** [comment]
For me at least having bash-completion installed by default would be way more useful than Mesa et al ;o)

(Anyway I don't have time right now, but will try to get to this sooner or later, though if someone gets to it before me that would also be most welcome.)

**Comment by 89luca89** [comment]
Seems like an useful addition to me :smile: 
Will queue in the TODO list, or if you someone has time, can give a shot at this :+1:
