### ISSUE TITLE
[Error] Zrythm can't detect jack audio server from host

### ISSUE THREAD

**Issue by minidcon7** [89luca89/distrobox#555]
**Describe the bug**
I'm on Debian 11 with an audio configuration use. I have jack2 running and I can use applications with jack support (e.g Carla). I install distrobox and create an Arch image. Then I install Zrythm with yay. I can start the app but it can't detect jack. So I can't use it with my jack low-latency configuration.

**Expected behavior**
Zrythm should detect jack host configuration

**Desktop:**
 - Podman 3.0.1
 - Install with `curl` in local (no root) following the official documentation.

**Comment by 89luca89** [comment]
Hi @minidcon7 

I'm not familiar with Jack setups, maybe you ned to install jack also inside the container?

**Comment by minidcon7** [comment]
When installed Zrythm the system installs dependencies, so Jack is install.

**Comment by amazingidiot** [comment]
maybe you accidentally installed the pipewire-jack plugin in the distrobox since it can replace jack2 in arch. The jack-dependency is in rtaudio, where jack is required. Pacman should ask during the installation if you want jack2 or pipewire-jack to provide the jack api.
