### ISSUE TITLE
[Suggestion] distrobox push

### ISSUE THREAD

**Issue by dmytri** [89luca89/distrobox#557]
**Is your feature request related to a problem? Please describe.**
wrap podman/docker push to push container to repo like ghcr to make it possible to use create on a different computer

**Describe the solution you'd like**
a `distrobox push` command that:
- increments a version number
- does a commit
- pushes the image

**Describe alternatives you've considered**
can do it manually with podman

**Additional context**
would be nice to have my pet containers or more than one machine, so push to repo, then create from that image on other machine

**Comment by 89luca89** [comment]
Hi @dmytri 

Not sure if a `push` would add much value to distrobox, it would be mostly a 1to1 with docker/podman, an alias almost :sweat_smile:

**Comment by dmytri** [comment]
the main advantage would be convenience around making a commit and setting a version to push

**Comment by 89luca89** [comment]
I'm not convinced in implementing this
Image building/pushing is already an advanced case that can (and should) be directly managed with podman/docker/buildah
