### ISSUE TITLE
[Error] Empty /home/user directory on OSTree-based system

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#562]
**Describe the bug**

After a year using distrobox, I just found out the `/home/user` directory is empty. My host is Fedora Silverblue, and the canonical home is at `/var/home`, with `/home` being a symlink to that.

Inside the distrobox, my home is correctly set to `/var/home/user`, but `/home/user` is an empty directory. 

```
toolbox:~ % ls -ld /home/$USER
drwxr-xr-x 1 root root 0 Sep 17 11:27 /home/sph
toolbox:~ % ls -ld $HOME
drwx--x---+ 1 sph sph 1912 Dec 18 11:01 /var/home/sph
```

**To Reproduce**

1. Create a distrobox in Fedora Silverblue or any other Linux system where /home is a symlink.
2. Enter the distrobox
3. `ls -ld /home/$USER`

**Expected behavior**

Distrobox to create the `/home -> /var/home` symlink if present on the host.

**Additional context**

```
~ % distrobox version
distrobox: 1.4.1
~ % podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 15:01:27 2022
OS/Arch:      linux/amd64
```

**Comment by 89luca89** [comment]
Hey @1player 

Seems strange to me, on SB I indeed have both `/home/user` and `/var/home/user` inside the distrobox
Not as a symlink, but as a mountpoint

**Comment by 89luca89** [comment]
@1player do you still have this bug? 

This should not happen thanks to these lines: https://github.com/89luca89/distrobox/blob/main/distrobox-init#L758 in commit 1e67af8

**Comment by 1player** [comment]
I have not recreated my container in a year, so I assume that code fixes it. Thanks!

**Comment by 1player** [comment]
This is still an issue and I've managed to reproduce it on 1.4.2.1:

* `distrobox create --image docker.io/library/alpine:latest --name test`
* `distrobox enter test`
* Inside the container: `ls -l /home/$(id -un)/`: directory is not empty, as expected.
* Exit the container
* `distrobox stop test`
* `distrobox enter test`
* Inside the container: `ls -l /home/$(id -un)/`: **directory is empty**

**Comment by 89luca89** [comment]
> Seems like the mount is not set up correctly the second time the container is started.

That's probably it!

```sh
if [ -e "/var/home/${container_user_name}" ] && [ ! -e "/home/${container_user_name}" ]; then
	if ! mount_bind "/run/host/var/home/${container_user_name}" "/home/${container_user_name}" rw; then
		printf "Warning: Cannot bind mount %s to /run/host%s\n" "/var/home" "/home"
	fi
fi
```

The first time, the /home/$USER is not there, so it mounts it, but the second time, it's there and empty...
So it does not mount! I can finally reproduce this :sweat_smile: 

I think we can simply remove `&& [ ! -e "/home/${container_user_name}" ]` from the condition, and have it more relaxed
