### ISSUE TITLE
[Suggestion] offline install when using distrobox create

### ISSUE THREAD

**Issue by tim78245** [89luca89/distrobox#565]
First this tool is great, I wanted something like WSL but for Linux itself that "just works" and this is it. Thank you.

However I would like to store a bunch of distroboxes on a harddrive and then be able to install them, I imagine first I would save the docker image as shown [here](https://serverfault.com/questions/701248/downloading-docker-image-for-transfer-to-non-internet-connected-machine/718470#718470), but then on distrobox's side I would want to do something like:

distrobox create -i ./ubuntu.docker

Currently what I want seems impossible, so I am requesting it be made possible.

**Comment by luc14n0** [comment]
Before running `distrobox create`, you should first load the image, as per the answer you posted.

``` bash
# Save the image
$ podman save -o docker.io-ubuntu-devel.tar ab765816b397
Copying blob bb704b4c7ba1 done                               
Copying config ab765816b3 done                                                                                            
Writing manifest to image destination                                                                                     
Storing signatures

# Remove the image from remote registry
$ podman image rm ab765816b397                                                                                   
Untagged: docker.io/library/ubuntu:devel                                                                                  
Deleted: ab765816b3974729f0fde5886d9639590664cc371496b7e3c2e6e15edcef4896

# Load the local image
$ podman load -i docker.io-ubuntu-devel.tar          
Getting image source signatures
Copying blob bb704b4c7ba1 done   
Copying config ab765816b3 done   
Writing manifest to image destination
Storing signatures
Loaded image: sha256:ab765816b3974729f0fde5886d9639590664cc371496b7e3c2e6e15edcef4896

$ podman images
REPOSITORY  TAG         IMAGE ID      CREATED     SIZE
<none>      <none>      ab765816b397  7 days ago  72.8 MB

# Tag it
$ podman tag ab765816b397 ubuntu:devel
$ podman images
REPOSITORY        TAG         IMAGE ID      CREATED     SIZE
localhost/ubuntu  devel       ab765816b397  7 days ago  72.8 MB

# Usual workflow
$ distrobox create -i ubuntu:devel -n devel
Creating 'devel' using image ubuntu:devel        [ OK ]
Distrobox 'devel' successfully created.
To enter, run:

distrobox enter devel

$ distrobox list
ID           | NAME                 | STATUS                         | IMAGE                         
afd747f6ed9e | devel                | Created                        | localhost/ubuntu:devel
```

Distrobox is a great wrapper, but it can't do everything. IMHO, having this feature doesn't make much sense.

**Comment by tidux** [comment]
Another option would be to run your own OCI registry like Quay on a machine on your LAN, and push your images to it, then specify your local registry to pull images from when running `toolbox create`.   Unless "offline" means literally no network connections to the machine, that should suffice.

**Comment by 89luca89** [comment]
As suggested, offline installs are possible if you use a custom image, 
so I'm marking as solved as the main project won't support an offline install (due to the nature of how it works at all)
