### ISSUE TITLE
[Error] Couldn't open a raw socket. Error: Operation not permitted (1)

### ISSUE THREAD

**Issue by sakibulalikhan** [89luca89/distrobox#568]
**Describe the bug**
When I try to use nmap tool, it start but give an error. I tried it on Kali linux latest os & also on Ubuntu os but result is same. I tried to solve this problem and also search on internet but cant't fixed this error.

 ```
$sudo nmap -sV scanme.nmap.org

 Starting Nmap 7.80 ( https://nmap.org ) at 2022-12-24 23:07 +06
 Couldn't open a raw socket. Error: Operation not permitted (1)
```
![image](https://user-images.githubusercontent.com/75080608/209446051-83dd10b2-dec9-4822-a335-1eb259e8d670.png)

**To Reproduce**
1. I use distrobox on Fedora 37
2. Install by this command  > curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

**Expected behavior**
Nmap scan finish without any error.

**Logs**
[kali-podman.log](https://github.com/89luca89/distrobox/files/10298975/kali-podman.log)
[ubuntu-podman.log](https://github.com/89luca89/distrobox/files/10298976/ubuntu-podman.log)

**Desktop (please complete the following information):**
 - I'm using podman.
 - podman version 4.3.1
 - distrobox: 1.4.2.1

**Additional context**
![image](https://user-images.githubusercontent.com/75080608/209446213-131bed23-7a16-4512-a33f-34acd9ddb341.png)

**Comment by 89luca89** [comment]
Hi @sakibulalikhan 
To use real root inside a distrobox, you need to use a rootful distrobox 

Please refer to the documentation for this

**Comment by sakibulalikhan** [comment]
Sorry but I can't find any documentation. Can you share the way, how I can use rootful distrobox?

This will'be great help for me.

**Comment by Rasp-Scallion** [comment]
Hi, Kali Linux noobie here and having the same error when running the command using raspberry pi 400, any help is appreciated in resolving this!
