### ISSUE TITLE
[Suggestion] A way to always export apps to the host system or automatically create a entry for a app installed on a container

### ISSUE THREAD

**Issue by Heus-Sueh** [89luca89/distrobox#570]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
auto-generate a entry for apps installed on a container='0' or '1'

**Describe alternatives you've considered**

In KDE we can create a new category in the application launcher: "container-name" with the apps installed in the container and GNOME we can group the apps and rename the folder with the container name

**Additional context**
In Gnome we can group the apps by container like this:
![paginated.jpg](https://user-images.githubusercontent.com/98482469/209547766-65cfe67a-4405-4b1b-955e-2af8a5d7ff40.jpg)

**Comment by 89luca89** [comment]
I think this could be a neat addition (opt-in during creation tho)
Need to think of a nice way to detect installations and uninstalls

Might be a step after implementing #386

**Comment by 89luca89** [comment]
Thinking of this, I've decided to not implement auto-export

There are tools for that (apx, blend, and so on) and that's on them if they want to auto-export
