### ISSUE TITLE
[Suggestion] Should we setup locales using the LANG/LC_* env?

### ISSUE THREAD

**Issue by black-desk** [89luca89/distrobox#571]
**Is your feature request related to a problem? Please describe.**

When I enter the container, I found that inside container I have empty LANG, and empty /etc/locale.gen, which means application will fallback to LANG=C or something like that.

**Describe the solution you'd like**

Should we just automatically setup language/encoding when we create the container? such like install "locales" and run `dpkg reconfigure locales` according to the environment var like LANG/LC_*

**Comment by juhp** [comment]
This OS specific I think: eg Fedora defaults to `LANG=C.UTF-8`

**Comment by black-desk** [comment]
But should we keep LANG sync with host? It seems not very hard to do that. Just install some package include /usr/share/locales/i18n/... and a localedef command will get this job done.

For now, the enter command will ignore LANG, which make everything in container fallback to English.

**Comment by juhp** [comment]
Sure it is makes sense to do something for debian/ubuntu here.
Some locale package could indeed be added in distrobox-init for deb based containers with POSIX locale.

**Comment by 89luca89** [comment]
Intresting, mounting /usr/share/locales could be a neat addition to the integration, this needs more tests and investigations :smile:

**Comment by black-desk** [comment]
> Intresting, mounting /usr/share/locales could be a neat addition to the integration, this needs more tests and investigations smile

I don't think that would work, as the libc in container might be different from that in host.

**Comment by 89luca89** [comment]
now init will setting up at least en_US.UTF-8 by default
At least this way it does not revert to C.POSIX which would let to errors
