### ISSUE TITLE
[Suggestion] init script for fast ephemeral startup

### ISSUE THREAD

**Issue by k1mbl3** [89luca89/distrobox#574]
My usecase is very simple:

I need to startup ephemeral custom images as fast as possible.
At the moment i am initing the image running this Dockerfile command:

`RUN curl https://gitlab.com/k1mbl3/public-scripts/-/raw/main/distrobox/image-init.sh | sh`

(which is a snippet from https://raw.githubusercontent.com/89luca89/distrobox/b2f7b5059b685fc01cbd1a2ba5b39b9d82739f5c/distrobox-init)

It would be nice if there were an easy way to have an updated and oficial version of this script in a public url to init docker images during the build time

**Comment by 89luca89** [comment]
Hi @k1mbl3 
you can always use this github link to have latest official version:

https://raw.githubusercontent.com/89luca89/distrobox/main/distrobox-init

You can just pass the flags with:

```dockerfile
...
RUN curl https://gitlab.com/k1mbl3/public-scripts/-/raw/main/distrobox/image-init.sh | sh -s -- --name example [...]
...
```

**Comment by k1mbl3** [comment]
> 

It would be nice to have an option to just install the deps. If i init an image entirely it loses its purpose of being reusable among different machines.
