### ISSUE TITLE
[Error] issue with the export command

### ISSUE THREAD

**Issue by manan-gup** [89luca89/distrobox#580]
Hi, sorry for not using the template but I don't know how to reproduce this issue.

Using Distrobox 1.4.2.1 with podman 4.3.1 on Fedora Silverblue 37.

While running the command `distrobox export --app zathura` from within a Fedora 37 container I get an error:
```
cp: not writing through dangling symlink '/run/host//var/home/manan/.local/share//icons/hicolor/scalabl
e/apps/org.gnome.Logs.svg'
```
And now icons for all flatpak apps have disappeared form my desktop.
![Screenshot from 2023-01-06 06-14-03](https://user-images.githubusercontent.com/77879361/210906959-e134a136-1b61-4282-8fa3-bd7a62a53f3d.png)
One thing to note would be that I had already exported zathura once before. So, I was hoping that this would only overwrite the previous files.

Any clues to troubleshoot this would be appreciated.

**Comment by 89luca89** [comment]
Hi @manan-gup 
I've just now tried with F37sb with an F37 container and it didn't error for me

Can you please provide a log of the error running `distrobox export --app zathura --verbose`?
Also can you check the file in that error if it's some broken link or stuff like that?

**Comment by manan-gup** [comment]
Hi,
I ran `distrobox-export --app zathura --verbose &> distrobox-export.log` and the resulting file is 160k lines long. Attached here.
[distrobox-export.log](https://github.com/89luca89/distrobox/files/10789466/distrobox-export.log)

The symlinks at `/run/host/var/home/manan/.local/share/icons/hicolor/scalable/apps/` for flatpak apps point to files that don't exist.

**Comment by castrojo** [comment]
I am able to replicate this with an archlinux box and exporting libreoffice: https://gist.github.com/castrojo/619a25c83f3a2fb1300f279e0e1e7c51

Deleting the files from `~/.local/share/applications` restores functionality, not sure if the .desktop files that are being generated are valid or not.
