### ISSUE TITLE
[Default Behavior] "Do you want to remove custom home of container" prompt should default to "No".

### ISSUE THREAD

**Issue by emmetoneillpdx** [89luca89/distrobox#581]
This is not strictly a bug or a feature request, but I'd like to suggest that the default response for the `Do you want to remove custom home of container [CONTAINER]? [Y/n]:` prompt be changed to [y/N]. (This is the message that appears when removing a distrobox container that uses a custom home directory.)

In the case of removing a directory (especially a `$HOME` directory) I think it's a lot safer to default to "no" instead of "yes". In the event that the user mistakenly hits the enter key twice, or is just being careless, defaulting to "yes" creates the risk of significant unintentional data removal, while defaulting to "no" only risks the minor inconvenience of needing to manually go delete a directory.

**Comment by misobarisic** [comment]
If your custom home is the same as the host home, it willl not prompt for confirmation.

You can also set an environment variable `$DBX_CONTAINER_RM_CUSTOM_HOME` to either 1 or 0. 0 will not delete, 1 will. Both don't ask for additional confirmation.

**Comment by 89luca89** [comment]
Hi @emmetoneillpdx 
Generally speaking I'm ok with this, I just fear to leave too much litter/unused homes inside user's disk
