### ISSUE TITLE
[Error] Failed to connet to bus when --init flag was used

### ISSUE THREAD

**Issue by DarielVR** [89luca89/distrobox#583]
**Describe the bug**
I tried to replicate the example from here:
> https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-init-system-inside-a-distrobox

But i get the next error:

`$ sudo systemctl enable --now sshd`
`Failed to connect to bus: No such file or directory`

**To Reproduce**
Same steps from the link above.

**Expected behavior**
Use systemd units from container without errors.

**Logs**
Output of `distrobox create -i docker.io/almalinux/8-init --init-hooks "dnf install -y openssh-server" --init --name test --verbose`:
[distrobox-verbose.txt](https://github.com/89luca89/distrobox/files/10398647/distrobox-verbose.txt)

Output of `podman logs --latest`:
[podmanlogs-latest.txt](https://github.com/89luca89/distrobox/files/10398649/podmanlogs-latest.txt)

**Desktop:**

- Host OS: OpenSUSE MicroOS (Tumbleweed) Desktop GNOME (RC)
- Kernel: Linux 6.1.3-1-default x86_64
- Podman: version 4.3.1
- Distrobox: 1.4.2.1

**Additional context**
No major changes where made to the base image of the OS.

**Comment by 89luca89** [comment]
Hi @DarielVR 

It was a problem when using `--verbose`, Fixed by commit https://github.com/89luca89/distrobox/commit/2f877ec27fed59d48ea3081c4775e72913d0df5b
