### ISSUE TITLE
Host apps run when running GNOME apps in gnome-session on Fedora Rawhide

### ISSUE THREAD

**Issue by RudraSwat** [89luca89/distrobox#586]
When running GNOME apps such as Nautilus or Gedit (this occurs with all GNOME apps) from the application launcher in GNOME (doesn't happen in MATE), their binaries from the host seem to be run. I was able to confirm this by removing Gedit from the host, which resulted in Gedit simply not opening if launched from GNOME's application launcher. When launched using Alt+F2 or from a terminal, these GNOME apps seem to work perfectly fine.

**Host:** Ubuntu 22.10
**Distrobox version:** 1.4.2.1 (from the Ubuntu 23.04 repos)

**EDIT:** Looks like this appears on all DEs when using GNOME apps (including MATE).

**Comment by RudraSwat** [comment]
This is be caused by `DBusActivatable=true` (set by all GNOME apps in their desktop files), which causes the host apps to be launched as the common session bus is being used.

One temporary solution could be to run a daemon which automatically replaces `'DBusActivatable=*\n'` with `''` in all desktop files at a specified interval (for example, 3 seconds by default).

**Comment by 89luca89** [comment]
Yes this is due to dbus integration
And in fact it's acting like a "real" host application, if the developer of the app wants "DbusActivatable" then I'll leave it as it is
