### ISSUE TITLE
[Error] changing container name in podman does not change container HOSTNAME variable

### ISSUE THREAD

**Issue by tidux** [89luca89/distrobox#589]
```
user@host ~ $ podman rename distrobox-foo distrobox-bar
user@host ~ $ distrobox enter distrobox-bar
user@distrobox-foo ~ $ echo $HOSTNAME
distrobox-foo.host.domain.tld
user@distrobox-foo ~ $
```

Where is this environment variable being set?  How do I change it without destroying and recreating the container?

**Comment by 89luca89** [comment]
This is not a bug, this is how distrobox works.

The hostname will always be `name-of-container.name-of-host`, that is intended behavior, 
you can "rename" an existing distrobox using [container save and restore](https://distrobox.privatedns.org/useful_tips.html#container-save-and-restore)
