### ISSUE TITLE
[Suggestio] Remove hyphens in commands

### ISSUE THREAD

**Issue by TheEvilSkeleton** [89luca89/distrobox#59]
I suggest changing the commands to `distrobox {create,enter,init,export}` (notice the lack of hyphens) because it's consistent with other utilities like Podman, Docker or Toolbx and many more.

**Comment by 89luca89** [comment]
@TheEvilSkeleton I would like in the future to do something like this

But I want to maintain backward compatibility and I would like to avoid creating a single shell file with all inside because it would become quite unmanageable and unreadable 

Any ideas?

**Comment by TheEvilSkeleton** [comment]
The only idea I have at the moment is making bash act like a compiled language, where all "libraries" (functions and such) get copied and prepended to the main bash script.

**Comment by 89luca89** [comment]
That would break backwards compatibility as right now the `distrobox-init` script itself is mounted inside the container as entry point, and renaming it would break existing distroboxes 

For now I see having both option active as the only way, having a `distrobox` command that manages subcommands and calls the dedicated scripts so that we have both ways 
Then in the future we can think of a migration path

But I would like to maintain the code base as lean as possible, as the main target of the project was also this. Having smaller more readable files, easier to debug and modify

**Comment by manics** [comment]
You could make `distrobox` a wrapper script?
```sh
#!/bin/sh
set -eu
COMMAND="$1"
shift
exec distrobox-$COMMAND "$@"
```
With the added benefit that it handles new commands automatically.

**Comment by alegrey91** [comment]
> But I want to maintain backward compatibility and I would like to avoid creating a single shell file with all inside because it would become quite unmanageable and unreadable

I think you should create a sort of library and then use just a single file to avoid code duplication. It's better to have a single tool (in my opinion).

**Comment by 89luca89** [comment]
> You could make `distrobox` a wrapper script?
> 
> ```shell
> #!/bin/sh
> set -eu
> COMMAND="$1"
> shift
> exec distrobox-$COMMAND "$@"
> ```
> 
> With the added benefit that it handles new commands automatically.

Yep that was the idea



> > But I want to maintain backward compatibility and I would like to avoid creating a single shell file with all inside because it would become quite unmanageable and unreadable
> 
> I think you should create a sort of library and then use just a single file to avoid code duplication. It's better to have a single tool (in my opinion).

The library approach could work in the future, but would break compatibility with existing distroboxes as the entry point is a mount of the `distrobix-init` file itself.

A sensible middle approach would be having single/separated files to do the stuff like now 
And a `distrobox` script that will manage the subcommands (like @manics said)

This would enable also to use simple subcommands for quality of life (list, remove, clone, etc etc)

**Comment by 89luca89** [comment]
Started a first implementation of the wrapper and added a couple of quality of life commands like `list` and `rm`

**Comment by 89luca89** [comment]
I'm merging and closing this, if anyone has suggestions on including other quality of life commands just open a new issue :+1:
