### ISSUE TITLE
[Error] Cannot add user to group with usermod

### ISSUE THREAD

**Issue by ekirchman** [89luca89/distrobox#590]
Please, before opening a bug:

**Describe the bug**
User cannot be added to a group. `usermod -aG mythtv $(whoami)` fails silently and does not add the user to the group upon logging back in.

**To Reproduce**
1. Create a Ubuntu 22.04 container
2. Enter the container and try to add an existing group to a user with usermod
3. Log out, stop the container, then re-enter the container.
4. The group will not have been added to the user

**Expected behavior**
The group should be added to the user

**Logs**

[distrobox.log](https://github.com/89luca89/distrobox/files/10462569/distrobox.log)

[podman.log](https://github.com/89luca89/distrobox/files/10462582/podman.log)

Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 podman
 - Which version or podman or docker?
 - Version 4.3.1
 - Which version of distrobox?
 - Version 1.4.2.1

**Additional context**
If distrobox is based on toolbox, perhaps it's related to [this toolbox](https://github.com/containers/toolbox/issues/632)  issue?
I am running Fedora Silverblue 37. Would [this issue](https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group) be relevant?

`getent group | grep mythtv`
Shows that I am in the group, however:

```dialout:x:20:mythtv
cdrom:x:24:mythtv
audio:x:29:mythtv
video:x:44:mythtv
mythtv:x:113:kirchman
```

**Comment by jeffteixeira** [comment]
Has the user been added to the group on the host?

**Comment by ekirchman** [comment]
No, it hasn't. It was my understanding that the container user was a separate user than the host user.

**Comment by ekirchman** [comment]
I've created a `mythtv` group on the host, and added the active user to this group. After trying to add the user to the mythtv group within the container and restarting, the container user still isn't in the group

**Comment by jeffteixeira** [comment]
Have you tried doing this in a container created with the --root flag?

**Comment by ekirchman** [comment]
Removed the old container, and created a new one with the `--root` param, and followed the steps from before. But nothing was changed. My user still isn't in the group

**Comment by 89luca89** [comment]
Hi @ekirchman 

Adding user to a group is somewhat different, depending on what you have to do

If the group `mythtv` is existing *on the host*, and you're using podman, you should be able to
access files of the `mythtv` group
Running `groups` inside the container, *won't report the group itself to the groups command*, it is how podman works: https://www.redhat.com/sysadmin/supplemental-groups-podman-containers
This read will probably clear some of the doubts
If you use a rootful distrobox (works only on rootful), you can also create a group inside the container with the same GID of the group outside the container, then add the user to that group

If instead the `mythtv` group is inside the container, you should be able to just add your user (inside the container) to it

**Comment by ekirchman** [comment]
Hm. I think I understand. Since I am not requesting resources outside of the container (all the MythTV software will be installed within the container), from my understanding, creating the group within the container should suffice. 

That said, I still should be able to add a user to the group within the container. The software I'm trying to run in the container, mythtv-frontend, complains that it can't run unless my user is in the `mythtv` group

**Comment by 89luca89** [comment]
Yes if everything is inside the same container, then you should be able to normally add user to the group
Can you try with some other group?

Like:

```
sudo groupadd test
sudo usermod -a -G test your-username
grep test /etc/group
```

This should work correctly
You should also try doing this, stopping the container, then starting it again and verify

Thanks!
