### ISSUE TITLE
[Discussion]  How to remove app icon from host after container is gone

### ISSUE THREAD

**Issue by lmckiwo** [89luca89/distrobox#593]
Is your feature request related to a problem? Please describe.
I am not sure if there is a way to fix with the current version, so I am starting a discussion.  

I am on Fedora 37.  I have exported an app from my distrobox.  Then I have deleted the distrobox container (without deleting the app), but app still shows up on my host.  This was done by accident because i forgot i had exported this app. 

How can I remove this app from my host now?   I have already tried to spin up a new container and reinstalling the app so i can remove it again, but it just creates a new instance of the app on my  host.

Describe the solution you'd like
It would be good have a way to clean up the app from the host if the container no longer exists.
Something like:  distrobox cleanup --apps  

or if there is a way to manual clean up from the host would be good too.

Describe alternatives you've considered

Additional context

**Comment by lionblaze55** [comment]
app launcher is generated in .local/share/applications. Removing the app launcher file there will remove it from your desktop.

**Comment by lmckiwo** [comment]
thanks.  That is all i need :)
