### ISSUE TITLE
Kali/Parrot/Blackarch support for Distrobox

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [89luca89/distrobox#594]
I've been looking for a quick and easy vm to help with programming and pen testing, and distrobox seems perfect. Only problem is there's not a supported pen-testing distro.

**Comment by lbssousa** [comment]
Have you tried this?
```
distrobox create --image kalilinux/kali-rolling:latest --name kalibox
```

**Comment by Kiwi-the-Cat** [comment]
I have and it works, thank you
