### ISSUE TITLE
Add support for containerized VPN network

### ISSUE THREAD

**Issue by pablos-here** [89luca89/distrobox#596]
**Is your feature request related to a problem? Please describe.**

I have an `OpenVPN Client` container named `openvpn-client`.  

I haven't been able to successfully route my `distrobox` to use the VPN.

**Describe the solution you'd like**

Perhaps have `enter` extended to allow a `--network` switch:

`distrobox enter --network container:openvpn-client ...`

**Describe alternatives you've considered**

As I'm very new to containers (and `distrobox`), some of my efforts to try to get it to work are probably amusing to most.  :)

For example, I inspected the output of `distrobox create --dry-run` and replaced the --network switch:

> `--network host` => `--network container:openvpn-client`

While I was able to successfully do the initial build via `distrobox-enter`, I immediately received  a `userns` error.

I tried again without `--userns` and this time `distrobox-enter` worked.   \o/ 

However, I received an error about $HOME being inaccessible.  :[ 

I `sudo -i` and using `traceroute`, I was able to confirm that I was using the VPN network.  A modicum of progress.  I think.  :]

**Additional context**

I do have a work-around - use the exposed VPN HTTP/SOCKS proxies and try to force the apps in a `distrobox` to use them.  Of course, I prefer that the networking is handled at a higher level.

**Comment by 89luca89** [comment]
Probably the best thing for VPN/Network stuff is either to use a [rootful distrobox](https://distrobox.privatedns.org/useful_tips.html#run-the-container-with-real-root), so it can indeed modify/access host's network

**Comment by pablos-here** [comment]
Hi @89luca89 ,

You're absolutely correct.  I was trying to use an app image and it failed.

Using `openvpn` within `rootful distrobox` worked.  

Thank you for setting me straight.

I'm sorry to have wasted your time.  :\  I should have thought of it.  :p

**Comment by 89luca89** [comment]
> I'm sorry to have wasted your time. :\ I should have thought of it. :p

Don't worry no problem :)
