### ISSUE TITLE
[Suggestion] add proot and chroot support

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#598]
**Is your feature request related to a problem? Please describe.**
Podman takes longer to start and when you run podman your system takes forever to shut down

**Describe the solution you'd like**
There is an app [Atoms](https://flathub.org/apps/details/pm.mirko.Atoms) that does what I am talking about so I know that it is possible

**Describe alternatives you've considered**
if you copy the root system of the container to a folder on your home folder and you can chroot inside of that folder

**Additional context**
it probably shouldn't be the default but I would like there to be an option to use chroot(for root containers) or proot(for user containers)

**Comment by 89luca89** [comment]
Hi @dnkmmr69420 

Now there is [Lilipod](https://github.com/89luca89/lilipod) that effectively just unpacks the rootfs and pivot_root in it

Enter times are much faster, at the expense of disk usage (no overlayfs and deduplication)

This is as near as to pure chroot we can go for now

**Comment by gmankab** [comment]
@89luca89, proot supports termux on android, lilpod is not

please consider reopening issue
