### ISSUE TITLE
[Feature] add support for RedHat UBI

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#60]
As pointed out in #57 by @alcir 

> For the records, for what it worth, also Red Had UBI images seem to work.
distrobox-create -i registry.access.redhat.com/ubi8/ubi:latest --name ubi8
You have to install vte-profile to avoid bash: __vte_prompt_command: command not found messages
sudo dnf install vte-profile
and glibc-langpack-en to avoid Failed to set locale, defaulting to C.UTF-8
sudo dnf install glibc-langpack-en

Let's investigate on this and see if we can integrate the missing dependencies also in other distribution families

**Comment by alcir** [comment]
Well also CentOS Stream 9 requires to install `vte-profile` in order to avoid the message 
`bash: __vte_prompt_command: command not found`

**Comment by 89luca89** [comment]
Fixed with merge of #69
