### ISSUE TITLE
[Error] Cant find any mount point done inside the host (Cant mount drives)

### ISSUE THREAD

**Issue by elyashivhazan** [89luca89/distrobox#600]
**Describe the bug**
Running inside the host `mount /sda/drive /mnt` then `distrobox enter box` will not show up the mount point in the container.
Also trying to mount with:
```
> distrobox-create -n gamerig -H ~/.local/share/homes/gamerig -i localhost/userspace-gamerig:latest --volume /mnt/games:/mnt
```
Will give the error:
```
Creating 'gamerig' using image localhost/userspace-gamerig:latest	Error: statfs /mnt/games: no such file or directory
 [ ERR ]
```

But it dose
```
# From the host
> ls -Al
drwxr-xr-x    4 elyashiv elyashiv    4.0K Dec 15 01:32 .lutris
drwxr-xr-x    4 elyashiv elyashiv    4.0K Nov 19 12:08 .wine
drwxr-xr-x   12 elyashiv elyashiv    4.0K Dec 31 17:04 linux
drwxr-xr-x    3 elyashiv elyashiv    4.0K Jan  1 23:16 steam
drwxr-xr-x    7 elyashiv elyashiv    4.0K Nov 21 22:26 wine
> pwd
/mnt/games
```

**To Reproduce**
See "**Describe the bug**"

**Expected behavior**
Be able to access the mount point in the container

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.3.1
 - Which version of distrobox? 1.4.2.1
 
 

I most say its odd considering my home folder is a mount point (`/home` from host) (it is a zfs mount point)

**Comment by 89luca89** [comment]
Hi @elyashivhazan does the `/mnt/games` directory itself readable by the user (whithout root)?

Because on my system I cannot reproduce the issue:

![image](https://user-images.githubusercontent.com/598882/218083591-2f76d1f0-595b-433b-bd13-ff4d8c6936e6.png)

**Comment by elyashivhazan** [comment]
hi, i created an image with `fallocate -l 5G image.img` (i dont have the drive on me but its the same)

```
> mount -t ext4 ~/image.img /mnt
> distrobox enter arch-game
> cd /mnt
> ls -al
total 6
drwxr-xr-x  2 nobody        nobody        4096 Jan  9 19:58 .
dr-xr-xr-x 17 elyashivhazan elyashivhazan   21 Feb  7 18:43 ..

#go to the host
> exit
> cd /mnt
> ls -al
total 28
drwxr-xr-x    4 elyashiv elyashiv      4096 Feb 10 14:29 .
drwxr-xr-x   23 root     root          4096 Jan 31 07:53 ..
drwxr-xr-x    2 elyashiv elyashiv      4096 Feb 10 14:29 games
drwx------    2 root     root         16384 Feb 10 14:13 lost+found
```

**Comment by 89luca89** [comment]
Hi @elyashivhazan do you still have this issue?
I'm not able to reproduce this sadly

**Comment by elyashivhazan** [comment]
Hi @89luca89, no I don't have this issue any more.

Thanks for checking this issue.
