### ISSUE TITLE
[Error] Distrobox creates a malformed desktop entry

### ISSUE THREAD

**Issue by poperigby** [89luca89/distrobox#602]
**Describe the bug**
When Distrobox creates a desktop entry for the new container, it uses the wrong name for the category in the `.desktop` file it creates. It uses `Category` instead of `Categories`. It also adds an extraneous `"` at the end of the line. This causes the desktop entry to only show up in the Lost & Found section of the application launcher.

**To Reproduce**
Run `distrobox create test`

**Expected behavior**
The desktop entry that Distrobox creates ends up in the System and Utilities sections of the application launcher.

**Logs**
N/A

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.3.1
 - Which version of distrobox? 1.4.2.1

**Additional context**
This is the desktop file it created for the `test` container:
```
[Desktop Entry]
Name=Test
GenericName=Terminal entering Test
Comment=Terminal entering Test
Category=Distrobox;System;Utility"
Exec=/usr/bin/distrobox enter test
Icon=/home/cassidy/.local/share/icons/distrobox/fedora.svg
Keywords=distrobox;
NoDisplay=false
Terminal=true
TryExec=/usr/bin/distrobox
Type=Application
```

For it to work correctly, it should look like this:
```
[Desktop Entry]
Name=Test
GenericName=Terminal entering Test
Comment=Terminal entering Test
Categories=Distrobox;System;Utility
Exec=/usr/bin/distrobox enter test
Icon=/home/cassidy/.local/share/icons/distrobox/fedora.svg
Keywords=distrobox;
NoDisplay=false
Terminal=true
TryExec=/usr/bin/distrobox
Type=Application
```

**Comment by 89luca89** [comment]
Hi @poperigby I've just tested now with `generate-entry` and it seems the desktop file is generated correctly

You can check here that it is using `Categories` and no quotes are used: https://github.com/89luca89/distrobox/blob/main/distrobox-generate-entry#L277

**Comment by poperigby** [comment]
Oh, it looks like someone fixed it last month, but the Fedora version hasn't been updated yet. Thanks!
