### ISSUE TITLE
[Error] openSUSE > browser's idea of date/time incorrect 

### ISSUE THREAD

**Issue by pablos-here** [89luca89/distrobox#603]
**Describe the bug**

Hi,

On `openSUSE Tumbleweed` and `Leap`, `brave` uses GMT.  Ignoring the host's timezone.

Using `Ubuntu 22.10`, I do not see the problem.

Using `date`, all containers report the same date/time as the host.

**To Reproduce**

Prepare Host OS:

- openSUSE MicroOS
- Timezone not set to GMT.

Recipe using openSUSE Tumbleweed:

1. `$ distrobox-create --name vpn-leap --image registry.opensuse.org/opensuse/leap:latest`
2. `$ distrobox enter vpn-tw `
3. Install Brave in vpn-tw - see https://brave.com/linux/
4. $ brave-browser 
5. Go to your favorite website
6. Check brave history via `ctrl-h` and note the time is in GMT.

Note, brave has the ability to display a clock on a new tab.  As expected, the issue affects this widget.

**Expected behavior**

Brave should use the host local time.

**Logs**

[vpn-leap.logs.gz](https://github.com/89luca89/distrobox/files/10542119/vpn-leap.logs.gz)

**Desktop (please complete the following information):**

 - `podman version 4.3.1`
 - `distrobox version: 1.4.2.1`

**Additional context**

- The problem is the same with `Firefox`.
- During `distrobox-create` I tried using `--additional-flags` to pass in `--tz=local`.  Did not work.  :)

**Comment by 89luca89** [comment]
Hi @pablos-here inside the container, what does `date` say?
Timezones should be in sync with the host

**Comment by pablos-here** [comment]
Hi @89luca89 ,
Inside the container `date` returns the correct date.  Funky eh?  

Just to underscore, it does _not_ happen with `Ubuntu 22.10`.

**Comment by 89luca89** [comment]
> Hi @89luca89 , Inside the container `date` returns the correct date. Funky eh?

heh :-)

> Just to underscore, it does _not_ happen with `Ubuntu 22.10`.

Host or guest?

**Comment by pablos-here** [comment]
On 2023-02-10 15:10, Luca Di Maio wrote:
>
>     Just to underscore, it does /not/ happen with |Ubuntu 22.10|.
>
> Host or guest?
>
Hi!

A guest.  Here's  a summary of my test results:

  * openSUSE
      o Leap - has the issue
      o Tumbleweed - has the issue
  * Ubuntu 22.10 - no issue

I am happy to run any test you'd like.

Thank you so much!

**Comment by 89luca89** [comment]
What time does report if you open the browser Console (Ctrl+Shift+J) and enter the following command? 
`new Date()`

**Comment by pablos-here** [comment]
Hi @89luca89 ,

W00t, you pointed me in the right direction and I found the root-cause.  Thank you!

Both `openSUSE Leap` and `Tumbleweed` have `/etc/localtime -> /usr/share/zoneinfo/Etc/UTC`

When I manually symlink'd the Guest to match the host's timezone, `brave` is happy.  \o/

I'm not sure whether `distrobox` should handle the symlink'ing.  If not, we can close the Issue.

Thx so much!

**Comment by 89luca89** [comment]
Strange, this should work, I'm using OpenSUSE both as host and guest, and timezone is working correctly

**Comment by pablos-here** [comment]
Hmmm, is your host MicroOS?  Could that be the difference?

FWIW, I set up MicroOS in a VM.  I don't think that'd be material but .....

**Comment by 89luca89** [comment]
Yes I use MicroOS indeed, but the symlink is still like yours, it is not a relative symlink

**Comment by pablos-here** [comment]
What the heck?!   

Yesterday I re-created the VM using the latest ISO[1].    

Would it be helpful if I took care to write down every step so that you can try to reproduce the issue?

I don't think I'm doing anything fancy pants.  :\

### Reference
1 - `openSUSE-MicroOS-DVD-x86_64-Snapshot20230208-Media.iso`
