### ISSUE TITLE
[error] unable to install arch

### ISSUE THREAD

**Issue by godalming123** [89luca89/distrobox#604]
**Describe the bug**
When trying to create an arch distrobox after running:
```
distrobox create -i docker.io/library/archlinux:latest
```
(Which runs succsesfully)
I am unable to enter it with:
```
distrobox enter archlinux-latest
```

**Logs**
[test.txt](https://github.com/89luca89/distrobox/files/10549303/test.txt)

**Desktop (please complete the following information):**
- Host: nobara linux (fork of fedora)
 - Are you using podman or docker: Podman
 - Which version or podman or docker: 4.3.1
 - Which version of distrobox: 1.4.2.1

**Comment by godalming123** [comment]
For some readon it works now I assume that the mirrors were down.

**Comment by nathanchance** [comment]
This is likely due to the `filesystem` package getting upgraded, which seems to choke in `distrobox`:

```
$ sudo pacman -Syu --noconfirm
...
testing/filesystem               2023.01.30-1  2023.01.31-1    0.00 MiB       0.01 MiB
...
(1/7) upgrading filesystem                                                                                                                                         [#####################################################################################################] 100%
error: could not rename /etc/host.conf.pacnew to /etc/host.conf (Device or resource busy)
error: could not rename /etc/hosts.pacnew to /etc/hosts (Device or resource busy)
warning: /etc/shells installed as /etc/shells.pacnew
error: problem occurred while upgrading filesystem
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.
```

Just upgrading again fixes it.
