### ISSUE TITLE
[Discussion] Is is currently possible to not share a particular namespace

### ISSUE THREAD

**Issue by ldelossa** [89luca89/distrobox#608]
Is your feature request related to a problem? Please describe.

Currently, I do not necessarily see a way to run a distrobox container without sharing a specific namespace. I'm wondering if it possible. 

I'm using distrobox to develop eBPF programs which touch the network stack. It's very helpful to develop these applications in a "network sandbox". Meaning, I can create devs, remove them, mess with routing and routing policy, and then just "blow it away" when I'm done. 

However, I can't seem to find a way to have distrobox create my container without sharing the net namespace. I imagine the desire to do this extends further then just network namespaces. 

Describe the solution you'd like

Curious if there is currently a way to not share the network namespace when creating a distrobox container (based on fedora toolbox).

**Comment by ldelossa** [comment]
I didn't see a way to do it, so opened a PR which adds two new flags.

**Comment by 89luca89** [comment]
Hi @ldelossa 
There is some thinking in the #28 but nothing really worked on by me

There is already a standing PR in #478 which you could partecipate to have separate networking
