### ISSUE TITLE
[Suggestion] Create website

### ISSUE THREAD

**Issue by TheEvilSkeleton** [89luca89/distrobox#61]
Reading a long README is painfully annoying, especially when the installation procedure is far down the README. At least the table of contents is there, but it's still really hard to access because the README is overwhelmingly long.

I suggest creating a website (distrobox.github.io I guess) so we can have a good place to document without overwhelming a newcomer.

**Comment by misobarisic** [comment]
If @89luca89 gives me permission, I'll create a website using Next.js and deploy it. A one stop location with everything you'd need but presented in a noob friendly way.

**Comment by 89luca89** [comment]
Yeah i agree
Either that or a wiki here on github
Want also to integrate the info gathered on #51 and other stuff

**Comment by misobarisic** [comment]
GitHub wiki's content is not indexed by search engines. That is something to keep in mind.

**Comment by 89luca89** [comment]
> If @89luca89 gives me permission, I'll create a website using Next.js and deploy it. A one stop location with everything you'd need but presented in a noob friendly way.

You're welcome 😄 we can do that with github websites?

**Comment by misobarisic** [comment]
>  we can do that with github websites?

Most likely, yes. I remember reading a blog post about it some time ago but it was more complicated than what it in reality should have been.

What I've created so far. Does it look somewhat decent?
![image](https://user-images.githubusercontent.com/50531162/147609950-541d5056-008b-4779-93a8-bc960e4dd209.png)
![image](https://user-images.githubusercontent.com/50531162/147609974-c5efe886-5bca-44bb-a724-af6f34028ad6.png)

**Comment by 89luca89** [comment]
Can we make something simpler with github sites? 
Just to have all on here and don't have to host anything 😄

**Comment by 89luca89** [comment]
> > we can do that with github websites?
> 
> Most likely, yes. I remember reading a blog post about it some time ago but it was more complicated than what it in reality should have been.
> 
> What I've created so far. Does it look somewhat decent? ![image](https://user-images.githubusercontent.com/50531162/147609950-541d5056-008b-4779-93a8-bc960e4dd209.png) ![image](https://user-images.githubusercontent.com/50531162/147609974-c5efe886-5bca-44bb-a724-af6f34028ad6.png)

Thanks a lot I like the graphics
But I was thinking of something more of a static website to act as a all info center

**Comment by misobarisic** [comment]
This is a static page which more or less requires _compiling_. Hosting it is not a problem but if you were more interested into something simpler, sure. Just point me in the general design direction and we're set.

**Comment by TheEvilSkeleton** [comment]
I'm just gonna say it. Please add a dark mode.

**Comment by misobarisic** [comment]
> I'm just gonna say it. Please add a dark mode.

Dark mode. **Always**.

**Comment by 89luca89** [comment]
> This is a static page which more or less requires _compiling_. Hosting it is not a problem but if you were more interested into something simpler, sure. Just point me in the general design direction and we're set.

Sure, I would follow this 
https://docs.github.com/en/pages/quickstart
And use this theme 
https://github.com/pages-themes/midnight

It should work by putting all in a `./docs` directory in the project's root, and will be reachable at 89luca89.github.io/distrobox

**Comment by misobarisic** [comment]
Oh. You had jekyll in mind. Simple, the easiest to create. Will get the job done but it lacks character if you ask me.

**Comment by 89luca89** [comment]
Yes they're a bit underwhelming graphically but on the other side, it is possible to maintain the docs right here with the code, in markdown format like the rest of the readme and so on

**Comment by misobarisic** [comment]
What if we were to use [this](https://github.com/Drassil/git-wiki-theme). I quite like the look of it.
If not, the previous option sounds good

**Comment by 89luca89** [comment]
> What if we were to use [this](https://github.com/Drassil/git-wiki-theme). I quite like the look of it. If not, the previous option sounds good

Fancy 😄  Oh yes i like this git-wiki much more 😄

**Comment by 89luca89** [comment]
For now I've implemented a basic site using gh pages and cracking down the readme in various pages
I'm using the hacker theme for now and it's completely static

If someone has a better theme to suggest or a way to have a sidebar with the categories instead of doing with markdown TOCs like I'm doing now

https://89luca89.github.io/distrobox/

**Comment by 89luca89** [comment]
I've also now meged the site and the readme, so that it works the same on both github markdown and gh-pages

**Comment by misobarisic** [comment]
I have to say this but the theme you picked is looking rather nice.

**Comment by 89luca89** [comment]
Good :smile: It's the least blinding between the available choices :rofl: 

Anyway I hope the content is divided in a clearer manner now and it's more navigable and readable

**Comment by TheEvilSkeleton** [comment]
Excellent work! My only suggestions are to increase the font size because I had some trouble reading and decreasing the max-width. I suggest increasing the font to `22.5px` or even `25px`, and the padding to `0 2em 0 2em`.

It looks like this on a 1080p screen:
![image](https://user-images.githubusercontent.com/50847364/147994505-563a9de9-8b09-46a7-8982-1c2eb327140b.png)

**Comment by 89luca89** [comment]
Thanks, not really sure how to tweak this, tried dropping some font sizing in the `assets/css/style.scss` but didn't work
Waiting for someone more knowledgeable than me on this maybe :smile:

**Comment by TheEvilSkeleton** [comment]
I guess in the meantime you can just increase the font size.

**Comment by 89luca89** [comment]
> I guess in the meantime you can just increase the font size.

Yea was trying to do this but didn't succeed using gh-pages style override, but I must say I'm completely a css noob lol

**Comment by misobarisic** [comment]
I've examined the whole CSS file located [here](https://distrobox.privatedns.org/assets/css/style.css) and I have come to the conclusion that every header tag has a separate hard coded size in pixels. Best approach would be to create a media query targeting desktops and change the sizing **only** for desktop.

**Comment by 89luca89** [comment]
> I've examined the whole CSS file located [here](https://distrobox.privatedns.org/assets/css/style.css) and I have come to the conclusion that every header tag has a separate hard coded size in pixels. Best approach would be to create a media query targeting desktops and change the sizing **only** for desktop.

Yea was seeing the same, but the text of the non-header is simply the one declared in the body:

```css
body {
  margin: 0;
  padding: 0;
  background: #151515 url("../images/bkg.png") 0 0;
  color: #eaeaea;
  font-size: 25px;
  line-height: 1.5;
  font-family: Monaco, "Bitstream Vera Sans Mono", "Lucida Console", Terminal, monospace
}
```

I'm trying to override it without success tho, on gh-pages they say you can override stuff using `docs/assets/css/style.scss` but doesn't seem to work

**Comment by misobarisic** [comment]
@89luca89 give me a moment or two and I'll try it myself

**Comment by 89luca89** [comment]
I was already fiddling with it if you rebase on current main you'll have the directory in docs/assets

**Comment by 89luca89** [comment]
Technically if we manage to make the style working we could do this to zoom in a bit on all text:

```css
body {
   transform: scale(1.1); // zoom 110%
   transform-origin: 0 0;
   // add prefixed versions too.
}
```

**Comment by misobarisic** [comment]
> Technically if we manage to make the style working we could do this to zoom in a bit on all text:
> 
> ```css
> body {
>    transform: scale(1.1); // zoom 110%
>    transform-origin: 0 0;
>    // add prefixed versions too.
> }
> ```

That's a no-go. Responsive design should not rely on transform as its purpose is something else usually.

**Comment by misobarisic** [comment]
Update: I am not able to get a fully functional locally hosted page with jekyll. The theme is not working for me.

**Comment by 89luca89** [comment]
> Update: I am not able to get a fully functional locally hosted page with jekyll. The theme is not working for me.

I think you can just use 

misobarisic.github.io/distrobox

**Comment by misobarisic** [comment]
> > Update: I am not able to get a fully functional locally hosted page with jekyll. The theme is not working for me.
> 
> I think you can just use 
> 
> misobarisic.github.io/distrobox 

I wanted to test locally where changes would immediately propagate since gh may cache css files if I am not mistaken.

Guess I'll testing with a million commits on my branch 😂

**Comment by 89luca89** [comment]
> Guess I'll be testing with a million commits on my branch 

That's what I'm doing :joy:

**Comment by 89luca89** [comment]
I'd say this is implemented now, I'll close this, for future improvements on the website let's open a new issue if needed

thanks to all of you for the suggestions and ideas!
