### ISSUE TITLE
[Error] Permission error when exporting a read-only service

### ISSUE THREAD

**Issue by Lin-Junhao** [89luca89/distrobox#612]
**Description**
- Host OS: SteamOS 3.4.4
- Container OS: Arch Linux
- Podman version: 4.2.1
- Distrobox version: 1.4.2.1

I was trying to install [CUPS](https://wiki.archlinux.org/title/CUPS) and export its service `/usr/lib/systemd/user/cups.service` when I got a permission error. The service is read-only.

**To Reproduce**
```
(deck@distrobox-archlinux ~)$ distrobox-export --service cups.service
/home/deck/.local/bin/distrobox-export: line 535: /run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service: Permission denied
```

**Expected behavior**
`/usr/lib/systemd/user/cups.service`  is correctly exported to `/home/deck/.config/systemd/user/distrobox-archlinux-cups.service`.

**Logs**
<details open>
<summary>(deck@distrobox-archlinux ~)$ distrobox-export --service cups.service --verbose</summary>

```
+ '[' '!' -f /run/.containerenv ']'
+ grep -q rootless=0 /run/.containerenv
++ id -u
+ '[' 1000 -eq 0 ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ '[' -z cups.service ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n distrobox-archlinux ']'
+ container_name=distrobox-archlinux
+ '[' -z distrobox-archlinux ']'
+ container_command_prefix='/home/deck/.local/bin/distrobox-enter  -n distrobox-archlinux --  '
+ '[' -z '' ']'
+ exported_app_label=' (on distrobox-archlinux)'
+ case "${export_action}" in
+ export_service
++ find /etc/systemd/system/ /lib/systemd/system/ /usr/lib/systemd/system/ /lib/systemd/user/ /usr/lib/systemd/user/ /home/deck/.config/systemd/user/ -type f -name 'cups.service*'
++ tail -1
+ service_file=/usr/lib/systemd/system/cups.service
+ '[' -z /usr/lib/systemd/system/cups.service ']'
++ basename /usr/lib/systemd/system/cups.service
+ exported_service_file=distrobox-archlinux-cups.service
+ exported_service_fullpath=/run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service
+ '[' 0 -ne 0 ']'
+ '[' -f /run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service ']'
++ mktemp -u
+ temp_file=/tmp/tmp.08pnDhKHV8
+ mkdir -p /run/host/home/deck/.config/systemd/user/
+ cp -f /usr/lib/systemd/system/cups.service /run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service
+ for exec_cmd in ExecStart ExecStartPre ExecStartPost ExecReload ExecStop ExecStopPost
+ cp -f /run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service /tmp/tmp.08pnDhKHV8
+ grep ExecStart /tmp/tmp.08pnDhKHV8
+ grep -q '/home/deck/.local/bin/distrobox-enter  -n distrobox-archlinux --  '
+ sed 's|^ExecStart=|ExecStart=/home/deck/.local/bin/distrobox-enter  -n distrobox-archlinux --  |g' /tmp/tmp.08pnDhKHV8
+ sed 's|^ExecStart=.*|& |g'
/home/deck/.local/bin/distrobox-export: line 535: /run/host/home/deck/.config/systemd/user/distrobox-archlinux-cups.service: Permission denied
```
</details>

<details open>
<summary>(deck@distrobox-archlinux ~)$ ls -l /usr/lib/systemd/system/cups.service</summary>

```
-r--r--r-- 1 root root 291 Feb  2 03:02 /usr/lib/systemd/system/cups.service
```
</details>

<details open>
<summary>(deck@steamdeck ~)$ ls -l /home/deck/.config/systemd/user/distrobox-archlinux-cups.service</summary>

```
-r--r--r-- 1 deck deck 291 Feb  7 00:14 /home/deck/.config/systemd/user/distrobox-archlinux-cups.service
```
</details>

**Comment by 89luca89** [comment]
Hi @Lin-Junhao thanks for the report, this is fixed as of commit https://github.com/89luca89/distrobox/commit/8ec48cf42dd98c83b35b06e694146e0acfac6d52

**Comment by Lin-Junhao** [comment]
Thanks. It works. :)

**Comment by mthbrown** [comment]
@Lin-Junhao Could you detail how exactly you got **cups** to work on Steam Deck using **distrobox**? Thanks

**Comment by Lin-Junhao** [comment]
> @Lin-Junhao Could you detail how exactly you got **cups** to work on Steam Deck using **distrobox**? Thanks

Well actually I didn't manage to export CUPS service correctly. It brings up other services which aren't exported so it doesn't work.

It's better to use Podman that comes with Distrobox directly:

```
# podman run -d --rm -p 631:631 -e ADMIN_PASSWORD=mySecretPassword --name cups registry.opensuse.org/opensuse/cups:latest
```

See also: https://en.opensuse.org/Portal:Container/Image/cups
