### ISSUE TITLE
[Error] Exported programs not killed if tracked by launch PID

### ISSUE THREAD

**Issue by parkerlreed** [89luca89/distrobox#613]
**Describe the bug**

If a script launches an exported program and tracks the PID with `$!` , this PID belongs to sh executing the export script and not the real program.

**To Reproduce**

1. Setup container
2. Install PHP in container
3. distrobox export /usr/bin/php
4. On the host side
```
#!/bin/bash
~/.local/bin/php &
PID="$!"
kill $PID
```

The sh script is killed but /usr/bin/php continues to run in the distrobox container.

**Expected behavior**

Either the script passing on the real PID or killing the script also killing the process within the container. 

**Desktop (please complete the following information):**
 - Podman rootless
 - Podman 4.2.1
 - Distrobox 1.4.2.1

**Comment by 89luca89** [comment]
Closing this in favor of #966
