### ISSUE TITLE
distrobox support for cloud-init

### ISSUE THREAD

**Issue by grue-bleen** [89luca89/distrobox#614]
[cloud-init](https://cloudinit.readthedocs.io/en/latest/) is a uniform way to initialize cloud vm instances across multiple providers and distributions.  if distrobox were to use cloud-init, we would gain the ability to run cloud-init [predeploy testing](https://cloudinit.readthedocs.io/en/latest/howto/predeploy_testing.html) with distrobox.

cloud-init works with multipass, lxd and qemu today, but distrobox would be far more developer friendly.

**Comment by 89luca89** [comment]
Hi, i'm not planning to add support to cloud-init for now
There is `assemble` now that allows for declarative managing of boxes
