### ISSUE TITLE
[Suggestion] Keep HOME in the container

### ISSUE THREAD

**Issue by seal20** [89luca89/distrobox#618]
**Is your feature request related to a problem? Please describe.**
I am trying to increase reproducibility of my workflow (mostly R statistic) using containers. The idea is to have a container for each project that I can save and archive. This container should therefore have the OS, the installed R and its packages library. Here lies the problem. Toolbox or distrobox would share $HOME with the host, overwriting the default R library and creating conflict (R install packages in $HOME/R/version/ ). Distrobox can keep home separate from host but this is done by providing a separate folder (which I assume is mounted as volume), at least it is better, but it means I need to archive this folder too.

**Describe the solution you'd like**
What could be nice is to allow to use $HOME located inside the container. For example, having the --home with no path to a folder would default to have $HOME set to /home/user in the container.

**Describe alternatives you've considered**
I have tried to use podman rootless and create custom containers for each project. But this solution has its own problem, namely, the host home directory is not accessible and need to be mounted at run time and further volume cannot be (easily) added. As I am on Fedora, I also have to fight with SElinux. Distrobox has already taken care of it.

**Additional context**
Host os: Fedora 37
Image used: images from rocker-project.org (but any would be fine as long as I can install rstudio.

Sorry if there is a simple solution that I missed or if it is not possible to implement.

Thanks for distrobox, containers and tools as distrobox can radically change the way we work.

**Comment by 89luca89** [comment]
Hi @seal20 as @misobarisic said, it is already possible to do what you wanted
You can either use that config, or specify manually `--home /path/to/whatever` during create to have the custom home

**Comment by seal20** [comment]
Sorry I may not have been clear enough or I am misunderstanding. I know I can have a separate $HOME. What I want is to have $HOME to be a directory inside the container (like a normal container), meaning not integrating $HOME with the host at all (not storing the files, ie: R packages, config files, etc. on the host). However I still want to be able to access the files (data, figures, etc.) stored in the host user home folder. The goal is that I can save the container, send to another pc (coding on my laptop and send to beefy workstation) and run my code. With distrobox and a $HOME stored on the host, I have to reinstall the R package everytime I move the container.
Sorry it is difficult to understand or I am thinking wrong...

**Comment by misobarisic** [comment]
Install the packages inside the container somewhere other than its home if possible

**Comment by seal20** [comment]
Thanks @misobarisic You've given me a good idea. I can pass an environmental variable R_LIBS when I create the container using additional flags! Thanks a lot.
