### ISSUE TITLE
[Suggestion] add operator (&& , ;, ||) support to launch the app after open the container immediately

### ISSUE THREAD

**Issue by dtantono** [89luca89/distrobox#623]
**Is your feature request related to a problem? Please describe.**
I want to launch specific app. But, it will be tedious & repetitive if I must enter distrobox enter "distro name" and then few seconds later we need to put separate command to open the app

**Describe the solution you'd like**
in one instance, it will be great if we can run the app or multiple applications immediately after open the app in one clear command 
i.e: distrobox enter archlinux-latest && gedit
distrobox enter archlinux-latest ; gedit 
or distrobox enter archlinux-latest && gedit && kate && signal-desktop

**Describe alternatives you've considered**

**Additional context**

**Comment by 89luca89** [comment]
@dtantono 
Hi, i appreciate you interest in distrobox
But did you check the usage page or at least the `--help` ?

There is a `--/-e` flag already there to do what you ask

`distrobox enter archlinux -- gedit` or alternatively 
`distrobox enter archlinux -e gedit`
