### ISSUE TITLE
[Error] Incorrect distrobox-host-exec shebang on Silverblue host

### ISSUE THREAD

**Issue by gabrielkulp** [89luca89/distrobox#626]
**Describe the bug**
On a Fedora Silverblue host, `distrobox-host-exec` uses `#!/usr/bin/sh` as the interpreter, but this path does not exist in Alpine, leading to an opaque error:

```
bash: /usr/bin/distrobox-host-exec: cannot execute: required file not found
```

If you first execute `ln -s /bin/sh /usr/bin/sh` then the script works as expected. This solution is not quite perfect because of the double-redirection since Alpine makes `/bin/sh` a symlink to `/bin/busybox`. Instead, a "proper" solution would be to use `readlink` first to check if `/bin/sh` is a symlink and point to its target. I have locally implemented a temporary fix as a `container_init_hook` with the following script that at least works in Alpine, Debian, and Archlinux containers:

```sh
#!/bin/sh
if [ ! -x /usr/bin/sh ]; then
	ln -sf "$(readlink -f /bin/sh)" /usr/bin/sh
fi
```

**To Reproduce**
First, install Fedora Silverblue. Or maybe any Fedora. Or maybe other distros, I don't know. Then:
```sh
distrobox ephemeral --image docker.io/library/alpine:latest
# then, inside the container:
distrobox-host-exec
```

**Expected behavior**
A host shell should spawn, but does not because `distrobox-host-exec` cannot run in a fresh Alpine image.

**Desktop (please complete the following information):**
I'm using `distrobox` version 1.4.2.1 with `podman` version 4.3.1 as the backend. Host is up-to-date Fedora Silverblue.

**Additional context**
This may be because `which sh` on the Silverblue host returns `/usr/bin/sh`.

The first line of `distrobox-host-exec` in GitHub is `#!/bin/sh`, so this may just be a packaging issue in Fedora Silverblue. I just checked and at least in the Manjaro packaging, it is `#!/bin/sh` as expected, and the Alpine image works as expected without the above init hook.

Also rather strange: `distrobox-export` retains the correct `#!/bin/sh` shebang even when `distrobox-host-exec` does not. These two files are the same on the host system, too: `distrobox-export` uses `#!/bin/sh` while `distrobox-host-exec` uses `#!/usr/bin/sh`, though both execute on the host (printing a message that they must be run inside a container) since both `/bin/sh` and `/usr/bin/sh` work on Silverblue.

**Comment by 89luca89** [comment]
Hi @gabrielkulp this is a packaging problem, I think @alcir will be able to address it soon :+1:

**Comment by 89luca89** [comment]
> As these scripts should never be executed on the host anyways, would it make sense to exclude them from the host packages and install them in the container during init instead of mounting it from the host?

This is simply easier to ship
I can this way have a consistent versioning between "inside" and "outside" of the container

and can work "offline", if you have a dedicated distrobox image, the `init` shouldn't forcibly install stuff
and if you would include distrobox component within an image from the get-go, then you'd have images bounded to distrobox versions which would be unmanageable

**Comment by gabrielkulp** [comment]
Maybe this is obvious, but how about if the guest scripts are not on the host PATH, so they aren't (easily) executed as @schewara suggests, and this non-PATH location is mounted inside the container on its PATH to maintain versioning consistency as @89luca89 wants?

**Comment by 89luca89** [comment]
> Maybe this is obvious, but how about if the guest scripts are not on the host PATH, so they aren't (easily) executed as @schewara suggests, and this non-PATH location is mounted inside the container on its PATH to maintain versioning consistency as @89luca89 wants?

This also could be done, yes

Anyway for now this problem is specifically an RPM packaging problem so even moving that wouldn't help :shrug:

**Comment by 89luca89** [comment]
This should be opened to fedora's maintainer not here
