### ISSUE TITLE
[Suggestion] Apply VPN running on guest system to the host as well

### ISSUE THREAD

**Issue by eylenburg** [89luca89/distrobox#627]
Problem: 
My VPN providers only has an DEB package. They don't have a RPM or AppImage so I can't install it on my distro (OpenSUSE). However I could of course create an Ubuntu guest in Distrobox and install their VPN app there.

Suggestion:
It would be great if the VPN connection in the guest (here Ubuntu) also applies to the host (here OpenSUSE). So for example, if I connect to a VPN server via OpenVPN or Wireguard in Ubuntu, then all connections in OpenSUSE run through that VPN.

**Comment by 89luca89** [comment]
This is inherently not possible with a rootless container
If you use `--root/-r` you should already be able to run VPNs just fine
