### ISSUE TITLE
[Error] distrobox enter fails because distrobox create uses old image for arch which makes pacman fail gpg signature checks

### ISSUE THREAD

**Issue by Trollman16747** [89luca89/distrobox#629]
**Describe the bug**
So I wanted to create distrobox archlinux container, apparently it used old image for it (28 Dec was last time i created arch container) and when you try to enter it fails at installing basic packages, internally i've seen it failing with gpg signatures (standard thing for arch if you didn't update in ~2 weeks as far as i understand). I 'fixed' it with adding "--pull" flag to "distrobox create" command. I am not sure which way would be correct to fix this, but maybe add "--pull" automatically for arch (maybe for other distros?); ask/tell user about it or update keys for arch before trying to install packages. Sorry, didn't copy gpg part from container (cannot replicate right now after --pull, maybe 2-3 weeks later) and have no idea where older logs are, but here is how distrobox output looked:

```
distrobox enter arch-bugreport
Container arch-bugreport is not running.
Starting container arch-bugreport
run this command to follow along:

 podman logs -f arch-bugreport

 Starting container...                           [ OK ]
 Installing basic packages...                    Error: An error occurred
```

**Expected behavior**
distrobox should enter new arch container

**Desktop:**
podman version 4.4.1
distrobox version: 1.4.2.1
fedora (37) kinoite

**Comment by jerengie** [comment]
Hi,

maybe the issue is that you have an outdated image? Distrobox seems to always use `archlinux:latest`, but as I see it, the image is only pulled once when you start the first arch based container. I just installed distrobox today and immediately tried to use arch, without any issue :)

So `podman inspect archlinux` gives me `"Digest": "sha256:799424744d6bf6519f36b16ffff7927bc4a90b9581ac7905e8593b1ff347d045"`, can you check whether your image differs?

**Comment by misobarisic** [comment]
Distrobox will not repull images which are already present. Be it `archlinux:latest` or `ubuntu:20.04`. It does not know if one gets updated frequently or not, therefore you need to do it manually by running `podman pull archlinux:latest`. Your prior containers which use an outdated image will still be functional even if you pull a newer version.

**Comment by ryanayoung** [comment]
I ran in to the same problem, so thank you for the workaround.

Still seems odd. To me "latest" implies that it will pull the latest version down. Not that it's using the latest local copy

**Comment by Trollman16747** [comment]
You are welcome.
I think that it is weird as well. I *was* about to say something like "ok it was not obvious but at least it's in the docs", but i don't see it [here](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md). Another option would be to add a note to the ":latest" option i guess. (And thanks for clarifications btw)

**Comment by 89luca89** [comment]
This is simply how docker/podman works :) 
Even if you say `:latest` it uses the latest cached version, if you don't explicitly tell to `--pull` it

> Another option would be to add a note to the ":latest" option i guess. (And thanks for clarifications btw)

Could be an option yes
