### ISSUE TITLE
[Suggestion] support for /run/.distroboxenv file

### ISSUE THREAD

**Issue by schewara** [89luca89/distrobox#630]
It would be great to have a `/run/.distroboxenv` file available in the same or similar way as `toolbox` has the `/run/.toolboxenv` file.

This could then be leveraged in multiple places and tools, for checking the runtime context.

In my personal case, it would be super helpful to have a visual indicator (`PS1`) to display that my shell is running in a distrobox container.

Having the file and adding some functionality to `/etc/profile.d/distrobox_profile.sh` , in a similar way as [/etc/profile.d/toolbox.sh](https://github.com/containers/toolbox/blob/main/profile.d/toolbox.sh#L47) would solve my problem.

I am aware of the `distrobox create --pre-init-hooks ...` possibility, but having it baked in would be way more user friendly.

**Comment by 89luca89** [comment]
> It would be great to have a /run/.distroboxenv file available in the same or similar way as toolbox has the /run/.toolboxenv file.
>
> This could then be leveraged in multiple places and tools, for checking the runtime context.

This is actually a great idea!
I'd be more keen to have a unified behaviour with toolbx, and try to follow their standard
like, having same file name and content (at most, adding more info?) in order to have pet-containers standardized between the two implementations

> Having the file and adding some functionality to /etc/profile.d/distrobox_profile.sh , in a similar way as [/etc/profile.d/toolbox.sh](https://github.com/containers/toolbox/blob/main/profile.d/toolbox.sh#L47) would solve my problem.

Can you share some example of what you'd add in it?
