### ISSUE TITLE
debian distrobox behind a proxy

### ISSUE THREAD

**Issue by briner** [89luca89/distrobox#631]
I've got the problem to work with distrobox behind a proxy.

After some searching on the web, I've found no information on how to do this.

So this is my receipe on creating a **debian** distrobox and tell him to create /etc/apt/apt.conf.d/proxy.conf
```bash
proxy=http://my_proxy.domain.example:3128
t="echo 'Acquire::http::Proxy \\\""${proxy}"\\\";' > /etc/apt/apt.conf.d/proxy.conf; echo 'Acquire::https::Proxy \\\""${proxy}"\\\";' >> /etc/apt/apt.conf.d/proxy.conf;"
http_proxy="${proxy}" distrobox create --image debian --name deb --pre-init-hooks "${t}"
```

**Comment by briner** [comment]
I've created this issue to some how document how I solved this successfully.

**Comment by 89luca89** [comment]
Hi @briner 
would you like to add a paragraph in the docs about it? Seems useful :)

It would go into the `useful_tips.md` if you'd like to do it :smile: 
Or if anyone is interested in adding this to the docs :+1:
