### ISSUE TITLE
[Suggestion] distrobox-export: run in login shell 

### ISSUE THREAD

**Issue by Scafir** [89luca89/distrobox#639]
**Is your feature request related to a problem? Please describe.**
Some binaries may expect the presence of certain environment variables to function properly (in my case: petalinux suite from Xilinx). 
As of now, it is impossible to run such binaries with distrobox, except by specifying each variable in the Containerfile, which may cumbersome. This is a bit annoying because otherwise distrobox is the perfect tool to run that type of cumbersome proprietary software which are supported on a few, potentially end-of-life platforms.

**Describe the solution you'd like**
This issue mainly comes from the fact that the binaries are ultimately run with `podman exec  <container> <binary>` which does not provide a login shell as such. I suggest modifying https://github.com/89luca89/distrobox/blob/6af1458efffa5879abc82899be6f2f4d8cdf7d99/distrobox-export#L249 to insert `bash -l -c` in front of `${is_sudo} ${exported_bin} ${extra_flags} "`.

This can be either a new default, or through a new option which could be named `--login` during the export.

**Describe alternatives you've considered**
Alternatives either involve manually editing the exported scripts, edit the Containerfile, which are a bit cumbersome. The other option would be to find somehow a way to source files for non-interactive, non-login shells, but I am not aware of a universal way to accomplish that.

I would be willing to make a merge request if this idea is well recieved.

**Comment by abyszuk** [comment]
+1 to this!
I may add that these environment variables aren't completely static, so just adding them to the Dockerfile is not the proper way to solve it.
Software like Xilinx Vivado, Xilinx Petalinux, Intel Quartus or Microchip Libero comes with a script(s) that should be sourced before launching main binary (e.g. `source /opt/Xilinx/petalinux/settings.sh`) - this script may change with each tool version.
When building ready-to-use images with these tools it's convenient to make this env variable setup automatic - either through completely custom entrypoint script, or by adding them to `/etc/profile.d` and using login shell.
