### ISSUE TITLE
[Discussion] Implement "re-create" and "auto-upgrade"

### ISSUE THREAD

**Issue by equals03** [89luca89/distrobox#644]
_Is your feature request related to a problem? Please describe._
It's not a problem as such. More of a workflow issue.  

I manage my distroboxes via Github Actions (much like https://github.com/ublue-os/boxkit) so that I can synchronize them between my various installations. If I need something I add it to the repository, let it build and on success I pull the image down to the client machines. Every time this happens though, I need to manually remove the container and recreate it.   
Not a biggie, but I'm lazy 😄  

_Describe the solution you'd like_
I would like to:
1. quickly recreate the container, using the latest image, with the exact same arguments as I used to create it,
2. automate this process if a new image is pulled/detected.

I have implemented a very rough solution (definitely not production ready) that, whenever I create my distroboxes, I label them with an `INSTALL` label that is - basically - the create arguments I passed to distrobox [patch to `distrobox-create`]. When I use my own `distrobox-recreate`, it checks for this label, if its there it will `rm` the container and re-create it automatically using arguments in the `INSTALL` label.  
This has been working fine but I realized that I very often head over to my other machine, boot into my distrobox and realize I've forgotten to pull the new image. I have to exit, pull, recreate. This then encouraged me to work on another "rustic" script that would inspect the container for the image information and compare the named image digest with the image digest stored with the container. If they were different I would recreate using the above. One `systemd` unit later and as long as the distroboxes weren't in use (or on next reboot) they would be upgraded. And that's how `distrobox-autoupgrade` was birthed to much wailing and gnashing of teeth.

This works for me because I keep the boxes as "stateless" as possible. I don't keep anything that's not in my github build.

Anyways, this discussion is merely just me putting out some feelers to see if I was the only one with this need and if you would like me to try bring my scripts inline with this project and make a submission.

_Describe alternatives you've considered_
At first I attempted to use the podman auto-update feature but this completely broke the boxes so I quickly abandoned it. 

_Additional context_
My bash skills are borderline dangerous, but I feel that using the existing scripts as a base I could get them to be, at the very least, passable.

**Comment by 89luca89** [comment]
This is easily solved by using `assemble` with the `--recreate` flag

Regular boxes (non assemble-managed) cannot be easily reproduced so I prefer to leave to the user to remove and redo them
As it's a more involved and intentional process
