### ISSUE TITLE
[Discussion] Opening links from inside container on host

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#645]
Currently, opening links from inside container without having browser installed inside container is a massive pita,
you have to manually link desktop files, use xdg utils from flatpak, which makes it all very crumblesome and really not easy to handle...
Maybe distrobox should have some commands to automate process of making host browser as default one inside container?
Not automatically of course, as maybe you **do** want to make inside browser as main one, but with separate command.
By host browser i mean any one that is defined as default, that includes flatpak (like, firefox flatpak, chromium host, etc etc).

**Comment by Meister1593** [comment]
I specified only web browsers as an primary pain point, but i assume that something like that can be applied to other programs too (but i'm unsure about other ones that would have the same issue)

**Comment by 89luca89** [comment]
I think the best way should be to just use `xdg-open` via `distrobox-host-exec`

just do a `sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open` inside your distrobox, and all should work correctly now

Maybe I should consider providing some of those by default? (maybe flatpak, xdg-open, stuff like this)

**Comment by Meister1593** [comment]
> I think the best way should be to just use `xdg-open` via `distrobox-host-exec`
> 
> just do a `sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open` inside your distrobox, and all should work correctly now
> 
> Maybe I should consider providing some of those by default? (maybe flatpak, xdg-open, stuff like this)

i would say it might work like that but it doesn't cover programs that aren't using xdg-open
like, opening a link inside application that is inside distrobox
that would probably use xdg mimetypes and associated applications

**Comment by poperigby** [comment]
> Maybe I should consider providing some of those by default? (maybe flatpak, xdg-open, stuff like this)

I think that would be a good idea.

**Comment by dklawren** [comment]
> > I think the best way should be to just use `xdg-open` via `distrobox-host-exec`
> > just do a `sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open` inside your distrobox, and all should work correctly now
> > Maybe I should consider providing some of those by default? (maybe flatpak, xdg-open, stuff like this)
> 
> i would say it might work like that but it doesn't cover programs that aren't using xdg-open like, opening a link inside application that is inside distrobox that would probably use xdg mimetypes and associated applications, which are of course not the same as on host

This fixed Github authentication somewhat for me when running VSCode under distrobox. It will open github.com and perform the authentication, but then it cannot redirect back to let  the VSCode running in distrobox know about it. The desktop instead asks if I want to install something to handle the request.  Has anyone came up with a work around for this type of workflow or is this something that will not work without having the full application (VScode) installed on the host system?

**Comment by adocquin** [comment]
@dklawren Regarding this issue, [this solution works](https://stackoverflow.com/questions/75717394/vscode-settings-sync-with-github-account-not-working).
You do not have to run the `xdg-mime` command: Replace the `Exec` value with `/usr/bin/distrobox-enter -n you_distrobox_name -- /usr/share/code/code --open-url %U` and select the vscode program when asked to open the Github redirection link :)
