### ISSUE TITLE
Vscode integration with distrobox-export using container OS

### ISSUE THREAD

**Issue by jvellojin** [89luca89/distrobox#646]
Following the instructions to integrate Vscode to Distrobox "the easy way" I managed to get access to Vscode inside the container. However, the Python, C++, and other interpreters, as well as the active terminal, are those of the host and not those of the container.

This approach is different, and not equivalent, to the one expressed by the "not so easy way" in the documentation, where a .json configuration file is attached to open folders in the Distrobox container. However, in this approach you lose the host permissions for screen sharing or running GUIs (such as matplotlib, gnuplot, xeyes, etc).

At the moment I have a UBUNTU 22.04 Distrobox container and I would like to have Vscode integrated into this container, with the container terminal, and full permissions to plot and display GUI within the program. But I don't know how to proceed.

**Comment by jvellojin** [comment]
> I installed vscode inside the container, and start it using the exported app or bin.

Were you able to use the programming languages installed inside the container (Python, Java, C++, etc.)? I installed Vscode inside the container but it only detects the languages installed on the host. For example, in my case, I have Fedora 37 as the host using Python 3.11, whereas the Ubuntu 22.04 container has Python 3.10. I was not able to use this version but the 3.11.

**Comment by Hypnotist1148** [comment]
> > I installed vscode inside the container, and start it using the exported app or bin.
> 
> Were you able to use the programming languages installed inside the container (Python, Java, C++, etc.)? I installed Vscode inside the container but it only detects the languages installed on the host. For example, in my case, I have Fedora 37 as the host using Python 3.11, whereas the Ubuntu 22.04 container has Python 3.10. I was not able to use this version but the 3.11.

Are you sure vscode was running inside your distrobox?
I had some weird cases where I had a vscode window open which has been running in my distrobox, and on me trying to open vscode on my host it would still open inside the distrobox.

How were you opening vscode? Via the `code` command or a exported desktop shortcut?
Maybe try running vscode using `code --verbose` - make sure you are in your distrobox by using the `hostname' command.

**Comment by wlinna** [comment]
Here's what I did to make sure I run vscode from Distrobox:
I created a folder called `distrobox` in my `home` folder and then inside Distrobox I start vscode with `--user-data-dir distrobox` to make sure it doesn't  get confused with the host vscode. You can also add it to the exported .desktop file.

Somehow the same extensions are still present. I would have thought that using a different user-data-dir would mean that it uses different extensions too.
