### ISSUE TITLE
Ubuntu 18.04 container doesn't work

### ISSUE THREAD

**Issue by alcir** [89luca89/distrobox#65]
It is stated that Ubuntu 18.04 is a supported container distro, but

```text
[user@pc ~]$ distrobox-create --name ubuntu-18 --image docker.io/library/ubuntu:18.04
e4a127e1cf407e72033dc8f34326c1793796de62f97ecbc871ad71823824b89b
Distrobox 'ubuntu-18' successfully created.
To enter, run:
	distrobox-enter --name ubuntu-18
[user@pc ~]$    distrobox-enter --name ubuntu-18
Starting container ubuntu-18
run this command to follow along:
	podman logs -f ubuntu-18
.......
done!
Error: executable file `bash` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred
```

**Comment by 89luca89** [comment]
Hi @alcir 
Can i have the output of the podman logs? Probably something went wrong with the container initialization 

Thanks!

**Comment by alcir** [comment]
Sure

[log.txt](https://github.com/89luca89/distrobox/files/7789731/log.txt)

**Comment by 89luca89** [comment]
Seems like the container bootstrapped correctly
I've tried it right now and it works indeed, seems like a problem with your PATH 
Can you do 

`distrobox-enter --name ubuntu-18 --verbose`

to check? It should not have this type of problem, as for now you can see in line 163 of `distrobox-enter` I ensure that the standard FHS path is present (`/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin`)

Let's see if the problem is there

**Comment by alcir** [comment]
> `distrobox-enter --name ubuntu-18 --verbose`

[log2.txt](https://github.com/89luca89/distrobox/files/7789767/log2.txt)

**Comment by alcir** [comment]
Mmmh, I tryed on another Fedora host, and there, with `podman logs -f ubuntu-18` I simply get
`exec container process (missing dynamic library?) `/usr/bin/entrypoint`: No such file or directory`

**Comment by 89luca89** [comment]
Got it, can reproduce now
It's not adding the default `/bin/` and `/sbin/` paths to PATH correctly, hence it will not find `bash` in ubuntu-18
It doesn't work with your PATH, it works with my PATH, probably need to check in a better way while building up the PATH variable.

**Comment by 89luca89** [comment]
@alcir opened a new pull to fix this, can you check if the fix works? 
It worked for me after I've reproduced your PATH

**Comment by alcir** [comment]
Works for me :+1:

**Comment by 89luca89** [comment]
Cool! :tada:
