### ISSUE TITLE
[Error] Distrobox enter stops container at the end - WSL

### ISSUE THREAD

**Issue by azeveco** [89luca89/distrobox#652]
**Describe the bug**
I'm trying to `distrobox enter` using a Podman image I have and all the steps are done, including one named "Starting container" which is marked as "Ok". At the end, after the "Container Setup Complete!" message, I get a new one saying: `Error: can only create exec sessions on running containers: container state improper`.

It seems that the container is killed at the end.

**To Reproduce**
Create a box and try to enter using WSL2 (Ubuntu).

**Expected behavior**
Keep the container running to properly enter it.

**Logs**
[distrobox enter log.txt](https://github.com/89luca89/distrobox/files/10942545/distrobox.enter.log.txt)
[dbus log.txt](https://github.com/89luca89/distrobox/files/10942550/dbus.log.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 3.4.4
 - Which version of distrobox? 1.4.2.1

**Additional context**
I'm in a WSL2 (Ubuntu) environment.

**Comment by 89luca89** [comment]
Hi @azeveco WSL2 is not a supported platform, so I don't know how I can help
