### ISSUE TITLE
[Question] Is it possible to specify different history files?

### ISSUE THREAD

**Issue by cynicalsubject** [89luca89/distrobox#657]
Hi. Loving distrobox, but I have a little issue/question.

I'm currently using 2 containers that do completely different things, so I want to keep their `zsh` history files separate, as well from the host itself. I was thinking on using an environment variable that'd later be read by `zsh`'s configuration (`HISTFILE`), but I'm not sure how to send an environment variable to the container in this way.

Any suggestions?

**Comment by nathanchance** [comment]
You should be able to use the `--additional-flags` option to define the `HISTFILE` value you want directly for each container, which I think should work?

```
--additional-flags --env=HISTFILE=/...
```

**Comment by nain-F49FF806** [comment]
For this use case would you rather use the separate home feature?

You can ask distrobox to use a separate home directory using the `--home` flag during create. 
This way your histfiles (as well as other dot files) will remain separate for those distroboxes. 

Basically 

    distrobox create  --name box.apple --home ~/Distroboxes/box.apple

    distrobox create  --name box.orange --home ~/Distroboxes/box.orange

This way you'll have separate environments for your host and each individual distrobox.

**Comment by cynicalsubject** [comment]
That was the first that came to mind, but I was hesitant cause it'd break other changes I've made. I've currently testing the other suggestions first, though it seems the different home setting may be the "cleanest" solution.

**Comment by cynicalsubject** [comment]
That leads to another question. Is it possible to send environment variables to a distro that's already created? I'd imagine that changing the home directory would be difficult.

**Comment by misobarisic** [comment]
You can create a new distrobox by cloning an already present one and setting its environment variables with `--additional-flags`

**Comment by cynicalsubject** [comment]
Nice. Is it possible to modify them at all after creation? I mean, clone works, just curious if they could be modified later for whatever reason.

**Comment by cynicalsubject** [comment]
Ok. Seems I've been successful with your help. These are the steps I followed:

First, I created a clone of my distro:
   
    distrobox --clone distro1 -n distro1_clone --aditional-flags "--env HISTFILE=~/histfiles/distro1.history"

... but, this doesn't work, the file as I specified it cannot be found. To change it I used the following:

Stop the distro container:

    distrobox stop distro1_clone

Modify the environment variable:

    docker commit --change='ENV HISTFILE=${HOME}/histfiles/distro1.history' distro1_clone distro1_clone_updated

Removed the old clone container:

    docker rm distro1_clone

Re-create the distro using the updated image:

    distrobox create distro1_clone --image distro1_clone_updated

Now `distro1_clone` works as expected. I can now adjust the original `distro1` using the same steps.

Thanks for the guidance!
