### ISSUE TITLE
[Suggestion] Add Android-86 container image

### ISSUE THREAD

**Issue by FatalError93** [89luca89/distrobox#659]
If possible, add [Android-86](https://www.android-x86.org)  container.

I am not sure if it's possible, but if it is, it would improve host distro integration with android apps.

Merrits would be numerous.

**Comment by 89luca89** [comment]
Does the android-x86 docker image exist?
If it exists we can test it, if it does't then there isn't much distrobox could do about that

**Comment by mirkobrombin** [comment]
I found these:
- https://hub.docker.com/r/budtmo/docker-android-x86-8.1
- https://hub.docker.com/r/bitriseio/docker-android (which is based on docker-android-x86-8.1)

**Comment by 89luca89** [comment]
These sadly use the emulator in background, they are more like a docker wrapper around the emulator

**Comment by mirkobrombin** [comment]
I think those are the only available images

**Comment by 89luca89** [comment]
Yea then we can't have android sadly

**Comment by FatalError93** [comment]
I found this: `https://github.com/sickcodes/dock-droid` with [docker container](https://hub.docker.com/r/sickcodes/dock-droid/tags?page=1&ordering=last_updated), but it uses KVM sadly. On the bright side, there is WIP to make it [run without KVM](https://github.com/sickcodes/dock-droid#run-without-kvm-work-in-progress).

**Comment by 89luca89** [comment]
> I found this: https://github.com/sickcodes/dock-droid with [docker container](https://hub.docker.com/r/sickcodes/dock-droid/tags?page=1&ordering=last_updated), but it uses KVM sadly. On the bright side, there is WIP to make it [run without KVM](https://github.com/sickcodes/dock-droid#run-without-kvm-work-in-progress). EDIT: formatting

Interesting! 
Let's keep an eye on the development :)
