### ISSUE TITLE
[Error] The logo for Arch Linux is no longer available

### ISSUE THREAD

**Issue by yorickpeterse** [89luca89/distrobox#661]
**Describe the bug**

When creating a container using Arch Linux, Distrobox downloads the icon from https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Archlogo900.png/640px-Archlogo900.png. This URL is no longer available and reports an HTTP 404. This results in Distrobox downloading the HTML file, resulting in no logo being displayed.

**To Reproduce**

1. `distrbox create --image archlinux --name arch`
2. `file ~/.local/share/icons/distrobox/arch.png` will report the file as being a text/HTML file

**Expected behavior**

Either an error is produced, or some sort of fallback icon is used.

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.4.2
 - Which version of distrobox? 1.4.2.1

**Comment by mirkobrombin** [comment]
Alternative link: https://www.vectorlogo.zone/logos/archlinux/archlinux-icon.svg

**Comment by yorickpeterse** [comment]
@89luca89 Thanks for the fix! :tada:
