### ISSUE TITLE
[Error] `distrobox create` fails on fresh CoreOS installation due to missing `/etc/localtime`

### ISSUE THREAD

**Issue by bsherman** [89luca89/distrobox#664]
`distrobox create` fails on fresh CoreOS installation due to missing `/etc/localtime`

**To Reproduce**
1. Install Fedora CoreOS
2. `rpm-ostree install distrobox`, and reboot
3. `distrobox create`
4. observe failure

```
[core@ucore-test1 ~]$ distrobox create
Creating 'my-distrobox' using image registry.fedoraproject.org/fedora-toolbox:36	Error: statfs /etc/localtime: no such file or directory
 [ ERR ]
```

This fails because CoreOS defaults to UTC time with no `/etc/localtime` symlink present. If timezone is set with `timedatectl` the symlink is created as would normally be expected.

**Expected behavior**
distrobox should create successfully, even when `etc/localtime` is missing. 

**Logs**
[distrobox create verbose.log](https://github.com/89luca89/distrobox/files/11012010/distrobox.create.verbose.log)

Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - podman
 - 4.4.1
 - 1.4.2.1

**Additional context**
This bug report prompted by discussion on this [workaround commit](https://github.com/ublue-os/ucore/commit/2d2611aca60632f9f8b69e1dce767a7ca6c0dc23#comments)

**Comment by 89luca89** [comment]
@bsherman pushed a fix for this :)
