### ISSUE TITLE
Centos based Distrobox creation completes correctly but distrobox enter command fails at step: Installing basic packages: Error: an Error occured

### ISSUE THREAD

**Issue by viktormadarasz** [89luca89/distrobox#665]
**Describe the bug**

Centos based Distrobox creation completes correctly 
but **distrobox enter** command **fails** at step: **Installing basic packages: Error: an Error occured**

On the same host creating other type of distrobox containers works correctly.

_f.e Ubuntu_  with the command **distrobox-create --name ubuntu-distrobox --image ubuntu** Completes ok
When issued **distrobox enter ubuntu-distrobox**  all steps including _Installing Basic Packages_ completes and I land inside the container.

**To Reproduce**

```
viktormadarasz@fedora Downloads]$ uname -na
Linux fedora 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[viktormadarasz@fedora Downloads]$ distrobox-create --name centos-stream8-distrobox --image centos:8
Creating 'centos-stream8-distrobox' using image centos:8	 [ OK ]
Distrobox 'centos-stream8-distrobox' successfully created.
To enter, run:

distrobox enter centos-stream8-distrobox

centos-stream8-distrobox

$

[viktormadarasz@fedora Downloads]$ distrobox enter centos-stream8-distrobox
Container centos-stream8-distrobox is not running.
Starting container centos-stream8-distrobox
run this command to follow along:

 podman logs -f centos-stream8-distrobox

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 Error: An error occurred

$
```

**Expected behavior**

To complete all steps without error when issued distrobox enter containername and land me inside the containers terminal 
[githublog.txt](https://github.com/89luca89/distrobox/files/11015382/githublog.txt)
shell.

**Logs**

Logs attached from --verbose as txt

**Comment by 89luca89** [comment]
Hi @viktormadarasz 
check in the compatibility list, the image is not `centos:8` but `centos:stream8`
The `centos:8` repos are unactive nowadays so it cannot install stuff

**Comment by viktormadarasz** [comment]
Thanks a lot.. My fault.
Fixed it.Works with centos:stream8 as --image
