### ISSUE TITLE
[Help] Howto resolve dbus error when running RStudio in containerized Debian ... 

### ISSUE THREAD

**Issue by btreut** [89luca89/distrobox#668]
I am trying to get RStudio running in the OStree/flatpak based distribution [EndlessOS](http://community.endlessos.com), finnaly arrived at a solution based on podman (see [post](https://community.endlessos.com/t/problems-running-rstudio-via-podman/13683/8)). With a newer version of EndlessOS, podman was upgraded and I restarted experimenting this time with distrobox. I successfully set up a Debian bullseye (11.6) container and installed RStudio within the container ignoring the following messages I got during startup of Rstudio:
```
[1953:0322/124855.414678:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1953:0322/124855.415027:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1987:0322/124856.211165:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is
 ```
since RStudion did run without apparent problems. But after installation of several RStudio extensions (and some deb packages, which were required for installation of these extensions) for learning R (shiny,curl,libcurl,learnr) I encountered during installation of tidyverse the following error within RStudio:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Warning in system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
** testing if installed package can be loaded from final location
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Warning in system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
 ```
Reading a bit in [Podman in Action](https://livebook.manning.com/book/podman-in-action/chapter-7?origin=product-toc) about systemd integration, I fear that setting this up correctly is beyond my knowledge, so I am asking here for help. 

Additional Information:
podman version 3.0.1 (it is afaik tightly integrated in Endless OS 5.0.1)
distrobox version 1.4.2.1

**Comment by btreut** [comment]
Does it make sense to re-create the box with ```--init```?

**Comment by btreut** [comment]
Does it make sense to re-create the Debian box with the ```--init``` option?

**Comment by 89luca89** [comment]
Hi @bsvh 
You can try doing an init distrobox
But be aware, only opensuse and the other distros with "-init" in their image name will work, no Debian with init support is there

**Comment by btreut** [comment]
@89luca89 thanks for

> "-init" in their image name will work, no Debian with init support is there

before switching to a completely other distro, I started investigating the situation a bit and found that entering the Debian box and issuing a ```pstree -p``` reveals a systemd process with pid 1 exactly the same as the one found on the host. So I am puzzled: why does RStudio complain and why is it unable to communicate with pid 1. More info about my system (including process list under heading .```= Processes =``` can be found in the eos-diagnostic... file linked in my [post](https://community.endlessos.com/t/missing-apps-for-another-window-session-manager/20103) on the EndlessOS community platform.

**Comment by btreut** [comment]
ok, intermediate result:

in the box: there is no ```/run/dbus/system_bus_socket```, but this socket is available in the host environment. 

What is the best way to allow access in the box to the socket ```/run/dbus/system_bus_socket```?

**Comment by btreut** [comment]
> So you have systemd running on your host?

absolutely correct

> What command did you use for creating the box?

```distrobox create --image debian:latest --name debian```

and @89luca89 does not recommend to add a ```-i``` if the image is not prepared for that.

**Comment by btreut** [comment]
> What is the best way to allow access in the box to the socket `/run/dbus/system_bus_socket`?

Found this [Post](https://stackoverflow.com/questions/64043565/dbus-communication-from-docker-to-host-and-reverse), does this provide a solution?

**Comment by btreut** [comment]
Very strange: I followed the instructions of @firefoxlover given in this [post](https://github.com/rstudio/rstudio/issues/3079#issuecomment-1486786945) and there are no problems with communication with ```systemd``` under Fedora.

So this might be an issue with the Debian image, therefore I close this issue here.

**Comment by firefoxlover** [comment]
> .

yes the images sometimes have weird problems, I once had Ubuntu without apt

I also would use the newest image possible e.g. not Debian. Fedora with the COPR for the modules should work, but I dont know how other distributions handle that
