### ISSUE TITLE
Can't run example Ubuntu container

### ISSUE THREAD

**Issue by castrojo** [89luca89/distrobox#67]
Hi! Thanks for working on this. I'm following along with [this article](https://fedoramagazine.org/run-distrobox-on-fedora-linux/) and I tried this initial command: 

    distrobox-create --name ubuntu-20 --image ubuntu:20.04

The console hung so I tacked a -v, here is the result: https://gist.github.com/castrojo/f5d883398283aa2a78b95830af222462

I've got existing toolbox containers so I made sure there's no name collision, not sure how to proceed, this is on Fedora Silverblue 35.

**Comment by 89luca89** [comment]
Hi @castrojo can you check if the fix in the pull request #66 fixes this issue?

**Comment by castrojo** [comment]
I unfortunately was unable to get to that step, the container never created.

**Comment by 89luca89** [comment]
Oh didn't catch that 😅 
Is that the only log you got? Seems to be chopped after the find command

**Comment by 89luca89** [comment]
Mh I see that the console hung
Is it probably due to a gvfs mount?

I have fixed it here: https://github.com/89luca89/distrobox/commit/b83b35e9466591474c031d7e2bc8da761524f6ff

Should be included in the next release

**Comment by 89luca89** [comment]
@castrojo let me know if that was that, I'll close this when I release the fixed version it's that and if it works for you :+1:

**Comment by castrojo** [comment]
Yep, that was it, working now, thanks!

**Comment by 89luca89** [comment]
Cool stuff 😄 hope to close the latest fixes and release it asap 😅
