### ISSUE TITLE
[Error] The name org.freedesktop.Flatpak was not provided by any .service files (runit)

### ISSUE THREAD

**Issue by Animeshz** [89luca89/distrobox#672]
**Describe the bug**

When trying to use distrobox-host-exec, the command exits with error msg as follows:

```bash
$ distrobox enter debian-latest -- distrobox-host-exec fish
The name org.freedesktop.Flatpak was not provided by any .service files
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.4.0
 - Which version of distrobox? 1.4.2.1

**Additional context**

Running on void linux (glibc variant), that uses runit as its primary service manager.

**Comment by dannylin108** [comment]
> The execution on the host is done via dbux, using the flatpak helper service

you mean some additional packages / services (besides distrobox / podman)? which exactly?
