### ISSUE TITLE
[Error] Trouble starting a container I moved over from OpenSUSE MicroOS to NixOS

### ISSUE THREAD

**Issue by fearlessgeekmedia** [89luca89/distrobox#674]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
It can't start the entrypoint when I put in distrobox-enter devel.

I had saved the container to a tar.gz file and loaded it in podman under NixOS. The container itself is Arch.

**To Reproduce**
distrobox-enter devel

**Expected behavior**
The container should start

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

+ case "${container_manager}" in
+ command -v podman
+ container_manager=podman
+ command -v podman
+ '[' 1 -ne 0 ']'
+ container_manager='podman --log-level debug'
+ '[' 0 -ne 0 ']'
+ container_home=/home/fearlessgeek
+ container_path=/run/wrappers/bin:/home/fearlessgeek/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/fearlessgeek/.nix-profile/bin:/etc/profiles/per-user/fearlessgeek/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
+ '[' 0 -ne 0 ']'
+ container_status=unknown
++ podman --log-level debug inspect --type container devel --format 'container_status={{.State.Status}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}'
INFO[0000] /nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman filtering at log level debug 
DEBU[0000] Called inspect.PersistentPreRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug inspect --type container devel --format container_status={{.State.Status}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}) 
DEBU[0000] Found default OCI runtime /nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun path via PATH environment variable 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon from $PATH: "/nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon" 
DEBU[0000] Initializing boltdb state at /home/fearlessgeek/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/fearlessgeek/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/fearlessgeek/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/fearlessgeek/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] using runtime "crun" from $PATH: "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
DEBU[0000] using runtime "runc" from $PATH: "/nix/store/1dvhk6ys45kfdrdg6hj1q2l64g1qyyg9-runc-1.1.4/bin/runc" 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Using OCI runtime "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Looking up image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage 
DEBU[0000] Trying "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" ... 
DEBU[0000] parsed reference into "[overlay@/home/fearlessgeek/.local/share/containers/storage+/run/user/1000/containers]@4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" 
DEBU[0000] Found image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" as "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage 
DEBU[0000] Found image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" as "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage ([overlay@/home/fearlessgeek/.local/share/containers/storage+/run/user/1000/containers]@4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10) 
DEBU[0000] Called inspect.PersistentPostRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug inspect --type container devel --format container_status={{.State.Status}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}) 
+ eval 'container_status=exited;
	container_home="/home/fearlessgeek/devel";
	container_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
++ container_status=exited
++ container_home=/home/fearlessgeek/devel
++ container_path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ '[' exited = unknown ']'
+ '[' exited '!=' running ']'
+ printf 'Container %s is not running.\n' devel
Container devel is not running.
+ printf 'Starting container %s\n' devel
Starting container devel
+ printf 'run this command to follow along:\n\n'
run this command to follow along:

+ printf ' %s logs -f %s\n\n' 'podman --log-level debug' devel
 podman --log-level debug logs -f devel

++ date +%FT%T.%N%:z
+ log_timestamp=2023-03-26T13:16:53.814116390-04:00
+ podman --log-level debug start devel
INFO[0000] /nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman filtering at log level debug 
DEBU[0000] Called start.PersistentPreRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug start devel) 
DEBU[0000] Found default OCI runtime /nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun path via PATH environment variable 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon from $PATH: "/nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon" 
DEBU[0000] Initializing boltdb state at /home/fearlessgeek/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/fearlessgeek/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/fearlessgeek/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/fearlessgeek/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] using runtime "crun" from $PATH: "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
DEBU[0000] using runtime "runc" from $PATH: "/nix/store/1dvhk6ys45kfdrdg6hj1q2l64g1qyyg9-runc-1.1.4/bin/runc" 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Using OCI runtime "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported 
DEBU[0000] Check for idmapped mounts support            
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported 
DEBU[0000] Check for idmapped mounts support            
DEBU[0000] overlay: mount_data=lowerdir=/home/fearlessgeek/.local/share/containers/storage/overlay/l/PHWOSQUXS752MXN6MK5FWWYSHB:/home/fearlessgeek/.local/share/containers/storage/overlay/l/PHWOSQUXS752MXN6MK5FWWYSHB/../diff1:/home/fearlessgeek/.local/share/containers/storage/overlay/l/T235UBTRZYMZX6L2NFD6LNFY2G:/home/fearlessgeek/.local/share/containers/storage/overlay/l/Z6B4ZZ2MCHON2PTBR2EFT4ENVC:/home/fearlessgeek/.local/share/containers/storage/overlay/l/CYXDB7HNKAZVRYRG3ZCPCLXMTO:/home/fearlessgeek/.local/share/containers/storage/overlay/l/OQ3QNYAMLNIZRJQW3LZNYYGUV2,upperdir=/home/fearlessgeek/.local/share/containers/storage/overlay/3d70077b172b47d7525bc9ecb7c13f194f86afc8aea67f0cd74df2d0178bf31b/diff,workdir=/home/fearlessgeek/.local/share/containers/storage/overlay/3d70077b172b47d7525bc9ecb7c13f194f86afc8aea67f0cd74df2d0178bf31b/work,,userxattr 
DEBU[0000] Mounted container "9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e" at "/home/fearlessgeek/.local/share/containers/storage/overlay/3d70077b172b47d7525bc9ecb7c13f194f86afc8aea67f0cd74df2d0178bf31b/merged" 
DEBU[0000] Going to mount named volume 54fbbfd38dd081c548493d4374184c1eea784efab0c759f52beed758099ebb5d 
DEBU[0000] Copying up contents from container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e to volume 54fbbfd38dd081c548493d4374184c1eea784efab0c759f52beed758099ebb5d 
DEBU[0000] Going to mount named volume 66a56f921915adc5f2cc6e1182a4bf92037c9143e3b86f0814a20ed2f7e8e9c3 
DEBU[0000] Copying up contents from container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e to volume 66a56f921915adc5f2cc6e1182a4bf92037c9143e3b86f0814a20ed2f7e8e9c3 
DEBU[0000] Created root filesystem for container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e at /home/fearlessgeek/.local/share/containers/storage/overlay/3d70077b172b47d7525bc9ecb7c13f194f86afc8aea67f0cd74df2d0178bf31b/merged 
DEBU[0000] Not modifying container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e /etc/passwd 
DEBU[0000] Not modifying container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e /etc/group 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode subscription 
INFO[0000] User mount overriding libpod mount at "/etc/resolv.conf" 
INFO[0000] User mount overriding libpod mount at "/etc/hosts" 
DEBU[0000] Setting Cgroups for container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e to user.slice:libpod:9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e 
DEBU[0000] Set root propagation to "rslave"             
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d 
DEBU[0000] Workdir "/" resolved to host path "/home/fearlessgeek/.local/share/containers/storage/overlay/3d70077b172b47d7525bc9ecb7c13f194f86afc8aea67f0cd74df2d0178bf31b/merged" 
DEBU[0000] Created OCI spec for container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e at /home/fearlessgeek/.local/share/containers/storage/overlay-containers/9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e/userdata/config.json 
DEBU[0000] /nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon  args="[--api-version 1 -c 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e -u 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e -r /nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun -b /home/fearlessgeek/.local/share/containers/storage/overlay-containers/9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e/userdata -p /run/user/1000/containers/overlay-containers/9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e/userdata/pidfile -n devel --exit-dir /run/user/1000/libpod/tmp/exits --full-attach -s -l journald --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/overlay-containers/9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e/userdata/conmon.pid --exit-command /nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --exit-command-arg --root --exit-command-arg /home/fearlessgeek/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg cni --exit-command-arg --volumepath --exit-command-arg /home/fearlessgeek/.local/share/containers/storage/volumes --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: 2249                               
INFO[0000] Got Conmon PID as 2247                       
DEBU[0000] Created container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e in OCI runtime 
DEBU[0000] Starting container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e with command [/usr/bin/entrypoint /usr/bin/entrypoint -v --name fearlessgeek --user 1000 --group 100 --home /home/fearlessgeek/devel --init 0 -- ] 
DEBU[0000] Started container 9659e612723d70b1aea2010b04f552311349944c9eb60d0d6a3ebf1c5b21718e 
DEBU[0000] Notify sent successfully                     
DEBU[0000] Called start.PersistentPostRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug start devel) 
++ podman --log-level debug inspect --type container devel --format '{{.State.Status}}'
INFO[0000] /nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman filtering at log level debug 
DEBU[0000] Called inspect.PersistentPreRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug inspect --type container devel --format {{.State.Status}}) 
DEBU[0000] Found default OCI runtime /nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun path via PATH environment variable 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon from $PATH: "/nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon" 
DEBU[0000] Initializing boltdb state at /home/fearlessgeek/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/fearlessgeek/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/fearlessgeek/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/fearlessgeek/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] using runtime "crun" from $PATH: "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
DEBU[0000] using runtime "runc" from $PATH: "/nix/store/1dvhk6ys45kfdrdg6hj1q2l64g1qyyg9-runc-1.1.4/bin/runc" 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Using OCI runtime "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Looking up image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage 
DEBU[0000] Trying "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" ... 
DEBU[0000] parsed reference into "[overlay@/home/fearlessgeek/.local/share/containers/storage+/run/user/1000/containers]@4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" 
DEBU[0000] Found image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" as "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage 
DEBU[0000] Found image "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" as "4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10" in local containers storage ([overlay@/home/fearlessgeek/.local/share/containers/storage+/run/user/1000/containers]@4d643a96559289d928a8bb8c4c19ee6ec784e6efb90538e649976d86db88df10) 
DEBU[0000] Called inspect.PersistentPostRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug inspect --type container devel --format {{.State.Status}}) 
+ '[' stopped '!=' running ']'
+ printf '\033[31m Error: could not start entrypoint.\n\033[0m'
 Error: could not start entrypoint.
++ podman --log-level debug logs --since 2023-03-26T13:16:53.814116390-04:00 devel
INFO[0000] /nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman filtering at log level debug 
DEBU[0000] Called logs.PersistentPreRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug logs --since 2023-03-26T13:16:53.814116390-04:00 devel) 
DEBU[0000] Found default OCI runtime /nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun path via PATH environment variable 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon from $PATH: "/nix/store/ywnzs69zrc5fvpi4crx7dfxqhl7sj6sm-conmon-2.1.5/bin/conmon" 
DEBU[0000] Initializing boltdb state at /home/fearlessgeek/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/fearlessgeek/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/fearlessgeek/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/fearlessgeek/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] using runtime "crun" from $PATH: "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
DEBU[0000] using runtime "runc" from $PATH: "/nix/store/1dvhk6ys45kfdrdg6hj1q2l64g1qyyg9-runc-1.1.4/bin/runc" 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Using OCI runtime "/nix/store/vlzp16bx4nmcpvss73fbnxgxxk1gc7r9-crun-1.7/bin/crun" 
INFO[0000] Setting parallel job count to 13             
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Called logs.PersistentPostRunE(/nix/store/nla9faxls8higwflkkbf5bl9kpycknzb-podman-4.3.1/bin/podman --log-level debug logs --since 2023-03-26T13:16:53.814116390-04:00 devel) 
+ container_manager_log='Error: Invalid arguments, missing user gud
Error: An error occurred'
+ printf '%s\n' 'Error: Invalid arguments, missing user gud
Error: An error occurred'
Error: Invalid arguments, missing user gud
Error: An error occurred
+ exit 1
+ '[' 1 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
+ rm -f '/home/fearlessgeek/.cache/.*.fifo' '/home/fearlessgeek/.cache/.*.status'

An error occurred

podman logs

Error: unknown shorthand flag: 'f' in -f
See 'podman --help'
[fearlessgeek@nixos ~]$ podman logs -f devel
Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

Error: Invalid arguments, missing user gud
Error: An error occurred
Error: Invalid arguments, missing user gud
Error: An error occurred

**Desktop (please complete the following information):**
podman 4.3.1
distrobox 1.4.1 (this is what's in the NixOS repositories currently)

**Additional context**

**Comment by luc14n0** [comment]
Could you please edit your comment and enclose the output you posted in triple back-quotes (selecting the output and pressing **Ctrl+E** should work)? Otherwise the readability is lost.

**Comment by fearlessgeekmedia** [comment]
Well doesn't matter much to me now as I found NixOS wasn't going to work well for me anyway. I was fine with it until I had to deal with Pip with Python. They have a whole different way of doing things on NixOS than a regular Linux distribution.

I'm going to chalk the problem up to NixOS not being POSIX compliant.

However, I was having some issues loading that same image on EndeavourOS. I'll have to post that issue here when I get a moment.

**Comment by luc14n0** [comment]
Yeah, **NixOS** has (new) different ways of doing things.

For now, I have a slight suspicion that **distrobox** containers aren't as portable as you think, due to how they integrate with the host.

**Comment by fearlessgeekmedia** [comment]
Well I knew it integrated into the system. I just didn't know exactly how much. I switched from NixOS because I was having problems installing some Python packages that weren't in their repositories. 

NixOS is fun to play with and I like their concepts but I just can't use it as a daily driver right now.
