### ISSUE TITLE
[Error] permission denied trying to install a file to /usr/local/share/fonts inside ubuntu 22.04 container

### ISSUE THREAD

**Issue by weatherhead99** [89luca89/distrobox#680]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I am not fully sure this is a bug actually, but can't find any relevant documentation. I am using a rootless ubuntu distrobox container to install some of the Microsoft packages for linux for testing. One of these (specifically microsoft-identity-broker) tries to install a new ttf font into /usr/local/share/fonts, which with a little investigation I see is actually bind mounted from a btrfs snapshot on my host. 

I do not think there is a problem in distrobox here, but what I would like is a way to e.g. bind mount on top of that /usr/local/share/fonts so that I can get this package to install. 

**To Reproduce**
`distrobox create -i ubuntu:22.04 -n ubuntu 
 distrobox enter ubuntu
 # ... some repo adding commands and package key imports etc....
sudo apt update
sudo apt install microsoft-identity-broker 
`

error reported is:

Unpacking microsoft-identity-broker (1.4.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-5LD2Jo/097-microsoft-identity-broker_1.4.1_amd64.deb (--unpack):
 unable to create '/usr/local/share/fonts/segoeuil.ttf.dpkg-new' (while processing './usr/local/share/fonts/segoeuil.ttf'): Permission denied
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)

**Expected behavior**
I think the behaviour may be expected, but I cannot find in config or docs any way to modify what gets mounted from the host. This is probably just rather bad packaging from microsoft but I really would like to find a way to use distrobox to play with this package. If it requires building my own ubuntu image that's acceptable but I wasn't able to find any instructions how to do that.

**Desktop (please complete the following information):**
podman 4.3.1, distrobox 1.4.2.1, host: openSUSE Leap 15.4 
Kernel: 5.14.21-150400.24.41-default

**Comment by luc14n0** [comment]
Hi there,

Yes, the behavior you're seeing is not a bug, it's expected:

https://github.com/89luca89/distrobox/blob/d925c3f10315b72ec38a0405e57fe06c87edc754/distrobox-init#L997-L1000

As far as I can tell, what gets bound by default is not configurable (it'd be interesting:tm: if it would through a config file, though) . What you can do, apart from using a rootful container -- in this case the Microsoft stuff would end up in the host's `/usr/share/fonts` --, is to create a new container and make use of `--init-hooks`.

An example of a `distrobox create` command (tested here with a `~/test/` directory under my homedir):

``` sh
$ distrobox create --image ubuntu:22.04 --name testing --init-hooks "umount /usr/local/share/fonts && mount --rbind -o rw /run/host/home/${USER}/.local/fonts /usr/local/share/fonts"
```

First we unmount `/usr/local/share/fonts`, then we bind-mount it to whatever location we want (`~/.local/fonts` in this example) :+1:

**Comment by juhp** [comment]
What I have been doing in toolbox is just to symlink appropriate subdirs from /run/host/usr/share/fonts/ to /usr/local/share/fonts (using sudo).

**Comment by 89luca89** [comment]
Yea in the container, /usr/local/share/fonts are the mountpoint for host's icons, in order to keep them integrated

The right solution for this is what @luc14n0 suggests, use an init-hook to umount the integration you don't need
