### ISSUE TITLE
[Error] Invalid flag '--nvidia'

### ISSUE THREAD

**Issue by printedz** [89luca89/distrobox#690]
The **NVidia integration** section of the distrobox-create usage docs says I can use _distrobox create --nvidia --image ubuntu:latest --name ubuntu-nvidia_ to create a container with NVidia integration, however using said command doesn't work and results in "ERROR: Invalid flag '--nvidia'".

**Expected behavior**
I expected the container to be created.

**Logs**
![image](https://user-images.githubusercontent.com/108233540/230434799-5de142dd-30c9-4689-a491-5a5c706106df.png)
There are no podman logs since the container wasn't created.

**Desktop (please complete the following information):**
 - Are you using podman or docker? I'm using podman
 - Which version or podman or docker? 4.4.4
 - Which version of distrobox? 1.4.2.1

**Additional context**
I'm using the distrobox package from the OpenSUSE Tumbleweed repositories.

**Comment by misobarisic** [comment]
You are using version 1.4.2.1 which does not have nvidia integration. There haven't been any releases featuring it. You can install the latest commit or wait for a new release.
