### ISSUE TITLE
[Discussion] Fonts from host not available inside the container in Silverblue

### ISSUE THREAD

**Issue by quazar-omega** [89luca89/distrobox#692]
## Description
In this article: [Run Distrobox on Fedora Linux](https://fedoramagazine.org/run-distrobox-on-fedora-linux/) (under "Exporting from the container to the host") it is said that exported applications have "themes and fonts integration with the host.", however I saw that the fonts I installed on Fedora Silverblue don't get picked up by the container, I tried both in VSCodium and Krita.
Is this the case only on this distribution or is the statement in the article incorrect?

## Proposed solution
Maybe it could be useful to specify the behavior in the docs?

## What I did
To obviate I installed the fonts in the `~/.fonts` directory of the container, which is separate from my own home directory

## Additional context

<details>
<summary>
This is the list of fonts I got from within the container (a Fedora Workstation 37):
</summary>

```
$ fc-list : family | sort | uniq
C059
Cantarell
Cantarell,Cantarell Extra Bold
Cantarell,Cantarell Light
Cantarell,Cantarell Thin
D050000L
Droid Arabic Kufi
Droid Sans
Droid Sans Armenian
Droid Sans Devanagari
Droid Sans Ethiopic
Droid Sans Fallback
Droid Sans Georgian
Droid Sans Hebrew
Droid Sans Japanese
Droid Sans Tamil
Droid Sans Thai
Jomolhari
Khmer OS System
Liberation Mono
Liberation Sans
Liberation Serif
Lohit Assamese
Lohit Bengali
Lohit Devanagari
Lohit Gujarati
Lohit Kannada
Lohit Marathi
Lohit Odia
Lohit Tamil
Lohit Telugu
Meera New
Mingzat
Montserrat
Montserrat,Montserrat Black
Montserrat,Montserrat ExtraBold
Montserrat,Montserrat ExtraLight
Montserrat,Montserrat Light
Montserrat,Montserrat Medium
Montserrat,Montserrat SemiBold
Montserrat,Montserrat Thin
Nimbus Mono PS
Nimbus Roman
Nimbus Sans
Nimbus Sans Narrow
Noto Color Emoji
Noto Naskh Arabic
Noto Sans
Noto Sans Arabic
Noto Sans Armenian
Noto Sans CJK HK
Noto Sans CJK HK,Noto Sans CJK HK Black
Noto Sans CJK HK,Noto Sans CJK HK DemiLight
Noto Sans CJK HK,Noto Sans CJK HK Light
Noto Sans CJK HK,Noto Sans CJK HK Medium
Noto Sans CJK HK,Noto Sans CJK HK Thin
Noto Sans CJK JP
Noto Sans CJK JP,Noto Sans CJK JP Black
Noto Sans CJK JP,Noto Sans CJK JP DemiLight
Noto Sans CJK JP,Noto Sans CJK JP Light
Noto Sans CJK JP,Noto Sans CJK JP Medium
Noto Sans CJK JP,Noto Sans CJK JP Thin
Noto Sans CJK KR
Noto Sans CJK KR,Noto Sans CJK KR Black
Noto Sans CJK KR,Noto Sans CJK KR DemiLight
Noto Sans CJK KR,Noto Sans CJK KR Light
Noto Sans CJK KR,Noto Sans CJK KR Medium
Noto Sans CJK KR,Noto Sans CJK KR Thin
Noto Sans CJK SC
Noto Sans CJK SC,Noto Sans CJK SC Black
Noto Sans CJK SC,Noto Sans CJK SC DemiLight
Noto Sans CJK SC,Noto Sans CJK SC Light
Noto Sans CJK SC,Noto Sans CJK SC Medium
Noto Sans CJK SC,Noto Sans CJK SC Thin
Noto Sans CJK TC
Noto Sans CJK TC,Noto Sans CJK TC Black
Noto Sans CJK TC,Noto Sans CJK TC DemiLight
Noto Sans CJK TC,Noto Sans CJK TC Light
Noto Sans CJK TC,Noto Sans CJK TC Medium
Noto Sans CJK TC,Noto Sans CJK TC Thin
Noto Sans Canadian Aboriginal
Noto Sans Cherokee
Noto Sans Ethiopic
Noto Sans Georgian
Noto Sans Gurmukhi
Noto Sans Hebrew
Noto Sans Lao
Noto Sans Math
Noto Sans Mono
Noto Sans Mono CJK HK
Noto Sans Mono CJK JP
Noto Sans Mono CJK KR
Noto Sans Mono CJK SC
Noto Sans Mono CJK TC
Noto Sans Sinhala
Noto Sans Thaana
Noto Serif
Nuosu SIL
P052
Padauk
PakType Naskh Basic
STIX Two Math
STIX Two Text
STIX Two Text,STIX Two Text Medium
STIX Two Text,STIX Two Text SemiBold
Source Code Pro
Source Code Pro,Source Code Pro Black
Source Code Pro,Source Code Pro ExtraLight
Source Code Pro,Source Code Pro Light
Source Code Pro,Source Code Pro Medium
Source Code Pro,Source Code Pro Semibold
Standard Symbols PS
Symbola
URW Bookman
URW Gothic
Vazirmatn
Waree
Z003
```

</details>

**Comment by 1player** [comment]
+1 here. Consider bind-mounting the host's fonts.

Case in point: my host is Fedora Silverblue, my distrobox is Arch Linux, which has GNOME Tweaks installed into it. When I open the app, all the fonts are broken.

![image](https://github.com/89luca89/distrobox/assets/690120/36155a7c-cccc-4caf-822a-0db3f3cfe871)

After some tracking down, it seems that the issue is due to the GNOME's default font (Noto Sans) not being available on the container:

```
toolbox:~ % fc-match :variable=true file                               
:file=/usr/local/share/fonts/google-noto-vf/NotoSans-VF.ttf
toolbox:~ % ls -l /usr/local/share/fonts/google-noto-vf/NotoSans-VF.ttf
ls: cannot access '/usr/local/share/fonts/google-noto-vf/NotoSans-VF.ttf': No such file or directory
```

To be fair, there are Google Noto Sans fonts in that directory, but the naming scheme of Fedora 38 is different than Arch Linux, so that's causes issues.

See also the same issue that happened in the Flatpak world: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1563

I reckon all host font directories should be mounted and available on the toolbox. Which understandably might be a pain, because a user might install a font in the toolbox, and I'm unsure what is the correct approach here.

Another approach would be to keep the font cache file separate from the host. So both environments are effectively independent font-wise, and each have their own sets of fonts and fontconfig settings that do not affect each other.

**Comment by 89luca89** [comment]
Hi all, thanks for this report!

So by default distrobox links the host's fonts into /usr/local/share/fonts

Not sure how we can work around the fact that font are called differently between distros tho

I'll gladly gather more infos about this, as I personally haven't encountered it, but it can be a real problem

**Comment by emanuelserpa** [comment]
> So by default distrobox links the host's fonts into /usr/local/share/fonts

What about ~/.local/share/fonts? Is there a way to add it in the containers?

**Comment by quazar-omega** [comment]
Was waiting for someone else to chime in, but since there's nothing new for now, what information would you like to have @89luca89?

**Comment by 89luca89** [comment]
Not really much
Distrobox already does the host's font integration

The problem arises when the same font is called differently between the distros, so even if files are there, tey are not found

**Comment by juhp** [comment]
This could also be related to different versions of fontconfig or it's caches.

**Comment by 89luca89** [comment]
Maybe adding a ` fc-cache -Ers` after the font mounts can help?

**Comment by 89luca89** [comment]
Also I just did the test above (run a base archlinux container, install gnome-tweaks and launch it) and I don't see problems
And fc-match returns correctly a path in `/usr/local/share/fonts` which is the mountpoint of host's fonts

**Comment by quazar-omega** [comment]
Sounds promising
