### ISSUE TITLE
[Suggestion] Improvements to Upgrading process for desktop users

### ISSUE THREAD

**Issue by eylenburg** [89luca89/distrobox#703]
**Is your feature request related to a problem? Please describe.**
Currently you need to run "distrobox-upgrade" to update the packages in a container distro. Users may forget about it or they may be unaware or afraid of it.

**Describe the solution you'd like**
It would be great if Distrobox could periodically check for updates for the guest distros without applying them and would then spawn a notification or persistent tray icon to inform the user that updates can be installed. Clicking on it would then run the "distrobox upgrade -all" command or (even better) open a graphical window showing all the installed guest distros with checkboxes for each one and an "Update" button so that the user can for example decide to update all guests except for one.

The ideal solution from the user's perspective would probably be if it could somehow be integrated into KDE Discover/GNOME Software. So for example, if you have two Distrobox guests, they would show up as two updateable "packages" whenever there's updates available for the guest. However, I'm not sure if it is possible to create these dummy "packages" for the guests (through packagekit?).

**Describe alternatives you've considered**
The easiest solution would be to be able to schedule the "distrobox-upgrade" command regularly, with different possible schedules for different guests (e.g. if there is a specific guest you only want to update manually). This way at least the user won't have to remember it after the initial set-up.

**Additional context**
Consider this example: You install an immutable system such as openSUSE MicroOS Desktop on your grandmother's computer. She doesn't know much about computers so you decided an immutable, auto-updating system like MicroOS would be ideal. The base system with all packages from the repo, as well as the Flatpaks from Flathub, are all updated automatically or in the worst case there will be a notification for her that updates are available. However, she really wants to use a couple of applications that are not available as Flatpaks yet. So you install these apps as native packages in a Distrobox guest and then export them using "distrobox-export". The problem is that these are not part of the update process. She doesn't know about this and would be afraid of using the terminal anyway. So she ends up running outdated, potentially insecure packages in the Distrobox guest.

**Comment by KenJyn76** [comment]
distrobox create -i [your image] -n [your name] --init-hooks=[command to upgrade system]

I don't have an environment to test this, but it may work? It would likely need to be a command that does not need confirmation, like 'pacman -Syu --noconfirm'

**Comment by eylenburg** [comment]
I just gave this a try. I created a new distrobox guest with the command:
`distrobox create --image registry.opensuse.org/opensuse/tumbleweed:latest --init-hooks "zypper -n dup" --name tumbleweed`
Upon entering the last step says: 
`Executing init hooks... 
"you are about to do a distribution upgrade ..." 
[ OK ]`

So it seems to work fine although hard to say because the image is brand new of course. Need to wait a few days and see if it will install any updates.

As a suggestion for Distrobox, I think it could be a nice idea when creating a new distrobox to have an "autoupdate" flag. So for example `distrobox -i [image] -n [name] --autoupdate` and that will set up the correct init-hooks for a non-attended update for the chosen image. So an Arch guest would have `--init-hooks "pacman -Syu --noconfirm"` and a Tumbleweed guest would have `--init-hooks "zypper -n dup"`

**Comment by 89luca89** [comment]
The real solution to auto-updates are either cron or systemd-unit

A workaround is using init-hooks, but I won't add this as a default command for everyone (what if I'm offline? I can't start a container?)

Anyway, init-hooks don't need sudo as they run as root into the container
