### ISSUE TITLE
[Suggestion] Consider shipping a custom PS1 variable like toolbox

### ISSUE THREAD

**Issue by fjbaldon** [89luca89/distrobox#704]
**Is your feature request related to a problem? Please describe.**
No (?). Just a small quality of life improvement. Being able to notice if I'm in a container or not is a good addition i think.

**Describe the solution you'd like**
Maybe just copy toolbox's PS1 variable and change it to some color?

**Describe alternatives you've considered**
Create a new and distinct PS1 for distrobox

**Additional context**

**Comment by numbertumbers** [comment]
I don't see any reason why not to implement this into Distrobox. It's a rather useful quality of life change.

**Comment by 89luca89** [comment]
I like the idea :smile: 

Contributions are welcome!
