### ISSUE TITLE
opensuse image looks for dnf when running distrobox upgrade

### ISSUE THREAD

**Issue by uncomfyhalomacro** [89luca89/distrobox#706]
**Describe the bug**
Distrobox opensuse looks for dnf and dnf related directories for upgrading.

**To Reproduce**
Running `distrobox-upgrade -a` or `distrobox-upgrade <name of the image>`

**Expected behavior**
It should use `zypper`

**Logs**
No relevant output. Just this

```sh
> distrobox-upgrade tumbleweed
 Upgrading tumbleweed...
distrobox: Installing basic packages...
/usr/bin/dnf
Error: There are no enabled repositories in "/etc/dnf/repos.d", "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
Error: An error occurred
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.4.4
 - Which version of distrobox? 1.4.2.1

**Additional context**
Just because dnf works on opensuse does not mean it is shipped by default. 

"Maybe it's actually you have either a Fedora or RHEL install?"

```
tumbleweed% sudo zypper in fastfetch
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 10 recommended packages were automatically selected:
  ImageMagick chafa dconf libxfce4util-lang pciutils sqlite3 vulkan-tools xfconf xfconf-lang xrandr

The following 39 NEW packages are going to be installed:
  ImageMagick ImageMagick-config-7-SUSE chafa dconf fastfetch gdk-pixbuf-loader-libheif hwdata libIex-3_1-30 libIlmThread-3_1-30 libImath-3_1-29
  libMagickCore-7_Q16HDRI10 libMagickWand-7_Q16HDRI10 libOpenEXR-3_1-30 libSvtAv1Enc1 libaom3 libchafa0 libdav1d6 libdconf1 libfftw3-3 libheif1 libhwy1
  libjxl0_8 liblqr-1-0 libltdl7 libpci3 librav1e0 libraw23 libwebp7 libwebpdemux2 libwebpmux3 libxfce4util-lang libxfce4util7 libxfconf-0-3 pciutils
  sqlite3 vulkan-tools xfconf xfconf-lang xrandr

39 new packages to install.
Overall download size: 16.1 MiB. Already cached: 0 B. After the operation, additional 55.5 MiB will be used.
Continue? [y/n/v/...? shows all options] (y):
Retrieving: ImageMagick-config-7-SUSE-7.1.1.6-1.1.x86_64 (openSUSE-Tumbleweed-Oss)
```

**Comment by 89luca89** [comment]
Hi @uncomfyhalomacro which OpenSUSE image are you using?
I'm using tumbleweed:latest myself and don't have this

Generally speaking, distrobox tries to detect which package manager is present, by simply using `command -v`
If `dnf` is installed in the system, then that is detected and used

**Comment by uncomfyhalomacro** [comment]
> 

Hmm, is this the incorrect image? `registry.opensuse.org/opensuse/distrobox:latest`

**Comment by uncomfyhalomacro** [comment]
I just assume that whatever it pulls, it is just okay. And yes, I don't have dnf installed in my system so it's weird.

**Comment by 89luca89** [comment]
To be honest I cannot reproduce this, I use MicroOS daily and use that same image and I don't have this problem
Can you post the output of `podman logs` of the erroring container?

**Comment by luc14n0** [comment]
Maybe `command` [detected](https://github.com/89luca89/distrobox/blob/587b46531ea4fcf515f8f1976fb198a73a02e2a0/distrobox-init#L408-L413C5) `dnf` somewhere in the `PATH`?

``` sh
	elif command -v dnf; then
		# If we need to upgrade, do it and exit, no further action required.
		if [ "${upgrade}" -ne 0 ]; then
			dnf upgrade -y
			exit
		fi
```

A `command -v dnf` inside the container might prove useful.

**Comment by uncomfyhalomacro** [comment]
![image](https://user-images.githubusercontent.com/66054069/237018233-8555c9fc-e822-41ca-a623-a5a242c47c33.png)

Idk how or why but after I removed and added the image again, and doing an upgrade, it fixed itself. Maybe I did have dnf before. I am closing this as completed.

However, I am going to open a new issue that detecting which package manager is available through `command` can be faulty. For example, I have `osc` installed in my system before and tried out distrobox, `osc` also pulls `dnf` as part of the recommends (?). And because of that this may have mess up my distrobox install causing it to look for dnf even after I removed it.

Wouldn't it be better to use `/etc/os-release` to check which distro someone has at first and use the default package manager then use `command` as a fallback later?

**Comment by luc14n0** [comment]
Well, removing and re-adding the container image wasn't helpful for people willing to understand why **DNF** was being called. The theory that `osc` recommends `dnf` is not valid. In my **Tumbleweed** system, where I have OSC installed:

``` sh
$ rpm -q --recommends osc | grep dnf

$ zypper --no-refresh search --match-exact --recommends dnf
Loading repository data...
Reading installed packages...

S  Name                  Summary                               Type
                                                                         
   kiwi-systemdeps-core  KIWI - Core host system dependencies  package
   mkosi                 Build Legacy-Free OS Images           package

```

The first command is looking for the symbols the OSC package recommends, more specifically `dnf`; and the second is basically asking "What packages do recommend the exact string `dnf`?

So the questions "Where did the `command -v dnf` check, used by `distrobox-init`, find `dnf`? Was it inside the container, or somewhere else inside the host system?" still remain.

> And because of that this may have mess up my distrobox install causing it to look for dnf even after I removed it.

Based on a recent experience where I switched my default shell in the host system, I'm afraid you _could be_ correct here (I hope someone could back us up). I switched from Zsh to Fish to do some experiments and `distrobox-init` is still detecting Zsh as `SHELL` in previous created distroboxes. I'm going to see if I do some debugging on this matter on another time.

> Wouldn't it be better to use /etc/os-release to check which distro someone has at first and use the default package manager then use command as a fallback later?

I agree that using `command` to find out what package manager the container should use for the `distrobox upgrade` call can be fragile if people install another package manager besides the default for the distro in use (be it in the container or in the host system) and `distrobox init` find the former first.

And using `/etc/os-release` should be safe. It's what **GNOME** uses to look up basic distro info through **GLib** APIs.

**Comment by uncomfyhalomacro** [comment]
It could be better if we have an option when creating the image or upgrading to choose a package manager to use in case there are hiccups. I am open to contribute but let me know if that's a good idea

**Comment by luc14n0** [comment]
I hear you. And I feel like `distrobox upgrade` is more of a convenience than anything else, so I'd think no one is aiming for speed there.

As a fellow user here, honestly I don't think it's a good idea to implement an option flag to pass which package manager should be used by `distrobox upgrade` or something else. The user shouldn't have to worry about such things at all.

Let's wait for Luca and other folks to express their opinions. For me, the improvement to be aimed at would be checking `/etc/os-release` and using the default package manager for the distro accordingly.

**Comment by uncomfyhalomacro** [comment]
> I hear you. And I feel like `distrobox upgrade` is more of a convenience than anything else, so I'd think no one is aiming for speed there.
> 
> As a fellow user here, honestly I don't think it's a good idea to implement an option flag to pass which package manager should be used by `distrobox upgrade` or something else. The user shouldn't have to worry about such things at all.
> 
> Let's wait for Luca and other folks to express their opinions. For me, the improvement to be aimed at would be checking `/etc/os-release` and using the default package manager for the distro accordingly.

Probably better to continue this then at #744
