### ISSUE TITLE
[Error] Cannot run xwayland apps

### ISSUE THREAD

**Issue by sid314** [89luca89/distrobox#712]
**Describe the bug**
Running x wayland apps (eg. Discord) fails

**To Reproduce**
Set up an Arch container in Fedora
Install Hyprland on Arch and add it to login manager according to this guide:
https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md
Try launching Xwayland apps on host

**Expected behavior**
Apps should launch

**Logs**
```
Discord 0.0.26
[22797:0421/154533.635198:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[22797:0421/154533.635291:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
zsh: IOT instruction (core dumped)  Discord
```
**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - Podman
 - Which version or podman or docker?
 - 4.4.4
 - Which version of distrobox?
 - 1.4.2.1

**Comment by 89luca89** [comment]
Hi @sid314 

As explained in the post, running graphical sessions is experimental and not an officially supported usage

In your case I'd suggest to look into setting up xwayland on the host, but anyway I'm going to close this bug report as this is not a use case that I intend to support in the project

**Comment by ChristopherRabotin** [comment]
Sorry to bump up this unplanned feature, but I was wondering whether you had tips on what I should investigate for a related issue: I had "Anytype" (https://download.anytype.io/) installed in a Fedora 39 distrobox work. It was working fine for weeks until yesterday when the same error as above started showing up. Trying to rebuild the fedora container or upgrading to Fedora 40 does not help either. The original Fedora container was built with `distrobox create -i fedora:39 anytype-box` and the version 40 using `distrobox create -i fedora:40 --init --additional-packages "systemd"  fedora-anytype`.

```
╭─chris at fedora-anytype in ~/Workspace/ 24-02-28 - 1:49:29
╰─○ anytype                                               
Authorization required, but no authorization protocol specified

[31642:0228/155722.817848:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[31642:0228/155722.817891:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
[1]    31642 segmentation fault (core dumped)  anytype
```

I'm running Opensuse Aeon, so I think that the only change is that I upgraded distrobox. 

What could have made it possible for that program to work well before and now show the error from above? I'm just looking for tips on how I can investigate this and hopefully fix it for my use case, not asking to make this a planned feature.
