### ISSUE TITLE
[Error] Can't launch SteamVR under distrobox with Nvidia Open kernel modules

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#713]
**Describe the bug**
Trying to use SteamVR within distrobox with either nvidia-utils from inside container, or with `--nvidia` flag passed to distrobox results in 307 compositor crash.

**To Reproduce**
I actually in the process of creating automatic installer for ALVR using distrobox so the best way to reproduce the issue is using this:
https://github.com/Meister1593/ALVR-Distrobox-Linux-Guidance
I collected bunch of feedback and found out that one user with Nvidia, on Plasma on Wayland/X11 has issues launching SteamVR (after opening alvr, which launches most of the steamvr runtime with itself) that way

**Expected behavior**
SteamVR shouldn't crash with 307 and work normally

**Logs**
SteamVR crashes with such backtrace, which might be most useful in this case:
```
Thread 2 (Thread 0x7f9ea840e6c0 (LWP 234310)):
warning: Section `.reg-xstate/234310' in core file too small.
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x27ab820) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x27ab820, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f9eab6267cf in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x27ab820, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at futex-internal.c:139
#3  0x00007f9eab63189f in do_futex_wait (sem=sem@entry=0x27ab820, abstime=0x0, clockid=0) at /usr/src/debug/glibc/glibc/nptl/sem_waitcommon.c:111
#4  0x00007f9eab631930 in __new_sem_wait_slow64 (sem=0x27ab820, abstime=0x0, clockid=0) at /usr/src/debug/glibc/glibc/nptl/sem_waitcommon.c:183
#5  0x00007f9eac0e9f28 in ?? () from /home/dj/Documents/Code/ALVR-Distrobox-Linux-Guidance/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#6  0x00007f9eac0ea055 in ?? () from /home/dj/Documents/Code/ALVR-Distrobox-Linux-Guidance/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#7  0x00007f9eac06ec18 in ?? () from /home/dj/Documents/Code/ALVR-Distrobox-Linux-Guidance/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#8  0x00007f9eac06e67b in ?? () from /home/dj/Documents/Code/ALVR-Distrobox-Linux-Guidance/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#9  0x00007f9eac0e9c59 in ?? () from /home/dj/Documents/Code/ALVR-Distrobox-Linux-Guidance/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#10 0x00007f9eab629bb5 in start_thread (arg=<optimized out>) at pthread_create.c:444
#11 0x00007f9eab6abd90 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f9eab488780 (LWP 234304)):
#0  0x0000000000000000 in ?? ()
#1  0x00007f9ea63002aa in ?? () from /usr/lib/libnvidia-glcore.so.530.41.03
#2  0x00007f9ea62f9c49 in ?? () from /usr/lib/libnvidia-glcore.so.530.41.03
#3  0x000000000045fd5f in vr::CHmdWindowSDL::FindDirectDisplayX(unsigned int, unsigned int) ()
#4  0x0000000000461312 in vr::CHmdWindowSDL::CreateDirectModeSurface(unsigned int, unsigned int, float, VkSurfaceKHR_T**, VkDisplayKHR_T**) ()
#5  0x0000000000463a6a in vr::CHmdWindowSDL::CHmdWindowSDL(vr::CHmdDistort*, int, int, unsigned int, unsigned int, float) ()
#6  0x000000000042aa60 in vr::CHmdDistort::Initialize(TVRSharedState<VRCompositorState_t, false>*, vr::IVRIPCResourceManagerClient*, bool) ()
#7  0x00000000004ba970 in CVRCompositor::Init() ()
#8  0x00000000004bc70e in RealMain(unsigned int, ParsedArguments_t&) ()
#9  0x0000000000424ac2 in main ()
```
it mentions a lot about windowing , but xwayland, xorg, nvidia-utils, everything supposed to be already there and it works even with other people with similar gpu, but not on open drivers.

**Desktop (please complete the following information):**
 - Podman installed through distrobox script
 - Distrobox installed through script, from repository
 - KDE Plasma Wayland/Xorg
 - RTX 3080ti, NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  530.41.03  Release Build  (archlinux-builder@)

**Comment by 89luca89** [comment]
Hi @Meister1593 
Sadly I can't help with this, I don't have nvidia hardware whatsoever 

If anyone steps up for the debugging, all is welcome

**Comment by Meister1593** [comment]
Sadly same, can't help much without nvidia gpu, but i did discover that it's possibly linked with 530 driver

**Comment by 89luca89** [comment]
I'll keep this open for a bit longer, if no one reports anything (or helps debugging) I'll close this

**Comment by Meister1593** [comment]
Yeah i'm not sure if that was a quirk, or possibly 530 driver issue, so i would close it if no one will tell anything in a while. So far couple of nvidia users managed to use it fine.
