### ISSUE TITLE
Distrobox Create --nvidia flag not valid flag

### ISSUE THREAD

**Issue by logisj91** [89luca89/distrobox#714]
Distrobox version 1.4.2.1 on NixOS does not recognize the --nvidia flag for container creation.

Command tried;
`distrobox create -n archnvidia -i archlinux:latest --nvidia`

Received: 
`ERROR: Invalid flag '--nvidia'`

Expected result: 
According to the documentation, this is the correct command to create a distrobox container that hooks into the host nvidia driver.

System info;
OS: NixOS (using unstable channel) 
GPU: Nvidia RTX 3070ti

**Comment by A-Lovett** [comment]
That flag doesn't exist in the version with the 1.4.2.1 tag. You have to pull the latest version from git. I agree that it's confusing, since the documentation on the website doesn't match the latest release.

**Comment by misobarisic** [comment]
[#690](#690)

**Comment by logisj91** [comment]
Ah, well that does explain the problem then, I'll just wait for the next release then :)

**Comment by MiMillieuh** [comment]
It might be a good idea to update the project now... if the flag is ready it's been since five month that the current release is the latest one... 

It's in the documentation but this issue will likely be open again and again by people that aren't looking at closed issues.

**Comment by 89luca89** [comment]
> It might be a good idea to update the project now

I'll do it when I deem it to be ready

**Comment by Danie10** [comment]
In fairness, then, the documentation should match the current release version. I spent the last hour or so also trying to figure out why the flag for --nividia was failing. I'm following the given examples.

**Comment by misobarisic** [comment]
> In fairness, then, the documentation should match the current release version. I spent the last hour or so also trying to figure out why the flag for --nividia was failing. I'm following the given examples.

If you've spent the last hour debugging this then you are not on the _release_ latest version.
