### ISSUE TITLE
[Error] Locally installed distrobox won't use locally installed podman from Desktop

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#716]
**Describe the bug**
So locally installed distrobox and podman works great and even desktop shortcuts will be exported correctly with needed distrobox path, but what about locally installed podman? It seems like it will try to use whatever podman is in path and fail upon trying to open it from desktop

**To Reproduce**
1. Install Podman locally, not appending paths globally, only during the session. If you have podman installed globally, remove it & relog (i assume theres no other way to fully remove it for the test)
2. Install Distrobox locally, not appending paths globally
3. Create any container, install any program that has icon with it, try to export it
4. It successfully exports it into desktop with distrobox path
5. Try to open it

**Expected behavior**
It should use podman from the local podman installation folder, which is basically what distrobox is found during it's initial installation in it's script, and launch it from desktop.

**Additional context**
This is done in context of [this](https://github.com/Meister1593/ALVR-Distrobox-Linux-Guidance) repository, where i want to make ALVR run pretty much anywhere, and even though you can utilize system-wide installed podman, i noticed that sometimes it differs in how it was packaged & works and it might not work the same, so installing locally ensures same behavior for everyone.

**Comment by 89luca89** [comment]
Hi @Meister1593 

so to be clear, distrobox works normally, but then when you export an app it does not find the podman installed in $HOME?

Did you check Step 3 of the installation guide? https://github.com/89luca89/distrobox/blob/main/docs/posts/install_rootless.md

Where you should put the podman's PATH to ~/.distroboxrc?

**Comment by Meister1593** [comment]
> Hi @Meister1593
> 
> so to be clear, distrobox works normally, but then when you export an app it does not find the podman installed in $HOME?
> 
> Did you check Step 3 of the installation guide? https://github.com/89luca89/distrobox/blob/main/docs/posts/install_rootless.md
> 
> Where you should put the podman's PATH to ~/.distroboxrc?

Hello.
I didn't notice the distroboxrc path at first, but i don't see how it would help if we have two distroboxes - from system (or local bin) and from the installation folder.
During my development of the guide i decided to switch to locally installed podman completely to avoid issues with specific system podman installations, and for the time being i launch steam before launching alvr manually (with appended paths for podman and distrobox)

**Comment by Meister1593** [comment]
> Ah so you mean having 2 distrobox instances (like one in /usr/bin the other in /opt) and have two different configs for them? I don't think this is a supported thing sadly

yeah [pr](https://github.com/89luca89/distrobox/pull/718) made recently was about supporting that type of configuration (i found that eventually) :smile:
