### ISSUE TITLE
[Error] unable to start container: error stat'ing file irqbalance sock file

### ISSUE THREAD

**Issue by tleepa** [89luca89/distrobox#72]
I have created two containers using `distrobox-create`: Fedora 35 and Ubuntu 20.04.
I was able to enter and configure them without issues.

However, after system reboot, trying to enter any of them results in error message:
```bash
❯ distrobox-enter -n ubuntu-toolbox-20
Error: unable to start container "1302abf5585c1ab2ce43c26347fca10bd41eed09d7fb378390defcb6d6be57be": error stat'ing file `/run/irqbalance/irqbalance1451.sock`: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred
```

After reboot, irqbalance sock file was recreated by system:
```bash
❯ ll /run/irqbalance/                   
srwxr-xr-x@ 0 root root 30 Dec 14:37  irqbalance1454.sock
```
and container expects it at the path it was during create:
```bash
❯ podman inspect ubuntu-toolbox-20 | grep -i irqbalance
                "Source": "/run/irqbalance/irqbalance1451.sock",
                "Destination": "/run/irqbalance/irqbalance1451.sock",
                "/run/irqbalance/irqbalance1451.sock:/run/irqbalance/irqbalance1451.sock",
                "/run/irqbalance/irqbalance1451.sock:/run/irqbalance/irqbalance1451.sock:rw,rprivate,nosuid,nodev,rbind",
```

Is there a way to overcome this?

Using `podman version 3.4.4` on `Fedora Linux 35` host,

**Comment by 89luca89** [comment]
Hi @tleepa thanks for reporting!

Yes at creation time I find sockets and Mount them
If they miss after that there is a failure

Because of this I'm thinking about moving the socket finding part from `distrobox-create` to `distrobox-init` as we already have the whole host's filesystem available at /run/host inside the container

I'm opening an issue to document this, that will solve this problem 

Thanks for reporting!

**Comment by 89luca89** [comment]
I've pushed a fix for this in branch `feature/move_socket_mount`
Sadly this is not retro-active, so you either have to re-create the container or you can `clone` it, so that it keeps your set up containers and recreate them with the new method

**Comment by tleepa** [comment]
Apologies for late response and big thanks you for the prompt fix!
