### ISSUE TITLE
[Error] Cannot start a container with --root argument

### ISSUE THREAD

**Issue by Ridhubharan** [89luca89/distrobox#722]
**Describe the bug**
I installed a Kali linux container using `distrobox-create --name KaliLinux --image kali-rolling:latest`. I needed root privilege to run wireshark, so i used `distrobox enter --root KaliLinux`. But I did not have any problem running it without --root argument

**Expected behavior**
start container with root privilege

**Logs**
no logs as it failed to start

**Desktop (please complete the following information):**
podman 4.5.0
distrobox 1.4.2.1

**Comment by 89luca89** [comment]
Hi @Ridhubharan 

this is not a bug, this is how distrobox (and podman) work

To have rootfull container, you need to create it separately `distrobox create  --root ...`, then enter it with `distrobox enter --root`

You cannot use a normal container as rootful or viceversa
