### ISSUE TITLE
[Suggestion] Show an example of distrobox-export with a Flatpak application

### ISSUE THREAD

**Issue by har-nick** [89luca89/distrobox#723]
The [Useful Tips](https://distrobox.privatedns.org/useful_tips.html#use-distrobox-to-install-different-flatpaks-from-the-host) section mentions using `distrobox-export` to export Flatpak applications. Is it possible to show an example of this?

I'm just struggling to understand what to point to to export.

**Comment by 89luca89** [comment]
Hi @har-nick 
running flatpaks (or snaps) inside distrobox is not a thing really supported, that section in the docs is a leftover before I took this decision, and now is removed
