### ISSUE TITLE
[Discussion] Is there an official forum to post unimportant questions for DistroBox?

### ISSUE THREAD

**Issue by birds-swim** [89luca89/distrobox#724]
I don't know where to post this, but I'd like to ask the project members a question.

I have seen Jorge's video with Silverblue.  And I have read your project's README.

This technical project is a lot to take in, so please help me comprehend the extent of possibilities afforded to me by DistroBox.

Here's my question:

Can I replace my entire Desktop Environment (like KDE) with a DistroBox container?  Can I, on Debian Stable, install KDE Debian Unstable via DistroBox?  Is that what's available to me?  Your README states that DistroBox can replace your "userspace", but is that for the CLI only?  Or can full DE replacement happen as well?

Sorry if this is the wrong spot to post this!

**Comment by misobarisic** [comment]
Take a look at [this](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md)

**Comment by 89luca89** [comment]
To ask questions, there are a matrix and a telegram channel, right under the title of the readme.

Anyway, I insist in reading carefully the docs page, this is **an unsupported experimental thing** so I won't accept bug reports for running complete graphical sessions inside distrobox
