### ISSUE TITLE
[Discussion] Cooperation with downstream and related projects?

### ISSUE THREAD

**Issue by momobobe** [89luca89/distrobox#726]
Is your feature request related to a problem? Please describe.
[Apx](https://github.com/Vanilla-OS/apx) is a package manager heavily relying on Distrobox, and I feel goals of both projects are aligned, so maybe it helps to cooperate at some level to avoid duplicated work.

Describe the solution you'd like
I'm not sure if their project is known here, and if not, maybe it's worthwhile to contact them for a joint communication, for example, about how to bring up WayDroid support in a unified manner. 

Describe alternatives you've considered
[blendOS](https://blendos.co/) also does a similar job like Apx, and actually they relied on Distrobox before, but not now.

Additional context
blendOS's dev mentions several issues with Distrobox are solved with their own implementattion in https://blendos.co/blend-os-v2/ and I wonder if these make sense

> Applications and binaries installed in containers now automatically and instantaneously appear on the base system, as expected from a blend of distributions.

> Since you’re now probably wondering about potential conflicts between distributions and apps from them, we’re happy to inform you that we have developed a new priority-based system, that allows you to control which container’s binaries and apps should be given preference over those of others. Any system packages override this behavior, to avoid any system-container conflicts.

**Comment by 89luca89** [comment]
Waydroid is using LXC, distrobox does not (yet) support it, so nothing can be done on that side

And if collaboration is indeed useful, it's downstream that should contact upstram, not the other way around :roll_eyes:

**Comment by mirkobrombin** [comment]
FYI Luca is one of Apx authors. 

> blendOS's dev mentions several issues with Distrobox are solved with their own implementattion in https://blendos.co/blend-os-v2/ and I wonder if these make sense

usually the solution here is collaborating with upstream to investigate those problems, instead of reinventing the wheel.

**Comment by 89luca89** [comment]
Just to add:

```


    Applications and binaries installed in containers now automatically and instantaneously appear on the base system, as expected from a blend of distributions.

    Since you’re now probably wondering about potential conflicts between distributions and apps from them, we’re happy to inform you that we have developed a new priority-based system, that allows you to control which container’s binaries and apps should be given preference over those of others. Any system packages override this behavior, to avoid any system-container conflicts.
```

Distrobox itself *is not a package manager*, APX and Blend are, if they want to use distrobox underneath it's their choice, not mine
If there are workable problems with distrobox, they can open an issue, or try to contribute
That said, auto-exporting is not in the scope of distrobox in any way
