### ISSUE TITLE
[Error] Piping input to a `distrobox-host-exec` command hangs forever

### ISSUE THREAD

**Issue by varunbpatil** [89luca89/distrobox#730]
**Describe the bug**

Piping input to a `distrobox-host-exec` command doesn't work.

**To Reproduce**
1. Create a symlink to host podman within the distrobox container.
```
sudo ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman
```
2. Pipe password from stdin to the `podman login` command.
```
aws ecr get-login-password --region <region> | podman login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
```
3. The output of `aws ecr get-login-password` is never sent to `podman login`. The command hangs forever.

**Expected behavior**

The output of `aws ecr get-login-password` is sent to `podman login` and the command succeeds.

As a workaround, the following works:
```
aws ecr get-login-password --region <region> | host-spawn -no-pty podman login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
```
The `-no-pty` is what is required.

**Logs**
N/A

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.5.0
 - Which version of distrobox? 1.4.2.1

**Additional context**
`host-spawn` with the `-no-pty` option works for this case.

**Comment by 89luca89** [comment]
Hi @varunbpatil thanks for the report!
Pushed a fix for this!
