### ISSUE TITLE
[Error] distrobox-assemble not found

### ISSUE THREAD

**Issue by kavishgr** [89luca89/distrobox#731]
Both `distrobox assemble` and `distrobox-assemble` are not being recognized:

```sh
[core@coreos distroboxes-assemble]$ distrobox-assemble create -f fedora-toolbox.ini
bash: distrobox-assemble: command not found

[core@coreos distroboxes-assemble]$ distrobox assemble create -f fedora-toolbox.ini
Error: invalid command
distrobox version: 1.4.2.1

Choose one of the available commands:
	create
	enter
	list
	rm
	stop
	upgrade
	ephemeral
	generate-entry
	version
```

**Comment by misobarisic** [comment]
They are not part of any release yet. Install latest git version to use them.

**Comment by kavishgr** [comment]
Thanks. I apologize for any confusion. I was under the impression that the command was available since I couldn't find any mention in the README.md that it hasn't been released in the stable version.
