### ISSUE TITLE
[Error] Unable to completly unmount /nix in the container

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#732]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
/nix is unmountable

**To Reproduce**
Install nix on silverblue with this [script](https://github.com/dnkmmr69420/nix-installer-scripts/blob/main/installer-scripts/silverblue-nix-installer.sh) there is a bind mount involved on the host.

Follow [this](https://github.com/dnkmmr69420/nix-installer-scripts/tree/main/nix-distrobox)

**Expected behavior**
It shouldn't even be mounted in the distrobox

**Logs**
No errors. Is the /nix mount intended?

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.5.0
 - Which version of distrobox? 1.4.2.1

**Comment by dnkmmr69420** [comment]
I think this is actually intended, have an option to disable the /nix mount.

**Comment by dnkmmr69420** [comment]
I found it in the source code https://github.com/89luca89/distrobox/blob/5c780e2773149ef9ea0b2e314853dfb0fc631a62/distrobox-create#L576

**Comment by 89luca89** [comment]
Yes this is mounted inside the container, it is used for integration with NixOS hosts

You should be able to umount them also using an `init-hook`, in order to make it unmount at each start

**Comment by dnkmmr69420** [comment]
That did not work. It says it is read only by the installer.

**Comment by 89luca89** [comment]
This is not a problem anymore, /nix and stuff is not mounted by default now
