### ISSUE TITLE
[Error] Error spawning containers using systemd-nspawn in Distrobox.

### ISSUE THREAD

**Issue by justan00b91** [89luca89/distrobox#736]
**Describe the bug**

I was using an application which uses `systemd-nspawn` to chroot into development environment. This functionality is not available in the containers created by Distrobox.

I'm no expert in this matter but it seams like it has something to do with the way systemd is used.
```bash
dumbermore@ubuntu:~$  ps 1
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:03 /usr/lib/systemd/systemd --switched-root --system --deserialize=39
``` 

**To Reproduce**

The following error occurs while using `systemd-nspawn`
```bash
dumbermore@ubuntu:~$ sudo systemd-nspawn --notify-ready=yes --register=yes --bind-ro="/etc/resolv.conf" --machine="cubic" --directory="/home/dumbermore/tmp/custom-root"
Spawning container cubic on /home/dumbermore/tmp/custom-root.
Press ^] three times within 1s to kill container.
Failed to open system bus: No such file or directory
Attempted to remove disk file system under "/run/systemd/nspawn/propagate/cubic", and we can't allow that.
```
Which after enabling dbus `sudo service dbus start` turns to
```bash
dumbermore@ubuntu:~$ sudo systemd-nspawn --notify-ready=yes --register=yes --bind-ro="/etc/resolv.conf" --machine="cubic" --directory="/home/dumbermore/tmp/custom-root"
Spawning container cubic on /home/dumbermore/tmp/custom-root.
Press ^] three times within 1s to kill container.
Failed to register machine: Launch helper exited with unknown return code 1
Attempted to remove disk file system under "/run/systemd/nspawn/propagate/cubic", and we can't allow that.
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? 
   - Docker
 - Which version or podman or docker?
   - 20.10.23-ce, build 6051f1429
 - Which version of distrobox?
   - 1.4.2.1
 - Which image is used?
   - Ubuntu 22.04.2 LTS

**Additional context**

Detailed steps and original conversations related to this topic are discussed [here](https://github.com/PJ-Singh-001/Cubic/issues/204)

**Comment by 89luca89** [comment]
Hi @justan00b91 

Distrobox is not really thought to work with nested containerization (like also Flatpaks and Snaps)
So my suggestion is to run the `systemd-nspawn` command on the host

You can do this by creating a little wrapper like:

```sh
#!/bin/sh

distrobox-host-exec sudo /usr/bin/systemd-nspawn $@
```

And place it into `/usr/local/bin/systemd-nspawn`

This will use host's systemd-nspawn to run
