### ISSUE TITLE
[Error] Cannot run host-exec from a DE started through a session file

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#739]
**Describe the bug**
Running `distrobox-host-exec` fails to start any process on the host. Running the command by itself launches a new shell session in the container.

**To Reproduce**
Create a session file containing this:
```
[Desktop Entry]
Name=GNOME (arch distrobox)
Comment=This session logs you into GNOME
Exec=/usr/local/bin/distrobox-enter -n arch-gnome -- dbus-run-session gnome-session
Type=Application
DesktopNames=GNOME
```

Launch it through SDDM. Run `distrobox-host-exec`.

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 podman
 - Which version or podman or docker?
 4.5.0
 - Which version of distrobox?
 latest git

**Comment by 89luca89** [comment]
Hi @misobarisic 

so this is probably dues to how `distrobox-host-exec` works, via `host-spawn`, it uses the flatpak-session-helper/dbus to spawn a shell in the host

I think this is more of a thing to solve in the main tool than distrobox

Also, the "Desktop-in-Distrobox" is a configuration that I explicitly not support (too much headache) so I won't do much work on supporting it
