### ISSUE TITLE
[Improvement] Void linux support

### ISSUE THREAD

**Issue by max12mx13** [89luca89/distrobox#74]
Hello, I have just installed distrobox on void linux and have successfully created two 'boxes' (Fedora and debian) 
Through this testing I imagine void linux could be added to the compatible distro's, however if there are more tests you would like me to exectute just ask

Max

**Comment by 89luca89** [comment]
Great! Glad it works :smile: 

Are you able to test the `distrobox-export` part? 
I know that Void does not use systemd, so the `distrobox-export --service` will definitively not work, but let's try `--app` and `--bin`, and I'll add a notice to the table for the `--service` part

**Comment by max12mx13** [comment]
Ok, the `--bin` works with htop and nano, if there are any troubling binaries that you would like me to try out just ask.

However, unfortunately the `--app` option has not worked for me; it successfully placed the icon and option in my applications box but when launched it did not work. I attempted it with atom ( with foreground set ) and also opera. The commands I used are as follows:
`distrobox-export --app opera 
`
`distrobox-export --app atom --extra-flags "--foreground`
This is with an arch linux box

I also tried to export gedit from a debian box which also did not work with the same problem.
Please lmk if I did anything wrong with the export command

**Comment by 89luca89** [comment]
OK can you check if you manually launch the command that you see in the desktop file?

Should be something like

`distrobox-enter -H -n ...`

So we can see what is happening

Thanks!

**Comment by max12mx13** [comment]
I found the command from the .desktop file for opera, it is
`/usr/local/bin/distrobox-enter -H -n arch -- "  opera  %U"`

The error I got was `No protocol specified`

**Comment by 89luca89** [comment]
Doesn't seem a `distrobox` error as I do not have any protocol, can you run it with `--verbose`? like

` /usr/local/bin/distrobox-enter --verbose -H -n arch -- "opera"`

**Comment by max12mx13** [comment]
Ok, I ran it with the verbose flag and I got a massive wall of text as shown in the text file (I decided to put it in a file because of github's formatting)
[error.txt](https://github.com/89luca89/distrobox/files/7796256/error.txt)

**Comment by 89luca89** [comment]
Mh seems something with the X11/Way integration

does launching `opera` from a normal container session work?

`distrobox-enter --name arch` and then you go with `opera`

**Comment by max12mx13** [comment]
I get the `No protocol specified error`
Then it states `Discarded=1`
Not sure what that means, I also got a crash ID of `CrashID=2572e20b-f6f7-485d-9093-753122211231
`

**Comment by 89luca89** [comment]
Seems a problem of X11/Wayland integration, I think I'll need to fire a VM and try it :smile: 

Did you install any particular version of Void? Also any particular guide to set up rootless podman on it?

**Comment by max12mx13** [comment]
I installed the main version, from the xfce live image.
The rootless podman was incredibly simple, just install podman with 
`sudo xbps-install podman` and execute the distrobox script and it just works. :+1:

**Comment by 89luca89** [comment]
Cool downloading it right now, will test in the next days and check where are the problems :+1:

**Comment by 89luca89** [comment]
> I installed the main version, from the xfce live image. The rootless podman was incredibly simple, just install podman with `sudo xbps-install podman` and execute the distrobox script and it just works. +1

Are you using the musl or glibc version? I suppose glibc to use podman but better ask

**Comment by max12mx13** [comment]
I use glibc, cannot get my head round musl.

**Comment by 89luca89** [comment]
Ok found the issue
seems like there is some sort of access control on Void due to the fact that Xorg runs as `root`, whilst in other distros it runs as your user

As a workaournd you can use `xhost +` to disable this access control temporarily and indeed the app launching works

**Comment by max12mx13** [comment]
Hey, sorry while using distrobox I started receiving this error while entering a box or using a binary that has come from a box.
`WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers`.
Could this be an error with rootless podman.

**Comment by 89luca89** [comment]
Yes I encountered this too and it's a rootless podman issue, which is not related to the `xhost` issue

**Comment by max12mx13** [comment]
However I have not experienced any limits with this error, perhaps it is not a problem, just another annoying error text

**Comment by max12mx13** [comment]
And also, could you please explain to me how to use `xhost` to export and run apps because I have never heard of it before, sorry.

**Comment by 89luca89** [comment]
The issue right now is that Void runs Xorg as a separate user than you one, so when a client from the container (that runs with your ID) wants to connect to the X11 display, it gets rejected

`xhost` is a command you can install and allows to tweak the access control list to X11

the correct command is `xhost -si:localuser:$USER`, this will allow connections from your user to X11, after this, graphical integration works

**Comment by max12mx13** [comment]
Yep, that is incredibly cool thanks!
I am willing to edit your README if you want to include void linux and the necessary steps (xhost) to run it.
That is if you think void linux is ready to be added to the complatible features.

**Comment by 89luca89** [comment]
generally speaking it seems to work as intended, we have 2 caveats 

1 - obviously systemd service exporting does not work
2 - we need this `xhost` shenaningan

I'll do some further testing and add it to the table :+1:

**Comment by max12mx13** [comment]
I could ask around on the void linux subreddit if anyone would be able to help us with conversion to runit as I am quite incompetent with runit as of now.
You could add to the install script something which determines if the distro is void and if so asks them to create  an autostart for the `xhost` problem. I could try if you want.

**Comment by 89luca89** [comment]
|    Distro  |    Version    | Notes |
| --- | --- | --- |
| Void Linux | glibc | Systemd service export will not work.</br>To setup graphical app exporting, you need to install `xhost` and add this to your `~/.profile` `xhost -si:localuser:$USER`.  |


I'd say something like this
I'm pretty sure the service export will not work as it relies on systemd in user mode heavily

**Comment by 89luca89** [comment]
Yes sorry it's `xhost +si:localuser:$USER`

**Comment by max12mx13** [comment]
Oh yeah just released that difference xD
Also, in my install I do not have a `~/.profile` file, maybe it is just on the vm?

**Comment by 89luca89** [comment]
Let's use `~/.xinirc`

**Comment by max12mx13** [comment]
Yep good idea.

**Comment by max12mx13** [comment]
Also, sorry to keep this issue open and it is completely unrelated but how do you delete a downloaded image?

**Comment by 89luca89** [comment]
> Also, sorry to keep this issue open and it is completely unrelated but how do you delete a downloaded image?

That's done via podman, you can list images with

`podman images`

and delete what you want with

`podman rmi name_of_image:version`
