### ISSUE TITLE
[Suggestion] Container Android Support

### ISSUE THREAD

**Issue by theonlyfoxy** [89luca89/distrobox#741]
It would be useful to have Android integrated with distrobox.
[Redroid](https://github.com/remote-android/redroid-doc) is a pure container Android without Emulator/Qemu Wrapper involved which is a good candidate here.

**Comment by profetik-777** [comment]
@89luca89 recommending closing this given the  now duplicate request here: https://github.com/89luca89/distrobox/issues/725 a
