### ISSUE TITLE
[Discussion] Environment Variables & Locales inside distrobox

### ISSUE THREAD

**Issue by simon-77** [89luca89/distrobox#743]
There is (GUI) software which requires correct `locale` environment variables for correct character encoding. I noticed the issue while using Matlab <https://de.mathworks.com/help/matlab/matlab_env/how-the-matlab-process-uses-locale-settings.html>

**Issue**
Most `LC_*` environment variables inside distrobox default to `POSIX` and are not easily changeable for all use cases.
Host: openSUSE MicroOS
Container: openSUSE Tumbleweed
Distrobox-Version: 1.4.2.1
Demo: [locale.log](https://github.com/89luca89/distrobox/files/11419724/locale.log)

**Describe the solution you'd like**
The possibility to set costume & changeable environment variables for all `distrobox` commands. (e.g. in an Podman `.env` file) 

**Describe alternatives you've considered**
- `distrobox-create -additional-flags "--env-file <file>" [...]` - ISSUE: can't be changed once the distrobox container is created
- `distrobox-enter -additional-flags "--env-file <file>" [...]` - ISSUE: does not work once the desired binary / app is exported with `distrobox-export`
- Create an `.profile` file inside (distrobox container specific) home directory - ISSUE: does not work once the desired binary / app is exported with `distrobox-export`

Additional context
This issue is probably linked to this open suggestion: https://github.com/89luca89/distrobox/issues/571

I do not have the insight to give a qualified suggestion for a solution - and maybe it is already possible and I have only missed this option in the documentation.
Althought, I thought it  might be feasible to have a place to define arguments that are used every time calling `distrobox-enter` with the specific container (e.g. the options `--no-workdir` and `--additional-flags [...]`) - maybe (only) in the manifest file used by `distrobox-assemble`.
From my understanding it would then be possible to define a costume Podman environment-file for every container - which will then be used by every `distrobox-enter <name>` call (without specifying these options every time explicitly) and also be used once the binary / app is exported with `distrobox-export`

**Comment by luc14n0** [comment]
Hello there Simon,

As a fellow **distrobox** user who had to deal with situations somewhat similar to this, I can propose you the following.

while the locale integration with the host system is not implemented/improved, it is possible to pass environment variables to the **distrobox** container in the meantime. Using `distrobox enter --help` will show you that passing `--additional-flags "--env MY_VAR=value"` to `distrobox-enter` is what you're looking for, and it can be repeated to pass more than one (`--additional-flags "--env FOO_VAR=value" "--env BAR_VAR=value" "--env BAZ_VAR=value" ...`).

Another way to pass variables is directly through the RC files of your shell. You could use something like this in your `~/.bashrc` or `~/.profile` or something else if you're using another shell (adapting it depending specifically on what shell is being used):

``` sh
if [[ -n $DISTROBOX_ENTER_PATH ]]; then
    # Set your locale variables and export them
    export LC_FOO=...
    export LC_BAR=...
    ....
fi
```

**Comment by simon-77** [comment]
Hello @luc14n0 and thank you for your extensive answer.

I have already figured out both "workarounds" you mentioned and used them successfully in an interactive shell.
However - I might not have stated that clearly in my first post - neither method works with exported binaries after calling `distrobox-export --bin [...]`.

Best regards
Simon

**Comment by luc14n0** [comment]
Ah, OK. So you're hitting a wall with `distrobox export`. I haven't looked exactly what `distrobox-export` is doing yet, so I don't have more answers for you at the moment. Let's see if someone else joins the discussion.

**Comment by 89luca89** [comment]
Hi @simon-77 you can set container_manager_additional_flags in the distroboxrc file:

```conf
container_manager_additional_flags="--env A=B --env-file tia"
```

I'm pushing a commit that will add to the example
