### ISSUE TITLE
[Error] Exported application is the same as the host application

### ISSUE THREAD

**Issue by RashiqAzhan** [89luca89/distrobox#746]
**Describe the bug**
Exported application is the same as the host application.

**To Reproduce**
Install an application on the host. E.g. VSCodium; browser.
Install the same application in a container and export it.
Both the application appears as expected but they are the same. VS code has the same extensions and settings and the browser has the same history.

**Expected behavior**
I expected a clean, stock VSCodium or browser since it has been exported out from a container.

**Logs**
No logs since no errors are produced.

**Desktop (please complete the following information):**
 - Are you using podman or docker? Docker
 - Docker version 23.0.5, build bc4487a59e
 - distrobox: 1.4.2.1

**Additional context**
Maybe I'm misunderstanding how distrobox works, if so please pardon the question. To my understanding, filesystems are sandboxed in containers so the software should've no context and how the host application is configured.

Both the host and the container are arch systems and I've **not** used the Flatpak version of the applications. They were the premade binaries available in AUR.

I ran `print $HOSTNAME` inside the integrated terminal in VSCodium and the exported VSCodium shows the expected user (as in shows the username of the container instead of the host) while the host VSCodium shows the host username. This leads me to belive the export worked correctly but still not sure why they are not completely different from each other.

**Comment by misobarisic** [comment]
Distrobox by default sets the home of containers to be the same as your user's home. You can specify a custom home directory when creating the box with `--home`. This will most likely solve your issues.

**Comment by RashiqAzhan** [comment]
Specifying a separate home folder has led to another issue when trying to export the application.

Command used
```
distrobox-export --app vscodium
```

Error Message
```
Error: cannot find any desktop files.
Error: trying to export a non-installed application.
```

This command worked when I was using the unified home folder. Typing in `vscodium` inside the distro box opens the VSCodium just fine but I'm not sure why it is unable to export it.

**Comment by awesomeDev12** [comment]
> Specifying a separate home folder has led to another issue when trying to export the application.
> 
> Command used
> 
> ```
> distrobox-export --app vscodium
> ```
> 
> Error Message
> 
> ```
> Error: cannot find any desktop files.
> Error: trying to export a non-installed application.
> ```
> 
> This command worked when I was using the unified home folder. Typing in `vscodium` inside the distro box opens the VSCodium just fine but I'm not sure why it is unable to export it.

Try
``` 
distrobox-export --app codium
```

Which guest container are you using inside the distrobox?

**Comment by profetik-777** [comment]
I think that is the point of distrobox, you share the home, but have isolated apps. 

I think the solution here is to bind the app to a different "home" location, no?

**Comment by 89luca89** [comment]
Solution is: custom home.

**Comment by profetik-777** [comment]
@RashiqAzhan , I can ask @89luca89 but given the exotic drive/partition scheme - this might not be a feasible thing to tackle given it reads from a different partition and what I assume to be an entirely different file system (I assume its btfs , or ext4 + your ntfs?).

**Comment by profetik-777** [comment]
I recommend - close-won't-fix.

**Comment by RashiqAzhan** [comment]
Understood. Thank you for the quick reply. Ext4 for current installation and ntfs for common data partition that both windows and linux can use. I understand the complexity of my request and that this is a open source community effort. This work from the team is much appreciated.

Please let me know if you'd like me to create another issue if this is something the project would like to add to it's backlog to be addressed into the near, or far, future.  Otherwise I will let this be. Thanks.

The reason I am looking at distrobox that I need a software agnostic way of installing multiple instance of the same binaries or applications. Flatpak doesn't support this from what I can gather but snap does but it's canonical cruft. Something like vscodium_home, vscodium_work, vscodium_work_2 each with their separate contained installation without depending on the application developer to develop a suitable profile system. If you're aware of how to do this in any other way besides separate home folder for each container in distrobox I'm all ears. Thanks you again for your contribution to the open source ecosystem.
