### ISSUE TITLE
Getting around `eval` in the various scripts

### ISSUE THREAD

**Issue by mulle-nat** [89luca89/distrobox#749]
Hi

first of all, thanks for the project.  It looks like it can save me a lot of time maintaining my containerized commands  :+1: 

I was curious, so I had a look at the scripts.  I  am wondering: in the generated code from a `distrobox-export`  you are quoting the arguments to run the command with `eval` when outside of the container. But why not just run the command directly ?

`exec /usr/local/bin/distrobox-enter  -n <whatever> --  /usr/bin/<whatever> "%@"`  

####  A way to avoid eval when constructing command lines

When constructing arguments, you could use `set --` to avoid lot of quoting. This example runs its arguments with the '-l' option through the `ls` command:

``` bash
#! /bin/sh -x

[ $# -eq 0 ] && echo "usage: $0 <filename>..." && exit 1

# build from back to front
ls_args="-l -d"
set -- ${ls_args} "$@"
set -- ls "$@"
"$@"
```

**Comment by 89luca89** [comment]
Implemented this only for `enter` now, as this is the only point where we interact with arguments of other commands

Will see if it's worth doing on others, but for now this already solves all our problems :+1:
