### ISSUE TITLE
Error: unable to start container "xxx": unable to find user root: no matching entries in passwd file

### ISSUE THREAD

**Issue by kkarsten62** [89luca89/distrobox#76]
I have created my first podman image/container based on distrobox. It's a Ubuntu 20.04 image with Python3 script based on PyQt reading Garmin devices data via an USB ANT stick, storing the data in a MariaDB. Works well - many thanks for the great development of Distrobox ...

I would like to save/import the container/image now, so that I can use it on a next Laptop by using the "Container save and restore" commands from the README.md. But I get the following error message on final `distrobox-enter` command.
"Error: unable to start container "xxx": unable to find user root: no matching entries in passwd file".

I check it by restoring in same environment I build the container in Fedora 33 and next in a Virtual Machine with Fedora 35. I always get the same message in both environments.

Any suggestions how to fix this?

**Comment by 89luca89** [comment]
Hi @kkarsten62 thanks for reporting
So you create the container on one machine
Use the commit and save commands 
Go to another machine
Restore/import the image, do a `distrobox-create` using that image and the `distrobox-enter` will fail on the new machine is that right?

Can I have some logs of the various stepst you've taken? Also some Infos about  podman or docker versions

**Comment by kkarsten62** [comment]
Hi Luca,
I can reproduce it very easily:
- I am on my Laptop with Fedora 33
- Using default podman version 3.3.1, (docker version 20.10.12, build e91ed57) is installed also, but podman is used by default
- Installation of Distrobox was done yesterday using your `curl ...` command
- Clean podman environment with `podman container rm ...` and `podman image rm ...`
- Create a new image/container by `distrobox-create --name test --image ubuntu:20.04`
- `distrobox-enter --name test` to enter into the container; not further command inside the container
- `CTRL-D` to step out
- Commit container with `podman container commit -p test test_export`
- `podman image ps -a` shows `localhost/test_export:latest`
- `podman save localhost/test_export:latest | gzip > test_export.tar.gz` to export to tar archive file
- `ls -alh` shows file with `51M 31. Dez 17:32 test_export.tar.gz`
- Import back with `podman import test_export.tar.gz`
- `podman image ls -a` shows `<none>                    <none>      9bf3629bf13d`; so I can identify the image by the IMAGE ID
- Create Distrobox image/container by `distrobox-create --image 9bf3629bf13d --name test_import`
- `distrobox-enter --name test_import` ==> **error message appears!**
During the process no error message appears - only on final `distrobox-enter ...`

When I import in a Fedora 35 Virtual Machine ==> same error message appears.

Please let my know if you need more information and let me know where I can reach out for log files ...
I will check now on my Ubuntu 18.04 desktop machine.

Karl ...

**Comment by kkarsten62** [comment]
Hi Luca,

I checked on my Ubuntu 18.04 Desktop Machine. But now with Docker Version 20.10.12, build e91ed57
The procedure from above brings the following error message on `distrobox-enter --name test_import`:

`Error response from daemon: unable to find user root: no matching entries in passwd file
Error: failed to start containers: test_import`

Karl ...

**Comment by 89luca89** [comment]
Cool thanks for the steps, I can reproduce that

The bad part is that on the imported image not even `podman run -ti IMAGE_ID /bin/sh` works, seems like it's an empty image

**Comment by 89luca89** [comment]
Oh got it, you need to use `podman load` not `podman import`

You can see here in the podman documentation: https://docs.podman.io/en/latest/markdown/podman-import.1.html

`To import the archive of image layers created by podman save, use podman load.`

**Comment by 89luca89** [comment]
I've fixed the wrong command in the documentation, tested the whole procedure using a couple of VMs and it works now, can you confirm?

**Comment by kkarsten62** [comment]
Hi Luca,

I did a quick check on my Ubuntu Desktop Machine with Docker and on my Fedora Laptop with Podman.
**YES `load` is the trick :-)**

As a regular user of Docker & Co I am more than impressed to see that all this funny stuff of OS, Gnome, Python, Qt, USB, ANT, MariaDB is working inside your Distrobox container - so many thanks for your great work. It helped me a lot to distribute my self-written Fitness-App from one machine to a next one ... So now I will celebrate Sylvester ...

For me you close the Issue.

Karl ...

**Comment by 89luca89** [comment]
Cool stuff glad is all fixed :-)
