### ISSUE TITLE
[Error] How to fix USB connectivity?

### ISSUE THREAD

**Issue by firefoxlover** [89luca89/distrobox#762]
**Describe the bug**
The container has no access to `/dev/bus/usb` which doesnt make sense from Distroboxes unisolated approach.

**To Reproduce**
Try to use ADB in a Distrobox with an Android phone. There is a permission error, even though the device is detected.

**Expected behavior**
Full permission over all ports as wished.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**

distrobox-1.4.2.1-2.fc38.noarch
podman-4.5.0-1.fc38.x86_64

--- Software ---
OS: Fedora Linux 38.20230521.0 (Kinoite)
KDE Plasma: 5.27.5
KDE Frameworks: 5.106.0
Qt: 5.15.9
Kernel: 6.2.15-300.fc38.x86_64
Compositor: wayland

--- Hardware ---
CPU: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx
RAM: 13.5 GB
GPU: AMD Radeon Vega 8 Graphics
Video memory: 2048MB
Thinkpad T495, no TLP e.g. installed, ports working normally with ADB on host

**Comment by 89luca89** [comment]
You need to use a rootful distrobox for this
Please refer to the documentation

**Comment by bam80** [comment]
@89luca89 you mean here?
https://distrobox.it/useful_tips/#run-the-container-with-real-root

Is anything else needed?

**Comment by bam80** [comment]
> You need to use a rootful distrobox for this

Could we emphasize it in the docs as it's not obvious?

I looked at the docs but didn't find clear answer.
USB access is claimed in the Readme, without any conditions.

**Comment by mabequinho** [comment]
ADB worked well(adb shell) on MicroOS and Tumbleweed container.
