### ISSUE TITLE
[Error] Ubuntu 23.04 no longer has libvte-common

### ISSUE THREAD

**Issue by chenxiaolong** [89luca89/distrobox#763]
**Describe the bug**

`distrobox-init` currently appears to unconditionally install the `libvte-common` package for images that have `apt-get`: https://github.com/89luca89/distrobox/blob/f008b521ee776a66c36a87848c85d3e3f0f6a3dd/distrobox-init#L380

However, the `libvte-common` package was removed from the repos as of Ubuntu 23.04: https://packages.ubuntu.com/kinetic/libvte-common

**To Reproduce**

```bash
distrobox create -i ubuntu:23.04 -n ubuntu-23.04
distrobox enter ubuntu-23.04
```

**Expected behavior**

`libvte-common` should only be installed if the package exists.

**Logs**

[log.txt](https://github.com/89luca89/distrobox/files/11525730/log.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? `4.5.0-1.fc38.x86_64`
 - Which version of distrobox? `1.4.2.1-2.fc38.noarch`

**Additional context**

n/a

**Comment by rrahl0** [comment]
see #774, there seems to be a bigger problem as libvte-2.91-common is not a drop-in replacement.
