### ISSUE TITLE
[Error] /home/user should be symlinked to user home

### ISSUE THREAD

**Issue by sandorex** [89luca89/distrobox#764]
**Describe the bug**

If the home directory of the user is not standard `/home/user` (like on silverblue for example) then `/home/user` exists but its empty and some applications have hardcoded home paths

**To Reproduce**
Steps to reproduce the behavior

Create a distrobox container with different home directory

**Expected behavior**

`/home/user` should be symlinked to user home

**Comment by rrahl0** [comment]
do you have a package, which you are interested in getting to run? I would like to run some tests.

**Comment by sandorex** [comment]
bob from cargo used to access home using hardcoded path until it was fixed very recently in https://github.com/MordechaiHadad/bob/issues/135 

Quick fix was to just symlink /home to /var/home (on silverblue/kinoite)

**Comment by 89luca89** [comment]
This is already fixed by dcf177ef14d3eea6f09e9547cc2f10e21c55371d
