### ISSUE TITLE
[Suggestion] allow running distrobox from within distrobox

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#770]
**Is your feature request related to a problem? Please describe.**
A nice feature of toolbox now is being able to able to run it from _within_ a toolbox.
eg You can 'enter' another toolbox from within toolbox
It would be nice if distrobox allowed this too.

**Describe the solution you'd like**
I haven't looked into it in detail but I assume toolbox is just calling out into the host toolbox.
This might require having distrobox packaged for the distro in question (same probably applies to toolbox).

**Comment by rrahl0** [comment]
well this is already possible, just use

**Comment by 89luca89** [comment]
Yep @rrahl0 has the right answer
either do a

`sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/distrobox`

or if you want 2 different versions of distrobox just link podman/docker
