### ISSUE TITLE
GNOME Console support

### ISSUE THREAD

**Issue by VarLad** [89luca89/distrobox#773]
https://gitlab.gnome.org/GNOME/console/-/merge_requests/125
@89luca89 Apparently they're waiting for a distrobox maintainer to comment on the PR.
Making this issue, just to bring your attention to that :)

**Comment by profetik-777** [comment]
@89luca89 This might be extreme opinion, but gnome got themselves into a mess with half-thought out terminal app...aren't they considering giving up on development? 

I can totally back the idea of just not doing anything with console in the meantime.

**Comment by VarLad** [comment]
@profetik-777 Basically, the PR I linked implements toolbox support and the author of the PR can implement distrobox support too, if a maintainer from distrobox has no issues with it. (Need to use appropriate icons and stuff)

**Comment by 89luca89** [comment]
Hi, no problem from my side, I've replied to the PR on gitlab :+1: 

Closing this, thanks for the notification :+1:
