### ISSUE TITLE
[Error] Proxy variables are not inherited when container starts

### ISSUE THREAD

**Issue by andreyorst** [89luca89/distrobox#776]
**Describe the bug**

I have an Ubuntu 20.04 with the GNOME Shell desktop environment in which I set proxy settings. When I start the terminal, I get the usual set of environment variables related to proxy settings, such as `http_proxy`, `no_proxy`, etc. If I enter the container from a terminal, with the usual `distrobox enter ...` the proxy variables are also set in the container.

However, when I use distrobox as the main CLI in the GNOME Terminal, as per the https://distrobox.privatedns.org/useful_tips.html#using-distrobox-as-main-cli instructions, the environment variables for proxy are not set. Setting the "Run command as login shell" doesn't change anything related to this problem.

/The same happens for exported applications, for example, I use Emacs in a container with a lot of development tools. The launch command in the generated `.desktop` file is `distrobox-enter -n name -- emacs`, and upon launch, proxy variables are not set in the container, and thus Emacs or any processes that it spawns can't access resources that require proxy.

**To Reproduce**

1. Set proxy settings in GNOME settings:
   ![image](https://github.com/89luca89/distrobox/assets/19470159/6cfdf24c-29a7-4bc2-ab45-ded3e329be06)
2. Launch the terminal and observe variables in a terminal:
   ```
   $ env | grep -i proxy
   no_proxy=localhost,127.0.0.0/8,::1
   ftp_proxy=http://localhost:1234/
   https_proxy=http://localhost:1234/
   NO_PROXY=localhost,127.0.0.0/8,::1
   FTP_PROXY=http://localhost:1234/
   HTTPS_PROXY=http://localhost:1234/
   HTTP_PROXY=http://localhost:1234/
   http_proxy=http://localhost:1234/
   ```
3. Set the main cli to distrobox, repeat step 2.

**Expected behavior**
Proxy variables are inherited from the desktop environment.

The only way of solving it right now is to launch container from the terminal session that has these variables inherited from the desktop environment.

**Desktop:**
 - podman 3.4.2 with ubuntu 20.04 container
 - distrobox version: 1.4.2.1

**Comment by andreyorst** [comment]
Upon further inspection I've noticed that it was Gnome Terminal what set the variables: https://github.com/GNOME/gnome-terminal/blob/a1ca39515e1747b6c28a5e2620eb28caa2568505/src/terminal-app.cc#L963-L985

from gsettings, so I guess this won't be easy to support for arbitrary container setup.

**Comment by 89luca89** [comment]
Hi @andreyorst 

I'm using gnome-terminal with a profile that has as command a `distrobox enter NAME` and the variables you show are present:

![image](https://github.com/89luca89/distrobox/assets/598882/d455e6f6-47d3-492e-a086-e1280d6756ab)

**Comment by andreyorst** [comment]
Weird, doesn't happen for me on both Ubuntu and Fedora distributions (and even toolbox on Fedora). Thanks for looking into it.

I've migrated the issue for now by implementing a piece of code that manually reads setting values from gsettings upon app launch, so this is not an issue for me anymore.
