### ISSUE TITLE
[Suggestion] Default to "y" or "n" when it comes to [y/n]

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#78]
When you run this `distrobox-create` you'll be greeted by this message if the specified container image has not been pulled `Do you want to pull the image now? [y/n]`. And if you press enter it'll prompt you to make an input.
My suggestion is to default to either Yes or No in certain commands. For example, `[y/n]` would be replaced by `[Y/n]` or `[y/N]`. 
It would reduce the overall amount of keystrokes by a small margin, nothing more.

**Comment by 89luca89** [comment]
Seems reasonable I'm ok with this
I'd default to N just to leave the choice to the user, we already implemented a `--non-interactive` mode to do automatic Yes
