### ISSUE TITLE
[Error] Host's groups are not mapped?

### ISSUE THREAD

**Issue by GrabbenD** [89luca89/distrobox#782]
`run.oci.keep_original_groups=1` was introduced in https://github.com/89luca89/distrobox/issues/121 which ensures: `the group keeps what the parent process can do (so in this case what the $USER can do outside the container) and propagate it inside the container` (@89luca89). This is useful for inheriting access to certain devices like `/dev/dri/card1`. However, it seems like this doesn't work as intended with Podman on OpenSuSE MicroOS Container Host?

```shell
# HOST
$ podman --version
podman version 4.5.1
$ whoami
me

$ sudo usermod -G video,render -a $USER
$ exec su -l $USER # Update groups without creating a subshell

$ mkdir ~/test; chmod 0770 ~/test; sudo chown root:video ~/test
$ touch ~/test/file1 # This works
$ ls -ld ~/test
drwxrwx--- 1 root video 14 Jun  6 11:17 /var/home/me/test

$ distrobox create --name desktop --image registry.opensuse.org/opensuse/tumbleweed:latest
$ distrobox enter desktop

# CONTAINER
$ touch ~/test/file2
touch: cannot touch '/var/home/me/test/file2': Permission denied
$ ls -ld ~/test
drwxrwx--- 1 65534 65534 24 Jun  6 11:19 /var/home/me/test
```

Please advise

**Comment by GrabbenD** [comment]
**Workaround**
Turns out you need `crun` instead of `runc` for this to work, see: https://github.com/containers/podman/issues/10166
With podman I was able to resolve it using:
```shell
# Tumbleweed
$ zypper install crun

# MicroOS
$ transactional-update pkg install crun
$ reboot
```
```shell
# Result
$ podman info --debug
host:
  ociRuntime:
    name: crun
```

**Comment by 89luca89** [comment]
Hi @GrabbenD 

that is not a workaround
that is how podman + runc/crun work
