### ISSUE TITLE
[Error] rootless distrobox-create asks for sudo for no apparent reason

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#789]
**Describe the bug**
When creating new non-rootful container, distrobox tries to use sudo without any explanation why

**To Reproduce**
Create any new non-rootful container in a clean shell

**Expected behavior**
No root perms asked

**Additional context**
This might be the source of the problem:  https://github.com/89luca89/distrobox/blob/main/distrobox-generate-entry#L290
It is being asked after https://github.com/89luca89/distrobox/blob/main/distrobox-create#L796 even though this can clearly be removed without a problem by user.

**Comment by 89luca89** [comment]
Thanks for reporting, this has been fixed now
