### ISSUE TITLE
distrobox login problem

### ISSUE THREAD

**Issue by roxibar73** [89luca89/distrobox#79]
![photo_2021-12-31_20-35-24](https://user-images.githubusercontent.com/74426602/147837232-2384dd99-7ecb-45dc-8e69-6117c7744d83.jpg)

as described I have problems logging into distrobox, returning the error as screen both with Ubuntu and Arch.
Do you have solutions?
PS: Fedora 35

thanks

**Comment by FedX-sudo** [comment]
What is the output of `distrobox-enter --name arch-distrobox --verbose`?

**Comment by roxibar73** [comment]
> What is the output of `distrobox-enter --name arch-distrobox --verbose`?

sorry what does verbose mean? forgive my ignorance

**Comment by roxibar73** [comment]
> > What is the output of `distrobox-enter --name arch-distrobox --verbose`?
> 
> sorry what does verbose mean? forgive my ignorance

the error also comes with    distrobox-enter --name ubuntu-20

**Comment by FedX-sudo** [comment]
It gives the full dump of what Podman or Docker is doing.

**Comment by FedX-sudo** [comment]
Oh, and by the way, welcome to GitHub, hope you find a long happy hobby in free and open source software!

**Comment by roxibar73** [comment]
> Oh, and by the way, welcome to GitHub, hope you find a long happy hobby in free and open source software (and Linux of course)!

thanks

**Comment by roxibar73** [comment]
hello, I solved it by restoring a previous snapshot, I don't understand what exactly happened, but the problem arose when I tried to install Timeshift on Ubuntu 20.04, from then on it returned the error I attached in the screen.
close Issue.
Thank you

**Comment by 89luca89** [comment]
Hi @roxibar73 thanks for reporting, reading that i was suspecting something to do with time shift, glad you resolved 👍

**Comment by roxibar73** [comment]
> Hi @roxibar73 thanks for reporting, reading that i was suspecting something to do with time shift, glad you resolved +1

I spoke too soon 
![Schermata del 2022-01-01 10-54-16](https://user-images.githubusercontent.com/74426602/147848128-719c25d4-4ad1-47be-a3e8-c41b4985d04c.png)

**Comment by roxibar73** [comment]
> > Hi @roxibar73 thanks for reporting, reading that i was suspecting something to do with time shift, glad you resolved +1
> 
> I spoke too soon ![Schermata del 2022-01-01 10-54-16](https://user-images.githubusercontent.com/74426602/147848128-719c25d4-4ad1-47be-a3e8-c41b4985d04c.png)

but what does Timeshift have to do with it??

**Comment by 89luca89** [comment]
Mh I see the problem here

Seems like you're in a directory (your home) which in reality is a link to that timeshift path
That timeshift path is not present inside the container
When the container starts, it tries to `cd` inside it, and will fail for this reason

**Comment by 89luca89** [comment]
I have an idea, probably it is related to the fix I've implemented in this commit: [47e86717a69029a22985f55ec5d02c7c761b3da7](https://github.com/89luca89/distrobox/commit/47e86717a69029a22985f55ec5d02c7c761b3da7)
 
Can you try installing from git the latest version from `main`, create a new container and try again?

**Comment by roxibar73** [comment]
> ~I have an idea, probably it is related to the fix I've implemented in this commit: [47e86717a69029a22985f55ec5d02c7c761b3da7](https://github.com/89luca89/distrobox/commit/47e86717a69029a22985f55ec5d02c7c761b3da7) Can you try installing from git the latest version from `main`, create a new container and try again?~
> 
> You can simply install new version 1.2.6 which includes the mentioned fixes, to have the fix applied please create a new container after the update.

ok, thanks a lot I can do it from COPR?

**Comment by 89luca89** [comment]
The COPR needs to be updated, so you can either wait for that or you can install manually using the command shown in the README page
