### ISSUE TITLE
[Error] No sudo when container created for arch linux

### ISSUE THREAD

**Issue by sonulohani** [89luca89/distrobox#790]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I have created archlinux container however there is no sudo installed. Now I dont know how do I update the container using pacman.

**To Reproduce**

- `distrobox create -i docker.io/archlinux -n archlinux`
- `distrobox enter archlinux`

**Expected behavior**
Should have sudo installed

**Logs**
[distrobox log](https://github.com/sonulohani/distrobox_logs/blob/main/distrobox-create-log.txt)
[podman log](https://github.com/sonulohani/distrobox_logs/blob/main/podman%20logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? podman version 4.3.1
 - Which version of distrobox? Last commit from git 209a6999a1df5b0a0f09b89f91ab1a98af4aa102

**Additional context**
![image](https://github.com/89luca89/distrobox/assets/2958681/5a310ac9-e9cd-4976-85c4-3deb583361ba)

**Comment by 89luca89** [comment]
Hi @sonulohani thanks for reporting, this has been fixed
