### ISSUE TITLE
[Error] Distrobox-export uses the real usr directory instead of podman's

### ISSUE THREAD

**Issue by Doc-4** [89luca89/distrobox#791]
**Describe the bug**
I get this problem when running distrobox-export -a mediacenter31 (the name of the program and what you'd run to launch it) within distrobox.

This seems to be a bug? I do also have these set already in .bashrc, though I have tried using other config files such as .distroboxrc with the same results.
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/podman/bin:$PATH
xhost +si:localuser:$USER
I also have the below line in etc/profile for the box as you suggested in #606, but it did not fix any issues
export PATH=$HOME/.local/bin:$HOME/.local/podman/bin:$PATH

My last issue on this was closed prematurely as a duplicate issue of something entirely unrelated, this isn't about the generated shortcut failing to run the app correctly, this is about the export process itself failing.

**To Reproduce**
Create box, install dependencies and program, attempt to export the program

**Expected behavior**
Operation successfully creates a desktop shortcut
**Logs**
[distroboxerror.txt](https://github.com/89luca89/distrobox/files/11728272/distroboxerror.txt)
[podmanlog.txt](https://github.com/89luca89/distrobox/files/11728274/podmanlog.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.4.3
 - Which version of distrobox? 1.4.2.1

**Additional context**
As far as I can tell, the error I get, "cp: cannot stat '/usr/lib/jriver/Media': No such file or directory", is probably because it's trying to read or write to the real "/usr/lib/jriver/media" subdirectory (which doesn't exist just like the error says, lib has no "jriver") instead of the one in the podman container (which does exist) for some reason.

**Comment by 89luca89** [comment]
Hi @Doc-4 
I Think this is due to the to the white space in the name which should have been fixed in the latest commits

can you try using the latest version from git?

**Comment by Doc-4** [comment]
Tried this and finished running various tests on things, everything related to the export process seems to have worked, I'm able to un-export the application as well. This solution now works almost perfectly, thank you very much! Some things I noticed about this application I'm passing along as bugs or limitations if you weren't already aware of them existing with other programs: 

The icon is incorrectly rotated 90 degrees for the program, exporting it makes it have no icon (though you can manually add it to the .desktop file at this point, not a big issue). Inversing the export puts back the improperly rotated icon. Another thing is that unlike "native" applications, while I get audio and video as a result of installing pulse audio and other dependencies within the box, I don't get the "media player" pop-up for applications playing audio/video in the KDE taskbar like I would for a browser or mpv. It might be a limitation as well, but FN + F5 through F8, which normally control media for any running applications, only work when the window is focused. Don't take it as me complaining though, thank you for your continued work on this project, it's proved very helpful.
