### ISSUE TITLE
[Suggestion] Provide a way for the user to directly specify `SHELL`

### ISSUE THREAD

**Issue by midchildan** [89luca89/distrobox#793]
**Is your feature request related to a problem? Please describe.**
`distrobox-init` always installs the shell from the container distro's package manager and points `SHELL` to it. There's no way for users to choose their own `SHELL`. This became a problem when I tried to use a shell provided by the host through a shared mount.

**Describe the solution you'd like**
Provide a way for `distrobox-init` to
1. keep `SHELL` unchanged
2. skip installation of the shell

**Describe alternatives you've considered**
Adding special rules for shells in known paths, which was the original approach in #750.

**Additional context**
https://github.com/89luca89/distrobox/pull/750#issuecomment-1586236619

**Comment by midchildan** [comment]
The current approach I'm considering is skipping the shell determination logic when

1. `SHELL` matches an entry in `/etc/shells`.
2. `SHELL` points to an executable path

**Comment by 89luca89** [comment]
i'd say, for now we do a `command -v` of the SHELL, but it could be at this point useful to:

- check if the file literally exist (like `ls -l file`)
- if not, then we extract the basename, and do a command -v
- if not, then we do the install

This should work for the nix situation?

**Comment by Nitrousoxide** [comment]
can't you just do --init-hooks "chsh path/to/shell/binary" as part of the distrobox create command?

**Comment by midchildan** [comment]
@89luca89 Yes, I think that'll work. Then I'll be able to use something like `--init-hooks 'SHELL=~/.nix-profile/bin/zsh; echo "$SHELL" | sudo tee -a /etc/shells'`.

@Nitrousoxide It's not possible to change the shell without making changes to distrobox. The user doesn't exist yet in the container image when the pre-init hooks are run.

**Comment by 89luca89** [comment]
> @Nitrousoxide It's not possible to change the shell without making changes to distrobox. The user doesn't exist yet in the container image when the pre-init hooks are run.

That's for pre-init-hooks, but plain init-hooks run *after* user creation, so that would also work
and probably it's the better solution to the problem (as it's a very specific use-case)

**Comment by midchildan** [comment]
I tried this, and while it does change the default shell, the init-hooks are still unable to change the `SHELL` variable.  So anything that spawns a subshell, say tmux, would launch a different shell.

**Comment by midchildan** [comment]
My bad, `SHELL` was unchanged because I mistakenly set `SHELL` inside a subshell.

I now use pre-init-hooks to backup the original value of `SHELL`. Then I restore it and run chsh in init-hooks. Here's the actual config I'm currently using:

* [distrobox.conf](https://github.com/midchildan/dotfiles/blob/1c190d0ac1d87c159b8b7d777f02261ae58a3fc5/files/.config/distrobox/distrobox.conf)
* [helper script used by the init hooks](https://github.com/midchildan/dotfiles/blob/1c190d0ac1d87c159b8b7d777f02261ae58a3fc5/files/.local/libexec/distrobox/nix.sh)

It mostly does what I want, though it does depend on distrobox's internal implementation.

Thanks for the help!
