### ISSUE TITLE
[Discussion] How to rename a distrobox?

### ISSUE THREAD

**Issue by mystiquewolf** [89luca89/distrobox#796]
Is your feature request related to a problem? Please describe.
distrobox created an ubuntu distrobox with the name tumbleweed

Describe the solution you'd like
rename the distrobox to ubuntu

**Comment by 89luca89** [comment]
You can use the clone flag in create, or just recreate it with the correct name

There is a docker/podman rename command, but it's pretty new and lots of hosts don't have still that version
so for now that is the workarounc

**Comment by mystiquewolf** [comment]
I've recreated it.

**Comment by ChocolateLoverRaj** [comment]
I feel like rename is a pretty necessary command.

**Comment by J3RN** [comment]
A manual approach is:
1. Use podman to rename the container
    ```
    podman container rename <oldname> <newname>
    ```
2. Update exported applications under `~/.local/share/applications/`.  The `Exec` line in each `.desktop` file for an exported application will contain `-n <oldname>` which you'll need to change to `-n <newname>`.
3. [Optional] You can update the hostname within the container with `sudo hostname <newname>`

**Comment by grtcdr** [comment]
@J3RN's method may be manual but there's probably no sure way for `distrobox` to ensure correct, automatic renaming when a user could've potentially modified their `.desktop` files manually (tracking `.desktop` file changes is probably out-of-scope for a container management wrapper), it is probably best left to the user to do the renaming operation (and extra migration) on their own.
