### ISSUE TITLE
[Discussion] CUDA support - need to run a CUDA program on the host system before it works in a container

### ISSUE THREAD

**Issue by trantp** [89luca89/distrobox#804]
This issue exists in release 1.5.0:

We're running a Debian 11 container created with `distrobox create --nvidia` on Alma Linux 9.0 and RHEL 9.0. Directly after a reboot CUDA code doesn't run in the container but after we run any CUDA application on the host system it starts working.

An easy way to reproduce this problem is to run the deviceQuery sample from the CUDA toolkit in the container after a host reboot to show the error, then run the same sample on the host system. Then do the same in the container.  The second run in the container succeeds in showing device information.

 When we run `nvidia-modprobe --unified-memory --create-nvidia-device-file=0 ` before starting the container the test also succeeds.

Our current solution is to run the above nvidia-modprobe line as a systemd service, but it would be nice if there was a way to handle this in distrobox enter.

(Since it affects Alma Linux 9.0 I assume it'll also impact RHEL 9.0)

**Edited to add:**

Tested on an Ubuntu 22.04 Laptop with the same result.

**Comment by 89luca89** [comment]
A rootless container cannot affect host's kernel
So either you need to modprobe that module at boot, or use a rootful container

**Comment by trantp** [comment]
Nvidia did something a bit ugly  here. They made the command line tool nvidia-modprobe suid root  so it can be invoked by a regular user.  You could probably start it with distrobox host-exec.

I'm not sure if you'd want to interact with a suid binary that is apparently not always installed though.

**Comment by 89luca89** [comment]
Exactly so this probably should be documented in `useful_tips` by someone else than me (as I don't have the HW to create the little guide) 

But I don't think distrobox (the program) should do anything here
