### ISSUE TITLE
[Error] Apt doesn't work in ubuntu 22.04 container

### ISSUE THREAD

**Issue by TheBicPen** [89luca89/distrobox#805]
**Describe the bug**
apt update and apt upgrade both fail in a ubuntu 22.04 container.

**To Reproduce**
```
$ distrobox-create -n test -i ubuntu:22.04
$ distrobox enter test
@test:~$ sudo apt update
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Could not resolve 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Could not resolve 'archive.ubuntu.com'
Err:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Could not resolve 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Could not resolve 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Could not resolve 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
@test:~$ sudo apt upgrade --fix-missing
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libcap2
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.3 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2 amd64 1:2.44-1ubuntu0.22.04.1
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2 amd64 1:2.44-1ubuntu0.22.04.1
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2 amd64 1:2.44-1ubuntu0.22.04.1
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2 amd64 1:2.44-1ubuntu0.22.04.1
Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2 amd64 1:2.44-1ubuntu0.22.04.1
  Could not resolve 'archive.ubuntu.com'
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libc/libcap2/libcap2_2.44-1ubuntu0.22.04.1_amd64.deb  Could not resolve 'archive.ubuntu.com'
```

**Expected behavior**
apt should install the packages I ask for

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[log.txt](https://github.com/89luca89/distrobox/files/11790895/log.txt)
[log.txt](https://github.com/89luca89/distrobox/files/11790904/log.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 3.4.4
 - Which version of distrobox? 1.5.0

**Additional context**

**Comment by profetik-777** [comment]
Working for me. 

While I have observed some instances where apt would read as if it wasn't there in the distrobox, but usually a reboot would resolve it and I wouldn't bother looking into it. 
 
 I just created a distrobox 22.04 and while I did see "hit / get/ ign in some read outs - things progressed normally. I would try again in a day and if it still persists. 

Note this could be just repository changes/updating. 

GET means that there is an update available for the package and it's new repository link is saved.

HIT means that you already have the latest version of the package.

IGN means that the package is ignored, maybe because it is obsolete and no update is available. This might happen also when the developer changes the version and repository keys. (https://www.quora.com/What-do-GET-HIT-and-IGN-mean-when-I-run-an-apt-get-update-on-Ubuntu)

**Comment by Denizzje** [comment]
I currently have the same issue, also tried with Ubuntu 20.04 The output of Ubuntu 20.04 seems the same as the user above. Currently I cannot install any packages on an Ubuntu distrobox because of this.

```
Container Setup Complete!
bash: /home/linuxbrew/.linuxbrew/bin/brew: No such file or directory
<username>@ubuntu:~$ sudo apt-get update
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Could not resolve 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Could not resolve 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Could not resolve 'archive.ubuntu.com'
Err:4 http://security.ubuntu.com/ubuntu focal-security InRelease
  Could not resolve 'security.ubuntu.com'
Reading package lists... Done         
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Could not resolve 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by alcir** [comment]
For the records.
`distrobox-init` reports this
`/run/host//etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`
`diff: /run/host../run/systemd/resolve/stub-resolv.conf: No such file or directory`

Thereby `/etc/resolv.conf` is empty, for this reason it can't resolve 'security.ubuntu.com'

**Comment by alcir** [comment]
Related issue #801

**Comment by 89luca89** [comment]
I can reproduce this, I'm pushing a fix
It wasn't working with relative symlinks, it will work now

**Comment by Denizzje** [comment]
Hi @89luca89 , sorry for a noob question but I only found out about distrobox today via Phoronix noting the 1.5 release, I installed via curl... will this fix be picked up there if I reinstall or will I have to wait for a 1.5.1 / 1.6 release? I specifically need Ubuntu + trying out the GPU sharing so downgrading to 1.4.2 will not work for me. Thanks for the quick fix!

**Comment by TheBicPen** [comment]
@Denizzje 
Try using the instructions for "If you want to install the last development version" here:
https://github.com/89luca89/distrobox#alternative-methods

Uninstalling and then installing with that command should pick up the fix.

**Comment by h4kon** [comment]
Hello, if I understand correctly the latest version of distrobox should correct the behavior, is that it? For me it is happening in the current version of distrobox according to the day of the message and in the version of ubuntu 23.04.

**Comment by BrettRD** [comment]
I had a related (but different) problem where resolve.conf in the distrobox became a zero size file with the executable bit set.
This was fixed for me by disabling systemd-resolved on the host system and stopping the affected distroboxes

https://gist.github.com/zoilomora/f7d264cefbb589f3f1b1fc2cea2c844c

**Comment by gronki** [comment]
Any progress on this? Cannot use apt with Ubuntu 24.04 container on Opensuse Tumbleweed.
