### ISSUE TITLE
[Error] distrobox-assemble fails to handle multiple declarations with bash < 5.2.0

### ISSUE THREAD

**Issue by DonaldKellett** [89luca89/distrobox#806]
See also: #803 

## Summary

`distrobox-assemble` fails to handle multiple declarations with bash < 5.2.0, e.g. when specifying `init_hooks` more than once in `distrobox.ini`, and the container is not created

## Description

Consider the advanced example in `man 1 distrobox-assemble`:

```ini
[tumbleweed_distrobox]
image=registry.opensuse.org/opensuse/distrobox
pull=true
additional_packages="acpi bash-completion findutils iproute iputils sensors inotify-tools unzip"
additional_packages="net-tools nmap openssl procps psmisc rsync man tig tmux tree vim htop xclip yt-dlp"
additional_packages="git git-credential-libsecret"
additional_packages="patterns-devel-base-devel_basis"
additional_packages="ShellCheck ansible-lint clang clang-tools codespell ctags desktop-file-utils gcc golang jq python3"
additional_packages="python3-bashate python3-flake8 python3-mypy python3-pipx python3-pycodestyle python3-pyflakes python3-pylint python3-python-lsp-server python3-rstcheck python3-yapf python3-yamllint rustup shfmt"
additional_packages="kubernetes-client helm"
init_hooks=GOPATH="${HOME}/.local/share/system-go" GOBIN=/usr/local/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
init_hooks=GOPATH="${HOME}/.local/share/system-go" GOBIN=/usr/local/bin go install github.com/onsi/ginkgo/v2/ginkgo@latest
init_hooks=GOPATH="${HOME}/.local/share/system-go" GOBIN=/usr/local/bin go install golang.org/x/tools/cmd/goimports@latest
init_hooks=GOPATH="${HOME}/.local/share/system-go" GOBIN=/usr/local/bin go install golang.org/x/tools/gopls@latest
init_hooks=GOPATH="${HOME}/.local/share/system-go" GOBIN=/usr/local/bin go install sigs.k8s.io/kind@latest
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/crun
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
```

With bash 5.1.8, `distrobox assemble create` results in a syntax error and the container is not created:

- OS: deepin 23 Beta
- bash 5.1.8
- podman 4.3.1
- distrobox 1.5.0

```
/home/dsleung/.local/bin/distrobox-assemble: 4: /tmp/tmp.bRQSjXVvcJ: additional_packages+=|net-tools nmap openssl procps psmisc rsync man tig tmux tree vim htop xclip yt-dlp: not found
```

![Screenshot_deepin-terminal_20230620111428](https://github.com/89luca89/distrobox/assets/7777884/1318a0d7-bbb1-4d18-864f-6a9df229d6a1)

With bash 5.2.15, `distrobox assemble create` works as intended and the corresponding container is created:

- OS: Fedora 38 Workstation
- bash 5.2.15
- podman 4.4.2
- distrobox 1.5.0

![Screenshot from 2023-06-20 11-58-17](https://github.com/89luca89/distrobox/assets/7777884/d1ddcd7d-8316-4086-b987-0548832843e4)

![Screenshot from 2023-06-20 11-59-24](https://github.com/89luca89/distrobox/assets/7777884/5b398172-cb01-45ee-be62-97bc2be101f2)

![Screenshot from 2023-06-20 12-10-19](https://github.com/89luca89/distrobox/assets/7777884/f76dfb47-0d7d-458e-8074-52531da3ad4d)

## Recommended fix

Mention the minimum supported Bash version (bash >= 5.2.0) of `distrobox-assemble` in the official docs and/or man pages so users know what to expect

**Comment by 89luca89** [comment]
Nice catch, I've pushed a fix, It was a bashism, and distrobox is posix so that would have broken also on busybox userlands

Fixed now :+1:
