### ISSUE TITLE
[Question] How do I make distrobox to create a blank container?

### ISSUE THREAD

**Issue by nhandt64** [89luca89/distrobox#814]
## Is your feature request related to a problem? Please describe.
Maybe, some commands and apps version doesn't match with host application or the app has two variants (like `google-chrome` and `chromium`) which causes frustrating like results in app data in `~/.local/share` broken. Or I want just to use the container as a blank VM.

## Describe the solution you'd like
I'd like having distroboxes do not inherit anything from host e.g. commands and apps (package manager and flatpak), configs (like dotfiles), etc.

## Describe alternatives you've considered
I've tried to use podman only but it isn't too handy as distrobox commands.

## Additional context
I looked up all the issue of this report and haven't found any of them matches my case so far.

**Comment by nhandt64** [comment]
> This is not the use case for distrobox (there is a feature request to make it more of a sandbox though). so if you want to have a contained container, then you should use podman directly for now. (or implement it and PR here)

I see, thanks for your reply.
I'll close this issue for now.

**Comment by misobarisic** [comment]
You can specify a custom container home when creating by using `--home` or `-H`. This will leave your host `~/.local/share` untouched

**Comment by nhandt64** [comment]
> The way I read his message was more about isolating the container from the host in total, not only home dir

Yeah, this much isolating simply boiled down to just using podman from the beginning. 😅
