### ISSUE TITLE
[Discussion] distrobox inside distrobox

### ISSUE THREAD

**Issue by k1mbl3** [89luca89/distrobox#815]
Is there a documented method for accessing an ephemeral container from within another container? My use case involves creating an ephemeral container for each project to maintain cleanliness in the "main" container.

Currently, I am using the following command:
```shell
distrobox-host-exec distrobox-ephemeral --image <project_image>
```

**Comment by 89luca89** [comment]
You can use `ln -s /usr/bin/docker-host-exec /usr/local/bin/podman` in order to have podman available and then use distrobox, or use the guide linked above to have a different podman inside
