### ISSUE TITLE
[Help] Make Davinci Resolve find host's GPU with the --nvidia option

### ISSUE THREAD

**Issue by lion-artiste** [89luca89/distrobox#816]
This is my first report here, and I'm not sure this is a bug, but I've been struggling with this for a few days, without success ! I need your help.

I have been following this tutorial : https://youtu.be/wmRiZQ9IZfc in order to install DaVinci Resolve in a Fedora 37 container. 
Everything works find, except that when I launch DaVinci Resolve after the installation, I receive this message : "Unsupported GPU Processing Mode. Please review the GPU drivers and GPU configuration under preferences."
In the preferences, it seems that DaVinci Resolve doesn't detect my Nvidia graphic card.

Prior to version 1.5.0, I tried to install akmod-nvidia from RPM Fusion, and all related packages I could find in all tutorials I could find, but nothing seemed to work. I thought that the error was coming from a different driver version between the host (NixOS with driver 535) and the container (Fedora 37 with driver 525).

I waited for the 1.5.0 release and the --nvidia option, I tried to create a new container with it, but it doesn't seem to work either. When I call "nvidia-smi" in the container, I get the host's information (driver 535, CUDA 12.2). But DaVinci still doesn't find my GPU.

Do you have any idea where this can come from ?

This is the logs I get when launching "/opt/resolve/bin/resolve" in the container : 

ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
18.5.0b.0031 Linux/Clang x86_64
Main thread starts: 17815180
0x7ff017815180 | Undefined            | INFO  | 2023-06-23 06:33:33,181 | --------------------------------------------------------------------------------
0x7ff017815180 | Undefined            | INFO  | 2023-06-23 06:33:33,181 | Loaded log config from /home/raphael/.local/share/DaVinciResolve/configs/log-conf.xml
0x7ff017815180 | Undefined            | INFO  | 2023-06-23 06:33:33,181 | --------------------------------------------------------------------------------
Resolve communication is open and waiting..
Accepted new client

Thank you for your time.

**Comment by trantp** [comment]
This sounds similar to this Issue: https://github.com/89luca89/distrobox/issues/804

The simplest way to check if that's it is probably to run `nvidia-modprobe --unified-memory --create-nvidia-device-file=0 ` on the host system and try again.

**Comment by 89luca89** [comment]
This could be yes
I cannot debug this, and it doesn't seem to be a distrobox-related issue, more about nvidia and its libs

If nvidia-smi works, it means the driver integration is working

**Comment by PizzaLovingNerd** [comment]
Here's a manual solution for Resolve...

```
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo -y
sudo dnf install -y cuda-driver```

**Comment by Zoucular** [comment]
> Here's a manual solution for Resolve (Assuming Alma or Rocky Linux 8)... idk why that tutorial recommends Fedora 37 lol
> 
> ```
> sudo dnf install -y dnf-plugins-core
> sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo -y
> sudo dnf install -y cuda-driver```
> ```

Hey, I'm getting an error that I'm not sure how to fix. It's telling me that I need at least 162MB more space needed on teh /usr/share/nvidia filesystem. 

I'm not really good at linux so any help is appreciated
