### ISSUE TITLE
[Suggestion] Replace "name" with "$(whereis name)" in export_binary?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [89luca89/distrobox#817]
When trying to export a binary program, it sucks a bit as you need to know the path.

`whereis NAME` can replace that, and get rid of the searching. It should also be no problem if people enter the full path.

I could try adding that

**Comment by 89luca89** [comment]
What if you have 2 binaries in path?
Like for example

Distrobox 1 -> install htop -> export htop
Distrobox 2 -> instal htop -> export htop

Which htop is exported in Distrobox 2?

I think export is a very an action the user needs to pay attention to, it's not something to do either automatically nor "on-the-fly"
Forcing to use a path, is less ambiguous and removes a lot of problematics that would come up from using simple names

**Comment by firefoxlover** [comment]
@89luca89 This is something else.

If you would export any binary from different distroboxes, they would be called the same and it would probably give an error? 

So this is not relevant.

Its about

```
distrobox enter NAME
PM install PACKAGE
distrobox-export -b PACKAGE
```

What it does is take the first entry of `whereis PACKAGE`

An issue may be from what location it has what permissions. So if there are multiple, take the first element?

This would be

```
PATH=whereis $PACKAGE | awk '{print $2}'
distrobox-export -b $PATH
```

**Comment by 89luca89** [comment]
Thinking of it, I'm not liking the idea of not specifying the path
Too risky in case of thared PATHs between host-guest

So I'm not going to implement this, If I change mind I'll reopen this
