### ISSUE TITLE
Language problem when integrating an application to the host with distrobox-export --app

### ISSUE THREAD

**Issue by Cardeepin** [89luca89/distrobox#819]
When setting the language of any container to Spanish; I proceed to install any application, for example GIMP, when launched from the container it starts in Spanish but when it is integrated into the host's applications menu with the command distrobox-export --app it always starts in English, even though the host is also configured in Spanish.

I have verified this, using different containers Fedora, Arch Gentoo, Ubuntu running on hosts like Debian 12 or Deepin OS and the same thing always happens.

https://github.com/89luca89/distrobox/assets/137560000/fe7904e5-af2a-4699-8ca5-35c2430b27a2

**Comment by 89luca89** [comment]
This is related to #797 
A login shell is needed to source the host's lang settings

Duplicate
