### ISSUE TITLE
[Error] Archlinux container with additional packages reinstalls all basic packages in every restart

### ISSUE THREAD

**Issue by Lin-Junhao** [89luca89/distrobox#826]
**Describe the bug**
I created an Archlinux container with init system support using this command:

```
$ distrobox create --image archlinux:latest --name distrobox-archlinux --additional-packages "systemd" --init
```

I notice that during every restart, it reinstalls all basic packages along with systemd. Also it fails to launch if there is no internet connection. Since Archlinux image has systemd built-in, I tried creating another container without `--additional-packages "systemd"` and it behaves normal.

**To Reproduce**
On the host machine:
```
$ distrobox stop distrobox-archlinux
$ distrobox enter distrobox-archlinux
```
It spent a long time on "Installing basic packages...".

**Expected behavior**
Distrobox should detect dependencies correctly and that the container has done setting up, launches the container without reinstalling packages.

**Logs**
https://0x0.st/HQEw.log

**Desktop**
- Host OS: SteamOS 3.4.8
- Container OS: Arch Linux
- Podman version: 4.5.1
- Distrobox version: 1.5.0.2

**Comment by Lin-Junhao** [comment]
I've updated my log file to only include a single restart.

https://github.com/89luca89/distrobox/blob/55052318202388ac17886f4e8cc12ed93d13ae0d/distrobox-init#L330-L336

@LukeShortCloud What do think of the conditions here? I believe if any of these conditions are met it will trigger the upgrade? But in a restart the container should have had all these dependencies and `/run/.containersetupdone` file as well. I don't know what went wrong, here are the corresponding logs:

<details open>
<summary>$ podman logs distrobox-archlinux</summary>

```
+ '[' 0 -ne 0 ']'
+ command -v find
/usr/sbin/find
+ command -v mount
/usr/sbin/mount
+ command -v passwd
/usr/sbin/passwd
+ command -v sudo
/usr/sbin/sudo
+ command -v useradd
/usr/sbin/useradd
+ command -v diff
/usr/sbin/diff
+ command -v pinentry
/usr/sbin/pinentry
+ command -v wget
/usr/sbin/wget
+ command -v curl
/usr/sbin/curl
+ command -v less
/usr/sbin/less
+ command -v bc
/usr/sbin/bc
time
+ command -v time
+ command -v lsof
/usr/sbin/lsof
+ command -v bash
/usr/sbin/bash
+ '[' -n ' systemd' ']'
+ '[' '!' -e /run/.containersetupdone ']'
```
</details>

**Comment by LukeShortCloud** [comment]
All of the commands appear to be found. The last bit of logic ``|| { [ -n "${container_additional_packages}" ] && [ ! -e /run/.containersetupdone ]; }`` basically says if (1) the $container_additional_packages variable has a non-zero length and if (2) the container was not setup already, then run `distrobox init --upgrade`. I don't believe that is happening.

I opened a PR to address all of the issues I could find relating to the Arch Linux container being slow which include:
- Old behavior: Pacman repository cache is updated on every `pacman` command that Distrobox runs.
    - New/PR behavior: It now only updates the cache once.
- Pacman does an upgrade every time (it is hardcoded into the "pacman" helper scripts).
    - New/PR behavior: Now it only does that if `distrobox init --upgrade` is explicitly run (or one of those conditions you pointed out are met).
- Pacman will re-install additional packages. In our case, `systemd` would get re-installed every time.
    - New/PR behavior: `pacman -S --needed` is used to avoid re-installing packages.
