### ISSUE TITLE
[Error] Changing disk size externally can affect a distrobox container to throw RLIMIT_NOFILE

### ISSUE THREAD

**Issue by dkvc** [89luca89/distrobox#827]
Please, before opening a bug:

- [x] make sure you've read the documentation.
- [x] Ensure there isn't already an open issue about this.
- [x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Changing the disk size of home/root partition might affect distrobox to throw a
```
Error: unable to start container <container-id>: crun: setrlimit `RLIMIT_NOFILE`: Operation not permitted: OCI permission denied
```
It is possible that changing the size of disk externally might affect SELinux operation.

**To Reproduce**
Resize the disk of root/home partition using GParted Live or any other live distribution.

**Expected behavior**
The container should start (distrobox enter) without any issues.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
[distrobox_enter_log.txt](https://github.com/89luca89/distrobox/files/11895102/distrobox_enter_log.txt)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[podman_logs.txt](https://github.com/89luca89/distrobox/files/11895129/podman_logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? **(Podman)**
 - Which version or podman or docker? **(4.5.1)**
 - Which version of distrobox? **(1.4.2.1)**
 - Which linux distribution are you using? **(Fedora 38 Workstation - GNOME 44.1 with SELinux set to default (enforcing))**

**Additional context**

**Comment by J3RN** [comment]
If I had to guess, I'd guess that the limits changed.  i.e. if you compare the output of `cat /proc/self/limits | grep open files` (limit on open files on the host) with `podman inspect <container-id> --format '{{ .HostConfig.Ulimits }}'` (what the container tries to set the limits to), you will find that they differ.

**Comment by 89luca89** [comment]
This has nothing to do with distrobox
Distrobox does nothing special with disks or such, so it is a podman problem

Workaround is cloning the container
