### ISSUE TITLE
[Suggestion] Add environment variable to container containing container name

### ISSUE THREAD

**Issue by henriquekirchheck** [89luca89/distrobox#832]
**Is your feature request related to a problem? Please describe.**
Recently I got a laptop and decided to install Fedora Workstation for extra stability over Arch Linux and was supposed to use distrobox as a dev environment. I wanted to use the same `.zshrc` for both, but the location of the zsh plugins changed in-between systems (something like `/usr/share/zsh-plugin/zsh-plugin.zsh` instead of `/usr/share/zsh/plugins/zsh-plugin/zsh-plugin.zsh`).

**Describe the solution you'd like**
I think a environment variable like `DBOX_NAME` or `DBOX_CONTAINER_NAME` that would have the name of the container would be a good way to differentiate not only between the host system and the container, but between multiple different containers. It could be behind a `distrobox-enter` flag so a container may not be easily identifiable by default or, if the privacy is not that big of a problem, it could be added a flag to deactivate this behaviour 

**Describe alternatives you've considered**
- A executable in a standard location could be added in every distrobox container that will output the container name to stdout.
- A file in a standard location that contains the name of the container added in every distrobox container that can be easily read.

The problem with these solutions are that changes in the container name or obfuscation of the name would be more difficult.

**Comment by misobarisic** [comment]
`$container_id` environment variable which matches container's name already exists

**Comment by henriquekirchheck** [comment]
> `$container_id` environment variable which matches container's name already exists

Doesn't seen to work on podman, only `container` variable defined which does not demonstrate the name of the container
