### ISSUE TITLE
[Error] Init error when trying to install yay-bin using init and pre-init hooks in arch

### ISSUE THREAD

**Issue by RashiqAzhan** [89luca89/distrobox#835]
**Describe the bug**
Unable to install yay to access AUR packages as hooks run `makepkg -si` as root.

**To Reproduce**
Run `distrobox assemble create --file foo-distrobox.ini`
Contents of `foo-distrobox.ini`.
```ini
[foo-distrobox-archlinux]
image=quay.io/toolbx-images/archlinux-toolbox:latest
pull=true
replace=true
start_now=true
additional_packages=vscodium-bin
additional_packages=tectonic
init_hooks=pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
init_hooks=ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker
home=/home/distrobox_homes/foo-distrobox-archlinux
```

**Expected behavior**
Be able to install packages from AUR.

**Logs**
Relevant section of the docker logs when running the command.
```
++ cd yay-bin
++ makepkg -si ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
+ '[' 10 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? docker
 - Which version or podman or docker? 24.0.2, build cb74dfcd85
 - Which version of distrobox? 1.5.0.2

**Additional context**
Since AUR can be an essential part of Archlinux, an easy way to install and use it the `.ini` files would be nice. Any other solution or fix to my process is greatly appreciated.

**Comment by 89luca89** [comment]
The init_hooks need a semicolon at the end of each one to concatenate them
This has been added to the documentation

**Comment by emmetoneillpdx** [comment]
I'm probably doing something wrong, but I had the same issue creating an Arch container with yay installation init hooks regardless of using semicolons or not. `makepkg` errors out complaining about being run as root, so I had to jump into the container and run it manually. :shrug:

**Comment by gaetan-puleo** [comment]
+1 @89luca89 it's not possible to install yay without makepkg complaining about using root

**Comment by gaetan-puleo** [comment]
is it possible to open the issue again?

**Comment by trailjeep** [comment]
```
[archtest]
image="docker.io/library/archlinux:latest"
additional_packages="base-devel git go zsh"
#exported_apps=""
#exported_bins=""
exported_bins_path="~/.local/bin"
init_hooks="wget https://github.com/Jguer/yay/releases/download/v12.2.0/yay_12.2.0_x86_64.tar.gz";
init_hooks="tar xzf yay_12.2.0_x86_64.tar.gz";
init_hooks="cp -a yay_12.2.0_x86_64/yay /usr/bin/";
init_hooks="cp -a yay_12.2.0_x86_64/yay /usr/sbin/";
init_hooks="rm -rf yay_12.2.0_x86_64.tar.gz yay_12.2.0_x86_64/";
#init_hooks="yay -S --needed --noconfirm dua-cli musikcube-bin";
pre_init_hooks=""
nvidia=false
pull=true
root=false
replace=true
start_now=true
home=""
volume=""
```
Can't get yay to autoinstall pkgs though.

**Comment by RashiqAzhan** [comment]
> The init_hooks need a semicolon at the end of each one to concatenate them This has been added to the documentation

`init_hooks=pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si;`

Is not working.

Still receiving `Executing init hooks...                          Error: An error occurred` on the terminal.

**Comment by marendowski** [comment]
Hi, to anyone still trying to install yay via `init_hooks`, here's my `distrobox.ini` that works:

```
init_hooks="export USER=<your_user>"
init_hooks="cd ~/Downloads"
init_hooks="git clone https://aur.archlinux.org/yay-bin.git"
init_hooks="sudo chown -R $USER:$USER yay-bin"
init_hooks="sudo chmod -R 777 yay-bin"
init_hooks="sudo -u $USER sh -c "cd yay-bin && makepkg -si --noconfirm""
init_hooks="rm -r yay-bin"
```

Cheers.

**Comment by gaetan-puleo** [comment]
777 is not a good solution

**Comment by marendowski** [comment]
> 777 is not a good solution

Yeah, I forgot about it because I was having a problem with permissions and left it there, it's deleting it after so it's a no biggie.
