### ISSUE TITLE
Assemble fails when there's already a container with a similar name

### ISSUE THREAD

**Issue by unit511** [89luca89/distrobox#838]
**Describe the bug**
`distrobox-assemble create --file something.ini` will fail if there's already a container that's name contains the new container's name separated by a dash.

The problem is likely caused by the `grep -qw container_name` command that checks for existing containers, as it considers dashes word separators and matches the old container's name. A possible workaround is to use underscores as word separators, as those are treated part of a word by `grep`.

**To Reproduce**
1. Create a container with a name that includes a dash, like "abc-xyz"
2. Attempt to create a container named "abc" using `distrobox-assemble`
3. The creation will fail with "abc already exists", even with replace enabled

**Expected behavior**
The new container should be created regardless of what other containers are named.

**Logs**
[distrobox-assemble.log](https://github.com/89luca89/distrobox/files/11956219/distrobox-assemble.log)

**Desktop**
distrobox 1.5.0.2

**Comment by Findarato** [comment]
having the same issue

```bash
 ~ ❯ distrobox assemble create --file ~/.config/distrobox/fedora.ini
 - Deleting fedora... 
Error: inspecting object: no such container fedora
Cannot find container fedora.
 - Creating fedora... 
fedora already exists

 ~ ❯ podman ps         
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```

I had a container not created by distrobox assemble named this. It does not have any issues with containers that assemble created.  I can create and recreate containers named something that assemble creates  eg. fedora-test

**Comment by 89luca89** [comment]
> having the same issue
> 
> ```shell
>  ~ ❯ distrobox assemble create --file ~/.config/distrobox/fedora.ini
>  - Deleting fedora... 
> Error: inspecting object: no such container fedora
> Cannot find container fedora.
>  - Creating fedora... 
> fedora already exists
> 
>  ~ ❯ podman ps         
> CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
> ```
> 
> I had a container not created by distrobox assemble named this. It does not have any issues with containers that assemble created. I can create and recreate containers named something that assemble creates eg. fedora-test

Well obviously podman cannot do 2 containers with the same name
If `fedora` is already done by an external non-distrobox resource, distrobox won't delete it
So this is not a bug
> Create a container with a name that includes a dash, like "abc-xyz"
> Attempt to create a container named "abc" using distrobox-assemble
> The creation will fail with "abc already exists", even with replace enabled

This is a bug instead :joy: 
I'll push a fix
