### ISSUE TITLE
[Error] Timezone isn't set correctly in new containers

### ISSUE THREAD

**Issue by CuBeRJAN** [89luca89/distrobox#839]
Upon creating a new container using the Tumbleweed image the timezone is incorrectly set to UTC, which doesn't align with the host system timezone.

Can be reproduced simply with ``distrobox create --name test --image tumbleweed``

``/etc/localtime`` is linked to the wrong timezone (UTC), deleting it and linking it manually solves the issue.

Peeking into the podman logs for the container this error appears repeatedly. 
```
diff: /run/host../usr/share/zoneinfo/Europe/Prague: No such file or directory
```

I do have a suspicion of what's going on...
```
/etc/localtime -> ../usr/share/zoneinfo/Europe/Prague
```
The host system localtime, for some reason, links the timezone with a relative path like so, which I think confuses distrobox. I suppose the solution would be to check for the relative path.

edit: forgot to mention, linking the host /etc/localtime to the absolute path fixes the issue

Using openSUSE Aeon, fully upgraded, distrobox 1.5.0-1.1, podman 4.5.1-1.3.

**Comment by luc14n0** [comment]
This seems to be fixed on an up to date **distrobox** (`1.5.0.2`). Someone already submitted an update to **openSUSE**'s **distrobox**. Once it gets accepted into **openSUSE:Factory**, soon it should be available in the next snapshot.

``` sh
test_tw% ls -l /run/host/etc/localtime
lrwxrwxrwx 1 65534 65534 39 Jul  5 17:53 /run/host/etc/localtime -> ../usr/share/zoneinfo/America/Sao_Paulo
test_tw% date
Wed Jul  5 09:48:22 PM -03 2023
test_tw% exit

❯ ls -l /etc/localtime
lrwxrwxrwx 1 root root 39 Jul  5 17:53 /etc/localtime -> ../usr/share/zoneinfo/America/Sao_Paulo
❯ date
Wed Jul  5 09:48:28 PM -03 2023
```

**Comment by kavishgr** [comment]
same thing on fedora-toolbox 38 image:

`diff: /run/host../usr/share/zoneinfo/Indian/Mauritius: No such file or directory
diff: /run/host../run/systemd/resolve/stub-resolv.conf: No such file or directory`

**Comment by awesomekyle** [comment]
Toolbx sets it up correctly: 

```
$ ls -ls /etc/localtime 
4 lrwxrwxrwx. 1 root root 23 Jul 10 10:05 /etc/localtime -> /run/host/etc/localtime
```

Is there a reason Distrobox couldn't create the same symbolic link?

**Comment by luc14n0** [comment]
> Distrobox version:
> 
> ```
> ❯ distrobox version
> distrobox: 1.5.0
> ```

And distrobox is already on version `1.5.0.2`, that should include the fix for this issue.

**Comment by kavishgr** [comment]
> > Distrobox version:
> > ```
> > ❯ distrobox version
> > distrobox: 1.5.0
> > ```
> 
> And distrobox is already on version `1.5.0.2`, that should include the fix for this issue.

I have the latest version of the app, which is currently 1.5.0.2, but the minor revision number '2' is not being displayed:

```
❯ date
Fri Jul 14 08:07:53 +04 2023

❯ curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local
 Checking dependencies...
 Downloading...
 Unpacking...
 Installation successful!
 Shell scripts are located in /var/home/core/.local/bin
 Manpages are located in /var/home/core/.local/share/man/man1

❯ distrobox version
distrobox: 1.5.0
```

**Comment by kavishgr** [comment]
> Toolbx sets it up correctly:
> 
> ```
> $ ls -ls /etc/localtime 
> 4 lrwxrwxrwx. 1 root root 23 Jul 10 10:05 /etc/localtime -> /run/host/etc/localtime
> ```
> 
> Is there a reason Distrobox couldn't create the same symbolic link?

Not in my box:

```sh
❯ ls -ls /etc/localtime
0 lrwxrwxrwx. 1 root root 29 Apr  9 10:21 /etc/localtime -> ../usr/share/zoneinfo/Etc/UTC
```

**Comment by CuBeRJAN** [comment]
Alright I think I can close now :)

**Comment by jake-herrmann** [comment]
I'm still seeing this behavior with `distrobox: 1.8.1.2` on Fedora 41 (Workstation Edition). After creating a container with:

```
distrobox create --name debian --init --image debian:latest --additional-packages "systemd libpam-systemd pipewire-audio-client-libraries" --home ~/distrobox-home-dirs/debian
```

The output of `date` showed UTC time and `/etc/localtime` was a link to `/usr/share/zoneinfo/UCT`. Deleting it and linking it to my local timezone fixed the issue.

Is this still expected behavior?

**Comment by plattrap** [comment]
When `--init` selected during create, then `localtime` is linked to `UCT`.
When it is not selected during create, then `localtime` is a bind mount to the host.

Host: OpenSuse 20260213
Distrobox: distrobox: 1.8.2.4

```bash
> distrobox create --image ubuntu --init ubuntu-localtime
> distrobox enter ubuntu-localtime
$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 23 Feb 17 01:37 /etc/localtime -> /usr/share/zoneinfo/UCT

> distrobox create --image ubuntu ubuntu-localtime
> distrobox enter ubuntu-localtime
$ findmnt /etc/localtime -o TARGET,SOURCE
TARGET         SOURCE
/etc/localtime /dev/nvme0n1p2[/@/.snapshots/19/snapshot/usr/share/zoneinfo/Pacific/Auckland]
```

Difference seems be deliberate?

```
$ journalctl --user --grep localtime
+ get_locked_mount_flags /run/host/etc/localtime
+ src=/run/host/etc/localtime
+ ls /run/host/etc/localtime
+ findmnt --noheadings --output OPTIONS --target /run/host/etc/localtime
+ mount_bind /run/host/etc/localtime /etc/localtime ro
+ source_dir=/run/host/etc/localtime
+ target_dir=/etc/localtime
+ [ -L /run/host/etc/localtime ]
+ init_readlink /run/host/etc/localtime
+ ls -l /run/host/etc/localtime
+ [ -e /etc/localtime ]
+ findmnt /etc/localtime
+ [ -L /etc/localtime ]
+ rm -f /etc/localtime
+ dirname /etc/localtime
+ touch /etc/localtime
+ mount --rbind -o ro /run/host/usr/share/zoneinfo/Pacific/Auckland /etc/localtime
        /etc/localtime
+ id=ubuntu-localtime
+ name=ubuntu-localtime
## No --init stops here, with --init continues and breaks the connection.
+ findmnt /etc/localtime
+ umount /etc/localtime
+ [ -f /etc/localtime ]
+ rm -f /etc/localtime
+ ln -sf /usr/share/zoneinfo/UCT /etc/localtime
```

**Comment by yatian-liu** [comment]
Also noticed this behavior today, boxes created with `--init` selected will use UTC timezone instead of host's timezone. Could this issue be reopened?

**Comment by CheckYourFax** [comment]
My distrobox with --init also constantly swaps back to "UCT".
