### ISSUE TITLE
[Suggestion] Set Exported binaries/executables within assemble file

### ISSUE THREAD

**Issue by stylerw** [89luca89/distrobox#842]
**The Problem**

Right now, there's not a particularly clear way to assemble a Distrobox and, at the time of creation, export a few relevant packages to the host system. I've tried with init-hooks, as below, but it doesn't seem to work as expected ('Error: An error occurred') and it doesn't make sense to run these commands every time the box starts, anyways:

```
[md]
image=fedora:latest
additional_packages="ansible lynx chromium neofetch"
init_hooks="distrobox-export --app chromium"
init_hooks="distrobox-export --bin /usr/bin/lynx --export-path $HOME/Documents/bin/distrobin"
```

Particularly for those who are using distrobox to declaratively set up part of their environment (e.g. within an immutable OS, or across multiple machines), the inability to do this without running a second script (e.g. running an ansible playbook within the distrobox which includes an export step or a shell script to export) is frustrating.

**Proposal**

I'd like to see syntax which, at the time of the assembly, specifies which of the additional packages get exported and how.  Something like:

```
[md]
image=fedora:latest
additional_packages="ansible lynx chromium neofetch cmus"
export="app chromium"
export="bin /usr/bin/lynx --export-path $HOME/Documents/bin/distrobin"
export="bin /usr/bin/cmus --export-path $HOME/Documents/bin/distrobin"
```

**Describe alternatives you've considered**

I've not been able to find a way to do this as a part of init or pre-init hooks ('Error: An error occurred') when running the code, and have had no luck with ansible playbooks as an init-hook (which is another way to accomplish this). Another approach would be to make a more general assemble.ini command like "first-run-ever" which contains code like this which would run once on first init, but nevermore. 

Thank you!

**Comment by awesomekyle** [comment]
If you look at the logs with `podman logs containername`, you'll see the error:

```
...
distrobox: Executing init hooks...
+ printf 'distrobox: Executing init hooks...\n'
+ eval distrobox-export -a slack
++ distrobox-export -a google-chrome
You must not run  distrobox-export as root!
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```

I then tried running export as a different user and got a different error:

```
...
distrobox: Executing init hooks...
+ printf 'distrobox: Executing init hooks...\n'
+ eval sudo -u kyle distrobox-export -a slack
++ sudo -u kyle distrobox-export -a slack
/usr/bin/distrobox-export: line 208: CONTAINER_ID: unbound variable
Error: An error occurred
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

This is a feature I really want. When I destroy and recreate my container I'd love for it to automatically export apps so I don't have to remember to manually do it.

**Comment by TheTaylorHicks** [comment]
I've been having some luck using the following workaround:

```
# Assuming that your container is named "md" and you're exporting chromium
init_hooks=sudo -u $USER CONTAINER_ID=md distrobox-export --app chromium
```

My best guess is that this is a bug caused by an interaction between a `set -o nounset` on [line 156 of distrobox-assemble](https://github.com/89luca89/distrobox/blob/main/distrobox-export#L163) and `if [ -n "${CONTAINER_ID}" ]` on [line 208 of distrobox-export](https://github.com/89luca89/distrobox/blob/40fdc93ff1b5a450abbccdb8503fdc8bd63bd449/distrobox-export#L208) that causes the script to exit with an error code due to the unset variable `CONTAINER_ID`.

I'll work on a PR to fix this, but it might take a while as I don't have a development environment to test this on.

**Comment by 89luca89** [comment]
Yep the CONTAINER_ID thing has been solved now

But I really dig the idea of setting up the exports in the assemble phase
Also because, `rm` will automatically un-export stuff, so the process of `create/remove` should not leave orphan exports :+1:

**Comment by Nitrousoxide** [comment]
Yeah, setting up exports for an assemble would be amazing.  You could spin up a new system, install Distrobox and clone your assemble.ini file and bam, have all the non-flatpak applications you need installed in a few minutes replicably.

**Comment by 89luca89** [comment]
This has now been implemented! Thanks for the idea!

**Comment by Nitrousoxide** [comment]
@89luca89 
in:
/distrobox-assemble.md

exported_apps
exported_bins

should also get listed in this grid for flags too rather than just show up in the example at the bottom:
Available options

**Comment by 89luca89** [comment]
apps don't take input
bins take just the path, which is specified in another flag

**Comment by 89luca89** [comment]
ah yes sorry I understand now what you're referring to :+1: adding to the table

**Comment by stylerw** [comment]
Thanks so much for this, I look forward to fully declarative exporting in the next release.
