### ISSUE TITLE
Ubuntu 22.04 Container Won't Update [Error]

### ISSUE THREAD

**Issue by h4kon** [89luca89/distrobox#846]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
After creating the ubuntu 22.04 container when trying to update it doesn't work.

**To Reproduce**
1 - distrobox create --image ubuntu:22.04
2 - distrobox enter ubuntu-22-04
3 - try to update with sudo apt update && sudo apt upgrade
4 - returns:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Could not resolve 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

and 

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libc/libcap2/libcap2_2.44-1ubuntu0.22.04.1_amd64.deb  Could not resolve 'archive.ubuntu.com'
E: Problem executing scripts DPkg::Post-Invoke 'if [ -e /run/host//etc/localtime ] || [ -e /run/host/$(readlink -fm /run/host//etc/localtime) ]; then mount --rbind $(readlink -fm /run/host//etc/localtime) /etc/localtime 2>/dev/null || mount --rbind /run/host/$(readlink -fm /run/host//etc/localtime) /etc/localtime; fi'
E: Sub-process returned an error code

5 - after that I tried to run sudo apt update && sudo apt upgrade --fix-missing. Return: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libc/libcap2/libcap2_2.44-1ubuntu0.22.04.1_amd64.deb  Could not resolve 'archive.ubuntu.com'
E: Problem executing scripts DPkg::Post-Invoke 'if [ -e /run/host//etc/localtime ] || [ -e /run/host/$(readlink -fm /run/host//etc/localtime) ]; then mount --rbind $(readlink -fm /run/host//etc/localtime) /etc/localtime 2>/dev/null || mount --rbind /run/host/$(readlink -fm /run/host//etc/localtime) /etc/localtime; fi'
E: Sub-process returned an error code

**Expected behavior**
update the container with ubuntu

**Desktop (please complete the following information):**
 - Are you using podman or docker? 
 podman
 
- Which version or podman or docker? 
 podman version 4.5.1

 - Which version of distrobox?
distrobox: 1.5.0

**Comment by jeffteixeira** [comment]
I tested with the fedora repository package (version 1.5.0.2) and didn't have this problem, but I did with the master branch version.

**Comment by h4kon** [comment]
@jeffteixeira Yeap, I forgot to mention this factor, my version was downloaded from github which would be the master.

**Comment by john-ghatas** [comment]
What method was used to install it from the master, the cur method or manually cloning it?

If you used the curl method you will likely have the 1.5.0 version installed instead of the 1.5.0.2 version installed.

**Comment by john-ghatas** [comment]
I ran the reproduction steps and it went just fine

![image](https://github.com/89luca89/distrobox/assets/14125058/983ea155-2093-458f-96cc-a4a94f619ee3)


Version check (running off the Fedora repo version)
```
> distrobox version
distrobox: 1.5.0.2

```

**Comment by jeffteixeira** [comment]
> What method was used to install it from the master, the cur method or manually cloning it?
> 
> If you used the curl method you will likely have the 1.5.0 version installed instead of the 1.5.0.2 version installed where this is fixed.
> 
> Can you confirm your distrobox version?

curl method (1.5.0 version)

**Comment by 89luca89** [comment]
I've fixed the installation script (curl method) to install the correct latest version which has this already fixed :+1:
