### ISSUE TITLE
[Error] Problem entering container with login shell set to Elvish

### ISSUE THREAD

**Issue by vendion** [89luca89/distrobox#847]
**Describe the bug**
When a new container is created while the login shell for the host system is set to be [Elvish](https://github.com/elves/elvish) I can create the container just fine but `distrobox enter <name>` fails.

**To Reproduce**
1. Install and run Elvish on host system
2. Create new container via distrobox
3. Try and `distrobox enter` newly created container

**Expected behavior**
Running `distrobox enter <name>` with no other arguments fails like so:

```
vendion on Vili ~ took 10m12s
✦ ➜ distrobox enter arch
flag provided but not defined: -l
Usage: elvish [flags] [script] [args]
Supported flags:
  -buildinfo
    	Output information about the Elvish build and quit
  -c	Treat the first argument as code to execute
  -compileonly
    	Parse and compile Elvish code without executing it
  -daemon
    	[internal flag] Run the storage daemon instead of an Elvish shell
  -db string
    	[internal flag] Path to the database file
  -deprecation-level int
    	Show warnings for all features deprecated as of version 0.X (default 19)
  -help
    	Show usage help and quit
  -i	A no-op flag, introduced for POSIX compatibility
  -json
    	Show the output from -buildinfo, -compileonly or -version in JSON
  -log string
    	Path to a file to write debug logs
  -lsp
    	Run the builtin language server
  -norc
    	Don't read the RC file when running interactively
  -rc string
    	Path to the RC file when running interactively
  -sock string
    	[internal flag] Path to the daemon's Unix socket
  -version
    	Output the Elvish version and quit
Exception: distrobox exited with 2
[tty 51]:1:1: distrobox enter arch

```

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
[distrobox.log](https://github.com/89luca89/distrobox/files/11994622/distrobox.log)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[podman.log](https://github.com/89luca89/distrobox/files/11994626/podman.log)

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? podman version 4.5.1
 - Which version of distrobox? distrobox version: 1.5.0.2

**Additional context**
Entering the container and manually calling `elvish` works though:

```
vendion on Vili ~ took 7ms
✦ ✗ distrobox enter arch -- /usr/bin/elvish

vendion on arch ~ took 195ms
✦ ⬢ [archlinux:latest] ➜
```

**Comment by 89luca89** [comment]
Distrobox uses the `-l` flag to do a login shell
If elvish is not a posix shell supporting `-l` you need to expressly specify the command (as you already did)

This is not a distrobox bug for me
