### ISSUE TITLE
[Error] Pipe in assemble init-hook doesn't work

### ISSUE THREAD

**Issue by ZofiaZementa** [89luca89/distrobox#853]
**Describe the bug**
When using a pipe in the `init_hooks="..."` directive in the assemble ini file it gets converted (as far as i can tell) to a `&&`.
This is not the case when using `distrobox create`

**To Reproduce**
The following init file will try to install rustup, but due to the bug it will just print out the install script:
```
[rust]
image=fedora:39
init_hooks='curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
```

**Expected behavior**
The command should not convert the pipe to `&&`, it should work just like with `distrobox create`

**Logs**
[`distrobox asemble` log](https://github.com/89luca89/distrobox/files/12026809/assemble2.log)
[`distrobox enter` log](https://github.com/89luca89/distrobox/files/12026816/enter2.log)
[podman log](https://github.com/89luca89/distrobox/files/12026710/podman.log)

**Desktop:**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.5.0
 - Which version of distrobox? 1.5.0.2
 
 **Additional info**
 Might be related to #845, not sure

**Comment by fbartels** [comment]
Yes, I have run into the issue with the pipe symbol in the init file as well. In the end I solved this by using my own container image which had the stuff I wanted to install via `init_hooks` already installed. Additional benefit is that by already preinstalling the packages distrobox installed during "Installing basic packages..." the first startup time was heavily reduced.

**Comment by ZofiaZementa** [comment]
Yeah I thought about that as well but that then kindof defeats the point of the assemble command a bit

**Comment by 89luca89** [comment]
Hi all, I've pushed a fix for this, now pipes are supported
