### ISSUE TITLE
[Error] --home incompatible with distrobox-export

### ISSUE THREAD

**Issue by ximGBu4cyQss5P** [89luca89/distrobox#86]
First of all, thanks a truck load for adding the new --home option for distrobox-create.  On the off chance that I want to export something from a container where I set a custom $HOME using --home, I'm running into the following error.

`
[foo@arch2 foo]$ distrobox-export --app featherpad
mkdir: cannot create directory ‘/run/host//home/foo/Containers/arch2/.local/share/applications’: Permission denied
`

**Comment by 89luca89** [comment]
Hi @ximGBu4cyQss5P 

I see the problem, the export is using HOME as variable, but obviously while using a custom home, we cannot rely on that.

I'll mark this as a bug and will investigate a way to make export work with custom homes

**Comment by 89luca89** [comment]
@ximGBu4cyQss5P I've opened a PR with a possible fix, a quick test from me confirmed it works but better have a second pair of eyes on it.

To make it work you'll need to recreate the container after upgrading distrobox
you can use `--clone` to preserve the current container setup

**Comment by renato-dl** [comment]
I encountered the same problem earlier and can confirm that the version from the PR branch exports apps successfully.
When the exported app is executed, though, it uses the host's home directory. Is this normal? Doesn't it defeat the purpose of specifying another directory for the container?

**Comment by 89luca89** [comment]
For now the `--home` flag aims to have a different $HOME, but does not deny the mount of host's home inside the container.
This is more for having per-container dotfiles, or avoiding littering the home with temp files or whatnot, it's not about isolation and security

For that there is another issue open #28 but I've not started working on that yet

**Comment by renato-dl** [comment]
But when the app is exported, $HOME becomes the one from the host, so it gets littered anyway right?
I guess that, until we have #28, it does not make much sense to use both the features (export and separate home), at least in my opinion.

Thanks again

**Comment by 89luca89** [comment]
> But when the app is exported, $HOME becomes the one from the host, so it gets littered anyway right? I guess that, until we have #28, it does not make much sense to use both the features (export and separate home), at least in my opinion.
> 
> Thanks again

Not really, the app will have access to hosts home (for example, a libreoffice or gnumeric app can still open the files in your document's directory), but cache temp and dotfiles will go to your defined home; so for example firefox and chrome profiles or cargo stuff or golang packages with go get, or pip packages

**Comment by renato-dl** [comment]
Then I must have done something wrong, because my brief tests have shown otherwise. Meaning, I got the behaviour you describe only if I ran the application from the container shell, but not from the exported entry in the host application launcher.
I will test again tomorrow with a new container and report back.

**Comment by 89luca89** [comment]
Ok let me know how/what you used so I can try to reproduce, feel free to reopen this very issue in case

**Comment by renato-dl** [comment]
The test I made earlier was with audacity installed in the container from fedora repos.
Tomorrow I will test again, also with other applications.

**Comment by renato-dl** [comment]
I can confirm that you are right and it was my bad.
I think the problem was that I didn't specify the `--home` flag again when cloning, only at the original creation of the container.
In any case, with a fresh container the exported app sees the container's home as its home, but it can access the host's home if needed.

Great job and sorry for this misunderstanding on my part.

**Comment by 89luca89** [comment]
Cool absolutely no problem :-) cheers
