### ISSUE TITLE
[Error] Inappropriate ioctl for device when piping input into exported distrobox fzf binary

### ISSUE THREAD

**Issue by shaun-mathew** [89luca89/distrobox#863]
**Describe the bug**

Attempting to use the fzf binary exported from a container using distrobox-export results in the error "inappropriate ioctl for device" when piping input. Within the container there is no issue. Also, running fzf normally without piped input works fine.

**To Reproduce**
1. Set up archlinux container using quay.io archlinux-toolbox image
2. Install fzf via pacman
3. Export fzf to host using distrobox-export --bin $(which fzf)
4. Exit container and execute following steps in host
5. Run command that pipes input into fzf, e.g. ```ls -la | fzf```.
6. The following error is returned: "inappropriate ioctl for device"

**Expected behavior**

Error does not occur and piped input can be processed by fzf like it does within the container.

**Logs**
Unsure how to check this with exported binary

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.5.1
 - Which version of distrobox? distrobox 1.5.0.2

**Additional context**

Using fish shell in both the container and host
Running fedora silverblue
```ls -la | fzf``` works fine when executed within container
Error also appears to occur on toolbox when running the following command:
```ls -la | toolbox run --container fedora-toolbox-38 fzf```

**Comment by shaun-mathew** [comment]
Some more information:

Looking around about the error, it appears to be some issue related to the shell being non-interactive (See https://stackoverflow.com/questions/34368532/i-get-inappropriate-ioctl-for-device-in-pycharm-but-not-the-normal-shell), which is quite bizarre since it works as expected when typing fzf. Moreover, when I try the command ```ls | fzf --filter query_string```, the results are correctly filtered, but no prompt appears which is the expected behaviour. There seems to be some strange behaviour with piping inputs into exported binaries that invoke an interactive shell.

**Comment by shaun-mathew** [comment]
Never mind, it appears that the exec command that is used by the file that is exported my distrobox cannot be used in a pipeline. I'll leave the issue open if someone has a solution to this.

**Comment by 89luca89** [comment]
If distrobox is called in a non-tty context (example, in a pipe) it won't allocate a tty

While inside a `distrobox enter` shell, the tty is instantiated and fzf works correctly

This is more of a problem of fzf I think, because for example, `jq` and `grep` and `less` works correctly when using exported binaries, or pipes with `distrobox-enter`

**Comment by einarpersson** [comment]
What is the solution?
