### ISSUE TITLE
[Suggestion] Copy host terminfo into the container if it does not match

### ISSUE THREAD

**Issue by sandorex** [89luca89/distrobox#864]
**Is your feature request related to a problem? Please describe.**

Using a terminal (for example kitty) on a LTS distribution like debian 12 gives you older version which then causes problems with containers as in the container the version of the terminfo is different and things can get weird

**Describe the solution you'd like**

Copy the host terminfo into the container
In case the container already has terminfo of the same name compare them and if they dont match copy the host terminfo but rename it to something else and change TERM variable

**Describe alternatives you've considered**

**Additional context**

Debian 12 has kitty version `0.26.5` but fedora-toolbox has `0.28.1` and they have changed some key codes
One of which is `kUP5` which is code for `Ctrl+Up` (`tput kUP5 | cat -A`)

**Comment by 89luca89** [comment]
This has been fixed by PR #1194
