### ISSUE TITLE
[Error] Networking not working in podman with toolbox images

### ISSUE THREAD

**Issue by FergusFettes** [89luca89/distrobox#866]
When using distrobox to create images using podman, there is no network connection inside the image.

Toolbox works. (I originally made an issue here: https://github.com/toolbx-images/images/issues/89 but on more testing I found out it was actually a distrobox issue).

- toolbox create --image quay.io/toolbx-images/alpine-toolbox:edge
- toolbox enter alpine-toolbox-edge
- ping google.com                                                                   <= works!
- distrobox create -i ghcr.io/ublue-os/boxkit -n boxkit              <= using the base alpine image doesn't work, but this is built on the same image
- distrobox enter boxkit
- ping google.com                                                                   <= timeout

[logs.log](https://github.com/89luca89/distrobox/files/12064067/logs.log)

Expected networking to work.

 - Are you using podman or docker? podman
 - Which version or podman or docker? 3.4.4
 - Which version of distrobox? 1.5.0

I first noticed this when trying to use podman/distrobox in a gcloud instance, so I don't think it's just on my local machine.

Docker works fine. Other images also work fine, aka
```
distrobox create -i ubuntu:20.04
```
so I think its something specific about the toolbox images.

**Comment by FergusFettes** [comment]
I tested this with a bunch of different images, and its only the ones from toolbox that don't have a network connection, and only when running in podman.

**Comment by 89luca89** [comment]
I've tested all the images, and they work as expected, please be sure to be on latest version (1.5.0.2) as probably some of the fixes were implemented in the minor releases
