### ISSUE TITLE
[Suggestion] Hooks to run commands on container creation

### ISSUE THREAD

**Issue by TheBicPen** [89luca89/distrobox#867]
**Is your feature request related to a problem? Please describe.**
I have a container with commands I want to run when I build the container before the package manager runs, when I build the container after the package manager runs, and commands that run when I enter the container. Basically, I want to install dependencies and build a project when creating the container, and source a script when I enter the container so that the project can run correctly.

**Describe the solution you'd like**
Clearer documentation on when init_hooks, pre_init_hooks run, and possibly a new build_hook or something similar. That way, I don't need to run the build manually when I enter the container for the first time. Similar to the way that Dockerfile RUN commands execute when building the container.

**Describe alternatives you've considered**
- Running the build manually when I enter the container for the first time.
- Writing the setup script in such a way that it detects an existing build and aborts if one is found.

**Additional context**
Here's the distrobox.ini I am using. The commented-out init_hooks (and all the pre_init_hooks) are part of the build script that I want to run once, on container creation. 
```
[kdenlive]
image="ubuntu:22.04"
additional_packages="build-essential git cmake extra-cmake-modules libsm-dev"
additional_packages="libkf5archive-dev libkf5bookmarks-dev libkf5coreaddons-dev libkf5config-dev libkf5configwidgets-dev libkf5dbusaddons-dev libkf5kio-dev"
additional_packages="libkf5widgetsaddons-dev libkf5notifyconfig-dev libkf5newstuff-dev libkf5xmlgui-dev libkf5declarative-dev libkf5notifications-dev libkf5guiaddons-dev"
additional_packages="libkf5textwidgets-dev libkf5purpose-dev libkf5iconthemes-dev libkf5crash-dev libkf5filemetadata-dev libkf5codecs-dev kio kinit qtdeclarative5-dev"
additional_packages="libqt5svg5-dev qml-module-qtquick-controls libqt5networkauth5-dev qtmultimedia5-dev qtquickcontrols2-5-dev qttools5-dev breeze-icon-theme breeze"
additional_packages="frei0r-plugins ffmpeg"
additional_packages="libmlt++-dev libmlt-dev melt"
# init_hooks="git clone https://invent.kde.org/multimedia/kdenlive.git;"
# init_hooks="cd kdenlive;"
# init_hooks="mkdir -p build && cd build;"
# init_hooks="cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="" -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DRELEASE_BUILD=OFF;"
# init_hooks="make -j20;"
# init_hooks="make install;"
init_hooks=". prefix.sh;"
pre_init_hooks="apt update;"
pre_init_hooks="apt install -y software-properties-common;"
pre_init_hooks="add-apt-repository ppa:kdenlive/kdenlive-master;"
pre_init_hooks="apt update;"
start_now=true
```

**Comment by kekkoudesu** [comment]
I want to do something similar; configure some webserver modules and start up some other services. `init_hooks` don't appear to work for that.

**Comment by xz-dev** [comment]
I have plan to add `build dockerfile` function at [distrobox-boost](https://github.com/xz-dev/distrobox-boost).

**Comment by kekkoudesu** [comment]
> I think in this situation it's better to either mount a script and execute it for these type of situations
> 
> Or build a custom image

This is something I'm going to look into soon—but not super soon. I see Distrobox has some documentation on loading custom images: https://distrobox.privatedns.org/useful_tips/#container-save-and-restore

I have my own Dockerfiles I want to use that aren't uploaded to any registries, so presumably I could create a container from them, save them to an image archive, save them with a particular tag, and use Distrobox to create a container with that tag.

I have a Docker Compose setup, and I don't want full integration with my home directory, instead taking advantage of Volumes so I can run webserver files in a particular folder in my home directory without setting the group execution bit on my home folder. So I probably won't end up using Distrobox to set up _this_ development environment. But I thought I'd ask those questions in case I do need Distrobox one day for its home directory integration features.
