### ISSUE TITLE
[Error] Providing 2 mount entries in distrobox.ini results in "invalid reference format" error

### ISSUE THREAD

**Issue by kees-closed** [89luca89/distrobox#868]
**Describe the bug**
When providing 2 volumes in my distrobox.ini file I get the error:

```
$ distrobox assemble create --verbose --replace --file distrobox.ini 
...
DEBU[0000] Successfully loaded 1 networks               
DEBU[0000] Pulling image /usr/local/bin:/home/kjong/bin (policy: missing) 
Error: invalid reference format
DEBU[0000] Shutting down engines                        
+ printf '\033[31m [ ERR ]\n\033[0m'
 [ ERR ]
+ '[' -n '' ']'
+ rm -f /tmp/tmp.cWYf3blhb2
```

Using one volume does work. Placing the 2 volumes on 2 separate lines doesn't result in an error, but only the last volume listed in the config is then mounted.

**To Reproduce**
Add the following in distrobox.ini, where USER is your home dir:
```
[tumbleweed]
image=registry.opensuse.org/opensuse/toolbox:latest
volume=/usr/local/sbin:/home/USER/sbin /usr/local/bin:/home/USER/bin
```

Then run `distrobox assemble create --verbose --replace --file distrobox.ini`

**Expected behavior**
I expect both volumes to be mounted, this config syntax also matches with what is in `man distrobox-assemble`
```
              [arch] # also inline comments are supported
              additional_packages=git vim tmux nodejs
              home=/tmp/home
              image=archlinux:latest
              init=false
              start_now=true
              init_hooks="touch /init-normal"
              nvidia=true
              pre_init_hooks="touch /pre-init"
              pull=true
              root=false
              replace=false
              volume=/tmp/test:/run/a /tmp/test:/run/b
```

It does work when I run it as a command: `distrobox-create --volume /usr/local/bin:/home/USER/bin --volume /usr/local/sbin:/home/USER/sbin tumbleweed test`, so I guess something with the parsing goes wrong.

The error doesn't happen when I use quotes: `volume="/usr/local/sbin:/home/USER/sbin" "/usr/local/bin:/home/USER/bin"`, however, then the mounts in my home dir are empty.

**Desktop (please complete the following information):**
Using Podman (podman-4.5.1-1.fc38.x86_64) with distrobox-1.5.0.2-1.fc38.noarch

**Comment by starquake** [comment]
I tried that and it actually didn't work. What did seem to work is:
`volume="/abc:/xyz" "/test/test2"`

It also looks like there is an error in the [example](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-assemble.md#examples) then.

Is there a way to get more information of what is wrong? Instead of "invalid reference format"?
