### ISSUE TITLE
[Error] Make distrobox-stop use default container name

### ISSUE THREAD

**Issue by ricardoseriani** [89luca89/distrobox#872]
**Describe the bug**
When running `distrobox stop` without a container name, it not works with the default container, and breaks the CLI.

**To Reproduce**
create a container with `distrobox create` without supplying a container name (it will use the default container name)
Try to stop the container with `distrobox stop` without supplying a container name

**Expected behavior**
distrobox stop should stop the default container name

**Logs**
```
distrobox stop --verbose
/home/ricardoseriani/.local/bin/distrobox-stop: 171: container_name: parameter not set
```

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 Docker
 - Which version or podman or docker?
docker-ce 24.0.4
 - Which version of distrobox?
 distrobox: 1.5.0.2

**Comment by 89luca89** [comment]
This has been fixed now
