### ISSUE TITLE
[Discussion] fish_config 403

### ISSUE THREAD

**Issue by jqhr** [89luca89/distrobox#877]
In container, I have installed fish shell.  
I want to config fish shell, but `fish_config` command open a web server to config. it means I need to use browser to visit this server so that cout config fish shell.
![image](https://github.com/89luca89/distrobox/assets/23305067/800fdb42-9fdd-444e-a752-eec11a45dd96)
![image](https://github.com/89luca89/distrobox/assets/23305067/9cb1cb8c-1678-4308-8b35-c324030babac)

**Comment by 89luca89** [comment]
As you see you can open the file in /tmp, which is shared between host and guest
So that's your answer :+1:
