### ISSUE TITLE
[Error] kitty-terminfo does not work for Arch root user

### ISSUE THREAD

**Issue by MakiseKurisu** [89luca89/distrobox#881]
**Describe the bug**

I use `kitty` as my terminal emulator, which requires additional terminfo to work. However, when the required package is installed, it only works with normal user, not the root user.

**To Reproduce**

Create archlinux-toolbox container, then:

```bash
sudo pacman -Syu kitty-terminfo
sudo nano
```

**Expected behavior**

Nano can open without `Error opening terminal: xterm-kitty.`

**Logs**

The provided instruction produced nothing interesting. I created this screen recording to show the problem, and can provide additional log upon request.

https://asciinema.org/a/XGddOem2jOP4QXrLLi2X1EX4k

**Desktop (please complete the following information):**
 - Are you using podman or docker?
   podman
 - Which version or podman or docker?
   4.5.0
 - Which version of distrobox?
   1.5.0.2

**Additional context**

I use NixOS 23.05 as my host.

Kitty works with debian-toolbox image under root with terminfo installed.

**Comment by luc14n0** [comment]
Hi there,

It would require more investigation, but it does sound like an issue with the image/**Arch Linux** or it could be an issue with the upstream terminfo db entry, not **distrobox**.

We can see that **Debian**'s [Kitty source tree](https://salsa.debian.org/debian/kitty/-/commits/debian/sid/terminfo) is quite out of date, compared with [upstream](https://github.com/kovidgoyal/kitty/commits/master/terminfo)'s.

**Comment by 89luca89** [comment]
This is a kitty-terminfo problem, not distrobox
