### ISSUE TITLE
[Error] /usr/sbin/apache2ctl: systemctl: not found

### ISSUE THREAD

**Issue by kekkoudesu** [89luca89/distrobox#884]
**Describe the bug**
This error occurs when attempting to start the `apache2` service in an Ubuntu 20.04 container created with `--root`:
```
$ sudo service apache2 start
```

```
 * Starting Apache httpd web server apache2                                                                                                                                                                          Invoking 'systemctl start apache2'.
Use 'systemctl status apache2' for more info.
/usr/sbin/apache2ctl: 171: /usr/sbin/apache2ctl: systemctl: not found
Action 'start' failed.
The Apache error log may have more information.
```

The offending segment of the `apache2ctl` script:

```
case "$ARGV" in
start)
    # ssl_scache shouldn't be here if we're just starting up.
    # (this is bad if there are several apache2 instances running)
    rm -f ${APACHE_RUN_DIR:-/var/run/apache2}/*ssl_scache*

    need_systemd=false
    if [ -z "$APACHE_STARTED_BY_SYSTEMD" ] ; then
        case "$(readlink -f /proc/1/exe)" in
        *systemd*)
            need_systemd=true
            ;;
        *)
            ;;
        esac
    fi
    if $need_systemd ; then
        # If running on systemd we should not start httpd without systemd
        # or systemd will get confused about the status of httpd.
        echo "Invoking 'systemctl start $APACHE_SYSTEMD_SERVICE'."
        echo "Use 'systemctl status $APACHE_SYSTEMD_SERVICE' for more info."
        systemctl start "$APACHE_SYSTEMD_SERVICE"
    else
        unset APACHE_STARTED_BY_SYSTEMD
        $HTTPD ${APACHE_ARGUMENTS} -k "$ARGV"
    fi

    ERROR=$?
    ;;
```

**To Reproduce**
Create an Ubuntu 20.04 rootful image with Apache2 installed:

```
distrobox create --root --image ubuntu:20.04 --additional-packages "apache2" --name ubuntu-rootful-apache
```

Attempt to start Apache:

```
sudo service apache2 start
```

**Expected behavior**
It should realize this container only works with Sys V instead of Systemd.

**Workaround**

Change `need_systemd=true` to `need_systemd=false` (or just remove it altogether) in the `/usr/bin/apache2ctl` script and it will work fine.

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - Which version or podman or docker?
 - Which version of distrobox?

```
distrobox: 1.5.0.2
podman version 4.6.0
```

**Additional context**
I'm using a `--root` container because a rootless container doesn't have permission to create services on ports lower than 1024 (this appears to be the error, anyway):

```
* Starting Apache httpd web server apache2                                                                                                                                                                          (13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
```

`sudo ss -tunlp` in my host environment reveals no 80 or 443 ports being used by an existing process, so I'm pretty sure that's the reason. I *need* port 443 for my use case, so I can't use an alternative port. Although, come to think of it, maybe I should look into port remapping... any pointers on that?

**Comment by misobarisic** [comment]
Create a container with the `--init` flag.

**Comment by kekkoudesu** [comment]
> Create a container with the `--init` flag.

Thanks for your response! I also tried this, but had issues with that too! You can see my issues here: https://github.com/89luca89/distrobox/issues/820#issuecomment-1658014900

I actually think I had less trouble without the `--init` option, since I only had to change a single line in a bash script to get it to work.

**Comment by 89luca89** [comment]
Now that 820 is fixed, you can just use `--init` for this use case. So I'm closing this
