### ISSUE TITLE
A host command to run a terminal based application inside of the box without having to enter the box first. 

### ISSUE THREAD

**Issue by nick123456789025** [89luca89/distrobox#885]
**Is your feature request related to a problem? Please describe.**

I am trying to run two of the same application at the same time they need to run in separate environments because the two different versions of these applications still collide with each other. They both run perfectly fine in host and the distrobox but I have no way of running the start command without having to enter the distro box to run it. I need a simple command that will pass commands through to the box so I don't have to type distrobox enter (distro name) every time I want to launch this program I'm trying to launch it through a launcher so I don't have to fiddle around with it all of the time. This one simple feature could save me thousands of headaches. 

**Describe the solution you'd like**

A simple command that will do the opposite of the run on host command that passes commands from the box to host. I want to be able to run commands inside of the box in a one line command. (Syntax like distrobox --pass < COMMAND > )

**Describe alternatives you've considered**

Pass all distro box commands through to the host OS so that they appear as usable commands without having to enter the box similar to how you link graphical applications. This would allow the use of aliases on the box side to run the same command line utility that the host might have without having to enter the box every single time, you want to run a launch command for a program 

**Additional context**
Just for additional context, I am trying to run legendary which is a epic games replacement for Linux. Epic games notoriously refuses to allow easy switching of accounts or transfers of ownership of games I have two accounts with games on them. I want to link to a single library but I cannot be logged in to two accounts at the same time, at least on my host OS. If I run it inside of distro box, it allows me to have two accounts logged in on the same computer at the same time so I can access all of my games without having to fiddle with logging out and logging back in every single time I want to switch a game. Epic games support says that they have no plan to fix this issue. So I'm trying to find a workaround and this is the closest I have got. I have tried heroic launcher and the flatpak version at the same time but the configs conflict with each other corrupting both of the installations. If this one command would exist, it would solve my issue. If you cannot implement this and have any ideas of how to help, please let me know.

**Comment by xz-dev** [comment]
You can use my tool, [distrobox-boost](https://github.com/xz-dev/distrobox-boost), like simple run `distrobox-boost fish -c 'ls -la'`

**Comment by 89luca89** [comment]
`distrobox exec -- COMMAND` is a thing

Please refer to the documentation
