### ISSUE TITLE
Can't access container from .desktop file

### ISSUE THREAD

**Issue by Toni500github** [89luca89/distrobox#887]
Hi, I have installed an ArchLinux container with distrobox 1.5.0.2 (commit 40fdc93) using podman 4.5.1 without root (installed by the [install-podman](https://github.com/89luca89/distrobox/blob/main/extras/install-podman) script).

When I type `distrobox enter archlinux-nvidia` on any terminal, it works fine. However, if I try to access the container using the .dekstop file, it doesn't even open the terminal, so if i try to access the cointainer's apps that i exported with `distrobox-export` they won't launch unless i use the command line. 
If I modify the `Exec=/home/toni/.local/bin/distrobox enter archlinux-nvidia` line on the .desktop to `Exec=kitty -e '/home/toni/.local/bin/distrobox enter archlinux-nvidia'` it gives me the error 
```
Failed to launch child: /home/toni/.local/bin/distrobox enter archlinux-nvidia 
With error: No such file or directory
Press Enter to exit.
```
```
[~]$ ls -al ~/.local/bin/distrobox*
-rwxr-xr-x 1 toni toni  2155 lug 22 13:57 /home/toni/.local/bin/distrobox
-rwxr-xr-x 1 toni toni  9708 lug 22 13:57 /home/toni/.local/bin/distrobox-assemble
-rwxr-xr-x 1 toni toni 28434 lug 22 13:57 /home/toni/.local/bin/distrobox-create
-rwxr-xr-x 1 toni toni 18567 ago  2 00:30 /home/toni/.local/bin/distrobox-enter
-rwxr-xr-x 1 toni toni  5780 lug 22 13:57 /home/toni/.local/bin/distrobox-ephemeral
-rwxr-xr-x 1 toni toni 14683 lug 22 13:57 /home/toni/.local/bin/distrobox-export
-rwxr-xr-x 1 toni toni 10976 lug 22 13:57 /home/toni/.local/bin/distrobox-generate-entry
-rwxr-xr-x 1 toni toni  5524 lug 22 13:57 /home/toni/.local/bin/distrobox-host-exec
-rwxr-xr-x 1 toni toni 45539 lug 22 13:57 /home/toni/.local/bin/distrobox-init
-rwxr-xr-x 1 toni toni  7849 lug 22 13:57 /home/toni/.local/bin/distrobox-list
-rwxr-xr-x 1 toni toni 10787 lug 22 13:57 /home/toni/.local/bin/distrobox-rm
-rwxr-xr-x 1 toni toni  7576 lug 22 13:57 /home/toni/.local/bin/distrobox-stop
-rwxr-xr-x 1 toni toni  6724 lug 22 13:57 /home/toni/.local/bin/distrobox-upgrade

[~]$ cat ~/.local/share/applications/archlinux-nvidia.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Archlinux-nvidia
GenericName=Terminal entering Archlinux-nvidia
Comment=Terminal entering Archlinux-nvidia
Categories=Distrobox;System;Utility
Exec=/home/toni/.local/bin/distrobox enter archlinux-nvidia
Icon=/home/toni/.local/share/icons/distrobox/arch.png
Keywords=distrobox;
NoDisplay=false
Terminal=true
TryExec=/home/toni/.local/bin/distrobox
Type=Application
```
Edit:
I have tested on terminal `gnome-terminal -e "/home/toni/.local/bin/distrobox enter archlinux-nvidia --verbose"` and it worked [(log.txt)](https://github.com/89luca89/distrobox/files/12240447/log.txt) BUT only on command line. since the `-e` option it's deprecated, I tried the command `gnome-terminal -- "/home/toni/.local/bin/distrobox enter archlinux-nvidia --verbose"` but it gives me kinda the same error like on kitty.

I'm so sorry if bad english

**Comment by 89luca89** [comment]
You don't need to wrap everything with quotes

In my case

`gnome-terminal -- /home/luca-linux/.local/bin/distrobox enter distrobox-p9AXRNzcgR`

works and I think it will be the same for kitty

**Comment by Toni500github** [comment]
ok it indeed worked with kitty and gnome-terminal. But what i don't understand is:

I have a keybind on [DWM](https://dwm.suckless.org) that launches [rofi](https://github.com/davatorium/rofi) and then when i select the Arch container it's doesn't open up, but if I run `rofi -show drun` on the terminal and select the container it _magically_ works...

And it isn't really a rofi or dwm problem, because i tried with cinnamon and same thing, it doesn't open even if the container it's running in the background. I tried replacing the 
```desktop
Exec=/home/toni/.local/bin/distrobox enter archlinux-nvidia
```
to 
```desktop
Exec=/usr/bin/gnome-terminal -- /home/toni/.local/bin/distrobox enter archlinux-nvidia
```
but still doesn't open neither on rofi or cinnamon, only if i run rofi through the terminal, with or w/ configs

**Comment by 89luca89** [comment]
This may depend on variables that are only loaded in a login shell

If you nave PATH or other stuff in an rcfile, dmemu probably won't load those

Maybe checking the output of journalctl while launching from dmenu could clear this up

**Comment by Toni500github** [comment]
```
ago 04 20:30:01 Linuxmint CRON[78992]: pam_unix(cron:session): session opened for user root by (uid=0)
ago 04 20:30:01 Linuxmint CRON[78993]: (root) CMD ([ -x /etc/init.d/anacron ] && if [ ! -d /run/systemd/system ]; then /usr/sbin/invoke-rc.d anacron start >/dev/null; fi)
ago 04 20:30:01 Linuxmint CRON[78992]: pam_unix(cron:session): session closed for user root
```
this is what shows up on journalctl when i run on dmenu `rofi -show drun` and select the container
