### ISSUE TITLE
[Discussion] Does running a container with just one app in it (AnyDesk) affect performance on Steam Deck?

### ISSUE THREAD

**Issue by karasuhebi** [89luca89/distrobox#890]
And is the container running all the time? Or only when I launch AnyDesk?

**Comment by 89luca89** [comment]
Containers are running all the time, but they only take resources related to the app you're running in that moment
These are not VMs so if every app is closed from a container, only the `init` is running which just does a `sleep 15` 

So no resources you need to worry about :+1:

**Comment by karasuhebi** [comment]
Thanks for this! This was the best response I could've asked for, it answered everything I needed to know! Thanks again and keep up the great work!
