### ISSUE TITLE
Infinite loop in install script

### ISSUE THREAD

**Issue by mogoh** [89luca89/distrobox#891]
**To Reproduce**

Execute 

```sh
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh -s -- --next
```

as suggested in the README.md.
It will result in an infinite loop.

**Reason and fix**

This is the code for parsing arguments:

```sh
# Parse arguments
while :; do
	case $1 in
		-h | --help)
			# Call a "show_help" function to display a synopsis, then exit.
			show_help
			exit
			;;
		-v | --verbose)
			shift
			verbose=1
			;;
		-N | --next)
			if [ -n "$2" ]; then
				shift
				next=1
			fi
			;;
		-P | --prefix)
			if [ -n "$2" ]; then
				prefix="$2"
				shift
				shift
			fi
			;;
		*) # Default case: If no more options then break out of the loop.
			break ;;
	esac
done
```

In case of `-N | --next` there is not necessary a second argument present.
`$2` might be empty.
`shift` is never triggerd.
This results in an infinite loop.

**Fix**

Change `$2` into `$1` in line 56 should fix it.

**Comment by 89luca89** [comment]
Corrected, thanks a lot for the report!
