### ISSUE TITLE
Entering distrobox fails with OCI permission denied

### ISSUE THREAD

**Issue by aksdb** [89luca89/distrobox#90]
I am trying to run distrobox on an archlinux host.
Podman (rootless) works (for my use case). Quick test:

```
$ podman run --rm -it docker.io/archlinux
[root@77651569708b /]#
```

However, running distrobox fails:
```
$ distrobox-create --name arch-distrobox --image docker.io/archlinux:latest
7428edb75949ba6a41e06140fdefc1a7e81a155079affb5d2d478a412dc1bd79
Distrobox 'arch-distrobox' successfully created.
To enter, run:
        distrobox-enter --name arch-distrobox

$ distrobox-enter --name arch-distrobox
Error: unable to start container "7428edb75949ba6a41e06140fdefc1a7e81a155079affb5d2d478a412dc1bd79": make `/home/user/.local/share/containers/storage/overlay/419714cd4a1c80be92635f628cdc5b2df117b3b5c04fddbb6e40163d318a5b68/merged` private: Permission denied: OCI permission denied

An error occurred
```

What am I missing or what can I check to find out more?

**Comment by 89luca89** [comment]
hi @aksdb 

can you attach the logs of both `create` and `enter`? Just do the same commands you did with additionally `--verbose`

thanks!

**Comment by aksdb** [comment]
WTF. Ok, so if I run the creation with `--verbose`, it actually works. Without, it doesn't.

Logs:
[create_normal_enter_verbose.txt](https://github.com/89luca89/distrobox/files/7799210/create_normal_enter_verbose.txt)
[create_verbose_enter_normal.txt](https://github.com/89luca89/distrobox/files/7799211/create_verbose_enter_normal.txt)

I compared the two pods (via `podman inspect`) and noticed, that when created with `--verbose`, those parameters are missing:
```
                "--userns",
                "keep-id",
                "--ulimit",
                "host",
                "--mount",
                "type=devpts,destination=/dev/pts",
```

So I assembled the podman run command using all the parameters, and it looks like, that as soon as I add `--userns keep-id`, I get the error "private: Permission denied: OCI permission denied".

**Comment by 89luca89** [comment]
Seems to me something up with podman, probably this? 

https://github.com/containers/podman/issues/5914

**Comment by aksdb** [comment]
Looks very much like it :man_facepalming: .
It was a home directory permission problem.

So my problem is solved. Maybe still of interest to you could be my find that with `--verbose` the container is created differently, which seems weird to me (verbose should increase the log output, not change the behavior, to my understanding).

Anyway: thanks for pointing me to the right solution :smile:

**Comment by 89luca89** [comment]
Yea I cannot even reproduce that to be honest, using with/without verbose it is the same container inspect for me :shrug: 
What version of distrobox are you using and how did you install it?

**Comment by aksdb** [comment]
```
$ distrobox-create --version
distrobox: 1.2.8
```

Installed using pacman.

```
$ pacman -Qi distrobox
Name                     : distrobox
Version                  : 1.2.8-1
```

**Comment by 89luca89** [comment]
Pacman? I didn't even know someone packaged this :smile: 

Anyway yes now I can reproduce it's a bugfix I've not pushed yet sorry :stuck_out_tongue:

**Comment by EvilBoi123** [comment]
For future comers, to simplify stuff, you have to check your home directory permission

My previous home permission: 
`drwx------+ 1 cancel 100 4120 Jul 13 02:31 cancel/`

You should change it to same user group as in: 
`drwx------+ 1 cancel cancel 4120 Jul 13 02:31 cancel/`
