### ISSUE TITLE
[Suggestion] Flag to not rm custom home

### ISSUE THREAD

**Issue by bigpod98** [89luca89/distrobox#901]
**Is your feature request related to a problem? Please describe.**
To not remove custom home you have to go trought interactive pressing N.

**Describe the solution you'd like**
add a flag that disables removal of custom home without interactive input(usefull for scripts)

**Describe alternatives you've considered**
assemble might have this option but i have already existing workflows i would like to keep at this time

**Comment by misobarisic** [comment]
There is [this](https://github.com/89luca89/distrobox/blob/main/distrobox-rm#L25)

**Comment by 89luca89** [comment]
Exactly in newer versions the home is never removed unless `--rm-home` or the env variable is set
