### ISSUE TITLE
[Suggestion] Command to know wether you are in a container or on host

### ISSUE THREAD

**Issue by Josh9912** [89luca89/distrobox#903]
Hi, 

(This is my first issue or suggestion.) I am using distrobox for an Ubuntu 20.04 container in order to use ROS not in a VM, but I want to source files when starting the container. I am using zsh for both my container and my host, which is why I would like to have the option to only source specific files if I am in the container environment.

Kind regards

**Comment by 89luca89** [comment]
You can do this in various ways

Check if $CONTAINER_ID exists
With newer versions you can check if the file /run/.toolboxenv exists
Or you can generally check if you're in docker with /.dockerenv or podman with /run/.containerenv

No need for a command, I'd like to keep the amount of command and flags to the strict necessary
