### ISSUE TITLE
[Error] ln: failed to create symbolic link '/usr/local/bin/xdg-open': File exists

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#905]
**Describe the bug**
I tried to enter my centos-stream 8 distrobox.
But it now fails with the above error in the podman log.
Known issue?

**To Reproduce**
Not sure - might not be reproducible with a fresh box, but I can try.

**Expected behavior**
Shouldn't try to create symlink if it already exists.

**Logs**
[distrobox enter -v centos-stream8](https://github.com/89luca89/distrobox/files/12326649/c8.log)

[podman logs centos-stream8](https://github.com/89luca89/distrobox/files/12326652/c8-podman.log)

(How to inline the logs?)

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? podman-4.6.0
 - Which version of distrobox? distrobox-1.5.0.2

**Additional context**
Fedora Linux 38

**Comment by 89luca89** [comment]
Hi @juhp yea we needed to add `-f` the symlink, in order to execute even if a previous symlink was done

This is fixed now in last commit :+1:

**Comment by juhp** [comment]
Thanks!  Are you planning to do a new release?

**Comment by 89luca89** [comment]
Yes but first I'm reviewing the last bugs I want to try and fix some of them before the release

**Comment by biji** [comment]
just info, my old centos 6 container also won't start
