### ISSUE TITLE
[Error] code added in f62da50 tries to start the developer's `user@.service` session

### ISSUE THREAD

**Issue by 25pwn** [89luca89/distrobox#907]
distrobox-init tries to start [`user@luca-linux.service`](https://github.com/89luca89/distrobox/blob/b640b28b86db0c2e7dc7700da07dcf9ce63ba1be/distrobox-init#L1826) instead of the actual user's `user@.service`

**Comment by 89luca89** [comment]
Woops! Thanks for noticing! I've pushed a fix :+1:
