### ISSUE TITLE
Can't create box

### ISSUE THREAD

**Issue by BigmenPixel0** [89luca89/distrobox#92]
ArchLinux, distrobox uses podman
```
$ distrobox-create
Image not found.
Do you want to pull the image now? [y/N]: y
Trying to pull registry.fedoraproject.org/fedora-toolbox:35...
Getting image source signatures
Copying blob 76dc685b05ee done  
Copying blob cb18b2a53204 done  
Error: writing blob: adding layer with blob "sha256:76dc685b05eef986dc43ae2b364bad8843fa810e94339085a29b1fb89d5e9779": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument

An error occurred
```

**Comment by 89luca89** [comment]
Hi @BigmenPixel0 

Is rootless podman working and set up correctly?
Please take a look here #90 for some archlinux vs podman problems

**Comment by BigmenPixel0** [comment]
> Hi @BigmenPixel0
> 
> Is rootless podman working and set up correctly? Please take a look here #90 for some archlinux vs podman problems

Hi!. Configured podman as stated [here](https://wiki.archlinux.org/title/Podman#Rootless_Podman)
But I get another error:
```
$ distrobox-create --name archlinux --image docker.io/archlinux:latest
Image not found.
Do you want to pull the image now? [y/N]: y
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob 15dd5e5b37a1 done  
Copying blob a30a01d1eaab done  
Copying config c654a65ce6 done  
Writing manifest to image destination
Storing signatures
c654a65ce6c1f91d816f27f01d85b9d12a2e7f111857f02d5dd637c22361253c
Error: chown /home/bigmen/.local/share/containers/storage/overlay-containers/bf36e5e28c22a47307d2e0c3188a0ebe1d8bbc224a534ba58d8e5853d49104bf/userdata: invalid argument
```

**Comment by 89luca89** [comment]
@BigmenPixel0 this seems to be podman related
can you check if you find your solution in this issue?

https://github.com/containers/podman/issues/7106

**Comment by 89luca89** [comment]
And this also: https://bugs.archlinux.org/task/68029

**Comment by BigmenPixel0** [comment]
> @BigmenPixel0 this seems to be podman related can you check if you find your solution in this issue?
> 
> [containers/podman#7106](https://github.com/containers/podman/issues/7106)

It worked, but now I have a problem as in #90 :) (I will try to solve it)

**Comment by 89luca89** [comment]
Cool 😄 as I understand it should be a home permission problem, if there are news, head to that issue and reopen it, I'll close this one

**Comment by Freemason-12** [comment]
having same issue on centos stream 9

**Comment by Freemason-12** [comment]
> @BigmenPixel0 this seems to be podman related can you check if you find your solution in this issue?
> 
> [containers/podman#7106](https://github.com/containers/podman/issues/7106)
I did not userstand from here how the issue was fixed, sorry, I'm new to podman/docker thing.
I've installed distrobox from EPEL, if that was not obvious.

**Comment by Freemason-12** [comment]
in case if I'm misguided or commenting to to an unrelated issue, here's the error I'm getting:
```
[maksatr@localhost ~]$ distrobox create --image registry.fedoraproject.org/fedora-toolbox:38 --name testfedora
Image registry.fedoraproject.org/fedora-toolbox:38 not found.
Do you want to pull the image now? [Y/n]: 
Trying to pull registry.fedoraproject.org/fedora-toolbox:38...
Getting image source signatures
Copying blob 69930001c1dc done  
Copying blob 48031c47e5fb done  
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:48031c47e5fb53ed2c92b342e03e840e1caaf263a50b9899463b1cff16574698": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /var/spool/mail: invalid argument): exit status 1
```
