### ISSUE TITLE
[Discussion]when I use hyprland in distrobox,why some app can't connect to x11 server

### ISSUE THREAD

**Issue by DreamMaoMao** [89luca89/distrobox#920]

**Comment by DreamMaoMao** [comment]
╰─$ google-chrome
[3761:3761:0817/142426.459171:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[3761:3761:0817/142426.459220:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

**Comment by DreamMaoMao** [comment]
when i compare to my host , hyprland in distrobox  lost something:

1.miss X0
╰─$ ls -l /tmp/.X11-unix
total 0
srwxrwxr-x 1 gdm gdm 0 Aug 17 14:58 X1024=
srwxrwxr-x 1 gdm gdm 0 Aug 17 14:58 X1025=


2.miss Xwayland:0 process
Xwayland :0 -rootless -core -terminate 10 -listenfd 28 -listenfd 29 -displayfd 73 -wm 61

**Comment by DreamMaoMao** [comment]
![image](https://github.com/89luca89/distrobox/assets/30348075/13eec4d5-cdc2-4595-ba81-cf157ed03b6b)
i follow this to change user to $user  , but ,it did't work.
/tmp/.X11-unix  user still is gdm

**Comment by EternalWinter** [comment]
Hi @DreamMaoMao , did u solve this?

**Comment by DreamMaoMao** [comment]
> Hi @DreamMaoMao , did u solve this?嗨，你解决了这个问题吗？

no  i  give up

**Comment by Thanh9356** [comment]
Actually, you need to run it the command in root, a.k.a "sudo"

**Comment by kRHYME7** [comment]
Hi, I'm really curious, can we run the Whole hyprland session on distrobox? Any pointers will be helpful 🙏 as I can't find anything when I google it.

**Comment by auspex** [comment]
> ![image](https://github.com/89luca89/distrobox/assets/30348075/13eec4d5-cdc2-4595-ba81-cf157ed03b6b) i follow this to change user to $user , but ,it did't work. /tmp/.X11-unix user still is gdm

That instruction looked wrong to me. Surely the owner of /tmp/.x11-unix has to be changed **in** the distrobox, not the host. But I'm having similar problems trying to get KDE Plasma 6 in a distrobox

**Comment by Thanh9356** [comment]
> > ![image](https://github.com/89luca89/distrobox/assets/30348075/13eec4d5-cdc2-4595-ba81-cf157ed03b6b) i follow this to change user to $user , but ,it did't work. /tmp/.X11-unix user still is gdm
> 
> That instruction looked wrong to me. Surely the owner of /tmp/.x11-unix has to be changed **in** the distrobox, not the host. But I'm having similar problems trying to get KDE Plasma 6 in a distrobox

no, it actually needs to do on host, however, root is the owner so you need root permission to change owner, the tutorial is wrong in this way honestly, if you set in `profile.d`, it just does as user, which is not powerful enough to change owner
