### ISSUE TITLE
[Error] distrobox assemble with multiple volumes does not work

### ISSUE THREAD

**Issue by samuelba** [89luca89/distrobox#923]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**

When using `distrobox assemble` with multible volumes it doesn't work. There are different symptoms:

1.

```
volume="/etc/a:/etc/a /etc/b:/etc/b"
```

results in 

```
Creating 'abc' using image abc 	invalid reference format
 [ ERR ]
Error response from daemon: No such container: abc
Cannot find container abc
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:38? [Y/n]:
```

2.

```
volume="/etc/a:/etc/a" "/etc/b:/etc/b"
```

results in 

```
/usr/local/bin/distrobox-assemble: 15: /tmp/tmp.u2H5G5dt58: /etc/b:/etc/b: not found
```

3.

```
volume=/etc/a:/etc/a
volume=/etc/b:/etc/b
```

results in not mounting the first defined volume

4. 

```
volume="/etc/a:/etc/a"
volume="/etc/b:/etc/b"
```

results in 

```
Creating 'abc' using image abc 	invalid reference format
 [ ERR ]
Error response from daemon: No such container: abc
Cannot find container abc
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:38? [Y/n]:
```

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

I expect that at least one of the above approaches works.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman or docker? `docker`
 - Which version or podman or docker? `Docker version 24.0.5, build ced0996`
 - Which version of distrobox? `distrobox: 1.5.0.2`

**Additional context**

My workaround is to (ab)use `additional_flags` and define additional volumes there with 

```
additional_flags="--volume /etc/b:/etc/b"
```

**Comment by 89luca89** [comment]
Hi @samuelba 

Can you try with latest git version?

The first attempt should be the right one:

`volume="/tmp/test:/run/a /tmp/test2:/run/b"`

Just tried with latest git version and works both for docker and podman

**Comment by samuelba** [comment]
Hi @89luca89 

Yes, it works on latest main branch. However, multi-line `pre_init_hooks` are completely broken, it always adds double `&& &&` instead of only `&&`. Not sure if this is expected.

**Comment by 89luca89** [comment]
Thanks the && error has been fixed now
