### ISSUE TITLE
Integrate Sysbox as container runtime

### ISSUE THREAD

**Issue by qdrop17** [89luca89/distrobox#931]
We're interested in containerizing various workflows of our development into containers (not VMs!). But a lot of solutions we're using are reliant on systemd. This on the other hand has dependencies which are not natively covered by Docker.

https://github.com/nestybox/sysbox solves this dilemma and would enable far more capable (more native-like) Distroboxes while still leveraging the lightweightness of containers.

One could launch an almost native-like container inside a Distrobox.

It has a strong isolation still which would also help with https://github.com/89luca89/distrobox/issues/28

**Comment by 89luca89** [comment]
Very interesting! Didn't know of it, very cool!

I think you already can use it by using the `--additional-flags` to specify the runtime (-`-additional-flags "--runtime=sysbox-runc" `)

Also, chrck initful container, they should be mostly the same

`distrobox create --init --additional packages systemd --image registry.opensuse.org/opensuse/distrobox:latest`

That will create a container with systemd running as pid1 inside. Install docker and run it, you'll have a very similar result :+1:

**Comment by qdrop17** [comment]
nice, that's great. It's basically a super lightweight VM now :-)

**Comment by 89luca89** [comment]
@qdrop17 
With the latest commit, using `--unshare-all --init` will provide an isolation quite similar to what sysbox or lxc does 
Let me know if there is missing stuff!
