### ISSUE TITLE
[Error] The value for the SHELL variable was not found in the /etc/shells file

### ISSUE THREAD

**Issue by strangeh21** [89luca89/distrobox#932]
**Describe the bug**
Prevents launching of GUI applications such as Game Conqueror from within Distrobox. 

**To Reproduce**
1. `distrobox create -n archie -i docker.io/library/archlinux:latest`
2. `distrobox enter archie`
3. `sudo pacman -S gameconqueror`
4. `gameconqueror`

```
The value for the SHELL variable was not found in the /etc/shells file
This incident has been reported.
```

**Expected behavior**
This should launch Game Conqueror.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

podman logs unfortunately did not contain anything related to this issue. In fact it contained nothing at all after the install.
`podman logs archie > logs.log`
[logs.log](https://github.com/89luca89/distrobox/files/12402630/logs.log)

Here is the output of cat /etc/shells within the container:
```
[nix@archie ~]$ cat /etc/shells
# Pathnames of valid login shells.
# See shells(5) for details.
/bin/sh
/bin/bash
/bin/rbash
/usr/bin/rbash
[nix@archie ~]$ echo $SHELL
/run/current-system/sw/bin/bash
``` 

Here is the host OS shells.
```
[nix@nixos:~]$ cat /etc/shells
/run/current-system/sw/bin/bash
/run/current-system/sw/bin/sh
/nix/store/kxkdrxvc3da2dpsgikn8s2ml97h88m46-bash-interactive-5.2-p15/bin/bash
/nix/store/kxkdrxvc3da2dpsgikn8s2ml97h88m46-bash-interactive-5.2-p15/bin/sh
/bin/sh
[nix@nixos:~]$ echo $SHELL
/run/current-system/sw/bin/bash
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? Podman
 - Which version or podman or docker? 4.5.0
 - Which version of distrobox? 1.4.2.1

**Additional context**
This is on the distro NixOS 23.05. This might be a quirk with NixOS specifically, although I'm not sure. 
```
[nix@nixos:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.2775.720e61ed8de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

@luc14n0 Came up with the workaround to use prepend the `distrobox create` command with `SHELL=/bin/bash distrobox create`
At this point I get a new error that I assume is not related to shell. 
```
[nix@archie2 ~]$ gameconqueror
Error getting authority: Error initializing authority: Could not connect: No such file or directory
``

**Comment by 89luca89** [comment]
Hi @strangeh21 
Noticing you're using 1.4.2.1
This should be already fixed in 1.5.0.2 or if you use the latest git version
