### ISSUE TITLE
Steam UI opening and closing when exported as application but runs fine when ran in the terminal

### ISSUE THREAD

**Issue by blonde0091** [89luca89/distrobox#933]
**Describe the bug**
I have been having this issue for a bit with Steam when running the application in distrobox via it being exported by the ``distrobox-export`` command which would result in the steam client trying to load for one second then close itself but the app would still be running in the background then it will be a repeating cycle of opening and closing. But when ``steam`` is ran in the terminal inside the container (bazzite-arch) Steam runs perfectly fine and games work as normal.

**To Reproduce**
1. My setup is KDE on Fedora 38 Kinoite
2. Make a distrobox container with bazzite-arch or arch in general 
3. Export the application Steam
4. Run Steam via the exported app 
5. Running Steam in the terminal in the container would give the expected

**Expected behavior**
When Steam is launched via the exported app it should launch up the steam client like normal and run games

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

[logs.log](https://github.com/89luca89/distrobox/files/12434456/logs.log)

Steam running in the terminal in the container
[steamlogs.log](https://github.com/89luca89/distrobox/files/12434474/steamlogs.log)

**Desktop (please complete the following information):**
 - podman
 - podman 4.6.1
 - distrobox 1.5.0.2

**Additional context**

**Comment by 89luca89** [comment]
Hi @blonde0091 this has been already fixed in latest git version

**Comment by blonde0091** [comment]
Hello this is great to hear ngl I did forget about this issue 😆 but nice to see progression being made
