### ISSUE TITLE
[Error] Unable to install Appimage-based applications using Yay

### ISSUE THREAD

**Issue by sobychnyj** [89luca89/distrobox#937]
**Describe the bug**
I'm getting the following error:
```
==> Starting prepare()...
/home/srgb/homes/arch/.cache/yay/altair/PKGBUILD: line 22: /home/srgb/homes/arch/.cache/yay/altair/src/altair-5.2.2.AppImage: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: altair-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
altair - exit status 4
```
And unable to install Appimage-based applications using Yay.

**To Reproduce**
Inside an Arch-based Distrobox container run:
`yay -S altair`

**Expected behavior**
Application is installed.

**Logs**
[logs.txt](https://github.com/89luca89/distrobox/files/12446617/logs.txt)

**Desktop:**
 - Host: Linux Mint 21.2 Cinnamon
 - Container: Arch Linux (VERSION_ID=20230723.0.166908)
 - I'm using podman.
 - podman version 4.6.1
 - distrobox: 1.5.0.2

**Additional context**
 - I've also tried to install x2goclient which resulted in the same error.
 - Additionally, I've tried to perform the same actions in a freshly installed Vanilla OS using its `apx` (which, as I understand, is also based on the Distrobox) package manager and it resulted in the same error.

**Comment by 89luca89** [comment]
Not sure why, I'm unable to reproduce, it worked for me on archlinux:latest using both normal and custom homes, with and without systemd enabled

Can't reproduce
