### ISSUE TITLE
[Error] you must run docker inside a container!

### ISSUE THREAD

**Issue by tony1016** [89luca89/distrobox#938]
My host is  Alpine Linux 3.18.After installed distrobox,when I type command in host:
```
sudo docker ps
```
I got 
```
you must run docker inside a container!
```

I don't know why

**Comment by 89luca89** [comment]
This is because `sudo` is a shared command using `distrobox-host-exec`

You cannot use `sudo distrobox-host-exec` to run commands as sudo on the host, you need to use

`distrobox-host-exec sudo docker` if you want and it will work

**Comment by tony1016** [comment]
> distrobox-host-exec

I think you don't understand me.I execucte `sudo docker ps` on the host,not in distrobox
