### ISSUE TITLE
[Error] pipewire-alsa in Arch container expects different location of modules in NixOS host

### ISSUE THREAD

**Issue by kquote03** [89luca89/distrobox#939]
**Description**
The pipewire-alsa compatibility package tries to load the `libasound_module_ctl_pipewire.so` module from a location that does not exist on my NixOS host. It tries to load it from `/nix/store/8l55v7r9r8mzasz28k39x07d8r7zhf1r-alsa-lib-1.2.8/lib/alsa-lib/libasound_module_ctl_pipewire.so` while in fact it is in `/nix/store/bq02jnx1046kxp8iri9h0v1q6gzn6f5n-pipewire-0.3.71-lib/lib/alsa-lib/libasound_module_ctl_pipewire.so`

**To Reproduce**
1. Try to load any application that needs ALSA (eg: Davinci Resolve)
2. no audio
3. Try to run alsa mixer, fails (error in logs section)

**Expected behavior**
The module is loaded from the correct path

**Logs**
```
[user@archlinux-toolbox ~]$ alsamixer 
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_ctl_pipewire.so (/nix/store/8l55v7r9r8mzasz28k39x07d8r7zhf1r-alsa-lib-1.2.8/lib/alsa-lib/libasound_module_ctl_pipewire.so: cannot open shared object file: No such file or directory)
```

**Desktop (please complete the following information):**
 - Are you using podman or docker?
 - Podman
 - Which version:
 - podman version 4.5.0
 - Which version of distrobox?
 - distrobox: 1.4.2.1

Thank you

**Comment by 89luca89** [comment]
You need to install alsa inside the container
Running nix binaries from the nix host inside the container is not a supported/suggested thing anymore (new versions will skip the mount of /nix)

Try with git version, `/nix` will be absent, and you will need to install properly alsa in the container in order to have it's own libraries
