### ISSUE TITLE
[Error] no matching entries in passwd file - WSL2

### ISSUE THREAD

**Issue by a-cristi** [89luca89/distrobox#94]
**Describe the bug**

`distrobox-enter` stops working after a reboot.

**To Reproduce**

1. create a new distrobox: `distrobox-create --image docker.io/library/alpine:latest --name alpine` (I'm using Alpine as an example, it doesn't seem to matter which distribution is used)
2. enter it: `distrobox-enter --name alpine` - this works without any issues
3. exit the distrobox and reboot the host
4. try to enter it again, this time the command fails:

```console
$ distrobox-enter --name alpine
Error: unable to find user cristi-lx: no matching entries in passwd file

An error occurred
```

**Expected behavior**

`distrobox-enter` should work as before the host reboot.

**Logs**

- [create.log](https://github.com/89luca89/distrobox/files/7806319/create.log) - logs gathered from `distrobox-create`
- [enter_ok.log](https://github.com/89luca89/distrobox/files/7806321/enter_ok.log) - logs gathered from `distrobox-enter` when it works
- [exit.log](https://github.com/89luca89/distrobox/files/7806324/exit.log) - logs gathered when I exit the distrobox
- [enter_err.log](https://github.com/89luca89/distrobox/files/7806326/enter_err.log) - logs gathered from `distrogox-enter` when it does not work

**Desktop (please complete the following information):**

 - OS: Ubuntu Jammy Jellyfish (development branch) on Windows 10 x86_64 (kernel 5.10.60.1-microsoft-standard-WSL2)
 - Browser: none
 - Version: 1.2.10 (I'm assuming that this is the `distrobox-enter` version); podman version is 3.2.1

**Additional context**

If I look at `/etc/passwd` when `distrobox-enter` works, my user is there: `cristi-lx::1000:1000::/home/cristi-lx:/bin/sh`, but after I reboot the host and look at it with `podman run alpine cat /etc/passwd` it is no longer there.

This might be an issue with my setup. I've never used podman before so maybe I'm doing something wrong. I simply installed it via apt. Or maybe it is related to something WSL does wrong.

This is similar to #84, but the fix in #85 doesn't seem to have done anything for me.

**Comment by 89luca89** [comment]
Hi @a-cristi thank a lot for the report
So this is on WLS2 right?

I've never tested it, so it will be interesting to use this occasion to bugfix :smile: 

Anyway are you able to test it with docker too? I knkow that in WSL2 works well so at least we can rule out some podman-in-wsl2 issues

**Comment by a-cristi** [comment]
> Hi @a-cristi thank a lot for the report So this is on WLS2 right?
> 
> I've never tested it, so it will be interesting to use this occasion to bugfix 😄
> 
> Anyway are you able to test it with docker too? I knkow that in WSL2 works well so at least we can rule out some podman-in-wsl2 issues

Yes, it's WSL2. It's going to take a while until I can try to install docker, but I'll give it a try and update the issue (it may take a few days though).

**Comment by 89luca89** [comment]
No worries :smile: 

I'd give it a shot, but I don't have physical windows devices and I suspect WSL2 inside a VM (so nested VMs) will be a chore :sweat_smile:

Also can you attach the `podman logs --since 30s NAME_OF_CONTAINER`? 
I'd say to do this just after a reboot and after the `distrobox enter` that doesn't work 

(probably you can contatenate a `distrobox enter --name alpine && podman logs --since 30s alpine`

**Comment by a-cristi** [comment]
`distrobox enter --name alpine && podman logs --since 30s alpine` generates no logs (or I don't know where to look for them).

**Comment by 89luca89** [comment]
> `distrobox enter --name alpine && podman logs --since 30s alpine` generates no logs (or I don't know where to look for them).

OK let's check without the `--since 30s` maybe thats that

**Comment by a-cristi** [comment]
> OK let's check without the --since 30s maybe thats that

This time there are a few logs: [podman.log](https://github.com/89luca89/distrobox/files/7807789/podman.log)

**Comment by 89luca89** [comment]
> > OK let's check without the --since 30s maybe thats that
> 
> This time there are a few logs: [podman.log](https://github.com/89luca89/distrobox/files/7807789/podman.log)

Seems this was all successful
Which makes things harder 😆 

I'll  try to setup wsl2 on my win10 VM and try to reproduce

**Comment by 89luca89** [comment]
Ok Finally got Win10 with WSL2 working in VM :smile: 

Installed ubuntu 20.04, upgraded to 22.04
Installed podman

`distrobox-create` and `distrobox-enter` worked

After a reboot I get your same error.

Searching around I've found this: https://github.com/containers/podman/issues/12236

After adding to fstab:

`tmpfs /tmp tmpfs defaults 0 0`

And rebooting all works as expected :smile: :tada:

**Comment by 89luca89** [comment]
Played a bit on WSL2, couldn't get the graphical application working (nor on WSL2 itself, nor in the container)
I'd say the various distros work as expected after the `tmpfs` workaround is applied, we could add this as an additional note in the support table as a beta/unfinished support

**Comment by a-cristi** [comment]
So `/tmp` is not cleared in WSL. That's... concerning 😆 

Thanks for the quick help and for investigating this. I just checked the fix (using alpine and arch) and everything seems fine. I also tried to just remove the `/tmp/podman-run-1000/alive` file as discussed in that issue, and that also works sometimes. 

> Played a bit on WSL2, couldn't get the graphical application working (nor on WSL2 itself, nor in the container)

I'm not using any graphical applications at the moment, but I did in the past, and getting them working using the WSL2 version in Windows 10 is a bit complicated, and the end result is bad in my opinion (I was using virt-manager and it frequently froze). Windows 11 might make that easier as it officially supports graphical applications in WSL2. I have a Windows 11 VM, I can try to get WSL working in that in a few days and see if I manage to get things working.

**Comment by 89luca89** [comment]
Cool I'll just add this as early/beta support in the compatibility table and citing the workaround for podman :+1:

**Comment by a-cristi** [comment]
Just wanted to leave a quick update. I finally managed to test this on Windows 11 (sorry for the loooong delay), and it works. Here's me running Firefox inside Arch inside Ubuntu 22.04:

![image](https://user-images.githubusercontent.com/9511999/179530774-ec0885f4-92f7-4f80-a49d-e0aba2f8daca.png)

It also looks like the workaround is no longer needed (at least not for the Windows 11 + Ubuntu 22.04 combination).

**Comment by 89luca89** [comment]
Thanks, for now I've removed the wsl2 from the compatibility list, as i don't have w10/11 machines and easy way to test and check that everything works
