### ISSUE TITLE
Ubuntu icon not downloaded?

### ISSUE THREAD

**Issue by firefoxlover** [89luca89/distrobox#940]
The ubuntu container requests an icon called `ubuntu.svg`. Notingly all other icons I have in the `/home/user/.local/share/icons/distrobox/` directory are PNGs. 

In that folder there is no SVG, maybe there is no source? Weirdly I cant finde the Ubuntu icon for download anywhere (it will be included in every distro, okay)

Anyways, I made an SVG myself lol, you can have use if you want. I hereby give it to you under Creative Commons license, mention me if you want. Its a bit shitty but serves the purpose.

![ubuntu-selfmade](https://github.com/89luca89/distrobox/assets/78762110/5d6cf075-b0ac-4ee3-b588-dbfc47f0cd6e)

**Comment by 89luca89** [comment]
This works correctly for me for ubuntu on latest release

Cannot reproduce
