### ISSUE TITLE
[Error] Lost audio in Archlinux container with init system

### ISSUE THREAD

**Issue by Lin-Junhao** [89luca89/distrobox#943]
**Describe the bug**
No audio output in an Archlinux container with init system. Works in the same container created without `--init`.

**To Reproduce**
1. Create an initful Archlinux container with following commands:
```
$ distrobox create --image archlinux:latest --name test --init
$ distrobox enter test
```
2. Install Firefox
```
$ sudo pacman -Syu firefox
```
3. Play any YouTube video with sound

**Expected behavior**
Can hear sound.

**Logs**
https://0x0.st/H95p.log

**Desktop:**
- Host OS: SteamOS 3.4.8
- Container OS: Arch Linux
- Podman version: 4.5.1
- Distrobox version: https://github.com/89luca89/distrobox/commit/88732a5b1b4a1db0cd3b202a323b78459e88b122

**Additional context**
Might not be related but time zone is incorrect as well in Archlinux container with init system.

**Comment by Lin-Junhao** [comment]
I tested again with the latest version https://github.com/89luca89/distrobox/commit/b3e1037b58c47c3491ae900d44792e7c0b32635e and unfortunately the issue still persist. I don't know what other information I can provide. When I try to play videos in Firefox, I get this error:
```
[Child 5757, MediaDecoderStateMachine #1] WARNING: 7f3c08cfe5e0 Could not set cubeb stream name.: file /build/firefox/src/firefox-117.0/dom/media/AudioStream.cpp:321
```

**Comment by 89luca89** [comment]
Pushed a fix for this, now sound is working as intended
For pipewire, there is a workaround documented in the docs for the steamdeck, introduced in this commit: 16868794122db998d9e6f4d37cd1981420510df1
