### ISSUE TITLE
[Suggestion] distrobox-assemble - hooks after installing additional packages ?

### ISSUE THREAD

**Issue by lorduskordus** [89luca89/distrobox#944]
I love the concept of one .ini file to recreate my containers. I don't have to write scripts for that anymore.. almost. If I want to run a few commands which are going to involve the packages I'm adding, I can't do that.

Would it make sense, would it be possible to have hooks after the packages get installed, so we can use them right away, in the init phase ?

**Comment by 89luca89** [comment]
This seems to me overly complicating the thing

What you can do is just install your additional packages in your custom init_hooks instead
Or create custom docker images

We already have hooks for pre-package stuff, and post-package stuff, this will cover already 99% of use cases
For complicated stuff I think the user should look into either scripting or doing custom images, for the sake of keeping things simpler on the distrobox usability side
