### ISSUE TITLE
[Error] Warning: failed to bind mount /run/host/usr/share/zoneinfo/America/Caracas to /etc/localtime Error: An error occurred

### ISSUE THREAD

**Issue by AndreidForGit** [89luca89/distrobox#946]
Can't enter any of my containers for some reason,when I try to enter my containers using `distrobox enter container` it says `Warning: failed to bind mount /run/host/usr/share/zoneinfo/America/Caracas to /etc/localtime Error: An error occurred` when it try to `Setting up read-only mounts...` 

**To Reproduce**
I change my kernel from 6.1 to 5.15 to 6.4, then I update my system and now I can't open it any more. I guess these are the only relevant changes I did since the last time I use my containers.

**Expected behavior**
It should open my containers

**Logs**
[distrobox_verbose.txt](https://github.com/89luca89/distrobox/files/12481394/distrobox_verbose.txt)
[podman logs.txt](https://github.com/89luca89/distrobox/files/12481485/podman.logs.txt)

**Desktop (please complete the following information):**
 - I'm using podman 
 - podman version 4.6.1
 - distrobox version: 1.5.0.2

**Additional context**
I just create a new container and it works, but the old ones not. The last time I use them was like a week ago. I'm using Manjaro with the kernel 6.1.49-1-MANJARO

**Comment by 89luca89** [comment]
Hi @AndreidForGit 

can you provide a more complete log of the podman container?

Using `podman logs NAME  > newlog.log  2>&1` as the one posted is missing STDERR

**Comment by AndreidForGit** [comment]
[newlog.log](https://github.com/89luca89/distrobox/files/12531860/newlog.log)
Here is the output

**Comment by 89luca89** [comment]
It seems to me there is a problem with your podman installation
As the root user seems to be mapped to UID 1 instead of 0

Probably you'll need to perform a `podman system reset` which **WILL DELETE EVERYTHING**
And restarting from scratch will solve the issue

But this is not inherently a distrobox problem

**Comment by AndreidForGit** [comment]
That worked, thank you

**Comment by battlezone** [comment]
I am having the same issue: `Warning: failed to bind mount /run/host/usr/share/zoneinfo/Europe/Amsterdam to /etc/localtime`. The logs show: 
```
+ mount --rbind -o ro /run/host/usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
mount: /etc/localtime: filesystem was mounted, but any subsequent operation failed: Unknown error 5005.
+ printf Warning: failed to bind mount %s to %s\n /run/host/usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
Warning: failed to bind mount /run/host/usr/share/zoneinfo/Europe/Amsterdam to /etc/localtime
```

Full log [here](https://pastebin.com/dDUiydTY). Any help is appreciated.

Desktop:
Arch on 6.5.9-Zen kernel with ZFS
podman version 4.7.2
distrobox version: 1.5.0.2

**Comment by AndreidForGit** [comment]
It's probably the same problem that I had, use `podman system reset` to fix the error but keep in mind that this **will delete everything**

**Comment by battlezone** [comment]
I should have been more clear. I tried `podman system reset` as suggested but it didn't work. Also, I get the error when trying to enter a Ubuntu:22:04 container, but _not_ when I enter a Fedora:39 container.
