### ISSUE TITLE
After suspend / resume, containerized Steam can't launch games: bwrap: Can't bind mount /oldroot/etc/resolv.conf on /newroot/etc/resolv.conf

### ISSUE THREAD

**Issue by ximGBu4cyQss5P** [89luca89/distrobox#947]
I don't think this is a distrobox issue and I'm probably just configuring something incorrectly, but if I create a distrobox container for Steam, after a suspend / resume, Steam can no longer launch games and I get an error like this.

`bwrap: Can't bind mount /oldroot/etc/resolv.conf on /newroot/etc/resolv.conf: Unable to mount source on destination: No such file or directory`

Host: Tumbleweed
Container: Tumbleweed
distrobox: 1.5.0.2-1.1 (RPM)
podman: 4.6.1-2.1
crun: 1.8.6-1.1

Container created like: `distrobox create --image tumbleweed:latest --name steam --home ~/Containers/steam`

The error message from Steam was helpful and it seemed like resolv.conf was bind mounted in the container, so when NetworkManager updated /etc/resolv.conf after resuming from sleep, for some reason bubblewrap is freaking out.

I poked around to see if I could disable bind mounting resolv.conf, and found the `--dns=none` parameter for podman-create.  So I tried adding `--additional-flags "--dns=none"` to the distrobox create, but I get the same result.

I thought maybe it was something interesting with Tumbleweed containers, but I tried the bazzite-arch container and had the same problem.  Everything works perfectly until the system goes to sleep, then when it wakes up, games won't launch and I get the error above from Steam.

**Comment by KyleGospo** [comment]
Found a fix for this, create your box with `--unshare-netns`
