### ISSUE TITLE
Rootless Podman

### ISSUE THREAD

**Issue by ozky84** [89luca89/distrobox#948]
` Checking dependencies...
 Downloading...
 Unpacking...
 Installation successful!
 Shell scripts are located in /home/ozky/.local/bin
 Manpages are located in /home/ozky/.local/share/man/man1
 Checking dependencies...
 Fetching crun 1.8.7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2773k  100 2773k    0     0  1393k      0  0:00:01  0:00:01 --:--:-- 2004k
 Fetching podman 4.6.2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     27      0 --:--:-- --:--:-- --:--:--    27
 Unpacking Podman...
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`

There is something wrong with podman....

**Comment by basreclame** [comment]
I have the same issue. Is someone has a workaround that would be great (so podman will be installed in the home directory).
Maybe the install script can be set to the previous version of podman.

**Comment by ozky84** [comment]
Okay....Script should installs it to home directory anyway as it's rootless.....
First need to see what's is problem until revert any changes...
Problem seems to be packaging problem as gzip: stdin: not in gzip format....

**Comment by ozky84** [comment]
@89luca89 can you take look this?

**Comment by basreclame** [comment]
For the time being I used the previous install file (installs podman 4.5.1)
curl -s https://raw.githubusercontent.com/89luca89/distrobox/1.5.0.2/extras/install-podman | sh -s -- --prefix ~/.local

**Comment by ozky84** [comment]
Working but still need to solving main problem....
