### ISSUE TITLE
[Discussion] Bins exported by one container shadows bin in other containers

### ISSUE THREAD

**Issue by alexanderfast** [89luca89/distrobox#949]
I have the following ini file, two distroboxes, one with an additional package thats exported (which one doesnt matter):

```
[a]
image=ubuntu:22.04
additional_packages="patch"

[b]
image=ubuntu:22.04
```

Create:

```
$ distrobox assemble create --file distrobox.ini
$ distrobox enter a -- distrobox-export --bin /usr/bin/patch
```

On the host, i can use `patch` as expected. Works inside `a` as well. But if something were to try and make use of this program inside `b` it would fail. Even if that image would have that program installed. This is because PATH is inherited into the started container.

```
$ distrobox enter a -- patch --version
GNU patch 2.7.6
$ distrobox enter b -- patch --version                                              
/var/home/alex/.local/bin/patch: 7: exec: /usr/bin/patch: not found
```

Not sure if this is something in my shell or env that causes more things than intended to be brought in when I start distroboxes. But if this is the intended behavior, it strikes as odd. The ini file has support for making many containers at once, and all of them can export binaries to the host system. But that also means that they export, and shadow, bins to each other.

Unless youre really careful when you lay this out, I think the only way to make this practical is to have only one container that exports many things. Or many containers that doesnt export. But either feels like a sacrifice.

Im curious if this is a quirk, a bug, or intended behavior.

**Comment by 89luca89** [comment]
This has been fixed by commit: 69088f77e8cbc09b189be4e954ad8377ed33a018

This will be possible in future releases, for now if you need, use the git version
