### ISSUE TITLE
[Error] PAM account management error

### ISSUE THREAD

**Issue by jasonwoodson** [89luca89/distrobox#95]
I'm currently using tumbleweed and encountered an issue with upgrading and installing applications on operating systems other than the host OS. When tumbleweed is used in conjunction with distrobox, everything works flawlessly. I'm simply curious as to what I might do to alleviate this issue. I'm not sure where to begin when it comes to permission concerns with my PAM account. Log below shows login in Fedora but when attempt update, i get this error.

_tumbleweedxpshost@unknown6057180f332c:~> distrobox-enter --name fedora-toolbox-35
Starting container fedora-toolbox-35
run this command to follow along:
	podman logs -f fedora-toolbox-35
.
done!
[tumbleweedxpshost@fedora-toolbox-35 ~]$ sudo dnf update
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
[tumbleweedxpshost@fedora-toolbox-35 ~]$_

**Comment by 89luca89** [comment]
Hi @jasonwoodson 
Can you please include some logs?

If possible I'd say to create a whole new container (different name for example "test-debug")  and attach here the logs of the commands 

`distrobox create --verbose --name test-debug`
`distrobox start --name test-debug`
From the host run also
`podman logs test-debug`

Thanks!

**Comment by 89luca89** [comment]
@jasonwoodson is by any chance your user an LDAP user?

**Comment by jasonwoodson** [comment]
> @jasonwoodson is by any chance your user an LDAP user?

@89luca89 Fresh install of OpenSuse Tumbleweed on my laptop (Dell XPS 13)

**Comment by 89luca89** [comment]
@jasonwoodson thanks

Can you run a `podman logs  test-debug`?

**Comment by jasonwoodson** [comment]
> podman logs test-debug

tumbleweedxpshost@localhost:~> distrobox-enter --name test-debug
Starting container test-debug
run this command to follow along:
	podman logs -f test-debug
.2022-01-04T14:24:46.158219000-06:00 /usr/bin/mount
2022-01-04T14:24:46.158429000-06:00 /usr/bin/mount
2022-01-04T14:24:46.158616000-06:00 /usr/bin/passwd
2022-01-04T14:24:46.158744000-06:00 /usr/bin/sudo
2022-01-04T14:24:46.158921000-06:00 /usr/sbin/useradd
2022-01-04T14:24:46.159062000-06:00 /usr/sbin/usermod
2022-01-04T14:24:46.159183000-06:00 /usr/bin/bash
2022-01-04T14:24:46.307849000-06:00 Warning: there was a problem setting up the user
2022-01-04T14:24:46.324780000-06:00 Removing password for user tumbleweedxpshost.
2022-01-04T14:24:46.324974000-06:00 passwd: Error
2022-01-04T14:24:46.325185000-06:00 Error: An error occurred

An error occurred
tumbleweedxpshost@localhost:~> podman logs test-debug
+ '[' '!' -f /run/.containerenv ']'
+ '[' -z 1000 ']'
+ '[' -z /home/tumbleweedxpshost ']'
+ '[' -z tumbleweedxpshost ']'
+ '[' -z 1000 ']'
++ basename /bin/bash
+ shell_pkg=bash
+ command -v mount
/usr/bin/mount
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
/usr/bin/sudo
+ command -v useradd
/usr/sbin/useradd
+ command -v usermod
/usr/sbin/usermod
+ command -v bash
/usr/bin/bash
+ HOST_MOUNTS_RO='
	/etc/machine-id
	/var/lib/flatpak
	/var/lib/systemd/coredump
	/var/log/journal'
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/etc/machine-id /etc/machine-id ro
+ source_dir=/run/host/etc/machine-id
+ target_dir=/etc/machine-id
+ mount_flags=ro
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ touch /etc/machine-id
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/etc/machine-id /etc/machine-id
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/flatpak /var/lib/flatpak ro
+ source_dir=/run/host/var/lib/flatpak
+ target_dir=/var/lib/flatpak
+ mount_flags=ro
+ '[' -d /run/host/var/lib/flatpak ']'
+ '[' -d /run/host/var/lib/flatpak ']'
+ mkdir -p /var/lib/flatpak
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump ro
+ source_dir=/run/host/var/lib/systemd/coredump
+ target_dir=/var/lib/systemd/coredump
+ mount_flags=ro
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ mkdir -p /var/lib/systemd/coredump
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/log/journal /var/log/journal ro
+ source_dir=/run/host/var/log/journal
+ target_dir=/var/log/journal
+ mount_flags=ro
+ '[' -d /run/host/var/log/journal ']'
+ '[' -d /run/host/var/log/journal ']'
+ mkdir -p /var/log/journal
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/log/journal /var/log/journal
+ return 0
+ HOST_MOUNTS='
	/media
	/mnt
	/run/libvirt
	/run/media
	/run/systemd/journal
	/run/udev
	/srv
	/var/lib/libvirt
	/var/mnt'
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/media /media rw
+ source_dir=/run/host/media
+ target_dir=/media
+ mount_flags=rw
+ '[' -d /run/host/media ']'
+ '[' -f /run/host/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/mnt /mnt rw
+ source_dir=/run/host/mnt
+ target_dir=/mnt
+ mount_flags=rw
+ '[' -d /run/host/mnt ']'
+ '[' -d /run/host/mnt ']'
+ mkdir -p /mnt
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/mnt /mnt
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/libvirt /run/libvirt rw
+ source_dir=/run/host/run/libvirt
+ target_dir=/run/libvirt
+ mount_flags=rw
+ '[' -d /run/host/run/libvirt ']'
+ '[' -f /run/host/run/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/media /run/media rw
+ source_dir=/run/host/run/media
+ target_dir=/run/media
+ mount_flags=rw
+ '[' -d /run/host/run/media ']'
+ '[' -d /run/host/run/media ']'
+ mkdir -p /run/media
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/media /run/media
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/systemd/journal /run/systemd/journal rw
+ source_dir=/run/host/run/systemd/journal
+ target_dir=/run/systemd/journal
+ mount_flags=rw
+ '[' -d /run/host/run/systemd/journal ']'
+ '[' -d /run/host/run/systemd/journal ']'
+ mkdir -p /run/systemd/journal
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/systemd/journal /run/systemd/journal
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/udev /run/udev rw
+ source_dir=/run/host/run/udev
+ target_dir=/run/udev
+ mount_flags=rw
+ '[' -d /run/host/run/udev ']'
+ '[' -d /run/host/run/udev ']'
+ mkdir -p /run/udev
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/udev /run/udev
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/srv /srv rw
+ source_dir=/run/host/srv
+ target_dir=/srv
+ mount_flags=rw
+ '[' -d /run/host/srv ']'
+ '[' -d /run/host/srv ']'
+ mkdir -p /srv
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/srv /srv
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/lib/libvirt /var/lib/libvirt rw
+ source_dir=/run/host/var/lib/libvirt
+ target_dir=/var/lib/libvirt
+ mount_flags=rw
+ '[' -d /run/host/var/lib/libvirt ']'
+ '[' -f /run/host/var/lib/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/mnt /var/mnt rw
+ source_dir=/run/host/var/mnt
+ target_dir=/var/mnt
+ mount_flags=rw
+ '[' -d /run/host/var/mnt ']'
+ '[' -f /run/host/var/mnt ']'
+ return 0
++ find /run/host/run -name user -prune -o -type s -print
++ :
+ host_sockets='/run/host/run/NetworkManager/private-dhcp
/run/host/run/irqbalance/irqbalance638.sock
/run/host/run/pcscd/pcscd.comm
/run/host/run/dbus/system_bus_socket
/run/host/run/avahi-daemon/socket
/run/host/run/nscd/socket
/run/host/run/mcelog/mcelog-client
/run/host/run/cups/cups.sock
/run/host/run/udev/control
/run/host/run/systemd/io.system.ManagedOOM
/run/host/run/systemd/private
/run/host/run/systemd/journal/io.systemd.journal
/run/host/run/systemd/journal/stdout
/run/host/run/systemd/journal/socket
/run/host/run/systemd/journal/dev-log
/run/host/run/systemd/userdb/io.systemd.DynamicUser
/run/host/run/systemd/notify
/run/host/run/systemd/inaccessible/sock'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/NetworkManager/private-dhcp
++ sed 's|/run/host||g'
+ container_socket=/run/NetworkManager/private-dhcp
+ '[' '!' -S /run/NetworkManager/private-dhcp ']'
+ '[' '!' -L /run/NetworkManager/private-dhcp ']'
+ rm -f /run/NetworkManager/private-dhcp
++ dirname /run/NetworkManager/private-dhcp
+ mkdir -p /run/NetworkManager
+ ln -s /run/host/run/NetworkManager/private-dhcp /run/NetworkManager/private-dhcp
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/irqbalance/irqbalance638.sock
++ sed 's|/run/host||g'
+ container_socket=/run/irqbalance/irqbalance638.sock
+ '[' '!' -S /run/irqbalance/irqbalance638.sock ']'
+ '[' '!' -L /run/irqbalance/irqbalance638.sock ']'
+ rm -f /run/irqbalance/irqbalance638.sock
++ dirname /run/irqbalance/irqbalance638.sock
+ mkdir -p /run/irqbalance
+ ln -s /run/host/run/irqbalance/irqbalance638.sock /run/irqbalance/irqbalance638.sock
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/pcscd/pcscd.comm
++ sed 's|/run/host||g'
+ container_socket=/run/pcscd/pcscd.comm
+ '[' '!' -S /run/pcscd/pcscd.comm ']'
+ '[' '!' -L /run/pcscd/pcscd.comm ']'
+ rm -f /run/pcscd/pcscd.comm
++ dirname /run/pcscd/pcscd.comm
+ mkdir -p /run/pcscd
+ ln -s /run/host/run/pcscd/pcscd.comm /run/pcscd/pcscd.comm
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/dbus/system_bus_socket
++ sed 's|/run/host||g'
+ container_socket=/run/dbus/system_bus_socket
+ '[' '!' -S /run/dbus/system_bus_socket ']'
+ '[' '!' -L /run/dbus/system_bus_socket ']'
+ rm -f /run/dbus/system_bus_socket
++ dirname /run/dbus/system_bus_socket
+ mkdir -p /run/dbus
+ ln -s /run/host/run/dbus/system_bus_socket /run/dbus/system_bus_socket
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/avahi-daemon/socket
++ sed 's|/run/host||g'
+ container_socket=/run/avahi-daemon/socket
+ '[' '!' -S /run/avahi-daemon/socket ']'
+ '[' '!' -L /run/avahi-daemon/socket ']'
+ rm -f /run/avahi-daemon/socket
++ dirname /run/avahi-daemon/socket
+ mkdir -p /run/avahi-daemon
+ ln -s /run/host/run/avahi-daemon/socket /run/avahi-daemon/socket
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/nscd/socket
++ sed 's|/run/host||g'
+ container_socket=/run/nscd/socket
+ '[' '!' -S /run/nscd/socket ']'
+ '[' '!' -L /run/nscd/socket ']'
+ rm -f /run/nscd/socket
++ dirname /run/nscd/socket
+ mkdir -p /run/nscd
+ ln -s /run/host/run/nscd/socket /run/nscd/socket
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/mcelog/mcelog-client
++ sed 's|/run/host||g'
+ container_socket=/run/mcelog/mcelog-client
+ '[' '!' -S /run/mcelog/mcelog-client ']'
+ '[' '!' -L /run/mcelog/mcelog-client ']'
+ rm -f /run/mcelog/mcelog-client
++ dirname /run/mcelog/mcelog-client
+ mkdir -p /run/mcelog
+ ln -s /run/host/run/mcelog/mcelog-client /run/mcelog/mcelog-client
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/cups/cups.sock
++ sed 's|/run/host||g'
+ container_socket=/run/cups/cups.sock
+ '[' '!' -S /run/cups/cups.sock ']'
+ '[' '!' -L /run/cups/cups.sock ']'
+ rm -f /run/cups/cups.sock
++ dirname /run/cups/cups.sock
+ mkdir -p /run/cups
+ ln -s /run/host/run/cups/cups.sock /run/cups/cups.sock
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/udev/control
++ sed 's|/run/host||g'
+ container_socket=/run/udev/control
+ '[' '!' -S /run/udev/control ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/io.system.ManagedOOM
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/io.system.ManagedOOM
+ '[' '!' -S /run/systemd/io.system.ManagedOOM ']'
+ '[' '!' -L /run/systemd/io.system.ManagedOOM ']'
+ rm -f /run/systemd/io.system.ManagedOOM
++ dirname /run/systemd/io.system.ManagedOOM
+ mkdir -p /run/systemd
+ ln -s /run/host/run/systemd/io.system.ManagedOOM /run/systemd/io.system.ManagedOOM
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/private
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/private
+ '[' '!' -S /run/systemd/private ']'
+ '[' '!' -L /run/systemd/private ']'
+ rm -f /run/systemd/private
++ dirname /run/systemd/private
+ mkdir -p /run/systemd
+ ln -s /run/host/run/systemd/private /run/systemd/private
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/io.systemd.journal
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/io.systemd.journal
+ '[' '!' -S /run/systemd/journal/io.systemd.journal ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/stdout
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/stdout
+ '[' '!' -S /run/systemd/journal/stdout ']'
+ for host_socket in ${host_sockets}
++ sed 's|/run/host||g'
++ printf %s /run/host/run/systemd/journal/socket
+ container_socket=/run/systemd/journal/socket
+ '[' '!' -S /run/systemd/journal/socket ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/dev-log
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/dev-log
+ '[' '!' -S /run/systemd/journal/dev-log ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/userdb/io.systemd.DynamicUser
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/userdb/io.systemd.DynamicUser
+ '[' '!' -S /run/systemd/userdb/io.systemd.DynamicUser ']'
+ '[' '!' -L /run/systemd/userdb/io.systemd.DynamicUser ']'
+ rm -f /run/systemd/userdb/io.systemd.DynamicUser
++ dirname /run/systemd/userdb/io.systemd.DynamicUser
+ mkdir -p /run/systemd/userdb
+ ln -s /run/host/run/systemd/userdb/io.systemd.DynamicUser /run/systemd/userdb/io.systemd.DynamicUser
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/notify
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/notify
+ '[' '!' -S /run/systemd/notify ']'
+ '[' '!' -L /run/systemd/notify ']'
+ rm -f /run/systemd/notify
++ dirname /run/systemd/notify
+ mkdir -p /run/systemd
+ ln -s /run/host/run/systemd/notify /run/systemd/notify
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/inaccessible/sock
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/inaccessible/sock
+ '[' '!' -S /run/systemd/inaccessible/sock ']'
+ '[' '!' -L /run/systemd/inaccessible/sock ']'
+ rm -f /run/systemd/inaccessible/sock
++ dirname /run/systemd/inaccessible/sock
+ mkdir -p /run/systemd/inaccessible
+ ln -s /run/host/run/systemd/inaccessible/sock /run/systemd/inaccessible/sock
+ '[' -d /usr/lib/rpm/macros.d/ ']'
+ set +o xtrace
+ net_mounts=/tmp:/sys:/proc:/dev:/var/mnt:/var/lib/libvirt:/srv:/run/udev:/run/systemd/journal:/run/media:/run/libvirt:/mnt:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id
+ cat
+ grep -q 'Defaults !fqdn' /etc/sudoers
+ printf 'Defaults !fqdn\n'
+ grep -q 'tumbleweedxpshost ALL = (root) NOPASSWD:ALL' /etc/sudoers
+ printf '%s ALL = (root) NOPASSWD:ALL\n' tumbleweedxpshost
+ grep -q tumbleweedxpshost /etc/group
+ groupadd --force --gid 1000 tumbleweedxpshost
+ grep -q tumbleweedxpshost /etc/passwd
+ useradd --home-dir /home/tumbleweedxpshost --no-create-home --shell /bin/bash --uid 1000 --gid 1000 tumbleweedxpshost
useradd: user 'tumbleweedxpshost' already exists
+ printf 'Warning: there was a problem setting up the user\n'
Warning: there was a problem setting up the user
+ passwd --delete tumbleweedxpshost
Removing password for user tumbleweedxpshost.
passwd: Error
+ '[' 1 -ne 0 ']'
Error: An error occurred
+ printf 'Error: An error occurred\n'
+ '[' '!' -f /run/.containerenv ']'
+ '[' -z 1000 ']'
+ '[' -z /home/tumbleweedxpshost ']'
+ '[' -z tumbleweedxpshost ']'
+ '[' -z 1000 ']'
++ basename /bin/bash
+ shell_pkg=bash
+ command -v mount
/usr/bin/mount
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
/usr/bin/sudo
+ command -v useradd
/usr/sbin/useradd
+ command -v usermod
/usr/sbin/usermod
+ command -v bash
/usr/bin/bash
+ HOST_MOUNTS_RO='
	/etc/machine-id
	/var/lib/flatpak
	/var/lib/systemd/coredump
	/var/log/journal'
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/etc/machine-id /etc/machine-id ro
+ source_dir=/run/host/etc/machine-id
+ target_dir=/etc/machine-id
+ mount_flags=ro
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ touch /etc/machine-id
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/etc/machine-id /etc/machine-id
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/flatpak /var/lib/flatpak ro
+ source_dir=/run/host/var/lib/flatpak
+ target_dir=/var/lib/flatpak
+ mount_flags=ro
+ '[' -d /run/host/var/lib/flatpak ']'
+ '[' -d /run/host/var/lib/flatpak ']'
+ mkdir -p /var/lib/flatpak
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump ro
+ source_dir=/run/host/var/lib/systemd/coredump
+ target_dir=/var/lib/systemd/coredump
+ mount_flags=ro
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ mkdir -p /var/lib/systemd/coredump
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/log/journal /var/log/journal ro
+ source_dir=/run/host/var/log/journal
+ target_dir=/var/log/journal
+ mount_flags=ro
+ '[' -d /run/host/var/log/journal ']'
+ '[' -d /run/host/var/log/journal ']'
+ mkdir -p /var/log/journal
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/log/journal /var/log/journal
+ return 0
+ HOST_MOUNTS='
	/media
	/mnt
	/run/libvirt
	/run/media
	/run/systemd/journal
	/run/udev
	/srv
	/var/lib/libvirt
	/var/mnt'
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/media /media rw
+ source_dir=/run/host/media
+ target_dir=/media
+ mount_flags=rw
+ '[' -d /run/host/media ']'
+ '[' -f /run/host/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/mnt /mnt rw
+ source_dir=/run/host/mnt
+ target_dir=/mnt
+ mount_flags=rw
+ '[' -d /run/host/mnt ']'
+ '[' -d /run/host/mnt ']'
+ mkdir -p /mnt
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/mnt /mnt
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/libvirt /run/libvirt rw
+ source_dir=/run/host/run/libvirt
+ target_dir=/run/libvirt
+ mount_flags=rw
+ '[' -d /run/host/run/libvirt ']'
+ '[' -f /run/host/run/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/media /run/media rw
+ source_dir=/run/host/run/media
+ target_dir=/run/media
+ mount_flags=rw
+ '[' -d /run/host/run/media ']'
+ '[' -d /run/host/run/media ']'
+ mkdir -p /run/media
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/media /run/media
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/systemd/journal /run/systemd/journal rw
+ source_dir=/run/host/run/systemd/journal
+ target_dir=/run/systemd/journal
+ mount_flags=rw
+ '[' -d /run/host/run/systemd/journal ']'
+ '[' -d /run/host/run/systemd/journal ']'
+ mkdir -p /run/systemd/journal
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/systemd/journal /run/systemd/journal
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/udev /run/udev rw
+ source_dir=/run/host/run/udev
+ target_dir=/run/udev
+ mount_flags=rw
+ '[' -d /run/host/run/udev ']'
+ '[' -d /run/host/run/udev ']'
+ mkdir -p /run/udev
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/udev /run/udev
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/srv /srv rw
+ source_dir=/run/host/srv
+ target_dir=/srv
+ mount_flags=rw
+ '[' -d /run/host/srv ']'
+ '[' -d /run/host/srv ']'
+ mkdir -p /srv
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/srv /srv
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/lib/libvirt /var/lib/libvirt rw
+ source_dir=/run/host/var/lib/libvirt
+ target_dir=/var/lib/libvirt
+ mount_flags=rw
+ '[' -d /run/host/var/lib/libvirt ']'
+ '[' -f /run/host/var/lib/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/mnt /var/mnt rw
+ source_dir=/run/host/var/mnt
+ target_dir=/var/mnt
+ mount_flags=rw
+ '[' -d /run/host/var/mnt ']'
+ '[' -f /run/host/var/mnt ']'
+ return 0
++ find /run/host/run -name user -prune -o -type s -print
++ :
+ host_sockets='/run/host/run/NetworkManager/private-dhcp
/run/host/run/irqbalance/irqbalance638.sock
/run/host/run/pcscd/pcscd.comm
/run/host/run/dbus/system_bus_socket
/run/host/run/avahi-daemon/socket
/run/host/run/nscd/socket
/run/host/run/mcelog/mcelog-client
/run/host/run/cups/cups.sock
/run/host/run/udev/control
/run/host/run/systemd/io.system.ManagedOOM
/run/host/run/systemd/private
/run/host/run/systemd/journal/io.systemd.journal
/run/host/run/systemd/journal/stdout
/run/host/run/systemd/journal/socket
/run/host/run/systemd/journal/dev-log
/run/host/run/systemd/userdb/io.systemd.DynamicUser
/run/host/run/systemd/notify
/run/host/run/systemd/inaccessible/sock'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/NetworkManager/private-dhcp
++ sed 's|/run/host||g'
+ container_socket=/run/NetworkManager/private-dhcp
+ '[' '!' -S /run/NetworkManager/private-dhcp ']'
+ for host_socket in ${host_sockets}
++ sed 's|/run/host||g'
++ printf %s /run/host/run/irqbalance/irqbalance638.sock
+ container_socket=/run/irqbalance/irqbalance638.sock
+ '[' '!' -S /run/irqbalance/irqbalance638.sock ']'
+ for host_socket in ${host_sockets}
++ sed 's|/run/host||g'
++ printf %s /run/host/run/pcscd/pcscd.comm
+ container_socket=/run/pcscd/pcscd.comm
+ '[' '!' -S /run/pcscd/pcscd.comm ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/dbus/system_bus_socket
++ sed 's|/run/host||g'
+ container_socket=/run/dbus/system_bus_socket
+ '[' '!' -S /run/dbus/system_bus_socket ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/avahi-daemon/socket
++ sed 's|/run/host||g'
+ container_socket=/run/avahi-daemon/socket
+ '[' '!' -S /run/avahi-daemon/socket ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/nscd/socket
++ sed 's|/run/host||g'
+ container_socket=/run/nscd/socket
+ '[' '!' -S /run/nscd/socket ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/mcelog/mcelog-client
++ sed 's|/run/host||g'
+ container_socket=/run/mcelog/mcelog-client
+ '[' '!' -S /run/mcelog/mcelog-client ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/cups/cups.sock
++ sed 's|/run/host||g'
+ container_socket=/run/cups/cups.sock
+ '[' '!' -S /run/cups/cups.sock ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/udev/control
++ sed 's|/run/host||g'
+ container_socket=/run/udev/control
+ '[' '!' -S /run/udev/control ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/io.system.ManagedOOM
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/io.system.ManagedOOM
+ '[' '!' -S /run/systemd/io.system.ManagedOOM ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/private
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/private
+ '[' '!' -S /run/systemd/private ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/io.systemd.journal
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/io.systemd.journal
+ '[' '!' -S /run/systemd/journal/io.systemd.journal ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/stdout
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/stdout
+ '[' '!' -S /run/systemd/journal/stdout ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/socket
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/socket
+ '[' '!' -S /run/systemd/journal/socket ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/journal/dev-log
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/journal/dev-log
+ '[' '!' -S /run/systemd/journal/dev-log ']'
+ for host_socket in ${host_sockets}
++ sed 's|/run/host||g'
++ printf %s /run/host/run/systemd/userdb/io.systemd.DynamicUser
+ container_socket=/run/systemd/userdb/io.systemd.DynamicUser
+ '[' '!' -S /run/systemd/userdb/io.systemd.DynamicUser ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/notify
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/notify
+ '[' '!' -S /run/systemd/notify ']'
+ for host_socket in ${host_sockets}
++ printf %s /run/host/run/systemd/inaccessible/sock
++ sed 's|/run/host||g'
+ container_socket=/run/systemd/inaccessible/sock
+ '[' '!' -S /run/systemd/inaccessible/sock ']'
+ '[' -d /usr/lib/rpm/macros.d/ ']'
+ set +o xtrace
+ net_mounts=/tmp:/sys:/proc:/dev:/var/mnt:/var/lib/libvirt:/srv:/run/udev:/run/systemd/journal:/run/media:/run/libvirt:/mnt:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id
+ cat
+ grep -q 'Defaults !fqdn' /etc/sudoers
+ grep -q 'tumbleweedxpshost ALL = (root) NOPASSWD:ALL' /etc/sudoers
+ grep -q tumbleweedxpshost /etc/group
+ groupadd --force --gid 1000 tumbleweedxpshost
+ grep -q tumbleweedxpshost /etc/passwd
+ useradd --home-dir /home/tumbleweedxpshost --no-create-home --shell /bin/bash --uid 1000 --gid 1000 tumbleweedxpshost
useradd: user 'tumbleweedxpshost' already exists
+ printf 'Warning: there was a problem setting up the user\n'
Warning: there was a problem setting up the user
+ passwd --delete tumbleweedxpshost
Removing password for user tumbleweedxpshost.
passwd: Error
+ '[' 1 -ne 0 ']'
Error: An error occurred
+ printf 'Error: An error occurred\n'
tumbleweedxpshost@localhost:~>

**Comment by 89luca89** [comment]
Ok seems there is a little problem here, I can reproduce this on TW not on any other distribution strangely enough :smile: 

I've pushed a new commit that fixes that on my TW, can you check if it work for you too?
You'll need to reinstall distrobox and recreate the container as the `init` has to run again :+1:

**Comment by jasonwoodson** [comment]
> Ok seems there is a little problem here, I can reproduce this on TW not on any other distribution strangely enough smile
> 
> I've pushed a new commit that fixes that on my TW, can you check if it work for you too? You'll need to reinstall distrobox (from git and not the `curl` install) and recreate the container as the `init` has to run again +1

Looks like when attempting to uninstall, i get an error cannot remove '/usr/local/bindistrobox'. I look at the script to see if any typos but not sure why file path is not being detected.  Currently i do have all files in /usr/local/bin/distrobox.  Please see information below.

tumbleweedxpshost@localhost ~/D/distrobox (main)> sudo ./uninstall
rm: cannot remove '/usr/local/bindistrobox': No such file or directory

**Comment by 89luca89** [comment]
Hi @jasonwoodson sorry there was a typo in the script :sweat_smile: Fixed it, you can clone again from source and try again :+1:

**Comment by jasonwoodson** [comment]
> Hi @jasonwoodson sorry there was a typo in the script sweat_smile Fixed it, you can clone again from source and try again +1

Thanks for resolving the concerns with Tumbleweed.  At one point I thought I was losing it, but happy to see you were able to rectify a few bug concerns to keep this project thriving.  Once again thanks for all the support :1st_place_medal:   and as of now fedora is working as plan.  :+1: Hopefully should start testing other distro's here soon

**Comment by 89luca89** [comment]
Cool, closing this one then, cheers! 😄
