### ISSUE TITLE
[Suggestion] Add documentation for GUI apps

### ISSUE THREAD

**Issue by Rathmox** [89luca89/distrobox#950]
**Is your feature request related to a problem? Please describe.**
Some distros (Arch in my case) are not configured by default to allow GUI apps for distrobox. It requieres running: `xhost +si:localuser:$USER` which is not documented on the project.
And I want to run GUI apps on wayland but I can't find how to allow running apps without root.

**Describe the solution you'd like**
Add the documentation for GUI apps.

**Comment by Rathmox** [comment]
My issue for wayland was because of Weston window on X11, it works with no issues on KWin. It may be needed to test a few compositors to tell which one works.

**Comment by 89luca89** [comment]
Already present

https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes

**Comment by Rathmox** [comment]
Ok I see.
I expected it in the "Useful tips" page.
