### ISSUE TITLE
[Error] Unable to invoke graphical applications in host from inside a distrobox

### ISSUE THREAD

**Issue by comminutus** [89luca89/distrobox#952]
**Describe the bug**
Attempting to run `distrobox-host-exec flatpak run ...` doesn't open any application but the shell return status is 0.  When I try it with GVim the window flashes briefly and closes.

**To Reproduce**
1. Install a graphical application like VSCodium or GVim
2. Create a distrobox and enter it
3. Try to run `distrobox-host-exec flatpak run com.vscodium.codium` (also tried with GVim)

**Expected behavior**
The application should start on the host

**Logs**
```
+ '[' -z test ']'
+ '[' -z flatpak ']'
++ id -ru
+ '[' 1000 -ne 0 ']'
+ command -v sudo
+ sudo_command=sudo
+ command -v curl
+ download='curl -sLo'
+ command -v host-spawn
++ sort -V
++ head -n 1
+++ host-spawn --version
++ printf '%s\n%s\n' 1.4.2 1.5.0
+ '[' 1.4.2 '!=' 1.4.2 ']'
++ basename flatpak
+ '[' flatpak = xdg-open ']'
++ basename flatpak
+ '[' flatpak = gio ']'
+ '[' '!' -t 1 ']'
+ tty
+ host-spawn flatpak run com.vscodium.codium
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
+ exit 0
```

For GVim:
```
+ '[' -z test ']'
+ '[' -z flatpak ']'
++ id -ru
+ '[' 1000 -ne 0 ']'
+ command -v sudo
+ sudo_command=sudo
+ command -v curl
+ download='curl -sLo'
+ command -v host-spawn
++ sort -V
++ head -n 1
+++ host-spawn --version
++ printf '%s\n%s\n' 1.4.2 1.5.0
+ '[' 1.4.2 '!=' 1.4.2 ']'
++ basename flatpak
+ '[' flatpak = xdg-open ']'
++ basename flatpak
+ '[' flatpak = gio ']'
+ '[' '!' -t 1 ']'
+ tty
+ host-spawn flatpak run org.vim.Vim
+ exit 0
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.6.2
 - Which version of distrobox? 1.5.0.2

**Additional context**
I did read the documentation about compatibility here: https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes)  I tried running `xhost +si:localuser:$USER` on the host side but that didn't seem to have any effect.
 I'm running the latest Fedora Silverblue (Gnome 44.4)

**Comment by 89luca89** [comment]
Hi @comminutus 
Can you try using `host-spawn -no-pty flatpak run com.vscodium.codium`?

**Comment by comminutus** [comment]
@89luca89 this works for both `com.vscodium.codium` and `org.vim.Vim`! It looks like there's a ticket to add some programs to the blacklist for `-pty` (mentioned here https://github.com/1player/host-spawn/issues/12) .  Should flatpak be in that list?

Also, is there any nifty way to add non-pty based symlinks so that `ln -s /usr/bin/host-spawn /usr/local/bin/flatpak` would never use a pty? The only way to get around this that I can think of is by creating a custom script that does the proper `-no-pty` switch.

**Comment by 89luca89** [comment]
No sadly for now there is no way with the symlinks
You'll need to write either an alias or a wrapper script to pass the `-no-pty` flag

Marking as solved as this is not a distrobox bug
