### ISSUE TITLE
[Error] App in container set as default browser in Gnome not kept after reboot

### ISSUE THREAD

**Issue by valmar** [89luca89/distrobox#953]
**Describe the bug**

I have installed the Vivaldi Browser in a Distrobox container and exported the app to the host. I then set Vivaldi in the container as my default browser in Gnome Settings/Default Apps. Everything works perfectly until I reboot. After rebooting, the default browser is set to the choice I had before (Firefox)

**To Reproduce**
- Installl Vivaldi in a distrobox container
- Export the app with `distrobox-export --app vivaldi`
- Set the app as default browser in Gnome Setting
- Reboot

**Expected behavior**
- Vivaldi is still kept as default browser after rebooting.

**Desktop (please complete the following information):**
 - Using podman
 - Podman version 4.6.2
 - Distrobox: 1.5.0.2

**Additional context**
- Using Gnome 44 on Fedora 38

**Comment by 89luca89** [comment]
> I then set Vivaldi in the container as my default browser in Gnome Settings/Default Apps. Everything works perfectly until I reboot. After rebooting, the default browser is set to the choice I had before (Firefox)

Then it seems like a gnome-settings bug

**Comment by valmar** [comment]
It is entirely possible. But if I set the preference to another non-containerized browser, the preference is kept. That is why I filed the bug here. Perhaps gnome tries to validate the desktop file and it fails for some reason

**Comment by 89luca89** [comment]
Interesting, does maybe `journalctl` get you some errors or logs about this revert?

**Comment by valmar** [comment]
So, I cannot reproduce the problem anymore on any machine. Perhaps it was really a bug that was closed. I will close this for now and maybe reopen if the problem presents itself again and I can collect more information. Thank you!
