### ISSUE TITLE
[Discussion] Is there a way to escape `#` in distrobox.ini?

### ISSUE THREAD

**Issue by jkuester** [89luca89/distrobox#956]
Is there a way that I missed that allows for escaping the comment character (`#`) when used in the middle of a quoted string in a `distrobox.ini` file?

 I have this `distrobox.ini` file:
```.ini
[my_debian]
image=debian:12
additional_packages="chromium git python3-pip python3-setuptools python3-wheel xsltproc"
init_hooks="sudo python3 -m pip install --break-system-packages git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic"
```

Running the `distrobox-assemble create` command in the directory with that file results in the following error:

```
$ distrobox-assemble create
/tmp/tmp.m2ufOShp04: line 3: unexpected EOF while looking for matching `"'
 - Creating my_debian... 
Creating 'my_debian' using image debian:12       [ OK ]
Distrobox 'my_debian' successfully created.
To enter, run:

distrobox enter my_debian
```

Obviously, removing the `#` from my `init_hooks` makes the error go away (but breaks the command).  I tried escaping it using `\#`, but that did not resolve the issue.

**Comment by TheBicPen** [comment]
To help other people who might have this issue, it can also manifest as `Syntax error: Unterminated quoted string`. Update your distrobox installation to >= 1.6.0 and the issue should go away.

This distrobox.ini:
```
[asd]
image="ubuntu:22.04"
pre_init_hooks="sed -Ei 's/^#\ deb-src/deb-src/' /etc/apt/sources.list;"
```
...produces this error message:
```
$ distrobox-assemble create
distrobox-assemble: 3: /tmp/tmp.R4LVVIvqOJ: Syntax error: Unterminated quoted string
```
...on distrobox version 1.5.0.1
