### ISSUE TITLE
[Discussion] how to input chinese?

### ISSUE THREAD

**Issue by tony1016** [89luca89/distrobox#957]
I can use ibus or fcitx in host.But how can I input chinese in a distrobox app?I think it doesn't connect to the host input framework

**Comment by juhp** [comment]
Host ibus works for me on Fedora Workstation (GNOME)

**Comment by espio999** [comment]
This may help something.
Mozc (Japanese input) on distrobox + ibus on host, this combination works as 

https://impsbl.hatenablog.jp/entry/JapaneseInputOnClearLinuxWithMozc_en

**Comment by tony1016** [comment]
> This may help something. Mozc (Japanese input) on distrobox + ibus on host, this combination works as
> 
> https://impsbl.hatenablog.jp/entry/JapaneseInputOnClearLinuxWithMozc_en

Config in both host and container,I got it.but are there any method to use input in host directly?

**Comment by espio999** [comment]
> but are there any method to use input in host directly?

Do you mean installing framework and imput method only to host, and commonly use it between host and concainer?
If so, it may technically possible, though not realistic, I think.

Example, mozc and ibus-mozc are installed under /usr/lib.  Although Distrobox make /usr/lib on container transparent from host, /usr/lin on host is not transparent from container.  In other words, container can't access mozc and ibus on host.

**Comment by juhp** [comment]
You could provide more details perhaps?  Ubuntu?  Wayland? etc

**Comment by tony1016** [comment]
I'm not familiar with input framework.As I know,if I install framework both
on host and guest,then it should work.But I wonder if it possible to use
input framework on host to do input on a guest gui app

Jens Petersen ***@***.***> 于2023年9月14日周四 00:52写道：

**Comment by juhp** [comment]
(Yes I was asking for more details about your environment, otherwise it is a bit hard to help)

**Comment by tony1016** [comment]
> (Yes I was asking for more details about your environment, otherwise it is a bit hard to help)

When I set below in container
```
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
```

I can put the input method on,and I can get the candidate word,but I can't get the word in the input box.While these settins are work in LXD

**Comment by tony1016** [comment]
According to https://bbs.deepin.org/post/258005,it's because of locale problem.
So anyone need CJK input enable,Please do:
1.change GTK_IM_MODULE and QT_IM_MODULE to xim,like
```
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
```
2.enable locale in /etc/locale.gen and run `locale-gen` command 

That's it.
Thx everyone.

**Comment by juhp** [comment]
Alright thanks - so I assume you are using deepin?
I don't think XIM is ideal, but I guess it can work :+1: 

Like I wrote I can input with ibus on gtk4-demo-application and gtk3-demo-application in fedora-toolbox (haven't tested today with distrobox) without setting _any_ envvars... This is using Fedora 38 GNOME Wayland.

**Comment by tony1016** [comment]
> Alright thanks - so I assume you are using Deepin? I don't think XIM is ideal, but I guess it can work 👍
> 
> Like I wrote I can input with ibus on gtk4-demo-application and gtk3-demo-application in fedora-toolbox (haven't tested today with distrobox) without setting _any_ envvars... This is using Fedora 38 GNOME Wayland.

No,not deepin.I use alpine and debian.I just found solution in deepin bbs

**Comment by juhp** [comment]
Ok, I don't think we are at the bottom of this yet...

**Comment by I-Want-ToBelieve** [comment]
https://github.com/fcitx/fcitx5/discussions/990

**Comment by iHad168** [comment]
In **distrobox** enter
`export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/host/run/user/1000/bus && notify-send "hello host"`
