### ISSUE TITLE
[Discussion]: Running distrobox  on NixOS

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [89luca89/distrobox#958]
The idea of ​​distrobox is to integrate the host's home directory into the container system, but the configuration files in the NixOS home directory have many paths to /nix/store/ and /etc/profiles/per-user/, and these paths are not included in the container. It does not exist. If these paths are mounted into the container, there will be bigger problems. Is there any solution to get rid of this dilemma?

```fish
❯ distrobox enter archlinux
/nix/store/5wspmqhgsfs7dza9gcyrj5yxbyd00q7y-coreutils-9.3/bin/dircolors: /var/lib/libvirt/distrobox/home/archlinux/.dir_colors: No such file or directory
Ducklett

    ▄▀▄▀▄       
    ▀▀▀▀▀▄      
  ▄▀▀▀▀▀▀▀▀     
  ▀▀▀▀▀▀▀▀▀▀ ▄  
▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀ 
 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
   ▄▀▀▀▀▀▀▀▀▀▀▀▀
   ▀▀▀▀▀▀▀▀▀▀▀  
    ▀▀▀▀▀▀▀▀▀   
        ▀▀▀     

/etc/profiles/per-user/i.want.to.believe/bin/starship: command not found
/home/i.want.to.believe/.config/fish/config.fish (line 1): 
/etc/profiles/per-user/i.want.to.believe/bin/starship init fish
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
in command substitution
	called on line 65 of file /home/i.want.to.believe/.config/fish/config.fish
from sourcing file /home/i.want.to.believe/.config/fish/config.fish
	called during startup
/home/i.want.to.believe/.config/fish/config.fish (line 65): Unknown command
        eval (/etc/profiles/per-user/i.want.to.believe/bin/starship init fish)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file /home/i.want.to.believe/.config/fish/config.fish
	called during startup
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[I] i.want.to.believe@archlinux /h/i.want.to.believe> 
```

**Comment by I-Want-ToBelieve** [comment]
Is it possible to mount these paths as read-only?

**Comment by I-Want-ToBelieve** [comment]
This seems to allow archlinux to read and execute programs in nixos-specific paths. Since archlinux does not have write permissions on these paths, it will not affect nixos.

**Comment by I-Want-ToBelieve** [comment]
Another way is to see if home-manager is compatible with distrobox.
One form is that home-manager does not use distro-dependent paths, for example `/etc/profiles/per-user/i.want.to.believe/bin/starship` can be directly replaced by `starship`.

**Comment by I-Want-ToBelieve** [comment]
The last way I can think of is for distrobox to provide an option whether to integrate nixos home into archlinux

**Comment by 89luca89** [comment]
I think it probably is easier to just source certain things in your ~/.profile or ~/.bashrc or ~/.zshrc only if NOT in the container

For example:

```sh
if [ ! -e /run/.toolboxenv ]; then
     do_my_awesome_stuff_on_host
else
     do_other_stuff_in_container
fi
```

This way you only source stuff when needed

**Comment by tu-maurice** [comment]
I mean the issue at hand is that the host's PATH and probably a other environment variables as well are reused inside the container created by distrobox. I don't think you'd want that regardless of what distribution you're using distrobox on. Docker and podman don't reuse the environment by default, so why do these environment variables end up in the container?

**Comment by I-Want-ToBelieve** [comment]
This is more about the problem that the configuration files in the home directory use hard-coded host directories and these directories do not exist in the container. It should not be related to the issue of environment variables.

**Comment by I-Want-ToBelieve** [comment]
NixOS has non-fhs

Imagine if you use an archlinux container on a host running Ubuntu, then when the container is created, since the container reuses the host's home directory, and some software in the configuration files in the home directory does not exist in the container, it A command not found error will be reported, but this is easy to solve. I only need to install these missing software in the archlinux container, but this does not work in nixos. The path of nixos is not /usr/bin but Unique /nix/store and /etc/profiles/per-user

**Comment by I-Want-ToBelieve** [comment]
I thought of another way to use the host's home directory as lowerdir in overlayfs and the one that distrobox will use as updir

**Comment by tu-maurice** [comment]
> This is more about the problem that the configuration files(dotfiles) in the home directory use hard-coded host paths

You're right. The ticket's description is different from my issue. Please disregard.

**Comment by SadSock** [comment]
I have encountered this problem as well. As an immutable distribution, NixOS greatly needs Distrobox. Immutable distributions are becoming increasingly popular. 

This question currently have solution or not? Can through not mounting/home directory temporarily solve it?

**Comment by 89luca89** [comment]
This is less of a distrobox problem and more of a configuration problem
please refer to the nixos package maintainer for this
