### ISSUE TITLE
[Error] Couldn't get Pipewire working in distrobox

### ISSUE THREAD

**Issue by Lin-Junhao** [89luca89/distrobox#960]
**Describe the bug**
All applications using Pipewire don't have sound, including mpv with `--ao=pipewire` and Telegram Desktop. This issue can be reproduced in Archlinux and Fedora containers (and probably other containers as well but I haven't tested them all).

Having been using distrobox for a year now I can confirm that they worked before. Other applications like Firefox, VLC or mpv with `--ao=pulse` work.

I have filed a similar issue #943 before but it seems to only affect Pulseaudio with `--init` so opening this new issue.

**To Reproduce**
```
$ distrobox create -i fedora:38 -n test
$ distrobox enter test
$ sudo dnf install mpv
$ mpv /path/to/any/audio/file --ao=pipewire
```

**Expected behavior**
Can hear sound.

**Logs**
- Podman log: https://0x0.st/Hfau.log
- Pipewire error message:
```
9/8/23 12:24 PM	pipewire	pw.core: 0x5612873310d0: error -2 for resource 3: port_set_io failed: No such file or directory
9/8/23 12:24 PM	pipewire	mod.client-node: 0x5612874612d0: error seq:165 -2 (port_set_io failed: No such file or directory)
9/8/23 12:24 PM	pipewire	pw.core: 0x5612873310d0: error -2 for resource 3: port_set_io failed: No such file or directory
9/8/23 12:24 PM	pipewire	mod.client-node: 0x5612874612d0: error seq:167 -2 (port_set_io failed: No such file or directory)
9/8/23 12:24 PM	pipewire	pw.node: (mpv-72) running -> error (error changing node state: No such file or directory)
9/8/23 12:24 PM	pipewire	pw.core: 0x5612873310d0: error -2 for resource 3: port_set_io failed: No such file or directory
9/8/23 12:24 PM	pipewire	mod.client-node: 0x5612874612d0: error seq:175 -2 (port_set_io failed: No such file or directory)
9/8/23 12:24 PM	pipewire	pw.core: 0x5612873310d0: error -2 for resource 3: port_set_io failed: No such file or directory
9/8/23 12:24 PM	pipewire	mod.client-node: 0x5612874612d0: error seq:176 -2 (port_set_io failed: No such file or directory)
```

**Desktop**
- Host OS: SteamOS 3.4.10
- Container OS: Fedora 38
- Podman version: podman-launcher v0.0.1
- Distrobox version: https://github.com/89luca89/distrobox/commit/b3e1037b58c47c3491ae900d44792e7c0b32635e

**Comment by 89luca89** [comment]
Hi @Lin-Junhao 

Sadly I'm not able to fix this on SteamOS, I can reproduce on a SteamOS Virtual Machine
Pulseaudio works, pipewire doesn't

I've documented a workaround in this commit: 16868794122db998d9e6f4d37cd1981420510df1
This will let you setup distrobox in order to force the use of pulseaudio for application inside the container, and have working sound

**Comment by Lin-Junhao** [comment]
> Hi @Lin-Junhao
> 
> Sadly I'm not able to fix this on SteamOS, I can reproduce on a SteamOS Virtual Machine Pulseaudio works, pipewire doesn't
> 
> I've documented a workaround in this commit: [1686879](https://github.com/89luca89/distrobox/commit/16868794122db998d9e6f4d37cd1981420510df1) This will let you setup distrobox in order to force the use of pulseaudio for application inside the container, and have working sound

I can confirm that with the git version of distrobox it falls back from Pipewire to Pulseaudio, and Pulseaudio does have audio output in initful containers.

SteamOS is not a typical platform to host containers so thanks for looking into this.

**Comment by siqale** [comment]
Install vlc package in your sistem that all dependencies will be installed and pulse will be works fine.
