### ISSUE TITLE
Distrobox scripts add extra newline char

### ISSUE THREAD

**Issue by alexanderfast** [89luca89/distrobox#963]
**Describe the bug**
When a command is run through distrobox, extra characters are added to output.

**To Reproduce**
Compare the following two commands, which should output the same:

```
> echo foo | hexdump -c
0000000   f   o   o  \n
0000004
```

When distrobox is used it changes newline (the box in question is default fedora):

```
> distrobox enter tools -- echo foo | hexdump -c
0000000   f   o   o  \r  \n
0000005
```

**Expected behavior**
These should be the same. 

**Logs**

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.6.2
 - Which version of distrobox? 1.5.0.2

**Additional context**
The bug was found when using hashicorp vault from a distrobox to base64 encode credentials (which rendered them invalid). That usecase also introduced additional whitespace, but the repro case posted here is simpler.

I did a search in all issues for "newline" but found nothing. Feels odd that Im the first to run into this so its possible that theres a mistake in my setup.

**Comment by 89luca89** [comment]
This is fixed by latest commits
