### ISSUE TITLE
[Error] Container with init system won't run if using Docker

### ISSUE THREAD

**Issue by sqrt-7** [89luca89/distrobox#964]
**Describe the bug**
Creating a container with init system fails to start if the host uses docker.
Works fine if I replace docker with podman.
Non-init containers also work fine with docker.

**To Reproduce**
`distrobox create --root --image registry.opensuse.org/opensuse/distrobox:latest --name blah --additional-packages "systemd" --init --unshare-netns --unshare-ipc`

The result:
```
$ distrobox enter --root blah

Container blah is not running.
Starting container blah
run this command to follow along:

 sudo docker logs -f blah

 Starting container...                           [ OK ]
 Installing basic packages...                    [ OK ]
 Setting up read-only mounts...                  [ OK ]
 Setting up read-write mounts...                 [ OK ]
 Setting up host's sockets integration...        [ OK ]
 Integrating host's themes, icons, fonts...      [ OK ]
 Setting up package manager exceptions...        [ OK ]
 Setting up rpm exceptions...                    [ OK ]
 Setting up sudo...                              [ OK ]
 Setting up groups...                            [ OK ]
 Setting up package manager exceptions...        [ OK ]
 Setting up rpm exceptions...                    [ OK ]
 Setting up sudo...                              [ OK ]
 Setting up groups...                            [ OK ]
 Setting up users...                             [ OK ]
 Executing init hooks...                         [ OK ]
 Setting up init system...                       [ OK ]
 Executing init hooks...                         [ OK ]
 Setting up init system...                       [ OK ]
 Firing up init system...                        [ OK ]

Container Setup Complete!
Error response from daemon: Container -snip- is not running
```

**Expected behavior**
Container starts without any issues.

**Logs**
See attached.

**Desktop (please complete the following information):**
 - Are you using podman or docker? docker
 - Which version or podman or docker? 24.0.5-ce
 - Which version of distrobox? 1.5.0.2

**Comment by sqrt-7** [comment]
[logs.txt](https://github.com/89luca89/distrobox/files/12575500/out.txt)

**Comment by moritz-t-w** [comment]
bump

**Comment by 89luca89** [comment]
@moritz-t-w bumping won't magically give me more free time to work on the project :eyes: 

@sqrt-7 
![image](https://github.com/89luca89/distrobox/assets/598882/c4bab475-0a12-4dc5-b37b-4c1531c2cfae)

As you can see it works, so probably it's a bug already fixed in the git version
Try upgrading and recreating the boxes

**Comment by moritz-t-w** [comment]
@89luca89 I wasn't implying that, I just thought you hadn't seen it. Thanks for helping!

**Comment by sqrt-7** [comment]
> @moritz-t-w bumping won't magically give me more free time to work on the project 👀
> 
> @sqrt-7 ![image](https://user-images.githubusercontent.com/598882/268454842-c4bab475-0a12-4dc5-b37b-4c1531c2cfae.png)
> 
> As you can see it works, so probably it's a bug already fixed in the git version Try upgrading and recreating the boxes

Can confirm it works using the latest git version. Thanks.
