### ISSUE TITLE
[Error] tty problem with distrobox-export --bin

### ISSUE THREAD

**Issue by AlbertoFabbri93** [89luca89/distrobox#965]
**Describe the bug**
distrobox-export --bin breaks the git plugin of oh-my-bash. I am not expert enough to explain what is going on but @akinomyoga helped me solving the problem by adding the flag --no-tty to the distrobox-enter command found in the script created by the export command.

Here is a comment from @akinomyoga that I think can be particularly useful:
> I guess this is again a Distrobox matter related to the TTY settings. The TTY converts the newlines between `LF <-> CR LF` for terminals. The terminal basically accepts `CR LF` so the TTY sitting between the terminal and the application converts `LF -> CR LF` in the application-to-terminal stream. However, this time the recipient is not a terminal but another command, so the conversion shouldn't take place. This could also be reported to Distrobox later.

I am opening this bug because it could make sense to make `--no-tty` the default.

**To Reproduce**
1. Install oh-my-bash
2. Open a folder containing a git repository

**Expected behavior**
The command line prompt should not return any error or present any visual artifact.

**Desktop:**
 - podman 4.6.2
 - distrobox 1.5.0.2

**Related bugs**
ohmybash/oh-my-bash#413
ohmybash/oh-my-bash#464

**Comment by akinomyoga** [comment]
Here's @akinomyoga from the original reports in Oh My Bash. I'm not so familiar with the idea and design of Distrobox, but I guess we can consider enabling TTY only when the stdout is connected to a TTY. Whether the stdout is connected to a TTY can be tested using `[ -t 1 ]` ([as specified in the POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html#tag_20_128_05:~:text=%2Dt%C2%A0%20file_descriptor,not%20associated%20with%20a%20terminal.)). A possible change could be adding

```diff
 if [ -z "\${CONTAINER_ID}" ]; then 
-	exec "${DISTROBOX_ENTER_PATH:-"distrobox-enter"}" ${rootful} -n ${container_name} -- \
+	if [ -t 1 ]; then
+		_distrobox_tty_flag=
+	else
+		_distrobox_tty_flag=--no-tty
+	fi
+	exec "${DISTROBOX_ENTER_PATH:-"distrobox-enter"}" ${_distrobox_tty_flag} ${rootful} -n ${container_name} -- \
```

in the following part of `distrobox-export`:

https://github.com/89luca89/distrobox/blob/b3e1037b58c47c3491ae900d44792e7c0b32635e/distrobox-export#L253-L256

But I'm not sure if it would be accepted by the Distrobox maintainers. I don't have enough time to perform exhaustive research on the entire Distrobox codebase. I'd appreciate it if anyone from the Distrobox maintainers could provide any thoughts on this.

**Comment by alexanderfast** [comment]
This appears to be the same thing I reported in https://github.com/89luca89/distrobox/issues/963. The explanation here is much better, while the other issue has a simple way of triggering the error.

**Comment by alexanderfast** [comment]
Hunting around for the best place to add this there appears to already be similar logic [here](https://github.com/89luca89/distrobox/blob/main/distrobox-enter#L293):

```
	if [ "${headless}" -eq 0 ] && [ -t 0 ]; then
		result_command="${result_command}
			--tty"
	fi
```

And `headless` is 0 by default and [set to](https://github.com/89luca89/distrobox/blob/main/distrobox-enter#L150) 1 with `--no-tty`. This constructs the command sent to podman/docker.

Which is very similar to the suggested patch, which constructs the command sent to distrbox itself:

```
+	if [ -t 1 ]; then
+		_distrobox_tty_flag=
+	else
+		_distrobox_tty_flag=--no-tty
+	fi
```

Except that it's... inverse? Do I understand it right that only when `-t 1` is true we want to attach tty?

It is on the right track though, `-T` toggles the behavior in the way I want, I just cant figure out how to have it auto detected.

```
$ distrobox enter -T debian -- echo foo | hexdump -c
0000000   f   o   o  \n                                                
0000004

$ distrobox enter debian -- echo foo | hexdump -c 
0000000   f   o   o  \r  \n                                            
0000005
```

**Comment by 89luca89** [comment]
Hi @alexanderfast and @akinomyoga 

Thanks for debugging this! The right place was in `distrobox-enter` to detect the tty
I've pushed a fix should work now

**Comment by akinomyoga** [comment]
Thanks!

**Comment by 89luca89** [comment]
Thanks for reporting and investigating! :tada:

**Comment by alexanderfast** [comment]
I think this needs to be reopened. Though the specific case is fixed, running just "distrobox enter box" no longer has a prompt. Or maybe I should open that as a separate issue and regression.
