### ISSUE TITLE
[Error] Issues with systemd-homed

### ISSUE THREAD

**Issue by burrhole** [89luca89/distrobox#97]
**Describe the bug**
When using distrobox as a user created with systemd-homed, there are some issues. Rootless podman isn't working at all (relating I believe to https://github.com/containers/podman/issues/12590 and https://github.com/systemd/systemd/issues/21952 ), but even with "regular" podman, `sudo distrobox-enter --name opensuse-leap -- bash -l` fails with
```
Error: chdir `/home/burrhole`: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred
```
which does not seem to be an issue with podman itself, as `sudo podman exec -it opensuse-leap /bin/bash` drops into a shell as expected. This seems to be somewhat similar to #43 
**To Reproduce**
run `distrobox-enter` as a systemd-homed user, get the error

**Expected behavior**
distrobox enters the container as expected

**Logs**
[distrobox-verbose.txt](https://github.com/89luca89/distrobox/files/7814081/distrobox-verbose.txt)
[podman-logs.txt](https://github.com/89luca89/distrobox/files/7814082/podman-logs.txt)

**Desktop (please complete the following information):**
 - OS: Arch linux, fully up to date

**Additional context**
It might be a good idea to mention somewhere that rootless podman can't work on systemd-homed right now until something changes with homed. If there's anything else I can try or provide I'd be happy to. Thanks!

**Comment by 89luca89** [comment]
Hi @burrhole thanks for opening the issue
Yes until #12590 is fixed we cannot use rootless podman on systemd-homed users

What you did (`sudo distrobox [...]`) is not supported, as stated distrobox supports rootless podman or sudoless docker
`sudo podman exec -it opensuse-leap /bin/bash` is not a rootless podman hence it works as expected.

You could try using docker as a backend, set up as sudoless (adding yourself to `docker` group) and let me know if it works :+1:

**Comment by burrhole** [comment]
That does work! Apologies, I misunderstood that rootless podman/docker was a requirement (which seems a little silly now that I'm thinking about the purpose of distrobox); I think that I assumed it was a possibility given the options for systemwide and rootless installation. Thank you for your time and work on this project!

**Comment by 89luca89** [comment]
So it works with docker?

**Comment by burrhole** [comment]
It works as expected with docker; one thing that I noticed, which is probably not related to homed at all, is that exported apps don't seem to be able to use fonts correctly on my system, for example after exporting gedit from opensuse it looks like this
![image](https://user-images.githubusercontent.com/31171855/148206614-012a16dc-b1f4-41ec-bb2c-0196bbe98bd9.png)
but I can open another issue for that.

**Comment by 89luca89** [comment]
Yes those are missing fonts inside the container
Generally speaking this is more of an issue on how the dependency are handled in some systems than others (for example, on fedora, installing gedit will bring also all the needed fonts)

We could work around this, I've just pushed a new `init` feature to integrate with host's font, but obviously it would be better to sort out the missing dependency in the container if needed
