### ISSUE TITLE
[Error] creating distrobox with Fedora 38 image already used, no such file or directory

### ISSUE THREAD

**Issue by firefoxlover** [89luca89/distrobox#972]
I had this issue some more times I think.

1. I have a Distrobox that uses `quay.io/fedora/fedora:38` and it works normally, standard configs
2. I try to create a new one using this command:

```
distrobox create Test -i quay.io/fedora/fedora:38 --home /home/user/test
```

The dir "test" already exists. The error message is:

```
Creating 'Test' using image quay.io/fedora/fedora:38     Error: creating container storage: creating read-write layer with ID "8480cdc55e7f8c741a0a353be40ef87ded26d3810234a3bde3082aa0b7f94ed1": Stat /home/user/.local/share/containers/storage/overlay/ff7b8932bfbcaec31087986bfffc8beb480427309e57da74ff19c3b3ac6afadf/diff: no such file or directory
```

Now I tried the soon EOL Fedora 37 image and it worked normally, downloaded it and everything worked, the same using `registry.fedoraproject.org/fedora-toolbox:38`.

What is going on here?

**Comment by 89luca89** [comment]
Probably podman is having some problems
This has nothing to do with distrobox

Check your podman configuration, try to pull again the image
