### ISSUE TITLE
[Discussion] Is --unshare-all still a supported flag?

### ISSUE THREAD

**Issue by baskrahmer** [89luca89/distrobox#973]
I am trying to create a new development instance that has Docker access using [this tutorial](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-docker-inside-a-distrobox), however I have noticed that the `--unshare-all` flag no longer exists on the latest version.

Did it get removed? If so, how do I achieve the same result? Perhaps by unsharing the netns, ipc or both?

After I better understand how this works, I can update the documentation :)

**Comment by 89luca89** [comment]
You need the latest git version for that flag to work

Documentation on git always refers to the code on git
Documentation on the website refers to the latest release
