### ISSUE TITLE
[Error] Nested quotes missing on running distrobox-enter

### ISSUE THREAD

**Issue by randshell** [89luca89/distrobox#977]
**Describe the bug**
Nested single quotes or escaped double quotes in a `.ini` file to be used with `distrobox-assemble` are lost upon entering and initializing the container.

**To Reproduce**
1. Write a command with nested quotes in a `containers.ini` file, for example `pre_init_hooks="touch ~/test && sed -i '1s/^/1.1.1.1\n/' ~/test;"`.
2. Dry run `distrobox-assemble`:
```bash
/usr/bin/distrobox-create --yes --name kali-test --image kali-rolling:latest --init --home /home/user/distrobox-home --pre-init-hooks ": && touch ~/test && sed -i '1s/^/1.1.1.1\n/' ~/test;" --additional-packages "systemd libpam-systemd"
```
Notice the sed command being correctly parsed.

4. Run `distrobox-assemble` to create the container and then `distrobox-enter`:
```bash
 Starting container...                           [ OK ]
 Executing pre-init hooks...                     [ OK ]
```
However the `~/test` file is empty.

**Expected behavior**
The quotes are preserved inside commands, the same way they are shown in the dry run test.

**Logs**
<details>
<summary>podman logs:</summary>
<code>
+ [ -n : && touch ~/test && sed -i '1s/^/1.1.1.1\n/' ~/test; ]
+ printf distrobox: Executing pre-init hooks...\n
distrobox: Executing pre-init hooks...
+ eval : && touch ~/test && sed -i '1s/^/1.1.1.1\n/' ~/test;
+ :
+ touch /home/user/distrobox-home/test
+ sed -i 1s/^/1.1.1.1\n/ /home/user/distrobox-home/test
distrobox: Installing basic packages...
+ printf distrobox: Installing basic packages...\n
</code>
</details>

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 4.6.2
 - Which version of distrobox? 1.5.0.2
 - Which host distribution? Fedora
 - How did you install distrobox? Fedora Repository

**Comment by 89luca89** [comment]
Hi @randshell 

TBH your sed command doesn't work on a local shell in the first place so I'm not sure it's assembly fault here
Try also escaping the quotes if needed

But in my tests, the quotes are correctly preserved, similar to your test, I'm using sed here:

![image](https://github.com/89luca89/distrobox/assets/598882/b1cd04f8-992b-4720-82b6-57511dc7e616)

And it correctly replaced world/test in the file

**Comment by 89luca89** [comment]
Yes that is not possible to do, as /etc/resolv.conf is mounted from the host
It is for now not supported to have it different than the host, without also using `--unshare-netns` flag

**Comment by 89luca89** [comment]
Yes the umounting is just sed not working well with how podman mounts the /etc/resolv.conf

But with`--unshare-netns` you are free to modify the resolv.conf
