### ISSUE TITLE
[Discussion] How to persistent changes to /etc/resolv.conf

### ISSUE THREAD

**Issue by tony1016** [89luca89/distrobox#979]
I use --unshare-netns to create a network seperate container and set a local dns in /etc/resolv.conf,and it works.
But everytime it reboot,the chanage is missing.
How can I persistent this changes?

**Comment by 89luca89** [comment]
Either you need to add the hosts using podman/docker flags (so use `--additional-flags`) or set a pre-init hook that
will umount /etc/resolv.conf and place a custom one for you

For example

`distrobox create ... --unshare-netns --pre-init-hooks "umount /etc/resolv.conf && cp /home/your-name/my-resolv.conf /etc/resolv.conf"`

Something on those lines

**Comment by tony1016** [comment]
Thanks for the tip!

Luca Di Maio ***@***.***> 于2023年9月19日周二 07:11写道：
