### ISSUE TITLE
[Error] Can't launch apps within distrobox with desktop files

### ISSUE THREAD

**Issue by helium18** [89luca89/distrobox#98]
**Describe the bug**
Tried creating a desktop file for an app and also set up a keybinding to open gnome terminal with the distrobox profile and both of them do nothing. 
Gnome terminal opens up and then closes immediately. It doesn't happen with other profiles for some reason. 
I specified the entire path to distrobox (for the desktop shortcut) as well, still no avail.

**To Reproduce**
```
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- -p ~/path/to/directory
podman pull docker.io/library/archlinux:latest
distrobox-create --name arch --image archlinux:latest

distrobox-enter --name arch 
yay -S vscodium-bin

```
Create a desktop file with the [following](https://pastebin.com/58yDJbpC) specifications.
Paste it in `~/.local/share/applications`

AND

create a gnome terminal profile named arch
![](https://i.imgur.com/WXnCiKa.png)
Shell command: `/path/to/distrobox/distrobox-enter --name arch`

Then create a keybinding which executes the following command: `/usr/bin/gnome-terminal --window-with-profile=arch`

**Expected behavior**
The desktop file should open the app and the Keybinding should open gnome terminal with the required profile.

**[Logs](https://pastebin.com/8aAFk1Va)**

**Desktop (please complete the following information):**
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish

**Comment by 89luca89** [comment]
hi @helium18 

For the keyboard shortcut I use `gnome-terminal --tab-with-profile=PROFILE_NAME` and it works (at least on GNOME)

About vscode, did you use the integrated `distrobox export` for it?
In any case as explained here: http://distrobox.privatedns.org/usage.html

```
NOTE: some electron apps such as vscode and atom need additional flags to work from inside the container, use the --extra-flags option to provide a series of flags, for example:

distrobox-export --app atom --extra-flags "--foreground"
```

So just try adding the `--foreground` flag to the desktop file Exec

**Comment by helium18** [comment]
> About vscode, did you use the integrated distrobox export for it?
Nope. I'm just trying to open the app from distrobox. I don't intend to export it...

> Also about the opening/closing immediately issue, be sure the PATH where distrobox is installed is available to non-terminal sessions
Actually I'm new to Linux so I had just appended to the PATH in .bashrc. For the commands, I had specified the entire path to distrobox.

**Comment by helium18** [comment]
Also, thanks for the prompt response :)

**Comment by 89luca89** [comment]
> > About vscode, did you use the integrated distrobox export for it?
> 
> Nope. I'm just trying to open the app from distrobox. I don't intend to export it...
> 
> > Also about the opening/closing immediately issue, be sure the PATH where distrobox is installed is available to non-terminal sessions
> 
> Actually I'm new to Linux so I had just appended distrobox's location to the PATH in .bashrc. For the commands, I had specified the entire path to distrobox.

Yep that could be the problem

I'll show you an example for me, I've installed distrobox in this path and added it only to .bashrc:

`PATH=$PATH:/home/luca.di.maio/Projects/Personal/distrobox/`

If I start the application or the gnome-terminal that PATH will not be sourced (as it will not read the bashrc)

To make it work you can either:

- use a canonical PATH (so in /usr/local/bin, in ~/.local/bin, in /bin etc etc)
- add that PATH inside your ~/.profile or in /etc/profile and reboot the machine to resource it

**Comment by helium18** [comment]
> use a canonical PATH

So does this mean I have to reinstall it?

> add that PATH inside your ~/.profile or in /etc/profile and reboot the machine to resource it

Basically, the path to distrobox on my machine is `/home/helium/Vault/Programs/minivm`
I added this line to `~/.profile`: `PATH="/home/helium/Vault/Programs/minivm"`
And then restarted my computer. Unfortunately, the results are still the same...

Is this happening because I didn't install distrobox with sudo?

**Comment by 89luca89** [comment]
>  I added this line to ~/.profile: PATH="/home/helium/Vault/Programs/minivm"

The line should be 
`PATH="$PATH:/home/helium/Vault/Programs/minivm"`

> Is this happening because I didn't install distrobox with sudo?

There shouldn't be the need, there is `~/.local/bin` that is accessible without sudo
try reinstalling in that directory instead

Also in case it doesn't work, can you paste here the result of the command

`echo $PATH`?

**Comment by helium18** [comment]
> The line should be
`export PATH="$PATH:/home/helium/Vault/Programs/minivm"`

Still no avail :crying_cat_face: 

>Also in case it doesn't work, can you paste here the result of the command
`echo $PATH?`

`/home/helium/Vault/Programs/minivm:/home/helium/.local/bin:/home/helium/.cargo/bin:/home/helium/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

Also, these are the contents under `minivm`
`distrobox  distrobox-create  distrobox-enter  distrobox-export  distrobox-init  distrobox-list  distrobox-rm`

> There shouldn't be the need, there is ~/.local/bin that is accessible without sudo
try reinstalling in that directory instead

I will do that soon :+1:

**Comment by helium18** [comment]
Does gnome-terminal close because it's done executing[?](https://stackoverflow.com/questions/3512055/avoid-gnome-terminal-close-after-script-execution)

**Comment by 89luca89** [comment]
> > The line should be
> > `export PATH="$PATH:/home/helium/Vault/Programs/minivm"`
> 
> Still no avail crying_cat_face
> 
> > Also in case it doesn't work, can you paste here the result of the command
> > `echo $PATH?`
> 
> `/home/helium/Vault/Programs/minivm:/home/helium/.local/bin:/home/helium/.cargo/bin:/home/helium/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
> 
> Also, these are the contents under `minivm` `distrobox distrobox-create distrobox-enter distrobox-export distrobox-init distrobox-list distrobox-rm`
> 
> > There shouldn't be the need, there is ~/.local/bin that is accessible without sudo
> > try reinstalling in that directory instead
> 
> I will do that soon

Strange profile didn't work, anyway you have `/home/helium/.local/bin` in PATH, you should be able to just

`install /home/helium/.local/bin/`

> Does gnome-terminal close because it's done executing?

In your case with the problem in PATH, it closes because of the problem executing the process

**Comment by 89luca89** [comment]
@helium18 

as per last commit: https://github.com/89luca89/distrobox/commit/5f04416d4c3d2fbe7049814f49530e709bed7bd0

Now it should work in your custom path situation :smile: 

Can you try it? You should install it directly from git not from the `curl` installation method

**Comment by helium18** [comment]
AWESOME, THAT WORKED!!!!! :tada::tada::tada:
Thanks a lot for your help :smile_cat:

**Comment by 89luca89** [comment]
Cool stuff! Glad it worked 😄
