### ISSUE TITLE
[Suggestion] Ansible Support

### ISSUE THREAD

**Issue by jansenm** [89luca89/distrobox#981]
**Is your feature request related to a problem? Please describe.**
I am trying to setup development boxed with ansible. Everything is automated. Pasword, Software and more.

For a handful of tools i need Distroboxes because our distribution of choice does not support them in general or a specific required version (Yay for Enterprise Distributions).

I try to setup the distrobox automatically with ansible to minimize the pain for me and the developers. Unfortunately distrobox misjudges my intent and tells me sudo is not supported.

The problem is this code:

```
# SUDO_USER is a variable set by SUDO and can be used to check whether the script was called by it. Same thing for DOAS_USER, >set by DOAS.
if [ -n "${SUDO_USER}" ] || [ -n "${DOAS_USER}" ]; then
       printf >&2 "Running %s via SUDO/DOAS is not supported." "$(basename "${0}")"
      printf >&2 "Instead, please try using root=true property in the distrobox.ini file.\n"
     exit 1
fi

```
Now i lack understanding if what i do could work or not. But i would like to be able to do it:

Ansible logs into the machine as user ansible per ssh key. Then it does a sudo -u <otheruser != root> and executes the command »distrobox-assemble« for me. The boxes will be used exclusively from _otheruser_ later but for setup by ansible i will come in with sudo into the account.

Is that possible?

**Describe the solution you'd like**
I can use ansible to setup distroboxes.

**Describe alternatives you've considered**
None yet. The devs naturally could call the code manually afterwards but i would like to not have that. 

**Additional context**
-

**Comment by 89luca89** [comment]
Thanks for the issue, now the `sudo` check is only in case the user becomes root
