### ISSUE TITLE
[Suggestion] Request for Zsh Completion Support

### ISSUE THREAD

**Issue by davide-ruota** [89luca89/distrobox#984]
**Is your feature request related to a problem? Please describe.**
I'm submitting a feature request for Zsh completion support in Toolbox. Currently, Toolbox supports command completion for Bash, but as a Zsh user, I'd love to see the same level of support for Zsh as well.

**Describe the solution you'd like**
Ideally, a script would be created that provides auto-completion for Toolbox commands and options in Zsh, similar to the existing support for Bash.

**Additional context**
Bash completion for Toolbox already exists, so hopefully, it would be possible to create something similar for Zsh. This feature would be very beneficial for users who prefer using Zsh as their shell.

**Comment by xgpt** [comment]
Yes please!
