### ISSUE TITLE
[Error] distrobox-upgrade fails on openSUSE Tumbleweed if kiwi-systemdeps package is installed

### ISSUE THREAD

**Issue by marcosps** [89luca89/distrobox#987]
**Describe the bug**
kiwi-systemdeps package has DNF as a dependency. The code that handles the distrobox upgrade process checks if a package manager is available, and it tries apt, dnf, ..., and then zypper. Since dnf is installed, it tried to run it, but there are no repositories available(only the tool is installed).

**To Reproduce**
```sh
$ distrobox-create -i registry.opensuse.org/opensuse/distrobox:latest -n tumbleweed
$ distrobox enter tumbleweed
$ zypper install kiwi-systemdeps
 (exit distrobox)

$ distrobox upgrade tumbleweed
 Upgrading toolbox...                                                                                                                
distrobox: Installing basic packages...                                                                                              
/usr/bin/dnf                                                                                                                         
Error: There are no enabled repositories in "/etc/dnf/repos.d", "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".       
Error: An error occurred
```

**Expected behavior**
distrobox should invoke zypper by default when dealing with openSUSE distribution. Or at least check if the package manager has the repos configured since nowadays a distribution can install different package managers.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 podman
 - Which version of podman, docker or lilipod?
podman  4.6.2
 - Which version of distrobox?
 1.5.0.2
 - Which host distribution?
 openSUSE TW Slowroll (20230822)
 - How did you install distrobox?
 zypper

**Comment by 89luca89** [comment]
I think this is a double of #744 

kiwi-systemdeps installs dnf, and then distrobox detects that

We can move the discussion to that issue
