### ISSUE TITLE
[Suggestion] `distrobox-export` should have the ability to export an app without the label "on containername"

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#992]
**Is your feature request related to a problem? Please describe.**
I am unable to export apps without the label after that

**Describe the solution you'd like**
A `--no-label` flag or `--nl` would be nice so you can export without the label

**Describe alternatives you've considered**
You could edit the `.desktop` files yourself but that is quite a hassle

**Additional context**
Would be useful to have an app exported with just the app name and no other labels

**Comment by 89luca89** [comment]
Just use the `--export-label` flag, and set it to a space

`distrobox-export --app foo --export-label " "`

And it works

![image](https://github.com/89luca89/distrobox/assets/598882/b0e83aee-f0dd-44ca-b39f-be89f0a2ea76)

**Comment by dnkmmr69420** [comment]
oh thank you. this should be added to documentation

**Comment by dnkmmr69420** [comment]
There is a problem with that, some spaces were added at the end so the application name won't be completely in the center @89luca89
