### ISSUE TITLE
[Error] Distrobox hostname issues freezing the system

### ISSUE THREAD

**Issue by scuba3198** [89luca89/distrobox#994]
**Describe the bug**
For some reasons graphical applications seems to freeze the system in general in distrobox containers but afterwards it recovers. The issue seems to be caused by the hostname. When the hostname is set for example as “teufort” graphical apps freeze after awhile or when interacting with the menus. When the hostname is the LAN address (192.168.1.10) it doesn’t freeze at all.

**To Reproduce**
Use KDE Plasma. I use Kubuntu LTS.

**Expected behavior**
App should be smooth. When I set my hostname to local LAN, the containerized app runs smooth with zero hiccups.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? podman version 3.4.4
 - Which version of distrobox? 1.5.0.2
 - Which host distribution? Kubuntu 22.04 
 - How did you install distrobox? PPA

**Additional context**
[here is a recording demonstrating the problem: ](https://streamable.com/vxc4dz)

**Comment by Mattheish** [comment]
This [issue for toolbox](https://github.com/containers/toolbox/issues/1059) might be related.

**Comment by DaniyalAhmadSE** [comment]
I just started using Distrobox and cannot figure what exactly is the solution.

**Comment by 89luca89** [comment]
Thanks @Mattheish for the report

This seems to be unique to KDE, as (from my tests) stuff like i3/sway, XFCE and GNOME do not suffer from this

Are you able to provide some logs from the KDE session so that I can try to find a solution?
Thanks!

**Comment by DaniyalAhmadSE** [comment]
@89luca89 What fixed it for me was to add ```my_containername.my_hostname``` to the ```/etc/hosts``` file of the host. But It's more of a workaround since I would need to do this for each container/distrobox that I create.

**Comment by sandorex** [comment]
Since d26a926ff71304409b469c2272c9607266a3beb5 you can use `--hostname` argument to set the hostname to your host hostname when creating a container, also referenced in [useful tips](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#enable-ssh-x-forwarding-when-ssh-ing-in-a-distrobox)

**Comment by 89luca89** [comment]
For this I've now reopened the discussion #62 

The idea is to default to host's username for the container, and use $CONTAINER_ID for default prompt

Let's discuss in that issue for the impact of this change on workflows and/or breakages that this could lead

**Comment by s1nistr4** [comment]
Please reopen. This is a severe issue that makes it impossible to use distrobox practically. It should be the top issue.
