### ISSUE TITLE
[Discussion] Add user inside distrobox to group that only exists in the container.

### ISSUE THREAD

**Issue by raldone01** [89luca89/distrobox#997]
I would like to add my host user to a group that only exists in the distrobox.
How are gids translated?
How can I achieve this?

```
HOST>getent group | grep abuild
HOST>groups
video uucp lp wheel main
HOST>distrobox enter alpine
ALPINE>groups
main nobody nobody nobody nobody
ALPINE>getent group | grep abuild
abuild:x:300:main
ALPINE>sudo usermod -aG abuild $(whoami) # does not persist and not work in general
```

**Comment by 89luca89** [comment]
You'll need to "login" the user again to take it effect

![image](https://github.com/89luca89/distrobox/assets/598882/d297d20f-4c1e-49d9-a8ae-abaf6e859133)

**Comment by raldone01** [comment]
I see thanks!

**Comment by AesaraB** [comment]
Is there any way to make this persist?

**Comment by xtexChooser** [comment]
Is there any way to add groups since `distrobox enter`?

**Comment by HugLifeTiZ** [comment]
This is also not working for me, and the sudo workaround doesn't work. I get the following error message: `Sorry, user tiz is not allowed to execute '/bin/bash' as tiz on alpine.Stealth.`

**Comment by raldone01** [comment]
I can't reopen this issue.
So if this affects you you should create a new one and link this one.
