### ISSUE TITLE
[Error] Distrobox assemble deletes custom home directory

### ISSUE THREAD

**Issue by hunger** [89luca89/distrobox#998]
**Describe the bug**

I created a `distribox.ini` file with a system I would like to have. I pointed it to a custom home directory in that configuration. The image was not as I had expected it to be, so I twiddled with the configuration and did `distrobox assemble create --replace`. This deleted my custom homedir with about 100GB of data in it (I do have backaups, no worry). I find any tool that claims to assemble a container and ends up hosing a part of my home directory really frustrating.

**To Reproduce**

Describe any distrobox in distrobox.ini with a custom home directory, then run:

```sh
distrobox assemble create
distrobox assemble create --replace
```

Check the custom home directory: All its contents is gone now (the directory itself is still there).

**Expected behavior**

I expect a tool that claims to set up a container will not nuke a significant chunk of my data -- without asking and without me having explicitly opted into having my stuff removed!

`distrobox rm` does have a the `--rm-home` flag to explicitly ask it to delete the home dir, I would have expected `distrobox.ini` to have some flag to ask it to delete the home directory as well -- with it being *OFF* by default.

**Logs**

None

**Desktop (please complete the following information):**

 - I configured distrobox to use podman
 - `podman version 4.6.2`
 - `distrobox: 1.5.0.2`
 - Opensuse MicroOS Aeon
 - Distrobox came pre-installed by the distribution

**Additional context**

None

**Comment by misobarisic** [comment]
I believe it has been fixed [here,](https://github.com/89luca89/distrobox/commit/e18e01844e71d38af9b5cd67ac0e49d81cd735d2)

Try using the latest git version.

**Comment by 89luca89** [comment]
Yes this is fixed in got version
